### ISSUE TITLE
add possibility of defining keyboard shortcuts

### ISSUE THREAD

**Issue by mromanello** [inception-project/inception#1041]
**Is your feature request related to a problem? Please describe.**

In the context of the [impresso project](http://impresso-project.ch) we are conducting a pretty large annotation campaign (on historical newspaper materials) entirely based on INCEpTION as an annotation environment. 

We realised that having to select each annotation type with the mouse (for a larger number of annotations) takes up a considerable amount of time. 

**Describe the solution you'd like**

Having the possibility of defining keyboard shortcuts (at a user- or project-level) for certain types of annotations (i.e. named entities in our case) would be extremely helpful. E.g. a shortcut would map the letter `p` to the NE type `Person`.

**Describe alternatives you've considered**

Just accept that it takes longer :)

**Comment by reckart** [comment]
Could you describe the actions the user should take in more detail? It seems to me that having hot-keys to select certain layers doesn't solve your problem because you still need to mark the text with the mouse.

**Comment by reckart** [comment]
Normally, I would expect that you have a single named entity layer and that you specify the type of named entity using a feature. So my expected workflow would be:

1. user selects layer **Named entity**
2. user marks mention of entity in the text
3. cursor automatically jumps to the feature editor in the right sidebar where the type of entity can be specified
4. user starts typing (e.g. `P`) and the auto-complete selects the first available tag with starting with *P*, e.g. *Person*
5. user presses enter
6. go back to step 2.

Here, there is no need to switch between layers.

**Comment by mromanello** [comment]
Yes, I had in mind the same workflow with only one difference:

4. user hit the keystroke ctrl+P (*) which automatically selects the Person entity (pressing enter is not necessary).

(*) this shortcut has been defined in the settings, where each Value in an annotation layer may get assigned a different shortcut; such shortcuts can be defined e.g. for the most frequent entities. Defined shortcuts should probably be displayed in the entity dropdown alongside the value.

**Comment by mromanello** [comment]
@reckart just wondering if you had a chance to look at this? If you need more details on the scenario we had in mind just let me know.

**Comment by reckart** [comment]
To be honest, at the moment, I do not see a benefit of pressing `CTRL-P` over `P + ENTER`.

**Comment by mromanello** [comment]
Well, the main benefit is having only to press a keystroke combination without having to select the text field, start typing and then select from the dropdown.

**Comment by reckart** [comment]
When you mark a span with the mouse, the focus should jump automatically into the input field of the dropdown. When you press "p", the first item with "p" (Person) should automatically get selected (i.e. there should be no extra effort to select from the dropdown). When you press enter, the selection should be applied. Does that work for you?

**Comment by mromanello** [comment]
This works well for us. Perhaps the need for keyboard shortcuts comes from our NE tagset, that is fairly larger than others, due to an annotation scheme with components. 

Only for location, for example, we have the following possibilities:
- `loc.add.elec`
- `loc.add.phys`
- `loc.adm.nat`
- `loc.adm.reg`
- `loc.adm.sup`
- `loc.adm.town`

I don't want to specify a shortcut for each, but only for the more frequent ones:
- `loc.adm.nat` => CTRL+N
- `loc.adm.reg` => CTRL+R
- `loc.adm.town` => => CTRL+T

In this case, your workflow won't work, whereas the keyboard shortcut would spare the annotator having to go through the options in the long-ish dropdown. Does this make sense to you?

**Comment by reckart** [comment]
Do you actually have ambiguities in the last component (i.e. does e.g. `town` appear in multiple branches of your "ontology")?

**Comment by mromanello** [comment]
Only in a few cases, e.g. `org.adm` and `loc.adm.*`

**Comment by reckart** [comment]
Have you considered sparing your annotators from the prefix, e.g. by modelling this feature via a small KB e.g.:

```
loc (concept)
  adm (concept)
     reg (instance) -> label "reg (loc)" 
org (concept)
  adm (concept)
     reg (instance) -> label "reg (org)" 
```

So when the user would enter "reg" (which the user can probably do faster than positioning the fingers for an `CTRL-L`), the choice might already be restricted to two options which then could very quickly be selected using cursor down+ enter.

**Comment by jcklie** [comment]
[LionBridge](https://lionbridge.ai/), an annotation-as-a-service company, has this nice gif on their website 

https://lionbridge.ai/wp-content/uploads/2019/06/services_workbench-entity-annotation.gif
![image](https://user-images.githubusercontent.com/934600/60800809-1dd19c80-a176-11e9-957d-e80b9f078e01.png)

**Comment by reckart** [comment]
Let's set this UI annotates on the Named Entity layer. Then it has only one layer with only one feature (entity type). Our UI must be able to deal with layers that have multiple features - or we would need a way to somehow lock it down to one particular feature.

So let's say for example we have the Named Entity layer which has two features (identifier and value). The user "locks in" to the value feature. Once this is done, the editor for the identifier could disappear and a faster editor for the value feature could appear, e.g. one which would offer hotkeys for the first 10 tags. Would that make sense?

**Comment by mromanello** [comment]
thanks @jcklie, the LionBridge UI is very slick and provides exactly the sort of shortcutting I had in mind when I opened this issue!

@reckart It makes totally sense to me. Up to 9-10 favourite tags seems to me a good number (it's quite unlikely the number of most often used tags will be higher than that..).

Should you make any progress with this, I'll be more than happy to test it ;)

**Comment by mromanello** [comment]
@reckart is there any chance that this feature will be implemented in future releases?
