### ISSUE TITLE
Dealing with many results in search sidebar 

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#1054]
**Is your feature request related to a problem? Please describe.**
For queries with a large number of results, it takes very long to popular the sidebar and if becomes tedious to scroll in it.

**Describe the solution you'd like**
Here are some ideas:

- a hard limit of results to be shown in the sidebar (e.g. 1000 or 10000 -- maybe configurable by server admin)
- paging, e.g. showing 100 (proper paging, i.e. by re-issuing query when switching pages...)
- use a tree or somehow otherwise collapse the results such that first only documents are shown and the hits in side the documents appear when expanding a particular document

**Describe alternatives you've considered**
I put all alternatives that came to mind above.

**Comment by MdeBoer95** [comment]
@reckart for the DataProvider that feeds the paging components in the UI I need the total number of results. I would do this by querying with mtas and subsequently iterate over the results just counting how many results we have and caching this value for future calls of the DataProvider's ```size()``` method. So basically an (almost) empty loop over the mtas results to find out the size. An alternative where we don't need the total number of results would be a scrollbar that loads new items when the user scrolls to the bottom. But I find the 'classic' paging i.e. something like ```< << 1 2 3 ... >> >``` is a much more convenient way to navigate. So I would sacrifice performance for a more convenient UI here. Let me know if you agree or disagree with my approach.

Regarding the annotation of search results:
Should we limit the selection of search results to annotate to the currently displayed page or should we keep track of all selections of all pages that the user has loaded before as well?

**Comment by reckart** [comment]
I think having the empty loop which counts should be sufficient for the moment. So I agree with your opinion.

I'd tend towards not limiting to the current page. GitHub does e.g. limit selections in the issues list to the current page and I tend to find this annoying.
