### ISSUE TITLE
Creating relations between named entities crashes

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#1067]
**Describe the bug**
Creating relations between named entities crashes

**To Reproduce**
1. Create two named entites, draw a relation

**Expected behavior**
It should not allow me to do that, especially it should not crash.

**Please complete the following information:**
 - Version and build ID: 538b7cf06b18825a54722620f6281765e4457544
 - Browser: Chrome

**Additional context**

<div>
<h1>Unexpected RuntimeException</h1>
<table><tbody><tr><td><pre><span><p>Last cause: null<br>WicketMessage: Couldn't find component behavior.</p><p></p></span></pre></td></tr></tbody></table>

<div>
<h2>Stacktrace</h2>
<table><tbody><tr><td><pre><span class="markup"><p>Root cause:</p><p>java.lang.ArrayIndexOutOfBoundsException</p><p>Complete stack:</p><p>org.apache.wicket.WicketRuntimeException: Couldn't find component behavior.<br>     at org.apache.wicket.core.request.handler.ListenerRequestHandler.invokeListener(ListenerRequestHandler.java:226)<br>     at org.apache.wicket.core.request.handler.ListenerRequestHandler.respond(ListenerRequestHandler.java:208)<br>     at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:914)<br>     at org.apache.wicket.request.RequestHandlerExecutor.execute(RequestHandlerExecutor.java:65)<br>     at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:282)<br>     at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:253)<br>     at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:221)<br>     at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:275)</p><p></p></span></pre></td></tr></tbody></table>
</div>

<p>

</p>

</div>

**Comment by reckart** [comment]
Requires upstream fix: https://github.com/webanno/webanno/issues/1272
