### ISSUE TITLE
PDF editor annotations not reacting

### ISSUE THREAD

**Issue by wpmp** [inception-project/inception#1081]
**Describe the bug**
In some cases span annotation knobs and relations in the PDF editor are not responding to any interaction.
Neither hovering nor clicking on it is working.
It seems to happen when the annotation is overlapped by another annotation.
However it doesn't always produce this behavior.

**To Reproduce**
1. Open a PDF document in the PDF editor
2. Create a span annotation in one line
3. Create another span annotation in the line below directly under the first annotation.
4. Knob of second annotation might not respond

**Expected behavior**
Span annotation knob and relations should always react when hovered or clicked.

**Screenshots**
Used PDF document: https://aclweb.org/anthology/L18-1175
![unreactive-span-knob](https://user-images.githubusercontent.com/5390724/55289174-44d44180-53c3-11e9-86c3-4030cc922583.gif)
![unreactive-relation](https://user-images.githubusercontent.com/5390724/55289178-47cf3200-53c3-11e9-8141-647171b39deb.gif)

**Please complete the following information:**
 - Version and build ID:  0.9.0-SNAPSHOT (2019-03-30 13:13:11, build 27391004409d33da4da95540dbe7524fbb01c108)
 - OS: Linux
 - Browser: Google Chrome

**Additional context**
Maybe this could have something to do with z-level of the html elements or something like that.

**Comment by reckart** [comment]
I have removed the screenshot since it contained personal information. Please choose another example.

**Comment by wpmp** [comment]
I am very sorry, didn't think about this, I was too focused on the problem...

**Comment by reckart** [comment]
Seems to happen sometimes(?) after accepting an annotation suggestion...

**Comment by reckart** [comment]
Unclear if this still happens with the new PDF editor we have since v24.0.

**Comment by reckart** [comment]
Did not observe this anymore since the switch to the new PDF editor in v24.0 - so assuming this is fixed now.
