### ISSUE TITLE
PDF editor annotation details

### ISSUE THREAD

**Issue by wpmp** [inception-project/inception#1083]
**Is your feature request related to a problem? Please describe.**
Brat editor shows detailed information when hovering over annotations.
The PDF editor currently only shows some labels important for recommendations, e.g. to know which POS tag the recommendation is about.
Other information is missing

**Describe the solution you'd like**
PDF editor shows detailed information in a similar manner like brat editor does.

**Comment by reckart** [comment]
Duplicate of https://github.com/inception-project/inception/issues/985
