### ISSUE TITLE
Editor settings in PDF editor

### ISSUE THREAD

**Issue by wpmp** [inception-project/inception#1086]
**Is your feature request related to a problem? Please describe.**
Some editor settings, for example `page size,` have no effect on the PDF editor.
Also the page panel does not effect the PDF editor.

**Describe the solution you'd like**
Those settings should not be usable or visible in the PDF editor

**Comment by wpmp** [comment]
Requires webanno/webanno#1339

**Comment by wpmp** [comment]
@reckart should we leave this one open, too?
Pagination is removed, however page size setting is still available.
However I guess the page size can stay even though it has no effect on the PDF editor, what do you think?

**Comment by reckart** [comment]
You mean teh page size setting in the preferences dialog, right? I guess that is negligible for the time being. So we can close this one.

**Comment by reckart** [comment]
Duplicate of https://github.com/inception-project/inception/issues/1418.

**Comment by wpmp** [comment]
Yes
