### ISSUE TITLE
Render spans across page  boundaries in PDF editor

### ISSUE THREAD

**Issue by wpmp** [inception-project/inception#1087]
**Is your feature request related to a problem? Please describe.**
Currently a span annotation that exists across PDF page boundaries does not render properly.
It renders only on the page it begins but does not continue to the next page.

**Describe the solution you'd like**
The span should be rendered completely.
This could be done by splitting the span into multiple annotations, one span for each page it covers.
They should then behave as one annotation.
Such annotations then could have only one knob at the first span.

**Comment by reckart** [comment]
Fixed along with #1088.
