### ISSUE TITLE
PDF Editor Viewport undefined

### ISSUE THREAD

**Issue by wpmp** [inception-project/inception#1089]
**Describe the bug**
Sometimes when opening a PDF document in the PDF editor it states `TypeError: Cannot read property 'viewport' of undefined`.
However when clicking on `close` and triggering rendering of annotations the editor just works fine.
I don't know yet how to reproduce with a 100% chance and whats the exact problem.

**To Reproduce**
1. Open a PDF in PDF editor
2. Open another PDF in PDF editor
3. Repeat till error occurs
4. Changing to Brat editor and back to PDF editor also sometimes triggers this error

**Expected behavior**
This error should not occur.

**Screenshots**
![2019-04-01-003718_482x174_scrot](https://user-images.githubusercontent.com/5390724/55296200-6d395b80-5416-11e9-80dd-8031849618d3.png)

```
[Log] Trace
	Console Evaluation (Console Evaluation 1:3)
	evaluateWithScopeExtension
	_evaluateOn
	_evaluateAndWrap
	mergeRects (pdfanno.page.bundle.js:1:71145)
	newInstance (pdfanno.core.bundle.js:1:211601)
	(anonymous function) (pdfanno.core.bundle.js:1:233674)
	forEach
	(anonymous function) (pdfanno.core.bundle.js:1:233578)
	forEach
	importAnnotations041 (pdfanno.core.bundle.js:1:233533)
	(anonymous function) (pdfanno.core.bundle.js:1:232828)
	forEach
	(anonymous function) (pdfanno.core.bundle.js:1:232556)
	initializePromise
	Promise
	importAnnotations (pdfanno.core.bundle.js:1:232451)
	importAnnotation (pdfanno.page.bundle.js:80:20669)
	importAnnotation
	(anonymous function) (Anonymous Script 1 (line 1186:18318))
	Eval Code (Anonymous Script 1 (line 1186:18395))
	eval
	(anonymous function) (wicket-ajax-jquery.js:1008)
	run (wicket-ajax-jquery.js:148)
	proxy (jquery-2.2.4.js:497)
	processNext (wicket-ajax-jquery.js:163)
	start (wicket-ajax-jquery.js:175)
	complete (wicket-ajax-jquery.js:738)
	fire (jquery-2.2.4.js:3187)
	fireWith (jquery-2.2.4.js:3317)
	done (jquery-2.2.4.js:8772)
	(anonymous function) (jquery-2.2.4.js:9123)
```

**Please complete the following information:**
 - Version and build ID: 0.9.0-SNAPSHOT
 - OS: Linux
 - Browser: Google Chrome

**Comment by reckart** [comment]
It looks to me as if this problem happens when pdf.js is still trying to load/render the PDF while we already try to push annotations into the UI.
