### ISSUE TITLE
Searching for KB resource when creating statements has blank suggestion entries

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#1096]
**Describe the bug**
The suggestion list for type has blank entries

**To Reproduce**
1. Create a wine KB
2. Create a new concept
3. Try to change the type to Wine

**Expected behavior**
List does not contain blank entries

**Screenshots**
![image](https://user-images.githubusercontent.com/934600/55407866-230fc180-555f-11e9-88ad-071606965a93.png)

**Please complete the following information:**
 - Version and build ID: 5692bf8f43e2e4762753f55dec56296839578191
 - OS: Linux
 - Browser: Chrome

**Additional context**
I know that wine should be an instance, not a concept.

**Comment by reckart** [comment]
I believe this issue is only in the 0.9.x branch...

**Comment by reckart** [comment]
Cannot reproduce this in 0.8.3-SNAPSHOT (2019-04-04 20:24:21, build f7a7cb116c5ce51eab5b1da694df931e0476190e)

Setting milestone to 0.9.0.
