### ISSUE TITLE
Evaluating DL4J as NER recommender only predicts NO-LABEL

### ISSUE THREAD

**Issue by UWinch** [inception-project/inception#1101]
**Describe the bug**
The sequences in the DL4j recommender are padded with NO_LABEL if no annotation exists yet for a token. This e.g. happens during the NER evaluation test. In this case, the predictions for this test are only NO_LABEL. 

**To Reproduce**
* Implement a counter in DL4J recommender that counts predicted labels not equal to the NO_LABEL label. Run the thatNerEvaluationWorks test and see that no differing labels are found.
* Alternatively, checkout https://github.com/inception-project/inception/pull/1070 and see that the test returns zero for all scores (the score calculation ignores the NO_LABEL label).

**Expected behavior**
Ideally, the padding labels NO_LABEL should be ignored during training, maybe masking can be used for this?

**Comment by reckart** [comment]
Good catch! Yes, DL4J supports masking but we currently don't use it effectively:

```
                featureVec.put(new INDArrayIndex[] { point(sampleIdx), all(), point(t) }, vector);
                featureMask.putScalar(new int[] { sampleIdx, t }, 1.0);
                labelMask.putScalar(new int[] { sampleIdx, t }, 1.0);
``
