### ISSUE TITLE
Allow NamedEntityLinker to link to a specific KB

### ISSUE THREAD

**Issue by rcffc** [inception-project/inception#111]
Instead of iterating over all KBs, NamedEntityLinker should respect the concept feature traits: kb and scope - just like in the ConceptFeatureEditor.
The NamedEntityLinker must be moved into its own module - otherwise it will introduce a circular dependency to inception-ui-kb.

**Comment by reckart** [comment]
My understanding is that the problem is are the ConceptFeatureTraits? How about moving that class from kb-ui to kb?

**Comment by rcffc** [comment]
Yes, that suffices.

**Comment by rcffc** [comment]
Addressed in #45.
