### ISSUE TITLE
Ability to export recommender model

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#1117]
**Is your feature request related to a problem? Please describe.**
Let's say I annotate a text with the help of the string matching recommender. The recommender learns all the possible aliases for my concepts. It would be nice if there was a way I could export this dictionary. And while at it, it would be interesting in general to export the recommender models.

**Describe the solution you'd like**
Offer an option in the recommender sidebar where the user can select a recommender and press a button to download the current recommender model.

**Describe alternatives you've considered**
Downloading recommender models could also be done in the project settings. But considering that models are currently per-user, allowing the download from the annotation page might make more sense.

**Comment by munterkalmsteiner** [comment]
@reckart I assume that the export should provide some sort of human readable (text) representation of the model? The purpose is to inspect the model, but there is currently no need to import the model back?

**Comment by reckart** [comment]
There are probably many motivating scenarios for exporting the model. Here are three

* using the model with outside INCEpTION, e.g. with OpenNLP on the command line
* re-importing the model as a baseline into another project (re-importing doesn't yet have an issue I believe)
* inspecting the model (e.g. for dictionaries learned by the string matcher, but certainly not for OpenNLP models)

So: the representation would depend on what classifier/recommender is used

* for the StringMatchingRecommender, it would be good to export in the same format that is used to supply gazeteers to the recommender.
* for the OpenNLP-based recommenders, it would be good to use the binary format(s) which OpenNLP works with

**Comment by reckart** [comment]
Recommenders store they models in-memory within a `RecommenderContext` instance.

I guess a good approach to address this issue would be roughly:

* obtain all annotation CASes from all users (or from a specific user) in the current project (cf. `de.tudarmstadt.ukp.inception.recommendation.tasks.TrainingTask.readCasses(Project, User)`)
* manually construct a `RecommenderContext`
* instantiate the recommender factory via `de.tudarmstadt.ukp.inception.recommendation.api.RecommendationService.getRecommenderFactory(Recommender)`
* instantiate the recommender via the factory
* pass the context and the CAS to the `train` method so the recommender trains the model and stores it into the context
* add a new method to the `RecommendationEngine` maybe with a signature like `void exportModel(RecommenderContext aContext, OutputStream aTarget)` which would take the model and serialize it to the target stream - and implement that method in e.g. the StringMatchingRecommender.

**Comment by reckart** [comment]
The `RecommendationEngineFactory` interface could also be extended with some `boolean isExportSupported()` which would tell if the recommender supports project export - and control if an export button should be visible in the UI.

**Comment by reckart** [comment]
There could be a more "lightweight" approach than adding export functionality at the level of the `RecommendationEngine` interface, namely implementing it just within the UI code of the traits editors of individual recommenders (cf. Gazeteer support in StringMatchingRecommender). This would have the advantage that one could easily add options e.g. to support different export formats for different recommenders or other recommender-specific export settings. But it might also lead to quite a bit of code duplication. Still, it is worth considering.
