### ISSUE TITLE
Ability to change background colour of image display panel

### ISSUE THREAD

**Issue by mromanello** [inception-project/inception#1130]
**Is your feature request related to a problem? Please describe.**

For images that contain a lot of white (such as our newspaper pages) it would be useful to allow the user to define the background colour of the image display panel (e.g. from white to black).

**Describe the solution you'd like**

A user setting in the preferences panel would do.

**Comment by reckart** [comment]
Unfortunately, the preferences are not yet modularized which makes it difficult to add stuff there. 

Maybe something like this could help: https://github.com/briangonzalez/jquery.adaptive-backgrounds.js

The idea would be to extract the general color of the images shown in the sidebar, determine this colors "lightness" and depending on that automatically put a dark or light background.
