### ISSUE TITLE
Unify training data selection for evaluation

### ISSUE THREAD

**Issue by UWinch** [inception-project/inception#1132]
**Is your feature request related to a problem? Please describe.**
During evaluation, different recommenders select different amounts of training data given the same data and the same DataSplitter. To make recommender evaluation more transparent and comparable, all recommenders should use the same amount of training data during evaluation when the same DataSplitter is used.

**Describe the solution you'd like**
Some recommenders only consider data from sentences with at least one annotation, others use all data. It makes sense to use the former strategy for all recommenders.

**Comment by reckart** [comment]
If you consider a sentence-based recommender (i.e. one that performs sentence classification), I guess it would be reasonable to train on non-annotated sentences, no?

**Comment by reckart** [comment]
For POS recommenders, I think it may be desirable be a bit more restrictive on which sentences to train to avoid having a large `GAP` class. E.g. one could consider to train only on sentences in which at least 50% of the tokens have been annotated.

**Comment by UWinch** [comment]
These are good points. So, we should keep the different data selection overall. However, we might consider changing the number of training instances displayed in the **EvaluationSimulation**, because like you, users might be surprised by seeing different amounts of data when the same data is used for evaluation. I see two alternatives:

- keep it how it is, document it in the user-guide
- show the amount of data before filtering out un-annotated data

**Comment by reckart** [comment]
Maybe we can display the amount of unannotated/filtered out data in the chart?
