### ISSUE TITLE
Import annotated corpus by other  NLP tools

### ISSUE THREAD

**Issue by fishfree** [inception-project/inception#1160]
There are many NLP tools which can automatically annotate the NER/Syntactic Parsing, especially for non-English languages.  So if INCEpTION can import the annotated result first, then elaborating manually will save a life.

**Comment by reckart** [comment]
@fishfree INCEpTION supports various "standard" formats for NER and dependency parses (i.e. various CoNLL years). Are you missing a particular format?

**Comment by fishfree** [comment]
@reckart Thank you for your reminding. Is this the right place to do it: A project -> Settings -> Layers/Tagsets import ?

**Comment by reckart** [comment]
If you want to import a pre-annotated document, this is done via the "Documents" tab in the project settings.

If you want to import a "standard" tagset, you can find many of them in the [DKPro Core tagset documentation](https://dkpro.github.io/dkpro-core/releases/1.10.0/docs/tagset-reference.html). In every tagset description, there is a link **WebAnno tagset** in the top-right corner of the tagset infobox where you can download a JSON file that you can import in **Project -> Settings -> Tagsets import**.

**Comment by fishfree** [comment]
@reckart Thank you very much! I will dig more.
