### ISSUE TITLE
JSON file for annotation export in Remote API truncates file name if document name contains dots

### ISSUE THREAD

**Issue by rgabbard** [inception-project/inception#1174]
**Describe the bug**
If you export annotation via the Remote API using `json` format, you get a zip file containing the type system as an XML file and the JSON for the document annotation with a filename which appears to be the document name with the extension `.json`.   However, some of our document names contain `.`s; when this happens, only the part of the document name preceding the `.` is used to form the file name for the JSON.  

**To Reproduce**
1. Set up remote API access.
2. Add a file to a project which has a `.` in its name (for example `AFP_ENG_19940528.0145`).
3. Export it via the remote API (e.g. `yourServer/api/aero/v1/projects/45/documents/1167/annotations/nash_whaley?format=json`).
4. Examine the filename of the JSON file in the zip.

**Expected behavior**
The JSON file would be named using the full name of the document.

**Please complete the following information:**
 - Version and build ID: 0.9.0-SNAPSHOT (2019-03-26 09:08:35, build eef9f5f1d88cd914b23e82744805ad6fc9f9758b)
 - OS: Linux
 - Browser: Chrome

**Additional context**
This is easy to work around, so it is only a mild annoyance.

**Comment by reckart** [comment]
I guess everything after the first dot in the file name is considered to be the extension - which is then removed and `.json` is added. Otherwise, you'd get such odd things as `blah.xmi.json` or `blah.conll.json` - would you prefer that?

**Comment by rgabbard** [comment]
Ah, good point, I hadn't thought of that.  I think this is case where it depends on your annotation setup.  For us, there are never any files with extensions - we load Gigaword into ElasticSearch using the LDC's unique document ID (which contains non-extension `.`s) and that document ID becomes the document name in Inception. But if you are working with files on disk, I can see how it would be weird not to strip the extension.

But since there is only one JSON file in the archive anyway, it is trivial to get the right one, so I don't think it is worth trying to do anything about this.

**Comment by reckart** [comment]
Looking at the code what should happen is that the *last* of potentially multiple extensions is removed. So it could maybe be considered to add a configurable extension in the Elastic Search adapter?

**Comment by rgabbard** [comment]
@reckart : hmm - I think that would be a cure worse than the disease, since in other cases where the document name is used we would get the extension showing up.  It's probably easiest just to leave the behavior as is, since the name of the JSON file within the zip file is pretty unimportant.

**Comment by reckart** [comment]
Ok, then I'll close this one.
