### ISSUE TITLE
AL repeats suggestions

### ISSUE THREAD

**Issue by UWinch** [inception-project/inception#1183]
**Describe the bug**
Already annotated suggestions are requested from the user again during an AL session.

**To Reproduce**
1. Configure a project with a recommender.
2. Start an active learning session.

**Expected behavior**
The user should only be asked to annotate suggestions that have not been annotated yet.

**Screenshots**
![AL_shown_again](https://user-images.githubusercontent.com/29500351/57914614-42547b00-788f-11e9-94eb-91ca48bfff8a.png)

**Please complete the following information:**
 - Version and build ID: 0.10.0 SNAPSHOT
 - OS: Ubuntu
 - Browser: Chrome

**Comment by reckart** [comment]
I believe the recent improvements to active learning should have fixed this - but let's test a bit more.

**Comment by reckart** [comment]
I tested more and fixed more and I believe it's good now... anybody else want to try?
