### ISSUE TITLE
Can't export Weblicht TCF

### ISSUE THREAD

**Issue by eawer** [inception-project/inception#1185]
**Describe the bug**
I have coreference-annotated text, and when I try to export the project as WebLicht TCF I receive this: `Unexpected error during project export: IOException: Target file [/tmp/webanno4516487179959140766export/admin.tcf] already exists and overwriting not enabled.`

**To Reproduce**
1. Go to 'Project settings'
2. Click on 'Export'
3. Select 'WebLicht TCF'
4. Click on 'Export the whole project'

**Expected behavior**
I expect a file-saving window to show up

**Please complete the following information:**
 - Version and build ID: INCEpTION -- 0.9.0 (2019-05-13 14:11:58, build 3416a7c48ae0c7ed4f5a951247afed0d4a704fd2)
 - OS: Ubuntu 16.04
 - Browser: Chrome

**Additional context**

**Comment by reckart** [comment]
Hm, that is odd...

Does it work when you choose another format?

**Comment by eawer** [comment]
Yes, other formats work as expected

**Comment by reckart** [comment]
Fixed upstream.
