### ISSUE TITLE
Mailing list not accessible

### ISSUE THREAD

**Issue by clarus** [inception-project/inception#1196]
**Describe the bug**
Cannot access to the mailing list.

**To Reproduce**
* have a Google account not related to the project;
* go to https://groups.google.com/forum/#!forum/inception-users;
* see an error message and no emails.

**Expected behavior**
The list of discussions of the mailing list.

**Screenshots**
![image](https://user-images.githubusercontent.com/316665/58157883-8ec9fd00-7c79-11e9-84a1-2fe5a39a6151.png)
![image](https://user-images.githubusercontent.com/316665/58157898-95f10b00-7c79-11e9-9300-e5be2926087c.png)

**Please complete the following information:**
 - OS: Linux
 - Browser: Firefox

**Additional context**
I accessed the mailing list from https://inception-project.github.io/mailinglists/

**Comment by reckart** [comment]
Google is updating their Groups service and it appears to have some hickups right now. I can see the group but it tells me that it is "shared privately" - I am trying to find out whether I have to reconfigure it to make it publicly accessible again or whether Google has to fix something on their side.

**Comment by reckart** [comment]
Can you please try again - I think it should work now.

**Comment by clarus** [comment]
Yes it works! Thanks.
