### ISSUE TITLE
Feeling that the annotation edition is slow

### ISSUE THREAD

**Issue by clarus** [inception-project/inception#1197]
**Describe the bug**
I feel that when editing the annotations on one document the interface is too slow.

**To Reproduce**
1. start Inception from Docker with:
```
docker run -it --name inception -p8080:8080 inceptionproject/inception:0.9.1
```
2. Create a project with one text document
3. Open the document for annotation:
![image](https://user-images.githubusercontent.com/316665/58244446-e5573a00-7d52-11e9-9c5f-d090f20068fd.png)
4. Change the value of a tag and save it:
![image](https://user-images.githubusercontent.com/316665/58244509-fbfd9100-7d52-11e9-94cc-b96098493f69.png)
5. wait (too long) for the UI to update

**Expected behavior**
An almost instantaneous update of the UI with the new tag value.

**Screenshots**
Here are the logs of the POST calls to the server:
![image](https://user-images.githubusercontent.com/316665/58244255-8abdde00-7d52-11e9-9ac8-683ec5a2cfaa.png)
Each one takes around 400ms which is noticeable for me.

**Please complete the following information:**
 - Version and build ID: 0.9.2
 - OS: Linux
 - Browser: Firefox

**Additional context**
I do not know if others are experiencing the same issue. Maybe I am not building the project the right way.

**Comment by reckart** [comment]
I have tried on in my local development setup (Tomcat + Safari, no Docker, commit 8ea476b46dc02cb3fe52d0e6f4291c540aa21b84 which is essentially 0.9.1) and for a simple 30-sentence document having some Named Entity annotations, I get an XHR round-trip of ~250ms when I update the label of an annotation via the right sidebar.

**Comment by reckart** [comment]
Actually sometime even less :)

So for XHR updates which make an update (i.e. change of an annotation label), I get between 150ms and 300ms - which seems to depend a bit on if I am switching to other applications in between - maybe there is some OS-level caching involved here because our code doesn't have time-related caching here as far as I know.

Requests which are just done for rendering (e.g. selecting some annotation) complete faster in the area of 100ms-150ms again with the same caching hypothesis as above.

Note that the numbers will vary depending on the size of the document. As I said: mine has 30 sentences and probably ~50 named entity annotations. I am showing 5 sentences on screen at a time.

**Comment by clarus** [comment]
I tested again with Tomcat + Firefox and got similar results:
![image](https://user-images.githubusercontent.com/316665/58257247-dd0df780-7d70-11e9-9405-294749520a0a.png)

**Comment by clarus** [comment]
I would be curious to know what performances are experienced by other developers.

**Comment by reckart** [comment]
Are you running on a system with an SSD?

**Comment by clarus** [comment]
Yes, on my personal laptop.

**Comment by reckart** [comment]
@jcklie @UWinch could you check in your respective system / browsers how long XHR requests take for you?

**Comment by UWinch** [comment]
I tested creating a few annotations and setting feature values. I got around 200-250 ms for the 0.10.0 SNAPSHOT using Ubuntu and Chrome. However, I'm also not using docker, the problem is there?

**Comment by reckart** [comment]
Meanwhile a lot of optimization has been going into the annotation with round-trip times for feature updates arriving in the range of 100ms or sometimes even lower. Of course it depends on the kind of feature, the size of the tagset (if any), the number of features a layer has, the document size, network latency, etc - but things have in fact become much faster.

<img width="1855" alt="Screenshot 2021-02-17 at 23 45 24" src="https://user-images.githubusercontent.com/1410238/108277852-5e7aff80-717a-11eb-8569-a526c933a26d.png">

<img width="1004" alt="Screenshot 2021-02-17 at 23 45 10" src="https://user-images.githubusercontent.com/1410238/108277889-6c308500-717a-11eb-93bd-92b6db9015f5.png">
