### ISSUE TITLE
Selected Document Annotation not visible in details

### ISSUE THREAD

**Issue by wpmp** [inception-project/inception#1200]
**Is your feature request related to a problem? Please describe.**
When selecting a document annotation in the left sidebar while annotating a document, it is not clear to which document annotation the Details belong.

![doc_annotations](https://user-images.githubusercontent.com/5390724/58327943-2f165200-7e31-11e9-84ac-8be28dcbb707.png)

**Describe the solution you'd like**
The currently selected document annotation could be highlighted in some way.
For example highlight the name of the document annotation.
It would also be possible to show the document annotation name besides the `Details` text in the details box.

**Comment by reckart** [comment]
Another alternative could be to display the document-level annotations in such a way that the "expand" when the user selects them.
