### ISSUE TITLE
Zero-width spans for PDF editor

### ISSUE THREAD

**Issue by wpmp** [inception-project/inception#1212]
**Is your feature request related to a problem? Please describe.**

INCEpTION offers the functionality to create zero-width span annotations.
The brat editor does support this, however the PDF editor does not.

**Describe the solution you'd like**
The PDF editor should support zero-width span annotation.
When holding shift and clicking in the text of the document a zero-width span annotation should be created.

**Comment by wpmp** [comment]
This one is probably a bit more tricky than I thought.
A annotation range in PDFAnno with the value [530,530] is the 530th character.
So telling PDFAnno that we want an empty annotation between two chars (for example 530 and 531) won't be that easy.
No idea yet how to easily get around this.

**Comment by reckart** [comment]
Normally, annotation tools would consider `[530,530]` to be an empty span (string of length 0) and `[530,531]` is considered to identify the character at position 530 (string of length 1).

**Comment by wpmp** [comment]
Yes and PDFAnno considers [530,530] as string of length 1 and [530,531] as string of length 2

**Comment by reckart** [comment]
Since we basically have decided to fork PDFAnno anyway ... how extensive would you think would it be to change this such that the offset ranges in the PDF JavaScript code are interpreted in the same way as on the backend?

**Comment by wpmp** [comment]
I'll have a look at that :)
