### ISSUE TITLE
Boundary for number features

### ISSUE THREAD

**Issue by wpmp** [inception-project/inception#1213]
**Is your feature request related to a problem? Please describe.**
Currently, number features (integer/float) can be used for annotations.
However it is not possible to set upper and/or lower boundaries for the value.

**Describe the solution you'd like**
When creating a number (integer/float) feature in an annotation layer the user can set a lower and/or an upper boundary to a number feature which limits the entered values.

**Comment by wpmp** [comment]
@reckart we discussed about the possibility to add a new representation for this limited numbers like a slider or star rating.
However I think it would be nicer to keep the current representation and just add the ranges behind the feature name, for example `Value (0-5)`.
I think both, a slider and a star rating are not that great if the number boundaries are getting larger, like 10+ because of limited space.
Maybe there is also another good method for representation?

**Comment by wpmp** [comment]
As discussed, we could add a limit for which a slider / star rating is used (like up to 10 e.g.)

**Comment by reckart** [comment]
Setting milestone to 0.12.1 since it will be based on WebAnno 4.0.0-beta-2 which includes the boundaries feature.
