### ISSUE TITLE
Larger string input features for annotations

### ISSUE THREAD

**Issue by wpmp** [inception-project/inception#1214]
**Is your feature request related to a problem? Please describe.**
Currently it is possible to add a string feature to an annotation layer.
However the string input size is fixed and only one line.
A possibility to modify the size of the string input like having multiple rows is not possible.

**Describe the solution you'd like**
An option to set the wanted number of rows for a string input field could be added.
Another possibility would be to open an overlay with a bigger string input field when clicking on the original input field

**Comment by wpmp** [comment]
@reckart how do like this possible solution:
![larger_strings](https://user-images.githubusercontent.com/5390724/63781164-9daff380-c8e9-11e9-99c5-edc15000526f.gif)

**Comment by reckart** [comment]
That looks nice :) 

* Should it be made such that the other editors are not pushed down to avoid the UI appearing to be "jumpy"?
* When the editor goes back into "small" again, how large will it be? 
* Does it fit to the size of the content (maybe limited to a maximum number of lines)?
* We should allow the manager to choose how many lines (i.e. single line (text field) or n-lines (text area)) in the traits section of the feature detail editor in the project settings.

**Comment by wpmp** [comment]
webanno/webanno#1455 is finished and implements everything required, closing this one too
