### ISSUE TITLE
New Page for Simulation Evaluation

### ISSUE THREAD

**Issue by Sibgha360** [inception-project/inception#1222]
**Is your feature request related to a problem? Please describe.**
The Evaluation Simulation does not have enough space for additional UI elements/controls.

**Describe the solution you'd like**
A new page for Evaluation simulation.

* Create a new page similar to the recommender project settings
* Move the evaluation simulation to the new page from the recommender tab.
* Also show lisr of recommenders to select from.

**Comment by UWinch** [comment]
I think we misunderstood each other, we want to move the recommender evaluation to a completely new page, not just a new tab in the project settings.
