### ISSUE TITLE
Clean up PDFAnno code

### ISSUE THREAD

**Issue by wpmp** [inception-project/inception#1226]
**Describe the refactoring action**
As there seems to be no more work done in the original PDFAnno repository, the code can be cleaned up.
This includes removing the change comments and reformatting the entire code.

**Expected benefit**
PDFAnno code becomes easier to read and maintain.

**Comment by wpmp** [comment]
@reckart should we use eslint and the existing .eslintrc.js config for JavaScript code style or the DKPro eclipse xml?

**Comment by reckart** [comment]
> @reckart should we use eslint and the existing .eslintrc.js config for JavaScript code style or the DKPro eclipse xml?

Let's stick with the exsiting eslint for now.
