### ISSUE TITLE
Allow user to enter literal for fact component

### ISSUE THREAD

**Issue by matchlesswei** [inception-project/inception#123]
- setup a new layer with named entity identifier and Primitive:String
- link Qualifier(maybe also Object) to this new layer
- in frontend add 2 buttons beside input field to let user choose type(concepts in KB or literal)
- store the value correspondently 
- Write this to the future work in thesis

**Comment by reckart** [comment]
Fact module has for the time being been deprecated in favor of the extended concept feature support.
