### ISSUE TITLE
Bulk create/delete operations are very slow

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#1235]
**Describe the bug**
The bulk create/delete operations are very slow because they save after the creation/deletion of every single annotation.

**To Reproduce**
1. Bulk-create/delete something with many hits and note that is is quite sluggish

**Expected behavior**
The bulk-operation should be completed and the saving of the CAS should happen in the end.

**Please complete the following information:**
 - Version and build ID: 026e05bb0319e4b386a170973c3913916464f9a1

**Comment by jcklie** [comment]
When I try to remove stuff, then I get "No annotation selected. Please select an annotation first"
![image](https://user-images.githubusercontent.com/934600/59019511-7a286000-8848-11e9-9315-b820dd3f9614.png)

**Comment by reckart** [comment]
Searches on the search sidebar do not actually find annotations - they find locations in the text. In order to delete annotations at the matching locations, you must select (in the main editor) an appropriate annotation (i.e. in this case a Named entity with the identifier "Bordeaux") - then if at the location matched in the sidebar there is such an entity, it will be deleted. They checkboxes in the sidebar indicate which locations to check.
