### ISSUE TITLE
Support recommendation of simple relations

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#1239]
**Is your feature request related to a problem? Please describe.**
Recommender right now cannot predict simple relations

**Describe the solution you'd like**
- [x] Add a simple "String matching " recommender for relations (see #406)
- [x] Add a renderer for this type of recommendations
- [ ] Group suggestions for same source and target
- [ ] Add traits to relation recommender for feature of source and target layer that is used for recommendation
- [ ] Render confidence, hint, explanation, ...
- [ ] Add accepting and rejecting
  - [X] Accepting
  - [ ] Rejecting: rejecting arcs does not trigger `DoActionResponse`
- [ ] Add hiding of recommendations

**Comment by jcklie** [comment]
The suggestions can now be received in the `RecommendationRelationRenderer`. Right now, I cannot get back the source and target fs back from the relationposition, the low level CAS says they are not in there. The addresses in the `aCas` and the position look different when I manually select them.

**Comment by reckart** [comment]
The IDs are re-generated when the user opens a document. While the user is editing the document, the IDs should be stable. Mind to fetch the IDs from the `original CAS`, not from the `prediction CAS`.

**Comment by jcklie** [comment]
@reckart  Rejecting: rejecting arcs does not trigger DoActionResponse

**Comment by jcklie** [comment]
@reckart  Is there a reason why we both have an abstract class `AnnotationSuggestion_ImplBase` and an interface `AnnotationSuggestion`? Cant we put all in the abstract class?

**Comment by reckart** [comment]
So we don't have to use the longish `AnnotationSuggestion_ImplBase` everywhere (`_ImplBase being a marker for abstract classes`)...

**Comment by reckart** [comment]
Btw.: https://github.com/webanno/webanno/issues/1579

**Comment by jcklie** [comment]
We could just call the abstract class `AnnotationSuggestion`

**Comment by reckart** [comment]
If you have a strong feeling about it, rename it.

**Comment by jcklie** [comment]
I just dont understand why we have an interface AND an abstract class instead of just an abstract class. I do not care about the name, just about having 2 bases which could be one.

**Comment by reckart** [comment]
Well, as I said: just the habit of appending `_ImplBase` as a marker to abstract classes and that `AnnotationSuggestion_ImplBase ` is quite an unwieldy name. There is no technical reason. Feel free to refactor if you find it annoying.

**Comment by jcklie** [comment]
I started implementing rejections, but now I have issues with getting the layerId from the VID.
