### ISSUE TITLE
Refactor concept features (0.4.0)

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#124]
- [x] Allow choosing between a concept feature allowing only concepts, instances or both as values

**Comment by naveen2507** [comment]
@reckart can you give a bit detail on this. Are we talking about the annotation UI here, where we list a set of   KB entities to annotate an entity to?

**Comment by naveen2507** [comment]
Relates to the user given choices on the project settings page for choosing between a concept feature allowing only concepts, instances or both as values

**Comment by naveen2507** [comment]
@MdeBoer95 Please update the branch and merge it with the branch for [statement validation issue](https://github.com/inception-project/inception/tree/feature/50-statement-editor-with-validation)

**Comment by reckart** [comment]
@naveen2507 I think we should move these two tasks to new and separate issues:
* Choose scope via a concept tree or auto-complete field
* Choose scope via a SPARQL query
