### ISSUE TITLE
Seeing annotations of other users

### ISSUE THREAD

**Issue by wpmp** [inception-project/inception#1247]
**Is your feature request related to a problem? Please describe.**
There should be a possibility to see other users annotations for a document.
This could be useful if you want to compare your annotations with annotations of other users, etc.

**Describe the solution you'd like**
This could be done by having a write protected editor view which shows annotations of other users for a document.

**Additional context**
For the upcoming peer review functionality this feature might be helpful when two or more reviewers review the same paper.

**Comment by reckart** [comment]
Sounds a bit like this is covered by #1256 (integrating curation functionality into the annotation page)... ?

**Comment by wpmp** [comment]
That's true, should we mark this as duplicte and close it?

**Comment by reckart** [comment]
I guess so.

**Comment by wpmp** [comment]
Closed due duplicate of #1256
