### ISSUE TITLE
Add timeout for external recommender timeout

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#1252]
**Is your feature request related to a problem? Please describe.** 
Long running external recommender run into HTTP timeouts. The default seems to be around 5 seconds which is not enough for e.g. flair.

**Describe the solution you'd like**
- [x] Set the timeout to something reasonable like 30-60 seconds (hard coded).
- [ ] Make it configurable via Spring.

**Additional context**
Deep learning is slow.

**Comment by reckart** [comment]
@jcklie do you want to keep this issue open, amend it for making the values configurouable by spring and move it to a future verson or close the issue and open a new one for the configurability?

**Comment by jcklie** [comment]
I would leave it open, I updated the description.

**Comment by jcklie** [comment]
Closed in #2263
