### ISSUE TITLE
Integrate curation into annotation page.

### ISSUE THREAD

**Issue by UWinch** [inception-project/inception#1256]
**Is your feature request related to a problem? Please describe.**
Integrate curation into annotation page as a new Tab instead of the Curation Page on the Dashboard to benefit from already implemented features on the annotation page.

**Describe the solution you'd like**

- [x] The user should be able to open the curation tab and select the users whose annotations she wants to see. The annotations are shown in a differing color additionally to the users' annotations. 

- [x] The user can accept other users' annotations into her own annotation document or the curation document. 

- [x] An automatic merge of consistent annotations analogous to the existing implementation in the curation can be triggered by button click.
- [x] Aggregate other users' annotations as suggestions (e.g. 3 people annotated this span).
- [x] Hide other users' annotations if the same annotation was already merged.
- [x] Integrate some help on the feature for better usability.
- [x] The message `You need users with finished documents to start curating` is confusing on an already closed document, remove or instead display `This document has already been finished`. 

Implementation is done using an AnnotationEditorExtension to save the accepted annotations and trigger the render of the ones from other users.

**Comment by reckart** [comment]
We have done all of this now for a while - although the feature is still marked as experimental.
