### ISSUE TITLE
Hints for new users

### ISSUE THREAD

**Issue by UWinch** [inception-project/inception#1270]
**Is your feature request related to a problem? Please describe.**
When first logging in or when creating a first project, it can be hard to understand what to do for a first time user.

**Describe the solution you'd like**
Include hints on the first steps (in general and especially on the create new project page). See e.g. https://medium.com/rareview/ui-design-for-empty-states-zero-data-and-on-boarding-264cdb92826e

*Guided tour*
Guided tour through setting up the user's first project:
- [x] New project
- [x] Adding documents
- [x] Explain project dashboard 

*Text hints for empty spaces*
- [x] No projects
- [x] No finished documents for curation (upstream)
- [x] No finished documents for agreement (upstream)
- [ ] Check that messages on empty sidebars have the same style

**Comment by UWinch** [comment]
Added tutorial, still need to add text to some empty spaces (needs upstream changes).

**Comment by reckart** [comment]
@UWinch Looks like there is little left to do here. Are the remaining items low-hanging fruits? If yes, maybe this can be resolved quickly. If not, maybe we can close the issue and open new issues when ready to work on the remaining things?
