### ISSUE TITLE
String matcher duplicates recommendations

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#1272]
**Describe the bug**
The string matcher duplicates recommendations, as it does not ignore predictions.

**To Reproduce**
1. Create a project with a string matching recommender and e.g. external spacy
2. The recommendations are duplicated

**Expected behavior**
Only the real annotations are used by the string matching recommender

**Please complete the following information:**
Master, 0.10.

**Comment by reckart** [comment]
What do you mean by "it does not ignore predictions"?

**Comment by reckart** [comment]
Is there a quick fix to this one?

**Comment by jcklie** [comment]
It also uses predictions to train. There should be an easy fix by checking for the `isPrediction` in every recommender when adding things to the training set.

**Comment by jcklie** [comment]
The issue is that we do not clone the CAS for every recommender, but for every layer.
