### ISSUE TITLE
Serialized CAS file not found

### ISSUE THREAD

**Issue by rgabbard** [inception-project/inception#1281]
**Describe the bug**

We have [some code](https://github.com/isi-vista/curated-training-annotator/blob/master/annotation-utils/src/main/java/edu/isi/vista/annotationutils/ExportAnnotations.kt) to download the annotation from an Inception server.  

It first [asks the server for all its projects](https://github.com/isi-vista/curated-training-annotator/blob/fc39af14d09f554bb242f5b172a6fbfa7b21abeb/annotation-utils/src/main/java/edu/isi/vista/annotationutils/ExportAnnotations.kt#L66).  For each project, it then [asks for the documents for that project](https://github.com/isi-vista/curated-training-annotator/blob/fc39af14d09f554bb242f5b172a6fbfa7b21abeb/annotation-utils/src/main/java/edu/isi/vista/annotationutils/ExportAnnotations.kt#L75).  For each document, it then [asks what users have annotated it](https://github.com/isi-vista/curated-training-annotator/blob/master/annotation-utils/src/main/java/edu/isi/vista/annotationutils/ExportAnnotations.kt#L92).  Finally, [we attempt to download the annotations themselves](https://github.com/isi-vista/curated-training-annotator/blob/fc39af14d09f554bb242f5b172a6fbfa7b21abeb/annotation-utils/src/main/java/edu/isi/vista/annotationutils/ExportAnnotations.kt#L117).

This final step consistently fails on one of the project-document-user combinations.  The failure can be reliably reproduced on our system using `curl` as follows:

```
curl -u remote_admin:$INCEPTION_PASSWORD 'http://curatedtraining.isi.edu:8080/api/aero/v1/projects/33/documents/57/annotations/admin?projectId=33&documentId=57&userId=admin&format=json'
{"messages":[{"level":"ERROR","message":"Internal server error: CAS file [admin.ser] not found in [/srv/inception/repository/project/33/document/57/annotation]"}]}
```

`admin` here is one of the Inception users.  This file indeed does not exist on the server.  Nothing seems to be logged to `inception.log` about this. 

**To Reproduce**

We are not sure of the cause, so we are not sure how to reproduce this on a fresh install.

**Expected behavior**

I'm assuming there shouldn't be a mismatch between what is on disk and what is in the database, but I'm not sure how the difference arose in the first place.

**Please complete the following information:**
 - Version and build ID: `0.10.0-SNAPSHOT (2019-05-30 12:43:10, build f086cc64280ecd26cbd2692a82ba88dbef862f97)`
 - OS: The server is running on CentOS
 - Browser: n/a

This issue is not a major problem for us because the missing annotation file is not something we actually need for our work, but we wanted to report the problem in case others encounter it in the future.

**Comment by reckart** [comment]
I expect this happens when you try to access annotations for a document which was never accessed by the respective user. Annotation files on disk are created lazily upon the first access on the annotation page. If an AnnotationDocument is in state `NEW`, there is no guarantee that an actual annotation file is associated with it.

**Comment by rgabbard** [comment]
@reckart : Thanks - is it reliable to check if the state is `NEW` to avoid these, or could that show up for some documents which do have annotations?

**Comment by reckart** [comment]
In the present implementation, a document which had seen user interaction is put into `IN_PROGRESS` and cannot changed back to `NEW` through the UI. It might be possible via the remote API though.

**Comment by rgabbard** [comment]
@reckart : For our use case, we know we won't do that, so this suffices.  Thanks!
