### ISSUE TITLE
Curation - annotations of one specific annotator

### ISSUE THREAD

**Issue by muemel210** [inception-project/inception#1296]
**Is your feature request related to a problem? Please describe.**
We have different annotations on the same layer from different annotators and we want to curate them. In the curation we only want to accept the annotations of one specific annotator. To have a lower workload it would be great if we didn´t have to click on every deviation individually but could confirm all annotations of this one specific annotator in one click.

**Describe the solution you'd like**
The best solution would be a function that allows to choose the annotation from this one specific annotator and to take over only this annotation.

**Comment by reckart** [comment]
Upstream issue: https://github.com/webanno/webanno/issues/1388

**Comment by reckart** [comment]
Fixed upstream in https://github.com/webanno/webanno/issues/1388
