### ISSUE TITLE
Error when rendering PDF

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#1314]
**Describe the bug**
Error is displayed when trying to view document in PDF mode.

**To Reproduce**
1. Import this project: 
[copy_of_X+DEVEL+-+PDF+Test_2019-07-17_2140.zip](https://github.com/inception-project/inception/files/3403548/copy_of_X%2BDEVEL%2B-%2BPDF%2BTest_2019-07-17_2140.zip)
2. Open the document with the PDF viewing mode

**Expected behavior**
There shouldn't be an error or there should be a reasonable error message.

**Screenshots**
In Safari:
<img width="700" alt="2019-07-17_21-21-26" src="https://user-images.githubusercontent.com/1410238/61404955-ec28a600-a8d8-11e9-9e6c-5d7a3513dd9e.png">

In Chrome:
<img width="555" alt="2019-07-17_21-34-38" src="https://user-images.githubusercontent.com/1410238/61405753-de742000-a8da-11e9-991f-ff11353fe1ac.png">

**Please complete the following information:**
 - Version and build ID: 0.10.2 as well as ea62cac182d918a67da90cbb97c155d2eb8b259e
 - Browser: Safari, Chrome

**Comment by wpmp** [comment]
@reckart with master it can be opened.
Also I noticed that there are zero-width span annotations in the document.
When deleting them you can also open the document in 0.10.2 without any errors.
So I guess problem is zero-width spans which is already merged into master.
What do we do?

**Comment by reckart** [comment]
Well, if it's fixed in master then it should be fine. I don't think it makes sense to backport a fix to the 0.10.x branch.

**Comment by wpmp** [comment]
I guess we can close this then.
