### ISSUE TITLE
Issue with using kb: concept/instance as feature type

### ISSUE THREAD

**Issue by parthspatel** [inception-project/inception#1318]
When trying to create a feature list with a kb
- specifying allowed values to either Concept or Instance
- specifying a scope
both of these things cause no concepts or instances to show up in the search bar.

Also, it would be nice if there was a dropdown for the user to select a concept without searching as stated in the documentation.
https://inception-project.github.io//releases/0.10.2/docs/user-guide.html#_concept_features

**Comment by reckart** [comment]
Regarding not being able to find stuff in the KB: do the concepts/instances in your KB have labels (using the "label" IRI configured in the KB mapping settings)? If they do not have labels, they won't appear.

Regarding a better linking editor: we have an [issue](https://github.com/inception-project/inception/issues/215) for that - but we didn't get yet to work on it.

**Comment by reckart** [comment]
Assuming this has resolved itself as there were no further comments.
