### ISSUE TITLE
Cross-Layer Relations

### ISSUE THREAD

**Issue by parthspatel** [inception-project/inception#1319]
**Is your feature request related to a problem? Please describe.**
It's frustrating that we cannot relate two different tags together.

**Describe the solution you'd like**
I would like a relation that can be anchored/attached to multiple layers would make it a simple fix.

![image](https://user-images.githubusercontent.com/7965948/61511162-b48a2e80-a9aa-11e9-9c80-dda93f64492b.png) 

i would make it take in an array of layers.

**Comment by reckart** [comment]
It's on the radar but will still take some time to be addressed.

Most of the time you can just work around the issue. Let's say for named entity annotation in brat you would create two annotation, one for "Person" and one for "Location" - and in brat you could make relations between them.

If you create two layers "Person" and "Location" in WebAnno, you cannot create relations between them. What you do instead is create a layer "Entity" and add a feature "category" which can be "Person" or "Location". Then you can nicely define a relation layer on "Entity" and are a happy camper. Doesn't cover all cases, but works often enough.

**Comment by parthspatel-mendel** [comment]
Thanks recka

> It's on the radar but will still take some time to be addressed.
> 
> Most of the time you can just work around the issue. Let's say for named entity annotation in brat you would create two annotation, one for "Person" and one for "Location" - and in brat you could make relations between them.
> 
> If you create two layers "Person" and "Location" in WebAnno, you cannot create relations between them. What you do instead is create a layer "Entity" and add a feature "category" which can be "Person" or "Location". Then you can nicely define a relation layer on "Entity" and are a happy camper. Doesn't cover all cases, but works often enough.

Thanks for the tip!

**Comment by karzideh** [comment]
This would definitively be a nice feature! Especially when you want to express relationships between two entities that are not part of the same category. Of course you can create a layer "Entity" with a feature "category" that separates the two entities. In my point of view, annotation process suffers under this restriction resulting in more annotation mistakes.
