### ISSUE TITLE
Importing .ann files from BRAT

### ISSUE THREAD

**Issue by parthspatel** [inception-project/inception#1321]
**Is your feature request related to a problem? Please describe.**
It would be great if we could be able to import .ann files from BRAT

**Describe the solution you'd like**
Adding BRAT Standoff to the document importer (https://brat.nlplab.org/standoff.html)

**Comment by reckart** [comment]
I believe there is no way to generically and meaningfully transform brat data into a format usable by INCEpTION - and I have transformed some brat data already ;)

What I am using is the [BratReader](https://dkpro.github.io/dkpro-core/releases/1.11.0/docs/format-reference.html#format-Brat) component in DKPro Core which has various way of configuring how the transformation is done. So if you care to migrate data, I'd suggest you have a look at it and implement a small pipeline which reads the brat data and then exports it as [XMI](https://dkpro.github.io/dkpro-core/releases/1.11.0/docs/format-reference.html#format-dkpro-core-io-xmi-asl) or [WebAnno TSV3](https://dkpro.github.io/dkpro-core/releases/1.11.0/docs/format-reference.html#format-dkpro-core-io-webanno-asl).
