### ISSUE TITLE
Prev/Next page jumps randomly

### ISSUE THREAD

**Issue by kimi40** [inception-project/inception#1322]
I am working with Inception 0.10.0. When annotating, I use the buttons Next page to move to the next sentences. It randomly skips pages. Instead of going from sentences 1-20 to 21-39 it goes to 41-59. A similar issue was reported for webanno: https://github.com/webanno/webanno/issues/1288

**Comment by reckart** [comment]
Which browser are you using?

**Comment by kimi40** [comment]
I am using Firefox (version 66.0.3).

**Comment by reckart** [comment]
Closing as duplicate of #1323.
