### ISSUE TITLE
Recommendationservice performance

### ISSUE THREAD

**Issue by munterkalmsteiner** [inception-project/inception#1335]
**Describe the bug**
The performance of the recommendation service decreases considerably with a larger corpus. The methods `cloneCAS` and `monkeyPatchTypeSystem` seem to be the culprits (see screenshot).

**To Reproduce**
1. Import a relatively large dataset (mine had 1572 lines and 11350 words)
2. Create a recommender (e.g. POS with data majority)
3. Create an annotation.
4. Go to the next document
5. Prediction takes ~60 seconds

**Screenshots**
Shows runtime sampled with VisualVM, when switching to the next document in inception, i.e. `computePredictions` is invoked.
![image](https://user-images.githubusercontent.com/720692/62711448-5d033f80-b9f9-11e9-8f05-f9fa94dd9922.png)

**Please complete the following information:**
 - Version and build ID: 0.11.0-SNAPSHOT
 - OS: Linux
 - Browser: Firefox
 - CPU: Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz

**Comment by reckart** [comment]
The cloning and monkey-patching can most likely be done in a single step. That should save some time. Also, the `aTargetCas.getJCas()` in `cloneCas` can be dropped since we mostly use the CAS API these days - that will also save a lot of time. Although, the time saving will be removed if a recommender should try to use the JCas API later on. I am also not sure how the performance will be when we switch to UIMAv3.

**Comment by munterkalmsteiner** [comment]
The performance issue is likely related to inefficiencies underlying in UIMA. When using the same amount of data, but in a single document (the above figures stem from ~400 documents), cloning and patching takes less than a second.

**Comment by reckart** [comment]
The creation and initialization of a JCas container takes a lot of time - with UIMAv2 at least, using a simple CAS is much faster. The overhead of the creation of a (J)Cas object currently is paid twice, once during cloning and once during patching. So there is a lot of potential for performance improvement just by optimizing the way the UIMA framework is used in INCEpTION code.

**Comment by reckart** [comment]
I have tried optimizing this locally and will create a PR later - would be great if you could have a look at it then.

**Comment by munterkalmsteiner** [comment]
Sure, I'll benchmark it against the dataset I have.

**Comment by reckart** [comment]
Here you go: https://github.com/inception-project/inception/pull/1337

**Comment by munterkalmsteiner** [comment]
Prediction time has been improved:
![image](https://user-images.githubusercontent.com/720692/63109917-876d7380-bf8a-11e9-9e7b-9a89697225b7.png)

**Comment by reckart** [comment]
@munterkalmsteiner if you have time, it would be great if you could check out this branch (https://github.com/inception-project/inception/tree/0.11.x-uimav3) and look if/how the performance changes there

**Comment by reckart** [comment]
We should also be able to save the `upgradeCasIfRequired` call since `cloneAndMonkeyPatchCAS` already takes care of that. So I'll re-open and look into that again.

**Comment by reckart** [comment]
We have two CASes in the prediction computation. The `upgradeCasIfRequired` affects both, the first one (`originalCas`) and also the second one (`predictionCas`)  which is created from the original using `cloneAndMonkeyPatchCAS`. I think we could change the code such that it works without upgrading the `originalCas` - that means in particular changing `calculateVisibility` to be able to deal with situations where the layers/features defined by the project differ from the ones present in the CAS. Probably it is a simple change as we just need to skip layers/features which are undefined in the CAS...

**Comment by munterkalmsteiner** [comment]
> @munterkalmsteiner if you have time, it would be great if you could check out this branch (https://github.com/inception-project/inception/tree/0.11.x-uimav3) and look if/how the performance changes there

Performance seems to be worse with UIMA v3:
![image](https://user-images.githubusercontent.com/720692/63281036-3623f380-c2ac-11e9-9d12-912b419e3084.png)

I'll benchmark the changes in #1346 next.
