### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#1336]
**Is your feature request related to a problem? Please describe.**
Looking at the white background for a while is not so good for the eyes.

**Describe the solution you'd like**
Maybe make the bootstrap theme configurable to use a dark background, the editor 

**Describe alternatives you've considered**
Use a plugin like [Dark Reader](https://darkreader.org) or GreaseMonkey scripts

**Comment by reckart** [comment]
One step closer to this with the upgrade to Bootstrap 5.3.0...
