### ISSUE TITLE
Additional KB IRIs

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#134]
**New categories**
- [ ] label (e.g. rdfs:label or skos:prefLabel / skos:altLabel)
- [ ] description (e.g. skos:definition, schema:description)
- [ ] property type (e.g. http://www.w3.org/1999/02/22-rdf-syntax-ns#Property, whatever it is for wikidata, etc.)

**New values for existing categories**
- [ ] class: skos:Concept
- [ ] subclass: skos:broader

**Comment by reckart** [comment]
@rcffc any other IRIs that you are currently hard-coding?

**Comment by rcffc** [comment]
I have updated the description.

**Comment by naveen2507** [comment]
Done
