### ISSUE TITLE
Boolean features makes inception crush

### ISSUE THREAD

**Issue by isabel-moreno** [inception-project/inception#1354]
**Describe the bug**
If a layer has a feature that is of type Boolean primitive enabled, when one tries to annotate in this layer inception crushes with an "internal error" message. Before this didn't happen.

**To Reproduce**
1. Log into inception
2. Create a project with a custom layer
3. Add to your custom layer a new feature whose type is Boolean
4. Add a document to this project
5. Try to make one annotation or select an existing one and you will see an "internal error" message
6. Return to home page
7. Disable this Boolean feature
8. Try to make one annotation or select an existing one and you won't see an "internal error" message

**Expected behavior**
Create annotations or select existing ones without errors

**Screenshots**
Boolean feature details:
![imagen](https://user-images.githubusercontent.com/40355008/63921070-67d25280-ca42-11e9-817e-97f1605ae951.png)
Error after selecting an existing annotation or trying to create one with a Boolean feature enabled:
![imagen](https://user-images.githubusercontent.com/40355008/63921230-b7b11980-ca42-11e9-82dd-ee70d8a4afc2.png)

**Please complete the following information:**
 - Version and build ID: 0.11.0 (2019-08-23 17:30:58, build 8a49b39f29604f1a74ea06586d7a14c6d37c1160)
 - OS: Linux
 - Browser: chrome

**Comment by UWinch** [comment]
Thanks for reporting this bug. We fixed it and the fix will be in the next release in about two weeks.

Does this work for you?

**Comment by isabel-moreno** [comment]
Yes! 
Thank you for your fast response

**Comment by UWinch** [comment]
https://github.com/webanno/webanno/issues/1406

**Comment by reckart** [comment]
Upstream issue has been fixed.
