### ISSUE TITLE
Allow concepts that are not explicitly class instances

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#136]
Various knowledge bases (e.g. Wikidata) does not mark every concept as an instance of their "class" concept. Instead, a concept can be identified by it being a subclass of another concept. 

* Our KBConcept.write presently always writes a type statement. Maybe that should not be the case.
* Methods such as listChildConcepts, listConcepts or readConcept also assume that a type statement is always present

- [x] `KnowledgeBaseServiceImpl.listConcepts(KnowledgeBase, boolean)` returns everything that is "instance-of class" - should instead return the root concepts and everything that is a subclass of something else.

**Comment by naveen2507** [comment]
PR #280 - DONE for now. Follow up issue #322
