### ISSUE TITLE
Documentmetadata-feature value are lost

### ISSUE THREAD

**Issue by floschne** [inception-project/inception#1364]
**Describe the bug**
When adding document-metadata and storing a value in a (string) feature of the document-level annotation, the value gets lost when the document-metadata sidebar panel gets closed or the page gets refreshed.

**To Reproduce**
1. Enable the document-metadata feature in settings.properties
2. Add a document-level layer and add a (string) feature to the layer.
3. Open a document in Annotation mode
4. Open the document-metadata sidebar panel
5. Add the layer / feature created in step 2.
6. Type any string in the input box next to the feature
7. Open any other sidebar panel or refresh the page
8. Re-open the document-metadata sidebar panel and see that the string for the feature from step 6. is lost.

**Expected behavior**
See step 8.

**Screenshots**
![Adding the document-level annotation with a string feature](https://user-images.githubusercontent.com/11663441/64158771-5b326d80-ce39-11e9-92b6-d93e096eb89c.png)
![Typing a string in the input box of the string feature in the document-metadata sidebar panel](https://user-images.githubusercontent.com/11663441/64158836-81580d80-ce39-11e9-9dd6-fcc859056442.png)

**Please complete the following information:**
 - Version and build ID:  0.12.0-SNAPSHOT (, build )
 - OS: Linux, Ubuntu 18.04 LTS
 - Browser: chrome

**Comment by wpmp** [comment]
This seems like a duplicate of  #1362.
There is already a PR for it: #1363

**Comment by reckart** [comment]
Closing as duplicate of #1362.
