### ISSUE TITLE
Add nicer URLs

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#1365]
**Is your feature request related to a problem? Please describe.**
Right now, the URLs in INCEpTION are really ugly and so 2000. It would also help bookmarking and sharing them.

**Describe the solution you'd like**
 It would be nice to haver nicer onces, e.g. `http://localhost/projects/42/settings/export` instead of  `https://localhost:projectsetting.html?6&p=127`

**Comment by reckart** [comment]
Done as part of #2043.
