### ISSUE TITLE
Imported Project:  AnnotationDocument NPE

### ISSUE THREAD

**Issue by UWinch** [inception-project/inception#1366]
**Describe the bug**
When importing a project with already annotated documents, a Nullpointer Exception is thrown when opening the annotated document.

**To Reproduce**
1. Import a project with annotated documents e.g. https://inception-project.github.io//use-case-gallery/lener-br/
2. Open an annotated document via the Open Document Dialog
3. See the error in the log

**Screenshots**
![annotationdoc-error](https://user-images.githubusercontent.com/29500351/64166382-44931300-ce47-11e9-9c33-b5e7f1e7497e.png)

**Please complete the following information:**
 - Version and build ID: 0.11.1
 - OS: Ubuntu
 - Browser: Chrome

**Comment by reckart** [comment]
It is better to post stack traces as text - this facilitates finding issues which have the similar stack traces or figuring out if an issue they observe has already been reported.
