### ISSUE TITLE
unable to set correct scope for KB feature

### ISSUE THREAD

**Issue by mromanello** [inception-project/inception#1368]
**Describe the bug**

I've added a KB feature to my annotation layer and I'd like to narrow its scope to `human` class in the Wikidata KB. However, if I selected `human` class from the scope dropdown and save, when I reopen the project settings the scope is set to a different (wrong) value, e.g. `history of North America` or `hydrology` (apparently not deterministic).

**To Reproduce**
1. Define a KB feature with name `person_wikidata_id`
2. Selected Wikidata from the KB dropdown
3. select `human` from the scope dropdown
4. save 
5. reopen the feature details and check the scope

**Expected behavior**
Ideally if I select `human` the scope should be set to `human` :)

**Screenshots**
![image](https://user-images.githubusercontent.com/310693/64324314-6e267880-cfc6-11e9-9a2e-82ca1eeb30c5.png)
![image](https://user-images.githubusercontent.com/310693/64324351-7e3e5800-cfc6-11e9-93d9-ad72303597cc.png)
![image](https://user-images.githubusercontent.com/310693/64324366-89918380-cfc6-11e9-82b4-9a2fb56b0137.png)

**Please complete the following information:**
 - 0.12.0-SNAPSHOT (2019-09-03 21:56:12, build fc17667b15c9dcdf2cc5f590be0e33a00594e488)
 - OS: Ubuntu 18.x
 - Browser: Chromium

**Additional context**

**Comment by reckart** [comment]
@mromanello for curiosity... when you set the scope to something like `Human` would you expect to get only instances of `Human` or also of sub-classes of `Human`?

**Comment by mromanello** [comment]
ideally also sub-classes, that would be great.

**Comment by mromanello** [comment]
thanks for fixing this! I will try to  install a recent 0.12-snapshot to test it.
