### ISSUE TITLE
Integrate WebAnnoCasUtil changes into inception

### ISSUE THREAD

**Issue by UWinch** [inception-project/inception#1372]
**Describe the bug**
Build fails because WebAnnoCasUtil no longer declares selectSingleFsAt, instead uses CasUtil.selectSingleAt.

**Expected behavior**
Replace calls to WebannoCasUtil.selectSingleFsAt with CasUtil.selectSingleAt

**Please complete the following information:**
 - Version and build ID: inception 0.12.0 with webanno 3.6.0-SNAPSHOT or 3.6.0-beta-13

**Comment by UWinch** [comment]
Seems to be already fixed in the bugfix-branch, so just needs to be merged into master.

**Comment by reckart** [comment]
Fixed in https://github.com/inception-project/inception/commit/8fdebeb921989ccc8b2833fa551a03f2b19b7476
