### ISSUE TITLE
Invalid Conll-U export of text reference (not on the same line)

### ISSUE THREAD

**Issue by MightyGoldenOctopus** [inception-project/inception#1373]
**Describe the bug**
In Conll-U exported files.
The reference text in the `# text =` fields is containing line breaks thus
making it impossible to distinguish the reference text and the part with informations
during parsing of the file.
Additionally, he standard explicitly says that any comment
must be preceded by a `#` at the beginning of the line. 

**To Reproduce**
1. Go to 'Project->Annotation->Export'
2. Scroll down to ''Conll-u"
3. Click on "export"
4. Check result of `cat -e myExportedFile.conllu | head`:
`# text = COUR D'APPEL DE PARIS  $
ARRM-CM-^JT DU 04 juin 2019 $
  $
PM-CM-4le 5 - Chambre 1  $
(nM-BM-0081/2019, 23 pages)  $
NumM-CM-)ro d'inscription au rM-CM-)pertoire gM-CM-)nM-CM-)ral : 17/15068 - NM-BM-0 Portalis $
35L7-V-B7B-B33AV $
DM-CM-)cision dM-CM-)fM-CM-)rM-CM-)e M-CM-  la Cour : Jugement du 30 juin 2017 -Tribunal de $
Grande Instance de Paris - RG nM-BM-0 16/00811 $
  $
`

**Expected behavior**
All quoted reference text should be on the same line as `# text =` without any line breaks
since the standard specs says you must have a `#` for each commented line.
Thus allowing the file to be parsed by SpaCy converters.

**Please complete the following information:**
 - Version and build ID: 0.11.0, 8a49b39f29604f1a74ea06586d7a14c6d37c1160
 - OS: ArchLinux
 - Browser: Firefox

**Additional context**
n/a

**Comment by reckart** [comment]
Good catch :)
