### ISSUE TITLE
Searching others' docs will search own annotations

### ISSUE THREAD

**Issue by UWinch** [inception-project/inception#1391]
**Describe the bug**
When viewing a document of another user (as an admin) and searching for annotations on the search-sidebar, the results are from the current user's annotations (the admin) and not the user whose document is shown.

**To Reproduce**
1. As an admin have some annotations.
2. Open the document of another user (via the Open Document Dialog).
3. Search for annotations using the search sidebar.
4. The results are annotations the admin made and not the selected user.

**Expected behavior**
One should be able to search the annotations of the user whose document is shown.

**Please complete the following information:**
 - Version and build ID: 0.12.0-SNAPSHOT
 - OS: ubuntu
 - Browser: chrome

**Comment by reckart** [comment]
This is something I was recently asked about by a user.

**Comment by UWinch** [comment]
> This is something I was recently asked about by a user.

Definitely still on my to-do list.
