### ISSUE TITLE
constraint with boolean feature

### ISSUE THREAD

**Issue by smarches15** [inception-project/inception#1392]
Hi,
I am trying to set a constraint in which the condition involves a boolean feature like:
```
import webanno.custom.TestEntities as Layer;
Layer {
  Booleanfeature1="Yes" -> Booleanfeature2="Yes";
}
```
I have read the full documentation, the test script works fine when the feature is a string, but there is no details on how to apply the same principle when booleans are involved. Has anyone tried something like this before and could point me towards the right approach?

Using Inception v0.11.2

Thanks

**Comment by reckart** [comment]
You can use `BooleanFeature1="true"` on the left side of a condition. However, on the right side of a condition, boolean features are not supported. So you can condition the preferred values of String feature on a boolean feature.

**Comment by reckart** [comment]
I have updated the documentation: https://github.com/webanno/webanno/pull/1450
