### ISSUE TITLE
annotation propagation changes the status of already finished documents

### ISSUE THREAD

**Issue by mromanello** [inception-project/inception#1397]
**Describe the bug**

A collaborator of ours (in impresso) reported having the following issue with the annotation propagation (search for a string, and apply to all its occurrences a given entity type label):

> Hi @matteo, I found a bug with the annotation propagation. I have completed quite a few documents. So when I create annotations for several NEs like “Angleterre”, it also resets all already finished documents to unfinished if the NE is present. Luckily, it does not alter the existing annotation in the finished documents. And it happens also when I untick the finished documents (see screenshot). But leaving these documents unfinished, other annotations could be altered with the next iteration of creating annotations. And it took me forever to double check each annotation and mark each affected document as finished again.

**To Reproduce**
1. Open a document
2. Select a token with a NE type annotation
3. Open search panel and untick finished documents
4. Finished documents where the searched string is found are re-opened again (marked as unfinished), although their annotations are not altered. 

**Expected behavior**

The status of unselected documents should remain unchanged.

**Screenshots**

<img width="403" alt="Bildschirmfoto 2019-09-16 um 17 03 46" src="https://user-images.githubusercontent.com/310693/65253785-87b5dd00-dafb-11e9-801b-3d3f00c74628.png">

**Please complete the following information:**
 - 0.11.2 (2019-09-11 15:24:14, build cdd78cb18259c51647488fde393166646c7f30c7)

**Comment by reckart** [comment]
Ouch...

**Comment by reckart** [comment]
Fix incoming.
