### ISSUE TITLE
No statements with reification enabled

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#140]
When I create a Wikidata-based KB with "WIKIDATA" reification turned on and select a concept, I see no statements.

Given, the Wikidata support is broken in many ways and the concept tree just shows bad data at the moment, but I believe at least some valid reified statements should could be salvaged.

![2018-04-29_01-25-47](https://user-images.githubusercontent.com/1410238/39401738-e82a12ae-4b4c-11e8-8afe-440f1ab743e6.png)

**Without reification enabled**
![2018-04-29_01-33-13](https://user-images.githubusercontent.com/1410238/39401751-64abf5a4-4b4d-11e8-8a5c-f0bfffb7a8f8.png)

**With reification enabled**
![2018-04-29_01-33-37](https://user-images.githubusercontent.com/1410238/39401752-72306fac-4b4d-11e8-9fe8-cb719a7a330a.png)

**Comment by naveen2507** [comment]
@Rentier Can you please update on the status of this issue?
