### ISSUE TITLE
Javascript event triggers on double click only

### ISSUE THREAD

**Issue by JavierLuna** [inception-project/inception#1400]
**Describe the bug**
I am setting a javascript action to trigger when I select a layer annotation. 
It only triggers when an annotator double clicks the annotation and not when they simply select the element.

Is this expected behaviour? In that case, could I ever achieve the behaviour I desire?

One click: Selects annotation but doesn't trigger the javascript action
Double click: Triggers the javascript action but doesn't select the annotation

**To Reproduce**
1. Go to Layers, Chunk (for example)
2. In **Run Javascript action on click**: `console.log($PARAM);`
4. Go to a document and annotate it
5. Make two Chunk annotations
6. Simple click one of them

**Expected behavior**
A simple click triggers the javascript action

**Please complete the following information:**
 - Version and build ID: 0.11.2 cdd78cb18259c51647488fde393166646c7f30c7
 - OS: Ubuntu 18.04
 - Browser: Chrome and Firefox, both latest versions

**Additional context**
No additional context needed.

Thank you so much for taking the time to look into this. I really appreciate the effort.

**Comment by reckart** [comment]
You can add the line

```
ui.brat.singleClickSelection=false
```

to your `settings.properties` file. This triggers the JavaScript on a single click and the selection of the annotation on a double-click.
