### ISSUE TITLE
Search in a Knowledgebase is not fulltext

### ISSUE THREAD

**Issue by munterkalmsteiner** [inception-project/inception#1408]
**Describe the bug**
Searching in a knowledge base seems to be restricted to the label field, i.e. the comment field or any other custom fields are not considered in the full text search. 

**To Reproduce**
1. Create a local pre-defined wildlife ontology knowledge base
2. Enable full text search
3. Go to the knowledge base and search for "Australasia" 
4. No hit

**Expected behavior**
At least the concept "Ecozone" should appear in the results as the comment contains the searched term.

**Please complete the following information:**
 - 0.12.0-SNAPSHOT (2019-09-26 17:00:24, build 6b60df01eecdc78f089fcf69fe097e2ba6e3aed2)

**Additional context**
I have tried to update the `INDEXEDFIELDS` according to Lucene Sail [documentation](https://rdf4j.eclipse.org/javadoc/2.5.4/org/eclipse/rdf4j/sail/lucene/LuceneSail.html), in 
`KnowledgeBaseServiceImpl`, but without success:

```
if (sailRepo.getSail() instanceof LuceneSail) {
                reindexSupported = true;
                LuceneSail luceneSail = (LuceneSail) (sailRepo.getSail());
                Properties indexedFields = new Properties();
                indexedFields.setProperty("index.1", "http://www.w3.org/2000/01/rdf-schema#comment");
                indexedFields.setProperty("index.2", "http://www.w3.org/2000/01/rdf-schema#label");
                indexedFields.setProperty("http\\://xmlns.com/foaf/0.1/name", RDFS.LABEL.toString());
                ByteArrayOutputStream indexedFieldsString = new ByteArrayOutputStream();
                indexedFields.store(indexedFieldsString, "update");
                luceneSail.setParameter(LuceneSail.INDEXEDFIELDS, indexedFieldsString.toString());
                
                
                try (RepositoryConnection conn = getConnection(aKB)) {
                    luceneSail.reindex();
                    conn.commit();
                }
            }
```

**Comment by reckart** [comment]
The SPARQL query which is generated by our `SPARQLQueryBuilder` enforces a restriction of the query to the label field. Cf. e.g. `de.tudarmstadt.ukp.inception.kb.querybuilder.SPARQLQueryBuilder.withLabelContainingAnyOf_RDF4J_FTS(String[])`.

https://github.com/inception-project/inception/issues/977 describes including also alternative labels into the query, but the issue remains open so far.

Including comments may help in some cases, but in other cases may be contra-productive (e.g. if the KB is large and has extensive descriptions). So the KB mapping configuration would probably need to be extended to allow configuring which fields are considered. Also, for some KBs, it may not be feasible to include non-label fields into the FTS query, e.g. when issuing queries against the official Wikidata endpoing which uses it own find-items-by-label FTS service.

**Comment by munterkalmsteiner** [comment]
Ah, I was looking at the issue from the wrong end... this complicates the situation since the search uses the `ConceptLinkingService`. I agree that comment fields may add noise or not be available. I'll probably cook something up that fits my particular use-case, which is however not that useful in general.
Being able to configure the search to use particular fields (also custom ones) would probably be the right solution.

**Comment by reckart** [comment]
With #977, it is now possible to include additional fields into the search. Depending on the KB being used, it may require extra configuration for these fields to be covered by the full text search. Some FTS services (e.g. the Wikidata search service) may not support this feature though.
