### ISSUE TITLE
Paging doesn't work in PDF editor

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#1418]
**Describe the bug**
Paging doesn't work in PDF editor.

**To Reproduce**
1. Try using the paging controls
2. See they do not work

**Expected behavior**
The PDF view has its own paging controls, we don't need the ones in the action bar.

**Please complete the following information:**
 - Version and build ID: 0.11.2

**Comment by fssh72** [comment]
This doesn't work in release version 0.19.1. Setting a specific page in the PDF viewer UI doesn't make the PDF jump to the selected page, further going to next or previous page doesn't work. Since jumping to a PDF page from search results also doesn't work it makes it very difficult to use this tool for annotation of larger PDF documents.

I'm on MacOS, observed this bug in Safari and Chrome.

**Comment by reckart** [comment]
The "paging" as we know it from the brat view is not available in the PDF view.

However, the "page" field of the PDF JS itself works for me (0.19.1, Chrome, MacOS):

<img width="284" alt="Screenshot 2021-03-30 at 16 01 29" src="https://user-images.githubusercontent.com/1410238/113001563-34513000-9171-11eb-9480-434a80230150.png">

**Comment by reckart** [comment]
For me it also worked without the developer console (89.0.4389.90 (Official Build) (x86_64))

**Comment by reckart** [comment]
The PDF JS version we currently include is quite old. We need to look into upgrading it, but we don't have a schedule for that yet and no idea how much effort it will be....

**Comment by fssh72** [comment]
Very strange. Are you also testing on localhost?

**Comment by fssh72** [comment]
It would be great if you can upgrade pdfjs. Further, being able to jump to the page where a search result was found, would be very helpful.

**Comment by reckart** [comment]
I tested on our demo server

**Comment by reckart** [comment]
Yeah, being able to jump to search results would be helpful (cf. https://github.com/inception-project/inception/issues/1512).

**Comment by reckart** [comment]
Well, try the demo server yourself: https://morbo.ukp.informatik.tu-darmstadt.de/demo

**Comment by fssh72** [comment]
Concerning jumping to a page, it is certainly possible with pdfjs (https://stackoverflow.com/a/34230090), but you need to keep track of the page of each token, I guess.

**Comment by fssh72** [comment]
@reckart Do you have a project with a very large PDF file? I was testing with a PDF document of 160 pages, but can't upload that unfortunately.

**Comment by reckart** [comment]
I tried with one with 1225 pages ;)

How large is your PDF file (in bytes)?

**Comment by reckart** [comment]
Somebody uploaded a huge PDF document in the project "AIDA" on the demo server.
