### ISSUE TITLE
Unused local variables and functions should be removed

### ISSUE THREAD

**Issue by JaviValera** [inception-project/inception#1422]
**Describe the refactoring action**
If a local variable or a local function is declared but not used, it is dead code and should be removed.

**Expected benefit**
Doing so will improve maintainability because developers will not wonder what the variable or function is used for.

**Comment by JaviValera** [comment]
@munterkalmsteiner

**Comment by reckart** [comment]
Be careful when doing this since fields and methods may at times be used through reflection which static code analysis tools may be unable to detect.

**Comment by munterkalmsteiner** [comment]
Thanks @reckart, this is a valid point! @JaviValera, please make sure that your changes do not change the behavior of the system. Depending on the change, you should consider writing a unit test or provide a protocol of the manual test steps you have performed to verify that the system behavior is not changed.
