### ISSUE TITLE
String literals should not be duplicated

### ISSUE THREAD

**Issue by JaviValera** [inception-project/inception#1427]
**Describe the refactoring action**
Duplicated string literals make the process of refactoring error-prone, since you must be sure to update all occurrences.

**Expected benefit**
Constants can be referenced from many places, but only need to be updated in a single place.

**Comment by JaviValera** [comment]
@munterkalmsteiner

**Comment by reckart** [comment]
Mind the semantic scope of the literals. Although e.g. the id `"form"` is used in many UI components, their scope is usually the individual component, not any component using a form.
