### ISSUE TITLE
Catch Exception instead of Throwable.

### ISSUE THREAD

**Issue by NovemberChopin** [inception-project/inception#1430]
**Describe the refactoring action**
Catch Exception instead of Throwable.

**Expected benefit**
Using subclassing exceptions provides information about what is going on, allowing clients of the functions to catch and treat it appropriately.

**Comment by reckart** [comment]
I believe we only catch throwable at the top level of scheduler threads with the purpose of avoiding at all cost that the scheduler dies because some scheduled task died. This is actually intentional. Curious if you find other places where we catch Throwable without a good reason.

**Comment by NovemberChopin** [comment]
@munterkalmsteiner
