### ISSUE TITLE
make this final field static too

### ISSUE THREAD

**Issue by jianglinyao1996** [inception-project/inception#1432]
**Describe the refactoring action**
make this final field static too.
The file link:
(1)links:inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndexTest.java
(2) inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceRemoteTest.java
(3)inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseProfileDeserializationTest.java
(4)inception-support/src/main/java/de/tudarmstadt/ukp/inception/kb/io/FileUploadDownloadHelper.java
@munterkalmsteiner 

**Expected benefit**
Static final modified variable is a static constant. There is no default value. The assignment opportunity is only one time, and there is only one place to assign value. It is only assigned in the place where it is declared.

**Comment by munterkalmsteiner** [comment]
@jianglinyao1996 what field are you referring to? In what file? 
What is the expected benefit (do NOT copy the generic issue description from sonar). Motivate the change!
Deadline: Oct. 9, 8am. If the description is not updated by then, I'll close the issue.
