### ISSUE TITLE
Rename this classes and fields to match the regular expression '^[a-z][a-zA-Z0-9]*$'.

### ISSUE THREAD

**Issue by Taaaaaserface** [inception-project/inception#1433]
**Describe the refactoring action**
Rename this classes and fields to match the regular expression '^[a-z][a-zA-Z0-9]*$'.
The classes are:
1)inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/dashlet/Dashlet_ImplBase.java
2)inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/trie/Trie.java
3)inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/util/OverlapIterator.java
4)inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/graph/KBInstance.java
5)inception-support/src/main/java/de/tudarmstadt/ukp/inception/kb/io/FileUploadDownloadHelper.java
6)inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/ranking/BaselineRankingStrategy.java
7)inception-external-search-pubannotation/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/pubannotation/model/PubAnnotationDocumentSection.java
8)inception-recommendation-api/src/test/java/de/tudarmstadt/ukp/inception/recommendation/api/recommender/RecommenderContextTest.java
9)inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseProfileDeserializationTest.java
10)inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/FactLinkingServiceImpl.java
11)inception-imls-lapps/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/lapps/traits/LappsGridRecommenderTraitsEditor.java
12)inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/pdfextract/RegionExtractor.java
13)inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceRemoteTest.java
14)inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImplWikiDataIntegrationTest.java
15)inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseSubPropertyLabelTest.java
16)inception-external-search-pubannotation/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/pubannotation/model/PubAnnotationDocumentSection.java
17)inception-imls-external/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/util/CasAssert.java
18)inception-imls-external/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/ExternalRecommenderIntegrationTest.java
19)inception-pdf-editor/src/main/js/pdfanno/src/core/src/annotation/abstract.js

An example provided of what I intend to change:
I renameed the variable name "_c" to "c_c" to match the regular expression '^[a-z][a-zA-Z0-9]*$' that and the name should point out the full meaning of the constant.

**Expected benefit**
make the modified classes and fields to match regular expression which makes the code look more compliant， which will benifits the developers more easy to undersand the meaning of variables and refactor the codes.

@munterkalmsteiner

**Comment by munterkalmsteiner** [comment]
@Taaaaaserface to which classes are you referring too? Please be specific. Also, maybe provide an example of what you intend to change. 
The expected benefit you describe is the actual change, you don't explain what the benefit is and who benefits.
You need to improve both the description of the refactoring action and the expected benefit. 

Deadline: Oct. 9, 8am. If the description is not updated by then, I'll close the issue.

**Comment by Taaaaaserface** [comment]
OK, I’ll update all the descriptions, sry for that.


Michael Unterkalmsteiner <notifications@github.com>于2019年10月7日 周一11:51写道：
