### ISSUE TITLE
Remove useless curly braces around statement

### ISSUE THREAD

**Issue by Taaaaaserface** [inception-project/inception#1434]
**Describe the refactoring action**
Remove useless curly braces around statement (sonar.java.source not set. Assu g 8 or greater.)

One of the statement I'm referring to is in file:
inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/AbstractInfoPanel.java
line 182
which means I need to remove useless curly braces around statement following:
LambdaAjaxLink deleteButton = new LambdaAjaxLink("delete",
                    AbstractInfoPanel.this::confirmActionDelete).onConfigure((_this) -> {
                        _this.setVisible(kbObjectModel.getObject() != null
                                && isNotEmpty(kbObjectModel.getObject().getIdentifier()));
                    });

I will remove the curly braces in second and last line, also the semicolon which will make the code like:

LambdaAjaxLink deleteButton = new LambdaAjaxLink("delete",
                    AbstractInfoPanel.this::confirmActionDelete).onConfigure((_this) -> 
                        _this.setVisible(kbObjectModel.getObject() != null
                                && isNotEmpty(kbObjectModel.getObject().getIdentifier()))
                    );

**Expected benefit**
The useless curly braces will be removed. Developers will spend less time to read the code without useless curly braces wihich will increase the readiability of the project.

@munterkalmsteiner

**Comment by munterkalmsteiner** [comment]
@Taaaaaserface What kind of statements are you referring to? In what file? What is the expected benefit and who benefits?
Please improve the description.

Deadline: Oct. 9, 8am. If the description is not updated by then, I'll close the issue.
