### ISSUE TITLE
Rename this method name to match the regular expression

### ISSUE THREAD

**Issue by wangspen** [inception-project/inception#1435]
**Describe the refactoring action**
Rename this method name to match the regular expression.

**Expected benefit**
Now the method name match the regular expression '^[a-z][a-zA-Z0-9]*$'.

@munterkalmsteiner

**Comment by munterkalmsteiner** [comment]
@wangspen To what method are you referring to? Also, what is the expected benefit of the refactoring? Now you describe only the change, but not who benefits why.

Please update the description as soon as possible.

**Comment by wangspen** [comment]
The regular expression is '^[a-z][a-zA-Z0-9]*$', there are some methods' name have underline, which is not match the regular expression. Therefore, we deleted the underline and make sure the name after refactoring match the regular expression.

But  actually I supposed that the original name of method is better. The method name with underline reflects what the method does exactly, make the code more clear and understandable. I think rename method is unnecessary.

**Comment by reckart** [comment]
@jcklie introduced the idea of using quite explicit names for unit test methods - so some of these have underscores and this is intentional. You probably won't find methods with underscores in non-test code.

**Comment by munterkalmsteiner** [comment]
@wangspen Thank you for the analysis. I will then close the issue. Please feel free to reopen if you find instances where removing underscore would be beneficial.
