### ISSUE TITLE
X hides or potentially hides a variable declared in an outer scope at line Y

### ISSUE THREAD

**Issue by clarkhywh** [inception-project/inception#1436]
An example of the issue: "_i" hides or potentially hides a variable declared in an outer scope at line 18. The file path is D:inception-html-editor/src/main/java/de/tudarmstadt/ukp/inception/htmleditor/annotatorjs/resources/annotator-full.js. The line is 300.

After refactoring, you can distinguish between the names of global variables and local variables. This makes it easier for developers to read the code, which increases the comprehensibility of the code.

@munterkalmsteiner

**Comment by munterkalmsteiner** [comment]
@clarkhywh Please remove the template text from the issue description. Also, please provide the following:

- An example of the issue. 
- A better description of the expected benefit. Why is the refactoring beneficial and for whom?

Please provide an update to the description as soon as possible.

**Comment by clarkhywh** [comment]
What should I do Is to clear code smell which is ""X" hides or potentially hides a variable declared in an outer scope at line Y.". After discussing with Michael I found the files I should improve are all automatically generated files or files of Mozillam, so they should not be changed manually.

**Comment by clarkhywh** [comment]
Maybe the issue should be closed

**Comment by clarkhywh** [comment]
The issue is M1. The files are inception-html-editor/src/main/java/de/tudarmstadt/ukp/inception/htmleditor/annotatorjs/resources/annotator-full.js, inception-pdf-editor/src/main/js/pdfanno/pdfjs/pdf.worker.js, etc.

**Comment by reckart** [comment]
If this happens in third-party code or auto-generated files, better leave it be - at least in our repo.

Theoretically, the issue could be reported upstream, either to the projects from which the generated files come or possible to the projects which maintain the code use to generate the files - but I don't know if that will make much sense.

**Comment by munterkalmsteiner** [comment]
Ok, it seems only 3rd party code is affected by this smell. Closing.
