### ISSUE TITLE
Extract this nested code block into a method

### ISSUE THREAD

**Issue by DEMONSTAT** [inception-project/inception#1437]

**Comment by munterkalmsteiner** [comment]
@DEMONSTAT Please remove the template text from the issue description. Also, please provide the following:

- An example of the issue ("this nested code block" is too unspecific). 
- A better description of the expected benefit. Why is the refactoring beneficial and for whom? Why does this refactoring improve code readability.

Please provide an update to the description as soon as possible.

**Comment by reckart** [comment]
Assuming this is no longer going to be worked on.
