### ISSUE TITLE
Move one method into another method

### ISSUE THREAD

**Issue by jianglinyao1996** [inception-project/inception#1438]
**Describe the refactoring action**
Move one particular method into another method.
For example, one method calls another method, but they can be wrote together to reduce code coupling.
@munterkalmsteiner 
**Expected benefit**
The code coupling can be reduced.

**Comment by munterkalmsteiner** [comment]
@jianglinyao1996 Please provide a better issue description, in particular:
- Provide an example of the refactoring you suggest 
- Describe the expected benefits (remove the template text).

Please update the description as soon as possible.
