### ISSUE TITLE
Refactor this method to reduce its Cognitive Complexity

### ISSUE THREAD

**Issue by Yancy-007** [inception-project/inception#1442]
**Describe the refactoring action**
An example of the issue
File link: inception-master\inception-master\inception-pdf-editor\src\main\java\de\tudarmstadt\ukp\inception\pdfeditor\pdfextract.java Line 303.

I reduced a nested loop in order to reduce its Cognitive Complexity

**Expected benefit**
Cognitive complexity attempts to measure and reduce the complexity of how a method's control processes are difficult to understand. Cognitive complexity is added when the code structure that interrupts the workflow is embedded. When these parts are reconstructed, the code's comprehensibility is improved.

**Comment by munterkalmsteiner** [comment]
@Yancy-007 please remove the text from the issue template.
Can you provide an example of the refactoring?
Why does the refactoring improve comprehensibility?

Please update the description as soon as possible.

**Comment by reckart** [comment]
Assuming this is no longer going to be worked on.
