### ISSUE TITLE
Make the enclosing method "static" or remove this set.

### ISSUE THREAD

**Issue by jianglinyao1996** [inception-project/inception#1446]
**Describe the refactoring action**
Make the enclosing method "static" or remove this set.
The methods is non-static, but it update static parameter.
@munterkalmsteiner 
**Expected benefit**
Do not use non-static methods to update static fields, which makes it difficult to get the correct results. If there are multiple class instances and multiple threads, it is easy to cause errors. Ideally, static fields are only updated from synchronous static methods.

**Comment by munterkalmsteiner** [comment]
@jianglinyao1996 Please provide a better issue description, in particular:

- Provide an example of the refactoring you suggest
- Describe the expected benefits (remove the template text).

Please update the description as soon as possible.
