### ISSUE TITLE
Remove unused function in JavaScript

### ISSUE THREAD

**Issue by Taaaaaserface** [inception-project/inception#1447]
**Describe the refactoring action**
Remove unused function in JavaScript

The unused function is in the following filed:
inception-pdf-editor/src/main/js/pdfanno/pdfjs/pdf.worker.js
in line 13228 named parseJbig2, which never be used in context.

**Expected benefit**
Developers will spend less effort to focus what they want to modified without unused function

@munterkalmsteiner

**Comment by munterkalmsteiner** [comment]
@Taaaaaserface Please provide a better issue description, in particular:

- Provide an example of the refactoring you suggest
- Describe the expected benefits. Currently, you describe the change, not why this change is important for whom.

Please update the description as soon as possible.
