### ISSUE TITLE
Override the "equals" method in this class.

### ISSUE THREAD

**Issue by Taaaaaserface** [inception-project/inception#1452]
**Describe the refactoring action**
Override the similar classes that has similar methods and Inherit the same parent class。
The classes are :
1)inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/TrainingTask.java
2)inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/SelectionTask.java
3)inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/PredictionTask.java
which have same parent class Task.java and similar method run(), so I 'll override the method in parent class which will be inherited by the child classes

**Expected benefit**
The action will reduce the the same codes and put the methods into parent class, which will reduce code redundancy and make developers easily to understand the codes.

@munterkalmsteiner

**Comment by munterkalmsteiner** [comment]
@Taaaaaserface please provide a better description of the refactoring action (you can provide an example). Which classes are affected? How does this action reduce code redundancy?

Please provide a issue description update as soon as possible.

**Comment by Taaaaaserface** [comment]
The classes TrainingTask.java, SelectionTask.java and PredictionTask.java in package inception-recommendation, classes ReindexTask.java,IndexSourceDocumentTask.java and IndexAnnotationDocumentTask.java in package inception-search-core all implements class Task.java in package inception-scheduling. 
They all overrided the function **fun()** from parent class Task.java which also implemented from his parent class Runnable, but the source of runnable cant be found and I'm not able to catch the origin function **run()**.

**Comment by Taaaaaserface** [comment]
And actually they only have few same code as follow:
Project project = getProject();
User user = getUser();
String userName = user.getUsername();

So I think maybe this refactor is unnecessary actually

**Comment by munterkalmsteiner** [comment]
Ok, agreed. Thanks for the analysis!
