### ISSUE TITLE
Image layer annotations not included when exporting document as XMI

### ISSUE THREAD

**Issue by mromanello** [inception-project/inception#1464]
**Describe the bug**

Image layer annotations are not included when exporting documents from INCEpTION with XMI as export format.

**To Reproduce**
1. Go to a document that has image layer annotations
2. Click on export and select XMI as the export format
3. Open the exported XMI in an editor and check for presence of image layer annotations
4. ...they are not there

**Expected behavior**
I'd expect such annotations to be included as well.

**Please complete the following information:**
 - `0.11.2 (2019-09-11 15:24:14, build cdd78cb18259c51647488fde393166646c7f30c7)`

**Additional context**

**Comment by reckart** [comment]
Image features are stores as URLs on some layer. E.g. in the following case, I have a custom span layer `ImageLink with a an image feature named `url` and it does appear when I export the annotated file as XMI:

```
    <custom:ImageLink xmi:id="6412" sofa="1" begin="151" end="297" url="https://geology.com/google-earth/google-earth.jpg"/>
    <custom:ImageLink xmi:id="6417" sofa="1" begin="371" end="509" url="https://cdn.pixabay.com/photo/2016/01/19/17/49/bible-1149924_1280.jpg"/>
    <custom:ImageLink xmi:id="6422" sofa="1" begin="689" end="974" url="https://s.hswstatic.com/gif/frog-1.jpg"/>
```

Search in your exported XMI file for "http" and you should find your image links somewhere.

**Comment by mromanello** [comment]
@reckart you can close this issue! the annotation layer is exported... I must have done something wrong at that time.
