### ISSUE TITLE
Annotation linking after double click not working

### ISSUE THREAD

**Issue by wpmp** [inception-project/inception#1465]
**Describe the bug**
In the PDF editor when a slot is armed for linking annotations and then double clicking on a span annotation that is no recommendation, the slot is disarmed.
However this should only happen if the double clicked span is a recommendation.

**To Reproduce**
1. Arm a slot of a link feature
2. Double click a non-recommendation span annotation
3. Single click a non-recommendation span annotation to link it

**Expected behavior**
When a slot is armed double clicking non-recommendation spans should do nothing.
And afterwards the slot should be filled correctly if a span annotation is selected.

**Additional context**
Requires webanno/webanno#1480

**Comment by reckart** [comment]
Double-clicking on an annotation should perform the "secondary action" which would be some JavaScript that can be configured per layer. Double-clicking on a recommendation should reject it. In both cases, I would tend towards disarming the armed slot.

**Comment by wpmp** [comment]
How can I call this JS function?

**Comment by reckart** [comment]
This is from the `BratAnnotationEditor` code for handling double-clicks:

```
                    else if (DoActionResponse.is(action)) {
                        if (paramId.isSynthetic()) {
                            Offsets offsets = getOffsetsFromRequest(request, cas, paramId);
                            extensionRegistry.fireAction(getActionHandler(), getModelObject(),
                                    aTarget, cas, paramId, action, offsets.getBegin(),
                                    offsets.getEnd());
                        }
                        else {
                            actionDoAction(aTarget, request, cas, paramId); // This method calls the JS
                        }
                    }
```
