### ISSUE TITLE
UI realoads when editing a field in 'annotationFeatureForm'

### ISSUE THREAD

**Issue by JavierLuna** [inception-project/inception#1479]
**Describe the bug**
This is a visual bug which makes more apparent in low-resolution devices with a small screen.

Basically, annotating using a custom layer with custom features, when updating a field's value, the whole `annotationFeatureForm` reloads. When it finishes reloading, it will scroll up to the top and not return the focus/scroll to the element the annotator was editing.

Fix would be something along the lines of:
1. When the "annotator has edited a feature value" event triggers, store the `scrollTop` value of that feature field
2. Issue AJAX request as usual
3. Reload `annotationFeatureForm` as usual
4. Assign the previously stored `scrollTop` value to the newly reloaded `annotationFeatureForm` html.

This should (hopefully) return the focus to the previous field, at least in the web console it works.

I've tried fixing it in your code but I don't quite find the place where it executes.

**To Reproduce**
1. Have a custom layer with a few custom fields. It doesn't matter the kind, just make a lot of them so the scrolling will activate.
2. Annotate a document using that custom layer
3. In the `Annotation` sidebar menu which will open, select one of the latest feature fields. Make sure you scroll down to see the visual bug
4. Change/Set the value of that field
5. A confirmation message will pop up, and the `Annotation` menu will lose focus and scroll to the top of it.

**Expected behavior**
Confirmation message pops up and the element I was editing is still on focus (or the scroll is in that position)

**Please complete the following information:**
 - Version and build ID: 0.11.2 cdd78cb18259c51647488fde393166646c7f30c7 (although I've tested in the 0.13 version and stills happens)
 - OS: Ubuntu 18.04
 - Browser: Firefox, Chrome

**Comment by reckart** [comment]
The "best" way to fix this is probably to limit the update to the content of the scrolling area (i.e. the feature editors) instead of updating the **entire** right sidebar.

The AJAX requests are managed by Wicket. We do it e.g. to display the "AJAX spinner" overlay:

```
      if (typeof Wicket != 'undefined') {
        Wicket.Event.subscribe('/ajax/call/beforeSend', function(
            attributes, jqXHR, settings) {
          showBusysign()
        });
        Wicket.Event.subscribe('/ajax/call/complete', function(
            attributes, jqXHR, textStatus) {
          hideBusysign()
        });
      }
```

... but as I said, I think this is going to be quite fragile and introducing a `WebMarkupContainer` here:

https://github.com/webanno/webanno/blob/9f5791bb9a98210dda98aecb668570496c436a63/webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.html#L110

**Comment by reckart** [comment]
Actually, there is already the `featureEditorsContainer` in the HTML - when editing a feature, it should suffice to reload that. Need to check if that is already the case and if nevertheless the scroll position resets...

**Comment by reckart** [comment]
Found the issue. In two cases, the wrong component was requested to be re-rendered.

**Comment by reckart** [comment]
Upstream issue: https://github.com/webanno/webanno/issues/1487

**Comment by JavierLuna** [comment]
Thank you so so much 👍
