### ISSUE TITLE
make tooltip for KB instance URI clickable

### ISSUE THREAD

**Issue by mromanello** [inception-project/inception#1484]
**Is your feature request related to a problem? Please describe.**

In the annotation view, for projects that have a KB annotation layer, it would nice to be able to click on an instance URI. It is currently shown in a tooltp (see screenshot) but alas it's not clickable.

**Describe alternatives you've considered**

Always possible to copy and paste into the browser address bar.

**Additional context**

![image](https://user-images.githubusercontent.com/310693/67491247-e5969100-f674-11e9-93da-d527296d0959.png)

**Comment by reckart** [comment]
When you click on the URL, where do you expect it to take you? To the corresponding entry on the KB page or to actually open the URL (mind that a KB URL is actually an IRI and might not even be resolvable by a browser).

**Comment by mromanello** [comment]
>  (mind that a KB URL is actually an IRI and might not even be resolvable by a browser). 

good point, I hadn't thought about that. Ideally I'd have liked to open the actual URL (in my example the Wikidata link). Would it be a problem for you is this is a non resolvable URL?

**Comment by reckart** [comment]
>  Would it be a problem for you is this is a non resolvable URL?

For INCEpTION: not really. Of course the browser would not be able to resolve it :)

**Comment by reckart** [comment]
I'm thinking of changing the popover such that it appears and disappears automatically (i.e. not on-click) and clicking on the badge would open the URL in a separate window/tab instead.

**Comment by reckart** [comment]
Added a second icon for now. This could be refactored later into a single icon for minimal space savings.
