### ISSUE TITLE
wrong display of cursor when annotating co-reference between distant annotations

### ISSUE THREAD

**Issue by mromanello** [inception-project/inception#1485]
**Describe the bug**

We are annotating co-reference, within the same document, between mentions of the same entity. When doing so in long documents, there are some issues with the actual position of the cursor and the displayed arrow (mismatch). 

**To Reproduce**
1. Go to a document
2. Starting dragging an arrow between two entities far apart from one another (i.e. one visible, the other not)
3. Scroll down while the keywords arrows while keep clicking with the mouse
4. The co-reference relationship is correctly established but it's very cumbersome having to use mouse and keyboard at the same time.

**Expected behavior**
It would be nice to have an auto-scroll when, while dragging, the user hover on the edge of the visible document area.

**Screenshots**

![image](https://user-images.githubusercontent.com/310693/67492043-25aa4380-f676-11e9-88c3-a713f795015b.png)

**Please complete the following information:**
 -  0.11.2 (2019-09-11 15:24:14, build

**Comment by mromanello** [comment]
A quick update: I've just tested this with INCEpTIOn 0.13.0, and now I can't create the relationship at all. Just let me know if you need more information about this bug.

**Comment by reckart** [comment]
Can you create short-ranging relations?

**Comment by mromanello** [comment]
Yes, the short ranging one work well.

**Comment by mromanello** [comment]
if it's helpful I can try to create a screencast?

**Comment by reckart** [comment]
I think a good solution to this issue would be adding proper support for long-ranging relations - something that works without scrolling. 

Long-ranging relation support is already existing as an issue: https://github.com/webanno/webanno/issues/1030

**Comment by mromanello** [comment]
Ah ok, good to know! I had a look at your [proposed solution](https://github.com/webanno/webanno/issues/1030#issuecomment-412483682) and it'd be fine with me. 

Is there a tentative due date for Webanno 4.0.0?

**Comment by reckart** [comment]
Probably not before next year - but that's not an issue here. INCEpTION gets the features earlier because it builds on WebAnno beta versions :)

**Comment by mromanello** [comment]
ok cool. I almost had a heart-attack :-)

**Comment by reckart** [comment]
@mromanello This should address the immediate issue: https://github.com/webanno/webanno/pull/1530

If you want to test it, you'd have to build WebAnno from the PR branch and try within WebAnno.
