### ISSUE TITLE
Feature editor directly in AL sidebar

### ISSUE THREAD

**Issue by matchlesswei** [inception-project/inception#149]
Feature editor directly in AL sidebar

**Comment by matchlesswei** [comment]
I want to create a FeatureEditor in the ALsidebar, I use 
```
FeatureEditor editor = featureSupport.createEditor("editor", mainContainer, this
            .getActionHandler(), this.getModel(), aFeatureStateModel);
```
So I need a FeatureStateModel `IModel<FeatureState> aFeatureStateModel = new FeatureStateModel(annotatorStateModel, annotationFeature);` 
The problem is:
This annotationFeature should be from the ALsidebar Layerselection(for example: POS layer), but the annotationFeature in annotatorStateModel is from the **right** sidebar Layerselection(for example: SurfaceForm)

I want to get POS feature editor, but the method `createEditor` in FeatureSupport cannot get POS feature, because it gets feature from AnnotatorState(feature in right sidebar). @reckart how can I solve this problem?

**Comment by reckart** [comment]
Can you use this?

```
IModel<FeatureState> aFeatureStateModel = Model.of(new FeatureState(annotationFeature, recommendedValue));
```

**Comment by matchlesswei** [comment]
Yes, thanks!

**Comment by matchlesswei** [comment]
<img width="1280" alt="screen shot 2018-05-08 at 15 52 43" src="https://user-images.githubusercontent.com/23156705/39761344-23b3a3e8-52d8-11e8-8e1e-21e45b7fc6df.png">

@reckart @betoboullosa ,2 more questions:
1. Do we need to add a 'correct' button in the al sidebar? If the user sets a value in the feature editor and press 'correct', then this annotation is saved, right?
2. If the user choose a token in the middle and select a same layer in right sidebar, the feature editor in the right sidebar should also be a `KendoComboboxTextFeatureEditor` according to the debug result of `PrimitiveUimaFeatureSupport`, but it is not. Do you have any idea why?

**Comment by reckart** [comment]
1) I think adding a "correct" button is necessary, yes. In the right sidebar, the value entered by the user is saved immediately when the focus leaves the input field. I feel that this would not be the proper approach in the AL sidebar though. Pressing "correct" should create an annotation with the selected value, save it to the AL history, and then directly move on to the next recommendation.

2) For string features, the `PrimitiveUimaFeatureSupport` has three modes: 
* no tagset: simple text field
* tagset with <75 tags: combobox
* tagset with >=75 tags: auto-complete field

**Comment by matchlesswei** [comment]
2. In the example above, the editor in the right should be the combobox, the same as the editor in al sidebar. In debug mode, `editor = new KendoComboboxTextFeatureEditor(aId, aOwner, aFeatureStateModel);` is called exactly. But the editor in webpage looks like a text field, and it saved no annotation when I entered the value.

**Comment by reckart** [comment]
Then my guess would be that the markup ID of both components (the one in the AL sidebar and the one in the right sidebar) is set to the same value. In the right sidebar, we need to force the markdown ID of feature editors to have a specific known value based on the feature ID. But in the AL sidebar, we do not need this and actually it would be harmful to have two elements with the same HTML markup ID on the same page.

Currently, we call `field.setMarkupId(ID_PREFIX + getModelObject().feature.getId());` in all of the FeatureEditor implementations. I guess this should be factored out from these components and be called in `FeatureEditorPanelContent.populateItem(Item<FeatureState>)` something like

```
            frag = featureSupport.createEditor("editor", AnnotationFeatureForm.this, editorPanel,
                    AnnotationFeatureForm.this.getModel(), item.getModel());
>>>>        frag.getFocusComponent().setMarkupId(ID_PREFIX + frag .getModelObject().feature.getId());
```

**Comment by reckart** [comment]
I'm changing the WebAnno code as described above (https://github.com/webanno/webanno/issues/934) so that we can re-use feature editors outside the right sidebar.

**Comment by matchlesswei** [comment]
@reckart thanks, it is exactly the markup ID problem. After changes in Webanno and PR #173 , this problem is solved.

**Comment by matchlesswei** [comment]
@reckart after pressing the "correct" button, AL sidebar should get the input selected value from FeatureEditor. I think `featureState.value` should be the selected input value, because featureState is the modelObject of FeatureEditor and the wicket id of input field is "value". But `featureState.value` in ALsidebar is still null. What do I miss?

**Comment by reckart** [comment]
No idea at the moment. I'd need to debug it.

**Comment by reckart** [comment]
@matchlesswei we seem to have two branches for this:

* feature/149-feature-editor-in-alSidebar
* feature/149-feature-editor-directly-in-AL-sidebar

**Comment by reckart** [comment]
![2018-05-16_16-49-12](https://user-images.githubusercontent.com/1410238/40124550-19e77e46-5929-11e8-9707-1be549249bf6.png)

Hm, I had thought we'd replace the "Label" line with the feature editor and pre-fill the feature editor with the suggested label. However, if we do that, we'd loose the information what the suggested label was once the user starts changing it. 

What do you think?

**Comment by reckart** [comment]
@matchlesswei actually. I see no "correct" button.

**Comment by reckart** [comment]
>But featureState.value in ALsidebar is still null. What do I miss?

I only see code which creates the feature editor, not no code which tries to read the value that the user entered. Is the branch up-to-date?

**Comment by matchlesswei** [comment]
@reckart Sorry that I forgot to push the commits. In the method `actionCorrect`(line 480) I tried to get the value.

**Comment by reckart** [comment]
@matchlesswei do you have any good idea for the Accept/Correct button label? I mean, we don't really want to write "Accept/Correct" on it, do we? ;)

**Comment by matchlesswei** [comment]
Use the word "Annotate"?

**Comment by reckart** [comment]
Sounds good

**Comment by matchlesswei** [comment]
@reckart a `FeatureEditor` is created initially in the component `RecommendationForm` in AL sidebar, using the code:
```
editor = featureSupport
            .createEditor("editor", mainContainer, this.getActionHandler(), this.getModel(),
                aFeatureStateModel);
```
Everytime a new suggestion shows, this FeatureEditor needs to be updated (e.g. the label before feature input field changes from `identifier` to `value`). 
How can I update this FeatureEditor? 

I have updated the `aFeatureStateModel`, and created the editor again, detached the model and the editor, added the editor to a target. But the FeatureEditor doesn't update.

**Comment by reckart** [comment]
Is the non-working state committed?

**Comment by matchlesswei** [comment]
Yes, I have committed in 145ed15.

**Comment by reckart** [comment]
Depends on https://github.com/webanno/webanno/issues/985

**Comment by reckart** [comment]
Depends on https://github.com/inception-project/inception/issues/272

**Comment by matchlesswei** [comment]
Depends on #271
