### ISSUE TITLE
Annotation screen reloads if window size changed

### ISSUE THREAD

**Issue by JavierLuna** [inception-project/inception#1501]
**Describe the bug**
When annotating, if the browser's window changes, inception will reload the page.

**To Reproduce**
1. Go to the annotation screen.
2. Resize window
3. Inception reloads the entire webpage.

I've also experienced it randomly without resizing (which is my much more annoying bug), but haven't quite discover what's the trigger in those scenarios.

**Expected behavior**
UI is responsive (as it currently is) but no reloading happens.

**Please complete the following information:**
 - Version and build ID: 0.11.2 cdd78cb18259c51647488fde393166646c7f30c7
 - OS: Ubuntu 18.04
 - Browser: Chrome, Firefox as well (firefox has always worked fine, even better performance wise btw)

**Comment by reckart** [comment]
The reloading of the page is by design. It is done to ensure the annotation view adapts to the new page size (in particular the brat view).

Probably it would be possible to optimize this, e.g. by redrawing only the annotation SVG instead of the entire page.

It should not happen if the page is not resized.

**Comment by JavierLuna** [comment]
The thing is annotators are complaining because that reloading is making their task slower.
They could be in the middle of a document, it randomly reloads and they lose the focus.

As I said, I tried triggering the reloading myself but couldn't. It is the same "behaviour" as the reloading I just described.

Drawing the annotations svg would be a viable solution as the problem is the "lose of focus".

**Comment by reckart** [comment]
When it happens "randomly", does it happen in conjunction with an action by the user (e.g. creation/deletion of an annotation, change of feature value) - or does it happen all by itself.?

**Comment by reckart** [comment]
Upstream issue: https://github.com/webanno/webanno/issues/1519

**Comment by reckart** [comment]
https://github.com/webanno/webanno/pull/1520 seems to work nicely - for me it re-renders quickly and best of all, the scroll position doesn't seem to get reset.

**Comment by JavierLuna** [comment]
Good news then!
Really looking forward to this release :)

**Comment by reckart** [comment]
Fixed upstream - I hope :)

**Comment by JavierLuna** [comment]
Thank you so much!
