### ISSUE TITLE
Open document dialog is shown after export fails

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#1510]
**Describe the bug**
Open document dialog is shown after export fails

**To Reproduce**
1. Create a document with content `第四卷第一四二八页。 　`
2, Try to export it
3. See that it opens the `Open document dialog`

**Expected behavior**
It exports or shows an error

**Screenshots**

[Video](https://i.gyazo.com/cba033361b936c289039f7511e897cad.mp4)

**Comment by reckart** [comment]
Tested with 0.20.0-SNAPSHOT commit 1acd170c exporting CAS XMI 1.0 and TSV - both exported fine.

**Comment by reckart** [comment]
I believe that https://github.com/inception-project/inception/issues/2130 probably handled this case as well.
