### ISSUE TITLE
PDF editor does not support jumping to places

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#1512]
**Describe the bug**
Active learning and search do not jump when using PDF editor. Similar for other functionalities which involve jumping.

**To Reproduce**
1. Create a project with recommender and pdf
2. Get recommendations
3. Do active learning

**Expected behavior**
It jumps to the page with the annotation

**Screenshots**

**Please complete the following information:**
 - Version and build ID: 0.13.0 Stable
 - OS: Firefox Ubuntu

**Comment by reckart** [comment]
Yep, that would really be a nice thing if we had an API to jump to particular places in a PDF.

**Comment by jcklie** [comment]
Search jumping also does not work
