### ISSUE TITLE
PDF editor crashes when clicking on recommendation

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#1513]
**Describe the bug**
PDF editor crashes when clicking on recommendation

**To Reproduce**
1. Create a project with recommender and pdf
2. Get recommendations
3. Accept a recommendation

**Expected behavior**
No crash

**Screenshots**

**Please complete the following information:**
 - Version and build ID: 0.13.0 Stable
 - OS: Firefox Ubuntu

**Comment by reckart** [comment]
As far as I can tell, it works now with the PR merged. Please check and re-open if it doesn't.
