### ISSUE TITLE
Description of KB items is cut in the concept editor

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#1517]
**Describe the bug**

The description of KB items during entity linking is cut on the right side.

**To Reproduce**
1. Do some entity linking with KB items that have long descriptions
2. See the error

**Expected behavior**
I can see all of the description.

**Screenshots**
![image](https://user-images.githubusercontent.com/934600/69054564-22536f00-0a0c-11ea-960e-4471f985ed86.png)

**Comment by reckart** [comment]
For mit this renders ok in Safari (13.0.3) and in Chrome (78.0.3904.108):

![2019-11-25_15-03-15](https://user-images.githubusercontent.com/1410238/69546822-bb4a3300-0f94-11ea-8a41-66a138c678e2.png)

I tested using DBPedia as the KB.
