### ISSUE TITLE
Document where the settings.properties file lives

### ISSUE THREAD

**Issue by UWinch** [inception-project/inception#1518]
**Is your feature request related to a problem? Please describe.**
There is some description in the admin guide-> application home folder. However, it should be made clearer that the settings.properties file is not present automatically but needs to be created.

**Comment by shohrehhd** [comment]
Hello,
I am following the guidelines on "Storing data on the host" to set up inception using docker. I need to change the CSRF setting on the setting.properties, however I cannot find the setting file as said in: srv/inception

> Thus, if you follow the instructions above, the settings file would go to /srv/inception/settings.properties on the host system.

Do I need to create it myself and if so what settings should I add aside from the ones I need to set for CSRF?

Thanks in advance,

**Comment by UWinch** [comment]
Hi @shohrehhd , yes, you will need to create the settings.properties file yourself. If you only want to change this one specific property, you don't need to add anything else to the file.

**Comment by jcklie** [comment]
Reopen as there were some unclear points
