### ISSUE TITLE
Russia (Q159) not found in Wikidata 

### ISSUE THREAD

**Issue by mromanello** [inception-project/inception#1538]
**Describe the bug**
I'm testing Wikidata as a KB in our annotation projects. I'm using both a local Wikidata dump (loaded on a Virtuoso triple store) as well as the official Wikidata endpoint. In both cases the right entity for Russia (Q159) does not show up in the auto-suggestion.

**To Reproduce**
1. Open a document that contains the mention "Russia"
2. Start typing 'Russia' in the `wikidata_id` field (connected to the Wikidata KB, without any scope constraint)
3. Scroll the dropdown list looking for entity Q159
4. The entity is not found

**Expected behavior**
Entity Q159 should show up.

**Please complete the following information:**
 - Version and build ID: `0.14.0-SNAPSHOT (2019-11-26 10:27:06, build 695812410e5e100924b9c2f029cc24f9563f527a)`

**Additional context**
Initially, I guessed this was related to high recall mentions/strings, such as Russia, Italy, etc. But I've failed to reproduce this behavior in other cases (tried France, Italy, etc.).

**Comment by reckart** [comment]
Try changing the **Allowed values** settings for your `wikidata_id` to **<Any Concept/Instance>**. Wikidata is not the cleanest ontology there is... probably there is some entry in there which claims to be an **instance of Russia** causing INCEpTION to treat **Russia** as a class, not as an instance.

**Comment by reckart** [comment]
I made this change and then Russia Q159 showed up for me (with a bit of scrolling down).

**Comment by reckart** [comment]
[Here](https://query.wikidata.org/#%23Cats%0ASELECT%20%3Fitem%20%3FitemLabel%20%0AWHERE%20%0A%7B%0A%20%20%3Fitem%20wdt%3AP31%20wd%3AQ159.%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%22.%20%7D%0A%7D) you can see it. According to Wikidata, these here are instances of **Russia (Q159)**:

* wd:Q4437629:  List of football clubs in Russia by competitive honours won
* wd:Q15991374: 20th century in Russia

**Comment by mromanello** [comment]
Yes, that did the trick! Many thanks.

**Comment by reckart** [comment]
I have used the Wikidata web interface to propose the removal of these "instance of" triples...

**Comment by reckart** [comment]
@mromanello instead of sticking with **<Any Concept/Instance>**, you might consider dropping the problematic triples from your Virtuoso and continue with **<Only Instances>**. You could also consider adding a second feature which links to **<Any Concept/Instance>** so annotators can see if a missing entity shows up there - that way you'd get info on what to fix in the KB.

**Comment by mromanello** [comment]
Thanks! Is `<Any Concept/Instance>` adding a substantial overhead? I'd prefer not to modify the data for the sake of reproducibility.

**Comment by reckart** [comment]
It may show more irrelevant entries and increase the need for scrolling.

Otherwise, it depends... for the official Wikidata endpoint, it won't make so much of a difference because the entity search services only returns 50 results in any case.

In you use Virtuoso,  if there are **many** matches, then it could happen that the results are truncated (depending on what your setting of the maximum number of results for the KB is)

**Comment by reckart** [comment]
Btw. if you edit texts where the same entity appears multiple times, you might consider turning on the "Remember" option on your `wikidata_id` feature such that newly created annotations inherit the value from the previously selected annotation.

**Comment by reckart** [comment]
That would probably be faster then always typing in a query.

**Comment by reckart** [comment]
There is also the "space" trick discoverd by @jcklie - if you just press space in a KB feature field, then it will load suggestions based on the mention you annotated. This can save some time if the mention is likely the same as the entity label. If the entity is not there, you can just continue typing a the label you would like to search for (no need to remove the initial space).

**Comment by mromanello** [comment]
@reckart @jcklie thanks a lot for the space trick! I'll add it right away to our _inception guide_ for annotators.
