### ISSUE TITLE
Navigation in annotation view skips sentences

### ISSUE THREAD

**Issue by mbugert** [inception-project/inception#1541]
**Describe the bug**
Clicking on "next page" in the annotation view skips sentences.

**To Reproduce**
I don't know which properties a project needs to have to reproduce the issue, sorry. But in principle, it's simple:
1. Open a project
2. Annotate a bit
3. Switch to next page
4. Note that sentences are being skipped

**Expected behavior**
No skipping.

**Screenshots**
[ZIP of video (can't upload webm on Github :man_facepalming:)](https://github.com/inception-project/inception/files/3905679/Peek.2019-11-29.16-00.webm.zip)

**Please complete the following information:**
 - Version and build ID: `0.14.0-SNAPSHOT (2019-11-29 04:26:56, build 6ae1884d1b6e41fa177c4ddf992012fff7c856db)`
 - OS, Browser: `Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0`

**Additional context**

**Comment by reckart** [comment]
Does this happen in "brat (line-oriented" or "brat (sentence-oriented")?

**Comment by reckart** [comment]
Sentence mode (can be seen in the video saying "Showing xxx of xxx sentences".

**Comment by mbugert** [comment]
This was sentence-oriented mode.

**Comment by reckart** [comment]
Could reproduce and it is being fixed upstream. Thanks for reporting :)

**Comment by reckart** [comment]
Fixed upstream.
