### ISSUE TITLE
annotation doesn't show up in pdf view

### ISSUE THREAD

**Issue by XiaZeng0223** [inception-project/inception#1546]
**Describe the bug**
When annotating page 4888 of the attached pdf file, the annotation gets created but doesn't show in pdf view. 
[P19-1483.pdf](https://github.com/inception-project/inception/files/3911268/P19-1483.pdf)

**To Reproduce**
1. View the document in pdf view.
2. Scroll down to page 4888.
3. Select any text in the page to annotate it.
4. See error.

**Expected behavior**
The annotation should appear in the pdf viewer.

**Please complete the following information:**
 - Version and build ID: Technische Universität Darmstadt -- Computer Science Department -- INCEpTION -- 0.14.0 (2019-12-02 11:28:51, build f074afefd676011aabb37077abc4e422fbae28be)
 - OS:  Linux
 - Browser: chrome

**Comment by reckart** [comment]
@wpmp this is the issue I mentioned when we met - about the PDF which has a page that cannot be annotated.

**Comment by wpmp** [comment]
@reckart interestingly annotations render on this page for me as long as you are on the page before or afterward.

**Comment by wpmp** [comment]
so, at least the ones that you still see

**Comment by wpmp** [comment]
so, the problem seems to be, that no match can be found on page 4889 for the last word `correlation`.
when I try to create a span annotation for this word, the editor says that no match is found.

**Comment by reckart** [comment]
Fixed in the new PDF editor: https://github.com/inception-project/inception/pull/3097
