### ISSUE TITLE
PDF editor sometimes has trouble loading the PDF 

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#1551]
**Describe the bug**
Not sure if there is a bug, but it seems that in certain browser/network configurations, the server might not return the proper content type - or whatever...

**To Reproduce**
Not really sure...

**Expected behavior**
Resources should load ok, in particular the PDF stream and the PDF-text-mapping file.

**Please complete the following information:**
 - Version and build ID: 0.14.0

**Comment by sdspieg** [comment]
Not sure whether I have the same issue, but when I try to open a pdf document (the name of the demo project is 'Attempt'), I don't see anything in the annotation 

- this is how I import (selecting pdf format) 
![image](https://user-images.githubusercontent.com/691472/80401715-1b832f00-88bd-11ea-815e-19269c201b03.png)

- this is how I open 
![image](https://user-images.githubusercontent.com/691472/80401823-43729280-88bd-11ea-92e2-df6219e34945.png)

- what I see then: 
![image](https://user-images.githubusercontent.com/691472/80401906-60a76100-88bd-11ea-99f7-f4ec5bf49627.png)

- what I have selected in the settings: 
![image](https://user-images.githubusercontent.com/691472/80401979-803e8980-88bd-11ea-8a3b-c473380b2d2a.png)

- what the info says about the doc: 
![image](https://user-images.githubusercontent.com/691472/80402061-a2d0a280-88bd-11ea-8af7-89d952cfdecb.png)

Any suggestions?

**Comment by reckart** [comment]
I can reproduce the issue with the given project. In the JS console of the browser, I see the message: 

> The page at about:blank was not allowed to display insecure content from http://morbo.ukp.informatik.tu-darmstadt.de/resources/pdfanno/index.html?pdf=http://morbo.ukp.informatik.tu-darmstadt.de/annotation.html?5-1.0-centerArea-editor-vis&p=272&pdftxt=http://morbo.ukp.informatik.tu-darmstadt.de/annotation.html?5-1.1-centerArea-editor-vis&p=272&api=http://morbo.ukp.informatik.tu-darmstadt.de/annotation.html?5-1.2-centerArea-editor-vis&p=272.

**Comment by reckart** [comment]
Looks like the PDF editor tries to request data via http while it should be using https

**Comment by reckart** [comment]
@jcklie looks like morbo needs reconfiguration to let nginx forward the port to the application:

* in the `settings.properties` set up the protocol [forwarding headers](https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application properties.html) (search for `server.tomcat.protocol-header` and similar protocols)
* in the nginx configuration to actually set [such headers ](https://stackoverflow.com/questions/50952783/wicket-incorrect-bookmarkable-page-url-when-using-https)

**Comment by jcklie** [comment]
@sdspieg Should be working now.
@reckart I will document it in the nginx guide.

**Comment by jcklie** [comment]
It is already documented and I did not set the correct settings.properties properties.

**Comment by sdspieg** [comment]
![image](https://user-images.githubusercontent.com/691472/80559565-38fbea00-89de-11ea-9da0-f2bf6d793893.png)
 It DOES seem to work now. Thanks much!

**Comment by reckart** [comment]
Ok, then let's call it a solution and if there are other / more issues open a different issue for them.
