### ISSUE TITLE
Inception behind Nginx proxy (issue)

### ISSUE THREAD

**Issue by mariomieldijk** [inception-project/inception#1556]
Problem: 
- inception behind a SSL nginx proxy does not work correctly

The situation: 
- https request --> nginx --> http request --> {jwilder/proxy -->inception}

What happens: 

Use case 1
- Site is reachable via https
- You are able to login but after that
       { Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.
Thu Dec 05 14:49:09 UTC 2019
There was an unexpected error (type=Bad Request, status=400).
Origin does not correspond to request}

Use case 2
- Site is reachable via http
- You are able to log in 
- Switch over directly to (example) https://inception.localdomain.local/projectsetting.html?5
- Press create 
- Result: nothing happens on the right screen (switch to http://inception.localdomain.local/projectsetting.html?5 and it works again)

What does work :
- http request --> nginx --> http request --> {jwilder/proxy -->inception}

What do we think we are missing in the settings:
- some setting to add a $BASE_URL or option ssl_proxy=true (or such)

Our questions:
- Is this 'infrastructural use case' already possible?
- if yes: what kind of settings must we adjust to make it work?
- if no: Any suggestions?

Other information
Config of nginx proxy 

#startconfig

### http section

upstream demo.localdomain.local {
      server 10.0.0.1:80;
  }

server {
    access_log "/var/log/nginx/demo.localdomain.local_access.log" combined ;
    error_log "/var/log/nginx/demo.localdomain.local_error.log";
    listen 1.2.3.4:80;
    server_name demo.localdomain.local;

    if ($blocked_bots = 1) {
        return 444;
    }

            location / {

            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_read_timeout 65;
            root /tmp;
            client_max_body_size 1m;
            allow all;
            deny all;
            proxy_pass http://demo.localdomain.local;
            proxy_redirect default;
                    }
    }

### https section

server {
    access_log "/var/log/nginx/demo.localdomain.local_access.log" combined ;
    error_log "/var/log/nginx/demo.localdomain.local_error.log";
    listen 1.2.3.4:443 ssl http2;
    server_name demo.localdomain.local;

        ssl_certificate        /etc/ssl/certs/demo.localdomain.local.crt;
        ssl_certificate_key     /etc/ssl/private/demo.localdomain.local.key;

    if ($blocked_bots = 1) {
        return 444;
    }

            location / {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_read_timeout 65s;
            root /tmp;
            client_max_body_size 1m;
            allow all;
            deny all;
            proxy_pass http://demo.localdomain.local;
            proxy_redirect default;

#end config

#start config docker-compose
version: '2'

networks:
  nginxproxynetwork:
    external:
      name: nginxproxynetwork

services:
  mysqlserver:
    image: "mysql:5"
    tty: true
    container_name: inception_mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=inception
      - MYSQL_USER=USER
      - MYSQL_PORT=3306
      - MYSQL_PASSWORD=PASSWORD
    volumes:
      - /srv/inception/mysql-data:/var/lib/mysql
    command: ["--character-set-server=utf8", "--collation-server=utf8_bin"]
    networks:
      nginxproxynetwork:

  webserver:
    image: "inceptionproject/inception:0.14.0"
    tty: true
    expose:
      - 8080
    container_name: inception_webserver
    ports:
      - "8080:8080"
    environment:
      - INCEPTION_DB_DIALECT=org.hibernate.dialect.MySQL5InnoDBDialect
      - INCEPTION_DB_DRIVER=com.mysql.jdbc.Driver
      - INCEPTION_DB_URL=jdbc:mysql://mysqlserver:3306/inception?useSSL=false&useUnicode=true&characterEncoding=UTF-8
      - INCEPTION_DB_USERNAME=USER
      - INCEPTION_DB_PASSWORD=PASSWORD
      - VIRTUAL_HOST=inception.localdomain.local
    volumes:
      - /srv/inception/server-data:/export
    mem_limit: 1g
    memswap_limit: 1g
    restart: unless-stopped
    networks:
      nginxproxynetwork:
#end of config

**Comment by reckart** [comment]
See https://github.com/webanno/webanno/issues/1543#issuecomment-559984744

**Comment by reckart** [comment]
In principle this should be supported. I have not used nginx myself yet, but people who have have contributed a guide to [WebAnno](https://webanno.github.io/webanno/releases/3.6.3/docs/admin-guide.html#_installing_nginx). These instructions should work for INCEpTION as well.

Also, as mentioned in my previous comment, CSRF protection can be an issue when running behind a proxy. You may have to turn it completely off by adding the following lines to your `settings.properties` file:

```
wicket.core.csrf.enabled=false
wicket.core.csrf.no-origin-action=allow
wicket.core.csrf.conflicting-origin-action=allow
```

**Comment by reckart** [comment]
@mariomieldijk could you maybe try if properly [configuring `accepted-origins`](https://github.com/MarcGiffing/wicket-spring-boot#extension-core-csrf-prevention) instead of entirely disabling CSRF works for you?

**Comment by BasLee** [comment]
Properly configuring does not work:
```
wicket.core.csrf.enabled=true
wicket.core.csrf.no-origin-action=allow
wicket.core.csrf.conflicting-origin-action=abort
wicket.core.csrf.error-code=400
wicket.core.csrf.error-message=Origin does not correspond to request
wicket.core.csrf.accepted-origins.*=
```

Disabling crsf works:
```
wicket.core.csrf.enabled=false
wicket.core.csrf.no-origin-action=allow
wicket.core.csrf.conflicting-origin-action=allow
```

**Comment by reckart** [comment]
@BasLee how far do you get with your configuration?

**Comment by BasLee** [comment]
My `settings.properties` is empty, except for one of the two code snippets above.
But I do wonder what `wicket.core.csrf.accepted-origins.*=` does, and what should it contain?

**Comment by reckart** [comment]
I have no idea ;) If I knew what the proper configuration were, I'd have documented it. In principle, I think there are two hurdles:

* 1) settings these wicket CSRF properties
* 2) possibly having to fix forms used in the application to submit a hidden field with the CSRF token

So far, we don't even get very far with 1) when people are running behind certain proxies.

**Comment by rashad101** [comment]
> I have no idea ;) If I knew what the proper configuration were, I'd have documented it. In principle, I think there are two hurdles:
> 
> * 1. settings these wicket CSRF properties
> * 1. possibly having to fix forms used in the application to submit a hidden field with the CSRF token
> 
> So far, we don't even get very far with 1) when people are running behind certain proxies.

Is there any update on running behind certain proxies?

**Comment by reckart** [comment]
Wicket 9 supposedly has better support for CSRF, but after upgrading the first thing I did was to turn it off because out-of-the-box it breaks all kinds of stuff in INCEpTION. We didn't look yet into how it might be configured.

**Comment by reckart** [comment]
How should we proceed here? Is there anything we should do (short of enabling/fixing the CSRF which is a bit more complicated)? Would it be valid to resolve the issue for the time being without any further action?

**Comment by reckart** [comment]
Assuming the that issue was resolved as there was no more feedback and thus closing the issue.

**Comment by reckart** [comment]
Ok, so `wicket.core.csrf.accepted-origins.*=` is pretty much misleading.... 

What should go into the ´settings.properties` file is a line like this:

```
wicket.core.csrf.accepted-origins[0]=my.host.that.runs.inception.com
```

And it seems one should just the host name without any protocol - no http or https.
