### ISSUE TITLE
Recommondations disappear after resizing/reloading

### ISSUE THREAD

**Issue by Rentier** [inception-project/inception#156]
When resizing, recommondations disappear. They are actually better than the average recommondations. This happens after deleting an annotation.

The issue is maybe one of the following two:
1) The annotation is deleted but should not be used for recommondation, but actually is 
OR
2) The recommondation disappears and should stay

![recommondations_disappear](https://user-images.githubusercontent.com/934600/39580158-c9ff0178-4ee8-11e8-8943-2db3d6f1bc4b.gif)

**Comment by reckart** [comment]
That is odd because afaik no related (filtering) state should be carried over between renderings. As long as no background prediction processes are running (i.e. triggered by creating/updating an annotation), the information displayed in the UI should remain stable across re-renderings.

**Comment by rcffc** [comment]
There must be a bug in the RecommendationSpanRenderer - I will go investigate.
