### ISSUE TITLE
Changing annotations in finished document

### ISSUE THREAD

**Issue by UWinch** [inception-project/inception#1578]
**Describe the bug**
Annotations can still be changed in some circumstances after setting a document to "Finished". If you just clicked on finished without leaving the page, you can still change annotations.

**To Reproduce**
1. Annotate and click on "Finish"
2. Select, change or delete annotations

**Expected behavior**
Immediately after finishing a document, the user should no longer be able to change it.

**Please complete the following information:**
 - Version and build ID: 0.15.0, 0.14.1
 - OS: ubuntu
 - Browser: chrome

**Comment by reckart** [comment]
Fixed upstream
