### ISSUE TITLE
Allow search page to query from an external corpus

### ISSUE THREAD

**Issue by betoboullosa** [inception-project/inception#158]
Search page will allow to query from an external corpus. First candidate is C4Corpus (https://dkpro.github.io/dkpro-c4corpus/)

- [x] First implementation of search against a search provider.
- [x] Allow configuration of external indexes in the project settings
- [x] Support ElasticSearch-based external indexes
- [x] Implement a search page allowing to query external sources
- [x] Import documents from the search page

**Comment by reckart** [comment]
@betoboullosa please open a PR for your work on this issue and mark it as`WIP`. Thanks!

**Comment by betoboullosa** [comment]
Done. New things will go to new individual issues.
