### ISSUE TITLE
Unable to edit annotations in curation mode

### ISSUE THREAD

**Issue by mromanello** [inception-project/inception#1584]
**Describe the bug**
This seems a regression from previous version (`0.14.0`). In curation mode, annotations can be created but not modified/deleted.

**To Reproduce**
1. Go to the curation section of an existing project
2. Try to modify an annotation in the curated view/panel
3. See that fields are greyed out and no delete button appears.

**Expected behavior**
The usual behavior in curation mode.

**Please complete the following information:**
 - Version and build ID: `0.14.1`

**Additional context**
For the time being we've reverted to `0.14.0`

**Comment by reckart** [comment]
Ok, looking into it.

**Comment by reckart** [comment]
Looks like a negation symbol got missing... *sigh*

**Comment by reckart** [comment]
Fixed upstream: https://github.com/webanno/webanno/issues/1578
