### ISSUE TITLE
'Show disabled user' is hiding enabled users

### ISSUE THREAD

**Issue by Horsmann** [inception-project/inception#1586]
**Describe the bug**
The panel for adding new users to inception has a checkbox which is named 'show disabled user'. Clicking on this box hides all enabled users and shows only the disabled ones (if any present). 

This is contrary to expectation. The checkbox should show disabled users additionally to the enabled ones.

**Comment by reckart** [comment]
IMHO this works as designed. If anybody else feels the behavior should be changed, please comment. Until then, I am closing this issue.
