### ISSUE TITLE
KB entity not displayed in candidates' dropdown

### ISSUE THREAD

**Issue by mromanello** [inception-project/inception#1595]
**Describe the bug**

In some documents where e.g. Paris is mentioned, the right entity linking candidate (= [Q90](http://www.wikidata.org/entity/Q90)) does not show up in the dropdown. The entity **is** in the KB (it's found by copying/pasting the concept URI `http://www.wikidata.org/entity/Q90` into the feature field).

**To Reproduce**
1. Go to a document where Paris is mentioned
2. Click on a mention of Paris
3. Type "Paris" or "Paris :: capital" into the search/text field
4. Paris `Q90` does not show up in either case (the former leads to 100 results, the latter to 0).

**Expected behavior**
Paris `Q90` should show up.

**Screenshots**

**Please complete the following information:**
 - Version and build ID: `INCEpTION -- 0.14.2 (2019-12-31 15:54:23, build a44b4c76b19fcc3d0a58e75a82aafdd96a564500)
<img width="449" alt="Screen Shot 2020-01-14 at 14 00 28" src="https://user-images.githubusercontent.com/310693/72347906-6fd11d00-36d9-11ea-8ffc-f3b704fa5ad2.png">
`

**Additional context**
KB settings:
- Wikidata dump served by local virtuoso triple store
- Result Limit for SPARQL queries = `500`
- Full text search mode = `bif:contains`

**Comment by jcklie** [comment]
I tried it with our own virtuoso KB and it worked: 

![image](https://user-images.githubusercontent.com/934600/72349916-b6c11180-36dd-11ea-80c3-5e072c03a988.png)

Is yours reachable from outside so we can investigate this issue further?

**Comment by jcklie** [comment]
I find it also via "Paris" and "Paris::capital"

**Comment by mromanello** [comment]
unfortunately it's accessible only within our internal (EPFL) network. But I'm happy to run whatever SPARQL queries you think could be useful to debug, and compare our results with yours.

**Comment by reckart** [comment]
Set the system property `log4j.configurationFile="/path/to/an/log4j2.xml"` when you start INCEpTION and into the file `/path/to/an/log4j2.xml`, put this:

```
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="WARN" monitorInterval="5">
  <Appenders>
    <Console name="ConsoleAppender" target="SYSTEM_OUT">
      <!--SHORT PATTERN -->
      <PatternLayout pattern="%d{yyyy-MM-dd HH:mm:ss} [%thread] %level{length=5} [$${ctx:username:-SYSTEM}] %logger{1} - %msg%n" />
    </Console>

    <Routing name="ProjectAppender">
      <Routes pattern="$${ctx:projectId}">
        <!--
          This route is used when we do *not* have a project ID set, i.e. the variable reference
          "${ctx:projectId}" is not resolved and remains as the plain string "${ctx:projectId}"
        -->
        <Route key="${ctx:projectId}">
          <!-- 
            Do not log anywhere if there is no project ID. In this case logging is going only to
            the console.
           -->
          <Null name="null"/>
        </Route>

        <!-- 
          This route is used when we have a project ID set (i.e. in case the key is not
          "${ctx:projectId}")
        -->
        <Route>
          <File name="Project-${ctx:projectId}"
            fileName="${ctx:repositoryPath}/project/project-${ctx:projectId}.log">
            <PatternLayout pattern="%d{yyyy-MM-dd HH:mm:ss,SSS} [${ctx:username}] %msg%n" />
          </File>
        </Route>
      </Routes>
    </Routing>
  </Appenders>

  <Loggers>
    <Logger name="uima" level="ERROR"/>
    <Logger name="liquibase" level="ERROR"/>
    
    <Logger name="org.springframework.beans.factory.config.PropertyPlaceholderConfigurer" level="ERROR"/>
    <Logger name="org.springframework.beans.factory.config.PropertiesFactoryBean" level="ERROR"/>
    
    <Logger name="de.tudarmstadt" level="INFO"/>
    
    <Logger name="uima" level="ERROR"/>
    <!-- Avoid warning on cookies with an invalid expiration date - cf. issue #739 -->
    <Logger name="org.apache.http.client.protocol.ResponseProcessCookies" level="ERROR"/>
    <!-- Avoid error when user leaves websocket-enabled page -->
    <Logger name="org.apache.wicket.protocol.ws.javax.WicketEndpoint" level="FATAL"/>

   <Logger name="de.tudarmstadt.ukp.inception.conceptlinking" level="TRACE"/>
   <Logger name="de.tudarmstadt.ukp.inception.kb.querybuilder.SPARQLQueryBuilder" level="TRACE"/>

    <Root level="WARN">
      <AppenderRef ref="ConsoleAppender" />
      <AppenderRef ref="ProjectAppender" />
    </Root>
  </Loggers>
</Configuration>
```

Now the SPARQL queries generated by INCEpTION should be logged. Also, the concept linker should log some more information on what it gets/does.

**Comment by reckart** [comment]
@mromanello did you have any chance to capture the SPARQL query and get any insight why you do not get the expected results?

**Comment by mromanello** [comment]
I've attached inception's logging when I try to look for Paris (see below). 

I guess this is what's happening: the right Paris (`Q90`) is retrieved from the triple store (it's part of the 603 candidates retrieved) but it's not retained in the list of 100 ranked candidates displayed in inception.

```
Jan 22 11:35:09 dhlabsrv25 inceptiondev-service[66725]: TEST 2020-01-22 11:35:09 [ajp-nio-18008-exec-1] DEBUG [mromanello] ConceptLinkingServiceImpl - Generated [603] candidates in 793ms
Jan 22 11:35:10 dhlabsrv25 inceptiondev-service[66725]: TEST 2020-01-22 11:35:10 [ajp-nio-18008-exec-1] DEBUG [mromanello] ConceptLinkingServiceImpl - Ranked [100] candidates for mention [Paris] and query [] in [91] ms
```

[inceptio-paris-debug.txt](https://github.com/inception-project/inception/files/4096637/inceptio-paris-debug.txt)

**Comment by reckart** [comment]
Having a quick look at the code, the problem seems to be that we do this

* rank, limit, filter (i.e. "paris :: capital)

but what we should be doing is this

* rank, filter, limit

so the filtering can be used to pull out results which would otherwise be swallowed by the limiting step.

**Comment by reckart** [comment]
So I guess `limit(properties.getCandidateDisplayLimit())` should be pulled out from the `ConceptLinkingServiceImpl` and into `ConceptFeatureEditor`.

**Comment by mromanello** [comment]
in case it helps, here the logging for when I search for "Paris :: capital"

```
Jan 22 12:01:15 dhlabsrv25 inceptiondev-service[66725]: TEST 2020-01-22 12:01:15 [ajp-nio-18008-exec-6] DEBUG [mromanello] ConceptLinkingServiceImpl - Found [145] candidates exactly matching [Paris]
Jan 22 12:01:15 dhlabsrv25 inceptiondev-service[66725]: TEST 2020-01-22 12:01:15 [ajp-nio-18008-exec-6] DEBUG [mromanello] ConceptLinkingServiceImpl - Found [499] candidates using containing [Paris]
Jan 22 12:01:15 dhlabsrv25 inceptiondev-service[66725]: TEST 2020-01-22 12:01:15 [ajp-nio-18008-exec-6] DEBUG [mromanello] ConceptLinkingServiceImpl - Generated [603] candidates in 1ms
Jan 22 12:01:16 dhlabsrv25 inceptiondev-service[66725]: TEST 2020-01-22 12:01:16 [ajp-nio-18008-exec-6] DEBUG [mromanello] ConceptLinkingServiceImpl - Ranked [100] candidates for mention [Paris] and query [] in [75] ms
Jan 22 12:01:17 dhlabsrv25 inceptiondev-service[66725]: TEST 2020-01-22 12:01:17 [ajp-nio-18008-exec-8] DEBUG [mromanello] ConceptLinkingServiceImpl - Found [145] candidates exactly matching [paris, Paris]
Jan 22 12:01:17 dhlabsrv25 inceptiondev-service[66725]: TEST 2020-01-22 12:01:17 [ajp-nio-18008-exec-8] DEBUG [mromanello] ConceptLinkingServiceImpl - Found [500] candidates starting with [paris]]
Jan 22 12:01:17 dhlabsrv25 inceptiondev-service[66725]: TEST 2020-01-22 12:01:17 [ajp-nio-18008-exec-8] DEBUG [mromanello] ConceptLinkingServiceImpl - Found [499] candidates using containing [paris, Paris]
Jan 22 12:01:17 dhlabsrv25 inceptiondev-service[66725]: TEST 2020-01-22 12:01:17 [ajp-nio-18008-exec-8] DEBUG [mromanello] ConceptLinkingServiceImpl - Generated [954] candidates in 3ms
Jan 22 12:01:18 dhlabsrv25 inceptiondev-service[66725]: TEST 2020-01-22 12:01:18 [ajp-nio-18008-exec-8] DEBUG [mromanello] ConceptLinkingServiceImpl - Ranked [100] candidates for mention [Paris] and query [paris] in [134] ms
```

**Comment by jcklie** [comment]
@mromanello I created a bugfix in #1604, is it possible that you try it out?

**Comment by mromanello** [comment]
@jcklie I've just tested `0.14.3-SNAPSHOT (2020-01-24 16:46:10, build cb148e0cff938b65a6631e7376128acb64c324ec)` and I'm happy to report that searching for `paris :: capital` does retrieve indeed Paris Q90. That's terrific, many thanks!
