### ISSUE TITLE
Entity linking shows German labels

### ISSUE THREAD

**Issue by Rentier** [inception-project/inception#160]
When I select an named entity identifier, it turns to German.

![german_label](https://user-images.githubusercontent.com/934600/39618674-13c107a6-4f85-11e8-8c57-6a0e934d69dd.gif)

**Comment by reckart** [comment]
Seems that there might be a SPARQL query involved which does either not include the language filter or sets it to German instead of English.

This is what we normally use when fetching labels:

```
                         , "  OPTIONAL {"
                         , "    ?s ?pLABEL ?l ."
                         , "    FILTER(LANG(?l) = \"\" || LANGMATCHES(LANG(?l), \"en\"))"
                         , "  }"
```

**Comment by rcffc** [comment]
The problematic method is ```
public static RepositoryResult<Statement> getStatementsSparql(RepositoryConnection conn,
            Resource subj, IRI pred, Value obj, boolean includeInferred)``` in RdfUtils. Sometimes the predicate is <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>, sometimes <http://www.w3.org/2000/01/rdf-schema#label>, if I add a filter, the query  for type will return nothing.
Should I add a new method for getting the labels?

**Comment by reckart** [comment]
@rcffc I do not understand the problem in getStatementsSparql(). From where and how is it called in this particular case?

**Comment by rcffc** [comment]
Suppose we are using the following query:
```
select * where 
{
  { <http://www.wikidata.org/entity/Q82955> <http://www.w3.org/2000/01/rdf-schema#label> ?o.
    FILTER(LANG(?o) = "" || LANGMATCHES(LANG(?o), "en")).
  }
}
```
With this I can get the labels in english. This is the case when a user clicks on a candidate entity and getFeatureValue is called.

However, when a document is opened, the method is called with <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> . In this case, I get no results, but I do not understand why.
