### ISSUE TITLE
NEL only looks for first word and not entire span

### ISSUE THREAD

**Issue by JackDapid** [inception-project/inception#1602]
**Describe the bug**
Having a NEL running on a Token-level base NE layer only looks in Knowledge Base for the first word

**To Reproduce**
- Have an active named entity layer
Validation: Always
Granularity Level: Token-level
Overlap: Any
- Add a [Named entity@identifier] Named Entity Linker
Feature: identifier

**Expected behavior**
The NEL should look foremost for the entire NE tag: Human Rights Office and not only the first word 'Human'

**Screenshots**
![image](https://user-images.githubusercontent.com/8346230/72896840-e21caf80-3d20-11ea-95de-019140c6fa9f.png)

**Please complete the following information:**
 - Version and build ID: a44b4c76b19fcc3d0a58e75a82aafdd96a564500
 - OS: OSX client, CentOS server
 - Browser: Chrome

**Comment by reckart** [comment]
Hm, indeed. In particular since the NEL recommender only kicks in if there already is a named entity annotation, it should really take the entire covered text into account.

Sounds like it should not be too difficult to fix.

**Comment by jcklie** [comment]
The logic in the named entity linker is really difficult to understand. Why are we predicting explicitly for tokens and not the whole named entity?

**Comment by reckart** [comment]
I have no idea... maybe to ensure that annotation boundaries match token boundaries and that they don't go across sentences? ... but actually the behaviors of the NamedEntity layer should already enforce that...
