### ISSUE TITLE
Multiple Tags in the same Layer per Annotation

### ISSUE THREAD

**Issue by Wolkenstein** [inception-project/inception#1609]
**Is your feature request related to a problem? Please describe.**
There is only one tag per layer allowed in an annotation.

**Describe the solution you'd like**
Allow adding multiple tags to a layer of an annotation. I.e. supply a list of two possible pos-tags to a token because of ambiguity. 

**Describe alternatives you've considered**
Adding multiple layers like pos_1, pos_2... Let's call this a work around.

**Additional context**
-

**Comment by reckart** [comment]
On the built-in POS layer, you cannot have stacking annotations - that is true.

If you define a custom POS layer, you can set the "Overlap" behavior to "Stacking" or "Any" to allow multiple tags. Mind that stacked annotations are not supported in curation or agreement calculation. Custom POS tag layers are only supported with the WebAnno TSV or UIMA file formats (e.g. XMI).

**Comment by reckart** [comment]
Stacking the built-in POS tag layer is not possible due to the way the DKPro Core type system is designed which is used for the built-in layers.

**Comment by Wolkenstein** [comment]
Thank you for your immediate response! I was afraid that lists of Tags are not possible. I will stick to my multiple layer workaround.
