### ISSUE TITLE
Problems with liquibase preconditions in recommendation module

### ISSUE THREAD

**Issue by betoboullosa** [inception-project/inception#161]
- There is no precondition for adding the column learning_record.changeLocation 
- There is no precondition for changing the column recommender.threshold
- There is no onFail parameter for adding the column recommender.enabled

**Comment by reckart** [comment]
Also, most of the Liquibase configuration for these tables are still in `inception-active-learning/src/main/resources/de/tudarmstadt/ukp/inception/active-learning/model/db-changelog.xml` but the entities are now in `inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model`. I guess the db-changelog.xml needs to be merged with the one in inception-recommendation-api?

**Comment by rcffc** [comment]
It is not used anymore. I have pushed a commit which drops the column.
