### ISSUE TITLE
Re-Enable SPARQLBuilder Tests

### ISSUE THREAD

**Issue by UWinch** [inception-project/inception#1610]
**Is your feature request related to a problem? Please describe.**
I disabled the tests `SparqlQueryBuilderTest.testWithLabelMatchingExactlyAnyOf_Wikidata_FTS` and `SparqlQueryBuilderTest.testWithLabelStartingWith_Wikidata_FTS`, `testWithLabelContainingAnyOf_Wikidata_FTS`, `testWithLabelMatchingExactlyAnyOf_multiple_Wikidata_FTS`. They stopped clearing most likely due to problems with the wikidata sparql endpoint. Should be re-enabled when the problem is solved.

Disabled for: 0.15.0, 0.14.x

**Comment by reckart** [comment]
Tests were re-enabled in commit fd3f6f6596ecafe841072192c96c963beb99ca4e which belonged to #1600.
