### ISSUE TITLE
Inconsistent behaviour when two recommenders are set

### ISSUE THREAD

**Issue by mromanello** [inception-project/inception#1614]
**Describe the bug**

We have noticed inconsistent behaviours of inception in projects where multiple recommenders are set. We have one string recommender making suggestions for (custom) named entity types, and one for named entity links (same annotation layer, but different features).

When accepting the linking recommendation, inception creates a new entity (having the recommended link) instead of simply adding the link to the already existing mention.

**To Reproduce**
1. Open a document on inception
2. Wait for some linking recommendations on annotated mentions
3. Single click to accept a suggestion
4. You will see that a new annotation is created instead of adding the link to the existing one

**Expected behavior**

When accepting the linking recommendation, inception should simply add the link to the already existing mention.

**Screenshots**

![image (2)](https://user-images.githubusercontent.com/310693/73737275-9a475080-4742-11ea-9beb-890df3439fb5.png)
![image (1)](https://user-images.githubusercontent.com/310693/73737276-9adfe700-4742-11ea-9b3d-a5e431b90357.png)

**Please complete the following information:**
` 0.14.2 (2019-12-31 15:54:23, build a44b4c76b19fcc3d0a58e75a82aafdd96a564500)`

**Comment by reckart** [comment]
Ok, so if I see/understand it correctly, there are two differences between the screenshots:

1) on `Deutschland` in **line 21** you clicked on the recommendation `Germany` and it was added to the `-is_NIL | loc.adm.nat` annotation - I take it this is the expected behavior
2) on `Deutschland` in **line 24** you clicked on `Germany` and it was not added one of the existing annotations, instead creating a new one - this was **not** the expected behavior. 

Is this right?

**Comment by reckart** [comment]
The code is pretty straightforward:

```
        // Check if there is already an annotation of the target type at the given location
        Type type = CasUtil.getType(aCas, adapter.getAnnotationTypeName());
        AnnotationFS annoFS = selectAt(aCas, type, aBegin, aEnd).stream().findFirst().orElse(null);
        
        int address;
        if (annoFS != null) {
            // ... if yes, then we update the feature on the existing annotation
            ...
        }
        else {
            // ... if not, then we create a new annotation - this also takes care of attaching to 
            // an annotation if necessary
            ...
        }
```

The behavior would that either `selectAt` for some reason misses the existing annotation in some cases. 

Which recommender is generating these suggestions?

**Comment by mromanello** [comment]
thanks for looking into this, @reckart 

> Is this right?

yes, it's correct.

> Which recommender is generating these suggestions?

it's the string-based recommender

**Comment by reckart** [comment]
Documentation has been updated with an explanation how the code now (since a while already) consistently handles such a situation: 

> *Stacked annotations*: If you configured a recommender on a layer that allows stacking (i.e. multiple annotations of the same layer type at the same position in the text), accepting a suggestion will always create a new annotation with the suggested feature value. Even if annotation(s) of the same type already exist at this position, the suggested feature value will not be added to this annotation, but a new one will be created instead.
