### ISSUE TITLE
Upgrade to Bootstrap 4

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#1621]
**Describe the refactoring action**
Upgrade from Bootstrap 3 to Bootstrap 4.

**Expected benefit**
Using a CSS framework that is actually supported... although it should be noted that the respective Wicket packages are still only available as milestone builds.

Upstream issue: https://github.com/webanno/webanno/issues/1612

**Comment by jcklie** [comment]
![image](https://user-images.githubusercontent.com/934600/75659596-8708a180-5c6a-11ea-8b68-14e2224b1a7a.png)

It would be nice if there was a border around the box, white in white hurts my eyes

**Comment by jcklie** [comment]
![image](https://user-images.githubusercontent.com/934600/75659714-bb7c5d80-5c6a-11ea-8b9e-cc7b88af1b28.png)

I would like a border around the page counter, it is really white else

**Comment by jcklie** [comment]
I tested in chrome 79.0.3945.79

**Comment by jcklie** [comment]
The footer in bootstrap normally does not have a hline, but has either no divider or is a different color. Ours look really cramped.
