### ISSUE TITLE
POS annotations in curation

### ISSUE THREAD

**Issue by UWinch** [inception-project/inception#1626]
**Describe the bug**
POS annotations in curation seem to be no longer merged automatically.

**To Reproduce**
1. Annotate some POS annotations
2. Finish the document
3. Open the document in curation
4. No annotations are automatically merged into the curation document

**Expected behavior**
Annotations that all users agree on should be merged automatically.

**Screenshots**
![curating_POS](https://user-images.githubusercontent.com/29500351/75686334-63f6e580-5c9c-11ea-86e2-5bc84ee1f9d3.png)

**Please complete the following information:**
 - Version and build ID: 0.15.0
 - OS: Ubuntu
 - Browser: Chrome

**Comment by reckart** [comment]
I couldn't reproduce the issue. Can you provide a minimal sample project displaying this problem?

**Comment by reckart** [comment]
If there is an issue here, I think it should be fixed for 0.15.0.

**Comment by UWinch** [comment]
Also can no longer reproduce the issue, closing it.
