### ISSUE TITLE
Unable to export custom layer annotations

### ISSUE THREAD

**Issue by thak123** [inception-project/inception#1631]
I am having trouble exporting data from Inception application. I have 3 custom layers;
Can anyone tell me how to get the exports.?

Also If I have pre-annotated data how can I upload it to the inception application.
Which format does it have to follow. I intend to upload data for one layer .

**Comment by jcklie** [comment]
What exactly are your problems? You can export from the Project Settings in the format of your choice. For custom layers, you can use e.g. UIMA XMI and then dkpro-cassis or Java UIMA to read back your annotations.

**Comment by thak123** [comment]
Thank You I will try and let you know.

**Comment by reckart** [comment]
Closing assuming that all is fine as no further information was provided.
