### ISSUE TITLE
More explicit UI for accepting/rejecting recommender suggestions

### ISSUE THREAD

**Issue by munterkalmsteiner** [inception-project/inception#1634]
**Is your feature request related to a problem? Please describe.**
I've performed an experiment with industry practitioners (no professional annotators) and accepting/rejecting recommender suggestions via single/double click was experienced as quite fiddly and error-prone.
The current UI is shown below.
![old](https://user-images.githubusercontent.com/720692/76613047-ada5c280-651d-11ea-8461-f10a6c3c747e.png)

**Describe the solution you'd like**
I'd like to accept/reject suggestions with a single click and provide visual hints on the decision.
Mockup of the solution below.
![new](https://user-images.githubusercontent.com/720692/76613203-fa899900-651d-11ea-94a9-746dc62a0488.png)

This solution is also not ideal, as it covers the label. The information is however still visible in the popup. Maybe the green/red boxes can be transparent and without the checkmark/x so the text is still readable.

**Comment by jcklie** [comment]
I agree that the current approach is not ideal. In your mockup, which suggestion do I accept with the checkmark/x when there are several and how can I choose one?

**Comment by munterkalmsteiner** [comment]
It's not visible in the mockup, but when the mouse is over suggestion A, the pop-up with detailed information appears (as it is now the case) and the label of the suggestion A changes from showing the name to red/green with checkmark for accepting and x for rejecting. When the user moves the mouse to another suggestion B, the text of suggestion A becomes visible again, the text of suggestion B is hidden and shows the accept/reject areas, and the pop-up with detailed information for suggestion B is shown.

**Comment by waleedabdeen** [comment]
Hi, I have just started working on this issue.

**Comment by reckart** [comment]
@waleedabdeen Nice. You can create a pull request draft if you wish to share your work with us and if you would care to get any feedback.

**Comment by waleedabdeen** [comment]
@reckart  I see [`#1701`](https://github.com/webanno/webanno/pull/1701) in the upstream were closed. So the development should be done here in the downstream.

**Comment by reckart** [comment]
Right. I have already merged everything down here and pushed the updates into your PR.

**Comment by waleedabdeen** [comment]
Here is a working version.! what do you think @reckart ? should we hide the buttons immediately onClick?

![peek-inception](https://user-images.githubusercontent.com/31651466/107848565-a99cb780-6df4-11eb-995d-8764f787a660.gif)
