### ISSUE TITLE
'user not specified error' when importing rezipped projects

### ISSUE THREAD

**Issue by aakum03** [inception-project/inception#1640]
**Describe the bug**
When I export an annotated inception project; unzip it; and compress it again without modifying the contents, a reimport returns a 'user not specified error' error

**To Reproduce**
1. Export any non-empty inception from inception into any format (I am using UIMA CAS JSON)
2. Unzip the zip file
3. Zip the unzipped contents back into a zip file (Note: this should not include a top-level folder as described in the User Guide)
4. In Inception, as an administrator, go to administration and click projects and import the newly zipped project file
5. This returns "Error importing project: IllegalArgumentException: User must be specified"

**Expected behavior**
Import is successful without any errors and the project appears on the 

**Screenshots**
![image](https://user-images.githubusercontent.com/52176187/76791338-08961e80-6797-11ea-970e-910e587341ce.png)
Note: The result is the same even when I check the "Create missing users" checkbox

**Additional context**
My purpose is that I want to be able to import pre-annotated documents into inception from a different (non-inception supported) format for annotators to further annotate, so I will need to parse and generate my own .ser files and then compress and import it into inception.

**Comment by reckart** [comment]
Double-check the directory structure inside your ZIP file using e.g. `unzip -t yourzipfile.zip`. The content must start at the root of the ZIP not in a subfolder.

**OK**:

```
$ unzip -t demo.zip
Archive:  demo.zip
    testing: curation/document.tsv/CURATION_USER.bcas   OK
    testing: source/document.tsv   OK
    testing: annotation/document.tsv/anno2.bcas   OK
    testing: annotation/document.tsv/admin.bcas   OK
    testing: annotation/document.tsv/anno1.bcas   OK
    testing: exportedproject8681420238631463205.json   OK
    testing: log/project-12.log       OK
    testing: annotation_ser/document.tsv/admin.ser   OK
    testing: annotation_ser/document.tsv/INITIAL_CAS.ser   OK
    testing: annotation_ser/document.tsv/anno1.ser   OK
    testing: annotation_ser/document.tsv/anno2.ser   OK
    testing: curation_ser/document.tsv/CURATION_USER.ser   OK
    testing: event.log                OK
```

**NOT OK**:

```
$ unzip -t demo.zip
Archive:  demo.zip
    testing: demo/                    OK
    testing: demo/curation/           OK
    testing: demo/source/             OK
    testing: demo/annotation/         OK
    testing: demo/exportedproject8681420238631463205.json   OK
    testing: demo/log/                OK
    testing: demo/annotation_ser/     OK
    testing: demo/curation_ser/       OK
    testing: demo/event.log           OK
    testing: demo/curation/Mockingjay2.tsv/   OK
    testing: demo/source/Mockingjay2.tsv   OK
    testing: demo/annotation/Mockingjay2.tsv/   OK
    testing: demo/log/project-12.log   OK
    testing: demo/annotation_ser/Mockingjay2.tsv/   OK
    testing: demo/curation_ser/Mockingjay2.tsv/   OK
    testing: demo/curation/Mockingjay2.tsv/CURATION_USER.bcas   OK
    testing: demo/annotation/Mockingjay2.tsv/anno2.bcas   OK
    testing: demo/annotation/Mockingjay2.tsv/admin.bcas   OK
    testing: demo/annotation/Mockingjay2.tsv/anno1.bcas   OK
    testing: demo/annotation_ser/Mockingjay2.tsv/admin.ser   OK
    testing: demo/annotation_ser/Mockingjay2.tsv/INITIAL_CAS.ser   OK
    testing: demo/annotation_ser/Mockingjay2.tsv/anno1.ser   OK
    testing: demo/annotation_ser/Mockingjay2.tsv/anno2.ser   OK
    testing: demo/curation_ser/Mockingjay2.tsv/CURATION_USER.ser   OK
```

You can see that in the second NOT OK sample, there is a leading "demo" folder.

**Comment by aakum03** [comment]
@reckart My directory structure is the first one (content is the root of the zip folder)

**Comment by reckart** [comment]
Then can you please provide the full error stack trace from the server log / console that is written there when this error appears in your UI?

**Comment by reckart** [comment]
> My purpose is that I want to be able to import pre-annotated documents into inception from a different (non-inception supported) format for annotators to further annotate, so I will need to parse and generate my own .ser files and then compress and import it into inception.

I think you can import the ser files on the documents panel in the project settings choosing "UIMA Binary CAS" as format.

**Comment by reckart** [comment]
... or do you need to import different pre-annotated files for each user?

**Comment by aakum03** [comment]
> 
> 
> Then can you please provide the full error stack trace from the server log / console that is written there when this error appears in your UI?

I'm not sure where to see the log files. I'm currently running inception locally using the inception-app-standalone-0.14.3.jar.

> 
> 
> ... or do you need to import different pre-annotated files for each user?

Yes, I will need to import different pre-annotated files. I want to be able to generate these project files (.zip) that contain these pre-annotated files and then import these projects into inception for further annotation. Doing it manually via the document panel will be difficult as I have a large number of documents/user/project combinations.

**Comment by jcklie** [comment]
Can you share us an example file?

**Comment by aakum03** [comment]
Here is the original zip file (that works):
[A_project_2020-03-16_1223.zip](https://github.com/inception-project/inception/files/4351464/A_project_2020-03-16_1223.zip)

And here is the rezipped file that returns the error(exact same contents and directory structure):
[REZIPPED_A_project_2020-03-16_1223.zip](https://github.com/inception-project/inception/files/4351465/REZIPPED_A_project_2020-03-16_1223.zip)

**Comment by jcklie** [comment]
Which operating system are you running INCEpTION on?

**Comment by jcklie** [comment]
@reckart When I debug it, then I see that in `AnnotationDocumentExporter::importAnnotationDocumentContents`, the `entryName` is `annotation_ser/admin.tsv/`. The ending slash messes the following logic up I think. I use Windows.

**Comment by aakum03** [comment]
I run it on Windows

**Comment by jcklie** [comment]
I think I found the error, it hopefully is fixed in the next INCEpTION release (next week or so). You can try to build it locally to test it.

**Comment by reckart** [comment]
Should be fixed by https://github.com/webanno/webanno/issues/1641.

**Comment by aakum03** [comment]
@reckart @jcklie I would like an update on when the next inception release will happen

**Comment by jcklie** [comment]
We already releaed 0.15.0 with should fix this issue.

**Comment by aakum03** [comment]
Thanks. I'm not sure how I missed it.
