### ISSUE TITLE
Document Status not displayed properly on Monitoring page

### ISSUE THREAD

**Issue by llaska** [inception-project/inception#1641]
**Describe the bug**
We have some 35 users in one of our projects, so the name list ("Documents finished") pushes down the "Document status" pane and it's impossible to see anything. The scrollbar doesn't help.

**Expected behavior**
Be able to resize Documents finished/ Progress/ Document status frames.

**Screenshots**
![DocumentStatusBug](https://user-images.githubusercontent.com/61777631/76842870-9f201980-6843-11ea-8568-e08e8ab48e07.png)

**Please complete the following information:**
 - Version and build ID:  0.14.3 (2020-02-04 16:28:25, build 7f794ab99fd2695ac9d5ed831b7e3ea92b511be5)
 - OS: Windows 10
 - Browser: Chrome, Firefox

**Comment by reckart** [comment]
Ok, thanks for reporting!

**Comment by reckart** [comment]
Upstream issue: https://github.com/webanno/webanno/issues/1638

**Comment by reckart** [comment]
Resizing not, but I have changed the layout such that the content scrolls reasonably.
