### ISSUE TITLE
checking annotation: internal error

### ISSUE THREAD

**Issue by HelenaSabel** [inception-project/inception#1643]
**Describe the bug**
Sometimes, when an administrator user opens a file annotated by another user through the Annotation environment, an error appears (either “Error:null” at the bottom of the page or “Internal error”).
The project log does not present any errors at all. However, the actions are registered under another username (an annotator with no administration rights).
For example, at the time when an administrator opened one of the files of the annotator `mgraa` this was recorded in the log file:
`2020-03-18 21:21:57,469 [sreymon9] Upgraded CAS of user [mgraa] for document [saturae_book-4.txt](40) in project [WoPoss](1)
2020-03-18 21:21:57,473 [sreymon9] Read constraints set [constraints_woposs.txt] in project [WoPoss](1)`

However, `sreymon9` was not the user that was implementing that action. `sreymon9` is an annotator (not the administrator).

**To Reproduce**
1. Administrator user selects “Annotation” in the dashboard.
2. In the left-side panel, an annotator user is selected and in the right-side panel, a document that has been annotated by said user (whose title is blue).
3. Sometimes just after opening, sometimes when jumping to the next section, an error appears.
4. The log file records the activity under a different user (not the administrator).

**Expected behavior**
The user with the administrator rights should be able to browse the document annotated by another user (reading view).

**Please complete the following information:**
 - Version and build ID: INCEpTION -- 0.14.2 (2019-12-31 15:54:23, build a44b4c76b19fcc3d0a58e75a82aafdd96a564500) 
 - OS: Linux (Ubuntu 18.04)
 - Browser: Firefox

**Comment by UWinch** [comment]
@HelenaSabel I'm having trouble reproducing this error. You say it happens sometimes: how often is this and did you notice anything else at the time that the error occurred? Which rights does the user _sreymon9_ have? What other users do you have configured (e.g. how many curators, admins) and what is your typical workflow e.g. does everyone work at the same time or do annotators finish their work and then a curator goes through?

Thanks.

**Comment by HelenaSabel** [comment]
Thank you so much for looking into this!

I cannot detect a pattern. Sometimes, logging out and logging in again works, but sometimes it doesn’t. Sometimes it doesn’t work in the morning, but it works normally in the afternoon. It doesn’t seem to be related either to the number of users connected (there is usually not more than three people at the same time). 

Concerning the workflow, the annotator finishes the annotation task and then one curator goes through it. Sometimes the file is already “finished” (locked) and the curator needs to open it through the annotation environment to check the chain layers, and other times it is a first supervision of the file before it is “finished” (locked). Thus, the status of the file is not the source of the issue.

Concerning the users, the following screenshot shows the users of the project.

![users](https://user-images.githubusercontent.com/8516387/77191883-ef190d80-6adb-11ea-81dc-5e1377fe914a.png)

Now, as an administrator, I made some changes regarding the users, and these are the corresponding log entries.

![log-users](https://user-images.githubusercontent.com/8516387/77191864-e7596900-6adb-11ea-96e2-7ba7e5303971.png)

All log entries, since March 10th  are recorded as the user `sreymon9` which, as you can see in the previous snapshot, only has annotation rights. I don’t know if this could be somehow related to the other problem, since the log file does not present any errors at all.

**Comment by UWinch** [comment]
@reckart do you have an idea for this?

**Comment by reckart** [comment]
You can try adding the following line to the `settings.properties`

```
debug.showExceptionPage=true
```

Then instead of an "internal error", you should get an error page with additional information that might be helpful. Won't help against the "Error:null" though.

> All log entries, since March 10th are recorded as the user sreymon9 which, as you can see in the previous snapshot, only has annotation rights.

If you deliberately log in as another user (i.e. not `sreymon9`) and open some document for annotation, there should be a line logged such as

```
2020-04-04 13:37:55 [http-nio-8080-exec-1] INFO [USERNAME] AnnotationSchemaServiceImpl - Upgraded CAS of user [USERNAME] for document [16688807.json](25938) in project [#0 Bootstrap migration](244)
```

Does the`USERNAME` here also appear as `sreymon9` or as the user you logged in as?

**Comment by UWinch** [comment]
@HelenaSabel Could you get some more information on the bug with the option that Richard suggested?

**Comment by UWinch** [comment]
Are there any news on this error or can the issue be closed?

**Comment by HelenaSabel** [comment]
Apologies for taking so long in replying back. 
We have a new workflow and this is no longer an issue: We reupload the annotated files, so a “curator” user can go through these file in the annotation environment (the reason why the curation environment was not appropriate for us was the lack of visibility of chain layers)

**Comment by UWinch** [comment]
Great, that it is working for you. Sorry, we couldn't be of more help.
