### ISSUE TITLE
AL does not show history

### ISSUE THREAD

**Issue by UWinch** [inception-project/inception#1648]
**Describe the bug**
The active learning sidebar does not show the history any more.

**To Reproduce**
1. Enable a recommender
2. Open the active learning sidebar and start a AL session

**Expected behavior**
I think until 0.15.0 the last suggestions in the AL session were shown.

**Screenshots**
![AL_history](https://user-images.githubusercontent.com/29500351/77293617-f5c5a180-6ce2-11ea-8f50-29f576e27fed.png)

**Please complete the following information:**
 - Version and build ID: 0.15.0
 - OS: Ubuntu
 - Browser: Chrome

**Additional context**

**Comment by reckart** [comment]
I updated the al history to BS4 so it was still working then-maybe just a CSS/SASS issue? Try checking if the html is on the page and just not visible.

**Comment by UWinch** [comment]
Seems it takes some time to populate, I was just too impatient. Keeping the issue open in case we want to look into making the reaction faster for other impatient people.

**Comment by reckart** [comment]
As soon as you acccept/reject something, it should be updated. I'm not aware that there should be any delay or time it requires to populate...

**Comment by reckart** [comment]
Nobody has ever noticed this again and/or complained about it. So I am assuming that this has been resolved. If not, please re-open.
