### ISSUE TITLE
Can export annotations only after opening document on curation page

### ISSUE THREAD

**Issue by mbugert** [inception-project/inception#1649]
**Describe the bug**
I'm not sure if this is a bug or just user error.
When exporting curated documents from the project settings page, only those documents appear in the ZIP file which have been opened previously in the curation view. Completing the curation of a document on the monitoring page is not sufficient.

**To Reproduce**
1. Create new project, add a document, create some annotations, mark the document as finished
2. On the monitoring page, click twice on the document in the curation column (green checkmark appears)
3. "Export curated documents" in the project settings (format does not matter)
4. The ZIP file is empty
5. On the curation page, open the document (do nothing else)
6. "Export curated documents" in the project settings
7. The ZIP file contains the annotated document

**Expected behavior**
No need for step 5.

**Please complete the following information:**
 - Version and build ID:  0.15.0-SNAPSHOT (2020-03-23 10:16:14, build 47206d953c93ca1b4a52f193b5688407333dff8f)
 - OS: Ubuntu 18.04
 - Browser: FF

**Comment by reckart** [comment]
One could argue that the files you just marked as "curation complete" haven't actually been curated.

What would you expect these uncurated files to look like in the export?

**Comment by mbugert** [comment]
Okay, I got it now.

I have an annotation project where there is only one annotator per document. There are no mismatching annotations to resolve during curation, so I only want to quickly accept all annotations. I had hoped that setting the checkmark for all documents on the monitoring page would do that for me.

The culprit is the :heavy_check_mark:  symbol, it doesn't represent well what is happening in the tool. I think a better solution would be to rename the column to "Curators" and to use a :lock: symbol instead.

**Comment by jcklie** [comment]
If you have only one annotator per document, why dont you just export the project in the project settings instead going to the curation?

**Comment by mbugert** [comment]
Because the file structure in the full project export is more complex (nested ZIP files and less predictable file names).
