### ISSUE TITLE
Project import dialog is missing checkboxes

### ISSUE THREAD

**Issue by mbugert** [inception-project/inception#1653]
**Describe the bug**
The "Import Project(s)" dialog is missing checkboxes.

**To Reproduce**
Click on the import button on the project settings page.

**Expected behavior**
Checkboxes are there.

**Screenshots**
![Screenshot_2020-04-03_13-35-19](https://user-images.githubusercontent.com/23331603/78356812-96a04080-75b0-11ea-92fb-4f38bc55601f.png)

**Please complete the following information:**
 - Version and build ID: 0.15.0 (2020-04-02 11:37:08, build c95448d453aee93cfaafc6a40fbe51cbe2f5728a) 
 - OS: Ubuntu 19.10
 - Browser: FF and Chrome

**Comment by reckart** [comment]
I can see the effect on our server even with Safari, but when I try to reproduce it locally, the checkboxes appear - I have tried running locally as Spring application (in Eclipse) as well as within Tomcat (Eclipse).

**Comment by reckart** [comment]
Actually, the bug is not that the checkboxes are missing - the bug is that the labels are present. Only an instance admin (global `ROLE_ADMIN` may use these options) - a regular user with the permission to create projects (global `ROLE_PROJECT_CREATOR`) is not allowed to use them.

**Comment by reckart** [comment]
Fixed upstream.
