### ISSUE TITLE
Importing Wildlife ontology fails

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#1661]
**Describe the bug**
Importing Wildlife ontology fails

When pressing the "add" button during the KB creation, I get

`Error: Illegal char <:> at index 5: https://www.bbc.co.uk/ontologies/wo/1.1.ttl`

**Please complete the following information:**
 - Version and build ID: master
 - OS: Windows
 - Browser: chrome

**Comment by reckart** [comment]
The wildlife ontology seems no longer to be available online.
