### ISSUE TITLE
Sentence Segmentation ?

### ISSUE THREAD

**Issue by a-tsioh** [inception-project/inception#1665]
**Is your feature request related to a problem? Please describe.**

I'm running into issues of sentence segmentation when users import plain-text files. Sentences with abbreviations tend to be splitted into multiple sentences, preventing some annotation, and this create discrepancies with recommenders such as CoreNLP.

**Describe the solution you'd like**

Is it configurable in any way ? Maybe pointing to an external service like recommenders.

**Describe alternatives you've considered**

Alternative option is to pre-process the documents and upload more structured data, but this make plain text import hazardous to use for me.
(I may also have missed something in the documentation, I've seen nothing about this kind of issue)

**Comment by UWinch** [comment]
Hi @a-tsioh, the segmentation is in fact not configurable and your best option is as you suggested to pre-process your text files with segmentation before the import into INCEpTION. If your pre-processed files contain Sentence or Token annotations, these can be imported and displayed in INCEpTION.

**Comment by jcklie** [comment]
If you preprocess, then the easiest way is to have one sentence per line and import as Plaintext (one sentence per line) or so.

**Comment by a-tsioh** [comment]
Ok, I will do this for now, thanks !
