### ISSUE TITLE
Annotators cannot mark documents with specific features as finished

### ISSUE THREAD

**Issue by mbugert** [inception-project/inception#1666]
**Describe the bug**
Documents with required String primitive features in a document-level layer cannot be marked as finished by annotators.

**To Reproduce**
1. Create new project, add plaintext document
2. Add new layer with type *Document metadata*
3. Add one feature with type `Primitive: String`, and enable the *required* checkbox
4. Go to annotation page, open the document, fill the feature of the document metadata layer with content
5. Attempt marking the document as finished
6. Inside the modal window the message ` Error: Type [webanno.custom.DocLevel] is not an annotation type ` appears and the document isn't marked as finished. For some reason, the same document can be marked as finished on the monitoring page.

**Expected behavior**
Marking document as finished should work in this case. 

**Please complete the following information:**
 - Version and build ID:  0.16.0-SNAPSHOT (2020-04-14 23:11:04, build fd1e33890850894aee073eaae81e017ab7454b98)
 - OS: Ubuntu 19.10
 - Browser: FF 75.0

**Comment by UWinch** [comment]
Fixed in https://github.com/webanno/webanno/issues/1658
