### ISSUE TITLE
NPE when deleting feature and recreating with same name

### ISSUE THREAD

**Issue by mbugert** [inception-project/inception#1667]
**Describe the bug**
It's unlikely this will ever happen to anyone but it's reproducible so let's go.

**To Reproduce**
1. Create project, add plaintext document
2. Create layer with type document metadata
3. Add feature named `AStringFeature`, do not mark it as required
4. On annotation page, add some text to this feature
5. Mark document as finished
6. In project settings, delete the feature, then recreate it with the same name as in step 3
7. Open the document again on annotation page, click on the tags-symbol to unfold the document metadata
8. See wicket exception with attached stacktrace [stacktrace.txt](https://github.com/inception-project/inception/files/4486298/stacktrace.txt)

**Expected behavior**
No NPE in this case. I would expect that the previously entered feature value is gone since the feature was deleted midway through the process.

**Please complete the following information:**
 - Version and build ID:  0.16.0-SNAPSHOT (2020-04-14 23:11:04, build fd1e33890850894aee073eaae81e017ab7454b98) 
 - OS: Ubuntu 19.10
 - Browser: FF 75.0

**Comment by reckart** [comment]
In such a case, the annotation editor should display a message that there was a concurrent modification and that the document as to be re-opened.

**Comment by mbugert** [comment]
I didn't mention it in the steps above, but this issue can be reproduced while working in a single tab. One leaves the annotation page in between steps 5 and 6 and reopens it in step 7. This is not a case of concurrent modification as far as I can tell.

**Comment by reckart** [comment]
It is a concurrent modification situation. Please read the text in the confirmation dialog that pops up when you delete a feature.

**Comment by mbugert** [comment]
Maybe I'm still not understanding it correctly, but how can it be a case of concurrent modification if I am the only user working on the project with no annotation editor open by anyone during the feature removal? I thought that in step 7, the freshly opened annotation editor would already load the post-feature-removal CAS.

**Comment by reckart** [comment]
Thanks for being persistent. I agree you are right. Since the annotation page is re-opened in step 7, there should not be an NPE.

**Comment by reckart** [comment]
I have followed the instructions, but I could not reproduce the problem. If I follow the instructions, I simply see an empty feature in step 7. So whatever the problem was, it seems to have been fixed since its initial reporting.
