### ISSUE TITLE
Curation won't start properly

### ISSUE THREAD

**Issue by LisaEggert** [inception-project/inception#1669]
**Describe the bug**

When I try to load an annotated text (approx. 3200 lines and annotation on 16 layers) the curation mode won't start. By now I have waited for about 2 hours - without any progress.

We have had this problem with an earlier version (it must have been the one before 0.12.0) and was fixed within version 0.12.0. 
Maybe the bug "remigareted" to version we use (0.14.3).
The short answer could be that we simply have to update our installation ;)

Thank you and stay healthy!

**To Reproduce**
1. Go to 'Curation'
2. Click on 'file to open it'
3. See error: Won't open in curation-mode

**Expected behavior**
That file opens in curation mode within a manageable time.

**Screenshots**

**Please complete the following information:**
 - Version and build ID:  INCEpTION -- 0.14.3 (2020-02-05 14:21:11, build 7f794ab99fd2695ac9d5ed831b7e3ea92b511be5) 
 - OS: Windows
 - Browser: firefox

**Additional context**

**Comment by reckart** [comment]
Upstream issue: https://github.com/webanno/webanno/issues/1340
