### ISSUE TITLE
Tutorial: does not select recommender

### ISSUE THREAD

**Issue by UWinch** [inception-project/inception#1680]
**Describe the bug**
The tutorial fails on the recommender selection: it selects `tagsets` from the settings tabs instead of the `recommenders`tab. 

**To Reproduce**
1. Go through the tutorial until the recommender creation.

**Expected behavior**

**Screenshots**
![tutorial_bug](https://user-images.githubusercontent.com/29500351/80495854-bab13080-8968-11ea-9891-8232f5aad785.png)

**Please complete the following information:**
 - Version and build ID: 0.16.0
 - OS:ubuntu
 - Browser: chrome

**Additional context**

**Comment by reckart** [comment]
@UWinch can this be fixed for 0.16.0, maybe in conjunction with also fixing the tutorial breaks caused by #1668?

**Comment by UWinch** [comment]
@reckart I'm pretty sure that this has something to do with webanno changes, it's not in the stable branch. I'm looking into both problems at the moment to hoepfully fix for 0.16.0

**Comment by UWinch** [comment]
Fixed in https://github.com/inception-project/inception/pull/1676
