### ISSUE TITLE
Add prometheus monitoring

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#1681]
**Is your feature request related to a problem? Please describe.**
We want to expose interesting metrics via Prometheus.

- [x] Memory usage
- [x] Number of users
- [x] Recommenders running
- [x] Number of documents

**Describe the solution you'd like**
Add prometheus monitoring.

**Additional context**
There is also a JMX exporter for Prometheus. 

https://www.openlogic.com/blog/prometheus-java-monitoring-and-gathering-data

**Comment by reckart** [comment]
At which level do you want to measure "number of documents"? Globally? By Project?

By number of users, you mean active users (logged in users with an active session), enabled users, or generally the total number?

**Comment by jcklie** [comment]
I would always measure globally, as it is difficult to visualize that per project. I would measure all 3 user states that you mentioned.

**Comment by UWinch** [comment]
Keeping the issue open, because we want to refine metrics, add more.

**Comment by reckart** [comment]
Let’s close this issue and create a new one (or multiple new ones) for further improvements.

**Comment by UWinch** [comment]
ok
