### ISSUE TITLE
Limit amount of active users

### ISSUE THREAD

**Issue by An-Feli** [inception-project/inception#1683]
**Is your feature request related to a problem? Please describe.**
We don't want INCEpTIOn to give bad user experiences to our users, esp. when many will soon work simultaiously due to Projektpratikum. We want to find INCEpTIONs performancelimit (and may raise it then.)

**Describe the solution you'd like**
- Limit the accepted ammount of users (at a time - not gerneally).
- Slowly increase this limit until we have found the performancelimit.
- Decrease the limit again and keep it under the performancelimit.

**Describe alternatives you've considered**
//

**Additional context**
//

**Comment by reckart** [comment]
Upstream issue resolved: https://github.com/webanno/webanno/issues/1700
