### ISSUE TITLE
Whitelabel Error

### ISSUE THREAD

**Issue by norawebbwilliams** [inception-project/inception#1692]
**Describe the bug**
After Inception loads, I get an error from browsers when trying to access the program. A screenshot of the error is below; I get the same error from multiple browsers. 

**Screenshots**
![whitelabel_error](https://user-images.githubusercontent.com/22669329/81007126-ac5a8d00-8e1e-11ea-9cf4-73b05915b657.JPG)

**Please complete the following information:**
 - Version and build ID: 0.15.2
 - OS: Windows 10
 - Browser: Chrome, Firefox, Edge

Thanks for your help on this! Any advice would be much appreciated.

**Comment by reckart** [comment]
Hm, I thought we had tackled that pesky Windows issue... thanks for letting us, know.

How are you starting the application? Using a double-click or from the command line? If you start form the command line, do you get any stack trace printed to the console that you might provide us with?

**Comment by reckart** [comment]
Which Java version are you using to run the application?

**Comment by norawebbwilliams** [comment]
I'm using Version 8 Update 251 of Java (the latest update). And I've been starting it with the double-click, but just ran it from the command line and will attach everything that printed to the console below. This line stood out to me: 

2020-05-04 18:22:11 ERROR [SYSTEM] [dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Filter execution threw an exception] with root cause
java.lang.UnsupportedOperationException: Platform windows 10:x86 not supported

Maybe windows 10 is just not a good option? For what it's worth, it does load in Windows 8.1 without any trouble. Thanks for the quick reply. 

[error_traceback.txt](https://github.com/inception-project/inception/files/4578071/error_traceback.txt)

**Comment by reckart** [comment]
I have added this to 0.15.3 for the moment - the idea is not necessarily fixing this (fix needs to go into JSass anyway), but rather to document in the system requirements that running on Windows 10 is presently not supported.... maybe there is an updated JSass we can use ... let's see.

**Comment by reckart** [comment]
Correction: Windows 10 should be working but according to the JSass homepage, 32bit versions of Windows are not supported. So that needs to go into our system requirements.

Cf. https://gitlab.com/jsass/jsass
