### ISSUE TITLE
Adding new tags not possible

### ISSUE THREAD

**Issue by llaska** [inception-project/inception#1693]
**Describe the bug**
We have a string feature bound to a tagset, where adding new tags is enabled.
Still, when I try to enter a new tag in the corresponding slot, nothing happens and I see only the layer label over the selected text span.

**Expected behavior**
Be able to enter new tags from the Annotation pane when "Annotators may add new tags" is enabled.

**Screenshots**

**Adding enabled:**

![1-Tagset-details](https://user-images.githubusercontent.com/61777631/81270857-02644600-9054-11ea-9757-d206dcd001d8.png)

**Feature settings:**

![2-Feature-tagset](https://user-images.githubusercontent.com/61777631/81270862-02fcdc80-9054-11ea-9048-1d8eff4da39c.png)

**No tag added:**

![3-New-tag-impossible](https://user-images.githubusercontent.com/61777631/81270864-03957300-9054-11ea-875e-9bd5174ff8c6.png)

**Please complete the following information:**
 - Version and build ID: 0.15.2 (2020-04-20 13:43:52, build 3f14b8c32e57ce44cb7f470c54307d66960a08b6) 
 - OS: Windows
 - Browser: Firefox

**Comment by reckart** [comment]
The value in the annotation in the left circle should be updated:
* if you select a new value on the right
* if you enter a new value and press enter
* if you enter a new value and make the input focus (text cursor) leave the field

**Comment by reckart** [comment]
If you perform any of these actions above - does the bubble still not update if you reload the page?

**Comment by llaska** [comment]
>     if you select a new value on the right

Yes, true, the thing is we want to be able to add a value that is not yet listed in the tagset.

>   if you enter a new value and press enter

It works once. On the second try we get "Unable to load data: IOException: There was a concurrent change to the document. Re-open the document to continue editing." Reopening the document does not help, the bubble is not updated, the value is not added to the tagset.
 

> if you enter a new value and make the input focus (text cursor) leave the field

This works fine.

**Comment by reckart** [comment]
Ok, thanks. We'll look into it.

**Comment by jcklie** [comment]
I can confirm that It works when using tab but not enter. Changing focus also does not create a new tag (e.g. creating a new annotation)

**Comment by jcklie** [comment]
setFeatureValue is not called when pressing enter

**Comment by jcklie** [comment]
FeatureUpdate::onUpdate is not called when pressing enter

**Comment by reckart** [comment]
I have:

* create a new project
* imported a document
* opened the **Named Entity tagset** on the **Tagsets** pane in the project settings
* ticked **Annotators may add new tags**
* clicked **Save**
* opened the document for annotation
* created a named entity annotation
* clicked into the **value** feature and entered `NOM` and pressed enter
* clicked into the **value** feature and entered `MUM` and clicked outside the field to remove the focus
* both the `NOM` and `MUM` tags were successfully added to the **Named Entity tagset**

@jcklie how to you reproduce the issue?

**Comment by reckart** [comment]
Hm, ok... works in Safari 13.1 but doesn't seem to work in Chrome 83.0.4103.61 and also not in Firefox 76.0.1

**Comment by reckart** [comment]
Fixed upstream: https://github.com/webanno/webanno/pull/1693
