### ISSUE TITLE
"MERGE-ALL"-feature doesn't work

### ISSUE THREAD

**Issue by LisaEggert** [inception-project/inception#1694]
**Describe the bug**
In earlier versions of INCEpTION there was a feature called "MERGE-ALL" for the curation-mode to merge all annotations of a certain annotator on a certain layer. When you right-clicked on the annotation of a certain annotator to open a drop-down-menu to merge all those annotations in the document. Now the drop-down-menu doesn't open.

**To Reproduce**
1. Go to Curation mode and open a document
2. Rightclick on an annotation of a certain user
3. See error: Drop-Down-Menu doesn't open

**Expected behavior**
The Drop-Down-Menu should open

**Screenshots**

**Please complete the following information:**
 - Version and build ID: 0.15.0 (2020-04-20 13:56,24, build c95448d453aee93cfaafc6a40fbe51cbe2f5728a)
 - OS: Windows
 - Browser: firefox

**Additional context**

**Comment by reckart** [comment]
Thanks for the report. I can reproduce it.

**Comment by UWinch** [comment]
Fixed upstream
