### ISSUE TITLE
Panel on KB UI with Search functionality for KB entries 

### ISSUE THREAD

**Issue by naveen2507** [inception-project/inception#170]
- [x] Search over KB annotations in search side bar
- [x] Panel on KB UI to show the instance annotations on text
- [x] Utility class for indexing of KB Linked concepts
- [x] List data from KB linking on KB UI

**Comment by naveen2507** [comment]
Done PR #223

**Comment by reckart** [comment]
@naveen2507 the listing of concept / instance mentions is rather confusing:

* the mentions list is always in in the middle column of the screen which generally contains information about the class - even if it shows instance mentions when an instance is selected. Would have expected separate mention lists, one in the "class" column and one in the "instance" column. I can understand that a single list might be more convenient, but then I believe it should be spanning the "class" and the "instance" columns, i.e. appear below both of them.
* the mentions list shows only the annotated word - no left or right context, and no information about in which document the annotation was found.

**Comment by naveen2507** [comment]
> the mentions list is always in in the middle column of the screen which generally contains information about the class - even if it shows instance mentions when an instance is selected. Would have expected separate mention lists, one in the "class" column and one in the "instance" column. I can understand that a single list might be more convenient, but then I believe it should be spanning the "class" and the "instance" columns, i.e. appear below both of them.

@reckart What happens now is, when we click on instances it shows the mention for the instances and as we discussed initially about the possibility of including parent concept for search here once we include parent and sub-super class concept thingy in KBSI. 

WDYS? Should we have two separate **Mentions** for concept and instances OR include the search to one with the parent concept for instance and subclass for concept.

**Comment by reckart** [comment]
This is what we have now

```
+---+------------+----------+
|   | Class      | Instance |
|   |            |          |
|   |------------+----------|
|   | Class      | Instance |
|   | Stmts      | Stmts    |
|   |------------|          |
|   | Mentions   |          |
|   | (cls/inst  |          |
+---+-----------------------+
```

I could imagine this:

```
+---+----------+----------+
|   | Class    | Instance |
|   |          |          |
|   |----------+----------|
|   | Class    | Instance |
|   | Stmts    | Stmts    |
|   |----------|----------|
|   | Mentions | Mentions |
|   | Class    | Instance |
+---+---------------------+
```

or 

```
+---+----------+----------+
|   | Class    | Instance |
|   |          |          |
|   |----------+----------|
|   | Class    | Instance |
|   | Stmts    | Stmts    |
|   |---------------------|
|   | Mentions            |
|   | (class or instance) |
+---+---------------------+
```

WDYT?

**Comment by naveen2507** [comment]
We can change it too this one, as it gives user more privilege to see the mentions for instance and class separately 
``` 
+---+----------+----------+
|   | Class    | Instance |
|   |          |          |
|   |----------+----------|
|   | Class    | Instance |
|   | Stmts    | Stmts    |
|   |----------|----------|
|   | Mentions | Mentions |
|   | Class    | Instance |
+---+---------------------+
```
