### ISSUE TITLE
Support advanced AJP secret

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#1701]
**Is your feature request related to a problem? Please describe.**
To connect to the application using AJP, it should be possible to specify a shared secret.

**Additional context**
This was already implemented in WebAnno but not ported here yet.

**Comment by UWinch** [comment]
Keeping this issue open, so we don't forget to test

**Comment by reckart** [comment]
Since this has been merged, let's close it for the version in which it was release. If we discover a problem with the implementation, we should then open a new bug to fix it.
