### ISSUE TITLE
Inception not loading

### ISSUE THREAD

**Issue by lmompela** [inception-project/inception#1703]
**Describe the bug**
Whether I double-click on the executable JAR file or launch it through powershell, the application keeps on loading and does not actually launch itself.

**To Reproduce**
Double-click on the executable JAR or launch it via the command "java -jar inception-app-standalone-0.15.2.jar

**Expected behavior**
Expected to launch

**Screenshots**
![image](https://user-images.githubusercontent.com/49000319/81956848-cdb73800-95d9-11ea-90c5-5b90164e423d.png)

**Please complete the following information:**
 - Version and build ID: inception 0.15.2
 - OS:Windows
 - Browser: N/A

**Comment by jcklie** [comment]
There are at least two ways to solve the problem. Do you already have data in the INCEpTION that you want to not loose? If you have no data you care about, just delete the `.inception` folder in your home folder.

**Comment by lmompela** [comment]
Yes I have annotations I started. I don't mind losing them but would rather not. As well, if it happens again when I have more annotations I would like to be able to troubleshoot without loss of data, if possible.

**Comment by jcklie** [comment]
This problem should not occur, it is normally caused if the jar crashes or is stopped during startup. You need to fix the database by hand by removing the log in there. Do the following:

1. Download DBeaver CE from https://dbeaver.io/download/ . There is a standalone version that does not requiring installing stuff
2. Open it, create a new connection with "HSQL Embedded". As path, use C:\Users\klie\.inception\db\inception and change your username .

![image](https://user-images.githubusercontent.com/934600/81964960-aa12e280-9617-11ea-804d-c8ed179980fe.png)

3, Find the `DATABASECHANGELOGLOCK` table in the left menu under `Public -> Public -> Tables` and switch to the data view.

4. Remove the lock by finding the It should look like this (unticked lock)

![image](https://user-images.githubusercontent.com/934600/81964903-91a2c800-9617-11ea-91aa-083aed6899f5.png)

**Comment by lmompela** [comment]
Perfect it worked ! Thanks

**Comment by reckart** [comment]
@lmompela make regular exports of your project - in particular if you are using the embedded DB and not MySQL. It is known that people have already lost access to their data with the embedded DB e.g. because their computer crashed and left a corrupted database behind.
