### ISSUE TITLE
YAGO 3 SPARQL endpoint down

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#1708]
**Describe the bug**
The YAGO SPARQL endpoint currently shipping as a default profile in INCEpTION is down. There is a replacement: https://github.com/yago-naga/yago3/issues/5#issuecomment-630651560

**Expected behavior**
INCEpTION KB default profiles should all work.

**Comment by jcklie** [comment]
The schema between v3 and v4 is different, so we disabled the KB profile until we fix it for real.
