### ISSUE TITLE
PDF setting leading to internal error and no way out

### ISSUE THREAD

**Issue by jackmen** [inception-project/inception#1721]
**Describe the bug**
I uploaded some xmi documents to an inception project in the latest inception version (0.16.0-SNAPSHOT (2020-05-26 12:55:23, build 71d4111ec620cf6b7ea1513f5380a0e5e164321e)).

In the annotation view under settings I wanted to present my documents as PDF (just out of curiosity) and I was confronted with this error message:

"Incompatible file format, the original document is not a pdf file, but a xmi file. Switch to another editor via the settings dialog accessible from the action bar above"

This makes sense, but I was not able to access the settings, but was forwarded to an "internal error" page. Logging out of the project and inception itself, didn't solve it.

Also, I was not able anymore to open any of the other documents to annotate them, making it impossible to go on working.

Even deleting all documents and fresh upload, the error remained and I cannot access any document. 

**To Reproduce**
1. Upload xmis to project
2. Go to annotation view
3. Try to represent doc as PDF

**Please complete the following information:**
 - Version and build ID: 0.16.0-SNAPSHOT (2020-05-26 12:55:23, build 71d4111ec620cf6b7ea1513f5380a0e5e164321e
 - OS: [Linux]
 - Browser: [e.g. chrome]

Thanks for looking into it!

**Comment by reckart** [comment]
Thanks for reporting. To recover from your situation, please look into your INCEpTION data folder. Under the `repository` folder, there are folders for the individual projects you have. In each of these project folders, there is a `settings` folder which contains user-specific `annotation.properties` files. If you locate these files for your project and remove them or if you remove the `annotation.editor=...`line, it should switch back to the brat-based editor and you should be able to continue working.

**Comment by jcklie** [comment]
Should be solved in master and the fix will be backported to 0.16.x .

**Comment by jackmen** [comment]
Perfect! Thanks  a lot!
