### ISSUE TITLE
Dashboard link in navbar is missing project identifier

### ISSUE THREAD

**Issue by mbugert** [inception-project/inception#1722]
**Describe the bug**
Clicking on "Dashboard" in the navigation bar sends the user to the dashboard of the project he/she last interacted with, not the one the currently opened page belongs to.

**To Reproduce**
1. Open projects page, have at least two projects
2. Open the dashboard of each project in a new tab (ctrl-click)
3. In each tab, navigate to the project settings - observe that the h1 with the project name is still correct in both tabs
5. In both tabs, click on Dashboard in the navigation bar
6. Both tabs end up on the dashboard of the project whose project settings you opened last.

**Expected behavior**
Dashboard button always points to the dashboard of the currently opened project

**Please complete the following information:**
 - Version and build ID: 0.17.0-SNAPSHOT (2020-06-02 18:45:15, build f542eed5a1050fa440b599e37832ba6c856ad0f6)
 - OS: Ubuntu 20.04
 - Browser: FF 76.0.1

**Comment by reckart** [comment]
Fixed since #1982 - Remove concept of "current project" from the session
