### ISSUE TITLE
Fast tabbed browsing lets users end up on wrong project page

### ISSUE THREAD

**Issue by mbugert** [inception-project/inception#1723]
**Describe the bug**
I wanted to export multiple projects in a row. I opened all projects in a separate tab, aimed for "Settings" on the dashboard in the first tab and then did Mouse1, Ctrl+Tab, Mouse1, Ctrl+Tab, and so on to navigate all tabs at once. In several tabs I ended up in the project settings of a different project.

**To Reproduce**
1. Have n projects
2. Open each project dashboard in a separate tab
3. Quickly open project settings as described above
4. End up in the project settings of the same project in all tabs

**Expected behavior**
End up in the project settings of the correct project.

**Screenshots**
Sorry for the low frame rate.
![Peek 2020-06-02 19-28](https://user-images.githubusercontent.com/23331603/83551294-72a5a080-a508-11ea-97e1-159fe274561e.gif)

**Please complete the following information:**
 - Version and build ID:  0.16.0 (2020-05-25 17:05:02, build 65c5dae1b96ab538194873659ed59bb6b6bf4ec9) 
 - OS: Ubuntu 20.04
 - Browser: FF 76.0.1

**Additional context**
The server must take long enough on each request for this bug to appear. I only managed to reproduce this once on inception-experimental, 0.17.0-SNAPSHOT (2020-06-02 18:45:15, build f542eed5a1050fa440b599e37832ba6c856ad0f6) because this instance is running much faster than stable.

**Comment by reckart** [comment]
As of yet, INCEpTION is not meant to be opened in multiple tabs. That is simply not supported. One of the reasons is that the "current" project is stored as a session variable.

**Comment by mbugert** [comment]
I see, thanks.

**Comment by jcklie** [comment]
I tried to reproduce locally but I cannot click that fast; I get the correct settings each time. I also used google chrome to throttle to 10kb/s and add 500ms latency but I still get the correct tabs. I looked at the source of `ProjectPage` and did not find a reference to a global session variable, we get the project from the get parameter.

**Comment by reckart** [comment]
With the new URL concept, this can no longer happen.
