### ISSUE TITLE
Multi-Annotator Agreement

### ISSUE THREAD

**Issue by tilmanbeck** [inception-project/inception#1734]
**Is your feature request related to a problem? Please describe.**
When evaluating the inter-annotator agreement, I would also like to see multi-annotator agreement instead of only binary comparisons

**Describe the solution you'd like**
In the "Agreement" Tab of a project, I'd like to have the opportunity to display the agreement of multiple raters for those measures which allow this (e.g. generalized Cohen's k by Davis and Fleiss (1982) or Krippendorff's alpha). One way could be to add a checkbox option in the corresponding measure or add it as extra 'Measure ' in the 'Setting' tab.

**Describe alternatives you've considered**
The only alternative I see currently is to download the annotations and compute the multiple raters measures by myself which is time-consuming and cumbersome. Simply averaging the binary agreements does not follow the formula of the respective measures.

**Additional context**

**Comment by reckart** [comment]
With https://github.com/inception-project/inception/issues/4704 we can now get an agreement per document (over all annotators) and even a macro average over all documents. Does not work for Cohen, but for the other measures. I think that resolves the issue.
