### ISSUE TITLE
Add attributes for annotation

### ISSUE THREAD

**Issue by LabexOBVIL** [inception-project/inception#1735]
Hi
Thank you for this great project !
Can we add attributes for annotations in Inception? Example, for Named Entities Places, add sub labels: _Building, Admin, Path_, etc...

![image](https://user-images.githubusercontent.com/9264660/84594858-24bc6100-ae55-11ea-8c96-7a90c1cd45a9.png)

Thank you for your help !

**Comment by reckart** [comment]
The pre-defined `Named entity` layer cannot be modified. However, you can disable it and create your own `Entity` span layer and define on it any features/attributes that you want.

**Comment by LabexOBVIL** [comment]
Thank you for your answer !
