### ISSUE TITLE
Add "..." to abbreviated Layernames

### ISSUE THREAD

**Issue by An-Feli** [inception-project/inception#1748]
**Is your feature request related to a problem? Please describe.**
When annotated span is short, layernames are abbreviated in order to save space. I found this irritating (despite the color coding), assuming two annotationes of the same layer belong to two different things - while two of different ones look the same.

Example: 
SemPred => Sem
SemArg => Sem

**Describe the solution you'd like**
Add "..." to show name has been abbreviated.
Abbreviate only in case the abreviation + "..." is still shorter than actual name.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by reckart** [comment]
This issue needs to be addressed upstream in WebAnno. Please open an issue there and link it from here.

**Comment by UWinch** [comment]
Implemented upstream
