### ISSUE TITLE
Annotation page: toggling left sidebar makes brat editor disappear

### ISSUE THREAD

**Issue by mbugert** [inception-project/inception#1750]
**Describe the bug**
When folding or unfolding the left sidebar on the annotation page, the brat editor disappears. Does not happen to the HTML or PDF editors.

**To Reproduce**
1. Have project with documents, open annotation page with brat editor
2. Unfold left sidebar
3. Area where brat was is blank
4. Folding/unfolding does not bring the editor back. Moving forward/backward in the document restores it.

**Expected behavior**
Brat stays

**Please complete the following information:**
 - Version and build ID:  0.17.0-SNAPSHOT (2020-06-05 13:19:57, build 6b5895f9be926d48f0c2f51ac79e9ae3ae475020)
 - OS: Ubuntu 20.04
 - Browser: FF 77.0.1 and Chrome 83.0.4103.116

**Comment by UWinch** [comment]
Thanks for reporting the bug. Also exists in webanno https://github.com/webanno/webanno/issues/1714

**Comment by UWinch** [comment]
Fixed upstream
