### ISSUE TITLE
Configure default editor in settings

### ISSUE THREAD

**Issue by konstantinmiller** [inception-project/inception#1752]
As an administrator, I would like to set the default editor for all users of a labeling project. Is that possible? And if not, I think that'd be a useful feature to not require every user to switch the editor.

**Comment by UWinch** [comment]
Hi, this is currently not possible. But you are right, this seems like a useful feature. Thanks for the suggestion!

**Comment by reckart** [comment]
Duplicate of #2678 - Set default annotation editor in project settings.

**Comment by reckart** [comment]
Feature is available since INCEpTION 22.0.
