### ISSUE TITLE
Make annotation guidelines visible

### ISSUE THREAD

**Issue by konstantinmiller** [inception-project/inception#1754]
I uploaded annotation guidelines as a pdf file to the Guidelines section of the project settings. However, how can I make those guidelines visible to the annotators?

**Comment by reckart** [comment]
An button with a book icon to open the list of annotation guidelines should appear on the annotation page in the action bar.

**Comment by konstantinmiller** [comment]
It does. Thanks a lot for the quick response! (And for the awesome tool you've built!)

**Comment by konstantinmiller** [comment]
It would be cool to have that appear at a more prominent position. For example, on the Dashboard, next to the project title, or as part of the project description.

Is it possible to link from the project description to the guidelines?

**Comment by reckart** [comment]
@konstantinmiller Unfortunately, it is currently not possible to access the guidelines directly using a link. Best open a feature request with your idea. It is a good idea but here in the closed issue, it will be forgotten soon.

**Comment by reckart** [comment]
@UWinch maybe you can open two follow-up issues: one for having guidelines show up in the project dashboard - maybe below the box for resuming annotation - and one for having URLs through which the guidelines can be accessed directly - and referring to these links on the dashboard and on the annotation page?
