### ISSUE TITLE
Project import does not import annotations from anyone but myself

### ISSUE THREAD

**Issue by mbugert** [inception-project/inception#1774]
**Describe the bug**
This is a different issue than #1773. When I export/import a project on the same INCEpTION instance, only my own annotations are imported, despite the fact that all users exist.

**To Reproduce**
1. With user U1, be ROLE_USER and ROLE_PROJECT_CREATOR. With user U2, be ROLE_USER.
2. As U1, create new project. Add some txt document. Add U2 as annotator.
3. Log in as U2, add some annotations.
4. As U1, export the project. Confirm that the annotations of U2 are present in the zip file.
5. As U1, import the project on the same INCEpTION instance. It does not matter whether this is done from the projects overview page or via Administration -> Projects, both ways lead to the same result.
6. Go to the annotation page of the reimported project. Observe that the annotations of U2 are missing.

**Expected behavior**
Annotations of U2 are there.

**Please complete the following information:**
 - Version and build ID:  0.16.1 (2020-06-19 14:59:14, build 654f8cda574ca2d5de85829a972b2ae33928b5da) 
 - OS: Ubuntu 20.04
 - Browser: FF 78.0.2

**Additional context**

**Comment by mbugert** [comment]
I played around with it a bit more.

The conditions for a successful project import are:
* importing user has to be admin
* import has to be done from Administration -> Projects
* the "Import permissions" checkbox needs to be activated

I.e. projects do not import correctly as a non-admin or when imported from the projects overview page (even as admin).

**Comment by jcklie** [comment]
@mbugert Is the issue that the annotations are missing or that the user is just not invited for the project? For me, the annotations are there once I add the user back to the project. @reckart What is the intended behaviour?

**Comment by mbugert** [comment]
I can confirm that manually adding the users to the project makes the annotations reappear. That's okay as a workaround for my small projects. For larger projects, I would definitely not want to do that as a project creator.

**Comment by jcklie** [comment]
The issue is that on the project list import, the "Import permissions" is not checked and there is no way to check it from there. With #1773 , this will be solved.

**Comment by UWinch** [comment]
Should hopefully be solved with https://github.com/inception-project/inception/issues/1773
