### ISSUE TITLE
Small UI issues on Agreement Page

### ISSUE THREAD

**Issue by mbugert** [inception-project/inception#1775]
**Describe the bug**
Null pointer exception appears.

**To Reproduce**
1. Go to agreement page
2. Select a feature
3. Select a measure
4. Select "Choose One" as the feature
5. NPE

**Expected behavior**
I suppose selecting "Choose One" for the feature should reset the measure select field.

**Please complete the following information:**
 - Version and build ID: 0.17.0-SNAPSHOT (2020-06-05 13:19:57, build 6b5895f9be926d48f0c2f51ac79e9ae3ae475020) 
 - OS: Ubuntu 20.40
 - Browser: FF 78.0.2

**Comment by mbugert** [comment]
One more which can likely be fixed together with the above.

**Describe the bug**
Link treatment options are not updated correctly.

**To Reproduce**
Steps to reproduce the behavior:
1. Select feature "Chunk: Tag"
2. Select measure "Fleiss kappa (coding)"
3. There are no options for "link treatment" on right side (that's correct)
4. Select feature "SemPred: arguments"
5. There are still no "link treatment" options, but they should be there.

It also does not work the other way around: Select "SemPred: arguments" first, then switch to "Chunk: Tag". The "link treatment" options should disappear, but they don't.

**Expected behavior**
Options appear/disappear properly.

**Please complete the following information:**
 - Version and build ID: *same as above*

**Comment by UWinch** [comment]
Fixed upstream in webanno
