### ISSUE TITLE
Layers got lost during Curation

### ISSUE THREAD

**Issue by LisaEggert** [inception-project/inception#1786]
During my last Curation three layers got lost. I have not actively merged them, for there were no deviations in the accounts because those were three layers we have annotated in the beginning of the project and never changed anything since then. They were also marked grey in the lower panels. In previous rounds those layers did not disappear although I have not actively merged them.

Now I have two questions:
1. Is this a new feature or a bug? If it's a feature it would be good to mark this somewhere ;)

2. I there any possibility for me o get those three layers back without annotating them again. I have a version of the document where the layers are annotated. For there have been no other changes in the document - besides the curated annotations on other layers - maybe there is a way to somehow import those annotations. We have less than two months left in our projekt and any kind of shortcut would help us extremely.

Thank you!
Lisa

**Comment by UWinch** [comment]
Hi Lisa,

this sounds like a bug. Could you please give me some more information on this:

- which inception version are you using?
- when you say you lost layers, do you mean you lost all annotations of a specific layer?
- what type of layers were these?

Thanks

**Comment by LisaEggert** [comment]
Hi,

thanks for your quick answer.

- We use version 0.16.0

- The annotations on those three specific layers got lost. And the layers do not appear in the dovuments header. As you can see in those screenshots:
![Curated_document](https://user-images.githubusercontent.com/63925920/89170552-17337580-d580-11ea-91be-935fe71a6e11.JPG)
![Precurated_Document](https://user-images.githubusercontent.com/63925920/89170562-1a2e6600-d580-11ea-8450-4da538f69ae7.JPG)

- All three layers are span-annotation-layers with relatively long spans (from 30/40 up to several 100 lines)

Thanks for your help!

**Comment by UWinch** [comment]
I might have found a problem, but I'm not sure, if this is related to your bug. When you open the document on the curation page, can you maybe still see the missing annotations in blue in the users (not the curators) view? You might need to increase the number of rows that are shown in the settings (cog wheel in the navigation bar). 

If this is not the problem:
- do you get any error messages in the log ?
- would you mind sharing your project with me, so I can a have look at it ?

**Comment by jcklie** [comment]
Is it possible to share the project with us somehow? You can send it to `git@mrklie.com` or attach it here. We will handle it confidentially.

**Comment by LisaEggert** [comment]
Hello,

 thanks. I tried it, but unfortunately the annotations seem to be "very lost".
I get no error messages and - if I haven't missed it - have not got one during curation.

I have just send an E-Mail with the project and the two older documents, you might need.

Thank you!

**Comment by UWinch** [comment]
Sadly, we could not pinpoint the exact moment or cause when the layers got lost. However, we changed the implementation so as to prevent user annotations from being changed during curation and plan to implement regular full backups by default to help with recovery.
