### ISSUE TITLE
IllegalArgumentException when opening document metadata on annotation page

### ISSUE THREAD

**Issue by mbugert** [inception-project/inception#1790]
**Describe the bug**
In a certain scenario, opening the document metadata view on the annotation page can result in an IllegalArgumentException.

**To Reproduce**
1. Create new project, add plaintext document
2. Annotate one span, for example on the Chunk layer
3. In the project settings, create new Document metadata layer called `DocLevel` (it doesn't need any features)
4. Go back to annotating the document, select document metadata in the left sidebar
5. Full screen error message:
```
Unexpected RuntimeException
[...]
Root cause:
java.lang.IllegalArgumentException: Undeclared type [webanno.custom.DocLevel]. Available types: uima.cas.TOP
```

**Expected behavior**
No crash.

**Please complete the following information:**
 - Version and build ID: 0.17.0-SNAPSHOT (2020-06-05 13:19:57, build 6b5895f9be926d48f0c2f51ac79e9ae3ae475020) 
 - OS: Ubuntu 20.04
 - Browser: FF 79.0

**Comment by reckart** [comment]
I have tried it in 0.18.0-SNAPSHOT (2021-01-26 22:51:28, build 02c765bb) and could not reproduce the issue.

**Comment by mbugert** [comment]
I tried it too in 0.18.0-SNAPSHOT (2021-01-31 22:56:44, build 82c05892) and it appears to be fixed. Great!
