### ISSUE TITLE
CAS API error when trying to delete non-overlapping annotation (minor issue)

### ISSUE THREAD

**Issue by mbugert** [inception-project/inception#1791]
**Describe the bug**
Attempting to delete a non-overlapping span annotation produces an error.

**To Reproduce**
1. Create new project, add a document
2. Add named entity span annotation for "Lorem ipsum"
3. Try to add named entity span annotation for "Lorem" (subset of the span annotated in step 2)
4. Get "no overlap or stacking is allowed for this layer" error - this is justified
5. Now a user may want to correct their mistake: click on "delete" in the right sidebar
6. Get "Error: Error in low-level CAS APIs: accessing FS with id -1, but no such FS exists in this CAS."

**Expected behavior**
The error should not be shown to end users. I guess it disappears anyway once the root cause of this issue is fixed.

**Please complete the following information:**
 - Version and build ID: 0.17.0-SNAPSHOT (2020-06-05 13:19:57, build 6b5895f9be926d48f0c2f51ac79e9ae3ae475020) 
 - OS: Ubuntu 20.04
 - Browser: FF 79.0

**Comment by jcklie** [comment]
When I clear and then try to create a new overlapping annotation, then I cannot select the existing one (webanno master, Chrome).

**Comment by reckart** [comment]
Fixed upstream issue.
