### ISSUE TITLE
Curation Re-Merge does not work anymore

### ISSUE THREAD

**Issue by UWinch** [inception-project/inception#1796]
**Describe the bug**
On the curation page clicking re-merge should reset the curation document to a state where all finished annotation documents are merged (only annotations that users agree on are merged in the curation document or if incomplete annotation merge is enabled, separately annotated layers are also merged as long as there is no conflict between users).

**To Reproduce**
1. Have two finished documents
2. Go to the curation page
3. Solve some conflict by clicking on one of the users' annotations
4. Click re-merge
5. See that the annotation that was transferred to the curation document during conflict resolution is still there.

**Expected behavior**
Re-merge should happen.

**Screenshots**

**Please complete the following information:**
 - Version and build ID: 0.17.0-SNAPSHOT
 - OS: Ubutnu
 - Browser: [e.g. chrome, safari]

**Additional context**
Might have something to do with updates to CAS writes or reads because I did not find changes to previous versions specific to curation action bar.

**Comment by UWinch** [comment]
The problem still exists after reloading the page (i.e. the shown document is still not re-merged). I first thought it might have to do with https://github.com/inception-project/inception/issues/1794 and the view is just an old version, but if I export the curation document the curated annotations are still there (not reset). So, I'm currently investigating if the CAS storage has soemthing to do with this.

**Comment by reckart** [comment]
Let us know what you find.

**Comment by UWinch** [comment]
Fixed upstream
