### ISSUE TITLE
Make workflow management more extensible

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#1797]
**Is your feature request related to a problem? Please describe.**
Right now, the extension points for workflows are inside the dynamic module it seems. That is bad for extensibility. It might need some Webanno work

**Describe the solution you'd like**
- Move the constants (`inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/api/WorkloadConst.java`
- Get the dropdown options for selecting workflows from the extension (`inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/menu/MonitoringPageMenuItem.java`)

**Comment by reckart** [comment]
We need three modules in inception: one for the extension point and one for each of the workflow strategies (default and dynamic). Changes to WebAnno Schild should not be required.

**Comment by jcklie** [comment]
I thought it should replace the monitoring which is in webanno, that is why I wrote this.

**Comment by reckart** [comment]
We exclude the menu item that WebAnno provides for monitoring already and provide our own because we are pressing the current project along to the monitoring page in inception. We can simply continue doing that and make our own items which activate themselves depending on which workflow is active.
