### ISSUE TITLE
Can delete but not add features from the built-in Named Entity layer

### ISSUE THREAD

**Issue by g-simmons** [inception-project/inception#1798]
**Describe the bug**
It looks like it is possible to delete a feature from the built-in Named Entity layer, but adding features is not allowed.

**To Reproduce**

1. Fresh install of inception 0.16
2. Create a project
3. Go to settings > Layers > Named Entity
4. Click on the identifier feature, delete it using the dropdown in the Feature Details box
5. Attempt to re-add by clicking the create button in the Features box, cannot re-add because it's greyed out

**Expected behavior**
Able to re-add a deleted feature, or add a feature in general to the built-in named entity layer

**Please complete the following information:**
 - Version and build ID:  INCEpTION -- 0.16.1 (2020-06-19 14:59:14, build 654f8cda574ca2d5de85829a972b2ae33928b5da) 
 - OS: OSX
 - Browser: Firefox

**Comment by reckart** [comment]
Deleting a feature from a built-in layer should indeed not work.

Instead of adding a feature to a built-in layer, it would be better to define a custom layer which has exactly the required features.

**Comment by g-simmons** [comment]
@reckart Thanks, very new to the tool, after this incident I realize that. Would there be any way to migrate annotations created in the built-in Named Entity layer to a custom layer with the same features? I'm guessing that might be possible via export -> script with dkpro cassis -> reimport, but probably not any quick solution in the GUI?

**Comment by reckart** [comment]
You can search for all occurrences of a named entity and use the bulk-annotation feature to create an annotation of another type there. However, if you have a larger tagset, you'll have to do that for every tag which might be tedious.

**Comment by g-simmons** [comment]
My tagset isn't too large, that sounds like it wouldn't be too bad. Thanks!

**Comment by reckart** [comment]
Upstream fixed the issue that features on built-in layers could be deleted.
