### ISSUE TITLE
Check for invalid XML 1.0 characters on upload

### ISSUE THREAD

**Issue by g-simmons** [inception-project/inception#1799]
**Is your feature request related to a problem? Please describe.**
I encountered a situation where I had uploaded a document with character 0xc (form feed ascii control character), attempted to export the project to UIMA CAS XMI format, and the project wouldn't export (an error along the lines of "Invalid XML character encountered at position xyz")

**Describe the solution you'd like**
Warn me if I am uploading a document that contains characters that will make it impossible to export the project. Even better, option to remove the characters for me on upload. 

**Describe alternatives you've considered**
Now that I know, check for XML 1.0-invalid characters prior to upload.

Solved without having to re-annotate this particular document by exporting the document to WebAnno TSV, removing the characters there, and reuploading.

**Comment by reckart** [comment]
The DKPro Core XMI writer that we are using supports XML 1.0 as well as XML 1.1. I think we could just add a second XmiFormatSupport for writing UIMA CAS XMI in XML 1.1.

**Comment by reckart** [comment]
The XMI export has been improved now to replace illegal characters on export. 

https://github.com/inception-project/inception/issues/4058

There may still be reasons to sanitize text on import. If you encounter one, please open a separate issue explaining it.
