### ISSUE TITLE
'No layer is selected' when only Coreference Layer is enabled

### ISSUE THREAD

**Issue by mbugert** [inception-project/inception#1801]
**Describe the bug**
When only the stock Coreference Layer is enabled, creating the first annotation after opening the annotation page fails with "No layer is selected. First select a layer."

**To Reproduce**
1. Create project, add document, disable all layers except for Coreference
2. Open annotation page
3. Try to create a span annotation
4. See error. The right sidebar shows "no annotation selected" and the input fields for the Coreference Layer features at the same time.
5. On the second attempt it works

**Expected behavior**
Step 4 succeeds.

**Please complete the following information:**
 - Version and build ID: 0.17.0-SNAPSHOT (2020-08-31 11:44:18, build ac316eec200c61c08acc6543ad305eaf6a44f1bf) 
 - OS: Ubuntu 20.04
 - Browser: FF 80.0.1

**Comment by reckart** [comment]
Merged fix upstream.
