### ISSUE TITLE
Whitelabel error page

### ISSUE THREAD

**Issue by lmompela** [inception-project/inception#1802]
**Describe the bug**
When launching the runnable Java JAR file and after clicking on "open browser", localhost:8080 prints a "Whitelabel Error Page".

When starting it from the shell, it launches and works but I can't find any of the projects I've started. 

When looking into my .inception folder, the data seems to still be there. 

**To Reproduce**
1. launch the runnable Java JAR file
2. Click on 'open browser'
3. See error on browser at localhost:8080/login.html

**Expected behavior**
Have the login page for Inception show up.

**Screenshots**
![image](https://user-images.githubusercontent.com/49000319/92419183-db20a100-f139-11ea-97e8-bc47c908d475.png)

**Please complete the following information:**
 - Version and build ID: [INCEpTION -- 0.16.1 (2020-06-19 14:59:14, build 654f8cda574ca2d5de85829a972b2ae33928b5da)]
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome]

**Additional context**
Here is what the shell prints out, see "There are no projects accessible to you matching the filter criteria."
![image](https://user-images.githubusercontent.com/49000319/92419378-3901b880-f13b-11ea-8dc6-f8cab8501317.png)

**Comment by reckart** [comment]
Looks like you try running INCEpTION on a 32bit Windows.

A third-party library we are using to generate CSS style sheets at runtime does not work on Windows 32bit. See the system requirements: https://inception-project.github.io/releases/0.16.1/docs/admin-guide.html#_system_requirements

**Comment by lmompela** [comment]
My OS is a 64bits windows. I've been using Inception in the past and manage to do quite the amount of annotations. I had a prior issue with Inception that was solved by going to my database and removing the lock manually.

**Comment by reckart** [comment]
The Errpr message on the screenshot that you provided says `Could not initialize io.bit3.jsass.adapter.NativeAdapter`. That typically hints to a system not supported by JSass.

This page provides an overview of the platforms supported by JSass:

https://gitlab.com/jsass/jsass

If your Windows is 64bit, did you maybe accidentally install a 32bit Java?

**Comment by reckart** [comment]
When did your trouble start? Did you upgrade from a previous version? Did your computer crash or did you experience a power outage or something similar?

**Comment by lmompela** [comment]
I managed to use the 16.1 version of Inception once last week using the executable Jar file from which I did annotations, shut it down properly and yesterday tried again and that's when it gave me this message. 
I would assume that if my java version was incorrect I would not have been able to execute the 16.1 version of Inception even once. 
My computer did not crash and there was no power outage whatsoever.
I'll recheck my java version just to be extra-sure.

**Comment by lmompela** [comment]
Here is my java version 
![image](https://user-images.githubusercontent.com/49000319/92503803-c4c52480-f1cf-11ea-837e-a16681ae7161.png)

**Comment by reckart** [comment]
The Java version reported on the command line looks good. It might be that Windows uses a different one if you do a double-click on the JAR.

So when you start INCEpTION on the command line, do you also get the white screen when you open http://localhost:8080 - and if yes, which error does it show?

When you start from the command line, very early during the startup (close to the ASCII-art logo), INCEpTION says whether it is using a DB and where it is reading its data from. Unfortunately, that part already scrolled out of your screenshot. Can you run INCEpTION via the command line and paste the early part of the console output?

**Comment by lmompela** [comment]
So when I launch INCEpTION via the command line, it launches properly, however once on the program it cannot find any of my projects and says "There are no projects accessible to you " although physically present in my .inception folder. 
Here is the upper part of the startup 
![image](https://user-images.githubusercontent.com/49000319/92504630-ed99e980-f1d0-11ea-8419-85ab87375a11.png)

**Comment by reckart** [comment]
> I had a prior issue with Inception that was solved by going to my database and removing the lock manually.

Did you work with the embedded HSQLDB or did you configure INCEpTION to work with a MySQL?

**Comment by lmompela** [comment]
I'm not sure I understand the question, but I had to manually create the embedded HSQL and then remove the lock, using DBeaver. I didn't really configure anything pertaining to INCEpTION.

**Comment by lmompela** [comment]
My initial problem is here https://github.com/inception-project/inception/issues/1703#issue-618346451

I followed the steps by jcklie here https://github.com/inception-project/inception/issues/1703#issuecomment-628775854

**Comment by reckart** [comment]
The annotation data is stored in files in `~/.inception/repository` but all the meta-data about which projects you have and what their settings are is stored in the DB (either a HSQLDB in `~/.inception/db` or -as recommended for serious use- a MySQL/MariaDB). If that DB for some reason gets reset or corrupted, that is bad. HSQLDB is known to be e.g. corruptable by crashes, force computer shutdowns etc (as the lock you had to manually remove hints to). MySQL/MariaDB is typically more robust against such issues.

If you did as I said in #1703 (make regular exports from your projects), then you copy your `~/.inception` folder some place for safe-keeping and start with a fresh setup into which you can import your exported projects.

**Comment by lmompela** [comment]
Ok got it. I'll try to use a MySQL with the fresh setup from now on. Can I just set up the MySQL via DBeaver and/or do I need to configure INCEpTION some specific way ?

**Comment by reckart** [comment]
Please consider the [documentation](https://inception-project.github.io/releases/0.16.1/docs/admin-guide.html#sect_home_folder).

**Comment by reckart** [comment]
Mind that exporting your projects as backups still isn't a bad idea - even if you use MySQL.

**Comment by lmompela** [comment]
Ah, perfect I was looking for that documentation. 

Got it, thanks !
