### ISSUE TITLE
Some DL4J tests fail

### ISSUE THREAD

**Issue by UWinch** [inception-project/inception#1816]
**Describe the bug**
Some DL4J tests fail with `java.io.FileNotFoundException: https://sites.google.com/site/germeval2014ner/data/NER-de-dev.tsv`

**To Reproduce**
Run unit tests for DL4J.

**Comment by jcklie** [comment]
It should be downloaded from https://drive.google.com/drive/folders/1kC0I2UGl2ltrluI9NqDjaQJGw5iliw_J

The exact link is 

https://drive.google.com/file/d/1ZfRcQThdtAR5PPRjIDtrVP7BtXSCUBbm/view?usp=sharing
