### ISSUE TITLE
Re-enable DL4J NER tests

### ISSUE THREAD

**Issue by UWinch** [inception-project/inception#1819]
Re-enable DL4J NER tests when resource is available again. Follow-up to https://github.com/inception-project/inception/issues/1816

**Comment by reckart** [comment]
The Germeval 2014 can for the moment being not be downloaded automatically at all - it is now hosted on Google Drive and there does not seem to be any mechanism to get a direct download link which would work with the likes of curl (or Java's URL support for that matter).

**Comment by jcklie** [comment]
We can host it on UKP public server

**Comment by reckart** [comment]
I wrote a mail to the owner of the files on the Google Drive asking if they can move the data to GitHub or CLARIN Lindat. Waiting for response.
