### ISSUE TITLE
Recommendations in different documents have same VID

### ISSUE THREAD

**Issue by matchlesswei** [inception-project/inception#182]
Using the method `public AnnotationObject getPredictionByVID(VID aVID) `, I got AnnotationObject from not desired document. By debugging, there are AnnotationObjects from different documents but having same VID.
<img width="1276" alt="screen shot 2018-05-13 at 00 34 23" src="https://user-images.githubusercontent.com/23156705/39962157-2ce33a88-5647-11e8-842f-6ef4f0494605.png">
This leads to that the learning record is different from user click in BratAnnotationEditor.

**Comment by Rentier** [comment]
@matchlesswei Where do you use the function?

**Comment by matchlesswei** [comment]
If you click to reject or accept the recommendations in BratEditor, then you may notice the learning record in ALsidebar history may be wrong.
