### ISSUE TITLE
Unable to receive Knowledge Base recommendations for annotations (Wikidata)

### ISSUE THREAD

**Issue by Wolkenstein** [inception-project/inception#1820]
**Describe the bug**
I am unable to receive recommendations on annotations for a wikidata annotation layer.

**To Reproduce**
1. Add a knowledge base wikidata (remote Sparql, Wikidata (direct mapping), all default)
2. Add a Layer (Span) with a property id, pointing to any concept/instance of the wikidata kb
3. Annotate a Text. Any entered string for the property id returns 0 results in the kb

**Expected behavior**
Receive suggestions for the entered string id from the kb.

**Please complete the following information:**
 - Version and build ID: 0.16.1 (2020-06-19 15:11:50, build 654f8cda574ca2d5de85829a972b2ae33928b5da)
 - OS: Docker-Container
 - Browser: Chrome

**Additional context**
Same problems occour with GND or dbpedia. Might of course be simply my fault and not a bug!

Thank you 😄 

-----

Upstream issue: https://phabricator.wikimedia.org/T263952

**Comment by jcklie** [comment]
Can you share an example project with us where this happens?

**Comment by Wolkenstein** [comment]
[You can download an example project here.](https://myfiles.sbg.ac.at/index.php/s/eHjwtCA4ZYXjSJP).

There is only one text in the project and there is a mentioning of the bible in the beginning. I tried to link it to the matching ressources at GND, Wikidata and dbpedia (three layers). 
Only querying dbpedia works, but the label (rdfs:label) can not be shown in the annotation view.
Entering _bible_ in the id of the Wikidata/GND Annotation does not lead to any results. Of course the bible should exist in both knowledge base. Maybe it is simply a configuration error.

**Comment by jcklie** [comment]
With recommendations, do you mean recommendations like we have in INCEpTION via recommenders or suggestions in a dropdown from the annotation editor on the right?

**Comment by reckart** [comment]
It looks like Wikidata full text search is broken - on the side of Wikidata. Their official example for using the fulltext search does also return no results.

Go to https://query.wikidata.org and click on *Examples*, search for `mwapi`, select the example and try to run it. 0 results.

**Comment by Wolkenstein** [comment]
Thanks for your responses! Yes, I was talking about the suggestions, not the recommenders. But maybe this is all a problem of wikidata and bad timing on my side. wikibase:mwapi seems to be broken for the moment.

**Comment by reckart** [comment]
I have added a link to the upstream issue at Wikidata to the issue description: https://phabricator.wikimedia.org/T263952

**Comment by reckart** [comment]
The upstream issue is still open, but they did some actions to mitigate the problem and in the Wikidata SPARQL Web UI, it works again.

**Comment by reckart** [comment]
Upstream issue was marked as resolved now as well.
