### ISSUE TITLE
InlineXML output file does not contain tag for spans across sentences. 

### ISSUE THREAD

**Issue by bsharma5** [inception-project/inception#1829]
**Describe the bug**
Spans annotated across sentence boundary do not shown in output inlneXML file. Possibly due to sentence splitter issue?

**To Reproduce**
Create a simple Layer of Type Span, and with option "Allow crossing sentence boundaries" selected. 
Assign a feature to this layer with a set of string values for tagset. 

Try annotating the following simple file with two lines:

Do you own a house? Yes
Do you commute to work? No

Annotate this span "own a house? Yes" with tag value say "A"
In the output file exported as InlineXML, the tag "A" is not present. 
If I just annotate "own a house", then the tag is present in the output file exported as InlineXML

**Expected behavior**
Looks like this issue is because of the way the sentence is split. Currently, the sentence splitter does splitting on the question mark (?) and since the span crosses the sentence boundary, the output does not show the span. 

Note:  can the tool be configured to ignore question mark while doing sentence splitting. Or is this a bug that the output does not have the tag. 

**Screenshots**
NA

**Please complete the following information:**
 - Version and build ID: [see bottom of the browser screen]
 - OS: [e.g. Windows, Linux, OS X]
 - Browser: [e.g. chrome, safari]

**Additional context**

**Comment by reckart** [comment]
Inline XML format does not support overlapping annotations. If you have an annotation that crosses a sentence boundary (sentences are also annotations), then you have overlapping annotations. This is why the annotation is not there. The format is not suitable for your case.

**Comment by reckart** [comment]
You cannot configure the sentence splitting right now.

However, if your plain text input file should be interpreted as "one sentence per line", then you have the option of importing it using the "Plain text (one sentence per line)" format. Then INCEpTION will simply treat each line as a sentence and not look for sentence markers.

**Comment by bsharma5** [comment]
Understand now that sentences are also annotations. So how do I export in
order to see such cross sentence annotations

**Comment by reckart** [comment]
You can export e.g. as UIMA CAS XMI or WebAnno TSV 3 format.

**Comment by reckart** [comment]
If you need to post-process the exported data, you might want to do with XMI and have a look at [DKPro cassis](https://github.com/dkpro/dkpro-cassis). It allows you to load the data in a Python script. So you could code yourself a Python script which transforms XMI into any target format you can come up with.
