### ISSUE TITLE
Wanna know if have the plan to support Chinese?

### ISSUE THREAD

**Issue by Mozarstra** [inception-project/inception#1840]
![图片](https://user-images.githubusercontent.com/71584724/97382206-cd032b80-1905-11eb-9ad7-7846d81e0e8a.png)
Hello, I'm a student from China. 
During using this excellent app, I found that it doesn't support Chinese very well. It tends to recognize the whole phrase as a word, but not the exact word I want. 
For example in the figure, I want to annotate the person's name like '吕瑞'. However, it annotate the whole phrase "吕瑞再审称", which means'In the second trial, 吕瑞 insists'. This is a totally mistake.
Thank you for your work, it helps me a lot in the annotation. Chinese is uesd widely in this world, there is so much knowledge waiting us to organize. We really hope you can add the support to Chinese.
VERY THANKS!!!

**Comment by jcklie** [comment]
There are some things you can do:
1. Annotate on character level and not on token level, you can change the layer granularity when you create layers
2. If you are familiar with Python, then you can presegment your text with e.g. [Jieba](https://github.com/fxsjy/jieba) and then use another data format as import, e.g. Conll or XMI (you can use [DKPro cassis](https://github.com/dkpro/dkpro-cassis). I can help you with that step if you want
