### ISSUE TITLE
Unable to move past Telemetry Set page

### ISSUE THREAD

**Issue by NimeeshaChan** [inception-project/inception#1842]
**Describe the bug**
When I log into Inception for the first time, I am asked to choose whether to opt in or out of the data collections. Clicking "Toggle" does not show anything, and clicking "Save" brings me back to the same page. Clicking "Projects" or "Administration" also brings me back to this Telemetry page.

**To Reproduce**
1. Log into Inception (for the first time)
2. Click on "Toggle details"
3. Click on "Save"

**Expected behavior**
Once I click "Toggle details", I expected a textbox to pop up with further details on the data collected. When I click on "Save" I expect to go to the "Projects" page.

**Screenshots**
![Screenshot of problem](https://user-images.githubusercontent.com/56051153/97858350-fd99f980-1d39-11eb-86d1-ee55036feec7.png)

**Please complete the following information:**
 - Version and build ID: 0.17.0, a4ce83232f58eba5968ccdf27c49c099c5e6a4ac
 - OS: Windows
 - Browser: Internet Explorer

**Comment by reckart** [comment]
Hum.... that looks like some weird CSS / HTML / FONT issue. 

We don't really support Internet Explorer - maybe you can try with Chrome or Chromium?

**Comment by reckart** [comment]
Also, best get the INCEpTION 0.17.1 version ;)
