### ISSUE TITLE
Events are not logged properly when navigating documents via arrows in editor

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#1843]
**Describe the bug**

**To Reproduce**
1. Import some fresh documents
2. Annotate them and go to next documents via arrow buttons in editor
3. Export the project 
4. See error in event.logs, some events are missing

**Expected behavior**
In this project, 2 people annotated 50 tweets each, but there are not 50 AnnotationStateChangeEvent or 50 DocumentOpenedEvent
[Curriculum+Annotation%3A+JCK+x+JL+Prestudy_project_2020-11-04_1207.zip](https://github.com/inception-project/inception/files/5487508/Curriculum%2BAnnotation.3A%2BJCK%2Bx%2BJL%2BPrestudy_project_2020-11-04_1207.zip)

Blinky Stable

----

* [ ] The steps in the guide should by default explain the Unicode-oriented setup. We should not explain any non-Unicode setup anymore. 
* [ ] We need to test the new instructions so that we know it actually works for fresh installations.
* [ ] We should have a guideline on how to migrate from the old setup to the Unicode setup.

**Comment by jcklie** [comment]
It looks like that many more events are missing

**Comment by jcklie** [comment]
The events are also not in the db, so it is not an export problem.

**Comment by reckart** [comment]
@jcklie I suppose the only thing we should fix for this is actually updating the installation guide, right?

**Comment by jcklie** [comment]
Yes, we need to update the admin guide to say if you want UTF8 then you need to configure the db correctly.

**Comment by reckart** [comment]
Well, the steps in the guide should by default explain the Unicode-oriented setup. I don't think we should explain any non-Unicode setup anymore. Also, we should have a guideline on how to migrate from the old setup to the Unicode setup. Finally, we need to test the new instructions so that we know it actually works for fresh installations.

**Comment by jcklie** [comment]
Encoding problem
