### ISSUE TITLE
Downloading text of annotation sequences with labels

### ISSUE THREAD

**Issue by zacyapjq** [inception-project/inception#1844]
Instead of any of the export formats provided in Inception, is there a way I could export the raw text sequences I labelled, along with their label names? 

The use case I have here is in creating a dataset where I label the sentences in my text as text sequences (sentence boundary detection is not well-solved for my domain), along with a custom tag for each sentence.

An ideal export format would be, on each line of a txt file:
text <TAB> label

The data format I am hoping to achieve is similar to what you see here: https://github.com/Law-AI/semantic-segmentation/blob/master/data/text/1953_L_1.txt

**Comment by jcklie** [comment]
You can export XMI and format it like you want, e.g. using DKPro cassis [1]. That should be pretty simple for your use case.

[1]: https://github.com/dkpro/dkpro-cassis

**Comment by reckart** [comment]
I have provided an example as a Python notebook linked on our website:

https://inception-project.github.io/example-projects/python/

You can open it directly on Google Colab and try it out.
