### ISSUE TITLE
IndexSizeError when rendering BRAT

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#1849]
**Describe the bug**

When viewing the attached document, the JS console on line 56 throws

`Rendering terminated due to: IndexSizeError: SVGTextContentElement.getEndPositionOfChar: Character index out of range getTextAndSpanTextMeasurements/textSizes<@https://blinky.ukp.informatik.tu-darmstadt.de/inception-stable/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratVisualizerResourceReference/visualizer-ver-6FE6C5C69300B2B09BCF3952BBD91BFE.js:1356:8`

Only Firefox

![image](https://user-images.githubusercontent.com/934600/98667568-d9987280-234e-11eb-83b3-b286a31edf31.png)
[webanno17703269163771074364export.zip](https://github.com/inception-project/inception/files/5516837/webanno17703269163771074364export.zip)

**Comment by reckart** [comment]
The file contains unusual Unicode codepoints: 

<img width="804" alt="Screenshot 2021-01-05 at 00 27 25" src="https://user-images.githubusercontent.com/1410238/103589990-01d6c480-4eed-11eb-9569-f0623318404d.png">

These are:
* `U+2066` | ⁦`e2 81 a6` | LEFT-TO-RIGHT ISOLATE
* `U+2069` | ⁩`e2 81 a9` | POP DIRECTIONAL ISOLATE

Extracted sentence as file: [problem-text-unicode.txt](https://github.com/inception-project/inception/files/5767240/problem-text-unicode.txt)

**Comment by reckart** [comment]
For the substring `Karl_Lauterbach\u{2069} mit`, we get different values when querying the string length around `visualizer.js:1499`

| Browser | `text.getNumberOfChars()` | text.textContent.length | Exception | 
| --- | --- | --- | --- |
| Chrome | 20 | 20 | no |
| Firefox | 19 | 20 | yes |

**Comment by reckart** [comment]
Related issue: https://github.com/webanno/webanno/issues/307

**Comment by reckart** [comment]
Fixed upstream https://github.com/webanno/webanno/issues/1841

**Comment by reckart** [comment]
It could also be a bug in the rendering code - we had a similar issue on Firefox recently: https://github.com/inception-project/inception/issues/1849
