### ISSUE TITLE
Unlock/Lock all documents for a particular user at once (Monitoring)

### ISSUE THREAD

**Issue by tilmanbeck** [inception-project/inception#1851]
**Is your feature request related to a problem? Please describe.**
I have a project with 30+ documents and 30+ users. In the monitoring section, I would like to grant access for only one user to only one document. By default, each document which is upload is open for each user added. Manually locking users takes approx. 10 seconds/user (in the described scenario) which results in approx. 30x30 seconds to do it.

**Describe the solution you'd like**
A button which allows me to unlock/lock all users for a particular document (this could also be extended to row-wise unlocking/locking a single user for all documents).

**Describe alternatives you've considered**
I could create one project per user+document combination but that would be a technical overkill IMHO and take too much time managing it.

**Additional context**
a project with many users and many documents
![image](https://user-images.githubusercontent.com/2581770/98697998-d795da00-2375-11eb-9beb-9b81692dec7e.png)

**Comment by reckart** [comment]
Bulk operations in the static workload management page are possible since #1990.
