### ISSUE TITLE
Logout from external authentication

### ISSUE THREAD

**Issue by UWinch** [inception-project/inception#1875]
**Is your feature request related to a problem? Please describe.**
I would like to be able to log out from external authentication. Currently I can click on the *logout* link, but nothing will happen.

**Additional context**
I experienced this while being authenticated via Shippoleth SAML SSO.

**Comment by reckart** [comment]
The question is: how do you log out from SAML SSO?

**Comment by jcklie** [comment]
It reads like one can configure it with a default URL:

https://wiki.cac.washington.edu/display/infra/Configure+Service+Provider+Logout

Does INCEpTION/webanno add additional session info that we need to clear?

**Comment by reckart** [comment]
When we trigger a logout from the SSO, we should also terminate the Tomcat/Wicket/SpringSecurity session.

Cf. `LogoutPanel`: 

```
            @Override
            public void onClick()
            {
                AuthenticatedWebSession.get().signOut();
                getSession().invalidate();
                setResponsePage(getApplication().getHomePage());
            }
```
