### ISSUE TITLE
Installation guide for MySQL configuration should be refined

### ISSUE THREAD

**Issue by sandimschuh** [inception-project/inception#1887]
**Describe the refactoring action**
When I installed mysql on my Ubuntu via apt-get the mysql configuration file did not contain any configuration sections. For people who are not used to mysql configuration it will not be apparent that they have to add the sections by their own.

This is an excerpt from the installation guide:
![image](https://user-images.githubusercontent.com/345385/101781939-b94c0700-3af8-11eb-8d11-e7467957f071.png)

My configuration file where I have added the sections:
![image](https://user-images.githubusercontent.com/345385/101781834-99b4de80-3af8-11eb-8a4a-304645335d67.png)

**Comment by reckart** [comment]
@jcklie When can we have the update for the documentation that tells people no longe to switch to `utf8` an instead use the settings that you figured out that are more compatible with Unicode / emojis etc.?

**Comment by UWinch** [comment]
I'll include it in https://github.com/inception-project/inception/issues/1886.

@sandimschuh thanks for the hint. Sorry, the admin guide is not yet updated to the newest findings. You should use `utf8mb4` as the default-character-set and character-set-server and `utf8mb4_unicode_ci`for collation-server. This way your content can also contain emojis and other unicode characters that are not available for the 3 byte encoding.

**Comment by UWinch** [comment]
Updated in https://github.com/inception-project/inception/pull/1891
