### ISSUE TITLE
Showing error on uploading JSON file in document section.

### ISSUE THREAD

**Issue by mofahad** [inception-project/inception#1889]
Description:
Showing this error  "Cannot deserialize instance of `java.util.ArrayList" when uploading  a json file.

**To Reproduce**
1. Go to  Receipt Project Settings
2. Click on Document
3. Upload a JSON file and select the format type as pubannotation document with sections(JSON), and click on the import button 
4. There you can see this error Cannot deserialize the  instance of `java.util.ArrayList.
5. I tried to upload 4 to 5 JSON doc, but it is giving the same error with all of the files.

**Expected behavior**
It should simply accept the json file.

**Screenshots**

**Please complete the following information:**
 - Version and build ID: INCEpTION -- 0.17.2
 - OS: windows
 - Browser: Chrome

**Additional context**

**Comment by jcklie** [comment]
Thanks for reporting. Can you give us an example document that did not work?

**Comment by mofahad** [comment]
here is the link to the file iam uploading.
https://github.com/mofahad/_CUTIE_/blob/main/Faktura1.pdf_0.json

**Comment by jcklie** [comment]
Are you sure that your file is valid PubAnnotation JSON? The format is described [here](http://www.pubannotation.org/docs/annotation-format/).

**Comment by mofahad** [comment]
okay , i thought that all the json file can be annotated.But there are two json format (pubannotation format, LAPPS)

**Comment by mofahad** [comment]
So i need to structure my json file into pubannotation format or Lapps

**Comment by jcklie** [comment]
We support many file formats, you can see a list [here](https://inception-project.github.io/releases/0.17.2/docs/user-guide.html#sect_formats)

**Comment by mofahad** [comment]
@jcklie , i have see those format , actually i have my data coming from google vision api. I need to annotate that.Can you suggest which option , I can choose , from the given options present in inception.

**Comment by jcklie** [comment]
What do you exactly want to annotate? INCEpTION is for texts, and your example JSON does not have much text in it.

**Comment by reckart** [comment]
Presently, INCEpTION cannot be used for annotating images and thus we also do not support the JSON format that you reported to be coming from the Google Vision API. 

I believe this resolves the issue as not being a bug, so I am closing it. If you should disagree, please let us know.

**Comment by mofahad** [comment]
Hi Richard,

Yes, you can close this bug.

Regards
Mohd Fahad
