### ISSUE TITLE
Options for creating a relation annotation programatically

### ISSUE THREAD

**Issue by michaelmika** [inception-project/inception#1890]
I am writing a simple text relation editor plugin for inception. From there, I want to create a relation annotation. I managed to use the Action Handler to show the new relation annotation at the Annotation Sidebar (see image).
![Image of Yaktocat](https://i.ibb.co/89WrNLK/Bildschirmfoto-2020-12-14-um-15-23-41.png)

However, the annotation is not saved and is not displayed when I reload the page or switch the editor. Also, I would like to set the "label" (which is a feature with predefined tags) in the code already (with e.g. `Tag aTag`).
My Code looks like the following:

```
private void createRelationAnnotation(AjaxRequestTarget aTarget, Tag aTag){
        try {
            CAS aCas = getCasProvider().get();
            // Gets the Origin & Target of Type SENTENCE_LAYER_NAME
            AnnotationFS originFs = aCas.createAnnotation(getType(aCas, SENTENCE_LAYER_NAME), sentence1.getBegin(), sentence1.getEnd());
            AnnotationFS targetFs = aCas.createAnnotation(getType(aCas, SENTENCE_LAYER_NAME), sentence2.getBegin(), sentence2.getEnd());
            // Get State
            AnnotatorState state = getModelObject();
            // Select
            Selection selection = state.getSelection();
            selection.selectArc(VID.NONE_ID, originFs, targetFs);
            // Create
            getActionHandler().actionCreateOrUpdate(aTarget, aCas);
        }
        catch (IOException | AnnotationException | CASRuntimeException e)
        {
            handleError("Unable to create relation annotation", e);
        }
    }
```

**Comment by reckart** [comment]
At first glance, I would have said that probably the CAS was not saved. However, looking at the code of `actionCreateOrUpdate()`, it internally calls `internalCompleteAnnotation()` which in turn calls `editorPage.writeEditorCas(aCas)` - so everything should get saved.

To confirm, you could export the file e.g. as CAS XMI.

You could pass a custom logging configuration when you start INCEpTION `-Dlog4j.configurationFile="path/to/custom/log4j2.xml"` - you can use the `inception-app-webapp/src/main/resources/log4j2.xml` file as a template.

Try e.g. upping the log levels of the detail panel, the adapters and for the storage:

```
<Logger name="de.tudarmstadt.ukp.clarin.webanno.ui.annotation.detail.AnnotationDetailEditorPanel" level="TRACE"/>
<Logger name="de.tudarmstadt.ukp.clarin.webanno.api.annotation.adapter" level="TRACE"/>
<logger name="de.tudarmstadt.ukp.clarin.webanno.api.dao.CasStorageServiceImpl" level="TRACE"/>
```

The brat visualization displays an annotation only if both endpoints are within the "window" of the document which is shown on screen. If any of the endpoints is outside of that "window", then no arc is rendered.

Which visualization are you looking at?

**Comment by michaelmika** [comment]
Thanks for the reply.
The XML Export does indeed reveal that the annotations have been made. 
```
...
    <custom:Sentence xmi:id="52008" sofa="1" begin="0" end="78"/>
    <custom:Sentence xmi:id="52012" sofa="1" begin="79" end="225"/>
    <custom:SentenceRelation xmi:id="52024" sofa="1" begin="79" end="225" Dependent="52020" Governor="52016" label="expansion"/>
...
```

But the SentenceRelation is not visible in the Brat-editor (sentence-related). The custom Sentence Annotation is visible however (written directly in the CAS without the ActionHandler) and I can manually draw a relation from the same annotated sentences, so the Brat editor is theoretically able to display that relation. Restarting & Reloading does not make a difference. 

I will have a look into the logging soon. 

Another general question: I have noticed I can write a SentenceRelation without writing a Sentence Annotation on the origin & target node before, but as I understood in Inception, Relations have to depend on a span layer (which is Sentence in this case). Is it correct that CAS would allow a Relation without creating span layers before, but Inception does need this hierarchy to display the Relation?

**Comment by reckart** [comment]
If you get stuck, you could consider exporting the project so I might have a look at it locally.

Brat cannot render relations which are not attached to spans. 

At the CAS / UIMA level, you can theoretically create anything at any time - but INCEpTION might not be able to deal with it. In INCEpTION, creating an annotation (unfortunately) goes through a few levels of indirection:

* fetch the `LayerSupport` for the layer on which you want to create an annotation from the `LayerSupportRegistry`
* call `createAdapter` on the `LayerSupport` to get an adapter (at this point you usually also need to type-case to `SpanAdapter` or `RelationAdapter`
* call the methods on the adapter to create or delete an annotation

The adapter should ensure that all consistency requirements of INCEpTION and all behaviors configured for the layer in the project settings are met.

**Comment by michaelmika** [comment]
Ok. Looking more closely at the project's export output and comparing it to the output when I draw the relation manually with the Brat Editor, I realized that the span annotation, to which the relation annotation should be attached, seems to be created twice (although the layer was setuped as "sentence-level" & "none overlapping" and no exception has been thrown).

To clarify, these are the configured layers:

- Sentence: none overlapping, sentence-level span annotation layer without features
- SentenceRelation: relation annotation layer attached to Sentence with feature `label:[String]` linked to a Tagset

What I (want) do when selecting a value in a dropbox in the custom editor:

1. Checking if the current two sentences have already been already annotated with type Sentence
2. Annotate sentence(s) with type Sentence
3. Annotate both Sentence spans with the SentenceRelation and Tag `aTag`

So I have noticed in the output posted before that the id's for dependent & governor do not match, see: 

> ```
> ...
>     <custom:Sentence xmi:id="52008" sofa="1" begin="0" end="78"/>
>     <custom:Sentence xmi:id="52012" sofa="1" begin="79" end="225"/>
>     <custom:SentenceRelation xmi:id="52024" sofa="1" begin="79" end="225" Dependent="52020" Governor="52016" label="expansion"/>
> ...
> ```
Scrolling down the export I found a couple lines below:
```
    <custom:Sentence xmi:id="52020" sofa="1" begin="79" end="225"/>
    <custom:Sentence xmi:id="52016" sofa="1" begin="0" end="78"/>
```
I am a bit confused that the annotation seems to be there twice. As said, when annotating the same sentences with Brat, the output is as expected with no duplicate `custom:Sentence` and fitting dependent & governor ids.

For task 1. I wrote a function that checks if a text from `begin` to `end` already has an annotation from `aAnnotationLayer`, which is in this case Sentence:
```
private boolean isTextAnnotated(CAS aCas, int begin, int end, AnnotationLayer aAnnotationLayer){
        VDocument vdoc = new VDocument();
        List<AnnotationLayer> l = new ArrayList<>();
        l.add(aAnnotationLayer);
        preRenderer.render(vdoc, begin, end, aCas, l);
        boolean alreadyAnnotated = false;
        for (VSpan vspan : vdoc.spans(aAnnotationLayer.getId())) {
            alreadyAnnotated = true;
        }
        return alreadyAnnotated;
    }
```
I do not think that this task/implementation causes the problem because it recognizes the annotation. Without that check, it throws an exception because the Sentence Layer can't be stacked.

The implementation for task 2. is pretty simple and more direct than the adapter method you proposed. I simply create the annotation & write it in CAS. After that, switching to the Brat Editor, the span seems to be correctly marked:
```
     AnnotationFS annotation = aCas.createAnnotation(getType(aCas, SENTENCE_LAYER_NAME), begin, end);
     aCas.addFsToIndexes(annotation);
```

Task 3 I tried to implement as explained above:
> ```
> private void createRelationAnnotation(AjaxRequestTarget aTarget, Tag aTag){
>         try {
>             CAS aCas = getCasProvider().get();
>             // Gets the Origin & Target of Type SENTENCE_LAYER_NAME
>             AnnotationFS originFs = aCas.createAnnotation(getType(aCas, SENTENCE_LAYER_NAME), sentence1.getBegin(), sentence1.getEnd());
>             AnnotationFS targetFs = aCas.createAnnotation(getType(aCas, SENTENCE_LAYER_NAME), sentence2.getBegin(), sentence2.getEnd());
>             // Get State
>             AnnotatorState state = getModelObject();
>             // Select
>             Selection selection = state.getSelection();
>             selection.selectArc(VID.NONE_ID, originFs, targetFs);
>             // Create
>             getActionHandler().actionCreateOrUpdate(aTarget, aCas);
>         }
>         catch (IOException | AnnotationException | CASRuntimeException e)
>         {
>             handleError("Unable to create relation annotation", e);
>         }
>     }
> ```
As I said, it seems to write the SentenceRelation annotation, but it is attached to the wrong & duplicate Sentence annotation. Does the method `aCas.createAnnotation()` also write the Sentence annotation to the CAS? Because then it's done the second time (after task 2.). How can I get the already written annotation from task 2. there? 
_____
I also tried your approach with the adapter, but there a lot of information is missing for me. To create the adapter, I followed your instructions and ended up with this, also I am not quite sure which Layer to pass (`sentenceLayer` or `relationLayer`):
```
Supplier supplier = new RelationFeatureSupplier(relationLayer);
TypeAdapter adapter = layerSupportRegistry.getLayerSupport(relationLayer).createAdapter(relationLayer, supplier);
```
The only real function that seems to be useful for my use case in this adapter is `setFeatureValue` I guess, but I do not understand the parameters. Is the string value for instance the value of the feature? What is the integer value & the object? 
```
void setFeatureValue(SourceDocument var1, String var2, CAS var3, int var4, AnnotationFeature var5, Object var6);
```
And does this already write an annotation? 

Thanks a lot for your help!

**Comment by reckart** [comment]
If you create things like this (below) directly on the CAS, then the consistency safe-guards of INCEpTION and the layer behaviors have no effect - yes, these two lines do add new annotations to the CAS: 

```
 // Gets the Origin & Target of Type SENTENCE_LAYER_NAME
            AnnotationFS originFs = aCas.createAnnotation(getType(aCas, SENTENCE_LAYER_NAME), sentence1.getBegin(), sentence1.getEnd());
            AnnotationFS targetFs = aCas.createAnnotation(getType(aCas, SENTENCE_LAYER_NAME), sentence2.getBegin(), sentence2.getEnd());
```

If you work with the adapters, you need to cast the adapter either to `SpanAdapter` or to `RelationAdapter` - depending on which kind of layer you are working with. Once you do that, the methods to create (`add`) and delete annotations become available.

For some inspiration, you can look at the following methods:

* `de.tudarmstadt.ukp.clarin.webanno.ui.annotation.detail.AnnotationDetailEditorPanel.createNewAnnotation(AjaxRequestTarget, TypeAdapter, CAS)` (here the type-cast happens)
* `de.tudarmstadt.ukp.clarin.webanno.ui.annotation.detail.AnnotationDetailEditorPanel.createNewRelationAnnotation(RelationAdapter, CAS)` (here the adapter cast to `RelationAdapter` is used)
* `de.tudarmstadt.ukp.clarin.webanno.ui.annotation.detail.AnnotationDetailEditorPanel.createNewSpanAnnotation(AjaxRequestTarget, SpanAdapter, CAS)` (here the adapter cast to `SpanAdapter` is used)

I am sorry that this is not quite so easy to get started with. I have refactored this code already several times and every time it gets a bit better. There is very much happening here at different levels of abstraction and one cannot change too much at a time in that code either because it is quite complex. 

Anyway, the `setFeatureValue()` comes into play *after* you have added a new annotation either using `SpanAdapter.add(SourceDocument, String, CAS, int, int)` or `RelationAdapter.add(SourceDocument, String, AnnotationFS, AnnotationFS, CAS)`, e.g.

```
AnnotationFS annotation = spanAdapter.add(document, username, cas, begin, end);
spanAdapter.setFeatureValue(document, username, cas, WebAnnoCasUtil.getAddr(annotation), feature, value);
```

You can get `document` and `username` from the `AnnotatorState` (`state.getDocument(), state.getUser().getUsername()`).

**Comment by reckart** [comment]
If you use the adapters directly and do not create the annotation via the `ActionHandler`, then you need to save the CAS yourself using:

```
// persist changes
annotationPage.writeEditorCas(cas);
```

(cf. `de.tudarmstadt.ukp.inception.ui.core.docanno.sidebar.DocumentMetadataAnnotationDetailPanel.actionAnnotate(AjaxRequestTarget)`)

**Comment by reckart** [comment]
Depending on where you are, you might have to search the Wicket component hierarchy for the page:

```
        AnnotationPageBase annotationPage = findParent(AnnotationPageBase.class);
```

**Comment by reckart** [comment]
> For task 1. I wrote a function that checks if a text from begin to end already has an annotation from aAnnotationLayer, which is in this case Sentence:

If you want to retrieve/find stuff from the CAS, you should use the `CasUtil.select...` or `cas.select...` methods instead of going through the renderer.

**Comment by reckart** [comment]
@michaelmika can we consider this issue as resolved?

**Comment by michaelmika** [comment]
@reckart, thank you very much for your support. I resolved the issue with your help! 

I just one small note: Although I did not use the ActionHandler, but the specific adapters for creating the annotations, I did not need to persist the changes via 

```
// persist changes
annotationPage.writeEditorCas(cas);
```

The annotations are now visible with the brat-editor & in the project export.

**Comment by reckart** [comment]
Hm. We keep the CAS in memory for a while to avoid having to load it on every user action. So even if you do not manually persist the CAS, the changes will hang around. However, eventually this cached CAS will be dropped from memory and if it was not persisted up to that point, then your data will be lost. You should make sure that the CAS is actually saved after you made your changes.

**Comment by michaelmika** [comment]
Okay, thank you for this note. So I guess saving the CAS after each write would be a good strategy, or is this a big bottleneck?

**Comment by reckart** [comment]
Saving the CAS after an annotation action is a good strategy. Normally, we save once per user interaction (i.e. when the user creates/deletes an annotation or when the user sets a feature). However, if your annotation action consists of (automatically) creating multiple annotations, then save once when the last annotation of your batch is done.

**Comment by michaelmika** [comment]
Okay perfect, thanks a lot!
