### ISSUE TITLE
Workload page:  Checkbox in the table to select documents

### ISSUE THREAD

**Issue by christophscheunemann** [inception-project/inception#1894]
**As project manager it would be a lot easier to execute an action on multiple documents at once**
This would drastically improve QoE of the page

**Solution: Checkboxes as first column of the table**
Having checkboxes to select the documents I want to perform actions on, would be very handy.

**Comment by reckart** [comment]
We have that for quite some time now. The matrix workload page supports bulk actions where you can select either documents or annotators or both to affect all documents for an annotator or all annotators for a document.
