### ISSUE TITLE
When many tags exist the annotations are not saved

### ISSUE THREAD

**Issue by ofersabo** [inception-project/inception#1897]
Tag names are not annotated and not displayed on the webpage. 
Tags are also not written to the exported file. 

I have a kind of SRL annotation project, with a slight difference which is that each predicate is mapped to one of 341 tags. Then I also have an additional layer of arguments (arg0,arg1,arg2) that are connected to the predicates, like in SRL.

The original project was created in WebAnno and I imported it into inception. 
In WebAnno the annotations work well, the predicate tags are visible and they exist in the exported document. 

**To Reproduce**

1. import the attached project. 
2. try to annotate any span for the layer of demo_layer.
3. See error

The attached screenshot shows the problem.

 - using the latest docker tag uploaded 16 days ago.
 - Mac os 10.15.5
 - Chrome

![Screen Shot 2020-12-21 at 11 21 09](https://user-images.githubusercontent.com/31179968/102760998-ff1d9080-437e-11eb-9e4e-01277a0b850d.png)
[demo_for_bug_project_2020-12-21_0924.zip](https://github.com/inception-project/inception/files/5723445/demo_for_bug_project_2020-12-21_0924.zip)

**Comment by reckart** [comment]
You have apparently chosen "AUTO" or "Plain text" as the export format. Please select "UIMA CAS XMI" or "WebAnno TSV" when exporting.

**Comment by reckart** [comment]
Note, the recommendation given above is regarding being able to "see" the annotations when extracting the ZIP file.

If the project is imported into INCEpTION, the annotations should be there regardless of the format chosen during export. I'll try importing the project and have a look. Thanks!

**Comment by ofersabo** [comment]
> You have apparently chosen "AUTO" or "Plain text" as the export format. Please select "UIMA CAS XMI" or "WebAnno TSV" when exporting.

No, I used the WebAnno TSV format.
The issue is that choosing the annotation tags doesn't work. so the span is just marked as the name of the layer.

**Comment by reckart** [comment]
Ok, gotcha. Which browser are you using?

**Comment by ofersabo** [comment]
Chrome

**Comment by reckart** [comment]
Ok, I can reproduce it. Very strange.

**Comment by reckart** [comment]
Ok, found the bug :)

**Comment by reckart** [comment]
Upstream issue: https://github.com/webanno/webanno/pull/1832

**Comment by reckart** [comment]
Fixed upstream.

**Comment by ofersabo** [comment]
Thanks, @reckart!
Any idea when this change will be available in the docker version?

**Comment by reckart** [comment]
Once 0.17.3 has been released. If you need it earlier, you can build directly from the sources. Check out the `inception-app-webapp/src/main/docker/README.md´ file for points on building the docker image *after* having built the whole project.

Please note that INCEpTION can be significantly slower than normal if you build INCEpTION from the GitHub sources because it enables an internal sanity checking mode. 

To disable the sanity checks, you can add the following setting to the `settings.properties` file [1]:

```
debug.casDoctor.forceReleaseBehavior=true
```

**Comment by reckart** [comment]
There are a couple of other issues we are also investigating right now - so I would assume that 0.17.3 won't happen this year anymore.

**Comment by reckart** [comment]
Oh and mind that the fix for this particular issue is in the WebAnno code base - so you need to check out both, the WebAnno code repository and the INCEpTION code repository and build both - you only need to build Docker in INCEpTION though.

**Comment by reckart** [comment]
@ofersabo should be available on Docker now (0.17.3 / latest)

**Comment by ofersabo** [comment]
Amazing @reckart 

Thank you :)
