### ISSUE TITLE
WikiData integration test

### ISSUE THREAD

**Issue by Rentier** [inception-project/inception#191]
Right now, the support for reified `WikiData` is only partial. For instance, in the knowledge base view, concepts cannot be listed. Write an integration test that checks whether the support is fully functional.

**Comment by reckart** [comment]
@Rentier @naveen2507 can you please check if this is still required or superseded by the new KB test suite that @naveen2507 has created?

**Comment by naveen2507** [comment]
@Rentier Do we need this, as KnowledgeBaseServiceRemoteTest.java checks the propertyList, conceptList along with accessing the parent list for a particular identifier ?

**Comment by Rentier** [comment]
This test should test most of the cases that the `KnowledgeBaseServiceIntegrationTest` tests. These tests should be more concrete (e.g. looking up properties and concepts on `https://www.wikidata.org`) and against the real WikiData, with and without reification. The `KnowledgeBaseServiceRemoteTest` just look for existence, this test should check whether WikiData integration completely works..

**Comment by naveen2507** [comment]
DONE  #441
