### ISSUE TITLE
Explore SKOS General Standards 

### ISSUE THREAD

**Issue by naveen2507** [inception-project/inception#194]
Take a look at some of SKOS ontologies about their general standards

**Comment by naveen2507** [comment]
@MdeBoer95  Reference : http://dublincore.org/resources/training/dc-2011/Tutorial_Isaac.pdf

**Comment by naveen2507** [comment]
[SKOS-Ontologies.tar.gz](https://github.com/inception-project/inception/files/2137030/SKOS-Ontologies.tar.gz)

Zip has three ontologies  : 
- countries
- languages-skos 
- unescothes (this is comparatively a larger one with varied set of IRI)

Link for SKOS vocab specifications : [https://www.w3.org/TR/swbp-skos-core-spec/#member](url)

**Comment by reckart** [comment]
* **countries**: this is like a list of terms (flat vocabulary). I think one would use it either with `jur:Country` being mapped as an explicit root concept and all the countries would be instances under it, or using `jur:Country` as the class marker such that every country becomes a class in INCEpTION.

* **languages-skos**: seems to be the same situation as *countries*. 

* **unescothes**: looks like this could be mapped either using `skos:broader` or `uneskos:memberOf` as the subclass hierarchy properties. 

Is there some screenshot or diagram somewhere how these ontologies is meant to be used?

What are the sources of the files?

**Comment by reckart** [comment]
@naveen2507 the SKOS vocab link above does not work.

**Comment by naveen2507** [comment]
@reckart link works now

**Comment by reckart** [comment]
@naveen2507 what is you opinion on the "mappability" and usability of these ontologies in INCEpTION?

**Comment by naveen2507** [comment]
We definitely need to incorporate SKOS as its widely popular and used nowadays. 

One option could be : As you said about using the explicit root concept can be used for certain ontologies which are relatively flat and we just make everything as instance of a class. But for ontologies like unescothes, we need to set type IRI or give user an option to provide explicitly, which can be used as union in SPARQL queries (specially for relatively larger ontologies) . But there might be cases where it would not import any root concept at all. 

Another option which I am not sure how would it impact the base for KB in Inception is: Specially, in case our SPARQL queries doesn't return any concept at all. We can take a root concept as "Thing" and provide the member items as instances of that. This is a rather brute force thing. 

Refer to this link : [https://mailman.stanford.edu/pipermail/protege-owl/2010-July/014745.html](https://mailman.stanford.edu/pipermail/protege-owl/2010-July/014745.html)

Another idea which I see by referring to this [link](https://www.w3.org/TR/skos-reference/#semantic-relations) is, we can have explicitly define two base concepts for all SKOS ontologies i.e Concept and Concept Schema. But we need to explore a bit for this option.

**Comment by reckart** [comment]
@naveen2507 I think we have a good idea now which kind of SKOS ontologies we support. So I guess we can close this issue?

**Comment by naveen2507** [comment]
Yeah. We can
