### ISSUE TITLE
Creating Project with no permission 

### ISSUE THREAD

**Issue by ofersabo** [inception-project/inception#1945]
When importing a project and unchecking the checkbox "import permissions", a project is created but no user has the ability to change it, not even the admin. Thus we end up with a Zombie project.

**To Reproduce**
1. Import any project, and uncheck the "Import permissions" box.
2. You get a Zombie project

**Please complete the following information:**
 - Version and build ID:
 INCEpTION -- 0.17.3 (2020-12-29 19:22:47, build fde91146f90bb5e4e2d340fbbe27be553b3284eb)
 - OS: [e.g. Windows, Linux, OS X]
 OSX
 - Browser: [e.g. chrome, safari]
 Chorme

**Comment by reckart** [comment]
Hm, thanks for reporting. We'll have a look. Normally, the person importing the project should always be assigned all roles on the imported project.

**Comment by ofersabo** [comment]
Is there any way in which I can override this? Given that I have access to the embedded database, for example, deleting this project directly from the DB?

**Comment by reckart** [comment]
As an admin user, you can click on "administration" next to the logout button at the top of the screen. Then you click on projects in the left sidebar. There you get access to all projects irrespective of whether you (admin user) have a role in them.

**Comment by reckart** [comment]
In 0.18.0, the Settings menu item will also be accessible to admin users for any project - no matter whether they have a role in it.

**Comment by reckart** [comment]
Btw. I'd strongly advise against using the embedded DB for serious usage - we have had reports from users who lost access to their data because their embedded DB got corrupted due to power loss or computer crashes. It appears that proper SQL servers like MariaDB or MySQL are more resilient.

**Comment by ofersabo** [comment]
Thanks @reckart 
We would definitely move to MySQL

**Comment by reckart** [comment]
I have created a project using a normal (project creator) user account and exported it. Then, I have imported the project using an admin account and did uncheck the "import permissions" box. But I cannot reproduce the "zombie project" - for me, the "admin" user was added to the project as manager/curator/annotator during import (as expected).

**Comment by ofersabo** [comment]
Did you try that with embedded DB?
On my end it still happens also in 0.17.4.

**Comment by reckart** [comment]
I tried with Maria DB. I would not expect the DB to make a difference here but I can try.

**Comment by reckart** [comment]
```
        // If the current user is a project creator then we assume that the user is importing the
        // project for own use, so we add the user as a project manager. We do not do this if the
        // user is "just" an administrator but not a project creator.
        Optional<User> manager = currentUserIsProjectCreator ? Optional.of(currentUser)
                : Optional.empty();
```

The idea here is/was that an administrator should be able to import a project without implicitly gaining project roles - otherwise a migration secenario where an admin exports all projects from instance A and imports them afterwards into instance B would mean that the admin would end up having permissions in all the projects - permissions the admin didn't have before the migraiton and doesn't want to have.

I guess we can probably change the condition to ´ currentUserIsProjectCreator || (currentUserIsAdministrator && !importPermissions)´.

**Comment by reckart** [comment]
Fixed upstream.
