### ISSUE TITLE
[Question] where the backup files are saved?

### ISSUE THREAD

**Issue by ofersabo** [inception-project/inception#1946]
Hi,

Trying to configure a backup mechanism to the annotations and documents. 
Following the admin guide, I created a file named "settings.properties" in the directory mounted by the docker.
i.e. the docker is mount to a directory on the host filesystem. In this directory, I created the file "settings.properties", so now this directory contains "db", "repository" directories and the new "settings.properties" file. 

The configurations dictate a backup every 5 minutes, and up to 10 backups. 
Where does the system save these backups?
How can they be restored?

**Comment by reckart** [comment]
The backup files are stored next to the annotation files in the "home" folder of INCEpTION.

<img width="370" alt="Screenshot 2021-01-14 at 19 36 28" src="https://user-images.githubusercontent.com/1410238/104633675-c7fd7f00-569f-11eb-8e9c-2ac2fd969286.png">

This type of backup is part of the annotation storage.

It protects against data loss when e.g. bugs in the software cause a broken annotation file to be saved.

It does not protect against:
- deletion of documents (while the backups are apparently currently not deleted, the document metadata in the DB is deleted and this metadata is not part of the backup)
- deletion of projects
- corruption of metadata in the database (only the annotations are contained in the backup files but not other metadata like the document state, layer configuration or any other aspects of the project configuration)

If you want to do regular backups of your projects, I would recommend setting up a cron job which exports the project e.g. using https://github.com/inception-project/inception-cli. Mind that the user accounts (usernames, passwords, application-level permissions) are not part of the exported projects either. 

For a really complete backup, you'd need to save the INCEpTION home folder as well as the SQL database INCEpTION is configured to use.
