### ISSUE TITLE
Importing Preannotated sentence-level dataset

### ISSUE THREAD

**Issue by thak123** [inception-project/inception#1947]
I have some sentence which I want to get tagged as positive negative neutal . I have already tagged few of them using a tool.

I have created layers and tagset for the same.

Can anyone tell me how to import the preannotated files in inception. I can write a code to convert it into any format.

**Comment by jcklie** [comment]
You can use XMI for that, either in Java using UIMAj or in Python using [dkpro-cassis](https://github.com/dkpro/dkpro-cassis). I have an example under [here](https://github.com/inception-project/inception-external-recommender/blob/master/scripts/util.py#L9) for the Python way.

**Comment by thak123** [comment]
Thank you very much
