### ISSUE TITLE
Internal Server Error after loging in for the first time

### ISSUE THREAD

**Issue by izaskr** [inception-project/inception#1950]
**Describe the bug**
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.
Wed Jan 20 20:36:43 CET 2021
There was an unexpected error (type=Internal Server Error, status=500).

**To Reproduce**
Download the latest .jar from the website, install it from the command line, go to http://localhost:8080/, log in with the defualt username and password.

**Expected behavior**
No error.

**Please complete the following information:**
 - Version and build ID: 0.17.04
 - OS: Linux
 - Browser: Chrome and Firefox

**Comment by reckart** [comment]
INCEpTION 0.17.4 requires Java 11 or higher (despite the system requirements in the documentation saying otherwise).

Are you running INCEpTION on Java 11 or higher? 

(type `java -version` on the command line to see which Java version you are using).

**Comment by reckart** [comment]
I'm closing this assuming the Java version was the issue and it could be resolved by using a more recent Java. Should this be wrong, please comment - we'll re-open it.
