### ISSUE TITLE
PDF export

### ISSUE THREAD

**Issue by aesuli** [inception-project/inception#1963]
PDF documents are not exported in their original format:

    "No writer found for original format [pdf] - exporting as [WebAnno TSV v3.2 (WebAnno v3.x)] instead."

Having them exported in their original format would allow user to migrate* projects that work on documents in such format across different inception instances, without losing the possibility to annotate on the original PDF page, which a great feature of the system.

\* is there any alternative procedure, apart from export->import, that one can use to move annotated PDF documents from one inception instance to another?

**Comment by reckart** [comment]
Have you tried just importing the project again into another instance? I believe it should just work despite the warning which might simply be misleading.

**Comment by aesuli** [comment]
@reckart , you are right!
I did test importing, then opening a document. What I missed was the simple act of switching the editor to PDF also on the target instance 🤦‍♂️.
That warning made me focus on the source instance, while your comment made me investigate with more attention the target instance, thank you!

I close this and leave it for reference to future users.
