### ISSUE TITLE
Chain Layer not visible in Curation mode

### ISSUE THREAD

**Issue by saligerpa** [inception-project/inception#1983]
I created a chain layer, however the annotations for that chain layer do not appear in curation mode.

Is this expected behaviour?

Is there an alternative way of creating discontinuous annotations?

Thanks for the great software!

**Comment by reckart** [comment]
Chain layers are unfortunately presently not supported in curation.

You can emulate discontinuity either a relations or link features.

So you can define a relation layer on top of your span layer and when you have multiple spans that should be considered as one, you can use a the relation to connect them.

Or you can add a "Link: XXX" feature to your span layer which either points to the same layer or which points to a new layer you might call e.g. "Extension". So when you have a discontinuous span, you could annotate the first span with your normal span layer and then add one or more links to the other spans.  

See also: #1882

**Comment by saligerpa** [comment]
Hi @reckart,

thanks so much for your quick and extremely helpful reply.
It might be a good idea to make other users of the chain layer aware of this limitation, maybe a short warning [here](https://inception-project.github.io/releases/0.17.4/docs/user-guide.html#_chains) would be in order?

Thanks!
