### ISSUE TITLE
All stacked annotations highlighted at the same time

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#1995]
**Describe the bug**

It looks like stacked relations have the same id internally, all stacked relations are highlighted when selecting one.

https://gyazo.com/907d0ac04fea0c97ff35f11a7c8a9f85
https://gyazo.com/bea678ca5add0f5beaf4737e5a14bf7d
https://gyazo.com/172a6db56b8351f140140f32954e747d

**To Reproduce**
1. Create stacked relations
2. Click on it
3. All are highlighted

**Expected behavior**
Select only one.

**Please complete the following information:**
 - Version and build ID: master
 - OS: Windows 10
 - Browser: Chrome

**Comment by reckart** [comment]
Relevant code in `visualizer.js`:4211:

```
          highlightArcs = $svg.
              find('g[data-from="' + originSpanId + '"][data-to="' + targetSpanId + '"]').
              addClass('highlight');
          highlightSpans = $($svg).
              find('rect[data-span-id="' + originSpanId + '"], rect[data-span-id="' + targetSpanId + '"]').
              parent().
              addClass('highlight');
```
