### ISSUE TITLE
After rejecting a recommendation, accepting doesn't work anymore

### ISSUE THREAD

**Issue by HerrKrishna** [inception-project/inception#2029]
**Describe the bug**
After rejecting a recommendation with a double-click, when hovering the mouse over an annotation the usual pop-up that describes the annotation isn't displayed anymore. Also it's impossible to accept another recommendation by clicking on it once. 
Rejecting still works however. The behaviour goes back to normal after going to the dashboard and then returning to annotation mode.

**To Reproduce**
1. Set up a StringMatching Recommender for the NamedEntity Layer
2. Create a Named Entity Annotation in a document. Make sure that the Annotation is on a string that occurs frequently in the document.
3. Hover your mouse over a recommendation or annotation. You will see a pop-up describing the recommendation.
3. Reject one of the recommendations that appear by double-clicking it.
4. Hover your mouse over a recommendation or annotation. There won't be a pop-up.
5. Try to accept a recommendation by clicking on it once. It won't work.
6. Go back to the dashboard.
7. Click on Annotation and select the same document.
8. Hover your mouse over an annotation. Pop-up is back.

**Please complete the following information:**
 - INCEpTION -- 0.18.1 (2021-02-10 23:33:09, build d108e4b5
 - Linux
 - Firefox

**Comment by reckart** [comment]
Works in Chrome. In Firefox, there is an exception logged in the JS console:

<img width="825" alt="Screenshot 2021-02-25 at 21 06 43" src="https://user-images.githubusercontent.com/1410238/109210663-6c013c80-77ad-11eb-9000-cf8c991a508a.png">

**Comment by reckart** [comment]
Fixed upstream.
