### ISSUE TITLE
agreed relation annotations don't move to the curator panel

### ISSUE THREAD

**Issue by ofersabo** [inception-project/inception#2037]
Given a tagging assignment with the span and relation layers.
Two annotators tag the same relation and the same spans.
The curation panel mark their spans as gray, meaning that they agreed about the span.
However, the relation isn't automatically received by the curator.
When manually trying to move the relation an error comes up saying that: 
"Error: The annotation already exists in the target document"

**To Reproduce**
Due to privacy concerns I want to share the project privately with inception members.
1. import the attached project.
2. go to curation and look for the words: "descending thoracic aorta"
3. See error

**Screenshots**
see the attached image.
[screencapture-127-0-0-1-5001-curation-html-2021-02-25-17_49_09.pdf](https://github.com/inception-project/inception/files/6044160/screencapture-127-0-0-1-5001-curation-html-2021-02-25-17_49_09.pdf)
 

**Please complete the following information:**
 - OS: macos 
 - INCEpTION -- 0.17.4 (2021-01-13 23:39:05, build 2bb5cd9e078e9dca5ef29d40d8381c44ee9b1431)
chrome

**Comment by ofersabo** [comment]
Although the image was taken from a tool which uses the embedded DB, this happens also when the tool uses MySQL V5 database.

**Comment by reckart** [comment]
If you care, you can send me the project.

**Comment by reckart** [comment]
Btw. did you try running a CAS doctor diagnosis in the project settings? If you get the message "Error: The annotation already exists in the target document" it could mean that there is a dangling relation hanging around in the curation document (which would not render in the UI because it's dangling).

**Comment by ofersabo** [comment]
@reckart to what email should I send the project?

**Comment by reckart** [comment]
@ofersabo check my lastest commits ;)

**Comment by reckart** [comment]
... for the committer mail address that is.

**Comment by ofersabo** [comment]
Cas doctor says that there is nothing to report.
