### ISSUE TITLE
Concurrent modification + all document annotations lost

### ISSUE THREAD

**Issue by purple749** [inception-project/inception#2038]
**Describe the bug**
After annotating a document for a while, a concurrent modification error appears, and afterwards all annotations in the document are lost. This does not happen after a consistent set of steps, so it is difficult to describe steps to reproduce - but once it happens for the first time, it starts happening repeatedly for the same document.

**To Reproduce**
Use the standalone Docker image of Inception, version: inception-0.17.3. Use the embedded database. 
1. Create a project
2. Import documents
3. Create several new layers
4. Create a new tagset and also add new tags to the existing Named entity tagset
5. Add a recommender (Multi-Token Sequence Classifier (OpenNLP NER)) for the new layer and existing Named entity layer
6. Begin annotating a document, switching between several layers as annotation progresses. 
7. Eventually, this error appears and all document annotations are lost.

**Expected behavior**
No errors and annotation proceeds as normal.

**Screenshots**
Instead of screenshot, posting redacted logs with more details:

```
2021-02-25 19:48:49 INFO [admin] CasMetadataUtils - Annotation file [*****.ser] of user [*****] for document [*****.xmi](239) in project [*****](3) does not support CASMetadata yet - unable to check for concurrent modifications
2021-02-25 19:49:06 INFO [admin] AnnotationSchemaServiceImpl - Upgraded CAS of user [*****] for document [*****.xmi](239) in project [*****](3)
2021-02-25 19:49:42 INFO [*****] AnnotationSchemaServiceImpl - Upgraded CAS of user [*****] for document [*****.xmi](239) in project [*****](3)
2021-02-25 19:52:07 INFO [*****] ApplicationPageBase - *****: The [Named entity] annotation has been deleted.
2021-02-25 19:54:20 INFO [*****] ApplicationPageBase - *****: The [Named entity] annotation has been deleted.
2021-02-25 20:02:28 INFO [SYSTEM] CasStorageServiceImpl - Restoring previous annotations due exception when trying to write new annotations: /export/repository/project/3/document/239/annotation/*****.ser.old
2021-02-25 20:02:28 ERROR [SYSTEM] RecommendationServiceImpl - Cannot read annotation CAS for user [*****] of document [*****.xmi](239) in project [*****](3) - skipping document
java.io.IOException: Detected concurrent modification to file in storage (expected timestamp: 1611180489000; actual timestamp in storage 1614283348000) - please try reloading before saving again.
```

**Please complete the following information:**
 - Version and build ID: 0.17.3 (2020-12-29 19:22:47, build fde91146f90bb5e4e2d340fbbe27be553b3284eb)
 - OS: Linux
 - Browser: Safari

**Additional context**
The docker container is being run on the following type of server: Ubuntu 18.04 (64-bit)

**Comment by reckart** [comment]
Do you have multiple browsers / windows / tabs in parallel logging in with the same user account and working on the same document?

**Comment by purple749** [comment]
No - only one user was logged into this account, and only in one browser tab.

**Comment by reckart** [comment]
Is your docker images running out of disk space by any chance?

**Comment by purple749** [comment]
No, this does not seem to be the case.

**Comment by reckart** [comment]
Which command exactly do you use to start the docker container?

**Comment by purple749** [comment]
The first time: 
`docker run -d --name inception-0.17.3 -p8080:8080 inceptionproject/inception:0.17.3`

All subsequent times:
`docker start inception-0.17.3`

**Comment by reckart** [comment]
It would be nice if we could inject a custom log4j configuration file into the docker image so we could yank the log level for the storage layer up a bit - but I don't see an easy way to do that with the Docker image.

Could you maybe try exporting the project (I'd recommend that anyway), fetching the latest 0.18.1 version JAR version (or 0.18.2 later today or on the weekend), importing your project there and check if you can reproduce the issue with it? If yes, we can look into increasing the log levels and maybe figure out what is happening here exactly.

There was a user recently reporting similar problems on an Azure cloud setup - but the user reported it worked better once switching from the Azure storage service to a actual Docker-based setup...

**Comment by purple749** [comment]
Just tried the following:
- exported the project from the Docker container version of Inception
- downloaded the 0.18.1 JAR, started running and imported the project
- the user attempted to keep annotating this same document that was giving them trouble and after a few annotations quickly started getting the Concurrent Modification exceptions again.

Just as an additional note, there are several other annotators on the project and none of them have seen this issue (though they have been annotating other documents, not the one where we've been seeing this issue). I have tried to annotate this document myself a bit (as the admin user) and have not run into this issue.

**Comment by reckart** [comment]
Hm, so you have the problem with (a) specific document(s)?

**Comment by purple749** [comment]
For this specific user, they have been trying to annotate this particular document, yes. They have not annotated many documents in this project yet and haven't noticed this with others. They will try annotating a few others and if this issue pops up again I will add a comment about that. 

However, I'm not sure that it's document-specific - I saw this error in the past (a few months ago with Inception 0.17.2, both with the JAR and in a Docker container) with other documents, but I ended up downgrading (to I think 0.16.1 via a Docker container) and never saw that error again. Unfortunately, there are circumstances requiring that we use a more recent version, which is why I guess we are seeing this error again.

**Comment by reckart** [comment]
So we do indeed seem have a bug in the storage engine that causes the CAS to be deleted if a concurrent access was detected. I'm fixing that.

But the question is: why do you hit the concurrent access in the first place if you are sure that the same user is not logged in multiple times / works on the same document with multiple windows...

**Comment by purple749** [comment]
Great, thank you. I'll comment if we get any additional insights into the concurrent access issue on our end.

**Comment by reckart** [comment]
Fixed upstream and in daa3a3a686cc7fa05ba5d3c9cf7a4171a80ce500

**Comment by huzefaqubbawala** [comment]
We are facing similar issue with latest version of inception.

Scenario -

- We are using Azure web app with docker and mounted azure file storage 
- Getting this exception frequently - Error: Detected concurrent modification to file in storage (expected timestamp: 1621520164638; actual timestamp in storage 1621520164750) - please try reloading before saving again.
- When I downgrade this to docker image 0.17.3 everything works fine.

Is the fix present in latest release ?

**Comment by reckart** [comment]
The fix for annotations being deleted on a concurrent access detection is present. **You should definitely not use INCEpTION versions prior to: 0.18.3**

However, the problem with mounted azure file storage is apparently now. We do believe that it is a problem with the Azure File System and not with inception. See: 

* https://github.com/inception-project/inception/issues/1879
* https://feedback.azure.com/forums/223579-azure-portal/suggestions/42201571-timestamps-in-azure-file-storage-not-reliable

Apparently, the issue resolves itself once using a proper Azure VM with a virtual harddisk instead of the mounted azure file storage.

If you can provide any further insight that would indicate a problem with INCEpTION itself or get any more insight on the way file timestamps are handled in the azure file storage, please let us know.

**Comment by huzefaqubbawala** [comment]
Thanks for the reply.

I am curious to understand why this does not occur if I use inception 0.17.3 version with azure file storage.

Ideally we want our system to auto scale and hence going with Azure VM, Virtual hard disk is not something we are looking for.

**Comment by reckart** [comment]
The issue here is rather about losing annotations because of a bug in the concurrent access detection. The discussion about compatibility with Azure is rather here: https://github.com/inception-project/inception/issues/1879 - to keep information together, it would be better to discuss there.
