### ISSUE TITLE
Plugins, extenstion for Inception - is there any documentation/best practices?

### ISSUE THREAD

**Issue by k-sap** [inception-project/inception#2049]
**Is your feature request related to a problem? Please describe.**
I have a few specific annotation problems to solve via custom code: visualisation, comparison, serialisation etc. I'd like to add to Inception. I already have some working code as a fork repository of Inception and Webanno.

**Describe the solution you'd like**
My question is is there some easy way to separate my custom code as an external plugin. The plugin could be used by other people, especially my team, to install and update the plugin in an easy way. Easier than updating directly Inception from fork repository.

Is there any documentation about that kind of case? Is it possible on the level of Incpetion or Java/Maven? 

**Describe alternatives you've considered**
Should I just create releasable Docker image with custom Inception version? That's possibly the easiest way, but it requires admin activity and is not backward compatible with running Inception instances.

**Additional context**
I attach the link to one of the forks of Incpetion I'd like to work with: https://github.com/pw-mini-ig/inception

**Comment by reckart** [comment]
There are at least two approaches:

1) There is an experimental plugin mechanism in INCEpTION. Currently, two of the modules that are in the INCEpTION repository are realized as plugins. They are built as part of the normal Maven build, but they just produce JARs which are not bundled up into the standalone JAR or into the Docker. Instead, one can install them by dropping them into `{inception.home}/plugins`. Besides the examples, there is no additional documentation yet. The examples are both recommenders. We did not yet try if the mechanism supports plugins that include UI/Wicket code/HTML.
  - inception-example-imls-data-majority
  - inception-imls-dl4j
2) You can create a separate repo containing a Maven project with two submodules. The first module would be a JAR module contain your custom extensions. The second module would be a WAR module which uses the inception-app-webapp module as an overlay. This module depend on the first module as well as on the inception-app-webapp and allow to package both of them into a custom standalone JAR. Additionally, a class will be needed in the module which inherits from the INCEpTION.java class and which has a main method that calls the INCEpTION.main method. It will run as a standalone application in Eclipse or probably other IDEs or as a standalone JAR - but I didn't get this kind of setup running with the Eclipse WTP tooling yet.

Mind that the APIs in INCEpTION at in flux. We do not (yet) have a particular strategy of requiring that APIs remain rock solid stable. So a plugin that runs in a particular version of INCEpTION may well not run anymore in the next version.

**Comment by reckart** [comment]
I'm afraid, we do not have a concept for API stability and tracking yet. 

The best option right now would probably be to have a continuous integration system (maybe like GitHub Actions) monitor the inception repo as well as your repo and perform regular integration tests so see when/if things break.

**Comment by reckart** [comment]
Assuming the question was answered.
