### ISSUE TITLE
Cannot see agreement menuitem icon

### ISSUE THREAD

**Issue by UWinch** [inception-project/inception#2050]
**Describe the bug**
The icon for the agreement menu item on the dashboard is not shown.

**To Reproduce**
1. Go to the dashboard 

**Screenshots**
![no_agreement_icon](https://user-images.githubusercontent.com/29500351/109969729-8464e000-7cf4-11eb-8dda-931d629541e1.png)

**Please complete the following information:**
 - Version and build ID: 0.19.-SNAPSHOT
 - OS: Linux
 - Browser: Chrome

**Additional context**
On feature branch, did not check master.

**Comment by reckart** [comment]
Do you have more than one annotator in the project?

**Comment by UWinch** [comment]
Yes

**Comment by reckart** [comment]
aah,.. *ICON* - of course... doh
