### ISSUE TITLE
UX/UI: Visual similarity between "Delete" project and "Delete" document

### ISSUE THREAD

**Issue by habernal** [inception-project/inception#2061]
**Describe the bug**
On the Settings -> Documents page, there are two "Delete" buttons. Hard to tell which one does what on the first glance. Suggestion: Rename the bottom one to "Delete document" to make it very clear. (and the top one to "Delete project" would be great too).

**Please complete the following information:**
 - Version and build ID: 0.18.3 (2021-03-09 20:02:49, build bf16e970)

**Comment by reckart** [comment]
Fixed by commit https://github.com/inception-project/inception/commit/07fa950f9138aac7addc363243529d87391e9353 which has the wrong title...
