### ISSUE TITLE
UX/UI: Nonsense prompt in confirmation dialog for deleting single document

### ISSUE THREAD

**Issue by habernal** [inception-project/inception#2062]
**Describe the bug**
See screenshot

**To Reproduce**
1. Go to 'Project settings - Documents'
2. Click on 'Document and Delete'

**Expected behavior**
Document name?

**Screenshots**
![screenshot_2021-03-10_09-49-52](https://user-images.githubusercontent.com/11850778/110602479-58c77700-8186-11eb-81d9-abd0c9946df2.png)

**Please complete the following information:**
 - Version and build ID: 0.18.3 (2021-03-09 20:02:49, build bf16e970)

**Comment by reckart** [comment]
Actually it was meant to say "Are you sure you want to delete 1 document(s)?"
