### ISSUE TITLE
Export as XMI produces JSON

### ISSUE THREAD

**Issue by david-waterworth** [inception-project/inception#2065]
I'm not sure if I'm doing this correctly, my motivation was I've added a custom layer and need to export the TypeSystem.xml file for use with `cassis`.

I went to the Export tab, selected "UIMA CAS XMI (XML 1.1)" and hit Export. A zip file was produced containing `exportedproject8754122862091094589.json` in the root along with other subfolders

I'm assuming this should be an xmi file and the TypeSystem.xml should be along side it?

I found another hack of exporting an existing annotation in "UIMA CAS XMI (XML 1.1)"  and then copying the TypeSystem.xml but I assume there's a more direct way of doing this?

I'm using version 0.18.2 locally

**Comment by jcklie** [comment]
The XMI is zipped up under the `annotations`  folder:
```

│   event.log
│   exportedproject2452654953818172424.json
│
├───annotation
│   └───act01_tyndale.txt
│       │   webanno6151388004753565972export.zip
│       │
│       └───webanno6151388004753565972export
│               klie.xmi
│               TypeSystem.xml
│
├───annotation_ser
│   └───act01_tyndale.txt
│           INITIAL_CAS.ser
│           klie.ser
│
├───kb
│       SemanticBible.ttl
│
├───log
│       project-160.log
│
└───source
        act01_tyndale.txt
```

I extracted it so you better see how the export layout is. Is it not there for you?

**Comment by david-waterworth** [comment]
@jcklie Ahh yes it is - I didn't look close enough. I didn't notice that `annotation/act01_tyndale.txt` was actually a folder, I assumed it was a file.
