### ISSUE TITLE
Error in string interpolation in log4j2.xml or ctx:repositoryPath not defined

### ISSUE THREAD

**Issue by sandimschuh** [inception-project/inception#2071]
**Describe the bug**
When I run INCEpTION in VSCode a file named ${ctx:repositoryPath}/project/project-0.log was created in the root folder. Perhaps this phenomenon occurs only when using the Remote API. In my case, this file was created when I used the remote API for the first time.

![image](https://user-images.githubusercontent.com/345385/110828979-e9da4300-8297-11eb-883f-076205a82d2f.png)
![image](https://user-images.githubusercontent.com/345385/110837628-c1574680-82a1-11eb-840d-f64dfe9d6521.png)

**Please complete the following information:**
 - Version and build ID: v0.18.3 build 492bf63f
 - OS: Linux 
 - IDE: VSCode

**Comment by reckart** [comment]
I hope that #2090 fixes the issue. If not, please feel free to re-open.

**Comment by reckart** [comment]
Actually, #2226 should probably (finally) fix this one... I hope.
