### ISSUE TITLE
String matcher suggestions applied non-deterministically?

### ISSUE THREAD

**Issue by david-waterworth** [inception-project/inception#2072]
**Describe the bug**
In the example below, the string recommender has identified two span's for eZVP-440, the entire sequence just the first 4. The reason is 4 occurs as an id in different context (I'm not sure why it's not suggested the other 4 as well). 

**Expected behavior**
What I've observed though is when I select `apply all` it's 50:50 which will get accepted. In general I would prefer it to either always select the longer one, or always select the one which I've reinforced as correct. I keep removing the 4 but it continues to add it back and select it as the correct annotation. I've tried retraining but that doesn't help (I assumed it would clear out the models state and only use what's accepted but I've observed the only way to truly reset a recommender seems to be to delete and recreate it).

**Screenshots**
In this case I've not been assigning a value to the named entity as I'm not clear at this stage what "thing" an eZVP-440 is, I'm not sure if that's causing the issue. At some stage I want to plug in my own recommender and use the active learning but for now I need to bootstrap enough labelled data.

![image](https://user-images.githubusercontent.com/5028974/110871445-8d703580-8322-11eb-8d3a-9008974adbef.png)
![image](https://user-images.githubusercontent.com/5028974/110871766-14bda900-8323-11eb-8fc7-34073503c3f2.png)

**Please complete the following information**

Version and build ID: 0.18.2

**Comment by reckart** [comment]
A deterministic behavior at least should be expected, so I'd agree this is a bug.

Please use the issue templates when creating an issue as they query for relevant information (including the version of INCEpTION where an issue has been observed) and organize it into a structure which helps us.

**Comment by reckart** [comment]
The code has been changed from "accept all" to "accept best" - so in principle those labels that are used more should win because they get assigned a higher score by the string matching recommender. That said - if two labels have a tied score, the assignment may still be random.
