### ISSUE TITLE
Create example of how to prepare an XMI file for import into INCEpTION

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#2073]
**Is your feature request related to a problem? Please describe.**
Create an example of how to prepare an XMI file externally from scratch for import into INCEpTION.

**Describe the solution you'd like**
A Jupyter/Colab notebook showcasing:

* How to prep an XMI file just with DKPro Core tokens and sentences and text
* How to create custom layers in INCEpTION, export them as a type system file, and then generate matching XMI files

**Additional context**
See: https://github.com/inception-project/inception/issues/2060#issuecomment-797056568

**Comment by jcklie** [comment]
Is this done?
