### ISSUE TITLE
UI: Dynamic palette in HTML makes highlighted text hardly readable

### ISSUE THREAD

**Issue by habernal** [inception-project/inception#2074]
**Describe the bug**
Some background colors generated by the palette are too dark (e.g., dark blue), so one cannot read the annotated text.

**Expected behavior**
Generate only colors that provide good contrast with black text font.

**Please complete the following information:**
 - Version and build ID: 0.18.4-SNAPSHOT (2021-03-11 06:23:19, build f4260acd)

**Comment by reckart** [comment]
You can switch between different palettes in the preferences (cogwheel) on the annotation page. Is there another palette which you find better?

**Comment by habernal** [comment]
I tried, but all the static ones do not distinguits between different tags, they only highlight "binary" (annotation / no annotation).

**Comment by reckart** [comment]
Ah, I see - gotcha.

**Comment by reckart** [comment]
I think this upstream change addresses the problem: https://github.com/webanno/webanno/issues/1897
