### ISSUE TITLE
String Matcher no longer providing recomendations for numeric strings

### ISSUE THREAD

**Issue by david-waterworth** [inception-project/inception#2084]
**Describe the bug**

I upgraded to 0.18.3 and am no longer getting recommendations for numeric spans, for example, `1` from `AHU1`  and `550` from `ACH550` (despite annotating several examples). Prior to the upgrade, this worked, although I have been switching from token and character-based spans at the same time so I'm not entirely sure what triggered the issue.

Edit: I think the numeric span observation may be a red herring. After a bit more time it seems that the recommender is just randomly missing a few annotations per document. For similar documents, it's generally the same annotations it misses (hence my observation) but when I moved to a different set I observed that it was consistently not recommending a different set of tags. It's almost like there's a timeout so the last few don't get displayed.

**Comment by reckart** [comment]
You have the option of triggering a force re-train in the recommender sidebar on the annotation page. That should discard any existing state and regenerate from scratch. There is also an option to access a log there about what the recommenders are doing. In the next version, the log will also be a bit more detailed and the per-recommender activity indicators at the bottom of the sidebar will have tooltips explaining why inactive recommenders are inactive.

We have a bug prior to 0.18.2 with the string matching recommender missing stuff (#2031). 

It is internally possible to limit the data on which recommender is trained - this is used during self-evaluation. But when training for giving actual predictions, they should train on the full data.

**Comment by david-waterworth** [comment]
I've been pressing that but it's not obviously doing anything - at least the log doesn't indicate anything and the annotations don't change.

**Comment by reckart** [comment]
In 0.18.x, the suggestions are not cleared from the screen immediately - and by the time you refresh the screen, they may already have been re-generated. For 0.19.0, there will be a feedback message and the suggestions are cleared immediately and only come back when the re-training is done (requires action or refresh).

Also, there will be the option to export the dictionary learned by the string matcher from the recommender sidebar - so we can better investigate this kind of issue.

**Comment by david-waterworth** [comment]
I'll try using an external recommender (i.e. https://github.com/inception-project/inception-external-recommender/blob/master/ariadne/contrib/stringmatcher.py) - that might give me more insight into what's going on.

**Comment by david-waterworth** [comment]
One thing which comes to mind.  I switched to character-level spans, and excluded tokens from my XMI. As you mentioned earlier tokens are then added when the file is imported. However, the tokenisation isn't compatible with my text - for example, AHU1 is tokenised as a single token, not AHU and 1. This means that whilst I can annotate AHU and 1 as separate NamedEntity spans, I'm wondering if they're getting ignored by the recommender due perhaps to [StringMatchingRecommender.java#L233](https://github.com/inception-project/inception/blob/f2e8f727bcb7010c91088255a6101a59e0aca536/inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/StringMatchingRecommender.java#L233)

There does seem to be code to exclude this check if the layer has character-level enabled though. However, when I modified the generation of the XMI to include a token for each character (excluding whitespace etc.) it did start showing the missing recommendations (unfortunately usability drops as it starts producing far more spurious matches but that's to be expected - but the main reason I'm doing this is to validate how I need to tokenise my text, then I'll go back to token-level).

**Comment by jcklie** [comment]
@david-waterworth The stringmatcher in ariadne is different and slower than the one in INCEpTION, it uses fuzzy matching based on levensthein distance and might be a bit buggy.

**Comment by david-waterworth** [comment]
Yes I just used it to get a better idea how the recommenders work and then went back to the standard string marcher. My comment above is based on the Java string marcher not the levenstein version.

**Comment by reckart** [comment]
@david-waterworth have you have the chance to upgrade to 0.19.0? Do you still experience this issue? Note that the recommender should respect the layer granularity, so if you switch from character-recommendations to token-recommendations, you shouldn't get character-level suggestions anymore.

**Comment by david-waterworth** [comment]
@reckart not yet but I will do before I next use it.

**Comment by david-waterworth** [comment]
@reckart I've been using 0.19.2 and it's working fine - but I think the original issue is due to

- Not providing tokens in the xmi file
- Using character-based annotation
- The automatically generated tokens are at "word" rather than "character" level

I'm no longer doing this (not providing a tokenisation in the xmi documents) so I no longer have the issue but I suspect the underlying cause remains.

**Comment by reckart** [comment]
Ok, I'm closing this then because I'm not really sure if there is anything we should fix here. If you think a particular change to the code would be necessary, feel free to comment, then we can re-open.
