### ISSUE TITLE
Add testing profiles

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#209]
For every PR, all the tests are run, some of them are really slow. In order to improve PR turnaround time, add profiles to flag slow tests. Only run these before merging.

- [x] Flag slow tests
- [x] Update CI configuration

**Comment by reckart** [comment]
@Rentier How does Jenkins know that a PR is "before merging"? I believe we only have the option to reduce build times for PR builds and then run the long-running tests **after** merging (i.e. on the master branch build). Or is there any GitHub hook that triggers when the "merge" button is pressed?

**Comment by reckart** [comment]
It might be possible to set up multiple PR jobs on Jenkins and activate some only when talking something specific... never tried this.

**Comment by reckart** [comment]
We annotate several tests with `@Category(SlowTests.class)` since a while and run these only on the CI but not for simple local builds.

This was introduced in commit d6103530797f9c44eb58a665942a6d3464f56af4.
