### ISSUE TITLE
Gazetteer Case Sensitive

### ISSUE THREAD

**Issue by david-waterworth** [inception-project/inception#2105]
**Is your feature request related to a problem? Please describe.**
The String Matcher Gazetteer appears case sensitive. If I have an entry `drive` it doesn't appear to match `DRIVE` or `Drive`. I've not actually verified but perhaps the string matcher itself also is?

**Describe the solution you'd like**
Being able to configure the string matcher and gazetteer to be case insensitive.

**Comment by reckart** [comment]
The matcher is currently case sensitive, but it should be simply to lower-case words before adding/matching them in order to achieve a case independent matching.
