### ISSUE TITLE
Reload of Knowledge Base

### ISSUE THREAD

**Issue by david-waterworth** [inception-project/inception#2113]
**Describe the bug**
I may be misunderstanding how to update a knowledge base but after I create a knowledge base I find that I can clear and reload once and on subsequent attempts it fails with "admin: Failed to import: tagsets.ttl". There's nothing wrong with the ttl file, recreating the knowledge base from scratch works.

**To Reproduce**

1. Create a knowledge base by importing a TTL file. I'm using my own `Base Prefix`, `Local` and I set IRI Schema to `OWL`.
2. Clear contents
3. Import contents
4. Repeat steps 2 and 3. On repeat the import fails.  

**Expected behavior**
Be able to reimport a knowledge base without having to delete and recreate the configuration

**Please complete the following information:**
 - Version and build ID: INCEpTION -- 0.18.3 (2021-03-09 20:02:49, build bf16e970)
 - OS: Ubuntu
 - Browser: Chrome

**Comment by reckart** [comment]
Any error logged to the console?

**Comment by david-waterworth** [comment]
No. One thing I have noticed. I can get a schema validation error because I've messed up the TTL ie.

ParseErrorLogger - [Rio fatal] Expected ']', found '.' (896, -1)

So I fix it, check with a validator and then attempt to reload and it reports the same error. It's also like it's re-processing a cached version of the file at times. But I also get the error when I'm loading a valid file at times.

I should probably switch from files to a triple store and generate my TTL using a tool.

**Comment by david-waterworth** [comment]
Also note the same issue occurred using a SPARQL endpoint. I spun up a stand-alone fuseki instance serving the ttl file read-only.

I accidentally set the SPARQL endpoint URL to `https:\\0.0.0.0\ontology` - https isn't supported in stand-alone mode.

I tried to fix it by editing the config, it continued to report SSL errors. I had to delete and recreate with the correct URL before the error would go away.

**Comment by reckart** [comment]
With SPARQL endpoints it is a known bug that you have to recreate or to restart the server to apply an url change.

**Comment by david-waterworth** [comment]
Also presumably related, the ontology seems to be cached (I guess by concept using the concept name as a key) and there's no way to clear the cache other than by recreating or restarting.

**Comment by reckart** [comment]
There is a way to influence the caches via the `settings.properties` file (values given below are defaults):

```
knowledge-base.default-max-results=1000
knowledge-base.hard-max-results=10000
knowledge-base.cacheSize=100000
knowledge-base.cacheRefreshDelay=5m
knowledge-base.cacheExpireDelay=15m
```

Supported time units (as per Spring Boot):

* `ns` for nanoseconds
* `us` for microseconds
* `ms` for milliseconds
* `s` for seconds
* `m` for minutes
* `h` for hours
* `d` for days

**Comment by reckart** [comment]
I don't think this issue still exists. If somebody can reproduce this in the current INCEpTION version, please open a new issue.
