### ISSUE TITLE
Display of recomdenations after re-training

### ISSUE THREAD

**Issue by david-waterworth** [inception-project/inception#2118]
**Describe the bug**
I've noticed two quirks with recommendations after retraining.

1. After retraining a recommender from the sidebar, click on a recommendation that was already present causes a pop-up "Error: Null"
2. When you open a new document when using an external recommender the results from the response to "predict" aren't displayed until you interact with the document.

I suspect these have the same cause. The internal state of the document (the response from the recommender) is out of step with the graphical representation in the UI. A redraw isn't requested until some user interaction.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open a document and ensure there are unaccepted recommendations
2. Click on retrain
3. Click on one of the previous recommendations

**Expected behaviour**
When a recommender updates the state of the active document it should be displayed on the screen as soon as the response is received.

**Please complete the following information:**
 - Version and build ID: 0.18.3 (2021-03-09 20:02:49, build bf16e970)
 - OS: Ubuntu 20.04
 - Browser: chrome

**Comment by reckart** [comment]
With 0.19.0 the suggestions on screen are cleared when retraining is requested. The suggestions only show after an interaction because if we would show them immediately the screen layout would jump around and you would surely find that very annoying. Also we do not support Server push at yet.
