### ISSUE TITLE
Using Brick Knowledge Base

### ISSUE THREAD

**Issue by david-waterworth** [inception-project/inception#2120]
I'm trying to use concepts from the [Brick](https://brickschema.org/schema/1.2.0/Brick.ttl) ontology. I've created two layers, a named entity layer, and a relationships layer. For both I allowed <any concept/instance> from the knowledge base.

This works for for the named entity layer. However I'm having issues the relationships. There's a relationship defined in the schema as `brick:isPointOf` / `brick:hasPoint` 

These aren't appearing in the drop down list of the annotation interface - I believe because they don't have a `rdfs:label` ?

Is that correct? I guess it's not that hard for me to generate labels. The names to be all camel or snake cased

```
brick:hasPoint a owl:AsymmetricProperty,
        owl:IrreflexiveProperty,
        owl:ObjectProperty ;
    rdfs:range brick:Point ;
    owl:inverseOf brick:isPointOf ;
    skos:definition "The subject has a digital/analog input/output point given by the object"@en .

brick:isPointOf a owl:AsymmetricProperty,
        owl:IrreflexiveProperty,
        owl:ObjectProperty ;
    rdfs:domain brick:Point ;
    owl:inverseOf brick:hasPoint `.`
```

Instead of appearing as properties, they appear as instances of the ObjectPropery class. I'm not sure if that's incorrect, it doesn't seem any different o `brick:FeedsAir` other than that it's also `a owl:AsymmetricProperty` and `owl:IrreflexiveProperty`.

![image](https://user-images.githubusercontent.com/5028974/111940131-160c8400-8b22-11eb-9783-9c75d99216e3.png)

The issue is even though I have <any concept/instance> selected, I cannot find

**Comment by reckart** [comment]
Properties are not treated as "concepts/instances" - to have them, you need to select "properties only":

<img width="715" alt="Screenshot 2021-03-23 at 08 57 05" src="https://user-images.githubusercontent.com/1410238/112112385-beb7f380-8bb5-11eb-89d0-1617b2b7ffba.png">

... and yes, they need to have a label.

**Comment by david-waterworth** [comment]
Thanks, I added an additional ttl file containing the labels and it works.

Although if you look at the image I uploaded, 'hasPoint' is not being treated as a property, if I'm not mistaken it's an instance of the ObjectProperty concept?

**Comment by reckart** [comment]
Ah, ok. Indeed. If the ObjectProperty would inherit from the property type configured in your KB mapping, then it should be treated as a property - if not, then `hasPoint` is treated as a regular instance.
