### ISSUE TITLE
Download link not working 

### ISSUE THREAD

**Issue by lfoppiano** [inception-project/inception#2121]
**Describe the bug**
The download link at the page: https://inception-project.github.io/downloads/ bring to a 404 page.

**To Reproduce**
Try to download the release from the website 

**Expected behavior**
the download link should be https://github.com/inception-project/inception/releases/download/inception-0.19.0/inception-app-webapp-0.19.0-standalone.jar

In the download page the link point to `inception-app-0.19.0` instead of `inception-0.19.0`

**Comment by reckart** [comment]
Fixed, thanks for the report!
