### ISSUE TITLE
Error 403 on Administration

### ISSUE THREAD

**Issue by habernal** [inception-project/inception#2122]
**Describe the bug**
See the screenshot

**To Reproduce**
Click Administration -> Projects

**Screenshots**
![screenshot_2021-03-22_19-48-08](https://user-images.githubusercontent.com/11850778/112042652-0d2ea900-8b48-11eb-972c-81dab75efbdb.png)

**Comment by habernal** [comment]
Actually, it wasn't clear what "Administration" should do - I expected it to be the "Settings" of the project, but obviously it's something different. If the current user has no access right, better hide the link. 403 is confusing.

**Comment by reckart** [comment]
In that past, that was a (necessary) way for users with the project creator role to access their project settings, but this has been superseded by other way now. We'll remove the option for non-admins.
