### ISSUE TITLE
Configurable whitespace replacement character

### ISSUE THREAD

**Issue by ofersabo** [inception-project/inception#2125]
Rendering of non-ascii characters has changed during the transition from 0.17.3 to 0.17.4 inception versions.
Particularly, non-ascii character - \u200F is not rendered correctly as of 0.17.4 version.
This naturally happens for non-English text - in this example, it is for Hebrew which is an RTL language. 

**To Reproduce**

1. Lunch the 0.17.3 and the 0.17.4 versions.
2. create any project to both versions to which you import the attached txt file. 
3. see the differences in the appearance at a particular place. see attached image. 

**Expected behavior**
Both documents should be displayed identically without the weird question mark.

![Screen Shot 2021-03-22 at 22 38 31](https://user-images.githubusercontent.com/31179968/112055464-8c7ba700-8b5f-11eb-9e0c-32a311029be6.png)
[reproduce.txt](https://github.com/inception-project/inception/files/6185153/reproduce.txt)

**Please complete the following information:**
 - OS: OSx
 - Browser: chrome

to adopt the new version we must have documents displayed identically across versions.

**Comment by reckart** [comment]
The idea in the change was to raise awareness of characters in the text which may be problematical - e.g. because the tokenizer might not recognize them properly as whitespace and other kinds of issues.

I think a good option could be to allow configuring which character is used to substitute such potentially problematic characters.

**Comment by reckart** [comment]
Made the default replacement character a non-breaking space again (as with 0.17.3) and made the setting configurable.

The best way would be to not render such zero-width characters or actually render them as themselves - but some browsers (e.g. Firefox) then do not return the correct offsets for text selection because they do not count zero-width characters.

Btw, below you see an illustration of a named entity which *should* have only applied to "rul", but was expanded because the tokenizer is unable to handle the right-to-left mark.

<img width="900" alt="Screenshot 2021-03-23 at 08 24 42" src="https://user-images.githubusercontent.com/1410238/112109012-4e0ed800-8bb1-11eb-9aa7-66d3baaaaf1d.png">

**Comment by ofersabo** [comment]
Thanks for your input :) 

we create a pre-processing step to handle the cases where the INCEpTION tokenizer can't handle the right-to-left marks.

**Comment by reckart** [comment]
So... should we keep the questionmark-thingy as the default replacement character to make it more obvious to users that there is something fishy they might care to look at?

**Comment by ofersabo** [comment]
yup, I think it's a good idea to keep these question marks as default. 

btw, I can't seem to understand when these question marks appear exactly. 
so in the exampled document, there were more such tokens \u200F which were just ignored, i.e. there are not shown in the report. do you happen to know when these tokens appear?

**Comment by reckart** [comment]
They should appear whenever one of these characters is encounterd in the document:

```
            case '\u2000': // EN QUAD
            case '\u2001': // EM QUAD
            case '\u2002': // EN SPACE
            case '\u2003': // EM SPACE
            case '\u2004': // THREE-PER-EM SPACE
            case '\u2005': // FOUR-PER-EM SPACE
            case '\u2006': // SIX-PER-EM SPACE
            case '\u2007': // FIGURE SPACE
            case '\u2008': // PUNCTUATION SPACE
            case '\u2009': // THIN SPACE
            case '\u200A': // HAIR SPACE
            case '\u200B': // ZERO WIDTH SPACE
            case '\u200C': // ZERO WIDTH NON-JOINER
            case '\u200D': // ZERO WIDTH JOINER
            case '\u200E': // LEFT-TO-RIGHT MARK
            case '\u200F': // RIGHT-TO-LEFT MARK
            case '\u2028': // LINE SEPARATOR
            case '\u2029': // PARAGRAPH SEPARATOR
            case '\u202A': // LEFT-TO-RIGHT EMBEDDING
            case '\u202B': // RIGHT-TO-LEFT EMBEDDING
            case '\u202C': // POP DIRECTIONAL FORMATTING
            case '\u202D': // LEFT-TO-RIGHT OVERRIDE
            case '\u202E': // RIGHT-TO-LEFT OVERRIDE
            case '\u202F': // NARROW NO-BREAK SPACE
            case '\u2060': // WORD JOINER
            case '\u2061': // FUNCTION APPLICATION
            case '\u2062': // INVISIBLE TIMES
            case '\u2063': // INVISIBLE SEPARATOR
            case '\u2064': // INVISIBLE PLUS
            case '\u2065': // <unassigned>
            case '\u2066': // LEFT-TO-RIGHT ISOLATE
            case '\u2067': // RIGHT-TO-LEFT ISOLATE
            case '\u2068': // FIRST STRONG ISOLATE
            case '\u2069': // POP DIRECTIONAL ISOLATE
            case '\u206A': // INHIBIT SYMMETRIC SWAPPING
            case '\u206B': // ACTIVATE SYMMETRIC SWAPPING
            case '\u206C': // INHIBIT ARABIC FORM SHAPING
            case '\u206D': // ACTIVATE ARABIC FORM SHAPING
            case '\u206E': // NATIONAL DIGIT SHAPES
            case '\u206F': // NOMINAL DIGIT SHAPES
```

**Comment by reckart** [comment]
Could be that brat doesn't care for them / render them if they appear in between tokens... if you have an illustrative file, I could take a look.

**Comment by ofersabo** [comment]
yea, we've a bunch of them, sending you them by email.

**Comment by reckart** [comment]
In the sample you sent, it looks like in most of the cases, the characters appear at the token boundaries - the rendering code strips these off the the tokens before displaying them. The place where you noticed the � appears to be the only case in the document where the right-to-left appears within a token.

**Comment by reckart** [comment]
Actually, if you look at the data being sent from the server, you can see the � characters all over the text, but since the brat visualization does not display things in between tokens, you don't see them on screen.
