### ISSUE TITLE
Exporting broken document not handled well

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#2130]
**Describe the bug**
When trying to export a document that is broken or which cannot be exported in a given format, there may not be an error message or the failure might just lead to a general failure error page not telling why the export actually failed.

**To Reproduce**
See: https://github.com/inception-project/inception/issues/2002#issuecomment-804461281

**Expected behavior**
There should be a proper error feedback message.

**Screenshots**
See: https://github.com/inception-project/inception/issues/2002#issuecomment-804461281

**Please complete the following information:**
 - Version and build ID: 0.19.0

**Comment by lfoppiano** [comment]
I've updated to the 0.19.1 and it seems that the error message is the same. 

<img width="1156" alt="image" src="https://user-images.githubusercontent.com/15426/112777560-10d39b80-9032-11eb-905a-530cbb153e68.png">

**Comment by lfoppiano** [comment]
If I try to export from the curation page, I don't get the error page as p[reviously reported](https://github.com/inception-project/inception/issues/2002#issuecomment-804461281), but just an error saying NullPointerException: 

<img width="432" alt="image" src="https://user-images.githubusercontent.com/15426/112777676-52644680-9032-11eb-8956-9b49a601dcec.png">

**Comment by reckart** [comment]
You get this message on the **project export page** in the project setting.

This issue is about the export dialog on the **annotation page** which had failed without producing any message at all.

Sorry about the confusion and thanks for pointing this out again.

**Comment by reckart** [comment]
Besides that - does CAS doctor (0.19.0) help to find and fix the problem?

**Comment by lfoppiano** [comment]
I understand. I wanted to close #2002, but I guess we can leave it open for the time being. 

> Besides that - does CAS doctor (in >= 0.19.0) help to find and fix the problem?
Yes, I was able to fix the problem with the new CAS doctor. Thanks!
