### ISSUE TITLE
Slow performance and brwoser crash ('Aw, Snap!')

### ISSUE THREAD

**Issue by Maroussia** [inception-project/inception#2143]
**Describe the bug**
(1) Slow annotation process: when I select the chunk/named entity to annotate, it takes about 5-10 seconds to let me choose the right tag, and again 5-10 seconds to validate my choice before I can annotate further. It's a bit faster when I disable the recommenders, but only slightly.
(2) Browser crash: increasingly the browser crashes ('Aw, Snap!') and the only way to continue annotating is by restarting INCEpTION all together.

**To Reproduce**
I sent my project export to @reckart, let me know if you need more information to test it.

**Expected behavior**
A slightly faster annotation process would make the work more efficient. Yet, I prefer it to be slow than having the server crashing, so ideally the annotation process should be relatively fast and without crashing the browser, or at least slow without crashing.

**Screenshots**

**Please complete the following information:**
 - Version and build ID: 0.19.0 (build 3f297349)
 - OS: Linux, Ubuntu 20.4
 - Browser: Version 1.21.77 Chromium: 89.0.4389.90 (Official Build) (64-bit)

**Additional context**
I have been annotating 2 texts in classical Arabic. The first text contains 300 lines (5963 tokens). I had two levels of annotations: NER and Chunk, using two recommenders: String Match and Multi-Token Sequence Classifier (OpenNLP NER). The annotation was slow (very slow at times) but the browser crashed only a few times.
The second text contains 504 lines (14339 tokens). I started annotating only the chunks disabling the recommenders for NER as well as the Multi-Token for chunk, keeping only the String Match, after I experienced several browser crashes (every 2-5 annotations). I am still battling with it and managed to annotate about 300 lines so far.
I will try to reduce the size of the text to see if it can get slightly quicker. Is there an ideal size for each document? Has someone tried performance with different document size? Is there anything else I am doing wrong? 
The side bar was never opened as described by @david-waterworth in [here](https://github.com/inception-project/inception/issues/2098#issue-832227842), because I noticed this was slowing down the annotation process even more.
Thanks a lot for your great work and support!

**Comment by reckart** [comment]
@Maroussia I had a look at the project. It appears as if the automatic sentence splitting has completely failed on your file. Looks like there is no punctuation in it - at least non that the sentence splitter is able to deal with.

However, it looks like treating the files as "one sentence per line" would be sensible. So I'd recommend to import these files using the "Plain text (one sentence per line)".

This lack of sentences is also the cause of the annotation being so slow. The entire document is treated as a single sentence which causes the default "brat (sentence-oriented)" to try and display the entire document as one huge sentence - which is awefully slow.

If you import as "Plain text (one sentence per line)", things should be much faster. They are also faster if you switch e.g. to "brat (line-oriented)" or "brat (wrapping @ 120 chars)".

**Comment by Maroussia** [comment]
Thank you so much @reckart!

Indeed, I had noticed the segmentation problem, I could not even load the document initially without crashing the browser. This is why I uploaded a smaller document, opened it, applied the ''brat (line-oriented)", and only then I could open the longer document, since the ''brat (line-oriented)" setting was retained. I also tried adding full stop (dot) at the end of each sentence in my first document (file starting with AN_0179...), but I had to apply the ''brat (line-oriented)" to have the document split by sentence nevertheless and it did not improve the speed performance.

I have just tried your suggestion and started annotating a file uploaded with "Plain text (one sentence per line)". It is still slow (maybe a bit less), but the browser crashed only once over 100 lines, which is a great improvement.

I will try further to segment my file in less lines, adding full stops maybe, and see if this improves the performance, since the size seems to be an issue together with the segmentation with "\n".

**Comment by reckart** [comment]
Ok, so here is what I tried:

* Removed all the documents from your project (all annotations lost of course)
* Imported the documents again using "Plain text (one sentence per line)"
* Went to the annotation page, switched to "Auto" mode in the preferences dialog and set a page size of 10
* Annotated a few chunks

The annotation seems to me to be fast - recommenders remained enabled (I didn't change their config).

I didn't annotate much, so it could be that things slow down with many annotations, but at least so far, I didn't notice any problems.

**Comment by reckart** [comment]
Note that keeping the documents you already had in the project (which are treated as one humongous sentence) can retain the slowdown.

I would recommend that you export the project, re-import it (so you keep all your settings), delete all the documents and then import your documents as "Plain text (one sentence per line)" and try how it goes.

**Comment by Maroussia** [comment]
Many thanks! That's very useful. I will try that before anything else and let you know how it goes.

**Comment by Maroussia** [comment]
Following your instruction, I deleted completely the project and started it from scratch. It has considerably improved the speed and I haven't experienced any crashes so far :)
