### ISSUE TITLE
Add OCR capability to PDF editor

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#2148]
**Is your feature request related to a problem? Please describe.**
Some pdf are image only, they cannot be annotated right now with INCEpTION.

**Describe the solution you'd like**
Use OCR to add a text layer during import, like Apache Tika.

https://stackoverflow.com/questions/32354209/apache-tika-extract-scanned-pdf-files

**Comment by reckart** [comment]
Tika does not do OCR. It used Tessaract which needs to be installed at the system level. We cannot easily ship it with INCEpTION. Also my understanding is that tesseract does not work well out of the box and may need tuning and training. I believe PDFs should be OCRed externally and be turned into "searchable PDFs" before they are imported into INCEpTION with whatever is the best tool a particular user has available - possibly even a commercial tool like Finereader.
