### ISSUE TITLE
Not able to see Dashboard and other options like import project

### ISSUE THREAD

**Issue by kirti48** [inception-project/inception#2150]
**Describe the bug**
Clicking on the options available does not do anything and also not able to see few options
**To Reproduce**
1. Go to login screen
2. Click on Project

**Expected behavior**
logging into inception, i am not able to click on any option and also not able to see dashboard and other buttons

**Screenshots**

![image](https://user-images.githubusercontent.com/23244709/113265195-76a17b00-92f1-11eb-8709-779093fa698f.png)

**Please complete the following information:**
 - Version and build ID: [see bottom of the browser screen]
 - OS: [e.g. Windows, Linux, OS X] windows
 - Browser: [e.g. chrome, safari] safari

**Additional context**

**Comment by jcklie** [comment]
What happens if you actually agree or disagree to the telemetry?

**Comment by reckart** [comment]
The layout looks completely broken and the Safari version seems old. Which Safari version are you using? (Click on Safari in the menu bar and then on About Safari).

**Comment by reckart** [comment]
Closing as there was no further feedback,
