### ISSUE TITLE
Override default admin password and allow remote access

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#2164]
**Is your feature request related to a problem? Please describe.**
When doing an unsupervised deploy, I would like to be able to override the default admin password, have the admin account be created directly on startup (not on login page access) and have it be created with remote API permissions.

**Describe the solution you'd like**
Ability to set encoded PW and remote API role via properties.

**Comment by jcklie** [comment]
API keys would be also nice to be supported in this use case, see  #2165
