### ISSUE TITLE
Importing documents from external search sidebar gives errors

### ISSUE THREAD

**Issue by elizlee** [inception-project/inception#2172]
**Describe the bug**
For our project, we annotate imported documents from an ElasticSearch server. Whenever an annotator clicks on a document to import from the external search sidebar on the Annotation page, the app loads for three minutes, then gives a set of two messages at the bottom left corner of the screen around the same instance:
```
Imported document <document_123>
```
```
Error: de.tudarmstadt.ukp.clarin.webanno.api.casstorage.CasSessionException: Unable to borrow CAS
```
One annotator reported seeing this set of messages instead, but I myself have been unable to reproduce it:
```
Document already present: <document_123>
```
```
Unable to load document <document_123> IOException: There was a concurrent change to the document. Re-open the document to continue editing.
```
In both cases, the first message disappears after split second.

`inception.log` has this error logged around the same time:
```
12:44:22.649 [http-nio-8080-exec-4] ERROR de.tudarmstadt.ukp.clarin.webanno.ui.annotation.AnnotationPage - Error: de.tudarmstadt.ukp.clarin.webanno.api.casstorage.CasSessi
onException: Unable to borrow CAS
...
Caused by: de.tudarmstadt.ukp.clarin.webanno.api.casstorage.CasSessionException: Unable to borrow CAS
...
Caused by: java.util.NoSuchElementException: Timeout waiting for idle object
```
The imported document does not appear in the window -- you need to access it by going to the full list of documents and finding the document ID. When you click on it, you may or may not get the "Re-open the document" message, but either way, the document can be annotated.

There is no issue importing a document from the Search page. It would be nice though if the annotator didn't have to leave the Annotation page for each new document.

You can also load a document from the sidebar without issue if it is already labeled as "imported."

I have tried restarting INCEpTION and ElasticSearch, but neither have any effect. I also wondered if, given that the loading duration is exactly three minutes every time, it had something to do with the `cas-storage.cas-borrow-wait-timeout`, which by default is three minutes. However, changing the value to something else like `5m` did not change the load time.

The CAS Doctor has nothing to report on these documents when I check.

**To Reproduce**
1. Set up an ElasticSearch (version 6.6.1) server from which to import documents.
2. Begin a new project on INCEpTION.
3. Go to the Search page of that project, enter a query that will yield search results, and import one of the documents.
4. Go to the Annotation page by clicking "Open" beside the document you just imported.
5. Open the external search sidebar and enter another query.
6. Click one of the documents in the search results labeled "not imported" to import it. If you are experiencing the same issue, it will "load" for three minutes and then show you the two messages mentioned.
7. Click on the folder icon above the document view to bring up the complete list of imported documents. If you click the one that you just imported, you may get the "Re-open document" error message, but you will still be able to annotate it.

**Expected behavior**
After clicking a document from the external search sidebar, the document is imported in a matter of seconds and automatically appears in the annotation window with the search query highlighted and with no error message displayed.

**Screenshots**

![inception_import_error_01](https://user-images.githubusercontent.com/15387865/113741235-70374880-96cf-11eb-9511-6cf3fed095da.png)

**Please complete the following information:**
 - Version and build ID: 0.19.1 (2021-03-26 22:07:53, build b3eefe95)
 - OS: MacOS
 - Browser: Chrome, Safari

**Comment by reckart** [comment]
Thanks for the report. That should not happen - I'll look into it.

**Comment by reckart** [comment]
I can reproduce the issue with a PubAnnotation repo (easier to test than with ElasticsSearch) - during the import, a the storage runs into deadlock situation.

**Comment by reckart** [comment]
@elizlee release 0.19.2 with fix for this is out now.

**Comment by elizlee** [comment]
@reckart Thank you! 🎉
