### ISSUE TITLE
Make long relations nicer without arcs

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#2176]
**Is your feature request related to a problem? Please describe.**
Relations spanning more than a row are sometimes not looking good, especially if there are many of these.

**Describe the solution you'd like**
Several things are thinkable:

1. Use numbers at source and target 
2. Use same color something around source and target, e.g. underline

Hide the arcs, on hover, highlight both as always

**Comment by reckart** [comment]
I believe #4826 solves this issue here as well.
