### ISSUE TITLE
Minmal HTML document cannot be imported

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#2177]
**Describe the bug**
When I import

Error while uploading document foo.html: NullPointerException: Cannot invoke "org.dkpro.core.api.xml.CasXmlHandler$StackFrame.isCaptureText()" because the return value of "java.util.Deque.peek()" is null 

```
<!DOCTYPE html>
<html lang="en">
  <head>

  </head>
  <body>
      <p>Ich mag Rentiere</p>
      <p>I like reindeer.</p>
  </body>
</html>

```

**Please complete the following information:**
 - Version and build ID: 20.0 snapshot
 - OS: Windows
 - Browser: chrome

**Comment by reckart** [comment]
Looks like the importer doesn't like any type of characters outside the root `<html>/</html>` tags. I.e. removing the doctype and and potentially trailing empty lines and linebreaks makes the import work.
