### ISSUE TITLE
Different color for resolved conflicts

### ISSUE THREAD

**Issue by habernal** [inception-project/inception#2193]
**Is your feature request related to a problem? Please describe.**
Red boxes show sentences with conflicts in Curation. Once you resolve them (in any way), the red color remains.

**Describe the solution you'd like**
Able to set a different color (even manually), so one knows which conflicts have been resolved (curated) and which remain.

**Describe alternatives you've considered**
Excel sheet. That sucks though :)

**Additional context**
See screenshot
![screenshot_2021-04-14_15-40-10](https://user-images.githubusercontent.com/11850778/114721203-02c39180-9d39-11eb-96b4-e342b411ae2c.png)

**Comment by reckart** [comment]
I have a few ideas how to do that but its a bigger thing, so we'll have to let it slip for the next feature release.

**Comment by reckart** [comment]
<img width="616" alt="Screenshot 2021-07-02 at 21 43 16" src="https://user-images.githubusercontent.com/1410238/124321827-a37a5e00-db7e-11eb-957d-c5ad5789b39b.png">
