### ISSUE TITLE
UX / Curation / Left box too wide

### ISSUE THREAD

**Issue by habernal** [inception-project/inception#2194]
**Is your feature request related to a problem? Please describe.**
Long spans in curation are painful, one has to scroll horizontally through all of them. As a little help, having the left box with sentence numbers very narrow helps.

**Describe the solution you'd like**
Having it adjustable up to 5% only.

**Describe alternatives you've considered**
I hacked the CSS in Chrome and it worked well. After refresh, you have to hack it again.

**Additional context**
![screenshot_2021-04-14_15-40-11](https://user-images.githubusercontent.com/11850778/114721591-5cc45700-9d39-11eb-956e-591d26e90ca9.png)

**Comment by reckart** [comment]
You should be able to configure the sidebar width in the preferences dialog. It applies to both sidebars though.

**Comment by habernal** [comment]
Unfortunately not (neither Firefox 87.0; nor Chromium 89.0.4389.114)

**Comment by reckart** [comment]
Does this option not appear for you?

<img width="514" alt="Screenshot 2021-04-18 at 10 43 03" src="https://user-images.githubusercontent.com/1410238/115139582-f12d0300-a032-11eb-957d-7c1d5382c88a.png">

**Comment by reckart** [comment]
Never mind - setting is not effective due to a bug. Will be covered by #2203.
