### ISSUE TITLE
UX / Curation / Bad UX with multiple annotators

### ISSUE THREAD

**Issue by habernal** [inception-project/inception#2195]
**Describe the bug**
Too much unused white space BUT one has to scroll through annotators in the bottom. See screenshot.

It tried to hack the CSS but failed (some "flix" blocks or similar, no idea).

**Expected behavior**
No empty space in the middle

**Screenshots**
![screenshot_2021-04-14_15-56-13](https://user-images.githubusercontent.com/11850778/114722981-8fbb1a80-9d3a-11eb-8071-f8a6ac474d62.png)

**Comment by habernal** [comment]
Wow, that's fast! When is 0.19.3 out? :)

**Comment by jcklie** [comment]
I just marked it to fix for the next bugfix release, we do not know whether we will solve it until then and when that release will be.

**Comment by reckart** [comment]
Added a draggable splitter between the upper and the lower part. Splitter resets its position when the page is re-loaded.

**Comment by habernal** [comment]
> Added a draggable splitter between the upper and the lower part. Splitter resets its position when the page is re-loaded.

Sounds good, no need to be fancy here. Thanks!
