### ISSUE TITLE
How does Active Learning work?

### ISSUE THREAD

**Issue by david-waterworth** [inception-project/inception#2197]
I've been experimenting with the Active Learnig feature today, there's a few things that are unclear

First - what is it actually training? I've set up a single `[Named entity@value] Multi-Token Sequence Classifier (OpenNLP NER)` recomender - I'm assuming it's training that?

Second - it seems to be cycling through a very small number of document, may only 3-5 even though I have ~150 documents in my project. It seems to be the "current" document and maybe the previous and next? 

Third - it seems to cycle the same sentences over and over, it's very rare that it suggest an un-annotated sentence. I assume since there's no way of marking each sentence as finished the uncertainty sampling algorithm simply considered all sentances?

**Comment by reckart** [comment]
Active learning requires a classifier that actually generates multiple alternative predictions. This is the case e.g. for the POS recommender or the dictionary recommender. However, the OpenNLP sequence classification recommender is not able to generate alternative predictions.

In principle, active learning should cycle through all documents. It could be that we have a bug in the code though. At some point, we started only fetching predictions for the current document and caching those. Active learning then operates on this cache. However, if active learning is turned on, we should not only fetch predictions for the current document but for all documents. This might not happen and this could be the bug.

There are bugs in the AL code currently that jumping doesn't really work well :( We need to look into them...

* AL does not always jump to the text passage #1182
* AL repeats suggestions #1183

**Comment by david-waterworth** [comment]
Thanks, I encountered both the bugs you've reported. I'll comment in the issues.

The first time I started Active Learning it seemed to cycle through only the last few documents, when I restarted it seemed to cycle through a more random selection. I guess though if the selective sampling isn't working (i.e. if I'm using OpenNLP) then that could explain some of the issues.

Am I correct in assuming that although I could implement an external recommender for active learning, I won't be able to modify the selective sampling?

**Comment by reckart** [comment]
Sorry for not having answered to this earlier. 

An external recommender cannot directly change the active learning strategy at this point. It can only provide scores for the uncertainty-sampling-based strategy. In order to implement a different strategy, it would be necessary to implement the `ActiveLearningStrategy` interface in Java and after that to actually make the strategy selectable via the UI.

**Comment by reckart** [comment]
Assuming the that issue was resolved as there was no more feedback and thus closing the issue.
