### ISSUE TITLE
Export-download query-reports 

### ISSUE THREAD

**Issue by Juanaloga** [inception-project/inception#2198]
**Is your feature request related to a problem? Please describe.**

There is no way to export-download queries. Not quantity, just examples. For instance, if I annotate nouns from a greek documment I query about them but I cant download that information. 

**Describe the solution you'd like**
A way to extract querys in csv or spreadsheets.

Thanks! :)

**Comment by reckart** [comment]
Is it correct that you refer to search results in the search sidebar of the annotation page that you would like to export?

**Comment by Juanaloga** [comment]
Yes, it is correct! Export search results to work with them out of the software: visualize, compare, etc. Thanks! ;)
