### ISSUE TITLE
PropertyListPanel is not scrollable when a local KB is selected

### ISSUE THREAD

**Issue by MdeBoer95** [inception-project/inception#220]
When a local knowledge base is selected in the KB UI, it is not possible to scroll the panel that contains the properties. I tried this with [Wine ontology](https://git.ukp.informatik.tu-darmstadt.de/inception/inception-application/uploads/6f095044b24d06fe6f204f3a2779a9ae/wine.rdf) and [small knowledge base with pets](https://git.ukp.informatik.tu-darmstadt.de/inception/inception-application/uploads/4150ca80e29e788a668d784d8d3e81b7/pets.ttl).
For remote KBs it works fine. 
@naveen2507 can you confirm this?

**Comment by naveen2507** [comment]
![image](https://user-images.githubusercontent.com/10420950/40188275-e3bd3154-59f9-11e8-925b-fc627560a276.png)

@MdeBoer95 works fine for me. I am not able to replicate this issue. I tried with the same - Wine ontology.

@reckart @Rentier  can you please check this on your side, if you can replicate the issue?

**Comment by MdeBoer95** [comment]
I tried it again with Chromium instead of Firefox. Now it works. Guess I can close this issue.
@naveen2507 What browser did you use?
