### ISSUE TITLE
Remove wrongly generated annotation 

### ISSUE THREAD

**Issue by ofersabo** [inception-project/inception#2200]
We have a project with a single annotator which annotated a bunch of documents. 
In this project, we also have a user who by mistake has curator permissions.
The curator mistakenly opened a document in curation mode without annotating the document.

Since we assume that in this project we shouldn't have curated documents, we'd like to restore the state of the curation document into the "New" state. 

**Describe the solution you'd like**
Restore the "New" state from the monitoring page or from API.

**Describe alternatives you've considered**
Another alternative is to cancel all the curation documents for a given project.

**Comment by reckart** [comment]
Try right-clicking on the  curation cell of the document you want to reset.

![2021-04-18_09-52-56](https://user-images.githubusercontent.com/1410238/115138356-efac0c80-a02b-11eb-9cd7-ee1221d7c94e.png)

**Comment by reckart** [comment]
No further response, so I assume the issue is resolved.
