### ISSUE TITLE
UX/UI: Collapsing left toolbar has low usability

### ISSUE THREAD

**Issue by habernal** [inception-project/inception#2210]
**Describe the bug**

In the project setup page, the menu on the left is collapsed to icons and unrolls on mouse over. This feature seems to have no added value, as the rest of the page provides enough space even for complex setup (see screenshot).

It makes it less easy to use effectively ( see https://en.wikipedia.org/wiki/Fitts%27s_law )

**Expected behavior**

No menu collapsing

**Screenshots**
![screenshot_2021-04-19_09-17-56](https://user-images.githubusercontent.com/11850778/115197196-02d4e000-a0f1-11eb-9598-ebf5a3270399.png)

**Comment by reckart** [comment]
Well, it kind of depends on the screen size and which settings page is open.

**Comment by habernal** [comment]
That's right. What is the worst case then? (In one of the previous version it looked diferently, it wasn't that bad, but maybe there was a reason to change it)

**Comment by reckart** [comment]
I mean: of course you are right. I was happy to have the new menus and they don't do a lot of what I would have liked them to do which include in particular:

- ability to pin the collapse/expand state
- remember the collapse/expand state across sessions (e.g. in a cookie or via a server-side user-specific preference)
- animated expansion/collapse

Maybe I was just so happy to have the collapse working that I felt the need to showcase it ;) Hard-changing it to "always visible" is a one-liner.... but hey, it's so nice!

**Comment by habernal** [comment]
I get your point. Happy to see it working. Yet when you have to manage several projects over months, you want to be as effective as possible. And this feature is then just annoying and slowing down, I'm sorry.

**Comment by reckart** [comment]
I did not understand your pointer to the wiki article on mouse movement. 

You move the mouse to an icon on the sidebar and click on the icon. The sidebar does expand to show the text but there is no need to move the mouse to the text, is there? Just click on the icon which is visible all the time and never changes position.

**Comment by habernal** [comment]
It says rougly "the bigger the target the better". Yes, borders play a special role (they "catch" the mouse). But cognitively and intuitively, one wants to click on the icons, not on the screen border, so you move to the icon. I mean, it's a detail. If you say "I want it this way", I'm fine :)

**Comment by reckart** [comment]
Fixed by https://github.com/inception-project/inception/pull/2215 which introduces a way to pin the sidebars so the do not collapse / expand. Default setting is for them to be pinned (i.e. permanently expanded). Setting is stored per user.
