### ISSUE TITLE
Websocket integration for the experimental annotation API

### ISSUE THREAD

**Issue by christophscheunemann** [inception-project/inception#2211]
**Websocket for the experimental annotation API**
* Websocket is a required feature for the experimental annotation API and needs to be implemented

**Comment by reckart** [comment]
We already have general websocket support enabled at the level of Tomcat and Spring. What do you want to do specifically?

**Comment by reckart** [comment]
At least I believe we have it enabled. If not, it should be enabled on this PR: https://github.com/inception-project/inception/pull/2051
