### ISSUE TITLE
Multi-Token Sequence Classifier (OpenNLP NER) matches an additional token

### ISSUE THREAD

**Issue by david-waterworth** [inception-project/inception#2216]
**Describe the bug**
`OpenNLP NER` seems to match one character extra at the end of each span. For example when I run both `OpenNLP NER` and `String Matcher` at the same time, on text like `L01_FCU-1-01_CHW_Vlv` the string matcher displays recommendations for `L01_FCU-1-01` and the OpenNLP displays `L01_FCU-1-01_`

I understand the `OpenNLP` could have somehow learnt that the trailing underscore is part of the text, but it seems to consistently always contain the following token, even if it's not `_` so it's possible the end offset is being interpreted incorrectly somewhere (i.e. should be endoffset-1 not endoffset)?

In the example below the lowest span is from the string matcher and the 2nd lowest is from OpenNLP NER

![image](https://user-images.githubusercontent.com/5028974/115499430-c7820f00-a2b2-11eb-9582-06e0446b0846.png)

**Comment by reckart** [comment]
I have also already observed this, but I have no idea what (if anything) we are doing wrong. Consider the following example:

```
Amid the developing Cold War with the Soviet Union, he publicly warned of an "iron curtain" of Soviet influence in Europe and promoted European unity.
```

The classifier predicts: `prediction => [7..10) MISC`

Looking more closely: 

```
tokenAnnotations.get(prediction.getStart()).getCoveredText() => Soviet
tokenAnnotations.get(prediction.getEnd() - 1).getCoveredText() => ,
```

Any ideas anybody?

**Comment by reckart** [comment]
Maybe the training is the problem

**Comment by reckart** [comment]
Seems to be a bug in training

**Comment by reckart** [comment]
@david-waterworth thanks for raising this one. It happens since a long time but continually fell of my radar... anyway, fixed now :)

**Comment by david-waterworth** [comment]
Good news, thanks! Is there a nightly build I can try tomorrow?

**Comment by reckart** [comment]
There is an immediate build that you can look at. Be sure to check the revision / commit message against the git history to ensure that the build already includes the change you are looking for:

https://zoidberg.ukp.informatik.tu-darmstadt.de/jenkins/job/INCEpTION%20(GitHub)%20(0.19.x)/lastBuild/

**Comment by david-waterworth** [comment]
Thanks!
