### ISSUE TITLE
Krippendorff's Alpha Agreement = 1.0 (Unitization)  although documents differ completely.

### ISSUE THREAD

**Issue by t-steu** [inception-project/inception#2219]
Hi,

First of all, thanks for the cool Inception project. This helps me with my research!

However, there is a behaviour in the Agreement calculation (Krippendorff Unitization) that I can not explain / is a bug IMHO.

I get a Krippendorff's Alpha of 1.0 although the documents differ completely.

**To reproduce**

- Let's assume we have two users (A and B) and 2 documents (1,2).

- Document 1 says "Foo bar".

- Document 2 says "The test".

- User A only closes document 1 and marks "Foo" (with a feature on a custom layer).

- User B only closes document 2 and marks "The" (with the same feature on the custom layer).

Then calculate Krippendorff's alpha (unitizing) with the completed documents ("Limit to completed documents").
I now get a Krippendorff Alpha of 1.0 although the comparison documents are different.

I would have **expected** that no comparison is made at all (since A and B have no common closed documents) or that at least a Krippendorff's Alpha of 0 as result.

Is suspect this to be a bug or is there something wrong with my reasoning (then I would expect the documentation to elaborate on this issue in more detail)?

Attached also a small project to follow. 

Best regards also from TUDa,

Tim

**Version:**
Inception version 0.19.2 build dae6182b
Linux (Ubuntu 18.04 OpenJDK)
Firefox 87.0 (64-Bit)

**Sample Project**

[Krippendorff+Unitizing+Test_project_2021-04-22_1241.zip](https://github.com/inception-project/inception/files/6357682/Krippendorff%2BUnitizing%2BTest_project_2021-04-22_1241.zip)

**Comment by reckart** [comment]
Thanks for the report :)
