### ISSUE TITLE
UI: "Cancel" in curation modal does not return to project dashboard

### ISSUE THREAD

**Issue by habernal** [inception-project/inception#2229]
**Describe the bug**
Open a project. Click on Curation (you have to be curator) to open a list of documents to choose from. Click on cancel. The view returns to the list of all projects.

**Expected behavior**
Canceling the modal should go back to the previous state, that is the project main dashboard.

 - Version and build ID: 0.19.3 (2021-04-25 09:58:11, build 238b0e91)

**Comment by reckart** [comment]
Affects the annotation page as well.
