### ISSUE TITLE
how to set up constraints on a relation and specify to show only values when the 2 involved entity tags are of a certain type?

### ISSUE THREAD

**Issue by jwijffels** [inception-project/inception#2236]
I've created a span which I called '`main`' which has possible tag values: `'2. TIJD', '3. GEO/PLAATS', '4. PERSOON', '7. OBJECT'`
Next I created a relation type with as `String` feature: '`link`' allowing to make relations among these `main `entity tags.

Now I would like to only be able when someone makes a link 
- between 2 '4. PERSOON' objects to show only possible values 'Family', 'Friends', 'Work'
- between a '4. PERSOON' object and a '3. GEO/PLAATS' object to show only possible values 'Work', 'Birthplace', 'Residency'
How do you do this, I tried to use the following constraints but this did not work

```
import webanno.custom.Entiteiten as Entiteiten;
import webanno.custom.PersoonsRelatie as PersoonsRelatie ;

PersoonsRelatie {
  @Entiteiten.main ="4. PERSOON" -> link="Friends" | link="Family" |  link="Work";
}

```
I've set the flag 'Hide when no constraints apply' to make sure the above constraint was applied but that did not give the desired effect of only showing values 'Friend', 'Family' or 'Work' in case the main entity was '4. PERSOON'
![Knipsel](https://user-images.githubusercontent.com/1710810/116251695-335eee80-a76f-11eb-968b-7c8a587abffd.PNG)

In BRAT you can set up relationship constraints as follows (using Arg1 and Arg2), how does one do that in Inception.

```
[relations]	
<OVERLAP> 	Arg1:<ENTITY>, Arg2:<ENTITY>, <OVL-TYPE>:<ANY>
#relaties
arbeidsrelatie     Arg1:PERSOON, Arg2:PERSOON
familierelatie     Arg1:PERSOON, Arg2:PERSOON
vrienschapsrelatie Arg1:PERSOON, Arg2:PERSOON
burenrelatie       Arg1:PERSOON, Arg2:PERSOON
andere-relatie     Arg1:PERSOON, Arg2:PERSOON
geen-relatie       Arg1:PERSOON, Arg2:PERSOON
is-dezelfde-persoon Arg1:PERSOON, Arg2:PERSOON
#persoonsattributen
leeftijd_wie	            Arg1:PERSOON-LEEFTIJD,     Arg2:PERSOON
leeftijd_wie	            Arg1:PERSOON,              Arg2:PERSOON-LEEFTIJD
beroep_wie	              Arg1:PERSOON-BEROEP,       Arg2:PERSOON
beroep_wie	              Arg1:PERSOON,              Arg2:PERSOON-BEROEP
persoonsbeschrijving_wie	Arg1:PERSOON-BESCHRIJVING, Arg2:PERSOON
persoonsbeschrijving_wie	Arg1:PERSOON,              Arg2:PERSOON-BESCHRIJVING
```

**Comment by reckart** [comment]
It should work along the lines of

```
import webanno.custom.Entiteiten as Entiteiten;
import webanno.custom.PersoonsRelatie as PersoonsRelatie ;

PersoonsRelatie {
  Governor.main = "4. PERSOON" & Governor.main = "4. PERSOON" -> link="Friends" | link="Family" |  link="Work";
  Governor.main = "4. PERSOON" & Governor.main = "3. GEO/PLAATS" -> link="Work" | link="Birthplace" |  link="Residency";
}
```

That assumes that the `Entiteiten` actually has a string feature named `main`.

Note that the constraints presently only re-order the tags - they do not completely disable the task. The "hide when no constraints apply" can be used to show certain **features** only if constraints match, but once the feature is offered, all the tags are offered (but the tags matched by the constraints appear first in the dropdown).

**Comment by jwijffels** [comment]
Thank you for the feedback! Using Governor and Dependent was indeed the solution.

**Comment by evertorres** [comment]
This only work with String Features or can I use with a Knowledge Base?

I tried to incorporate some constraints but nothing happened:

`
import webanno.custom.CONCEPTS as CONCEPTS;
import webanno.custom.Relation as Relation;

Relation {
  Governor.OMOP = "Negation"  -> Label = "HAS_NEGATION";
}
`

All have the Type KB

Thanks!

**Comment by jwijffels** [comment]
Not sure, only tested on string features in my case. I'd be interested in the omop setup as well

**Comment by reckart** [comment]
Currently the constraints functionality only activates on string features with a tagset. 

Here are other currently open issues related to constraints:

https://github.com/inception-project/inception/issues?q=is%3Aissue%20state%3Aopen%20label%3A%22Module%3A%20Constraints%22

Feel free to open another one for KB support. Don't know when I might get to that though.
