### ISSUE TITLE
inception export problem

### ISSUE THREAD

**Issue by whisere** [inception-project/inception#2239]
**Describe the bug**
can only export grey annotation after clicking it to turn it green

**To Reproduce**
1. use AdapterSentenceClassifier in https://github.com/inception-project/inception-external-recommender to annotate sentence sentiment automatically,
2. The annotations are  added in the document with grey color
3. following the answer in this link https://stackoverflow.com/questions/64704561/exporting-text-sequences-with-labels-from-inception-annotation-engine
to export UIMA CAS XMI (XML 1.0) for sentiment analysis
4. none of the grey annotations are exported, only the one turned green by clicking the annotation one by one.

**Expected behavior**
Is there way to export grey annotation (automatically annotated with recommender) without clicking them one by one to turn them green?

**Screenshots**
![Screen Shot 2021-04-28 at 4 20 33 pm](https://user-images.githubusercontent.com/2360494/116355891-d8e09380-a83d-11eb-9185-c17d8b6e875e.png)

**Please complete the following information:**
 - Version and build ID: INCEpTION -- 0.19.2 (2021-04-07 18:54:13, build dae6182b)
 - Browser: chrome

**Comment by reckart** [comment]
You could open the recommender sidebar and "accept all/best" annotations from your recommender and then export. It turns all suggestions to green at once. This currently needs to be done for each document in the project separately.

**Comment by whisere** [comment]
Thank you very much! That works perfectly!!
