### ISSUE TITLE
height of drop-down box

### ISSUE THREAD

**Issue by jwijffels** [inception-project/inception#2240]
**Is your feature request related to a problem? Please describe.**
I have a named entity recognition setup which has 13 possible entities. It would be nice if I can see these all immediately in 1 time instead of scrolling.

**Describe the solution you'd like**
Allow for a configurable size (height) of the drop-down box

**Describe alternatives you've considered**
None

**Additional context**
![msg](https://user-images.githubusercontent.com/1710810/116423408-f2370f00-a840-11eb-91ff-9b61f9fde564.png)

**Comment by reckart** [comment]
How would you like something like this instead?

<img width="1042" alt="Screenshot 2021-05-01 at 10 09 23" src="https://user-images.githubusercontent.com/1410238/116776525-21c86000-aa69-11eb-941d-e20626252ab3.png">

**Comment by jwijffels** [comment]
Radio buttons are indeed even better

**Comment by reckart** [comment]
Incoming: https://github.com/inception-project/inception/pull/2244

**Comment by reckart** [comment]
Marking as won't fix since it is super-seded by https://github.com/inception-project/inception/issues/2243.

**Comment by jwijffels** [comment]
Many thanks!

**Comment by reckart** [comment]
Meanwhile, you can do the following:

- assign key-bindings to each of your tags in the feature settings
- on the annotation page click "show key bindings" below the feature input field

This will show you the keys you can use to assign your label as well as provide clickable labels.

Also, you may want to consider turning on the "remember" option on your feature.
