### ISSUE TITLE
Finished annotations shown as ANNOTATION INPROGRESS in curation open dialog

### ISSUE THREAD

**Issue by habernal** [inception-project/inception#2241]
**Describe the bug**
See these two screenshots from the same project

![screenshot_2021-04-28_21-24-34](https://user-images.githubusercontent.com/11850778/116461724-e3fce900-a868-11eb-99cd-eadc947eaebb.png)

![screenshot_2021-04-28_21-25-43](https://user-images.githubusercontent.com/11850778/116461754-ec552400-a868-11eb-9c9d-270df90af1d4.png)

**Please complete the following information:**
 - Version and build ID: 0.19.3 (2021-04-25 09:58:11, build 238b0e91)

**Comment by reckart** [comment]
I'm pretty sure that #2144 fixed this one already for the upcoming 0.20.0 release.

**Comment by reckart** [comment]
Hm, ok now I see the actual issue. The matrix view displays the documents as finished but the open dialog does  not.

**Comment by reckart** [comment]
Ok, the issue sis that what you see here in parentheses in the open document dialog is the `SourceDocumentState` (leftmost column before the document name in the matrix view). The fact that these two are out of sync is addressed by #2144.

However, you probably expect to see the `AnnotationDocumentState` for the current user in the open document dialog instead.

**Comment by reckart** [comment]
This happens in 0.19.x because the monitoring page calculates the document status internally and this is de-coupled from the actual document state stored in the database.

The problem doesn't turn up anymore in 0.20.0-SNAPSHOT as the code for handling document and project state has seen some major upgrades.
