### ISSUE TITLE
Running INCEpTION for the first time 

### ISSUE THREAD

**Issue by Andi-GitHub** [inception-project/inception#2253]
Hello,
When running INCEpTION for the first time after downloading it, there are some issues as per below which I wanted to share:
1-First we see a pop-up on the screen that shows that “Application is loading” and after a while it disappears. Then it takes longer than normal for the dialog box to appear in a way that meanwhile you even doubt whether the application is running at all.
2-The “Application is loading” pop-up can not be moved, so files and what is behind it on the desktop cannot be seen and reached out.
3-I am using Windows10 on my laptop and when INCEpTION is running, I do not see the icon on the task bar. So, there is no way for me to figure it out whether the application is still running or not. Also, there are no instructions on how to stop the program from the terminal 
Thanks.
Andi

**Comment by jcklie** [comment]
@Andi-GitHub  Can you download https://zoidberg.ukp.informatik.tu-darmstadt.de/jenkins/job/INCEpTION%20(GitHub)%20(PR%20builder)%20-%20Docker/597/artifact/git/inception/inception-app-webapp/target/inception-app-webapp-0.20.0-SNAPSHOT-standalone.jar and run this jar and tell us whether it solves your problems?

**Comment by Andi-GitHub** [comment]
@jcklie Yes, I tried it and the issues are solved now. Thank you!

**Comment by reckart** [comment]
Seems to work good on OS X. There is just one problem with Safari (maybe other browsers) which may be locked to https for localhost and then the "open in browser" button does not work. It is a pretty annoying habit of Safari in particular.

**Comment by jcklie** [comment]
What does "does not work" mean? Does it not open the browser?

**Comment by reckart** [comment]
Well, we run on `http://...` but after opening a website using `https://...`, Safari thinks it is safer to always open the url using HTTPS. That means when you open `http://localhost:8080`, it automatically switches to `https://localhost:8080` and then the request obviously fails because we don't do HTTPS.

https://stackoverflow.com/questions/46394682/safari-keeps-forcing-https-on-localhost

**Comment by reckart** [comment]
It's annoying - I don't think we can do much about it really...

**Comment by reckart** [comment]
Very cool!

<img width="188" alt="Screenshot 2021-05-03 at 21 00 16" src="https://user-images.githubusercontent.com/1410238/116920526-07ea7100-ac53-11eb-9cb2-257473faea3a.png">

**Comment by Andi-GitHub** [comment]
@jcklie Hi. I wanted to point out that since last night the pop-up (splash screen) shows the application is loading and the dialog box has not appeared. I have tried it several times, but no progress.

**Comment by reckart** [comment]
Do you have any option of stopping the program at this point?

**Comment by Andi-GitHub** [comment]
@reckart Yes simply via the icon on the task bar.

**Comment by reckart** [comment]
For anybody finding this in the future: the application did get stuck at the splash screen because it was started multiple times. After opening the task manager and stopping all Java/INCEpTION processes, it was possible to start it up normally.
