### ISSUE TITLE
Connect INCEpTION to MariaDB : error when starting container

### ISSUE THREAD

**Issue by pottieral** [inception-project/inception#2255]
Hi, 
Sorry to bother again. Using the documentation, I tried adding a MariaDB connection to store inception data as advised. However, then INCEpTION sadly fails to start. I run INCEpTION inside a container. Inception was working fine before I tried plugging in the MariaDB storage.

Here is the container log error that seems relevant:

`java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=localhost)(port=3306)(type=master) : Socket fail to connect to host:localhost, port:3306. Connection refused (Connection refused)`

Here is my settings.properties file:
```
database.url=jdbc:mariadb://localhost:3306/inception?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
database.username=inception
database.password=t0t4llYSecreT
spring.datasource.hikari.connectionInitSql=SET NAMES utf8mb4 COLLATE utf8mb4_bin;

# 60 * 60 * 24 * 30 = 30 days
backup.keep.time=2592000

# 60 * 5 = 5 minutes
backup.interval=300

backup.keep.number=10
```

MariaDB seems to be working fine (as far as I am able to discern) with commands like `mysql -u inception -h localhost -P 3306 -p inception` then password connecting to the db.

I also modified as advised mariaDB properties, checking that these are verified:
```
SHOW VARIABLES WHERE Variable_name LIKE 'character\_set\_%' OR Variable_name LIKE 'collation%';
+--------------------------+-------------+
| Variable_name            | Value       |
+--------------------------+-------------+
| character_set_client     | utf8mb4     |
| character_set_connection | utf8mb4     |
| character_set_database   | utf8mb4     |
| character_set_filesystem | binary      |
| character_set_results    | utf8mb4     |
| character_set_server     | utf8mb4     |
| character_set_system     | utf8        |
| collation_connection     | utf8mb4_bin |
| collation_database       | utf8mb4_bin |
| collation_server         | utf8mb4_bin |
+--------------------------+-------------+
```

 - Version and build ID: inception:0.19.3
 - OS: CentOS Linux release 7.9.2009 (Core)
 - MySQL version: mysql  Ver 15.1 Distrib 5.5.68-MariaDB, for Linux (x86_64) using readline 5.1

It seems the app tries to load the embedded db with the mariaDB info provided? Maybe there is a problem with the way I structured my settings.properties file (or my mariaDB!). Thanks in advance for any tips you might provide.

edit: added full error log as attached file
edit 2: changed a few things after new tests, updated issue with latest error logs
[full_error_log.txt](https://github.com/inception-project/inception/files/6415275/full_error_log.txt)

**Comment by pottieral** [comment]
OK, I succeeded getting further changing localhost to "172.17.0.1" in the settings.properties file, and creating relevant user/passwords in the mariaDB database. If I understand it correctly, it seems to have something to do with the way docker interacts with the "outside world" ie could not connect to the host database. Sadly it is still not working as now I am faced with some other error :
```
ChangeSet - Change Set de/tudarmstadt/ukp/clarin/webanno/security/model/db-changelog.xml::1512223050574-4.4::WebAnno Team failed.  Error: (conn=17) Index column size too large. The maximum column size is 767 bytes. [Failed SQL: (1709) CREATE INDEX FKhjuy9y4fd8v5m3klig05ktofg ON inception.authorities(username)]
2021-05-03 15:03:26 WARN [SYSTEM] AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.MigrationFailedException: Migration failed for change set de/tudarmstadt/ukp/clarin/webanno/security/model/db-changelog.xml::1512223050574-4.4::WebAnno Team:
     Reason: liquibase.exception.DatabaseException: (conn=17) Index column size too large. The maximum column size is 767 bytes. [Failed SQL: (1709) CREATE INDEX FKhjuy9y4fd8v5m3klig05ktofg ON inception.authorities(username)]
```

**Comment by jcklie** [comment]
This error means that your database created tables with the wrong format. 

`SET GLOBAL innodb_default_row_format='dynamic';`

See https://mariadb.com/kb/en/innodb-row-formats-overview/

What version of mariadb are you using? Mariadb 5.* is quite old, you should use 10.5 or so if possible.

**Comment by pottieral** [comment]
Hi, with 10.5.9-MariaDB, INCEpTION launches again! Here is a ref for updating past 5.5 on CentOS 7: https://mariadb.com/docs/deploy/upgrade-community-server-cs105-centos7/ 
Sorry for the spam, I hope documenting my trials and errors will be able to help someone. Key issue was : docker install of INCEpTION + localhost install of MariaDB = some tweaks required for good communication. This is some sort of classical newbie docker pitfall I think.

**Comment by jcklie** [comment]
Ah, I thought that you had mariadb in docker and inception on metal, not the other way round. We also have a docker compose in the admin guide so that you can use a complete docker setup.
