### ISSUE TITLE
Add list of used libraries with licenses

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#2256]
**Is your feature request related to a problem? Please describe.**
We use 3rd-party things and need to list them somewhere to adhere to the licensing terms.

**Describe the solution you'd like**
Generate report via http://maven.apache.org/plugins/maven-project-info-reports-plugin/licenses-mojo.html and link it 
* on the INCEpTION website 
* about of INCEpTION standalone launcher
* INCEpTION itself reachable from admin settings or so

**Describe alternatives you've considered**
Infringe peoples' copyright and get sued.

**Comment by reckart** [comment]
We actually have a list of the dependencies in `META-INF/DEPENDENCIES`.
