### ISSUE TITLE
Creating new project and then clicking on dashboard displays error

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#2257]
**Describe the bug**
Creating new project and then clicking on dashboard displays error: admin: Project [-1] does not exist

**To Reproduce**
1. Create new project
2. Click on 'Dashboard'
3. See error in INCEpTION and log: admin: Project [-1] does not exist

**Expected behavior**
I go to the dashboard of the project I just created.

**Please complete the following information:**
 - Version and build ID: master
 - OS: Windows
 - Browser: chrome

**Comment by reckart** [comment]
I don't see a "Dashboard" link. Are you sure you're on the latest master?

**Comment by reckart** [comment]
When a new project is created, the ID should be `null` and not `-1`. I cannot locally reproduce the scenario where the ID ends up being `-1 `. For me it is `null` and then the dashboard link is not displayed.

**Comment by jcklie** [comment]
https://gyazo.com/29578f266eb9942587bc5127a1cae06e

```
D:\git\inception>git rev-parse HEAD
550db66ce4c806f7fb1f10192d29f9fed9fc20c4

```
