### ISSUE TITLE
Remove not remembering layer

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#2258]
**Is your feature request related to a problem? Please describe.**
Using !remember layer is painful, so why not remove it.

**Describe the solution you'd like**
- [x] Hide "remember layer" option behind a feature flag (merged for 0.20.0)
- [x] Remove !remember layer code
- [x] Remove documentation related to being able to turn of the "remember layer" feature

**Comment by reckart** [comment]
Before finally removing it, we should hide it behind a feature flag for a while - adding it back would be really annoying.
