### ISSUE TITLE
Create log file in .inception folder by default

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#2260]
**Is your feature request related to a problem? Please describe.**
We write logs only to the console which is not good in case of error and users not turning logging on until after bad things have happened.

**Describe the solution you'd like**
- Create log file in .inception folder by default with log rotation
- Show logs via tray icon

**Comment by reckart** [comment]
We need to reliably get the information which folder is the `inception.home` (even if it is unset) into the logging configuration before starting up any other part of the application that would actually make use of logging.

**Comment by jcklie** [comment]
Can we just create the log handler in code and add a property to not create it?

**Comment by reckart** [comment]
I wouldn't want to lose the ability to configure the logging through an external log file.

**Comment by jcklie** [comment]
You can, but you would have both I hoped.
