### ISSUE TITLE
imported Webanno_tsv_3.2 is not as same as the original annotation

### ISSUE THREAD

**Issue by sunurdy** [inception-project/inception#2267]
**Describe the bug**
Exporting the webanno-tsv_3.2 format file after the plain text annotation.
Then import the exported tsv. It is not the same annotation as the original text.
example is on https://morbo.ukp.informatik.tu-darmstadt.de/p/1060/annotate?32

**To Reproduce**
1. Go to  Settings and add a custom layer (Relation),  add some values and attach the layer to the Name entity Layer, 
2. Import a plain text, "test.txt"
3. Annote the text shown on "https://morbo.ukp.informatik.tu-darmstadt.de/p/1060/annotate?34#!d=4535&f=1"
4. Click on the button Export the document
5. rename the exported test.tsv to test1.tsv
6. Back to settings and import test1.tsv, on https://morbo.ukp.informatik.tu-darmstadt.de/p/1060/settings/documents?37
7. open the imported test1.tsv

the exported tsv add some extra wrong annotations
![error](https://user-images.githubusercontent.com/6326342/117432864-68ccbe80-af5d-11eb-87b2-2d3a95f108e2.jpg)

**Expected behavior**
The annotation in test1.tsv is the same as the annotation in test.txt

**Screenshots**
![origin](https://user-images.githubusercontent.com/6326342/117432501-083d8180-af5d-11eb-976c-b10b7323a124.jpg)
![imported](https://user-images.githubusercontent.com/6326342/117432507-096eae80-af5d-11eb-8496-35f84746df9e.jpg)

**Please complete the following information:**
 - Version and build ID: 0.19.3
 - OS:  Windows
 - Browser: chrome

**Comment by reckart** [comment]
Sorry, superficial read - I first understood you had changed the TSV between export and import. Need to investigate.

**Comment by sunurdy** [comment]
> Sorry, superficial read - I first understood you had changed the TSV between export and import. Need to investigate.

Thanks for reply. 
There's no change except renaming the exported TSV filename on above.
And I export test.txt anno as test.tsv,  then import it directly. It's also different from the original annotation.
It seems not working as I expected.

**Comment by reckart** [comment]
Thanks for reporting! Was indeed a bug.
