### ISSUE TITLE
Create example project for AL + recommendation

### ISSUE THREAD

**Issue by matchlesswei** [inception-project/inception#227]
Create example project for AL + recommendation:
- use a layer like 'POS'
- add recommender: StringMatchingClassifier
- add recommender: OpenNlpClassifier

**Comment by matchlesswei** [comment]
@reckart where should I put the example project?

**Comment by reckart** [comment]
@matchlesswei I have added the project to the website (https://github.com/inception-project/inception-project.github.io) under "Examples".

I think it would be good to add a bit more explanation to the project, e.g.:

* what should the user look at / try out after importing the project?
* add a screenshot of the annotation screen

**Comment by reckart** [comment]
@matchlesswei you can open a PR in the website repo (https://github.com/inception-project/inception-project.github.io) for updates to the example page.
