### ISSUE TITLE
Improve performance time of Active Learning functionality

### ISSUE THREAD

**Issue by matchlesswei** [inception-project/inception#228]
@rcffc wrote in https://git.ukp.informatik.tu-darmstadt.de/inception/inception-application/issues/338:

I tested Active Learning on the POS layer with OpenNlpPosClassifier and StringMatchingPosClassifier. 
On my machine (0.2.x), it takes 30s-40s until I can click the next button.
I also tried with the same documents on blinky-experimental (0.3.0), it takes 5s-7s.
The project is attached below.

[A+Recommendation+playground+_28POS_29_2018-03-18_0058.zip](https://github.com/inception-project/inception/files/2020226/A.Recommendation.playground._28POS_29_2018-03-18_0058.zip)

- improve the implementation of the active learning strategy for selecting the recommendation

- [x] log the duration time caused by actions in active learning sidebar

**Comment by reckart** [comment]
I think this may be related to serialization problems in the AL sidebar. Not sure if these are already fixed in your copy. Does your copy include the changes for #38?

**Comment by matchlesswei** [comment]
On my machine(0.3.1), it takes less than 5s until I can click the next button, if I clicked "accept", less than 2s if I clicked "reject"/"skip".
@rcffc could you check whether this problem still exists on your machine. If it is outdated, maybe we can close this issue.

**Comment by reckart** [comment]
It is still pretty long though :) We should try getting down to 500ms or less.

**Comment by matchlesswei** [comment]
For asking for recommendations and calculating everytime a user presses annotate/reject/accept, time costs are as follows:

<img width="746" alt="screen shot 2018-07-09 at 14 45 28" src="https://user-images.githubusercontent.com/23156705/42451206-d56e2a34-8386-11e8-8823-f31bc91b438f.png">

**Comment by matchlesswei** [comment]
The result of analyzing the time cost of geting and calculating the next recommendation is as follows:

Getting recommendations from recommender system costs | 536ms
Removing recommendations with Null Annotation | 0ms
Removing duplicate recommendations | 1ms
Removing rejected and skipped recommendations | 8ms
Spliting the list to per token per classifier | 2ms
Ranking | 1ms

So it makes sense to maintain a list in the `ActiveLearningRecommender`.

**Comment by reckart** [comment]
And idea why "set annotation and write learning record" takes 6,5 secs? Is it a very large document you test with here?

**Comment by matchlesswei** [comment]
If we keep the list of recommendations in the `ActiveLearningRecommender`, we need to filter the skipped and rejected suggestions **before** ranking. Because:
Suppose token X in Classifier Y has suggestions A(0.96), B(0.95) and C(0.92). According to my ranking implementation, I just calculate the difference between A and B, the difference between B and C, _not the difference between A and C_. If B is a skipped one, if we filter the skipped ones after ranking, we cannot get the difference between A and C.

Since ranking costs not much time, I suggest that we do filtering and ranking every time a user presses a button, and we filter invisible ones also before ranking.

WDYT @reckart ?

**Comment by reckart** [comment]
Could you please import the GUM corpus (CoNLL10 or CoNLL-U format) for testing? It contains POS tags and quite a number of documents. Then you can import some additional plain text document and try to use active-learning to add the POS tags to the new plain text document. Could you provide the performance measures for this setup?

**Comment by matchlesswei** [comment]
I created a project with 76 CoNLL10 files and 1 txt file. 
If this txt file contains more sentences (like 6,618), it costs more time as annotating a file with less sentences. But it takes still not too much time for ranking. 

<img width="548" alt="screen shot 2018-07-10 at 13 55 12" src="https://user-images.githubusercontent.com/23156705/42508675-abcf4906-8449-11e8-9540-645db2e9477a.png">

**Comment by reckart** [comment]
What is covered under "Getting recommendations from the recommender system"? Is that just a call to `Predictions.getSomething` or more?

**Comment by matchlesswei** [comment]
Yes, something like that. It calls `Predictions.getSomething` to get a map of predictions and put them to an arraylist.

```
Predictions model = recommendationService.getPredictions(aState.getUser(),
                aState.getProject());
List<List<AnnotationObject>> result = new ArrayList<>();

Map<String, List<List<AnnotationObject>>> recommendationsMap = model
            .getPredictionsForWholeProject(aLayer, documentService, true);

Set<String> documentNameSet = recommendationsMap.keySet();

for (String documentName : documentNameSet) {
      result.addAll(recommendationsMap.get(documentName));
}
return result;
```

**Comment by reckart** [comment]
Ok. Although due to the refactoring we are currently doing it doesn't make sense to optimize it now. But we should keep an eye on it for after the refactoring.

**Comment by reckart** [comment]
PR #388 has changed a lot such that the analysis in this issue is outdated. Closing for the moment - we probably have to open a new one as soon as we investigate the performance that we have post #388.
