### ISSUE TITLE
Delete shortcut for annotations

### ISSUE THREAD

**Issue by pottieral** [inception-project/inception#2306]
Working on pre-annotated documents, sometimes a user must delete a tag. I was asked if there is a shortcut to delete the selected tag.

Maybe DEL or CTRL+DEL or SHIFT+DEL (if DEL is reserved for some other actions I am not aware of) could delete the currently selected annotation.

Maybe I missed the shortcut but I think I can only define shortcuts to create an entity per the doc (https://inception-project.github.io/releases/0.19.3/docs/user-guide.html#_key_bindings).

Thanks in advance, and sorry if the feature exists and I did not find it.

**Comment by reckart** [comment]
The only way to delete an annotation is currently to select it and then delete it via the right sidebar. There is keyboard shortcut yet, so you didn't miss it. Thanks for opening the issue :)

**Comment by reckart** [comment]
DEL has a "normal" meaning when the cursor is in an edit field. As the cursor being in an edit field is a regular situation in INCEpTION, using DEL would not be a good idea. We usually use SHIFT+XXX in such a case (e.g. we have SHIFT key combinations for paging, switching between documents, switching between annotations - so having one for deleting annotations seems sensible as well.
