### ISSUE TITLE
coloring rules - transfer from one project to another

### ISSUE THREAD

**Issue by jwijffels** [inception-project/inception#2314]
I have 2 questions on the coloring rules

1. Is it possible to transfer the coloring rules from one project to another. Idea here is to have a development project where everything is set up and next copy the rules to the real project where the annotations are done. I see that that data is in the `traits `column of the  `annotation_type` table in the MariaDB. Is it ok to just populate it there directly or is there a more elegant way in the user interface

2. Question related to: https://inception.datatailor.be/doc/user-guide.html#_coloring_rules
I have a layer with multiple features, some features are required, some of them are not
![voorbeeld](https://user-images.githubusercontent.com/1710810/120452309-690c7e00-c392-11eb-8770-41c095a66d16.png)
I'd like to make a color based on the first feature.
I noticed that the following regular expression the first one does not match, the second one does match the image above and the third one as well. I don't understand why the first one does not match? Does it not allow partial matching?

- `2. GEO/PLAATS`
- `2. GEO/PLAATS \| .*.`
- `2. GEO/PLAATS .*.`

**Comment by reckart** [comment]
1) There is currently no elegant way in the UI to transfer only the coloring rules. To duplicate a project setup, you could currently only export the entire project, import it again and then remove all the documents.

2) The Java `Pattern.matches("regex", text)` documentation says: *Compiles the given regular expression and attempts to match the given input against it.* - Looks like that means the **entires** text, not  a substring. So if you want to do substring matching, you'd need to do e.g. `.*substring.*`.

**Comment by jwijffels** [comment]
Thanks for the information that Pattern.matches is used, I'll lookup the java docs on that.
