### ISSUE TITLE
Error: IllegalArgumentException: Position [XXXX] is not in any row

### ISSUE THREAD

**Issue by habernal** [inception-project/inception#2315]
**Describe the bug**
Switching to brat@120 chars alignment ends up with

```text
Error: IllegalArgumentException: Position [12439] is not in any row
```
**Please complete the following information:**
 -  0.19.4 (2021-05-23 14:43:43, build a9623e33)

**Additional context**
Not sure if this is input-dependent (and the input was mal-formed), but should not end up with such an exception.

**Comment by jcklie** [comment]
Can you share a file which causes this or is it for any?

**Comment by habernal** [comment]
It's a non-public file and I'm not even the project owner. I thought just the exception message might ring a bell. I'll handle it over e-mail then.

**Comment by reckart** [comment]
@habernal Running the CAS Doctor from the project settings finds that your projects contains zero-lengths sentences - sentences with the same start/end position are not supported. Not sure if that is part of the problem, but it is something you should be aware of. CAS Doctor can repair that for you if you want.

**Comment by habernal** [comment]
@reckart Good catch. I didn't know about the CAS Doctor, sounds like a great feature. How about running CAS Doctor on importing CAS files to spot potential errors very early?
