### ISSUE TITLE
Search for named entity using <> 

### ISSUE THREAD

**Issue by naveen2507** [inception-project/inception#232]
Queries using `< >`

- Doesn't highlight the search portion.
- If the annotated Named_entity is the first word of the document it throws `java.lang.ArrayIndexOutOfBoundsException` with zero results of course.

Search using` [ ]`, works perfectly fine except for the cases where  named entity covers multiple tokens

**Comment by betoboullosa** [comment]
@naveen2507 in which version/branch you got these errors? 

The command you're using to query is this one?

<Named_entity/>

**Comment by naveen2507** [comment]
@betoboullosa In the master branch, if we give search query : `<Named_entity.value="OTH">`, and in case the first token has been annotated as `OTH`, it gives `java.lang.ArrayIndexOutOfBoundsException` with -1,  as it tries to keep the begin index with tokenPositon-1. 

In `feature/170-kb-concept-indexing` branch, same happens for identifier search.

**Comment by naveen2507** [comment]
@betoboullosa I can replicate the issue on blinky-testing.

**Comment by betoboullosa** [comment]
@naveen2507 Please, tell me the name of the project and document where you reproduced the problem. I've tried to reproduce it, but was unable to.

**Comment by naveen2507** [comment]
@betoboullosa  Project NK-Test with NK-Test/document-wine.txt. 

Query : `<Named_entity.value="OTH">` doesn't return any result but in case we delete the annotation from the first token, it gives the result but without the highlighted search part.

**Comment by betoboullosa** [comment]
You're missing the /, like:
<Named_entity.value="OTH"/>

**Comment by naveen2507** [comment]
ok. It works for both the cases. (as well as identifiers)
