### ISSUE TITLE
Project import fails 

### ISSUE THREAD

**Issue by mromanello** [inception-project/inception#2322]
**Describe the bug**

The import of a project from one instance of inception (source) to another (target) failed after an `SqlExceptionHelper` exception was raised. A certain number of things (layers, etc.) were imported, but then the import suddenly failed with `ProjectExportException`. 

**To Reproduce**
1. Export project from source inception
2. Import project on to target inception
3. See error

**Expected behavior**

It should import the project without failing. 

**Please complete the following information:**
 - source inception (0.19.3)
     - Java (openJDK) version 11.0.11
     - OS Ubuntu 18.04.5
     - embedded DB
 - target inception (0.19.4)
     - Java 16
     - Ubuntu 20.04
     - MySQL DB
[log-inception.txt](https://github.com/inception-project/inception/files/6598656/log-inception.txt)

**Additional context**
Complete error stack trace attached. Exported project file may be shared privately for error replication purposes on request.

**Comment by reckart** [comment]
Sounds like your MySQL DB might not be configured for the UTF8MB4 character set?

**Comment by mromanello** [comment]
thanks for the quick reply @reckart ! that's the problem I think. Do I understand correctly that we'd need to do the following to fix this issue:
- change the utf-8 collation on the existing inception MySQL DB
- set the `characterEncoding` parameter in the JDBC connection string specified in `settings.properties`

(Since it's a MySQL DB server shared between several projects, I doubt we can set the utf8mb4 encoding globally).

**Comment by reckart** [comment]
You can set the encoding and collation per DB and even per column. If you have an existing DB you'd need to update all the tables manually. @jcklie Has done that for one of our servers at least and can probably give you pointers.

**Comment by jcklie** [comment]
I think that changing encoding and collation should be enough. You might run into the same issue if you do not change the default after an upgrade, as we then might introduce new tables which are then created with an old default. This also involves changing the save format to baracuda and enabling large keys from what I remember.

I used https://saveriomiroddi.github.io/An-in-depth-dbas-guide-to-migrating-a-mysql-database-from-the-utf8-to-the-utf8mb4-charset/

**Comment by reckart** [comment]
I believe if the charset and collation defaults are properly set at the level of the database, then new tables created during upgrades should automatically get the right settings.

**Comment by reckart** [comment]
@mromanello note we are using the "utf8mb4_bin" collation because INCEpTION distinguishes between upper and lower case. This is different from most tutorials you'll find out there which typically use some "ci" (case insensitive) collation.

**Comment by mromanello** [comment]
hello @reckart and @jcklie 👋 Many thanks for your useful replies, now it's very clear what the problem is and how to proceed next. We are working on it, will keep you posted.

**Comment by reckart** [comment]
Given there was no additional feedback, I assume the issue could be resolved.

**Comment by e-maud** [comment]
Hello @reckart sorry for not reacting earlier, busy times, I will actually apply and test the changes withing the next 2 weeks following your recommendations.  I will post a final word on the closed issue in any case.
