### ISSUE TITLE
Invalid? characters in files can cause "No source file found"

### ISSUE THREAD

**Issue by jacquelinekazmaier** [inception-project/inception#2338]
**Describe the bug**
Document import fails after setting up reverse proxy to run INCEpTION over HTTPS. 
`Error while uploading document XYZ.txt: FileNotFoundException: Source file [XYZ.txt] not found in [/export/repository/project/3/document/48/source/XYZ.txt]`

**To Reproduce**
1. Set up INCEpTION using docker compose (according to admin guide)
2. Set up nginx reverse proxy (according to admin guide)
3. Create a project in the instance and go to Project Settings/Documents
4. Select a file to import (in this case I chose to import a txt file with plain text format)
5. See error

**Expected behavior**
The document is imported without error. 

**Version info**
 - Version and build ID: INCEpTION -- 0.19.3 (2021-04-25 09:58:11, build 238b0e91)
 - OS: Debian Stretch
 - Browser: Happens on both Chrome and Safari

**Additional context**
This is the settings.properties file we are using

> `server.tomcat.internal-proxies=127\.0\.[0-1]\.1
> server.tomcat.remote-ip-header=x-forwarded-for
> server.tomcat.accesslog.request-attributes-enabled=true
> server.tomcat.protocol-header=x-forwarded-proto
> server.tomcat.protocol-header-https-value=https
> wicket.core.csrf.enabled=false
> wicket.core.csrf.no-origin-action=allow
> wicket.core.csrf.conflicting-origin-action=allow`

**Comment by reckart** [comment]
Please check the permissions on your file system. I assume you have mounted the `/export` folder to the host machine. Likely the target folder on the host machine is not configured to permit access to the user if of the INCEpTION user used inside the Docker container.

**Comment by reckart** [comment]
Btw. we just released 0.19.5 :)

**Comment by jacquelinekazmaier** [comment]
Thank you very much for your quick response!

It turned out to be a more trivial issue - our naming convention resulted in some files having the symbol `%` in the filename. Removing this symbol allows the file to be imported fine.

**Comment by jcklie** [comment]
Also seen as `Source file [CSA Adria.txt] not found in [/srv/inception-stable/repository/project/441/document/27407/source/CSA Adria.txt]`, maybe that is a similar issue

**Comment by jcklie** [comment]
If I upload a file called `Gum with %.txt`. then I get

`Error while uploading document Gum with %.txt: URISyntaxException: Malformed escape pair at index 85: file:/srv/inception-stable/repository/project/451/document/28205/source/Gum%20with%20%.txt
`

**Comment by jcklie** [comment]
Documents with space in their name work for me

**Comment by reckart** [comment]
INCEpTION no longer allows certain characters in document names including the `%` character.
