### ISSUE TITLE
Allow setting command to open browser

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#2347]
**Is your feature request related to a problem? Please describe.**
My default browser is Safari, but I want INCEpTION to fire up Chrome when running as a standalone app.

**Describe the solution you'd like**
The ability to set a custom command in the settings.properties file.

**Describe alternatives you've considered**
Using a general URL-handler switching tool.

**Comment by jcklie** [comment]
Jun 08 22:53:24 blinky inception-testing.jar[13557]: Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'commands.open-browser' in value "${commands.open-browser}"

**Comment by reckart** [comment]
Fixed
