### ISSUE TITLE
Unable to config and receive Wikidata (fr) Knowledge Base recommendations for annotations 

### ISSUE THREAD

**Issue by Lucaterre** [inception-project/inception#2351]
**Describe the bug**

The configuration of the knowledge base Wikidata (via SPARQL endpoint) and the full-text search in it, for an annotation project, fails with French language. I am unable to receive recommendations on annotations for a french wikidata annotation layer.

**To Reproduce**

1. Go to the "settings" and click on "create"

2. Enter name "wikidata-fr", choose language "fr" and type "Remote " and "next"

3. Choose in "suggestions" : Wikidata (direct mapping)

4. change nothing on default "Schema mapping" and click on "finish"

5. click on "wikidata-fr" KB and set language 'fr' again and "save" (Cf. screen_settings.png)

6. Return on Home project and go to "Knowledge Base", select "wikidata-fr", the tree structure appears in French (Cf. tree_fr_wikidata.png)

7. In the "Search bar", search the city in plain text "Vincennes" (for example) and it doesn't return anything after a long loading time. Which is weird, because it works for a 1 or 2 character word but not 3 (Cf. screen_search.png).

8. I test the same process in the "annotation" screen, and after a long time, the process return a SPARQL error (Cf. error_annotation.png + log.txt)

**Expected behavior**

It should be able to search the full-text French Wikidata KB and find a list of candidates labels and Qid URI.

**Screenshots and attached files**

screen_settings.png (sorry for the quality)
![screen_settings](https://user-images.githubusercontent.com/44713216/121336734-198efa80-c91c-11eb-831d-2e05164feab3.png)

tree_fr_wikidata.png
![tree_fr_wikidata](https://user-images.githubusercontent.com/44713216/121336875-35929c00-c91c-11eb-8251-a630ff6cb5f1.png)

screen_search.png
![screen_search](https://user-images.githubusercontent.com/44713216/121337013-5b1fa580-c91c-11eb-9a22-d229346bc126.png)

error_annotation.png
![error_annotation](https://user-images.githubusercontent.com/44713216/121337082-725e9300-c91c-11eb-9b1c-84bf9d5c9726.png)
![Capture d’écran de 2021-06-09 12-12-38](https://user-images.githubusercontent.com/44713216/121337139-82767280-c91c-11eb-900f-badfafcb479d.png)
[log.txt](https://github.com/inception-project/inception/files/6622889/log.txt)

**Please complete the following information:**

- Personal config :
    - Version and build ID: Inception 0.19.4 
    - OS: Ubuntu 18.04.5
    - Browser: Chrome

- Host config :
    - Version and build ID: Inception 0.19.4 
    - OS: Ubuntu 20.04
    - Java 16
    - DB : MySQL DB

**Additional context**

- I tested by configuring in German (de), I have the same issue;

- a full-text search works for English;

- I tested the SPARQL query from the log directly in the Wikidata endpoint (https://query.wikidata.org/), and returns an error too.

**Comment by reckart** [comment]
Please try setting the full text search mode to wikidata, save and try again.

**Comment by Lucaterre** [comment]
thank you for the answer ! it only works with "https://www.mediawiki.org/ontology#API/search" mode in "full text search mode".

But what is strange is that when I select the "mode" and after saving; it directly returns "No full text search support", as if it was a default that could not be changed, which confused me. 

![test](https://user-images.githubusercontent.com/44713216/121357662-43ebb280-c932-11eb-99e7-a00e831abffd.gif)

**Comment by reckart** [comment]
Hm, yes that looks odd. Thanks for letting us know. We need to check why this is resetting.

**Comment by reckart** [comment]
Fixed the issue regarding the FTS dropdown resetting itself here: https://github.com/inception-project/inception/issues/2360
