### ISSUE TITLE
Allow unlocking of liquibase from command line/tray icon

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#2382]
**Is your feature request related to a problem? Please describe.**
Sometimes the liquibase migration can lock itself. Then, one needs to release the liquibase lock. Right now, it requires an SQL editor.

**Describe the solution you'd like**
Allow unlocking of liquibase from command line/tray icon

https://forum.liquibase.org/t/lock-problems-with-hsqldb/2765
https://docs.liquibase.com/commands/community/releaselocks.html
https://github.com/liquibase/liquibase/blob/9fd6ea48f789da2e1c0551e0e5c86cd0d25825b5/liquibase-core/src/main/java/liquibase/integration/commandline/Main.java#L1703

**Comment by reckart** [comment]
For the moment, I'd tend to allow it only from the command line - e.g.

<img width="742" alt="Screenshot 2021-06-16 at 22 42 49" src="https://user-images.githubusercontent.com/1410238/122291101-ba6d4f00-cef4-11eb-997e-634050fb7a98.png">

I wonder - when the user requests to release the lock, should we only release the lock and then immediately shut down again to force the user to not simply run INCEpTION always with lock-force-removal enabled?
