### ISSUE TITLE
Sidebar of Getting Started User Guide

### ISSUE THREAD

**Issue by Falko1** [inception-project/inception#2383]
The "Table of Contents" sidebar on the left of the "Getting Started User Guide" moves from "Project Settings" to "Structure of an Annotation Project" way too early, i.e. already in the "Tagsets" subsection of "Project Settings".

**Comment by reckart** [comment]
I have the feeling this is simply how tocify works - it seems to look for the anchor closes to the current scroll position and highlight that: https://github.com/gfranko/jquery.tocify.js/blob/c5ef23554b731a3076ff767eb3b65d78968acf31/src/javascripts/jquery.tocify.js#L661-L670

```
                            // Determines the index of the closest anchor
                            anchors.each(function(idx) {
                                var distance = Math.abs(($(this).next().length ? $(this).next() : $(this)).offset().top - winScrollTop - self.options.highlightOffset);
                                if (closestAnchorDistance == null || distance < closestAnchorDistance) {
                                    closestAnchorDistance = distance;
                                    closestAnchorIdx = idx;
                                } else {
                                    return false;
                                }
                            });
```

**Comment by reckart** [comment]
Can we maybe remove the "Settings and Structure of an Annotation Project", move the "Project settings" and "Structure of an Annotation Project" up one level and then introduce sub-headings for the different "subsections" in "Project settings" and "structure"?

**Comment by jcklie** [comment]
I do not mind the change. @Falko1 What do you think?

**Comment by Falko1** [comment]
I had a quick look at it. Simply removing "Settings and Structure of an Annotation Project" and moving up "Project settings" and "Structure of an Annotation Project" one level does not work. The exact same error occurs at the same position. 
If we introduce sub-headings in addition, then the error does not occur anymore, but these sub-headings appear in the sidebar. It looks like this: 
![grafik](https://user-images.githubusercontent.com/61779598/130596632-d28f59ee-0cea-4005-99ef-4d572b5bcccc.png)

Maybe it is possible to tell tocify to not include headings of the fourth level (e.g. ==== Documents)  in the sidebar

**Comment by reckart** [comment]
IMHO looks good
