### ISSUE TITLE
Possibility to reopen all curated documents at once

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#2412]
Possibility to reopen all curated documents at once (e.g., usefull, if we want to add another layer or feature after the curation. Currently only the status of the annotator's files can be changed at once)

**Comment by reckart** [comment]
@salvadora if you add a new layer/feature and then re-open documents and then continue curation - how do you deal with going through the documents again to curate them? If you press "re-merge", all already curated data gets discarded. So you have to go through everything manually?

**Comment by reckart** [comment]
@salvadora You mean that in the "Curator" column also a checkbox appears when clicking on "bulk change", right?

<img width="542" alt="Screenshot 2021-06-23 at 22 42 48" src="https://user-images.githubusercontent.com/1410238/123165333-645c5680-d474-11eb-99a9-67a9bce3de88.png">

**Comment by salvadora** [comment]
@reckart My use case is: After adding a new feature, I would reopen all documents for the annotators at once, and after they added the annotation for the new feature, I would do the curation manually one more time. 

And yes, I meant a checkbox for a "bulk change". Another option would be to be able to reopen a single curated file in the curation view while checking the annotation
