### ISSUE TITLE
Ability to bulk-finish the curation documents without disagreements

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#2414]
Possibility to finish the curation of documents, where no disagreements are found or at least to hide them during the curation (usefull, if the annotation of some documents is rather easy, and we decide to trust the agreement. It would save time in large projects)

**Comment by reckart** [comment]
Interesting idea but not so easy because calculating the differences is relatively time consuming, so we would somehow need to model that as an asynchronous task. It is certainly not something you would want to do for every document at the time of opening the "open documents" dialog.

**Comment by salvadora** [comment]
Ok. I just thought the differences are kind of already calculated. In the curation view I can easily recognize "no disagreements", wher no sentence of a document  is marked as red.

**Comment by reckart** [comment]
Covered by #4768
