### ISSUE TITLE
Import BRAT annotations to INCEpTION

### ISSUE THREAD

**Issue by xegulon** [inception-project/inception#2424]
I have BRAT annotations (`.txt` files and their corresponding `.ann` files). I would like to import them to INCEpTION.

The import functionality only takes as input `.zip` files. I would like it to be able to import a folder containing `.txt`/`.ann` files.

**Comment by reckart** [comment]
INCEpTION does not support importing files in the brat format at this time. In principle, it is possible to convert brat data to the UIMA CAS XMI format using DKPro Core and then to import the converted data - but it is not a very straigh-forward procedure. First, you'd have to set up your annotation scheme in INCEpTION, then export the UIMA type system, then build a conversion script to read the brat data and map it to the annotation scheme and then to import the data.

**Comment by reckart** [comment]
Here is an example of a conversion script (originally used with WebAnno, but applies for INCEpTION as well): https://gist.github.com/reckart/306b8ffddd30bee1f3afd0468a9ad31d
