### ISSUE TITLE
Difference in labelling of annotation marker vs identifier lookup

### ISSUE THREAD

**Issue by antonyscerri** [inception-project/inception#2426]
**Describe the bug**
There appears to be a difference in the SPARQL queries being run to get the label and description for an annotation based on the linked concept from a KB vs the SPARQL run to lookup a concept based on a string in how they handle finding concept (class), instance or properties in the KB. 

Using Wikidata as the KB and setting the identifier attribute on a span layer to use "<Any concept/instance>" for "Allowed Values" this option will match any entity/item in wikidata using the label properties. I was doing this whilst checking on why certain items would not get labels in the annotation markers (or their tooltips) and some were not turning up when doing a search on the KB attribute of the span. Originally this was set to instance only and there were some which would display labels (as we loaded existing annotations into INCEpTION) but you could not lookup the same entity. After changing the option to use any concept/instance this drop all constraints in the full text search SPARQL and now matched anything, including resources in Wikidata which do not have "instanceof" or "subclassof" properties. 

However those resource which do not have both properties will not display their labels in the document view as the code there (https://github.com/inception-project/inception/blob/2fcd7001964fc3db9f43c3ef5ede98ac23c0188e/inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImpl.java#L1085) is I believe checking for concepts, then properties and then instances which will exclude these items.

**To Reproduce**
1. Using a project configured to use wikidata as a KB and with an attribute on a span layer set to use it with allowed values set to any concept/instance
2. Create a span and set the attribute (typically identifier) by searching for "solar minimum" and select http://www.wikidata.org/entity/Q2314257
3. In the document view the span will have a marker displaying the message "Error: NO LABEL"

**Expected behavior**
So this bit of code doesn't seem to follow the same selection based on the "Allowed Values" for the span attribute. To make it consistent either the same constrain needs adding to the FTS SPARQL or relaxing the label lookup on span markers. 

**Please complete the following information:**
 - Version and build ID: INCEpTION -- 0.19.3 (2021-04-25 09:58:11, build 238b0e91)

**Comment by reckart** [comment]
Thanks for the report! In principle, the code should already be highly de-duplicated so that no different paths exist for looking up things. But it looks like we may have missed a case here and need to look into this in more detail.

**Comment by reckart** [comment]
Yeah... `readItem()` seems to need some refactoring...

**Comment by antonyscerri** [comment]
Thanks for checking, the exact behaviours are a little open to interpretation, some of the comments in the other area of code for the query builder didn't quite match the code so I wasnt entirely sure what to expect, particular this set of lines - https://github.com/inception-project/inception/blob/ab449766e53dbfbd70c68ac294c7437c9adeabe5/inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilder.java#L1547

It says "it has...." but then uses filterNotExists. It all about the pattern that have been chosen to make distinctions between classes and instances i think.

**Comment by reckart** [comment]
Yes, sorry - looks like I copied the code and updated the code and did not update the comments. The top level comment would be "is an instance" and then a "not" in all the others. That's the crux with comments and why many people debate better not to have them... I still often find them useful.

**Comment by antonyscerri** [comment]
Indeed :) I found a few comments explaining the intended logic for determining class or instance elsewhere. Depending on the choice of the allowed values setting (originally i was on instance only) the query built for the lookup and the marker labelling seemed to be less aligned wrt using the class iri setting. 

I'm not sure if the current "Any Concept/Instance" is intended to also include properties (as it does in the FTS query, which also allows for anything really) but I was wondering about having such an option which did not constrain it as it does depend on the KB to be modelled appropriately.

**Comment by reckart** [comment]
You mean you'd like another setting "Any Concept/Instance/Property"?

**Comment by antonyscerri** [comment]
Whether its another option might be worth separate consideration for handling the nuance of class, instance, properties other types. Worst case would just be not to check any type information.

The problem as it stands though is the queries are not consistent in what they consider a concept/instance when doing a lookup and when displaying its label in the UI (in the input field box after you've selected an entry or in the tooltip over a span). So i think this would need to work still regardless of any additional options.

**Comment by reckart** [comment]
The inconsistency can be fixed on the annotation page by switching from `readItem()` to `readHandle()`. The second already does not make a distinction between the different types (concept, instance, property) and only needs to be tweaked minimally to retrieve the description in addition to the label. 

However, on the KB page, when clicking on an IRI, different parts of the UI need to handle the click depending on whether the IRI belongs to a concept/instance/property, so the distinction is important there. Maybe there are better ways to handle this on the KB page, but presently it is a bit difficult to "fix" it there.

So I think for the moment, switching from `readItem()` to `readHandle()` in the `ConceptFeatureSupport`should address the problem.

**Comment by reckart** [comment]
@antonyscerri the "Any concept/instance" is now simply any - so it reflects what it actually does. There is still a little inconsistency on the KB page - you can search for things that are neither concept/class/property but if you try to open it in the KB page, there will be an error message saying that is not possible. Otherwise, I think it should be pretty consistent now in the dropdown, rendering and also indexing.
