### ISSUE TITLE
Export to PubAnnotation JSON-based format for both entities and relations

### ISSUE THREAD

**Issue by xegulon** [inception-project/inception#2429]
I'm trying to export a project I made using INCEpTION. I have annotations for both spans and relations. I would like to have a JSON file with both the entities (with their document-wide character offsets) and the relations between the entities. I find the annotation format of [PubAnnotation](https://www.pubannotation.org/docs/annotation-format/) quite convenient.

**Comment by jcklie** [comment]
I think it would be easiest for you to export as XMI and construct the JSON with Python. We have an example that exports as XMI and uses sentence classification you can adapt [here](https://colab.research.google.com/github/inception-project/inception/blob/master/notebooks/annotations_as_one_sentence_and_label_per_line.ipynb).

**Comment by reckart** [comment]
Assuming the that issue was resolved as there was no more feedback and thus closing the issue.
