### ISSUE TITLE
Avoiding local download during export: Export via backend / parsing .ser files?

### ISSUE THREAD

**Issue by jacquelinekazmaier** [inception-project/inception#2430]
**Is your feature request related to a problem? Please describe.**
We are working with very sensitive data that should be saved in the cloud at all times and not downloaded locally. Therefore we need a process by which we can export the documents in the backend rather than through the GUI. I can access the `CURATION_USER.ser` files, for instance, but I am not sure how to parse these. 

**Describe the solution you'd like**
Either (1) a process by which I can initiate the export from the backend (so that the files are saved in the VM I am using to run the server, for instance, instead of my local machine, 
or (2) guidance on how to parse the `.ser` files 

**Describe alternatives you've considered**
As I mentioned, the GUI export function results in local download of the files which is unsuitable for our security requirements.

**Comment by jcklie** [comment]
You could try https://github.com/inception-project/inception-cli which can download from the command line. There is also the [INCEpTION remote API](https://inception-project.github.io/releases/0.19.7/docs/admin-guide.html#sect_remote_api) which you could use.

**Comment by reckart** [comment]
There is also the option of activating the "versioning" plugin in 0.20.x (when it is released) which allows to export to a git repository running on the machine where INCEptION is running.

The SER files are UIMA`CASCompleteSerializer` objects written using the Java serialization mechanism. Code to read them using the Apache UIMA Java SDK v3.x looks approximately like this:

```
CAS cas = CasCreationUtils.createCas();
try (ObjectInputStream is = new ObjectInputStream(new FileInputStream(aFile))) {
  CASCompleteSerializer serializer = (CASCompleteSerializer) is.readObject();
  Serialization.deserializeCASComplete(serializer, (CASImpl) cas);
}
```

After that you can access the annotation data from the CAS object. There are a few examples in the [readme](https://github.com/apache/uima-uimaj) of the Apache UIMA project and a quite [extensive documentation](https://uima.apache.org/d/uimaj-current/version_3_users_guide.html) on the Apache UIMA website (or more: https://uima.apache.org/d/uimaj-current/).

**Comment by reckart** [comment]
I assume that one of the suggested options is viable. If not, please comment, then we can re-open as a future improvment.
