### ISSUE TITLE
Disabling layers on a per-user basis

### ISSUE THREAD

**Issue by shohrehhd** [inception-project/inception#2431]
Hello, 
I am fascinated by INCEpTION and using it in different projects now, so I keep coming up with different questions :)

In some tasks when the project has many different layers of annotation which can affect the judgement of separate groups of annotators it would be very helpful to be able to disable layers of annotation for specific users.(or group of users) 

The fact that we are able to disable the layers is helpful in this case. However if the annotation of different layers are done in parallel it would be better to assign layers(or disable layers) for different users.

If such feature already exists would you please let me know?

Thanks in advance,

**Comment by reckart** [comment]
If the annotations do not build on each other, how about copying the project, performing the annotations in different projects and maybe merge the data post-hoc/externally if you target a unified representation?

**Comment by shohrehhd** [comment]
Of course, I was thinking  if such a feature exists we could skip the external merging step.

**Comment by reckart** [comment]
I believe that the complexity a per-user/per-layer visibility/editability setting would introduce (additional UI, additional code, maintainability, interaction of this feature with other features) is significantly higher than implementing e.g. a Python script which would use DKPro Cassis to load two XMI files for the same text and coping all their data into a third file and writing that out again.
