### ISSUE TITLE
Case Insensitive Token Search

### ISSUE THREAD

**Issue by antonyscerri** [inception-project/inception#2433]
Hi

Is it possible to do a case insensitive search on a token (or phrase) value within the annotation search? It appears to at least by default do the searches case sensitively. We found there is support for some level of regex on terms, so you can do [dD]og for title case, or "dog"|"Dog", but it would be nice to know if there is a feature or part of the search syntax we've overlooked that will let us simply do it case insensitive.

Thanks

Tony

**Comment by reckart** [comment]
Well... yes... that would be nice indeed.

Related issue: https://github.com/meertensinstituut/mtas/issues/20

**Comment by antonyscerri** [comment]
Ok its back to the t_lc...i did see that in MTas but couldnt find a query syntax to let me select it, so we dont have a convenient field switch there it seems. Are you able to toggle the default as a runtime option when passing over the query so it could maybe be a search setting?

**Comment by reckart** [comment]
I believe we actually need to create that "XXX_lc" field first.

Personally, when I wrote that feature request I had hoped that there would be some option for that in MTAS so one could make even parts of a query pattern case sensitive and others not like in the [original CQP](http://courses.washington.edu/hypertxt/csar-v02/CQPSyntax.html). But looks like that would also mean changes to the MTAS query parser...

I wonder - how about we simply always make the INCEpTION queries lower-case...

**Comment by antonyscerri** [comment]
I'll have a deeper dig, im not sure if these are explicit fields or prefixed added to tokens. I was trying to get one of the lucene inspection tools built but running into java and lucene conflicts for the versions used. I kind of got the impression if you pick "t" it would also automatically create the "t_lc" but at query time its seems like you have to pick one or the other.

**Comment by antonyscerri** [comment]
So the prefix is prepended to tokens during indexing, and the MTas schemas, which i assume are for standard formats they can ingest in some examples applies a second token generator which appends _lc to the default prefix used which provides the case insensitive searching. 

In INCEpTION you have a custom analyser setup by looks of it, the part generating the token to index is:

https://github.com/inception-project/inception/blob/f1e59f31e21e6704dcd1f84fdb607d4884b3bbb0/inception/inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUimaParser.java#L409

I think you might be able to get away with creating a second MtasTokenString with the same offsets and position information, just change the tokens value to the lowercased version and also change the prefix to be your own (looks like the prefix currently used is Token) so Token_lc.

Then in the query you can use a specific rather than default simple word, so rather than:

dog

You can use (and this works now):

<Token="dog"/>

With the addition, we could then use:

<Token_lc="dog"/> 

To match all instance ignoring case of the word dog. This can then be mixed in a query. Of course the cost here is double the words get indexed. This would only take care of bare document words, i didnt go through to check feature values etc.

**Comment by reckart** [comment]
Yes - the problem would remain for feature values. That's why I suggested maybe to simply lower-case everything (text + feature values). And then... we could still consider introducing a `Token%cs` (or `Token_cs`) for case-sensitive.

**Comment by antonyscerri** [comment]
You have a different analyzer for those so things could be kept separate, kind of depends on the most utility with feature values (and I'm assuming also sentence and annotations). Those last three I take it that its indexing the whole value as a single token, it doesnt include word search within a value (sorry playing catchup on MTas).

Having both options with words is useful just looking for abbreviations and the like you need that case sensitivity at time.  Where as for feature value if its typical a tag name or identifier then exact match probably is sufficient, question whether you get identifiers with mixed case much if at all.

**Comment by antonyscerri** [comment]
Of course is an IRI scheme includes save the name of a concept, which may have abbreviations etc its entirely possible there would be a conflict if they were lowercased, so maybe features should remain exact.
