### ISSUE TITLE
Documentation - Concept feature search

### ISSUE THREAD

**Issue by antonyscerri** [inception-project/inception#2434]
The documentation on "Concept features" does not explicitly state what is searchable and what it is searched against and when. I believe there is support for certain things like IRI matching which are given priority. It was unclear the interaction when entering a full IRI, vs a short form ID vs words. 

Also the identifier box (default concept linking NE setup) is not prefilled with the span text (might be a nice feature for new annotations), but simply clicking space will trigger a lookup and reasonable candidates are found but its unclear whether its using the annotation text, some surrounding context window (I've seen mention of that elsewhere).

Does it do lookups using different values other than simply the one entered, are these queries or post filters, are multiple queries run and results merged in some priority grouping.

Thanks

**Comment by reckart** [comment]
This is the code you are looking for:

https://github.com/inception-project/inception/blob/269eca069eebe0cb223c16dfb4075275ceca1b44/inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/ranking/BaselineRankingStrategy.java#L37-L63

**Comment by reckart** [comment]
Note though that the feature generators for the `KEY_FREQUENCY`, `KEY_NUM_RELATIONS` and `KEY_ID_RANK` are disabled, so these have no effect on the ranking.

**Comment by antonyscerri** [comment]
Thanks and the other relevant bit (I found it again) seems to be:

https://github.com/inception-project/inception/blob/ab449766e53dbfbd70c68ac294c7437c9adeabe5/inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/service/ConceptLinkingServiceImpl.java#L155

Which controls the different matches used to select candidates.
