### ISSUE TITLE
Curation mode failing to merge agreeing annotations when span is labeled multiple times

### ISSUE THREAD

**Issue by skatje-myers** [inception-project/inception#2438]
**Describe the bug**
The curation mode sometimes falsely claims a disagreement, failing to merge an annotations into the "gold" version when there is no disagreement in actuality. The sentence is *not* marked as red to identify it as a disagreement. This occurs when the same text span is marked as a SemArg twice.

**To Reproduce**
1. Have two annotators do identical annotations for a sentence: mark the same span as a SemArg twice, with each getting a relation to some predicate (see screenshots for examples)
2. Start Curation and observe that the span that was twice marked with SemArg has no annotation merged into the "gold" version, although the sentence itself is not flagged as having any disagreement.

**Expected behavior**
Since both annotators have identical annotations, they should have been fully copied into the "gold" sentence.

**Screenshots**
![Screenshot from 2021-07-02 12-49-45](https://user-images.githubusercontent.com/5782965/124312606-ce3bc680-db2c-11eb-9abb-f2c5f4b16328.png)
![Screenshot from 2021-07-02 12-54-00](https://user-images.githubusercontent.com/5782965/124312610-d09e2080-db2c-11eb-9b07-757ac626b6f9.png)
![Screenshot from 2021-07-02 12-49-22](https://user-images.githubusercontent.com/5782965/124312601-cc720300-db2c-11eb-8b24-ddad0f29ebd4.png)

**Please complete the following information:**
 - Version and build ID: 0.19.7 build 53edf712
 - OS: Linux
 - Browser: Chrome

**Comment by reckart** [comment]
If a user makes two annotations of a given type at the same position, then the system treats this as the annotator herself being unable to make a decision. If the annotator cannot make a decision, then the pre-merging also does not make a decision. That is why the curation ignores "stacked" annotations. Also, you can only click-merge one of the stacked annotations. You can however manually create the other one. In terms of merging the slot connections: if there are two semarg annotations at the same position in the curator's view, then the system is unable to decide to which a particular slot should be linked. Thus, merging again is not permitted.

Does that make sense to you?

**Comment by skatje-myers** [comment]
Sure, that makes sense. But shouldn't the sentence be marked in red to indicate to the curator that it should be investigated? As it is, these types of sentences are being quietly added as gold in their incomplete state.

**Comment by reckart** [comment]
A new coloring scheme has already been implemented and is going to be released soon.

See: https://github.com/inception-project/inception/issues/2193#issuecomment-873222572

**Comment by skatje-myers** [comment]
Awesome, we look forward to that update!
