### ISSUE TITLE
Extend scope of Search over annotated KB Identifer

### ISSUE THREAD

**Issue by naveen2507** [inception-project/inception#244]
- [x] Search for a specific instance, plus its class and all its super classes.

- [x] KBSI : Add method to get , if an IRI is an instance or class

**Comment by MdeBoer95** [comment]
follow up issue #124

**Comment by reckart** [comment]
@naveen2507 can you split out the "KBSI : Add method to get , if an IRI is an instance or class" into a separate issue please?

**Comment by naveen2507** [comment]
> @naveen2507 can you split out the "KBSI : Add method to get , if an IRI is an instance or class" into a separate issue please?

@reckart we don't need it now. Lot of work can be carried over from the statement validation PR changes for concept tree

**Comment by naveen2507** [comment]
@reckart Should we index in the super class i.e the concept tree or should we make it while searching for a particular identifier. WDYS?

**Comment by naveen2507** [comment]
I think the second option would be better and would give us more flexibility in terms of advanced search option we may want to introduce later on.

**Comment by reckart** [comment]
I believe we need to index the superclasses, otherwise the search would be terribly slow. How do you imagine to resolve superclasses during search without slowing it down?

**Comment by naveen2507** [comment]
@reckart I did the superclass thingy for the statement validation. I don't think retrieving just the superclass would make it too slow. I suggested the option during search, as it would be better if in future we want to give user that option to select for advanced search option. But indexing the superclass for now would not have any implication either.

**Comment by reckart** [comment]
@naveen2507 we are not talking about retrieving a single superclass for every named entity - we talk about retrieving all superclasses up to the root concept and indexing all of them.

**Comment by naveen2507** [comment]
@reckart Yeah. You mean to say like this https://github.com/inception-project/inception/blob/98aaa3c967e31eed6a4270b8139698e7af67e399/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImpl.java#L820

We can do that, as the depth of tree in most ontologies is not that much. For RDFS/OWL based ontology we have a direct method in SPARQL using **'*'** , but we can't do that for rest of them like WIkidata, etc. So we need to have n number of SPARQL queries to retreive the depth. Ideally SPARQL takes too much time when it has several pattern in ontology for the identified pattern in the query. I don't see that there can be issues for the retrieval in our case for superclass. One possible solution can also be to store parent in KBHandle to have a tree structure from that. But that would not be feasible solution for our current platform scenario. I had a discussion with @Rentier about it on Tuesday. We though to keep it simple and test it with time in case if it has issues w.r.t time complexity

**Comment by reckart** [comment]
Directed Acyclic Graph

**Comment by naveen2507** [comment]
Do you think, it makes sense to have an ontology with a cyclic graph. I don't think there are ontologies with a cyclic graph.

**Comment by reckart** [comment]
I am pretty sure that Wikidata has cycles.

**Comment by reckart** [comment]
I thought Wikidata has a cycle near https://www.wikidata.org/wiki/Q35120 (via subclass-of), but I don't see it right now - so maybe I'm just seeing ghosts. Still there is nothing that guarantees that there are no cycles in the ontology and hitting them would currently simple send the code into an endless cycle and harm the server, so IMHO this fetching of parents should take into account skipping duplicates and cancelling cycles (which is basically handled by skipping duplicates).

**Comment by naveen2507** [comment]
yeah, okay we can take care of the duplicates.
