### ISSUE TITLE
NullPointerException during export in WebAnno 3 format

### ISSUE THREAD

**Issue by ziorufus** [inception-project/inception#2441]
**Describe the bug**
Hello!
When exporting a project to WebAnno, I got NullPointerException error.
In the Inception log I can't see anything wrong, but I found out that the problem is related to a single file: exporting file by file using the button on the annotation interface, one of them cannot be exported. In this case, no message is shown, but no download window appears.

I made screenshots of all the annotations and try to repeat che problem, but I cannot: by re-annotating the file in the same identical way the export then works.

No problem on the export of the other formats.

I then exported the problematic file to UIMA XML format, reimported it and the error appears also with the new file.

In attachment, the two XMI files.

**Screenshots**
![Error](https://user-images.githubusercontent.com/3517832/124331147-20153880-db8f-11eb-80df-e5b6a097eb28.jpeg)

**Please complete the following information:**
 - Version and build ID: INCEpTION -- 0.18.1 (2021-02-10 23:33:09, build d108e4b5)
 - OS: macOS Mojave 10.14.6 (18G8022)
 - Browser: Chrome Version 91.0.4472.114 (Official Build) (x86_64)

**Attachments**
 - [xmi-files.zip](https://github.com/inception-project/inception/files/6757189/xmi-files.zip)

**Comment by reckart** [comment]
Before anything else, please export the full project as XMI as a backup. Then open the "CAS Doctor" tab in the project settings and run a check on your project. It is likely that the check reports some inconsistencies (I expect dangling relations). The tab also offers various repair options. 

From the XMI files, it is likely eventually possible but still difficult to see the issue. In order to process the files with a computer, we'd need at least the typesystem.xml file as well. Even better would be if you could do a full project export, re-import that project, delete all but the problematic file and then export this minimal project.

The WebAnno TSV 3 format makes certain assumptions of how the data is structured. If the data is consistent, it sometimes fails with no-very-helpful error messages. Normally, we should get stack traces for these in the logs.

**Comment by reckart** [comment]
I expect you have dangling relations because there was a recently-fixed bug producing those when deleting spans: https://github.com/inception-project/inception/issues/2075

**Comment by ziorufus** [comment]
Thank you for your answer! I did not know about the possibility of repairing the files through a check. I'll try it next time, and in the meantime I'll update Inception.

**Comment by ziorufus** [comment]
It happens again. The error is:

Non-indexed feature structure [Span:34861 sofa: _InitialView begin: 2376 end: 2394 label: "_"] reachable through [Relation:34871 sofa: _InitialView begin: 2376 end: 2394 Dependent: Span:34861 sofa: _InitialView begin: 2376 end: 2394 label: "_" Governor: Span:34866 sofa: _InitialView begin: 2397 end: 2400 label: "_" label: "_"]

Trying to repair, I get:

INFO	RemoveDanglingRelationsRepair	Removed [4] dangling relations.
ERROR	ProjectCasDoctorPanel	Error repairing annotations of user [teresa] for [83_DetDir_0003658.txt]: Repair attempt failed - ask system administrator for details.

What can I do?

**Comment by reckart** [comment]
Are you using 0.19.7 now? When you attempt the repair, do you see any errors in the logs?

**Comment by ziorufus** [comment]
Thank you for your quick answer. We have a seminar today at 1 PM CEST where we need to use the software. After that, we'll update. Apart from a backup of MySQL DB and the repository folder, is there anything else I should do? I cannot find an update guide, therefore I think it's only a matter of replacing the JAR and relaungh, isn't it?

**Comment by reckart** [comment]
That's essentially what the instructions also say: https://inception-project.github.io/releases/0.19.7/docs/admin-guide.html#sect_upgrade

There is also work towards tool that could be used to bulk-export/import projects via the remote API: https://github.com/inception-project/inception-cli - I have used that when I migrated my setup from MySQL to MariaDB.

**Comment by ziorufus** [comment]
Ok, I made a copy on another machine, upgraded to 0.19.7 and repaired and exported without problems! Thank you very much!
