### ISSUE TITLE
unable to export project

### ISSUE THREAD

**Issue by ofersabo** [inception-project/inception#2445]
**Describe the bug**
Trying to download a whole project from the webpage encounters an error:
Unexpected error during project export: NoSuchElementException: Timeout waiting for idle object
and then the project download process fails.

These are the logs:
2021-07-05 11:25:49 ERROR [Ofer] ApplicationPageBase - Ofer: Unexpected error during project export: NoSuchElementException: Timeout waiting for idle object
2021-07-05 11:25:49 ERROR [Ofer] ApplicationPageBase - Ofer: Project export failed

**To Reproduce**
I don't know how to reproduce this since I can't send you the project.
Also, most of the projects don't encounter this error.

**Screenshots**

**Please complete the following information:**
 - INCEpTION -- 0.17.3 (2020-12-29 19:22:47, build fde91146f90bb5e4e2d340fbbe27be553b3284eb)
 - OS X]
 - Browser: chrome

**Additional context**
we tried to use the CAS doctor and the output isn't returned, and there is no error message. 
See image. 
![image](https://user-images.githubusercontent.com/31179968/124463800-114fa100-dd9c-11eb-9547-56a4b9eefc4d.png)

On the docker logs we get:
2 ERROR [Ofer] ApplicationPageBase - Ofer: Error: de.tudarmstadt.ukp.clarin.webanno.api.casstorage.CasSessionException: Unable to borrow CAS

**Comment by reckart** [comment]
You could try restarting the application then exporting then - that should at least free the CASes which seem to be stuck in the pool. 

You can also make a proper database dump and copy of the data folder, upgrade to 0.19.7 and then try again to export.

**Comment by ofersabo** [comment]
After restarting, the download works, thanks
