### ISSUE TITLE
Unable to export annotations

### ISSUE THREAD

**Issue by maiiabocharova** [inception-project/inception#2446]
When I try to export my annotations in CoNLL format, all the words are annotated with O.
I know it sounds stupid, but please help me, I am desperate.

**Comment by reckart** [comment]
Which of the CoNLL formats do you choose and what layer did you make your annotations on?

**Comment by maiiabocharova** [comment]
I wanted to export in CoNLL 2000 format.
Imade annotations on my own CustomLayer with custom tagset. Maybe I should use a different format?

**Comment by reckart** [comment]
The CoNLL formats do not support custom layers. You can export either as UIMA CAS XMI or as WebAnno TSV 3.

**Comment by maiiabocharova** [comment]
> The CoNLL formats do not support custom layers. You can export either as UIMA CAS XMI or as WebAnno TSV 3.

Thanks a lot!

**Comment by maiiabocharova** [comment]
> The CoNLL formats do not support custom layers. You can export either as UIMA CAS XMI or as WebAnno TSV 3.
Can you please help me once again, how can I convert WebAnno TSV 3 to CoNLL format or at least properly read this tsv file using python?

**Comment by jcklie** [comment]
If you use custom layers, then we normally suggest using XMI. We have an example for that in [here ](https://colab.research.google.com/github/inception-project/inception/blob/master/notebooks/annotations_as_one_sentence_and_label_per_line.ipynb) and [here ](https://colab.research.google.com/github/inception-project/inception/blob/master/notebooks/using_pretokenized_and_preannotated_text.ipynb). Please let us know if you need help for converting.

**Comment by maiiabocharova** [comment]
> If you use custom layers, then we normally suggest using XMI. We have an example for that in [here ](https://colab.research.google.com/github/inception-project/inception/blob/master/notebooks/annotations_as_one_sentence_and_label_per_line.ipynb) and [here ](https://colab.research.google.com/github/inception-project/inception/blob/master/notebooks/using_pretokenized_and_preannotated_text.ipynb). Please let us know if you need help for converting.

Thank you! It helped, but I discovered that my custom tagset is not present in the XMI so I get something like this `(<custom:SECTION1 xmi:id="42409" sofa="1" begin="198" end="212" S1=""/>)`

S1 was the name of my custom tagset (but there were some classes in there, not an empty "")

**Comment by jcklie** [comment]
The XMI is how we also internally store annotations. It is strange that the export differs from the representation in the editor. Can you share us an export of the project? You can see my mail in my Github profile.

**Comment by jcklie** [comment]
Hopefully solved after mailing, if not, then please reopen this.

**Comment by maiiabocharova** [comment]
> Hopefully solved after mailing, if not, then please reopen this.

Yes! Thank you! And also thank you for supporting this wonderful project,  it's really great!
