### ISSUE TITLE
Jumping from annotation editor to PDF annotation via recent activity does not work

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#2449]
**Describe the bug**
Jumping from annotation editor to PDF annotation via recent activity does not work. It loads but then jumps back to the annotation editor.

**To Reproduce**
1. Annotate a PDF
2. Go to annotation dashboard
3. Click on recent activity 
4. See error, it loads, then jumps back to dashboard and shows error `Project [p] does not exist`

**Expected behavior**
It works

**Please complete the following information:**
 - Version and build ID: master

Not sure if it is also broken on stable, as the PDF is broken there.

**Comment by reckart** [comment]
For some reason, a request to an URL with two `p` is issued: `http://localhost:8080/p/p/432/annotate/45349?17-1.2-centerArea-editor-vis`

Check by setting a breakpoint in `de.tudarmstadt.ukp.clarin.webanno.ui.core.page.ProjectPageBase.getProjectFromParameters()`

**Comment by reckart** [comment]
Problem is that when opening the PDF by clicking on the "Annotation" link in the sidebar of the project dashboard, the URL of the page is e.g.:

```
http://localhost:8080/p/234/annotate
```

But when opening the PDF via the recent activity, the document ID is included as the last element:

```
http://localhost:8080/p/234/annotate/1234
```

That causes the relative path for the iframe's `index.html` to be calculated wrong in the second case...

*correct*
![Screenshot 2021-08-03 at 16 26 20](https://user-images.githubusercontent.com/1410238/128034406-07f983c9-837b-4226-80dd-53142ece2b29.png)

*wrong*
![Screenshot 2021-08-03 at 16 26 40](https://user-images.githubusercontent.com/1410238/128034428-4509d053-0e6d-4148-b3ae-b9a7f44fb3ad.png)
