### ISSUE TITLE
Collect project corpus statistics

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#2455]
**Is your feature request related to a problem? Please describe.**
I want to see statistics about my corpus. This should be on document level and aggregated for the whole project. Interesting would be e.g.

**Describe the solution you'd like**

Per document:
- Number of tokens
- Number of sentences
- Number of annotations per layer
- Number of annotations per layer grouped by feature value

For these, min/max/median/five-number summary/average/standard deviation would be nice

Then aggregate them to project level.

-----

Other ideas:

- Number of tokens per sentence
- Number of annotations per sentence

**Comment by jcklie** [comment]
I talked with Richard and we came to the conclusion that the way is not going to collect statistics over UIMA, but via the search that has already indexed the annotations. There is a description in [here](https://textexploration.github.io/mtas/search_component_stats_tokens.html) .

An example in how to do that in code is [here](https://textexploration.github.io/mtas/installation_lucene.html] *Advanced search**. We use Lucene in INCEpTION, not SOLR. The goal is to have a function in the search service similar to `query` called `queryStatistics` that gets not the query results, but the statistics of them.

I would do the following: 

1. Copy the test function from  `de.tudarmstadt.ukp.inception.search.index.mtas.MtasDocumentIndexTest.testAnnotationQuery()`and call it something like `testAnnotationQueryStatistics`
2. To get started. add a function to the search service called something like `getTokenPerDocumentStatistics` and implement it like the query method, you need to plumb it/create copies of functions all the way until you reach the `MtasDocumentIndex ` where the query is actually executed.
3. Then you can use the lucene code above to get the statistics from the Lucene `ComponentToken` .

When that works, you can try to add another method to the search service for other statistics. Once you get a feel for how it works, you can try to unify it into one `queryStatistics` method.

@reckart Did I understand it correctly?

**Comment by reckart** [comment]
Sounds good. And open a PR and commit frequently so we can keep in touch about the approaches taken.

**Comment by xegulon** [comment]
Having the live statistics as we annotate would be great.
For example, I'm annotating sentences for a classifier, and I would like to have the numbers and proportions of the different classes in my dataset, as I annotate.
