### ISSUE TITLE
Missing commands in Admin docs

### ISSUE THREAD

**Issue by xegulon** [inception-project/inception#2463]
![image](https://user-images.githubusercontent.com/74178038/124779471-1b130900-df42-11eb-8064-0b0b3537d4ac.png)
In the docker-compose Admin docs, the commands to set username/password aren't visible.

**Comment by jcklie** [comment]
From what I remember, the docker compose itself does all of this. Does it work when you just set the password in the compose and then start? If yes, then I would just remove that passage from the documentation.

**Comment by xegulon** [comment]
You mean I have to set the password, etc. in the `.yml` file?

**Comment by jcklie** [comment]
The default is inception:inception:

      - MYSQL_USER=${DBUSER:-inception}
      - MYSQL_PASSWORD=${DBPASSWORD:-inception}

That is the part with the`:-`. You can specify the username and password either by overriding the default or better in an .env file that is put next to the docker-compose.yaml

*.env*
```
DBUSER=inception_db
DBPASSWORD=my_secure_password
```

You can override in the `.env` all the variables in the compose

I will update the documentation

```
/srv/inception-demo$ ls -lha
total 60K
drwxr-xr-x 7 root root 4.0K Jun 19 09:58 .
drwxr-xr-x 3 root root 4.0K Dec 20  2019 ..
-rw-r--r-- 1 root root 1.6K Dec  9  2020 docker-compose.yml
-rw-r--r-- 1 root root  130 Jun 19 09:58 .env
```
