### ISSUE TITLE
pattern for text tokenization in INCEpTION

### ISSUE THREAD

**Issue by maiiabocharova** [inception-project/inception#2464]
Can you please consult me what is the pattern for text tokenization in INCEpTION (maybe you can give me a link to regular expression which is splitting the text into tokens)? I want to be able to tokenize my PDF the same was it was done by INCEpTION for model inference

**Comment by reckart** [comment]
We have a section on that in the FAQ in the users documentation: https://inception-project.github.io/releases/0.19.7/docs/user-guide.html#_what_tokenization_does_inception_use
