### ISSUE TITLE
Search Delete of Stacked Annotations

### ISSUE THREAD

**Issue by antonyscerri** [inception-project/inception#2467]
**Describe the bug**
If you have multiple annotations in the same layer with a different value attribute covering the same span of text, so stacked. You are able to search for the individual ones using the value feature. However if you try to then delete them it depends on their stacked order whether it will work or not, the one at the bottom seems to be the one you can delete (which corresponds to the first added to the document).  

**To Reproduce**
1. Open a project with a Named Entity layer, with a value feature and corresponding tagset with multiple values
2.Open a document, find a span of text without any annotations, to keep it simple you may want a single document and/or unique string
3. Create an annotation over the chosen span, and select your first value feature tag
4. Create a second annotation over the same chosen span, and select your second value feature tag
5. Run a search for the given phrase and the second value feature tag, and confirm you get the hit (note it is unnecessary to match on the layer feature value as the following steps only consider the matching spans as the hit and not the specific elements in the query).
6. Click the corresponding annotation marker (for the second value feature tag)
7. Click the delete button, nothing should happen
8. Repeat 5-7 using the first value feature tag and this time the annotation should get deleted.

**Expected behavior**
You should be able to delete the matched annotation as per the selected one when there are multiple annotations at the same location. This is assuming as noted above the query hits used for the selection only consider the span locations and not what else was used in the query wrt to matching any annotation, that relies solely on the selected annotation. 

**Please complete the following information:**
 - Version and build ID: 0.19.3 (2021-04-25 09:58:11, build 238b0e91)

**Comment by antonyscerri** [comment]
I believe the cause may lie with:
https://github.com/inception-project/inception/blob/f3bed56c384d1fbded0a8d50d2eb46279ee23a68/inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.java#L642

It appears to be selecting the first only matching annotation.

**Comment by reckart** [comment]
Yep, looks like - are you interested to submit a PR and in a position that would allow you doing so?

**Comment by antonyscerri** [comment]
Possibly, i haven't checked out the project development guidelines but just looking over the code it didnt appear there were necessarily test coverage for everything so i'm not sure how much that would entail (the fix itself should be fairly minimal). The main focus right now was completing an annotation exercise but having encountered these issues pinning down the cause let me look into immediate work arounds where possible whilst remaining on the current stable release. I'll have a look this weekend at the dev guidelines and see about a PR.

**Comment by reckart** [comment]
We don't have strict rules so far on PRs necessarily needing tests - they are welcome of course, but we know well that a good amount of the code is hard to test - in particular code that is in the UI layer. As we go along, the strategy is that we'll factor out logic from the UI layer into the service classes so it becomes easier to test. But we don't expect contributors to do such work.

**Comment by antonyscerri** [comment]
Ok had a go at a PR. I realised a similar loop was probably necessary in the create button path, see PR for a bit more detail.

**Comment by reckart** [comment]
Merged PR
