### ISSUE TITLE
Load an xmi file with recomendations

### ISSUE THREAD

**Issue by david-waterworth** [inception-project/inception#2481]
**Is your feature request related to a problem? Please describe.**
I'm experimenting with a preprocessor pipeline that adds annotations to a file before I load it into inception. It's basically a recommender but at this stage at least it's easier to experiment if I could generate the annotations, load the file into inception and then check if they're current and accept/reject them.

I tried to add a feature `inception_internal_predicted` to my layer, replicating the code in the external recommenders repo. However this doesn't work, when the file is loaded into inception this feature is ignored. I would imagine it's only tested when you actually receive a document back from a proper recommender.

I'm wondering if you can think of a way I can add "tentative" recommendations to a document.

**Comment by david-waterworth** [comment]
If I'm correct it seems that https://github.com/inception-project/inception/issues/2471 should allow me to do this, i.e. I can post the document and then add recommendations via the API?

**Comment by reckart** [comment]
You could implement an [external recommender](https://github.com/inception-project/inception-external-recommender). Normally, an external recommender would process the text using some ML tool and then return the predictions as suggestions to INCEpTION. But you could probably also instead load a "canned prediction" from your XMI file and return that instead.

**Comment by david-waterworth** [comment]
Yes I've created recommenders before, I'll give that a go. I really only want to run the rules on my document once (I'm investigating rules based labelling and I want to visualise what the rules are doing).
