### ISSUE TITLE
String Matcher Activation

### ISSUE THREAD

**Issue by david-waterworth** [inception-project/inception#2484]
Using version 0.20-rc-5, the string matcher recommender doesn't appear to activate when you select the option "Always Active (no evaluation)". It only seems to work if you set this to false, and set the threshold to 0.0

When I do this I see the log message:

> Jul 16 13:27:51 home-ubuntu-ml inception.jar[1647125]: 2021-07-16 13:27:51 INFO [admin] SelectionTask - [admin][[BMS Named Entity@value] String Matcher]: Activated (0.02346757477050637 >= threshold 0.0)

Also similar to my previous report, when a matcher is disabled the sidebar doesn't show helpful info such as accuracy. In particular, for the string matcher, the option to download the "model" (ie the gazetteer records) isn't available.

**Comment by reckart** [comment]
If a recommender is not active, then the full prediction model is not trained, hence also not available for download. Note that the model for download is not the same one as the one that is used for calculating the eval scores. The model for download which is used also for prediction has been trained on all data. The model used for evaluation has been trained and evaluated on a train/test split.

**Comment by reckart** [comment]
If a recommender is set to "Always Active (no evaluation)", then (as advertised) no evaluation is performed. Hence, no evaluation results are visible in the sidebar. If you want a recommender to be always active but still evaluated, then setting the threshold to 0 is the correct approach.
