### ISSUE TITLE
Exceptions during task selection and accept best

### ISSUE THREAD

**Issue by david-waterworth** [inception-project/inception#2497]
My recommender suddenly stopped providing recommendations, retraining etc didn't help. I restarted the service and then noticed in the log:

> inception.jar[1647125]: 2021-07-15 13:09:52 INFO [admin] SelectionTask - [admin][[Custom Named Entity@value] Multi-Token Sequence Classifier (OpenNLP NER)]: Not activated (0.7135417217943837 < threshold 0.8999999761581421)

Followed by an exception - I'm not sure if they're related. In any case when the F1-score dropped below the threshold, the sidebar stopped providing any useful information. It would be helpful if I still had access to the confusion matrix, that way I'd know that the recommender accuracy was in fact below the threshold.

I'm running INCEpTION 0.20.0-rc-5

> Jul 15 13:09:52 home-ubuntu-ml inception.jar[1647125]: 2021-07-15 13:09:52 ERROR [admin] SelectionTask - [admin][[Custom Named Entity@value] Multi-Token Sequence Classifier (OpenNLP NER)]: Failed
> Jul 15 13:09:52 home-ubuntu-ml inception.jar[1647125]: java.util.IllegalFormatConversionException: d != java.lang.Double
> Jul 15 13:09:52 home-ubuntu-ml inception.jar[1647125]:         at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4426) ~[?:?]
> Jul 15 13:09:52 home-ubuntu-ml inception.jar[1647125]:         at java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:2938) ~[?:?]
> Jul 15 13:09:52 home-ubuntu-ml inception.jar[1647125]:         at java.util.Formatter$FormatSpecifier.print(Formatter.java:2892) ~[?:?]
> Jul 15 13:09:52 home-ubuntu-ml inception.jar[1647125]:         at java.util.Formatter.format(Formatter.java:2673) ~[?:?]
> Jul 15 13:09:52 home-ubuntu-ml inception.jar[1647125]:         at java.util.Formatter.format(Formatter.java:2609) ~[?:?]
> Jul 15 13:09:52 home-ubuntu-ml inception.jar[1647125]:         at java.lang.String.format(String.java:2897) ~[?:?]
> Jul 15 13:09:52 home-ubuntu-ml inception.jar[1647125]:         at de.tudarmstadt.ukp.clarin.webanno.support.logging.LogMessage.<init>(LogMessage.java:49) ~[inception-support-0.20.0-rc-5.jar!/:?]
> Jul 15 13:09:52 home-ubuntu-ml inception.jar[1647125]:         at de.tudarmstadt.ukp.clarin.webanno.support.logging.LogMessage.info(LogMessage.java:75) ~[inception-support-0.20.0-rc-5.jar!/:?]
> Jul 15 13:09:52 home-ubuntu-ml inception.jar[1647125]:         at de.tudarmstadt.ukp.inception.recommendation.tasks.SelectionTask.execute(SelectionTask.java:230) [inception-recommendation-0.20.0-rc-5.jar!/:?]
> Jul 15 13:09:52 home-ubuntu-ml inception.jar[1647125]:         at de.tudarmstadt.ukp.inception.scheduling.Task.run(Task.java:110) [inception-scheduling-0.20.0-rc-5.jar!/:?]
> Jul 15 13:09:52 home-ubuntu-ml inception.jar[1647125]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
> Jul 15 13:09:52 home-ubuntu-ml inception.jar[1647125]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
> Jul 15 13:09:52 home-ubuntu-ml inception.jar[1647125]:         at java.lang.Thread.run(Thread.java:829) [?:?]
>

**Comment by reckart** [comment]
The format conversion problem has been fixed in 6b34395c75b5b7c359491500d3ea74c703e10eca as part of #2319
