### ISSUE TITLE
Include layer and value names in XMI export

### ISSUE THREAD

**Issue by shaunss** [inception-project/inception#2501]
Currently internal layer and value names are set when the project is created. If these names are changed the user interface shows these changed names, but exported files (e.g. UIMA CAS XMI or UIMA CAS JSON) still retain the original names.
This means projects have to keep track of name changes and need to manually replace possibly changed layer and/or value names in exported texts.

Ideally Inception would propagate name changes in the UI directly to the stored data (and the "logged_event" and possibly other tables in the SQL database). If this is not possible or too complex or error prone, an alternative solution would be to at least offer an option to adjust the names in the exported files so that they match the current names in the UI. (Even if this would probably mean that exported files with this option cannot be reimported into the same project.)

An even easier solution would possibly be to ALSO include the name that is visible in the UI in the export and to not ONLY include the Inception internal name, so basicaly to export "uiName" from table "annotation_type" in addition to "name" from the same table.

**Comment by reckart** [comment]
It might be possible to add some "annotations" which map the technical name to the UI name like:

```
<inception:type-mapping type="...MyType" uiName="My type"/> 
```

Would only work for XMI export though. Would that be useful?

**Comment by shaunss** [comment]
Yes, I think this would be very helpful.
