### ISSUE TITLE
Can't remotely download annotations in TSV format

### ISSUE THREAD

**Issue by ofersabo** [inception-project/inception#2510]
Hi,
I'm trying to download the annotated documents through the pycaprio package in the standard TSV format. 
Trying to download it, I get this errors:
b'{"messages":[{"level":"ERROR","message":"Format [tsv] is not writable. Acceptable formats are [bin, conll2000, conll2002, conll2003, conll2006, conll2009, conll2012, conllcorenlp, conllu, ctsv3, dkpro-core-tei, dkpro-core-uima-inline-xml, json, lif, nif, tcf, text, xmi, xmi-xml1.1]."}]}'

Has something changed in the acceptable formats? 

This happens in all documents.

when trying this code:
annotation_content = client.api.annotation(row['project_id'], row['document_id'], row['annotator'],
                                           annotation_format='tsv')

This error gets back:
b'{"messages":[{"level":"ERROR","message":"Format [tsv] is not writable. Acceptable formats are [bin, conll2000, conll2002, conll2003, conll2006, conll2009, conll2012, conllcorenlp, conllu, ctsv3, dkpro-core-tei, dkpro-core-uima-inline-xml, json, lif, nif, tcf, text, xmi, xmi-xml1.1]."}]}'

**Please complete the following information:**
 -  INCEpTION -- 0.19.7 (2021-06-19 00:45:41, build 53edf712)
 - Linux

**Additional context**
All of these documents were imported from INCEpTION projects in versions 0.17.3

**Comment by reckart** [comment]
`tsv` has not been a valid format for a very long time. The behavior was that if an unsupported format was requested, the exporter automatically fell back to `ctsv3`. But this was also a bit confusing since people thought they provided a valid format ID and got back what they expected most of the time but they were actually hitting default behavior. So the behavior was changed to not fall back to a default format if an invalid format specifier was given and instead provide a useful error message. The format ID you are looking for is `ctsv3`.

**Comment by ofersabo** [comment]
Thanks for the quick reply.

So downloading ctsv3 format in 0.19.7 is identical to the TSV in 0.17.3? 
Alsi, if TSV is not supported anymore why does the web tool suggest downloading annotations in TSV format?

**Comment by reckart** [comment]
* `tsv` is WebAnno TSV v1 - it is supported read-only to allow importing very very old WebAnno projects.
* `ctsv` is WebAnno TSV v2 - it supported read-only to allow importing very old WebAnno projects.
* `ctsv3` is WebAnno TSV v3.x - it allows importing WebAnno TSV 3.0, 3.1, 3.2 and 3.3, but only exports TSV 3.3

However, all of these are internal IDs that are basically only used in the DB and in the remote API. In the UI and documentation, they should never be called `TSV` but rather `WebAnno TSV vX.Y`.

Where does the tool suggest to download TSV?

**Comment by ofersabo** [comment]
OK, thanks for the informed answer.
The tool suggests WebAnno TSV vX.Y, which I previously interpreted as TSV.
