### ISSUE TITLE
Keyboard shortcut for jumping between annotations

### ISSUE THREAD

**Issue by annefried** [inception-project/inception#2513]
**Is your feature request related to a problem? Please describe.**
It is often useful to simply pre-mark annotation spans and upload these annotations for correction / validation. This certainly has overlaps with the recommender facility, but is nevertheless a common scenario. At the moment, annotators have to click the pre-marked spans before labeling them.

**Describe the solution you'd like**
A keyboard shortcut should be definable to automatically selecting the next / previous annotation on the same layer (including relations/links attached to the layer).

**Describe alternatives you've considered**
Implemented this feature in the unfortunately discontinued Swan project ;)

**Comment by reckart** [comment]
@annefried The PR introduces two buttons in the right sidebar to navigate between annotations on the same layer as the currently selected annotation. These buttons have keyboard bindings (shift left/right). Works for spans and relations. Note that the order depends on the usual internal sort order (begin increasing, end decreasing) and may not coincide with the position of the labels on screen. In particular for relations, navigating to the next relation may cause the focus to actually move to the left of its current position and vice versa. Links/relations are on different layers - they are not considered in the navigation. The two requirements "on the same layer" and "follow links/relations" are contradictory in this case. I think a better keyboard-based navigation would be better to implement more on the browser/JS side maybe in a visualizer that is not brat-based.
