### ISSUE TITLE
Allow for arbitrary Elasticsearch mapping

### ISSUE THREAD

**Issue by mdgilene** [inception-project/inception#2516]
**Is your feature request related to a problem? Please describe.**
Currently the Elasticsearch external provider requires a rather specific index mapping. This isn't very flexible for those who wish to use Inception with an existing index.

**Describe the solution you'd like**
Allow the user to specific exact keys for the text field and all metadata fields in a way that doesn't assume the presence of a "metadata" and "doc" field.

**Describe alternatives you've considered**
I could just implement my own provider, but it would essentially just be a more flexible version of the one that exists now. Also trying not to fork this if I don't have to.

**Comment by reckart** [comment]
You could propose an extension of the existing provider and offer it as a PR.

**Comment by reckart** [comment]
"Arbitrary" can become arbitrarily complex because it would probably not be sufficient to support simple field names but rather field paths...

**Comment by reckart** [comment]
ElasticSearch support has been frozen due to the EL license change.

**Comment by reckart** [comment]
OpenSearch support coming in v25. If the issue persists and a good idea how to implement it is available, please open a new issue and describe it.
