### ISSUE TITLE
Manual triggering for training

### ISSUE THREAD

**Issue by matchlesswei** [inception-project/inception#252]
During an Active Learning session, instead of automatically training after every individual suggestion, let the user be presented with a series of suggestions, and to manually decide when the training should be done.

**Comment by reckart** [comment]
Why would it be desirable that the user manually triggers the re-training process?

**Comment by matchlesswei** [comment]
It is an issue in gitlab, collected from the Sig-user meeting.
https://git.ukp.informatik.tu-darmstadt.de/inception/inception-application/issues/92

**Comment by reckart** [comment]
I think this is not adding any value at the moment. Before implementing please let us discuss what the benefit is.

**Comment by reckart** [comment]
Closing this as won't fix as this feature doesn't add any benefit I can see over the fully-automatic AL. The user shouldn't have to worry about when learning happens etc.
