### ISSUE TITLE
Add word conversion colab notebook

### ISSUE THREAD

**Issue by UWinch** [inception-project/inception#2534]
**Is your feature request related to a problem? Please describe.**
Add an example of converting .docx files with comments as annotations to UIMA CAS Xmi, so they can be imported into INCEpTION.

**Comment by reckart** [comment]
How about we add a default layer "Comment" in INCEpTION with a multi-line string feature - and then use that in the example?

**Comment by UWinch** [comment]
I would like to tell people that in general, they need to first configure their custom layer. Using a default layer comment to which the comments are mapped might trick people into thinking the layers are automatically generated from the input document.

I would not mind adding a default comments layer independent from this issue though.
