### ISSUE TITLE
Sometimes success feedback is squashed

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#2568]
Sometimes success feedback is squashed (e.g. after importing project).

Originally reported in https://github.com/inception-project/inception/issues/2475

**Comment by reckart** [comment]
@UWinch can you describe this in more detail or provide a screenshot? I have made a few fixes to the feedback panel for Bootstrap 5 - maybe the issue is resolved now.

**Comment by UWinch** [comment]
Looks good now, could no longer reproduce.
