### ISSUE TITLE
Canceling import does not do anything

### ISSUE THREAD

**Issue by UWinch** [inception-project/inception#2580]
**Describe the bug**
Clicking on the `x` when importing a project into INCEpTION does not do anything.

**To Reproduce**
1. Go to the projects overview
2. Click on Import
3. Select a file from your disk
4. Click the `x` to cancel
5. Nothing happens

Should also check if canceling an ongoing import is possible i.e. import a larger project, after 3. click import and then the `x` (have not checked at this time).

**Expected behavior**
Canceling the import should clear the selected file from the input field.

**Please complete the following information:**
 - Version and build ID: 20.3
 - OS: linux
 - Browser: chrome

**Comment by reckart** [comment]
Actually, the "x" button shouldn't be visible at all. The reason why it is visible is that the `display` property of the Bootstrap 5 button class accidentally overrides the `display: none` from the `kv-hidden` class. The fix in this case is to ensure that the `kv-hidden` class wins.
