### ISSUE TITLE
Correcting annotations

### ISSUE THREAD

**Issue by janmatti** [inception-project/inception#2600]
**Is your feature request related to a problem? Please describe.**
We work with student assistants who annotate large numbers of documents. Sometimes they make mistakes, and I (and my colleagues) cannot easily correct these mistakes without logging into INCEpTION with their respective account.

**Describe the solution you'd like**
We would really love to have a functionality that allows administrators to easily change, add, or delete annotations made by annotators.

**Describe alternatives you've considered**
We have tried to use the curation function for this, but this is cumbersome, because then every annotation has to be clicked individually, even though most annotations are correct. Another problem with using the curation function for this is that documents need to be finished, whereas we usually keep documents open in case annotators need to go back to correct annotations.

**Additional context**

**Comment by jcklie** [comment]
Why do you need to click every annotation? We have pre-merging which should import all non-conflicting annotations already in the curation document.

**Comment by janmatti** [comment]
True, I just saw that for some documents with annotation from only one annotator, the annotations are imported into the curated document. I must have missed this or it is a relatively new addition. In any case, I think we would be able to do without the new feature then. However, I have just noticed a problem:

 

In the case of this document, when trying to open it in curation mode, I get the message: “Error: null”.

 

For other documents with this combination of status, it works fine. Do you have a tip what could be going wrong here? 

Thanks!

Jan

 

 

 

Why do you need to click every annotation? We have pre-merging which should import all non-conflicting annotations already in the curation document.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by reckart** [comment]
In which version of INCEpTION do you observe the "Null" error?

Btw. by default, the auto-merge only merges annotations if **all annotators agree**. That means if annotator A marks a word but annotator B does not mark the word, then there is **no agreement**.

If you want to auto-merge all annotators where the annotators do **not disagree**, then you can use the "remerge" dialog on the curation page and check the box **Merge incomplete annotations**.  If this box is checked, if annotator A marks a word but annotator B does not mark the word, then there is **no disagreement**, so the annotation is merged.

If you want to accept all annotations of a given layer from a given annotator in the current document, you can right-click on an annotation of that layer in the view of the annotator and then select "Merge all XXX".

**Comment by janmatti** [comment]
The error occurs in version 20.4 (2021-09-12 15:49:05, build ce3c5dc4).

 

The right-click option to “merge all X” is very useful, thanks! It’s also good to know how auto-merge works. 

 

I am, however, struggling to find the “remerge” dialog. When I click curation, the folder opens where I can choose the document I want to curate. Once selected, I get to the page where I curate the document. I don’t not get a chance to tick boxes on either of these pages, but I am probably looking in the wrong place.

 

Thanks!

Jan

 

In which version of INCEpTION do you observe the "Null" error?

Btw. by default, the auto-merge only merges annotations if all annotators agree. That means if annotator A marks a word but annotator B does not mark the word, then there is no agreement.

If you want to auto-merge all annotators where the annotators do not disagree, then you can use the "remerge" dialog on the curation page and check the box Merge incomplete annotations. If this box is checked, if annotator A marks a word but annotator B does not mark the word, then there is no disagreement, so the annotation is merged.

If you want to accept all annotations of a given layer from a given annotator in the current document, you can right-click on an annotation of that layer in the view of the annotator and then select "Merge all XXX".

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by reckart** [comment]
<img width="940" alt="Screenshot 2021-09-17 at 18 21 15" src="https://user-images.githubusercontent.com/1410238/133821537-b21037bf-7a6f-4453-a58d-23ad8576e48a.png">

Regarding the null error - could it be that your post is missing an image or something? You wrote "However, I have just noticed a problem:", but after the colon follows just an empty space.

**Comment by janmatti** [comment]
Yes, there was a screenshot that showed a document line from the monitoring page. It was a document that had a few locks plus, for one annotator, the “tick” mark plus the “play” button in brackets. But this combination of statuses is the same for other documents that don’t produce the error, so I suppose this is not the reason.

Jan

 

Regarding the null error - could it be that your post is missing an image or something? You wrote "However, I have just noticed a problem:", but after the colon follows just an empty space.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by janmatti** [comment]
Oh, and I just saw the screenshot – thanks so much! Now all should be clear on this front.

Jan

 

Regarding the null error - could it be that your post is missing an image or something? You wrote "However, I have just noticed a problem:", but after the colon follows just an empty space.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by habernal** [comment]
I have one very recent (now quite painful) experience: I needed to fix a few annotations accross ~20 projects, each annotated by a single annotator. So I went to curation, found these documents, fixed the label in curation, and exported the document. But now, only the curated document are exported; if I hadn't done anything with a document in a curation mode, it's not exported under curation. Quite messy, so I have to go to all these projects again, I guess click on "curation finished" on all docs (?), and export... Right? (bottom-line: I'm also definitely in favor of this feature)

**Comment by reckart** [comment]
If you have opened a document in the curation view at least once, then it should be "curation in progress" and it should appear under the "curation" folder in the full export - it shouldn't be necessary to mark them as "curation finished".

Can you please check that all your documents are at least in the state "curation in progress"?
