### ISSUE TITLE
Exported project filename is lowercased

### ISSUE THREAD

**Issue by habernal** [inception-project/inception#2633]
**Describe the bug**
The latest version changed the behavior of naming of the exported files (previously it kept upper-cased letters unchanged). Not sure whether this is intended and if so, why.

**To Reproduce**
1. Go to Project -> Export XMI 1.1 -> check saved file name

**Expected behavior**
Capitals/lower case didn't bother anyone, I guess.

**Please complete the following information:**
 - Version and build ID: 21.0-rc-2 (2021-09-29 12:22:25, build 1421ee71)

**Comment by reckart** [comment]
That's the full project export - yes, the export file now uses the now "project slug". This is a globally (in the instance) unique name and only lower-case characters, numbers, dash and underscore are allowed (must start with a lower-case character). The project name is no longer unique and is generally not used anymore for technical purposes - only for displaying in the UI.

So, it is intended, yes.

**Comment by habernal** [comment]
OK, I see, thanks. Closing.
