### ISSUE TITLE
Refuses to export or open annotations

### ISSUE THREAD

**Issue by DGKore** [inception-project/inception#2634]
Hello,

I've been using Inception to annotate some data. So far, everything went well, but yesterday evening I started having problems. When I click on "annotation" to open and annotate my files, it simply gives me this empty screen: 

![afbeelding](https://user-images.githubusercontent.com/56878355/135402996-fc1f00b3-2fec-485a-8a4d-a845171ecaf5.png)

I can still open my last annotations via "recent activity" on the start page, and use the little arrows to go to the previous or next document:
![afbeelding](https://user-images.githubusercontent.com/56878355/135403459-9e26028c-c8af-4df8-a2ed-4a9dc551bf4b.png)

However, when I try to use the "open document" icon on the left, it simply does not do anything. 
Besides this, I am also no longer able to export my annotated files:

![afbeelding](https://user-images.githubusercontent.com/56878355/135403645-0ad8617b-1a15-4e06-ade3-432f8278dac1.png)

Any help would be very welcome, because I am on a deadline that is rapidly coming closer. 

Thank you in advance!

**Comment by jcklie** [comment]
What version are you using and can you post the INCEpTION log file? It is either in the console you started INCEpTION with, the systemd log or you can access it via the tray icon if you run INCEpTION on the desktop.

**Comment by DGKore** [comment]
I assume this is the version information: 0.19.6 (2021-06-08 16:59:33, build 36a1032b. ) 
But I am not sure where I can find this "log file"? I use INCEpTION via my university server in Firefox.

**Comment by reckart** [comment]
Timeout waiting for idle object sounds like the CAS cache has some issue - but I do not have an idea at the moment why/how this could happen. Restarting the app should return the cache into a sane state. Maybe restart and then try exporting again?

**Comment by DGKore** [comment]
@reckart Thank you for your reply! 
Unfortunately that does not seeem to help. I've logged out and in again, have restarted my browser, tried it in a different browser (Chrome), with or without my university VPN on, restarted my computer - but nothing seems to work...

**Comment by reckart** [comment]
I mean restarting the server - i.e. the computer at the university.

**Comment by reckart** [comment]
@DGKore any updates?

**Comment by reckart** [comment]
Assuming the that issue was resolved as there was no more feedback and thus closing the issue.
