### ISSUE TITLE
Unable to render: null

### ISSUE THREAD

**Issue by habernal** [inception-project/inception#2635]
**Describe the bug**

![screenshot_2021-09-30_12-16-46](https://user-images.githubusercontent.com/11850778/135437495-dbbbece4-fc8d-4259-a0d3-1e1bd14b728d.png)

Javascript console log is empty.

**To Reproduce**
Curation mode, select some paragraphs, but I haven't found any pattern of that error.

**Please complete the following information:**
 - Version and build ID: 21.0-rc-2 (2021-09-29 12:22:25, build 1421ee71) 
 - OS: Ubuntu
 - Browser: Firefox 92.0

**Comment by reckart** [comment]
This is most likely a duplicate of https://github.com/inception-project/inception/issues/2601

**Comment by reckart** [comment]
The problem seems to happen when there a partially visible span annotation is being rendered. The renderer supports partially-visible annotations these days, but the diff algorithm does not consider them - it only looks at the annotations that are fully contained in the visible window.
