### ISSUE TITLE
Error 400 after login (21.0.1)

### ISSUE THREAD

**Issue by shaunss** [inception-project/inception#2649]
**Describe the bug**
After an upgrade to version 21.0.1. inception runs, but after logging in I receive the following error message:
Status: 400 Bad request
Servlet: dispatcherServlet
Request path: /inception/login.html
Message: Origin does not correspond to request

**Screenshots**
![InceptinonScreenshot](https://user-images.githubusercontent.com/4353944/136986637-c08ac0fe-a9bb-46be-b4f0-fac06c8be30e.png)

**Please complete the following information:**
 - Version and build ID: 20.0.1, build db19cae9
 - OS: Ubuntu 20.04
 - Browser: Firefox
 - Inception running behind a nginx reverse proxy with https

**Additional context**
After downgrading to 20.4 everything works again

**Comment by stbachinger** [comment]
Is there any other fix apart from turning off CSRF protection? I am getting this error: 
<html><body>
<html><body>


Status | 400 Bad Request
-- | --
Servlet | dispatcherServlet
Request path | /login.html
Message | Origin does not correspond to request
Application version | 22.5 (2022-03-12 19:54:59, build a81eecf0)
Java Version | Ubuntu 11.0.14
Operation system | Linux 5.13.0-35-generic amd64


</body>
</html>
Thanks in advance!

**Comment by reckart** [comment]
Yes, configuring it according to your setup. We have meanwhile updated the documentation with relevant information, please have a look:

https://inception-project.github.io/releases/22.6/docs/admin-guide.html#_csrf_protection

**Comment by stbachinger** [comment]
Thank you for the fast answer. Unfortunately, this is not working for me. Do I need to take any further steps after updating the settings file?

**Comment by reckart** [comment]
After updating the settings file, INCEpTION needs to be restarted.

If you continue having issues, I assume you are running behind a reverse proxy. The reverse proxy config is a tricky one as different settings need to be make correctly to interplay with each other. Try reviewing your setup and comparing it with the example Apache HTTPD or nginx setups given in the documentation.

For a detailed investigation, it would be possible to supply a custom logging configuration to INCEpTION and increasing log levels for the web layer. You might find helpful information in this thread on the mailing list: https://groups.google.com/g/inception-users/c/wFAJb-cUJ_I

**Comment by stbachinger** [comment]
Okay,  I did restart Inception everytime and your assumption is correct.
I will take a look at the resources you sent. Thank you so much!
