### ISSUE TITLE
Make tagset default closed

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#2672]
**Is your feature request related to a problem? Please describe.**
Tagsets are open by default which is a bit surprising, as the idea behind a tagset is normally that you do not want annotators to add things.

**Describe the solution you'd like**
Make tagset default closed

**Comment by reckart** [comment]
Wether a feature is linked to a tagset also controls whether it shows as a combobox or as a simple text field. For example the quick "span/relation" project template associates an open emtpy tagset with the value feature of the span and relation layer. Thus, when the user fills in a new tag value on the annotation screen, then it will be available on the next annotation in the dropdown.
