### ISSUE TITLE
Supported db drivers

### ISSUE THREAD

**Issue by Giovani-Merlin** [inception-project/inception#2681]
We use a redshift database on our cluster, to connect to it with python we use the driver postgresql+psycopg2. Trying to use our DB I configured settings.properties to use the config 
```
# as described here https://www.postgresql.org/docs/7.4/jdbc-use.html )
database.driver=org.postgresql.Driver 
database.url=jdbc:postgresql://postgresql.default:5432/acm?
useSSL=false&serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8
database.username=admin
database.password=admin
``` 
but I receive the error:
"Cannot load driver class: org.postgresql.Driver". I just would like to know which drivers are supported by Inception (maybe only mariaDB?)

**Comment by reckart** [comment]
Interesting and odd. The `db` folder and whatever other database you configure INCEpTION with should not have anything to do with each other. INCEpTION is killed in an inappropriate moment during startup, the lock can remain in the database that is used at that point. So if the default HSQLDB is used at the point, the lock would end up in the `db` folder. But if MariaDB/MySQL or something else would be used, then the lock would end up there.
