### ISSUE TITLE
PoS tags and Dependency tags are crossing into each other visually

### ISSUE THREAD

**Issue by Kentoseth** [inception-project/inception#2686]
### Describe the bug

This issue was anecdotally mentioned in #2685 . I also experienced it previously in #1960 

Basically, the tags above the text are crossing into each other as seen in the screenshot below.

![pic](https://user-images.githubusercontent.com/2989402/140640697-d3ccc8ab-0296-4d8a-af32-ff61a9b1650f.png)

I was asked in #2685 about it, so I am splitting the rendering issue into this bug report.

>  Is it that relation label overlaps with the ADJ annotation?

Yes, this is the issue.

### To Reproduce

1. Download my .gz file containing the Layers and Dependencies 
[ar-layers-tags.tar.gz](https://github.com/inception-project/inception/files/7492068/ar-layers-tags.tar.gz)

2. Download the bismillah.txt file
[bismillah.txt](https://github.com/inception-project/inception/files/7492069/bismillah.txt)

3. Import it all into a project and reproduce the structure using this link: https://corpus.quran.com/treebank.jsp?chapter=1&verse=1

Alternatively:

1. Import the entire project as the .zip file

[zaad_project_2021-11-07.zip](https://github.com/inception-project/inception/files/7492066/zaad_project_2021-11-07.zip)

The output will look like above, with the PoS/Dep annotations overlapping on each other.

### Expected behavior

No overlapping of annotations.

### Screenshots

Please see above.

### Environment

Version and build ID: INCEpTION -- 21.1 (2021-10-19 17:00:50, build 64ba87ab)
Operating system: e.g. Linux
Browser: e.g. FireFox and Brave

**Comment by reckart** [comment]
<img width="336" alt="Screenshot 2022-02-09 at 21 12 00" src="https://user-images.githubusercontent.com/1410238/153460487-9f02be37-bc2b-483c-8dde-57418687a107.png">
