### ISSUE TITLE
New export page does not work over HTTPS

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#2689]
**Describe the bug**
The new export page uses unencrypted WebSocket even when running over HTTPS which means that the browser will actually block the entire active downloads component.

**To Reproduce**
1. Log in to an INCEpTION instance that is using HTTPS
2. Go to the exports page of a project
3. Note that the right sidebar is missing
4. Check the browser console messages

**Expected behavior**
Optimally, INCEpTION should detect when it is being used over HTTPS and in that case offer a WSS URL to the browser.

**Screenshots**

> Mixed Content: The page at 'https://.../inception/p/x001-demo/settings/details?4' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://...:443/inception/ws-endpoint'. This request has been blocked; this endpoint must be available over WSS.

**Please complete the following information:**
 - Version and build ID: 22.0-SNAPSHOT

**Comment by blochs** [comment]
@reckart this has reappeared in 22.1…

**Comment by reckart** [comment]
Did you update you reverse proxy settings for WebSocket?
