### ISSUE TITLE
Active learning deactivates when switching to another sidebar

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#269]
When starting an active learning session in the active learning sidebar, then switching to another sidebar and then switching back to the active learning sidebar, the active learning session is gone.

Look into the RecommendationUserState.
The State is maintained by activeLearningService

**Comment by matchlesswei** [comment]
@reckart, If a user switches to another model of INCEpTION, like the knowledge base, should the user state of active learning sidebar be cleared?

**Comment by matchlesswei** [comment]
For example, if a user moves from AnnotationPage to the WelcomePage, and then goes back to the AnnotationPage. In this case, should the user state of active learning sidebar be cleared? Is there any events to indicate this situation?

**Comment by reckart** [comment]
Yes in such a case the state needs to be cleared. It also needs to be cleared when the user opens a document from a project different from the one in which the al was started. There should be a 'document opened' event. Check the event log in the FB.

**Comment by reckart** [comment]
... I mean in the DB not FB.

**Comment by matchlesswei** [comment]
Thanks!
