### ISSUE TITLE
Perseus treebank XML 2.1 not visible to annotate

### ISSUE THREAD

**Issue by aniseferreira** [inception-project/inception#2692]
**Describe the bug**
When uploading a _Perseus treebank XML file_, the annotations don't appear on the annotation canvas. Just a straight and fine line appear through all the pages. 

**To Reproduce**
1. Go to 'Settings' > Documents > Files to import > Format > Perseus Treebank XML 2.1
2. Upload the XML file 
3. The file is successfully uploaded, however, when under Dashboard > Annotation > choosing the XML file it appears as a continuous and straight line.

**Expected behavior**
A brat visualization of the annotated file on the annotation edition canvas.

**Screenshots**

**Please complete the following information:**
 - Version and build ID: [see bottom of the browser screen] -- 21.1 (2021-10-19 17:00:50, build 64ba87ab) 
 - OS: [X] Monterey 12.01
 - Browser:  chrome, safari, and brave

The last version was showing the XML. file perfectly. It changed when I updated the INception file. Other files, such as. TXT and COLLU (this one of the same annotated files) are perfectly visible under the annotation edition canvas. Only XML Perseus treebank that is not (for me). 

Thanks

**Comment by reckart** [comment]
Thanks for the report. I'll try to see if I can reproduce the issue by downloading the treebank and importing randomly one of the files.

**Comment by reckart** [comment]
Ok, I can reproduce it.
