### ISSUE TITLE
Curation Overview list reset

### ISSUE THREAD

**Issue by gabriel-frickh** [inception-project/inception#2697]
The Curation overview (the where the documents can be seen, indicating the status in brackets, e.g. (ANNOTATION_FINISHED)) sometimes resets.

So far, we have established that it resets often when either (a) a document is opened again for an annotator to re-annotate or (b) when changes to the user roles are being made.

Is this an intended feature, if so, why or is it a (already known) bug?

 - OS: Windows
 - Browser: Firefox, Chrome

**Comment by reckart** [comment]
The status of a document depends on type of workflow management that is being used.

Which version of INCEpTION are you using?

Which workload management did you configure?

**Comment by reckart** [comment]
Closing as there was no further feedback.

**Comment by reckart** [comment]
Might be an issue after all...

**Comment by reckart** [comment]
1) Created a new project
2) Imported a document into the project
3) Added a few annotations to the project as the admin user
4) Marked the document as "finished"
5) Opened the document for curation as the admin user
6) Removed one of the pre-merged annotations from the curation view (to see if manual curation actions are preseved)
7) Marked the curation document as finished
8) Added a new annotation user to the project
9) Opened the workload page and pressed "refresh" to see what happens -> at this point the state of the document was changed back from CURATION_FINISHED to ANNOTATION_IN_PROGRESS. This is indeed unexpected.

**Comment by reckart** [comment]
Specifically, the reset happens when a `RecalculateProjectStateTask` is performed or `de.tudarmstadt.ukp.inception.workload.extension.WorkloadManagerExtension.recalculate(Project)` is otherwise called. A `RecalculateProjectStateTask` is scheduled e.g. when the permissions of a project changes (e.g. when a user is added/removed).
