### ISSUE TITLE
User details form, E-mail address  is always not a valid email address.

### ISSUE THREAD

**Issue by jeanemvista** [inception-project/inception#2699]
**Describe the bug**
in User details form, E-mail address  is always not a valid email address.

**To Reproduce**
1. Go to 'User details'
2. add an valid e-mail address
3. click on save
4. See error : "The value of 'E-mail address' is not a valid email address."

**Please complete the following information:**
 - Version and build ID: 21.1
 - OS: OS X
 - Browser: safari

**Comment by jcklie** [comment]
Do you have an example for an email that is considered invalid?

**Comment by jeanemvista** [comment]
I sorry, it's not a bug. I had invisible special char in copy/past.
