### ISSUE TITLE
Using recommenders for concept features

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#27]
With the recommenders now supporting custom layers and custom features, we are almost in a situation where using recommenders works for concept features as well. The following screenshot was taken with a String-based recommender and the Wine ontology:

![2018-04-09_12-07-35](https://user-images.githubusercontent.com/1410238/38505899-b781371c-3bee-11e8-913f-f530fedd3561.png)

So we already get the recommendations, but they do not use the FeatureSupport to convert the IRI into a human-readable label.

**Comment by rcffc** [comment]
```
Feature labelFeature = aFs.getType().getFeatureByBaseName(feature.getName());
String label = defaultString(fsr.getFeatureSupport(feature).renderFeatureValue(feature, aFs, labelFeature));
```
This is the code from Renderer.getFeatures that you showed me. How can I access an AnnotationFS without a CAS in RecommendationSpanRenderer?

**Comment by reckart** [comment]
Hm. I suppose we might have to introduce a second variant of renderFeatureValue() where the instead of aFS and labelFeature, the actual label value is passed...

**Comment by reckart** [comment]
@rcffc I have made relevant changes in WebAnno and INCEpTION (branch: feature/27-recommend-concept-features). You can now call `renderFeatureValue(AnnotationFeature aFeature, String aLabel)` - no need for a CAS. Please commit further changes you make also to this branch.
