### ISSUE TITLE
Existing Wikidata entity not appearing in linking candidates

### ISSUE THREAD

**Issue by mromanello** [inception-project/inception#2713]
**Describe the bug**
We are doing entity linking annotations against the remote Wikidata SPARQL endpoint (see settings screenshot below). 
We've occasionally stumbled upon the following issue: an entity, known to be in WD, does not appear in the candidate list. Strangely, when browsing the KB this very entity is shown, and the same query string leads to a different number of matches compared to the annotation page. 

**To Reproduce**
1. Open the annotation document `Wecklein1894_0016.xmi`
2. Select the mention "Athena" at line 12
3. Select the field `wikidata_id` in the layer `AjMC Named Entity`
4. Type "Athena" or whitespace
5. The entity [Q37122](http://www.wikidata.org/entity/Q37122) (Athena, goddess of wisdom in Greek mythology) does not appear in the candidate list (43 items found)
6. Now go to the Knowledge Base page
7. Search for "Athena"
8. See that entity [Q37122](http://www.wikidata.org/entity/Q37122) appears and 50 items are found for the same query. Copy pasting the WD concept URI does not work in this case.

**Expected behavior**
I would expect the KB search to behave consistently in the KB and annotation pages.

**Screenshots**
![Screen Shot 2021-11-26 at 09 09 59](https://user-images.githubusercontent.com/310693/143551512-cf85145e-8515-4b82-b37b-54c3f50321b6.png)
![Screen Shot 2021-11-26 at 09 11 00](https://user-images.githubusercontent.com/310693/143551523-e9855f38-8111-4b5c-b93f-fdc85de7ce82.png)
![Screen Shot 2021-11-26 at 09 11 33](https://user-images.githubusercontent.com/310693/143551530-3ad78b02-1ece-44dc-8a6a-4157bfd4de2c.png)

**Please complete the following information:**
 - INCEpTION 20.3 (2021-09-01 20:15:21, build 5ab7297b)

**Additional context**
For the time being we are not bale to upgrade to the latest release version of INCEpTION.

I'm attaching the exported document for reproducibility.
[webanno15093574150223546103export.zip](https://github.com/inception-project/inception/files/7607373/webanno15093574150223546103export.zip)

**Comment by reckart** [comment]
Is your feature set up to accept any type of value?

![Screenshot 2021-11-26 at 09 41 20](https://user-images.githubusercontent.com/1410238/143552116-0b14d7b8-7952-4037-af23-cdf8a707617f.png)

**Comment by mromanello** [comment]
Thanks @reckart Interestingly, when I change it to `any` the issue is solved and I can find the right Athena. But I'm not sure I fully grasp the implications of the different settings value.

**Comment by reckart** [comment]
The thing is that Wikidata is missing RDF triples on various entries. If e.g. an entry is missing any "is-a" triple, then INCEpTION won't recognize it as an instance... so by allowing "any" you remove the filter that INCEpTION applies to limit to instances.

**Comment by mromanello** [comment]
I see, thanks for the explanation. Is `any` already the default value of this setting? If not, perhaps it would make sense? In case, many thanks for your support (as always!). cheers

**Comment by reckart** [comment]
I think it is not the default but you are right - it might be a good idea to change it.
