### ISSUE TITLE
Document websocket reverse proxy config

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#2735]
**Is your feature request related to a problem? Please describe.**
We now use websocket, which needs special configuration when using a reverse proxy that needs to be documented.

**Describe the solution you'd like**
- [x] Document Apache Vhost config @reckart 
- [x] Document CSRF config with Apache @reckart 
- [x] Document nginx config @jcklie 
- [x] Document CSRF config with Nginx

Maybe then CSRF configs are the same for both.

**Comment by reckart** [comment]
The apache doc stuff is already merged in 68e432fd40c1d1f8b0a1337901042071557e2160

**Comment by reckart** [comment]
I have thrown out the AJP documentation because that doesn't work with Websocket and switch it over to http-proxying.

**Comment by reckart** [comment]
@jcklie Any more updates necessary here? I think we could maybe consider doing a release?
