### ISSUE TITLE
INCEpTION does not work on 32bit Windows

### ISSUE THREAD

**Issue by sundarasekar** [inception-project/inception#2736]
**Describe the bug**
I tried installing Inception on Windows 10 32 bit machine with openjdk and the inception jar file, i don't find any errors while installing openjdk as well as the inception jar file. It has loaded the Inception logo and preparation screen. Also finally shown the open browser and shut down service buttons. I clicked open browser. It has loaded the URL with http://localhost:8080 and ended up with 404 page not found error http://localhost:8080/login.html.

**To Reproduce**
1. Installed openjdk
2. Inception jar

**Expected behavior**
I am not getting login screen.

**Screenshots**

**Please complete the following information:**
 - Version and build ID: [OpenJDK11U-jdk_x86-32_windows_hotspot_11.0.13_8.msi, INCEpTION 21.2 executable JAR]
 - OS: Windows
 - Browser: Chrome

**Additional context**

**Comment by reckart** [comment]
Does the 404 page come up with an INCEpTION-style error page displaying a large "Whoops" header?

**Comment by reckart** [comment]
Ah, here we have it: https://github.com/bit3/jsass

This is the library we use to generate CSS from SCSS and it says there that Windows 32bit is not supported. I am very sorry for this. 

There has been some desire to move away from dynamically generated CSS to generating the CSS at build time. We have not addressed this so far, but I think it is something that is within reach.

**Comment by reckart** [comment]
Note: might well slip the 21.3 milestone - but let's see...

**Comment by sundarasekar** [comment]
Thank you so much.

**Comment by reckart** [comment]
Moving it to 22.0 since that's where all the JS/TS updates are being done and this one here fits in with them.
