### ISSUE TITLE
Imported Ontologies for the current Ontology in KB editor 

### ISSUE THREAD

**Issue by naveen2507** [inception-project/inception#274]
Show the list of imported ontology in KB Editor to support the current ontology with an option of importing them to current KB

Reference (For instance) : Wine Ontology imports Food Ontology 
<owl:imports rdf:resource="http://www.w3.org/TR/2003/PR-owl-guide-20031209/food"/>

![image](https://user-images.githubusercontent.com/10420950/41235855-feb5631a-6d8f-11e8-9d74-7df321deb035.png)

**Comment by reckart** [comment]
It's best to have only one ontology per KB. I don't think we need to support managing multiple ontologies in a single KB.
