### ISSUE TITLE
Support Solr-based external indexes

### ISSUE THREAD

**Issue by betoboullosa** [inception-project/inception#276]
External search must suppor Solr indexes

**Comment by a-tsioh** [comment]
Hi there ! anyone working on this issue ?

**Comment by reckart** [comment]
Note at the moment. Feel free to pick it up ;)

**Comment by a-tsioh** [comment]
Any direction about where to start ?
I feel capable to do so but new to Inception code (I've just been an user up to now, I guess the code from the elasticsearch module is the thing to look at ?)

**Comment by reckart** [comment]
Look at how we integrated support for ElasiticSearch / PubAnnotation and build something similar for Solr.

**Comment by reckart** [comment]
Mind that because of ElasticSearch and MTAS, we are locked to specific versions of Lucene. That also means you probably can't use any version of Solr but only a specific one.

**Comment by a-tsioh** [comment]
Thanks for the info ! I will keep this in mind (I didn't have much time to work on this until now, but we are still planning to give it a try)

**Comment by a-tsioh** [comment]
Hi !
we finally worked on this issue and have some working code on our side. In order to share it with you, do you prefer a pull request that would integrate the module to your codebase (just like the module for elastic search) or another project which would need to be added to the dependencies at compile time ?

**Comment by reckart** [comment]
Having it in the code base would probably be the preferable option. Maybe you can open a PR draft and we can have a look at the proposed contribution?

**Comment by a-tsioh** [comment]
Sure ! We'll try to get this done during the week

**Comment by a-tsioh** [comment]
PR sent !  #1720
