### ISSUE TITLE
Using guest link accounts and real user has some strange interactions

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#2760]
### Describe the bug

Using guest link accounts and real user has some strange interactions.

### To Reproduce

1. Join to a project with a guest link and create a new account for this project
2. Open INCEpTION in another tab and log in with a regular user
3. Open the guest link again and try to join

### Expected behavior

The guest user login should not be activate at the same time as a regular user.

### Screenshots

![image](https://user-images.githubusercontent.com/934600/146565168-6b48e447-3e0a-46c5-8b98-74b94281f531.png)

### Environment

Version and build ID: 21.4
Operating system: Windows
Browser: e.g. Chrome,

**Comment by reckart** [comment]
Actually - if you are logged in as a regular user and use an invite link, then the result should be that this user joins the project as a regular user - not as a guest user.
