### ISSUE TITLE
markdown in project description image 

### ISSUE THREAD

**Issue by jwijffels** [inception-project/inception#2797]
I've made an upgrade from Inception to 0.19.5 to inception 21.5 and noticed images in markdown are not rendered any more.
for example if I add the following markdown at the project at https://morbo.ukp.informatik.tu-darmstadt.de/p/demo-192?4

this renders as follows: 
![image](https://user-images.githubusercontent.com/1710810/148070700-6fb208b3-bdf3-4977-b280-5e08c6d1ae77.png)

```
## Contact

- bij vragen contacteer jan.wijffels@vub.be

![by DIGI](https://digi.research.vub.be/sites/default/files/paddle_core_plugin_data/branding/DIGI%20logo%20files_DIGI%20RGB_DIGI-RGB.png "DIGI")
```

**Comment by jcklie** [comment]
It might be that this breaks due to the cross origin policy
@reckart Did we change something there and how do we deal with it e.g. for the image  sidebar?

**Comment by jwijffels** [comment]
Where would the image have to be placed to refer to it in the description.
If I put logo.png into one of these locations and refer to it in markdown as `![by DIGI](logo.png "DIGI")` that still gives the same error indicating the image is not found.

sudo chown -R www-data:www-data /srv/inception/repository/project/10/logo.png
sudo chown -R www-data:www-data /srv/inception/repository/project/logo.png
sudo chown -R www-data:www-data /srv/inception/repository/logo.png
sudo chown -R www-data:www-data /srv/inception/logo.png

**Comment by jcklie** [comment]
Do you use a reverse proxy? If you use a reverse proxy, then you could let it serve the images under the same domain.

**Comment by jwijffels** [comment]
Yes, it's hosted behind a reverse proxy. 
Let me try server the images under the same domain.

**Comment by reckart** [comment]
Depending on the browser you are using, it may expect the server to provide a CORS header and won't load images from another domain unless these headers are present. So if you serve images from another domain, make sure that the server providing the images sends a CORS header along that allows cross-domain access.

**Comment by jwijffels** [comment]
Are you sure this cors is the issue? (It also happens at your servers at https://morbo.ukp.informatik.tu-darmstadt.de/p/demo-192?4).
My virtual host pretty much looks like this:

```
<VirtualHost *:443>
    ServerName inception.datatailor.be
    ServerAlias datatailor.be 
    ProxyRequests Off
    ProxyPreserveHost Off
    Header add Access-Control-Allow-Origin "*"    
    ProxyPass / http://79.99.203.97:18080/
    ProxyPassReverse / http://79.99.203.97:18080/
    Include /etc/letsencrypt/options-ssl-apache.conf
    SSLCertificateFile /etc/letsencrypt/live/inception.datatailor.be/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/inception.datatailor.be/privkey.pem
</VirtualHost>
```

If I use a file using the same domain (datatailor.be) it still does not render ![by DIGI](https://gitlab.datatailor.be/uploads/-/system/appearance/logo/1/bnosac_logo_met_txt.png "DIGI")

**Comment by reckart** [comment]
Try opening the web developer tools in your browser and check the console messages and the network tab there.

**Comment by jwijffels** [comment]
you are correct it is a CORS issue.
![image](https://user-images.githubusercontent.com/1710810/148102846-a78baa57-458a-4260-8f9e-702f07d7e890.png)

**Comment by jwijffels** [comment]
I'll see if I can host the png image on the same site using the reverse proxy.

**Comment by jwijffels** [comment]
I'll close this as it's clearly a feature, not a bug.

**Comment by jwijffels** [comment]
Thanks for all the help.

Note for my future self. Solved this by not proxying path` /images`, and putting the images in `/var/www/inception/images` and referring them in the project description as` ![by DIGI](../images/logo.png "DIGI")`

```
<VirtualHost *:443>
    ServerName inception.xyz.be
    ServerAlias datatailor.be 
    DocumentRoot "/var/www/inception"
    ProxyRequests Off
    ProxyPreserveHost Off
    ProxyPass /images !
    ProxyPass / http://myip:18080/
    ProxyPassReverse / http://myip:18080/
    Include /etc/letsencrypt/options-ssl-apache.conf
    SSLCertificateFile /etc/letsencrypt/live/inception.xyz.be/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/inception.xyz.be/privkey.pem
</VirtualHost>
```
