### ISSUE TITLE
invitation link behind reverse proxy

### ISSUE THREAD

**Issue by jwijffels** [inception-project/inception#2803]
**Is your feature request related to a problem? Please describe.**
When running inception behind a reverse proxy (e.g. as indicated at https://github.com/inception-project/inception/pull/2800#issuecomment-1005196261), the invitation link shows the name of the proxied server instead of the main url.
It shows 

`http://localhost:18080/p/projectxyz/join-project/aLX85Yg0eZYkrNLrnSpx7w
`
Instead of 

`https://inception.xyz.be/p/projectxyz/join-project/aLX85Yg0eZYkrNLrnSpx7w
`
When changing `http://localhost:18080` with `https://inception.xyz.be`, the invitation link works but it might be better to have this directly in the user interface.

**Describe the solution you'd like**

Maybe add an extra option at https://inception-project.github.io/releases/21.5/docs/admin-guide.html#sect_settings_sharing indicating how to change e.g. http://localhost:18080 to https://inception.xyz.be

**Comment by reckart** [comment]
If the wrong hostname is shown, it could be that the reverse proxy is not set up correctly.

That said, there is an option, it is just not documented:

```
sharing.invites.invite-base-url=https://inception.xyz.be
```

**Comment by jwijffels** [comment]
Thanks for the option. That worked as well but also changed the project name to the project id.
Without sharing.invites.invite-base-url: http://localhost:18080/p/projectxyz/join-project/aLX85Yg0eZYkrNLrnSpx7w
With sharing.invites.invite-base-url: https://inception.xyz.be/p/41/join-project/aLX85Yg0eZYkrNLrnSpx7w

**Comment by reckart** [comment]
Thanks for spotting - that should be an easy fix.

**Comment by jwijffels** [comment]
Thanks!
