### ISSUE TITLE
When not all units fit on screen brat editor scroll position jumps on re-render

### ISSUE THREAD

**Issue by maks1812** [inception-project/inception#2815]
**Describe the bug**
Scroll bar with sentences list  goes up when click on any text/span/relation.

**Expected behavior**
 Sentences list should not move after clicking on text/span/relation.

**Please complete the following information:**
 - Version and build ID:  22.0 ( build 7dee4fca)
 - OS: tried on Windows 10 and Linux
 - Browser:  Chrome
 
**Additional context**
In previous version(21.5) everything works fine.

**Comment by blochs** [comment]
Also seeing this as an issue!

**Comment by reckart** [comment]
On the curation page?

**Comment by blochs** [comment]
Curation/Annotation page. Large documents is where it's most affected.

**Comment by reckart** [comment]
On the annotation page, I'm not aware that we have a sentence list. I only know of a sentence list on the curation page.

**Comment by blochs** [comment]
More of a clicking an annotated item, once you go into edit it, it shoots up the page. I am 100% not explaining this well and can't show you because it's confidential info...

**Comment by blochs** [comment]
If you expand the number of lines on the screen, it's easily identifiable.

**Comment by reckart** [comment]
Ok, we are talking about central editor panel then. Gotcha.

**Comment by blochs** [comment]
It appears so, sorry i'm not hip to the lingo (and are going by what my people tell me) I just admin the thing.

**Comment by reckart** [comment]
No worries ;)

**Comment by blochs** [comment]
@reckart Any thoughts/issues that might come up with a "downgrade" back to 21.5 ?

**Comment by reckart** [comment]
I can see that every time the brat editor re-renders itself, it jumps a little - it seems to be due to the size of the boxes changing - this effect accumulates per row, so it becomes worse the more rows are rendered and the further down the user has scrolled.

**Comment by reckart** [comment]
It doesn't seem to happen consistently. E.g. for a given document, I can see jumping only in particular parts of the document and for particular numbers of visible rows - but going to a different part of the document or changing the number of visible rows can make the problem disappear.

**Comment by reckart** [comment]
Ok, looks like I found a fix for this problem. I'll do a 22.1 release asap.
