### ISSUE TITLE
Change external recommender protocol

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#282]
Instead of sending the type system and the XMI as BASE64-encoded strings wrapped in a JSON, use a multi-part POST request with the following fields:

* **target-type**: fully-qualified name of the UIMA type contain the target feature
* **target-feature**: simple name of the feature which is to be predicted
* **document**: document
* **typesystem**: optional type-system which is used if the document cannot be interpreted alone (e.g. for the XMI format).

The document and typesystem parts should specify a mime type indicating the format that is sent, e.g. `application/vnd.xmi+xml` for XMI.

Cf. https://stackoverflow.com/questions/27231031/set-content-type-of-part-of-multipart-mixed-request-in-curl

**Comment by reckart** [comment]
@horsmann FYI

**Comment by Rentier** [comment]
I was thinking about it and do not see many advantages of this approach. I think JSON is more standard for Web APIs.

**Comment by reckart** [comment]
Multi-part posts are also pretty standard, no? The advantage would be that we do not have to shoehorn XML into JSON which admittedly works but is terribly ugly.

**Comment by Rentier** [comment]
Multi-part posts are standard for e.g. uploading several files, but not for Web APIs. I would rather not surprise developers who are mainly familiar with JSON API requests.

**Comment by Rentier** [comment]
I would like to stay with the JSON, but we could think about supporting also BSON.

**Comment by Rentier** [comment]
We could use HTTP streaming to send around lots of data. The client and server then need to support JSON stream parsing, which is widely available in libraries.

**Comment by reckart** [comment]
@Rentier Not sure what to do with this issue. Is it implemented? Is it outdated? Is it something we still need to do and push to the next release?

**Comment by Rentier** [comment]
We refactored the request a bit in #398 .I  close this. We might open a new issue for HTTP streaming.
