### ISSUE TITLE
Where is annotation info stored

### ISSUE THREAD

**Issue by WilliamQue** [inception-project/inception#2835]
Where is annotation info stored? although it can be exported as xml or CoNll format, I can't find which table in mariadb storing it.

Indeed, I want to add more rows into the table (if existing), then more annotation info will be showed when opening annotation UI , than manual operations.

**Comment by jcklie** [comment]
The annotations are not stored in the database, but as UIMA serialized CAS objects on disk in your .inception folder. The folder itself (see [here](https://inception-project.github.io/releases/22.2/docs/admin-guide.html#sect_home_folder) on how to find it.

**Comment by WilliamQue** [comment]
@jcklie As a common nlp process, annotating docs manually first to get samples, then training samples by some nlp algorithms, after that, perhaps we can find more info that manual annotatation ignored, showing these info in annotation UI and let annotaters to check it,

Loop above process to improve precision of recoginization.

**Comment by jcklie** [comment]
We have recommenders in INCEpTION, is that not what you mean? [Video about Recommender](https://www.youtube.com/watch?v=Xz3Hs8Lyoeg&list=PL5Hz5pttaj96SlXHGRZf8KzlYvpVHIoL-&index=4), [Documentation for Recommenders](https://inception-project.github.io/releases/22.2/docs/user-guide.html#recommenders_in_getting_started). 

You can also export your project via our API, e.g. in Python with [pycaprio](https://pycaprio.readthedocs.io/en/latest/)
