### ISSUE TITLE
When marking a sequence in RTL it marks only the last character 

### ISSUE THREAD

**Issue by shaked571** [inception-project/inception#2837]
When marking a sequence in Hebrew (I guess it would happen in any RTL language)  the annotation marks only the last character 
  
**To Reproduce**
1. Open a new project.
2. Upload an Hebrew document
3. Try to mark a word
4. See only the last character being marked when all the marked text appearing in the text box in the right 

**Expected behavior**
Marking all the marked text.
 
**Screenshots**
![image](https://user-images.githubusercontent.com/19710724/151699706-77f15632-8c38-4843-bcf0-6906f9201e80.png)

 - Version and build ID: inception-app-webapp-22.2-standalone
 - OS: windows
 - Browser: chrome

**Comment by reckart** [comment]
Hm, yes I can see it. Thanks for reporting.

**Comment by reckart** [comment]
This is one of the cases where I scratch my head and wonder "how could this ever have worked..."
