### ISSUE TITLE
recommender allow multiple features

### ISSUE THREAD

**Issue by jwijffels** [inception-project/inception#2858]
**Is your feature request related to a problem? Please describe.**
I've set up an inception project to use a custom recommender. This recommender uses https://github.com/inception-project/inception-external-recommender with something along these lines

```
class MyClassifier(Classifier):
    def __init__(self, model_name: str, model_directory: Path = None):
        super().__init__(model_directory=model_directory)
        self._model = spacy.load(model_name, disable=["parser"])
    def predict(self, cas: Cas, layer: str, feature: str, project_id: str, document_id: str, user_id: str):
        text = cas.sofa_string
        doc = self._model(str(text))
        for named_entity in doc.ents:
            begin = named_entity.start_char
            end = named_entity.end_char
            entity_label = named_entity.label_
            entity_text = named_entity.text
            entity_label = re.sub("_", "-", entity_label)
            AnnotationType = cas.typesystem.get_type(layer)
            ## some other model with logic seeing if we need to predict a subentity or not and next assign it
            has_detail = True
            entity_detail = "ANOTHER_SUBENTITY"
            if has_detail:
              prediction = AnnotationType(begin = begin, end = end, sofa = entity_text, label = entity_label, mydetail = entity_detail, inception_internal_predicted = True)
            else:
              prediction = AnnotationType(begin = begin, end = end, sofa = entity_text, label = entity_label, mydetail = None, inception_internal_predicted = True)
            cas.add(prediction)
        #cas.to_xmi("updated.xmi", pretty_print = True)
```
That updates the cas file, and updates the `label `and `mydetail` features of the specific layer.
When writing down the cas to xmi, I see that the `mydetail` feature is in the xmi file but only the `label` feature is being shown/recommended in the user interface of Inception. Not the `mydetail` feature as in the UI of the recommender I specifically ask to update the Layer and Feature corresponding to 'label'.
Note also that the 'mydetail' feature has a Constraint applied to, which will only make it show up when the label is filled in

```
import custom.Span as Event;

Event {
  label="ABC" -> mydetail="item1" | mydetail="item2";
  label="XYZ" -> item1
}
```

**Describe the solution you'd like**
It would be nice for a recommender which updates 2 features in the cas that it shows these 2 features as being filled in by the recommender, even though they were conditional on a constraint.
When I upload the resulting "updated.xmi" file in the Inception user interface, it does show the 2 recommended features, giving a different behaviour as just when the recommender is applied. Maybe the constraints need to be applied again as well after recommendation.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by reckart** [comment]
When you set up a recommender in the project settings, you configure which layer and feature it recommends. When the external service sends its recommendations back to the server, only the data for the layer/feature that the external recommender is configured for is extracted from the data and used as suggestions. That means, at present, no recommender (not even an external one) can recommend more than one feature at a time. What it can do though, is set an "explanation" feature - that information is then shown in a on-mouse-over-popover on the recommendation in the UI:

```
prediction[f'{feature}_score'] = 0.1234
prediction[f'{feature}_score_explanation'] = "..."
```

**Comment by jwijffels** [comment]
Ok, for my case, I'll call the API twice then each time requesting a different feature while using the same prediction API.
Wasn't aware of the explanation feature, that will be handy for another thing as well.

**Comment by jwijffels** [comment]
Feel free to close, for my case setting up 2 recommenders with the same prediction API worked and updated the 2 recommended features. 
Not sure if a change allowing to have an API which overwrites the whole CAS make sense.

**Comment by reckart** [comment]
At some point it would be good if a recommender could set more than one feature or even multiple layers - but it requires a larger refactoring to support that.
