### ISSUE TITLE
Excessive loading times in curation mode

### ISSUE THREAD

**Issue by janmatti** [inception-project/inception#2875]
**Describe the bug**
When opening the curation mode it takes several minutes for the folder with to-be-curated documents to appear, and after curating and clicking "next", it takes again several minutes for the following document to open. I was assuming that this is because of server overload (we have several thousand documents uploaded).

**To Reproduce**
1. Open any project
2. Go to "curation"

**Expected behavior**
Smooth opening and transition between documents in curation mode.

**Screenshots**

**Please complete the following information:**
 - Version and build ID: 22.4 (2022-02-15 20:51:43, build 4725783b)
 - OS: OS X Big Sur
 - Browser: chrome

**Additional context**

**Comment by reckart** [comment]
Can you briefly say how many annotators and documents you have and what type of workflow mode you are using (static / dynamic)?

**Comment by janmatti** [comment]
We have about 8000 documents over 7 projects and approximately 10 active annotators (22 overall). Workload is static, which is important because we need the annotators to get long, continuous packages of documents, so we assign manually.

 

From: Richard Eckart de Castilho ***@***.***>
Reply to: inception-project/inception ***@***.***>
Date: Thursday, 3. March 2022 at 09:01
To: inception-project/inception ***@***.***>
Cc: janmatti ***@***.***>, Author ***@***.***>
Subject: Re: [inception-project/inception] Excessive loading times in curation mode (Issue #2875)

 

Can you briefly say how many annotators and documents you have and what type of workflow mode you are using (static / dynamic)?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
