### ISSUE TITLE
Document java options e.g. for increasing memory limit

### ISSUE THREAD

**Issue by OleMussmann** [inception-project/inception#2885]
**Is your feature request related to a problem? Please describe.**
Inception application memory is limited to 1923MB, for heavy usage this is not enough. The documentation mentions no approaches to increase this limit.

**Describe the solution you'd like**
Describe the use of java options in the documentation, for local usage or docker containers

Example: to increase available memory to 4GB for docker, add `-Xmx4g` to the `JAVA_OPTS` environment vars in `docker-compose`

    environment:
        - JAVA_OPTS=-Dspring.jpa.properties.hibernate.dialect.storage_engine=innodb -Xmx4g

**Additional context**
Find memory limit in the logs
`INFO [SYSTEM] InceptionApplicationContextInitializer - Max. application memory: 1923MB`

**Comment by reckart** [comment]
@OleMussmann Thanks for the pointer. Would you like to submit a pull request with the updated documentation?

**Comment by OleMussmann** [comment]
I'm happy to do that, @reckart . Are there any other java options important for inception you would like to have included?

**Comment by reckart** [comment]
I don't have any immediately springing to my mind. Most stuff can and should be configured via the `settings.properties`. Just settings that affect the JVM directly need to go into the `JAVA_OPTS` and memory settings seem to be the most relevant here.
