### ISSUE TITLE
Active learning moving to recommendation which no longer exists

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#29]
It can happen that the active learning module takes the user to a recommendation which no longer exists.

![2018-04-09_18-07-42](https://user-images.githubusercontent.com/1410238/38523137-fbc97024-3c20-11e8-8896-75d30cce3b1d.png)

Maybe it would be a good idea to add rendering capabilities to the sidebar so it can ensure that the recommendation it suggests actually is rendered.

**Comment by rcffc** [comment]
@eckart What do you mean with rendering capabilities, and how can they help?

The Active Learning Sidebar has access to the JCas, is it possible to use selectAt to check whether there is actually a recommendation for the type and offset?

**Comment by rcffc** [comment]
@matchlesswei What does `currentDifference` mean?

**Comment by matchlesswei** [comment]
@rcffc it contains two recommendations. These two recommendations have the closest confidence.

**Comment by rcffc** [comment]
Superseded by #369 .
