### ISSUE TITLE
Subclass button looks ugly

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#290]
The "create subclass" button is glued to the "concept" tag and it is too large.

![2018-06-15_12-18-42](https://user-images.githubusercontent.com/1410238/41463324-532f92e0-7096-11e8-966d-76b7d5782edf.png)

I would suggest to move it next to the delete button and to make sure it has the same size as the delete button. There should also be a "+" symbol in the button label as in the other buttons which add something.

**Comment by naveen2507** [comment]
Done
