### ISSUE TITLE
Error when trying to lock documents via bulk change

### ISSUE THREAD

**Issue by janmatti** [inception-project/inception#2949]
### Describe the bug

In monitoring mode, I have been working with bulk change to lock documents for all annotators and then reopen manually to assign specific documents to specific annotators. This now produces the error: "Error: No EntityManager with actual transaction available for current thread - cannot reliably process 'persist' call".

### To Reproduce

1. Go to 'Monitoring'
2. Click on 'Bulk change'
3. Select a row or column
4. Click on 'lock selected' in the bulk change drop down
5. See error

### Expected behavior

Usually, after the action all documents are locked or unlocked for the respective annotator. Manual locking works fine.

### Screenshots

![Screenshot 2022-04-05 at 08 50 40](https://user-images.githubusercontent.com/81179300/161695703-5120dcca-6965-42e5-91db-f32ad0bf8aef.png)

### Environment

Version and build ID: 23.0.1 (2022-04-02 23:20:47, build edf60f9c)
Operating system: OS X
Browser: Chrome

**Comment by reckart** [comment]
Thanks for the report. Will be fixed in 23.1.
