### ISSUE TITLE
Search can't find _all_ tokens of a layer

### ISSUE THREAD

**Issue by OleMussmann** [inception-project/inception#2957]
**Describe the bug**
The documentation states: 

> Thus, the following syntax will return all multi-token annotations of the LayerX layer, regardless of their features and values.
> `<LayerX/>`

A search for `<LayerX/>` fails. Confusingly, searching for features in a given layer _does_ work: `<LayerX.FeatureX="value"/>`

**To Reproduce**
1. Search for an (existing) LayerX: `<LayerX/>`
2. Witness no results
3. Search for an existing FeatureX of LayerX: `<LayerX.FeatureX="value"/>`
4. Find results

**Expected behavior**
I would expect to find all items of LayerX when not searching for Features.

**Please complete the following information:**
 - Version and build ID: docker image "inceptionproject/inception:22.4"
 - OS: Linux
 - Browser: chromium, firefox

**Additional context**
As a limited workaround, one can search for `<LayerX.FeatureX=""/>`, which returns all LayerX elements that have a FeatureX, regardless of value. It does not find elements without FeatureX, though.

**Comment by reckart** [comment]
It seems that the underlying library we use (MTAS) does not support `<LayerX/>` in the way you suggest. However, what seems to work is `<LayerX=".*"/>`.

**Comment by reckart** [comment]
I have opened an upstream issue: https://github.com/textexploration/mtas/issues/13

**Comment by OleMussmann** [comment]
Thanks a lot @reckart . What also work is the shorter notation `<LayerX=""/>` .

**Comment by reckart** [comment]
Maybe it would be possible to process the query before sending it to MTAS and replace `<XXX/>` with `<XXX=""/>`.

**Comment by reckart** [comment]
@OleMussmann on further analysis trying to build a workaround, I actually discovered that it was a bug in INCEpTION after all. Fix incoming.
