### ISSUE TITLE
Inception with MySQL 8 

### ISSUE THREAD

**Issue by WilliamQue** [inception-project/inception#2966]
Today, I switched mariadb to mysql 8 as database of inception, because, you know, mysql 8 is most popular, and 2 databases existing in one machine is confusing. I don't know whether inception with mysql has been tested strictly.

The error occurred when creating a tag for a tagset.

2022-04-10 01:47:24 ERROR [admin] ApplicationPageBase - admin: Error: org.hibernate.exception.SQLGrammarException: could not execute statement
2022-04-10 01:47:24 WARN [admin] SqlExceptionHelper - SQL Error: 1064, SQLState: 42000
2022-04-10 01:47:24 ERROR [admin] SqlExceptionHelper - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'rank, tagset) values (null, 'sales', 0, 2)' at line 1

1. Go to Tagsets page
2. Click on 'save' button beside 'Tagsets details'
3. See error

**Comment by reckart** [comment]
I have been able to reproduce the issue in a Docker Compose setup.

Looks like `rank` is a keyword in MySQL 8...

What worked for me is the following configuration:
* Force the dialect to `org.hibernate.dialect.MySQL8Dialect`
* Force the driver to by the embedded MariaDB driver
* Use a `mysql` JDBC URL
* Force identifiers to be quoted before sending them to the DB because otherwise schema-validation won't find the tables created by Liquibase (which have lower-case names)

```
      - INCEPTION_DB_DIALECT=org.hibernate.dialect.MySQL8Dialect
      - INCEPTION_DB_DRIVER=org.mariadb.jdbc.Driver
      - INCEPTION_DB_URL=jdbc:mysql://db:3306/inception?useSSL=false&useUnicode=true&characterEncoding=UTF-8
      ...
      - JAVA_OPTS=-Dspring.jpa.properties.hibernate.globally_quoted_identifiers=true -Dspring.jpa.properties.hibernate.globally_quoted_identifiers_skip_column_definitions=true
```

If you are using a `settings.properties` file, you can add these lines:

```
database.dialect=org.hibernate.dialect.MySQL8Dialect
database.driver=org.mariadb.jdbc.Driver
#database.url=jdbc:mysql://db:3306/inception?useSSL=false&useUnicode=true&characterEncoding=UTF-8
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.properties.hibernate.globally_quoted_identifiers_skip_column_definitions=true
```

Adjust the JDBC URL accordingly to your system in both cases!

**Comment by WilliamQue** [comment]
@reckart Thank you for your quickly reply every time.

I tested your advice and find it's OK, but the way is alpha one or a release one, please remark it in admin guide document after verion updation.

**Comment by reckart** [comment]
For the time being, it is recommended to run INCEpTION with MariaDB. According to the MariaDB documentation, the MariaDB driver should be compatible with MySQL as well. Depending on the database product and version being used, Hibernate has to be configured with different database dialects (in some cases, Spring Boot can auto-detect the necessary dialect, but not always as we have seen). I have added the `spring.jpa.properties.hibernate.globally_quoted_identifiers=true` as a default setting for INCEpTION 24.x and so far, I see no negative impact. I am adding a note that when using MySQL 8, manually setting the database dialect and database driver in the `settings.properties` may be necessary.
