### ISSUE TITLE
Show IRIs on-mouse-over

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#297]
While the human-readable labels in the UI are much nicer than the IRIs, it is sometimes important for the user to see what the IRI behind a label is. A use-case is if the `label` IRI in the KB settings is not correctly set and the user wants to change it to another property. 

The IRI (identifier) of a property or linked concept/class should be shown in a tooltip on-mouse-over.

This already happens when moving the mouse over the title of a concept/property/instance, but not on the statements.

![2018-06-17_11-10-38](https://user-images.githubusercontent.com/1410238/41506495-2e6c0526-721f-11e8-9c6d-ac2642f6de90.png)

![2018-06-17_10-55-15](https://user-images.githubusercontent.com/1410238/41506486-cfc699b4-721e-11e8-9452-1ec7e9bd70d4.png)

Note that just showing the identifier is not enough. It must also be possible to somehow **select and copy it**, e.g. to then paste it into the KB settings.

**Comment by reckart** [comment]
@naveen2507 the tooltips need a delay before they appear. Right now, if I just swipe the mouse over the screen, many tooltips appear and I need to close all of them manually. This is quite annoying.

**Comment by naveen2507** [comment]
@reckart explored options but didn't find anything to delay the tooltip, i will keep looking on this if I get something reasonable which matches our req. @reckart WDYS?

**Comment by reckart** [comment]
https://docs.telerik.com/kendo-ui/api/javascript/ui/tooltip/configuration/showafter

**Comment by naveen2507** [comment]
@reckart  I already tried that, its for delay before showing the tooltip initially. It takes a parameter for delay in milliseconds before the Tooltip is shown

**Comment by reckart** [comment]
I guess that means that the mouse has to hover for X milliseconds over the element before the tooltip is shown - wouldn't that solve our problem? I mean there is a minimal time required for the mouse to hover before the TT is shown, then a simple swipe shouldn't open many tooltips, no?

**Comment by naveen2507** [comment]
@reckart But that wouldn't enable the user to copy the text from the TT.

**Comment by reckart** [comment]
@naveen2507 Why not? The user could over with the mouse over the element for a while, then the TT appears, then the user can copy the text and then close the TT again using the close button. Does it not work in this way?

**Comment by naveen2507** [comment]
@reckart When we use `autoHide` in combination with `showafter`, we need to wait for the tooltip to show itself. I will commit in the code and you can have a look if its okay.  PR #362

**Comment by naveen2507** [comment]
```wicket-ajax-jquery-ver-0609994817998C227219FC6831EDBBCA.js:1 Wicket.Ajax:  Wicket.Ajax.Call.processEvaluation: Exception evaluating javascript: SyntaxError: Unexpected token :, text: (function(){Wicket.Ajax.ajax({"u":"./kb.html?13-1.IBehaviorListener.0-content-concepts-tree-subtree-branches-12-node-content-link&p=1","c":"id184","e":"click","pd":true});})();(function(){jQuery('#id198').kendoTooltip({ "showOn": click, "autoHide": false, "content": Model:classname=[org.apache.wicket.model.PropertyModel]:nestedModel=[Model:classname=[org.apache.wicket.model.CompoundPropertyModel]:nestedModel=[Model:classname=[org.apache.wicket.model.Model]:object=[KBHandle[identifier=http://www.w3.org/TR/2003/PR-owl-guide-20031209/wine#Region,name=Region]]]]:expression=[identifier] });})();(function(){Wicket.Ajax.ajax({"u":"./kb.html?13-1.IBehaviorListener.0-content-detailContainer-details-info-content-delete&p=1","c":"id19b","e":"click"});})();(function(){Wicket.Ajax.ajax({"u":"./kb.html?13-1.IBehaviorListener.0-content-detailContainer-details-info-content-createSubclass&p=1","c":"id19c","e":"click"});})();(function(){jQuery('#id199').kendoTooltip({ "autoHide": false, "content": "http://www.w3.org/2000/01/rdf-schema#subClassOf", "showAfter": 2000 });})();(function(){Wicket.Ajax.ajax({"u":"./kb.html?13-1.IBehaviorListener.0-content-detailContainer-details-info-content-statements-statementGroupListWrapper-statementGroupListView-1-statementGroup-content-form-propertyLink&p=1","c":"id199","e":"click"});})();(function(){Wicket.Ajax.ajax({"u":"./kb.html?13-1.IBehaviorListener.0-content-detailContainer-details-info-content-statements-statementGroupListWrapper-statementGroupListView-1-statementGroup-content-form-statementListWrapper-statementList-1-statement-content-makeExplicit&p=1","c":"id19d","e":"click"});})();(function(){Wicket.Ajax.ajax({"u":"./kb.html?13-1.IBehaviorListener.0-content-detailContainer-details-info-content-statements-statementGroupListWrapper-statementGroupListView-1-statementGroup-content-form-statementListWrapper-statementList-2-statement-content-makeExplicit&p=1","c":"id19e","e":"click"});})();(function(){Wicket.Ajax.ajax({"u":"./kb.html?13-1.IBehaviorListener.0-content-detailContainer-details-info-content-statements-statementGroupListWrapper-statementGroupListView-1-statementGroup-content-form-add&p=1","c":"id19f","e":"click"});})();(function(){jQuery('#id19a').kendoTooltip({ "autoHide": false, "content": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type", "showAfter": 2000 });})();(function(){Wicket.Ajax.ajax({"u":"./kb.html?13-1.IBehaviorListener.0-content-detailContainer-details-info-content-statements-statementGroupListWrapper-statementGroupListView-2-statementGroup-content-form-propertyLink&p=1","c":"id19a","e":"click"});})();(function(){Wicket.Ajax.ajax({"u":"./kb.html?13-1.IBehaviorListener.0-content-detailContainer-details-info-content-statements-statementGroupListWrapper-statementGroupListView-2-statementGroup-content-form-statementListWrapper-statementList-1-statement-content-makeExplicit&p=1","c":"id1a0","e":"click"});})();(function(){Wicket.Ajax.ajax({"u":"./kb.html?13-1.IBehaviorListener.0-content-detailContainer-details-info-content-statements-statementGroupListWrapper-statementGroupListView-2-statementGroup-content-form-statementListWrapper-statementList-2-statement-content-makeExplicit&p=1","c":"id1a1","e":"click"});})();(function(){Wicket.Ajax.ajax({"u":"./kb.html?13-1.IBehaviorListener.0-content-detailContainer-details-info-content-statements-statementGroupListWrapper-statementGroupListView-2-statementGroup-content-form-statementListWrapper-statementList-3-statement-content-edit&p=1","c":"id1a2","e":"click"});})();(function(){Wicket.Ajax.ajax({"u":"./kb.html?13-1.IBehaviorListener.0-content-detailContainer-details-info-content-statements-statementGroupListWrapper-statementGroupListView-2-statementGroup-content-form-add&p=1","c":"id1a3","e":"click"});})();(function(){Wicket.Ajax.ajax({"u":"./kb.html?13-1.IBehaviorListener.0-content-detailContainer-details-info-content-statements-add&p=1","c":"id1a4","e":"click"});})();(function(){Wicket.Ajax.ajax({"u":"./kb.html?13-1.IBehaviorListener.0-content-detailContainer-details-instances-instances&p=1","m":"POST","c":"id1a5","e":"change"});})();(function(){Wicket.Ajax.ajax({"u":"./kb.html?13-1.IBehaviorListener.0-content-detailContainer-details-instances-add&p=1","c":"id1a6","e":"click"});})();(function(){Wicket.Ajax.ajax({"u":"./kb.html?13-1.IBehaviorListener.0-content-detailContainer-details-instances-showAllInstances&p=1","m":"POST","c":"id1a7","e":"change"});})();```

![image](https://user-images.githubusercontent.com/10420950/42277644-6088e1ba-7f98-11e8-97a5-f3861f316a40.png)

I tried to fix the tool tip but there are some issues which I am stuck at. I already tried N number of solutions and the screenshot shows that it throws a error on browser console. 

` Label identifier = new Label("idtext"); 
  TooltipBehavior tip = new TooltipBehavior();
  tip.setOption("autoHide", false);
  tip.setOption("content",compoundModel.bind("identifier"));
  tip.setOption("showOn", "click");
  identifier.add(tip);
  add(identifier);`

Please do provide pointers in case you see any obvious issues here. 

Reference Link : [https://docs.telerik.com/kendo-ui/api/javascript/ui/tooltip](https://docs.telerik.com/kendo-ui/api/javascript/ui/tooltip)

**Comment by reckart** [comment]
Could you please commit the state with the label + ttbehavior committed to the PR?
