### ISSUE TITLE
Merging a slot link does not trigger rendering

### ISSUE THREAD

**Issue by GiantEnemyCrab** [inception-project/inception#2994]
### Describe the bug

During curation, when a link annotation is clicked on annotator's panel in order to transfer that arrow to the curation panel, the transferred link annotation is not visible unless either 1: the page is reloaded from the browser, or 2: click "next" document, then from the next document, click "previous" to come back to the same note. Then, the link arrow is visible.

### To Reproduce

Download this exported project zip file:

[link_curation_bug13809389020414686157.zip](https://github.com/inception-project/inception/files/8509088/link_curation_bug13809389020414686157.zip)

Import this zip file onto INCEpTION as a project, and make sure to add missing users.

Be on "admin" account or add user name that has curation privilege to this imported project.

Go to curation of "lorem_ipsum" file name document.
Then, curation should look like below:

![Screenshot from 2022-04-18 21:30:18](https://user-images.githubusercontent.com/1326079/163903560-d281c28a-703e-4963-86ba-80725e06770d.png)

From "user1"'s annotation, in the sentence 2, click on the link between `lorem` and `mollis` tags, to transfer the link onto curation, because that does not exist yet in curation.

Observe that clicking on `Link1` between `lorem` and `mollis` tags in user1 does not result in `Link1` being transferred to curation panel.

Then, either click "refresh" or "reload" button from the browse, and confirmed that `Link1` annotation was actually transferred from user1's annotation panel onto curation panel, even though it looked as if nothing happened.

### Expected behavior

The expected behavior is that if link annotation is transferred from annotator's panel, then these should be visible right after the link was clicked on annotator's panel.

### Environment

24.0 SNAPSHOT, latest main branch as of 2022-04-18.
Debiab 11, Chromium browser.

**Comment by reckart** [comment]
Thanks for the report.

**Comment by reckart** [comment]
I can confirm the bug. Let's see what causes it...

**Comment by GiantEnemyCrab** [comment]
Thanks for the fix with a very quick response, too, highly appreciated!
