### ISSUE TITLE
Introduce LIMIT constant for retrieving Statements from the Knowledge Base

### ISSUE THREAD

**Issue by rcffc** [inception-project/inception#300]
RdfUtils does not have a configurable LIMIT parameter yet. We might also need a limit parameter for other places where a limit is applied.

**Comment by reckart** [comment]
@rcffc Does #435 resolve this issue or are there more places where this constant needs to be introduced?

**Comment by rcffc** [comment]
There are still some limits in WikiDataReification and KnowledgeBaseServiceImpl (line 414).

**Comment by rcffc** [comment]
Okay.
