### ISSUE TITLE
Schema-validation: missing table [`annotation_document`]

### ISSUE THREAD

**Issue by GiantEnemyCrab** [inception-project/inception#3000]
Attempting to launch inception with embedded database results in
```
Caused by: org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing table [`annotation_document`]
```
This does not happen if mariadb is specified in settings.properties file.
If `database.url`, `databse.username`, `database.password` are commented out, then inceptino tries to use the embedded database, and that's when I encountered the schema validation error.

**Comment by reckart** [comment]
Thanks for reporting. The handling of casing in databases is really a pain in the lower backside....
