### ISSUE TITLE
Allow making changes to a document's curation status in workload panel

### ISSUE THREAD

**Issue by nicoblokker** [inception-project/inception#3009]
**Is your feature request related to a problem? Please describe.**

When assigning documents dynamically it seems no longer possible to access the monitoring panel to change the status of curated documents from "finished" back to "in progress".  I could not find this functionality in the workload panel either.

**Describe the solution you'd like**

It would be usefull if the workload panel had an option to re-open finished documents (analogue to the monitoring panel).

**Describe alternatives you've considered**

a) change status manually in underlying data base
b) disable dynamic assignment to access monitoring panel, change status of document, enable dynamic assignment again

**Comment by reckart** [comment]
Try clicking on the user's badge in the **Annotator** column. Clicking multiple times should rotate you through the possible states.

![Screenshot 2022-04-25 at 11 24 10](https://user-images.githubusercontent.com/1410238/165060782-b48d488b-d586-4971-939b-8b90519494c1.png)

**Comment by reckart** [comment]
Indeed. Since recently, however, a curator can re-open the curation document directly from the curation page. That's not optimal if you have to re-open **many** documents, but at least it saves you from having to switch the workload management mode. Simply go to the curation page and click on the "lock" icon again to put curation back into progress.

**Comment by nicoblokker** [comment]
The lock icon is grayed out. Is there a setting I need to set first?

![grafik](https://user-images.githubusercontent.com/67004671/165063795-7e86100f-2cb6-4803-8b14-3c2f67615510.png)

**Comment by reckart** [comment]
Which version are you using?

**Comment by nicoblokker** [comment]
INCEpTION -- 23.0-SNAPSHOT (2022-02-22 16:02:31, build 90c9cd01)

**Comment by reckart** [comment]
The feature was added in 23.0.1 - best upgrade directly to 23.3.

**Comment by nicoblokker** [comment]
I see, my bad! Thank you for your help :)
