### ISSUE TITLE
PDFs not shown for annotation

### ISSUE THREAD

**Issue by aesuli** [inception-project/inception#3017]
Release 23.3 on the demo website, and also on a docker-based installation, does not show pdf content in the annotation view:

https://morbo.ukp.informatik.tu-darmstadt.de/p/jjj/annotate?10#!d=13079

![image](https://user-images.githubusercontent.com/6543521/165488001-4f481e47-6d85-4abf-b044-182007b8414a.png)

Locally running jar works.

**Comment by reckart** [comment]
Thanks, will take a look.

**Comment by reckart** [comment]
Seems like morbo is https but the viewer tries to load the PDF via http.

**Comment by reckart** [comment]
@aesuli Thanks for the report. Turned out to be a bad reverse-proxy configuration on the demo server. Should be working now.

**Comment by aesuli** [comment]
Can you suggest me where I should look to fix it on my docker-based installation? (it previously worked on 22.1)
Or do I have just to wait for the next release?

**Comment by reckart** [comment]
For us this setting was missing in the settings.properties: 

```

# Use the forward-header handling of the embedded Tomcat - usually works best
server.forward-headers-strategy=NATIVE
```

The setting is documented in the reverse proxy admin docs but we had forgotten it. So maybe you double check that your setup matches the laustest documentation.

**Comment by aesuli** [comment]
FYI: our sysadmin solved the issue on our installation by forcing the NGINX frontend to set the `X-Forwarded-Proto` to `https`.
