### ISSUE TITLE
need for classification

### ISSUE THREAD

**Issue by KGl-f123** [inception-project/inception#3021]
**Is your feature request related to a problem? Please describe.**
I want to use inception to deal with text classification, including single classification and multiple classification.

**Describe the solution you'd like**
I want to work quickly.And I want to get rid of the mouse and lock the document I'm currently marking, and skip to the next one after one.
Tags can be tiled under text for easy viewing.

**Comment by reckart** [comment]
Closing since there appear to be no additional questions.
