### ISSUE TITLE
Configure document states to consider for training

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#303]
Add a setting to recommenders allowing the user to configure on which document states / annotation states to train. E.g. the manager may want to import pre-annotated data to overcome a recommender cold start but mark the respective documents as locked for all annotations. Similarly, a manager may require that a document is curated before being considered for recommendation.

- [x] Add to backend (recommender model and training task)
- [x] Add to UI
- [x] Update export/import
- [x] Update documentation

**Comment by reckart** [comment]
@Rentier this is the issue about including only documents in certain states into the recommender training, e.g. documents which are marked as finished or marked as curated.

**Comment by Rentier** [comment]
Do you want to have a set of `AnnotationDocumentState` which should be considered, making the configuration a list of checkboxes?

**Comment by reckart** [comment]
no, because `AnnotationDocumentState` doesn't capture whether a document is curated or not.

**Comment by reckart** [comment]
Well, maybe the case for the curated documents needs to be handled separately. In that case, a checkboxgroup might work.

**Comment by Rentier** [comment]
How would we save these options in the database? As it is a collection, I would need a new table, don't I?

**Comment by reckart** [comment]
@MdeBoer95 has used a primitive collection for the KB root concepts. That might be an option.

**Comment by Rentier** [comment]
I will do that. It still creates a table though.
