### ISSUE TITLE
Marking Up Code (Monospaced)

### ISSUE THREAD

**Issue by SvenPVoigt** [inception-project/inception#3036]
I am using inception to markup code like python files:

```python
def foo(x: int) -> int:
    return x

y = 1
z = foo(y)
```

Here, `foo` would be marked as a functional predicate, the first `x` would be of type input and integer, `int` would be a class, the second `x` would be of type output and integer, and `y` and `z` are of type `int` and would be linked by `foo`.

It would be helpful to have a monospace editor with line-height options for the annotation part of the inception app. Is there a way I could define a monospace editor in addition to options like the *brat (sentence-oriented)* and *brat (line-oriented)* editor? Maybe this is already possible through some configuration file that would allow me to import new editor styles. Or maybe there is already an editor for code in the works?

My current workaround is converting to html and styling in a `<code> block </code>`. This works fine (apart from the editor ignoring `line-height` options for the code block set using *css* styles), but I would like to make my own editor if it is possible.

**Comment by reckart** [comment]
Have a look here:

* https://inception-project.github.io/releases/23.4/docs/developer-guide.html#_external_editors
* https://github.com/inception-project/inception-recogito-editor-plugin

... but the APIs are relatively new and therefore a bit of a moving target ...

**Comment by reckart** [comment]
Closing since there appear to be no additional questions.
