### ISSUE TITLE
Problem with project import

### ISSUE THREAD

**Issue by janmatti** [inception-project/inception#3039]
### Describe the bug

I have tried several times to re-import a previously exported project. This no longer seems to work.

### To Reproduce

1. Go to 'Administration'
2. Click on 'Projects'
3. Click on 'Import'
4. Choose previously exported project
5. Click 'import'
7. See error

### Expected behavior

After the progress wheel in the right upper corner disappears, the imported project should appear in the list of projects on the right-hand side.

### Environment

Version and build ID: 23.4 (2022-05-01 08:43:58, build ef5e769b)
Operating system: e.g. OS X Big Sur
Browser: Chrome

**Comment by reckart** [comment]
Good to know that people still use this page ;) I'm normally importing projects via the main projects overview page. Does it work if you try importing the project from there? If you only import a single project, you should automatically be redirect to the imported project's dashboard page once the import has concluded successfully.

**Comment by janmatti** [comment]
No, I tried both ways, with the same result.

**Comment by reckart** [comment]
Do you see any suspicious logging messages / erros in the log?

**Comment by janmatti** [comment]
I’m attaching the log file from today; I tried importing today again with no success, however, I don’t remember at what time and I don’t know what exactly to look for, so perhaps it’s easiest if you quickly check.

 

Many thanks!

Jan

 

From: Richard Eckart de Castilho ***@***.***>
Reply to: inception-project/inception ***@***.***>
Date: Thursday, 12. May 2022 at 15:32
To: inception-project/inception ***@***.***>
Cc: janmatti ***@***.***>, Author ***@***.***>
Subject: Re: [inception-project/inception] Problem with project import (Issue #3039)

 

Do you see any suspicious logging messages / errors in the log?

**Comment by reckart** [comment]
Upon closer investigation, we found lots of lines with the following error

```
DefaultHandshakeHandler - "Handshake failed due to invalid Upgrade header: null"
```

It seems that the nginx reverse proxy that was being used was missing these two lines to support WebSocket:

```
       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection "upgrade";
```

Now the error message is gone. Import works again. Probably that was it.
