### ISSUE TITLE
Export functionality does not seem to work reliably in each scenario

### ISSUE THREAD

**Issue by ChristophLeonhardt** [inception-project/inception#3043]
### Describe the bug

First of all, thank you very much for the great work.

Using INCEpTION 22.5 running in Docker, we encountered a rather strange problem concerning the export functionality. The two ways you can export an entire project do not seem to be identical. One of those doesn't seem to work reliably.

The first export method via the project settings (described as "1" below) results in... nothing? Clicking on the "Start export..." button does nothing really. At the second glance, I noticed that the "Log out countdown" on the upper right corner of the screen resets, but other than that there is no response. 

The second method to export the project via the administator panel (described as "2" below) does work. The progress bar appears and the project is downloaded.

I cannot reproduce this behaviour when I run INCEpTION from the jar directly. There, the first methods works as expected.

On a related note, I noticed that trying to export a project twice in quick succession doesn't seem to work reliably. If the export functionaly works, like in the second method described below, selecting a different output format and clicking on the "Export whole project" button again results in either no response or the following error message is displayed: 

> Invalid project export state after export: RUNNING

Re-loading the export menu (by leaving it temporarily) seems to solve this issue for me. I can reproduce this as well when I run INCEpTION from the jar file and use the first export method.

### To Reproduce

As far as we know, there are two ways to export an entire project: 

1)
* after logging in, click on the project you want to export
* in the menu on the left side of the screen select "Settings"
* in the settings menu select "Export" on the very end of the menu bar on the left
* click on "Start export..." in the "Export backup archive" box

2)
* after logging in as an administator, click on "Administration"
* select "Projects"
* select the project you want to export from the resulting menu
* there, select the "Export" tab
* click on "Export the whole project"

### Expected behavior

In both scenarios, the entire project should be downloaded.

### Environment

Version and build ID: 22.5 (2022-03-12 19:54:59, build a81eecf0)
Browser: Safari

**Comment by reckart** [comment]
Is the Docker-based instance running behind a reverse proxy?

**Comment by ablaette** [comment]
Thanks for the quick question. I am on the project with Christoph, so I can chime in. Yes: It is a Docker-based instance running behind a reverse proxy.

**Comment by reckart** [comment]
INCEpTION 22 introduced a new websocket based export page. It can sometimes be tricky to get it working behind a reverse proxy. I would recommend you Update INCEpTION to the latest version (mind a backup) and then carefully check the documentation of that version wrt running behind a reverse proxy. We have documentation for Nginx and Apache - if you want to use caddy and cannot figure it out we might also find some docu for it.

**Comment by ablaette** [comment]
Thanks so much for this fast feedback. We will do the update and try to get as far as we can!

**Comment by ChristophLeonhardt** [comment]
Also from my side, thank you very much for the quick response!

**Comment by reckart** [comment]
@ChristophLeonhardt @ablaette Have you been able to get things working?
