### ISSUE TITLE
Remote Knowledge Base and API

### ISSUE THREAD

**Issue by A-Menu** [inception-project/inception#3054]
Hello, I have a question regarding remote KB in INCEpTION

**Is your feature request related to a problem? Please describe.**
I am currently linking annotations to a knowledge base imported locally on a project; however I wonder if querying it wouldn't be faster with a remote knowledge base (in addition to working with an up-to-date KB). 

The problem is that if the KB in question has a REST API returning data in turtle, json, jsonld and rdf, it doesn't have a SPARQL endpoint yet. [The API documentation can be found here](https://opentheso.hypotheses.org/50) (only available in French, my apologies).

**Describe the solution you'd like**
This is more a question than a feature request, but is there a way to add a distant knowledge base via an API rather than a SPARQL endpoint ? my attempts have returned errors so far.

Thank you and have a nice day

**Comment by reckart** [comment]
You would have to ask OpenTheso to export an entire thesaurus for you. Once you have an RDF file which contains the entire thesaurus, you can import it as a local KB into INCEpTION. Remote KBs are only supported via SPARQL.

**Comment by reckart** [comment]
I don't know how similar the OpenTheso KBs are to each other - but if they are all built in the same way, you'll likely want to configure your KB as follows after you have imported the RDF file:

![Screenshot 2022-05-18 at 11 47 02](https://user-images.githubusercontent.com/1410238/169010760-7bc0c721-7812-457f-a2be-cb3b1c6a5698.png)

**Comment by A-Menu** [comment]
I see, thank you for your quick reply and clarification ! we'll keep working with the local KBs
