### ISSUE TITLE
Unable to link "Indonesia"

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#306]
The auto-complete only offers very strange choices

![2018-06-20_11-29-21](https://user-images.githubusercontent.com/1410238/41650185-be55a4c0-747d-11e8-99a4-5167d0c20742.png)

A SPARQL query on the KB reveals though that the entity we are looking for is indeed contained in the KB

![2018-06-20_11-33-14](https://user-images.githubusercontent.com/1410238/41650239-d8645708-747d-11e8-85dc-b0a882e0506a.png)

**Comment by rcffc** [comment]
![screenshot from 2018-06-22 23-19-20](https://user-images.githubusercontent.com/13070150/41799724-d5fee3d8-7672-11e8-9293-68ae21ee7168.png)
Cannot reproduce this error. I suspect it is because of the EntityLinking properties currently active on blinky-experimental. Try with these settings that I use:
```
inception.entity-linking.cacheSize = 1024
inception.entity-linking.mentionContextSize = 5
inception.entity-linking.candidateQueryLimit = 10000
inception.entity-linking.candidateDisplayLimit = 20
inception.entity-linking.candidateFrequencyThreshold = 25
inception.entity-linking.signatureQueryLimit = 2147483647
```

**Comment by reckart** [comment]
Try writing "Indonesia" instead of "indo".

**Comment by reckart** [comment]
btw. it seems that if I write a prefix of the mention string into the field, the search always is for the mention string. E.g. if I write "indo" on a mention of "indonesia", the log would still says that it searched for "indonesia" instead of "indo".

You can also try something else. Search e.g. for "2017". I got a lot of stuff but not the year. Searching for "year 2017" also didn't help, but e.g. searching for "MMXVII" returned the year.

**Comment by rcffc** [comment]
> btw. it seems that if I write a prefix of the mention string into the field, the search always is for the mention string

That was done intentionally to improve the performance, see https://github.com/inception-project/inception/issues/87

**Comment by rcffc** [comment]
> Search e.g. for "2017"

![screenshot from 2018-06-22 23-35-22](https://user-images.githubusercontent.com/13070150/41800268-1936ec0c-7675-11e8-8ec3-b933b1cfc9fc.png)

Typing "Indonesia" also lead to the correct result.

**Comment by reckart** [comment]
> That was done intentionally to improve the performance, see #87

But it kind of prevents matching against an entity which in the KB has a prefix of the mention as its label, doesn't it?

**Comment by rcffc** [comment]
That's true.

**Comment by rcffc** [comment]
A first step to solve this issue might be to fire two queries for exact matching and intelligent matching and make a union of both candidate sets.

**Comment by reckart** [comment]
Can we apply separate limits for each part of the union?

**Comment by rcffc** [comment]
> It would be one query with a union, wouldn't it?

Yes.

> Can we apply separate limits for each part of the union?

Yes. But I think for the exact matching part we don't need a limit.

**Comment by reckart** [comment]
@rcffc Doesn't seem to work... I get lots of these in the logs:

```
2018-07-05 16:28:15 WARN [SYSTEM] SPARQLProtocolSession - Server reports problem: Virtuoso 37000 Error SP030: SPARQL compiler, line 23: syntax error at 'UNION' before 'SELECT'

SPARQL query:
define sql:big-data-const 0 DEFINE input:inference 'instances'
PREFIX e:<http://www.wikidata.org/entity/>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos:<http://www.w3.org/2004/02/skos/core#>
PREFIX base:<http://www.wikidata.org/ontology#>
PREFIX schema: <http://schema.org/>
SELECT DISTINCT ?e2 ?altLabel ?label ?description WHERE
{
  {
SELECT DISTINCT ?e2 ?description WHERE
    {
     VALUES ?labelpredicate {rdfs:label skos:altLabel}
      GRAPH <http://wikidata.org/terms>
      {
        ?e2 ?labelpredicate '"mit"' @en .
        OPTIONAL
        {
          ?e2 <http://schema.org/description> ?description.
          FILTER ( lang(?description) = "en" )
        }
      }
    }
    UNION
SELECT DISTINCT ?e2 ?altLabel ?description WHERE
    {
      VALUES ?labelpredicate {rdfs:label skos:altLabel}
      GRAPH <http://wikidata.org/terms>
      {
        ?e2 ?labelpredicate ?altLabel.
        ?altLabel bif:contains '"mit"'. 
        OPTIONAL
        {
          ?e2 <http://schema.org/description> ?description.
          FILTER ( lang(?description) = "en" )
        }
      }
    }
LIMIT 2500
  }
  FILTER EXISTS { GRAPH <http://wikidata.org/statements> { ?e2 ?p ?v }}
  FILTER NOT EXISTS 
  {
    VALUES ?topic {e:Q17442446 e:Q14204246 e:Q4167836 e:Q4167410 e:Q13406463 e:Q11266439 e:Q17633526 e:Q11753321}
    GRAPH <http://wikidata.org/instances> {?e2 rdf:type ?topic}
  }
  BIND (STRLEN(?altLabel) as ?len)
  {
    GRAPH <http://wikidata.org/terms> { ?e2 rdfs:label ?label. }
    FILTER ( lang(?label) = "en" )
  }
}
```

This time the comment is hopefully in the right issue ;)

**Comment by rcffc** [comment]
That's why the PR has the WIP label ;) The problem was a syntax error.

With our internal server now I get this error: `Virtuoso 42000 Error The estimated execution time 480 (sec) exceeds the limit of 400 (sec).` [An answer on a Github issue](https://github.com/openlink/virtuoso-opensource/issues/78) suggests to comment out  `MaxQueryCostEstimationTime` in the .ini file.

I have tried a similar query on DBpedia and it works:
```
PREFIX dbpedia:<http://de.dbpedia.org/resource/>

SELECT DISTINCT ?e2 ?altLabel ?description WHERE
{
  { 
    SELECT DISTINCT ?e2 ?description WHERE
    {
       VALUES ?labelpredicate {rdfs:label skos:altLabel}
       ?e2 ?labelpredicate "China" @en.
	OPTIONAL {
          ?e2 dbo:abstract ?description.
          FILTER ( lang(?description) = "de" )
          ?e2 dbo:wikiPageID ?id.
        }
    }
  }
  UNION
  {
    SELECT DISTINCT ?e2 ?altLabel ?description WHERE{
      VALUES ?labelpredicate {rdfs:label skos:altLabel}
        ?e2 ?labelpredicate ?altLabel.
        FILTER ( lang(?altLabel) = "de" )
        ?altLabel bif:contains "'China'".
	OPTIONAL {
          ?e2 dbo:abstract ?description.
          FILTER ( lang(?description) = "de" )
          ?e2 dbo:wikiPageID ?id.
        }
    } LIMIT 10
  }
}
```

**Comment by betoboullosa** [comment]
@rcffc What's the status of this issue?

**Comment by rcffc** [comment]
Review by @reckart is in progress.

**Comment by reckart** [comment]
> Review by @reckart is in progress.

... which doesn't mean that testing and reviewing by others is not welcome.

**Comment by reckart** [comment]
Closing this for now. Further problems/improvements to be handled in other/new issues.
