### ISSUE TITLE
NPE when opening 

### ISSUE THREAD

**Issue by hostettler** [inception-project/inception#3089]
### Describe the bug

I get the following NPE when trying to annotate the following PDF: [AnaCredit ECB PDF](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32016R0867&from=EN)

Here is the complete stack trace
[NPE.txt](https://github.com/inception-project/inception/files/8821725/NPE.txt)

Thanks a lot for your help

### To Reproduce

1. Go to 'Annotate'
2. See error

![image](https://user-images.githubusercontent.com/1552158/171578721-f2eb0cd5-28df-4aa3-b7b0-6750e72bc491.png)

### Expected behavior

I can annotate the PDF

### Screenshots

![image](https://user-images.githubusercontent.com/1552158/171578765-9f708687-4df3-468a-bf9d-99333f034e7a.png)

### Environment

Application version	23.6 (2022-05-29 11:50:02, build e3136a42)
Java version	Oracle Corporation 11.0.15
Operating system	Linux 5.10.16.3-microsoft-standard-WSL2 amd64

**Comment by reckart** [comment]
Please try changing the name of the PDF to something simple like `document.pdf` and try then. I believe the characters in the PDF file name may be the root cause.

**Comment by hostettler** [comment]
Hello, thanks for the feedback. Unfortunately I saved locally the PDF, renamed it to pdf.pdf and I am still getting the same NPE.

**Comment by hostettler** [comment]
Actually, I just changed the configuration and let inception select the editor (instead of forcing it to PDF) and it now works

**Comment by reckart** [comment]
I also can't reproduce it when I force the PDF editor. So no idea where your issue came from.
