### ISSUE TITLE
Always show description of linked concept in popover 

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#310]
When a concept is proposed by the NamedEntityLinker recommender, the description of the concept is shown in the mouse popover of the suggestion. However, once the suggestion has been accepted, the mouse popover no longer shows the concept description. This is a problem because then it is no longer clear if the mention has been linked to the correct concept.

When there a concept feature is rendered, its description and identifier must be added into the mouse popover.

Also when regular recommender (e.g. String matching recommender) proposes a value for a concept feature, the description and identifier of the proposed entity must be shown in the popover. Just having the label is not enough to tell if the suggestion is correct or not.

**Comment by rcffc** [comment]
@Rentier @reckart  I once asked whether we could add a _description_ feature that would be saved in the CAS, but I think one of you declined . Unfortunately, I cannot find the issue anymore. Do you remember what you suggested instead?

**Comment by reckart** [comment]
If I remember correctly, I suggested that the description would be obtained from the KB during the rendering phase.
