### ISSUE TITLE
Error while exporting curated documents: Unexpected error during project export: OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by maks1812** [inception-project/inception#3128]
**Describe the bug**
After clicking on Start Export button on Export page progress bar freezes and after a while throws error "Unexpected error during project export: OutOfMemoryError: Java heap space".

**Expected behavior**
After clicking on Start Export button project have to be exported.

**Screenshots**
browser console message and INCEpTION error are attached below 

**Please complete the following information:**
 - Version 23.7
 -  build ID:  8dec45b3
 - OS: Linux
 - Browser: FireFox, also tried on Chrome

**Additional context**
![INCEpTION_error](https://user-images.githubusercontent.com/47788759/174064753-82d70a72-2c67-465e-853f-fc904a568200.png)

![inception_error2](https://user-images.githubusercontent.com/47788759/174064629-1bebfcdb-dc87-4cfe-802a-fcfec1c3fbdc.png)

**Comment by reckart** [comment]
During application startup, INCEpTION logs how much application memory is available. If you run out of memory during export, you might care to increase the memory available to INCEpTION via the Java Runtime `-Xmx` parameter.

**Comment by blochs** [comment]
@reckart Is there a default for it? It's running inside K8's without a resource limit so it has ~ 32GB

**Comment by reckart** [comment]
Depends on your Java version - cf. https://stackoverflow.com/questions/4667483/how-is-the-default-max-java-heap-size-determined

**Comment by blochs** [comment]
Yup just did, gonna see how it rolls.

**Comment by maks1812** [comment]
Yeah, thanks, it helped. But somehow for one project I've got TypeError while downloading only curated documents in XML 1.0 format. That is weird because I  was able to export whole project. 
Should it be the separate bug?

![Error](https://user-images.githubusercontent.com/47788759/174734479-29b71e9e-8371-473b-a01c-c956af77e724.png)

**Comment by reckart** [comment]
It seems your WebSocket connection is not working. My guess would be that the error is related to that. 

If you have trouble with WebSocket, you should upgrade to the latest version 23.7 and set `websocket.enabled=false` in your `settings.properties` file. Note though that at some point in the future, more and more functionality of INCEpTION may be ported to WebSocket which may yield it unusable if the protocol is not supported by the reverse proxy/firewall setup.

**Comment by blochs** [comment]
@reckart websockets are natively supported by the ingress controller we use

**Comment by reckart** [comment]
Do you have any explanation why the websocket connection is lost then?

**Comment by blochs** [comment]
I do not, but it worked previously

**Comment by reckart** [comment]
@maks1812 So you can download the full project but not the curated documents only? Are you using the default export page that shows the exports in a sidebar on the right or the "legacy" export page which basically features a progress bar smack in the middle of the page?

**Comment by maks1812** [comment]
@reckart  Yeah, the problem is only with downloading curated documents. I think I use the default one (see screenshot). 
![Export](https://user-images.githubusercontent.com/47788759/174813013-88ee3e22-fc1a-49fd-ae9d-870433e24599.png)

Previously we downloaded only whole project.

**Comment by reckart** [comment]
Do you get some kind of error in the logs when you try exporting the curated documents?

**Comment by maks1812** [comment]
That is a question for @blochs, since he has an admin rights.

**Comment by reckart** [comment]
I may have a lead on this issue as I found a OOM situation that could happen when re-indexing a project. Possibly something similar happens during export. I'll let you know if/when I find out more.

**Comment by reckart** [comment]
What order of magnitude of documents did that project have?

**Comment by reckart** [comment]
If the problem persists with 24.0 please comment to re-open.
