### ISSUE TITLE
Two guest users with same UI name

### ISSUE THREAD

**Issue by mbugert** [inception-project/inception#3185]
### Describe the bug

We encountered a situation where one annotator has managed to sign up to a project as two users, but with both users having the same UI name.

In the project settings, they showed up as having the same UI name, but different hash identifiers.
Thankfully, it could be resolved by deleting the user with fewer annotations, but figuring out which one that was wasn't too easy.

### To Reproduce

Unclear, I could not reproduce it so far.
The annotator said he/she may have used multiple browser tabs and/or multiple browser windows, but doesn't remember the details.

### Expected behavior

Annotator is logged in into the already existing user account in this scenario.

### Environment

Version and build ID: 23.8 (2022-06-29 21:24:41, build 4b271961)
Operating system: Windows
Browser: Chrome, most likely

### Additional context

This happened on inception-stable on blinky, on 2022-07-13 roughly at 10:59. More details on request through a private channel of your choice. :)

A project export at the time of having the duplicate user IDs exists, but I cannot import it into a local INCEpTION instance because it fails with `org.hsqldb.HsqlException: integrity constraint violation: unique constraint or index violation; UK_REALM_UINAME table: USERS`

I'm aware of the documentation saying `INCEpTION does not support being used from multiple browsers / windows / computers concurrently with the same user ID`, but this looks like a different issue to me.

-----

## To do

* [ ] Ensure at a low level (e.g. in the calls to join a user to a project) that the user must either be a global user or a guest user of that project (i.e. not a guest user of another project)
* [ ] When accessing the join page for a project and the user is currently logged in as a guest user of another project, terminate the session to force the user to get a new identity when joining the new project

**Comment by reckart** [comment]
There should be a DB constraint which should prevent two users with the same UI name within the same realm (realm being a particular project) - that is the error you see when you try re-importing into another instance.

Unrelated but still interesting https://github.com/inception-project/inception/issues/2199

**Comment by reckart** [comment]
The constraint exists on blinky/stable - it should not be possible to create two guest users with the same UI name within the same project on blinky.

**Comment by mbugert** [comment]
It happened again, and we figured out how to reproduce it:

1. Create new project **A**
2. Add a document
3. Enable project joining via invite link, enable "allow guest annotators", take note of the invite link
4. Repeat steps 1-3 with a project called **B**
5. From a different machine (or from a different browser):
    1. Join **A** with username "Test"
    2. Open a second browser tab, join **B** with username "Test"
    3. Log out in the second tab
    4. Open the invite link for **B** in the second tab, and log in another time with username "Test"
6. Project **B** now has two users named *Test* with different hashes
![project_a](https://user-images.githubusercontent.com/23331603/180255261-fe1c8c0a-8fc7-4b1c-aec5-5549e751c1e8.png)
![project_b](https://user-images.githubusercontent.com/23331603/180255279-cb59fe5e-c789-439a-bc3a-1caea0adc43f.png)

**Comment by mbugert** [comment]
> Good catch. I really have no idea how you always find these types of issues, but it is a great find!

This time it was my relatives who found it (they are equally capable of breaking stuff). :laughing:
