### ISSUE TITLE
Flipped Behavior in Change document status 

### ISSUE THREAD

**Issue by akbugert** [inception-project/inception#3228]
### Describe the bug

In the Workload View, manually changing the document state does not behave as expected: Marking as finished sets the document to in-progress and vice versa.

### To Reproduce

1. Create new project
2. Add a document
3. Change Workload to dynamic
4. Annotate the document
5. In the Workload view:
    1. Under "Annotators", try to change the document status to FINISHED. 
    2. INCEpTION says "Document status has changed", but the document is neither marked as finished in the workload view (the symbols still show it as in progress) nor is it finished on the annotation page (the user can still annotate).
    3. Under "Annotators", try to change the document status to INPROGRESS.
    4. The document is now marked as finished (symbol says finished) and annotation is closed in the annotation page (user cannot annotate).

### Expected behavior

The document changes in the way the user has selected it.

### Environment

Version and build ID: INCEpTION -- 23.9 (2022-07-23 09:01:57, build 0f9d854e)
Operating system: Linux Mint 20.3 
Browser: Firefox 102.0

**Comment by reckart** [comment]
When I click on an annotators "badge" in the dynamic workload management page, the icon changes immediately - I don't get a message.

![demo](https://user-images.githubusercontent.com/1410238/180808118-48c47941-6fce-4825-b569-336b551a2e0b.gif)

**Comment by akbugert** [comment]
Thanks for the quick reply. In step 5.i the following dialog is used:

![Bug](https://user-images.githubusercontent.com/109971770/180809020-b04aa0bf-1db1-4839-b1c6-6fe02a0df84b.png)

**Comment by reckart** [comment]
I see - yes, there is something fishy in that dialog. Thanks for finding!

**Comment by reckart** [comment]
Actually, I think the part to change the document status can be removed from that dialog - clicking on the badge can be used instead.

**Comment by akbugert** [comment]
> Actually, I think the part to change the document status can be removed from that dialog - clicking on the badge can be used instead.

Because of #3230, this workaround cannot be used in all situations currently. :sweat_smile:
