### ISSUE TITLE
Status of abandoned documents cannot be changed

### ISSUE THREAD

**Issue by akbugert** [inception-project/inception#3230]
### Describe the bug

The status of abandoned documents cannot be changed by clicking on the badge. It is also not possible to lock them with the Annotators Dialog (which can only set to in-progress or finished). The consequence is that abandoned and finished documents cannot be reassigned to a different annotator.

### To Reproduce

After performing the steps from #3229, it is not possible to change the status of the document by clicking on the badge.

### Expected behavior

Clicking on the badge should have the same behavior as for non-abandoned documents.

### Environment

Version and build ID: INCEpTION -- 23.9 (2022-07-23 09:01:57, build 0f9d854eb3d4898e6a778dd3e722b06627d14fcd)
Operating system: Linux Mint 20.3
Browser: Firefox 102.0 and Chromium Version 103.0.5060.53

**Comment by reckart** [comment]
You can right-click on a badge and choose "Touch" - that removes the abandonment status. Then you can switch the state again by clicking on the badge.

**Comment by reckart** [comment]
But actually, you should not have to do that. An abandoned document is usually auto-locked (check the settings how you configured abandonment) and the dynamic assignment should then ignore it and assign the document to another annotator if one needs a new document.

**Comment by akbugert** [comment]
> But actually, you should not have to do that. An abandoned document is usually auto-locked (check the settings how you configured abandonment) and the dynamic assignment should then ignore it and assign the document to another annotator if one needs a new document.

Thats true, but as reported in #3229 I have documents that are finished and abandoned instead of auto-locked after abandonation.


> You can right-click on a badge and choose "Touch" - that removes the abandonment status. Then you can switch the state again by clicking on the badge.

:open_mouth: That's good to know, thanks! It was not mentioned in the user guide, but it's really helpful for my currently running annotation project.

**Comment by reckart** [comment]
With the other bugs fixed (in particular the bug that caused all documents to appear abandoned), I believe this now becomes a non-issue. Documentation has been updated as well.
