### ISSUE TITLE
Tag not saved when moving to next tag

### ISSUE THREAD

**Issue by 2xXLunAXx2** [inception-project/inception#3242]
**Describe the bug**
The bug occurs when the annotation is made by writing a text (instead of choosing an existing tag).
When I'm changing a tag that already exists I can't immediately move to create/change some next tag, but I have to click somewhere on the page for the tag to be saved first, otherwise the tag won't be saved. 

**To Reproduce**
1. Go to document annotation.
2. Create some annotations with written tags (not a layer with some already existing tags).
3. Choose one annotation and change the tag. Then immidiately (without clicking anywhere else) click on some other annotation you previously created.
4. See that the tag did not change.

**Expected behavior**
I change a tag and when I move to the next tag the previous tag saves automatically.

**Please complete the following information:**
 - Version and build ID: 23.0.1
 - OS: Windows
 - Browser: chrome
 
----

- [x] right-clicking on an annotation to open context menu does not cause editor value to be committed
- [x] double-clicking on text to create new annotation looses editor value
- [x] clicking on another annotation looses editor value
- [x] clicking into the text to start dragging a new annotation commits editor value, but commit of value disrupts selection action
- [x] switching to another annotation using shift-cursor-keys or the prev/next buttons
- [x] Selection of span in PDF editor requires two clicks

**Comment by reckart** [comment]
Thanks, will have a look. 

As a "workaround", you can press enter to commit the value.
