### ISSUE TITLE
Upload UIMA-CAS split to lines

### ISSUE THREAD

**Issue by yanirmr** [inception-project/inception#3243]
**Describe the bug**
When uploading a UIMA-type file, lines are not divided as expected.

**To Reproduce**
1. Upload a UIMA-CAS file with a newline character ("\n") via import documents
2. Open the file in annotation mode
3. Look at the line counter

**Expected behavior**
Different line after each newline character.

**Please complete the following information:**
 - Version and build ID:  23.0.1 
 - OS: Windows
 - Browser: Chrome

**Additional context**
1. In plain text, newline characters behave as expected. 
2. Attempts to overcome this issue include splitting the lines into different sofas (via different views. I'm not sure if it is a good idea, but the views don't appear in the inception, only the original CAS.

Your support is greatly appreciated, thank you!

**Comment by reckart** [comment]
INCEpTION does not support multiple views.

If you want to pre-split sentences, you add annotations of type `de.tudarmstadt.ukp.dkpro.core.api.segmentation.type.Sentence` to your CAS.

After import, I recommend to use the CAS Doctor from the project settings to check the imported files for validity.

**Comment by reckart** [comment]
Also, if you want to see lines separated by `\n`, you have to use an editor like `brat (line-oriented)` or `brat (wrap at 120 chars)` but not `brat (sentence-oriented)`.

**Comment by yanirmr** [comment]
'de.tudarmstadt.ukp.dkpro.core.api.segmentation.type.Sentence' works for me. Thank you!
