### ISSUE TITLE
Undo/redo feature

### ISSUE THREAD

**Issue by yanirmr** [inception-project/inception#3244]
**Is your feature request related to a problem? Please describe.**
Annotating something incorrectly or deleting an annotation incorrectly frustrates me a lot of times. 

**Describe the solution you'd like**
The ability to undo in INCEPTION would be very helpful, as it is in other applications and systems. With only one click or a ctrl+z prompt, the damage is repaired. One of the most useful features in any word processor or spreadsheet is the undo/redo list.

**Comment by reckart** [comment]
On which kinds of actions do you particular miss such a functionality?

**Comment by yanirmr** [comment]
I appreciate your help.

According to my opinion, the most needed actions to undo/redo are:
1. Add an annotation
2. Delete an annotation
3. Edit an annotation 

It happens a lot that I need to cancel/restore one of them

**Comment by reckart** [comment]
Are you working mostly on one document at a time or are you switching a lot between documents?

**Comment by yanirmr** [comment]
One document at a time.

**Comment by reckart** [comment]
@yanirmr I'd be curious if the undo/redo feature that we have now meets your expectations.

**Comment by 2xXLunAXx2** [comment]
> @yanirmr I'd be curious if the undo/redo feature that we have now meets your expectations.

Hello,
Thank you very much for listening to our suggestions for ways of upgrading the (already great) interface. 
The undo/redo feature works perfectely and it's very close to the sentences that need to be annotated, and it saves a lot of time, so thanks again!
