### ISSUE TITLE
Text Correction via Dedicated Layer

### ISSUE THREAD

**Issue by yanirmr** [inception-project/inception#3257]
**Is your feature request related to a problem? Please describe.**
An option to suggest fixing the text of a document. 

**Describe the solution you'd like**
A layer annotation for orthography change suggestions. These annotations can be reviewed and could be automatically applied to the documents including updating the offsets. 

**Describe alternatives you've considered**

**Additional context**
Many times, when we carefully tag text, we discover text errors, e.g. typos. It is very difficult to export an XML file and manually adjust tag offsets. I think real-time text correction might cause conflicts, but if we apply it via a dedicated layer with different permissions, it will work.

Is this a good idea?

**Comment by reckart** [comment]
The layer "Orthography" exists for this purpose already - have you seen it?

Applying the changes, however, is an action that needs to be performed externally. There is no ready-made code for this at the moment, but it should be relatively straightforward to implement such code using [DKPro Cassis](https://github.com/dkpro/dkpro-cassis).

**Comment by yanirmr** [comment]
Oh, I see. I didn't notice that. To clarify, after using this layer, do I need to export the documents, process them, and import them again?

**Comment by reckart** [comment]
Yes. Within INCEpTION, the document text is immutable.
