### ISSUE TITLE
"Jump to relation" breaks for Link features

### ISSUE THREAD

**Issue by mbugert** [inception-project/inception#3261]
### Describe the bug

When annotating relations, there is a button that can be used to jump from the currently selected span annotation to an incoming/outgoing relation annotation. Clicking on this button works as intended when the relation is modeled with a layer of type Relation (POS/Dependency), but fails with NPE when the relation is modeled with a feature of type Link (SemPred/SemArg).

### To Reproduce

1. Create new project, add some document
2. Create a SemArg span annotation, create a SemPred span annotation, add the arg to the pred with some arbitrary relation name
3. Select the SemArg span annotation
4. Click the button circled in red
![button](https://user-images.githubusercontent.com/23331603/182325343-f0af48e6-20e9-4c4a-8f40-54c47660e370.png)
5. `NullPointerException` appears

### Expected behavior

If the button worked as intended, I suppose it would lead to the selection of the SemPred span. That's identical to what clicking the crosshair button would do, so removing the "jump to relation" button entirely for Link-type features would be a reasonable solution, I think.

### Environment

Version and build ID: 23.11 (2022-08-01 19:30:04, build 119516fb) 
Operating system: Mint 20.3
Browser: FF

**Comment by reckart** [comment]
The "door" icon should select the relation. In the case of a link, there is no explicit representation of the link that would be selectable - it is owned by the span. So yes, I agree that for link features, the icon should be removed. Thanks for noticing!
