### ISSUE TITLE
Unable to start on Mac M1

### ISSUE THREAD

**Issue by maiiabocharova** [inception-project/inception#3262]
Hello, I installed the newest version of Java (https://www.java.com/en/download/apple.jsp). But now have a problem when starting INCEpTION - "INCEpTION requirers at least Java 11, but you are running Java 1.8"

**Comment by reckart** [comment]
Apple does not offer Java 11 for Mac. You can get a version e.g. from [Eclipse Temurin](https://adoptium.net/en-GB/). There are also other vendors that offer free Java environments like [Azul](https://www.azul.com/downloads/), [Amazon](https://aws.amazon.com/corretto/), [RedHat](https://developers.redhat.com/products/openjdk/download) and more...

**Comment by maiiabocharova** [comment]
Thank you a lot! Downloaded from [Eclipse Temurin](https://adoptium.net/en-GB/) and Issue solved!
