### ISSUE TITLE
Wrong character encoding in the page footer

### ISSUE THREAD

**Issue by jfiala** [inception-project/inception#3265]
**Describe the bug**
In the footer line it reads:
Technische UniversitÃ¤t Darmstadt -- Computer Science Department -- INCEpTION -- 23.8 (2022-06-29 21:24:41, build 4b271961) 

The Umlaut "ä" is broken, probably due to reading UTF-8 encoded data using charset ISO-8859-1.

**To Reproduce**
Login to Inception (23.8).
Look at the footer.

**Expected behavior**
The Umlaut "ä" should be rendered correctly.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/4069646/182391396-6b032e2e-a17b-4b63-9ec3-d4a8ba6685f3.png)

**Please complete the following information:**
 - 23.8 (2022-06-29 21:24:41, build 4b271961) 
 - Windows
 - Firefox

**Comment by reckart** [comment]
Could you open the developer console in Firefox, open the network panel there, reload the INCEpTION page and click on the entry for `login.html` and check what the `content-type` header is please?
