### ISSUE TITLE
Cannot tag few sentences with a single tag

### ISSUE THREAD

**Issue by 2xXLunAXx2** [inception-project/inception#3273]
**Describe the bug**
If I want to put a single tag on more than one sentence, I cannot do so. I get the error: "Unable to load data: Annotation covers multiple sentences, limit your annotation to single sentence!"

**To Reproduce**
1. Go to some document with at least two sentences.
2. Click on at least two sentences at once.
3. Get the error written above.

**Expected behavior**
I can put one single tag on more than one sentence.

**Please complete the following information:**
 - Version and build ID: 23.0.1
 - OS: Windows
 - Browser: chrome

Thank you!

**Comment by reckart** [comment]
* go to the layers panel in the project settings.
* locate the layer you want to create an annotation from
* enable the option "allow crossing sentence boundaries*
* save the layer configuration
* go back to the annotation page
* viola
*

**Comment by 2xXLunAXx2** [comment]
It works now. Thank you!!
