### ISSUE TITLE
Write the name of the tags with my keyboard during annotation without adding new tags accidently

### ISSUE THREAD

**Issue by 2xXLunAXx2** [inception-project/inception#3274]
**Describe the bug**
There are two options in tagging right now: either I cannot add new tags during annotation and I can write the name of the tags with my keyboard, or I can add new tags during annotation and I need to choose the tag with my mouse. 

**To Reproduce**
1. Enable the option 'annotators may add new tags' in the tags settings.
2. Go some document and click on a word.
3. See that you can write the names of the existing tags with your keyboard.
4. Go back to the tag's settings and disable this option.
5. Go back to the document and click on a word.
6. See that you can only choose the names of the existing tags with your mouse.

**Expected behavior**
I would like to shorten the tagging time, therefore I want to avoid creating new tags accidently by typos while still working only with my keyboard.

**Screenshots** 
The 'focus1' layer with 'annotators may add new tags' enabled:
![image](https://user-images.githubusercontent.com/110154717/182834837-c5a34bfc-5885-43b6-9fdc-2d76c36f7980.png)

The 'focus1' layer with 'annotators may add new tags' disabled:
![image](https://user-images.githubusercontent.com/110154717/182834599-dc22e26d-5a31-4d88-bacc-150cb39f834d.png)

**Please complete the following information:**
 - Version and build ID: 23.0.1
 - OS: Windows
 - Browser: chrome

Thank you!

**Comment by reckart** [comment]
* go to the project settings
* go to the layers panel
* select the relevant layer
* select the relevant feature
* locate the "Editor type" setting
* Choose the editor you want
* Save feature settings
* Go back to the annotation page and create/select an annotation of the relevant layer
* Voilá

**Comment by 2xXLunAXx2** [comment]
I played with the settings a little and finally it worked. Thank you!
