### ISSUE TITLE
Combine/merge outputs of different local taggers into shared one 

### ISSUE THREAD

**Issue by yanirmr** [inception-project/inception#3292]
Hello,

A network issue prevents our team from working on the inception online (on the server), so each member uses the same last export file, sets up local INCEPTION, and continues tagging. Is there a convenient way to merge tags when returning shared work? 
As long as each user continues to work on his user, I am not concerned about conflicts.

Thanks!

**Comment by reckart** [comment]
Through the remote API, you can upload exports of individual annotated documents (preferably as binary CAS or XMI) directly into the original project on your server using the ["create annotation"](https://openminted.github.io/releases/aero-spec/1.0.0/omtd-aero/#_create_annotations) endpoint. 

So you can ask your annotators to export the documents directly from the annotation page when they are finished so you can then import them to your server using the remote API.

Note that the project settings on the individual member's machines must **exactly** match the settings on the server - in particular the layer and feature configurations!

Through the UI, there is currently no option to upload annotations for individual annotators/documents within a project.

**Comment by reckart** [comment]
@yanirmr Mind to try this out before putting the it in full practice to avoid any surprises at the end.
