### ISSUE TITLE
The exported CoNNL-files contain no annotations with custom named entity tags

### ISSUE THREAD

**Issue by shigapov** [inception-project/inception#3293]
**Describe the bug**
The exported CoNNL-files contain no annotations with custom named entity tags.

**To Reproduce**
1. Create custom named entity tags in 'Tagsets'.
2. Create custom named entity layer in 'Layers'.  For the feature "value" specify the custom tagset created in 1.
3. Annotate a document with the new custom named entity layer.
4. Convert the document to any of CoNNL-formats (e.g., CoNNL 2002).

**Expected behavior**
The exported CoNNL-files contain annotations with custom named entity tags.

**Please complete the following information:**
 - Version and build ID: 24.0 and 'da827b12'
 - OS: Linux
 - Browser: chrome

**Additional context**
The exported UIMA CAS XMI (XML 1.0) files contain custom annotations.

**Comment by reckart** [comment]
CoNLL formats only support the built-in named entity layer. Please refer to the format documentation in the user's guide to see which formats support custom layers and which are restricted to the build-in layers.

You can use e.g. [DKPro Cassis ](https://github.com/dkpro/dkpro-cassis) to read the custom layers from the XMI files and convert them to your custom tab-separated format as you require.

**Comment by shigapov** [comment]
Thank you for your quick response!

Indeed, there is a column "Custom layers" in https://inception-project.github.io/releases/24.0/docs/user-guide.html#sect_formats. May be it would make sense to add short descriptions of those columns after "Appendix B: Formats"?

Thanks for pointing out to https://github.com/dkpro/dkpro-cassis. I'll give it a try.
