### ISSUE TITLE
Support for Wikidata properties

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#330]
Currently we hard-code the RDF property and sub-property IRIs. Wikidata uses its own IRIs to mark properties and sub-properties. We need to be able to configure these IRIs in the KB in order to be able to see Wikidata properties in the KB page.

**Comment by naveen2507** [comment]
Duplicate for  #322

**Comment by reckart** [comment]
#322 is not very specific about the required steps. If you consider it a duplicate, please ensure that #332 explicitly mentions the properties and subproperties and best refine its description to include a checklist of all necessary actions. Then please close the present issue as a duplicate removing it from the respective project and milestone.
