### ISSUE TITLE
Dependency support to connect NamedEntity annotations

### ISSUE THREAD

**Issue by jfiala** [inception-project/inception#3304]
**Is your feature request related to a problem? Please describe.**
Currently relations/dependencies can only be created between tokens.

**Describe the solution you'd like**
It would be nice to also allow relations between annotations (e.g. NamedEntity-annotations).

**Comment by reckart** [comment]
Create a custom layer of type "relation" and configure it to attach to the "Named Entity" layer - voilá.

**Comment by jfiala** [comment]
Perfect, thank you - just found it in the docs also (Relations).

Maybe the docs could be refined:
In order to create relation annotation, a corresponding relation layer needs to be defined between the source and target spans. If this is the case, there are two ways of creating a relation:

Better understandable:
In order to create relation annotation, a corresponding relation layer needs to be created (layer type: Relation) and attached to the layer you want to support relations. If this is the case, there are two ways of creating a relation:

**Comment by reckart** [comment]
Would you like to provide a PR for the documentation update?

**Comment by jfiala** [comment]
Sure, can you give me a pointer to where the documentation should be best updated?

**Comment by reckart** [comment]
https://github.com/inception-project/inception/blob/main/inception/inception-ui-annotation/src/main/resources/META-INF/asciidoc/user-guide/annotation_create-annotations_relation.adoc

**Comment by jfiala** [comment]
https://github.com/inception-project/inception/pull/3305

**Comment by reckart** [comment]
Thanks! I'll close this issue already. Made a small update to your PR - still good for you? Please comment on the PR.
