### ISSUE TITLE
HTML errors and warnings

### ISSUE THREAD

**Issue by stweil** [inception-project/inception#3326]
**Describe the bug**
The INCEpTION web pages include HTML 5 code with errors and warnings:

```
Error: Stray end tag meta.
Error: An img element must have an alt attribute, except under certain conditions. For details, consult [guidance on providing text alternatives for images](https://www.w3.org/WAI/tutorials/images/).
Warning: Consider adding a lang attribute to the html start tag to declare the language of this document.
Warning: The type attribute is unnecessary for JavaScript resources.
```

Wrong HTML code typically works differently on different web browser, so can be the reason why certain web browsers don't work..

**To Reproduce**
I installed the latest Docker image (`INCEpTION -- 24.1 (2022-08-23 13:26:20, build 631d180b)`).
Use the [W3C validator](https://validator.w3.org/) to validate selected pages either by URI (normally only possible for login page) or by [direct input](https://validator.w3.org/#validate_by_input) (possible for any page).

**Expected behavior**
Ideally all web pages should pass without any HTML error or warning.

**Comment by stweil** [comment]
More reports for the first page after successful login:

```
Error: Element [span](https://html.spec.whatwg.org/multipage/#the-span-element) is missing one or more of the following attributes: role.
Error: Element [div](https://html.spec.whatwg.org/multipage/#the-div-element) not allowed as child of element [span](https://html.spec.whatwg.org/multipage/#the-span-element) in this context. (Suppressing further errors from this subtree.)
Error: No p element in scope but a p end tag seen.
Error: Element [p](https://html.spec.whatwg.org/multipage/#the-p-element) not allowed as child of element [small](https://html.spec.whatwg.org/multipage/#the-small-element) in this context. (Suppressing further errors from this subtree.)
```

**Comment by stweil** [comment]
There remain unsolved HTML errors even after the latest commits. Therefore I suggest to keep this issue open.

**Comment by reckart** [comment]
I'll keep it open for further PRs on v25 but will close it when v25 gets released. A new issue can be opened for issues that remain after v25.
