### ISSUE TITLE
Sorting documents by upload date

### ISSUE THREAD

**Issue by salvadora** [inception-project/inception#3329]
**Is your feature request related to a problem? Please describe.**
I want to delete documents uploaded on specific date (mostly the newest ones for example because of an error), or in other case I want to manually block and assign newest documents to different annotators. I cannot do it because currently the documents are listed always in the alphabetical order. Adding a date to the document name is not a good solution for us. 

**Describe the solution you'd like**
Sorting of documents by upload date in documents and monitoring view.

**Describe alternatives you've considered**
We considered adding date to documents name, however it is not a good solution. The first word of the document name must be a word implicating the topic of the document in order to group the documents by topic in the annotation view.

**Comment by reckart** [comment]
Thanks for the suggestion. It fit in nicely with something that I had planned to improve for a long time already and which is now coming up in v25.

<img width="862" alt="Screenshot 2022-09-01 at 08 32 49" src="https://user-images.githubusercontent.com/1410238/187847267-3d248ad7-c35d-49e3-855b-063ccf865a67.png">
