### ISSUE TITLE
NE linking recommendations without NE annotation

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#333]
There still seems to be something funky with the NamedEntityLinker recommender. Normally, it should only show recommendations for things that are annotated as named entities, right? So why are there entity linking recommendations here for "support" even though there is no NE mention on that word.

<img width="1315" alt="2018-06-25_14-55-40" src="https://user-images.githubusercontent.com/1410238/41851342-d9369e80-7887-11e8-9903-12defd12e050.png">

0.4.0-SNAPSHOT (2018-06-25 12:44:31, build 0c47f2ac70e8d694dad3a3b907c8d18d4519692c)

**Comment by rcffc** [comment]
What happens when you go out of the Annotation Page and come back to the same page?

**Comment by reckart** [comment]
Same thing.
