### ISSUE TITLE
Difficulties in selecting an existing tag for deleting it

### ISSUE THREAD

**Issue by smadarsz** [inception-project/inception#3348]
**Describe the bug**
When I need to modify or delete an exisiting tag, I need to select it and highlight it first and only then can I make my changes. Selecting an existing tag is cumbersome - have to click multiple time before the selection "holds".

**To Reproduce**
1. Select a word and define a tag t'.
2. move on to the next selection - so that tag t' is no longer selected.
3. Now go back to tag t' and try to select it -> this operation takes lots of clicks / trials.

**Expected behavior**

**Screenshots**

**Please complete the following information:**
 - Version and build ID: 23.0.1 (2022-04-02 23:20:47, build edf60f9c)
 - OS: Windows
 - Browser: Chrome

**Additional context**

**Comment by reckart** [comment]
Thanks for the report. I think the issue might be related to this other issue which has been addressed in v24.2: https://github.com/inception-project/inception/issues/3242

Could you please check if the issue you are experiencing persists in v24.2?

**Comment by smadarsz** [comment]
Apologies but I cannot upgrade my system now. As soon as we can, I'll test and comment here.

**Comment by reckart** [comment]
Closing this assuming it has been fixed since there were no further complaints. If the problem persists, please open a new issue.
