### ISSUE TITLE
NamedEntityLinker broken

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#336]
Looks like now the NamedEntityLinker doesn't work anymore at all because it doesn't produce per-Token annotations in its results. The evaluation task doesn't like this at all:

* add named entity linker to project
* do **not** set "always active"
* enable assertions by passing `-ea` as an argument to INCEpTION or Tomcat.

You'll get a stack trace similar to this:

```
	ExtendedResult.<init>(List<List<AnnotationObject>>, List<List<AnnotationObject>>) line: XXX
	IncrementalTrainingEvaluationSuite.evaluateUnknownData(List<List<AnnotationObject>>) line: 257	
	EvaluationService.evaluate(List<List<AnnotationObject>>) line: 181	
	SelectionTask.evaluate(EvaluationConfiguration, ClassificationTool<?>, List<SourceDocument>) line: 168	
	SelectionTask.run() line: 111	
	TaskConsumer.run() line: 63	
	Thread.run() line: 748	
```

@Rentier this is what I meant when I said the evaluation needs to be fixed when the classifiers are changed to produce multi-token annotations.

**Comment by rcffc** [comment]
Will set a flag to skip Evaluation of the NamedEntityLinker, since it does not need to be evaluated anyway.

**Comment by reckart** [comment]
We have a new column in the Recommender entity but not in the DB...
