### ISSUE TITLE
Install inception using commandline - docs?

### ISSUE THREAD

**Issue by jfiala** [inception-project/inception#3404]
**Is your feature request related to a problem? Please describe.**
The current installation hints seem to be targeted to standalone UI-based installations in a closed network (port 8080).

**Describe the solution you'd like**
Are there installation instructions/hints available for setup on a linux system using commandline only including an up-front Apache?

**Comment by reckart** [comment]
Sure, check the admin guide: https://inception-project.github.io/releases/24.3/docs/admin-guide.html

There are instructions for installation on the bare metal as well as in Docker - with or without reverse proxy.

**Comment by jfiala** [comment]
Maybe it makes sense to add a reference from the installation guide?
