### ISSUE TITLE
Undo delete document/project

### ISSUE THREAD

**Issue by yanirmr** [inception-project/inception#3417]
Hello, 
Having the ability to undo deleting documents or projects is very important. According to my understanding, this is not possible at this time. Do I understand correctly?

I would also appreciate it if the option to restore the deleted file was available when I attempted to click "go back" after the previous page was deleted.

Until now, it has been considered a feature request. It is now a support issue - 
We accidentally deleted a very large project. Can a snapshot of the database be restored in some way?
Many thanks!

**Comment by reckart** [comment]
The deletion of projects / documents should always be accompanied with a challenge-response dialog. That means you have to manually enter the name of the document or project that you delete.

From the perspective of INCEpTION, deleting a document or project is a final and irreversible action.

If you have made backups of your system, you can restore them. It is always recommended that users keep backups of any important data.

**Comment by reckart** [comment]
How did you accidentally delete the data? If you did it via the UI, did you not have to go through a challenge-response dialog?

**Comment by yanirmr** [comment]
Hi, 
I did that via the UI but clicked on the "delete project" button instead of the "delete document" button. As the two buttons look very similar, I accidentally clicked on the wrong one.
Maybe remove the "delete project" button from the "document tab" (and any other tab) and keep it only in a very specific "danger zone", since it should not appear on any pages.

**Comment by yanirmr** [comment]
Thank you!
