### ISSUE TITLE
Allow optional document properties of type Integer/Float

### ISSUE THREAD

**Issue by jfiala** [inception-project/inception#3421]
**Is your feature request related to a problem? Please describe.**
Currently document properties of type Integer/Float are always mandatory.

**Describe the solution you'd like**
It should be possible to have nullable properties of type java.lang.Integer/java.lang.Float.

**Describe alternatives you've considered**
Currently we would have to use the property using type String or live with every document property of type Float set to 0.00, although it is rarely set (expert quality assessment).
As it is not possible to convert types, converting at a later time will be hard also.

**Comment by reckart** [comment]
The underlying UIMA framework does not have nullable float/integer values, so we'd have to use strings internally anyway.

**Comment by reckart** [comment]
For a manually set quality assessment, it's often a good idea to use a Likert Scale (i.e. a set of discrete values) which can be modelled as a String feature with a tagset. This can also be displayed in INCEpTION as a radio-group for easier access instead of a text input or combo.

**Comment by jcklie** [comment]
You could add a boolean feature that encode whether the property is set, if that is nicer than 0.0 or using strings.

**Comment by jfiala** [comment]
Thank you for the quick replies!
I think we'll give the tagset a try!
