### ISSUE TITLE
Layer cannot be deleted - what could be the reason?

### ISSUE THREAD

**Issue by jfiala** [inception-project/inception#3427]
**Describe the bug**
I have a layer I created earlier in the project, but it cannot be deleted (Button "Delete" is available, but rendered inactive).
What could be the reason why a layer becomes undeletable?
I can disable the layer, but I cannot delete it.

All other layers can be deleted as expected.

**To Reproduce**
Not sure, the layer was created earlier.

**Expected behavior**
Layer should be deletable.
If not, a hint should be given why it is not deletable.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/4069646/194297837-336c2d55-b9a7-4364-a431-9c3d972a776e.png)

**Please complete the following information:**
 - Version and build ID: 23.8 (2022-06-29 21:24:41, build 4b271961) 
 - OS: Windows
 - Browser: firefox

**Comment by reckart** [comment]
Span layers cannot be deleted as long as a relation layer attaches to them.
