### ISSUE TITLE
Knowledgebase - Handling of multiple labels/synonyms

### ISSUE THREAD

**Issue by jfiala** [inception-project/inception#3428]
**Is your feature request related to a problem? Please describe.**
In the knowledgebase, you can define multiple labels having the same language (e.g. de).
However, the new label value is immediately picked up as the preferred term of the instance.
The primary label cannot be defined somehow.

**Describe the solution you'd like**
The primary label of an item in the knowledgebase should be markable.

**Describe alternatives you've considered**
I tried adding a subproperty to the instance, but that subproperty is not searchable using the "identifier" field in the annotation view.
I tried to add the alternative labels/synonyms using another language (de2), but then it is also not searchable.

![grafik](https://user-images.githubusercontent.com/4069646/194300295-57f29833-971c-4753-b90c-6c8865029bbf.png)

**Comment by reckart** [comment]
There should only be one "primary label" with a given language. If you want to add synonyms, that can be done by adding a secondary label feature and configuring the KB mapping to look that feature up for secondary labels.

E.g. you could use `http://www.w3.org/2004/02/skos/core#prefLabel` as **Label IRI** and add `http://www.w3.org/2000/01/rdf-schema#label` to **Additional Matching Properties**.

**Comment by jfiala** [comment]
Thanks, that sounds good, I'll give that a try!
