### ISSUE TITLE
The layers are generated automatically with non-desired settings

### ISSUE THREAD

**Issue by yanirmr** [inception-project/inception#3487]
### Describe the bug

The custom layers were automatically generated when I uploaded tagged files with custom tags. However, the layer settings are set to default. There was also a problem with the customization settings, for example, the tag granularity, which did not restore and needs to be fixed manually.

### To Reproduce

1. Create a new project
2. Upload a tagged file with a custom layer with a specific setting
3. Open the layer setting that was generated after the uploading and see if the setting is saved.

### Expected behavior

There should be no difference between the layer settings that are exported and imported.

### Environment

Version and build ID: 25.1 (2022-10-11 21:15:38, build e85988ac)
Operating system: Linux
Browser: e.g. Chrome

**Comment by reckart** [comment]
@yanirmr I am not aware that custom layers would be created when importing pre-annotated documents through the "Documents" panel in the project settings. How did you import your pre-annotated data?

**Comment by yanirmr** [comment]
In our tagging procedure, every tagger that completes the tagging of a document is required to export the file as an XMI file. 
It proved to be a valuable habit when we used the single files backup to upload data back into Inception after the whole project had been deleted. 

To answer your question, we uploaded the documents one-by-one using the API and updated their annotations as well.

**Comment by reckart** [comment]
A proper backup procedure should involve a regular export of the entire project - that would then also include tagsets and all other settings.

**Comment by yanirmr** [comment]
We'll do that. OK.

**Comment by reckart** [comment]
@yanirmr when uploading documents or annotations through the remote API, no layers should be created at all. Uploading documents through the API requires the project to have been previously initialized with all the required settings.
