### ISSUE TITLE
Deleting a layer feature doesn't always work

### ISSUE THREAD

**Issue by Atlogit** [inception-project/inception#3492]
### Describe the bug

When deleting a feature on a layer, the confirmation box opens. Upon entering the required text and clicking “Confirm” it closes the window, and nothing happens.
Only after going through the deletion process again does it delete the feature.

### Expected behavior

Deletion should work on first try

### Environment

Version and build ID: 25.2 (2022-10-25 17:41:05, build 4a7663f9)
Operating system: Linux
Browser: Edge

**Comment by reckart** [comment]
Is there any error message?

**Comment by reckart** [comment]
Just had the same problem - did not see an error - needs to be investigated.

**Comment by reckart** [comment]
Hm, but I cannot really reproduce it...
