### ISSUE TITLE
Importing a layer doesn’t import behavior properly

### ISSUE THREAD

**Issue by Atlogit** [inception-project/inception#3493]
### Describe the bug

After importing a sentence layer, granularity was set to “Character-level”, eventhough the original (exported) layer was set to “sentence-level”, and “Allow crossing sentence boundaries” set to true.
It also imported the name without the whitespace between the 2 words (”i.e. Sentence Label” became “SentenceLabel”.

### To Reproduce

1. Go to a project
2. Create a sentence layer
3. Make sure "granularity" is set to "Sentence-level" and that "Allow crossing sentence boundaries" is off
4. Export the layer
5. Go to another project
6. Import the layer
7. 

### Expected behavior

All layer details and variables should be properly imported

### Environment

Version and build ID: 25.2 (2022-10-25 17:41:05, build https://github.com/inception-project/inception/commit/4a7663f936008f3901d5a2c8e0b9b21cf3c93928)
Operating system: Linux
Browser: Edge

**Comment by reckart** [comment]
In which format do you export the layer? 

Note that it is expected that exporting layers in the "UIMA" format could lose information because the UIMA type system format is unable to represent all the details of the INCEpTION layer configuration. Exporting as JSON should retain all details though.

**Comment by reckart** [comment]
Closing as there was no further response.
