### ISSUE TITLE
No properties shown in KB UI 

### ISSUE THREAD

**Issue by naveen2507** [inception-project/inception#352]
**Describe the bug**
No properties for ontologies for new project created. (Please check if somebody can reproduce)

**To Reproduce**
1. Create a new project
2. Add a local ontology - I took wine ontology
3. Add a document to the project
4. Go to KB UI and check if the properties are visible for you 

**Expected behavior**
List of properties on KB UI 

**Screenshots**
![image](https://user-images.githubusercontent.com/10420950/42077747-22eec878-7b7a-11e8-9f46-6fa93599a11e.png)

**Please complete the following information:**
 -  Technische Universität Darmstadt -- Computer Science Department -- INCEpTION 𝜶 -- 0.4.0-SNAPSHOT (2018-06-28 14:45:31, build 492d8c20bf4e6f0e2b12546cb56020ca1c90a71b) - master branch
 - Linux
 - chrome

**Comment by naveen2507** [comment]
#322 Duplicate Issue

**Comment by naveen2507** [comment]
Issue covered by PR #394

**Comment by reckart** [comment]
Since the PR is not yet merged, the issue should not be closed yet, right?

**Comment by naveen2507** [comment]
I have closed the PR, for the KB labelled issues there are lot of issue dependent on each other and overlap the fixes. Like Statement validation is dependent on the issues related to property. WDYS?

**Comment by reckart** [comment]
Ok, I understood from your comment that PR #394 covers (i.e. includes) the changes for this issue, not that #322 (the issue governing #394) supersedes this issue.

**Comment by reckart** [comment]
But actually... anyway. As long as the bug still exists, it should not be closed. Only once the properties are shown, it should be closed. Otherwise there is a risk that the issue will be opened again. As far as I can see PR #394 is not yet merged and does not yet fix the issue. So reopening it.

**Comment by naveen2507** [comment]
To be closed after closing PR #394

**Comment by naveen2507** [comment]
> To be closed after closing PR #394

Closing issue now.
