### ISSUE TITLE
Infinite merging of annotations on custom layers

### ISSUE THREAD

**Issue by GiantEnemyCrab** [inception-project/inception#3523]
**Describe the bug**
Not sure if this is considered bug or not, but does seem unexpected.
So, when using threshold merge in curation page, I can click the same tag from an annotator multiple times, and they make it into curation, even through none of annotator has that many stacked tags.

**To Reproduce**
Use threshold merge in curation page and merge settings can be something like "User threshold: 2", "Confidence threshold 50%", "Top vote: 3", so.
Click on any tag multiple times from an annotator.

**Expected behavior**
I think that curator should be able to create new stacked tags as needed, but in terms of copying from annotator pane, it should be limited to the max number of the same tag stacked per user.

**Screenshots**
The extra stacked tags are all coming from clicking from annotator pane and they get copied, despite none of annotator did that many stacking:
![Screenshot 2022-11-04 214801](https://user-images.githubusercontent.com/1326079/200096046-bc8e1668-f088-483f-a7df-5e870eaf9399.png)

**Please complete the following information:**
- Version and build ID: 26.0-SNAPSHOT,
- OS: Any
- Browser: Edge, Chrome, etc

**Comment by reckart** [comment]
The merge strategy should only affect the auto-merge process. What happens after that should only be affected by the layer settings. So if the layer has stacking enabled, one can merge annotations such that they stack up. 

I guess the unexpected behavior may be that there is no check if an annotation just as the one which would be created by the manual merge already exists. 

It seems the expectation in this case would be to suppress the manual merge action with a reasonable message.

**Comment by reckart** [comment]
@GiantEnemyCrab could you by any chance provide a project export of the example project you have created here? I somehow don't seem to be able to reproduce this despite having configured a layer as "stacking: any". The first time I merge an annotation, the color in the lower part changes from cyan to green to indicate that the annotation has been merged - the second time I click it, I get the message that the annotation has already been merged (checked with 26.4-SNAPSHOT).

**Comment by GiantEnemyCrab** [comment]
The reference commit hash is `9edbb59d1c1947ef909a868c714c3608f96320ca` from November 12th from `main` branch, which should be able to reproduce, from the full export zip I attached here.

I am having some mvn build issues so I am not able to try 26.4-SNAPSHOT nor 27.0-SNAPSHOT. (I may need to report if I am not able to figure this out, at some point)
I would also note that I am not able to make this zip to work with 26.4 version due to:
```
UnexpectedRollbackException: Transaction silently rolled back because it has been marked as rollback-only
```

But here is the project export that I used that I can reproduce with the commit hash I mentioned somewhere above.
[test_project-116326821991220384605.zip](https://github.com/inception-project/inception/files/10349819/test_project-116326821991220384605.zip)

**Comment by GiantEnemyCrab** [comment]
I can confirm reproducing of the issue with the export zip file directly above this comment for version 26.3.
In version 26.4, I could not import the file due to the error message I shared in that comment.
By the way, I am using HSQL database for local testing, and I wondered if this import failure has something to do with me not using MariaDB.

**Comment by reckart** [comment]
It appears that 26.4 is simply broken... I'm just in the process of trying to figure out why... suspecting a last-minute dependency upgrade  *sigh*

**Comment by reckart** [comment]
Ouch, what a stupid bug :) Thanks for providing the test case. It appears the bug only appears on custom layers and I seem to have tried this only on built-in layers. Anyway, fix is incoming.

**Comment by GiantEnemyCrab** [comment]
Thank you so much for the fix!!!
