### ISSUE TITLE
Importing project files with a new name

### ISSUE THREAD

**Issue by yanirmr** [inception-project/inception#3581]
**Is your feature request related to a problem? Please describe.**

When I import a project from a backup file, my mind becomes confused, and I am unable to distinguish between the uploaded project and the other projects because they have the same name.

It is possible that some people may make a mistake and work on an older version of the project.

**Describe the solution you'd like**

1. It would be helpful to include a field for "uploading time" in addition to the "creation time" field. 
3. When importing a project, add the option to change the slug name

**Comment by reckart** [comment]
In recent versions of INCEpTION, the project list can be sorted by creation date - that (at least for me) largely removes the problem and I think corresponds to your idea 1.

See https://github.com/inception-project/inception/pull/3828
