### ISSUE TITLE
Docker Container stopps with ERROR [SYSTEM] SpringApplication - Application run failed

### ISSUE THREAD

**Issue by lingdata-mf** [inception-project/inception#3596]
Good morning, 

i have some trouble starting the docker container (inceptionproject/inception:26.0). I am running a docker server on RancherOS v1.4.2 and using the image with persistant volume mount "XY:/export" and also a seperate MySQL-Server for which i added the credentals in the ENVs.

I can start the container and i am getting the credits but afterwards a ERROR [SYSTEM] SpringApplication - Application run failed . 

I attached the full log. 

Any advices?

Thanks a lot in advance and thanks for your awesome work on inception!

[inception-docker-log.txt](https://github.com/inception-project/inception/files/10101601/inception-docker-log.txt)

**Comment by reckart** [comment]
> DataSourceConfiguration$Hikari.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zaxxer.hikari.HikariDataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.IllegalStateException: Cannot load driver class: com.mysql.jdbc.Driver

This driver is no longer included in recent versions of INCEpTION. Please configure your installation to use the included MariaDB driver to connect to MySQL. The updated installation sections in admin documentation should be helpful.

**Comment by lingdata-mf** [comment]
THAAAANKS! Works perfect now !
