### ISSUE TITLE
Project import slow or not happening at all

### ISSUE THREAD

**Issue by janmatti** [inception-project/inception#3597]
**Describe the bug**
When trying to import a previously exported project (in the old JSON format or as xmi), the project is either (1) not being imported or (2) it at first seems that it has not been imported – and then the project appears only minutes later after several times of refreshing. After 10 attempts, the scenario (2) seems to be the less likely outcome. Most of the time nothing happens.

**To Reproduce**
1. Go to 'Administration', then to 'Projects'
2. Click on 'Import'
3. Select a local .zip file of an exported project in xmi or json format
4. Click 'Import'
5. Wait until the progress wheel stops turning
6. See error

**Expected behavior**
The project should be listed among the existing projects.

**Screenshots**
-

**Please complete the following information:**
 - Version and build ID: 26.0 (2022-11-22 12:24:34, build 0be6fbfb)
 - OS: OS X Big Sur 11.6
 - Browser: Chrome

**Additional context**

**Comment by reckart** [comment]
Could you please try adding the setting `document-import.run-cas-doctor-on-import=OFF` to your `settings.properties`, restart the application and see if the situation improves?

**Comment by reckart** [comment]
Just checked locally - as far as I can tell, the document import validation is currently not run during project import anyway, so the setting I mentioned above shouldn't make a difference.

**Comment by janmatti** [comment]
Thanks! So, does this mean it works on your side?

 

From: Richard Eckart de Castilho ***@***.***>
Reply to: inception-project/inception ***@***.***>
Date: Tuesday, 29. November 2022 at 09:51
To: inception-project/inception ***@***.***>
Cc: janmatti ***@***.***>, Author ***@***.***>
Subject: Re: [inception-project/inception] Project import slow or not happening at all (Issue #3597)

 

Just checked locally - as far as I can tell, the document import validation is currently not run during project import anyway, so the setting I mentioned above shouldn't make a difference.

**Comment by reckart** [comment]
No, it means I cannot reproduce your problem (yet). I'll have a look now on locally importing a very large project to see how that plays out.

**Comment by janmatti** [comment]
Alright, thanks!

 

From: Richard Eckart de Castilho ***@***.***>
Reply to: inception-project/inception ***@***.***>
Date: Tuesday, 29. November 2022 at 09:55
To: inception-project/inception ***@***.***>
Cc: janmatti ***@***.***>, Author ***@***.***>
Subject: Re: [inception-project/inception] Project import slow or not happening at all (Issue #3597)

 

No, it means I cannot reproduce your problem (yet). I'll have a look now on locally importing a very large project to see how that plays out.

**Comment by reckart** [comment]
So locally importing a 380MB project with tons of documents took about 110 seconds. During the import, I saw the spinning wheel in the browser window's top-right and once the import was complete, I was forwarded to the project's dashboard.

Maybe your project has a different structure that stresses other parts of the import process. I could have a look at that if you can privately share the project with me.

**Comment by reckart** [comment]
@janmatti thanks for supplying the project files. I could import both without any issue from the project overview page. The import took about 9 seconds for each of the projects. I could not observe any problems. I used INCEpTION 26.1-SNAPSHOT (but there should not have been changes relevant to import since the 26.0 release).

Your initial report did not specify which error you saw. Could you provide a part of your log (also privately if you like) which covers the time from the import until the failure?

**Comment by janmatti** [comment]
Lieber Sebastian,

 

würdest Du Richard das log von Inception schicken? (s.u.) Ich habe gerade (13:17 Uhr) nochmal versucht, das Projekt Stuttgart2016 zu importieren, was wieder nicht funktioniert hat. Bin darüber seit gestern mit Richard im Austausch. Danke!

 

Richard: Das Rad dreht sich oben rechts für ein paar Sekunden, dann verschwindet es und alles ist beim Alten, das heißt ich lande wieder auf der Projektübersicht. Allerdings (!) hat der Import ohne Probleme für andere Projekt funktioniert (z.B. Stuttgart 2017 und 2018). Scheint mir, als könnte die Datei defekt sein, aber wenn sie bei dir funktioniert, ist das wohl auch ausgeschlossen. Hoffen wir, dass das log einen Anhaltspunkt liefert.

 

Danke und viele Grüße,

Jan

 

From: Richard Eckart de Castilho ***@***.***>
Reply to: inception-project/inception ***@***.***>
Date: Tuesday, 29. November 2022 at 13:00
To: inception-project/inception ***@***.***>
Cc: janmatti ***@***.***>, Mention ***@***.***>
Subject: Re: [inception-project/inception] Project import slow or not happening at all (Issue #3597)

 

@janmatti thanks for supplying the project files. I could import both without any issue from the project overview page. The import took about 9 seconds for each of the projects. I could not observe any problems. I used INCEpTION 26.1-SNAPSHOT (but there should not have been changes relevant to import since the 26.0 release).

Your initial report did not specify which error you saw. Could you provide a part of your log (also privately if you like) which covers the time from the import until the failure?

**Comment by reckart** [comment]
I'll assume the problem has resolved itself as there was no further feedback.
