### ISSUE TITLE
Document Metadata are not accessible through the remote API

### ISSUE THREAD

**Issue by letailli** [inception-project/inception#3629]
**Describe the bug**
I am not sure this a bug. It might be the expected behavior but it would be great if we can use DocumentMetadata and remote API modules together.

**To Reproduce**

1. I setup DocumentMetadata and remote API in INCEpTION configuration
```
remote-api.enabled=true
documentmetadata.enabled=true
```

2. I create a projet .
3. I setup a "Document Metadata" layer in the project (see Screenshot 1)

4. I add a document in the project and fill the metadata for this document  (see Screenshot 2)
5. I try to read the document to get the metadata.
`http://localhost:8080/api/aero/v1/projects/0/documents/3?format=dkpro-core-uima-inline-xml`

**Expected behavior**
The metadata don't appear in the API response.
I would like to acess Document Metadata through the remote API (`create` and `read`). 

**Screenshots**
![image](https://user-images.githubusercontent.com/2536975/207033234-ecf707e8-cb37-4d34-886e-4cad5a7cf461.png)

![image](https://user-images.githubusercontent.com/2536975/207032292-22046e43-c561-4b7c-8230-949a2bbc89f4.png)

**Please complete the following information:**
 - Version and build ID: INCEpTION 25.4 (executable JAR)
 - OS: Linux Ubuntu 20.04.2 LTS
 - Browser: Chrome

**Comment by reckart** [comment]
Please use the CAS XMI format instead of the inline XML format. I recommend processing the CAS XMI data using [DKPro Cassis (Python)](https://github.com/dkpro/dkpro-cassis) or for Java users the [Apache UIMA Java SDK](https://github.com/apache/uima-uimaj/).

**Comment by letailli** [comment]
Thank you for your answer.

However I don't get the data either with this format.

I tried :
http://localhost:8080/api/aero/v1/projects/0/documents/3?format=xmi-xml1.1
I saved the result in `chataigne_test_Opscidia_API_xmi-xml1.1_API.zip`
I can see a line `<type:LayerDefinition xmi:id="1417" name="webanno.custom.Language" uiName="Document Metadata"/>`
but the data are missing.

Whereas in the manual export I have them :
`<custom:Language xmi:id="1368" sofa="1" Language="EN" OriginalURL="https://lemonde.fr"/>`
(I attached the full export in `chataigne_test_Opscidia_export_UIMA CAS XMI (XML 1.1).zip`)

[chataigne_test_Opscidia_API_xmi-xml1.1_API.zip](https://github.com/inception-project/inception/files/10209225/chataigne_test_Opscidia_API_xmi-xml1.1_API.zip)
[chataigne_test_Opscidia_export_UIMA CAS XMI (XML 1.1).zip](https://github.com/inception-project/inception/files/10209226/chataigne_test_Opscidia_export_UIMA.CAS.XMI.XML.1.1.zip)

**Comment by reckart** [comment]
You are exporting the document you have originally imported. To export annotated documents via the remote API, use the "read annotations" endpoint: https://openminted.github.io/releases/aero-spec/1.0.0/omtd-aero/#_read_annotations

**Comment by letailli** [comment]
Yes with read annotations it's OK. Thank you

**Comment by reckart** [comment]
Another tip: if you plan using DKPro Cassis, export using CAS XMI XML 1.0 because there seems to be no Python-based XML parser that supports XML 1.1.
