### ISSUE TITLE
Text not showing in annotation screen (brat)

### ISSUE THREAD

**Issue by bgittel** [inception-project/inception#3643]
10 lines in the middle of a text are not showing in annotation screen (see screenshot) The same text without annotations shows without problems.

CAS Doctor finds no errors for the document

**To Reproduce**
I'm not sure how to reproduce it on another server or with another document.

**Expected behavior**
Showing the text.

**Screenshots**
![Unbenannt](https://user-images.githubusercontent.com/58990077/208425502-a96408d1-ab9e-4e58-bb23-88f734dc95d4.png)

**Please complete the following information:**
 - Version and build ID: INCEpTION -- 25.4 (2022-11-08 12:45:47, build 1aeb414a)
 - OS: Windows 10
 - Browser: Chrome

**Comment by reckart** [comment]
Can you (privately) share an export of the project with me for debugging?

**Comment by reckart** [comment]
Thanks for the report. Fix is incoming. You might be able to work around the problem by opening the settings dialog (cogwheel icon on the annotation page) and switching there to another brat-based mode, e.g. "brat (wrapping @ 120chars)" - which considering you have long span annotations in the example data you sent me might in general be preferable for your annotation task.

**Comment by bgittel** [comment]
Thank you for the quick response. Unfortunately,  I have the same issue
with brat (wrapping @ 120chars).

Am Di., 20. Dez. 2022 um 09:57 Uhr schrieb Richard Eckart de Castilho <
***@***.***>:

**Comment by reckart** [comment]
I hope to do a bugfix release later today, stay tuned.

**Comment by bgittel** [comment]
Great, thanks!

Am Di., 20. Dez. 2022 um 12:33 Uhr schrieb Richard Eckart de Castilho <
***@***.***>:
