### ISSUE TITLE
Link label shows layer name instead of label

### ISSUE THREAD

**Issue by PA-CRIM** [inception-project/inception#3650]
**Describe the bug**
Link labels display the tagset name (or layer name, which is the same in our project) instead of the selected value from the tagset as before. The correct value is still there if the data is exported or the link selected (shown in the right detail panel). 

**To Reproduce**
The server was updgraded from 25.4 to 26.2 with an existing project with custom layers for semantic role labeling using custom tagsets for links. 

**Expected behavior**
The link should display the value selected from the tagset instead of the tagset name.

**Screenshots**
This is the new, invalid display of the tagset name on every link with version 26.2

![new_version](https://user-images.githubusercontent.com/3966927/208776845-0352e5c2-977c-4998-a915-57475b81f090.png)

But it used to show the values in the previous installed version 25.4 like this

![previous_version](https://user-images.githubusercontent.com/3966927/208776760-b8684682-715d-4a43-b3f7-c819f9eb3037.png)

**Please complete the following information:**
 - Version and build ID:  26.2 (2022-12-20 19:01:06, build f3ea5caa)
 - OS: Linux
 - Browser: chrome v108.0.5359.124

**Additional context**

**Comment by reckart** [comment]
Indeed. Thanks for the report. I'll have a look.

**Comment by reckart** [comment]
As `ARG` the tagset name or the layer name in your case?

**Comment by PA-CRIM** [comment]
Both are the same, but I changed the layer name and it changed in the display for all the links. So basically it's not the tagset name that is displayed, it's the layer name.
