### ISSUE TITLE
Inception malforms filename if upload directory name is longer than 110 characters and filename is longer than 110 characters

### ISSUE THREAD

**Issue by jfiala** [inception-project/inception#3652]
**Describe the bug**
Inception shows malformed filenames for filenames with length > 110 after doing an upload of many (here: 893) documents.
 
**To Reproduce**
1. Settings -> Documents -> "Files to import"
2. Choose directory with complete directory name length > 110 characters
3. Select 893 documents
4. Format UIMA CAS XMI (XML 1.1) and button "Import"
5. Files with filename longer than 110 characters are displayed with a filename starting with "R"<hex number>"~1.XMI"

Interestingly, the same upload works if the source directory name is shortened to less than 110 characters.
So this is a valid workaround, simply upload with a shortened source directory name and everything works as expected.

The same upload also works if fewer files are selected, so it seems to have to do with the bulk of files selected.

**Expected behavior**
Filenames should be kept regardless of the filename length.

**Screenshots**
Screenshot with malformed filenames:
![grafik](https://user-images.githubusercontent.com/4069646/208903340-087b55d3-7332-4fc1-926b-c4b0ce3c0a76.png)

**Please complete the following information:**
 - - INCEpTION -- 23.8 (2022-06-29 21:24:41, build 4b271961) 
 - OS:  Windows
 - Browser: firefox

**Comment by reckart** [comment]
I believe this is a restriction of Windows and nothing that INCEpTION could do anything about. We simply get the filename the browser sends - that's it. Your browser might be able to send a sensible filename if you enable long path support in Windows.

**Comment by jfiala** [comment]
You're right, the malforming already happens in the request:
![grafik](https://user-images.githubusercontent.com/4069646/208906150-0f2df3cb-9864-49f2-a592-24c13d535fc6.png)

Shortening the source directory name is an easy workaround, if somebody else faces that issue.

**Comment by jfiala** [comment]
This issue can be closed if you don't want to add this to the docs?

**Comment by reckart** [comment]
I don't think very possible quirk needs to be documented, in particular if INCEpTION cannot really do anything about it. That said, I'd consider the issue tracker part of the documentation ;)

**Comment by reckart** [comment]
I don't think very possible quirk needs to be documented, in particular if INCEpTION cannot really do anything about it. That said, I'd consider the issue tracker part of the documentation ;)
