### ISSUE TITLE
Document Metadata icon shows up, but with no content

### ISSUE THREAD

**Issue by jfiala** [inception-project/inception#3653]
**Describe the bug**
I enabled document metadata and imported a document of type Apache CAS XMI (XML 1.1).
The document metadata icon shows up, but it doesn't show any content:

![grafik](https://user-images.githubusercontent.com/4069646/208911446-973e0172-9bef-4c3a-bed7-d60c56620d2b.png)

This is the metadata contained in the document file:
```
    <type3:DocumentMetaData xmi:id="8" sofa="1" begin="0" end="3495" language="x-unspecified" documentTitle="Fachexpertin/Fachexperte Personal Präsidialbüro" documentId="tp_export.json_300_9364702_FachexpertinFachexperte Personal Präsidialbüro.xmi" documentUri="file:/C:/my_annotations/tp_export.json_300_9364702_FachexpertinFachexperte Personal Präsidialbüro.xmi" collectionId="file:/C:/my_annotations/" documentBaseUri="file:/C:/my_annotations/" isLastSegment="false"/>
```

I would expect at least the documentTitle to show up?

**To Reproduce**
Enable document metadata in settings.properties (documentmetadata.enabled=true)
Enable meta layer by creating meta / Document metadata 
Import XMI document (Apache CAS XMI (XML 1.1))
Open annotation editor and open metadata layer

**Expected behavior**
I would expect at least the documentTitle to show up?

**Screenshots**
see above.

**Please complete the following information:**
 - Technische Universität Darmstadt -- Computer Science Department -- INCEpTION -- 26.2 (2022-12-20 19:01:06, build f3ea5caa) 
 - OS: Windows
 - Browser: firefox

**Comment by reckart** [comment]
The DKPro DocumentMetaData  has nothing to do with the Document Metadata feature flag in INCEpTION.

Enabling the feature flag allows you to create document-level layers in the project settings. You can then create such a layer with the fields that are interesting to you and fill them in through XMI files that you generate externally. 

Any of the layers you create in INCEpTION will be in a different namespace than then DKPro Core DocumentMetaData type.

**Comment by jfiala** [comment]
Thank you for clearing that up!

The fields annotated in the document metadata layer are exported as follows:
(here the field testnotes has been added)
```
<custom:Meta xmi:id="6086" sofa="1" testnotes="test"/>
```
So this is as you said completely different from the DocumentMetaData xml tag.

Is there any chance to see the content of the DocumentMetadata in the annotation editor (documentTitle would be nice)?

**Comment by reckart** [comment]
There is currently no way to see the DocumentMetadata in the annotation editor. In theory, you could hack a layer configuration externally for that layer and them import it as a JSON layer configuration - but I would not recommend it because there is a risk that you might accidentally delete this annotation and it could have very bad side-effects.

Right now, I would recommend moving your documentTitle field to your Meta type. Also if you want only a single "Meta" annotation per document, enable the "singleton" behavior on the layer.

**Comment by jfiala** [comment]
Perfect, thank you! The new Meta-extension is very nice for us as we have other properties we like to add...!
