### ISSUE TITLE
The color of the existing layers changes after adding another layer

### ISSUE THREAD

**Issue by 2xXLunAXx2** [inception-project/inception#3656]
**Describe the bug**
Let's say I have two layers. One layer is shown in red and the other one in blue. Now I add another layer. The new layer gets a new color, BUT the colors of the two other layers change (for example, the first layer is now green, the second one is now red and the new layer is yellow).

**To Reproduce**
1. Go to a file with existing layers. 
2. Note the color of each layer.
3. Add a new layer. 
4. Go back to the file and see that the colors of the existing layers changed. 

**Expected behavior**
Each time a layer is added, the colors of the previous layers remain the same. 

**Please complete the following information:**
 - Version and build ID: 25.1
 - OS: Windows
 - Browser: chrome

Thank you!

**Comment by yanirmr** [comment]
If I may, I believe it is important to maintain consistency and predictability in the user interface. When the colors of existing layers change unexpectedly after adding a new layer, it can be confusing and disrupt the user's workflow. It would be more intuitive if the colors of the existing layers remained unchanged, and only the new layer was assigned a new color. This would help to reduce confusion and improve the overall user experience.

**Comment by reckart** [comment]
The colors are by default assigned in a round-robin fashion going over the layers. The problem is probably that the order the layers are gone through is by default alphabetic - which may induce the changes in color you observe. Probably we can fix it in the code by going over the layers in "creation" order.

**Comment by reckart** [comment]
Note that removing a layer would still cause "subsequent" layers to shift their colors.
