### ISSUE TITLE
A change in the number of tags in inceptalytics after updating INCEpTION

### ISSUE THREAD

**Issue by 2xXLunAXx2** [inception-project/inception#3666]
**Describe the bug**
We use inceptalytics (which uses pycaprio) in order to track the number of tags and their type. When we updated INCEpTION from 25.1 to 26.3, the number of tags in some of our older files had suddenly risen by 20%-50%. 
Was there a problem in the calculation before? Did the update fix he problem? Or was the calculation changed now because of some bug?

**To Reproduce**
1. Tag some files (preferably files which were imported into INCEpTION some time ago) with some tags and note the rise in tags in inceptalytics. Remember the number of tags.
2. Upgrade INCEpTION from 25.1 to 26.3.
3. Check the number of the tags in inceptalytics again. 

**Expected behavior**
Inceptalytics should show the same number of tags before and after the update.

**Please complete the following information:**
 - Version and build ID: 26.3
 - OS: Windows
 - Browser: chrome

Thank you!

**Comment by 2xXLunAXx2** [comment]
A followup:
I noticed that a new annotator was added to inceptalytics, INITIAL_CAS, which "tagged" the exact same number of tags as another annotator in our group:
![image](https://user-images.githubusercontent.com/110154717/209942139-8343455a-e753-4223-8641-eefea40cd786.png)

*PLEASE NOTE* that the number of tags under Yanir's (see screenshot) name is the number of tags that he uploaded from a backup version of INCEpTION, after they were accidently deleted from it.

**Comment by reckart** [comment]
The `INITIAL_CAS` is the CAS that is generated from the imported source document and which is used as a template for all the annotator's CASes.

@zesch I think maybe INCEpTALYTICS should filter the INITIAL_CAS out or at least provide an option to do so?

**Comment by reckart** [comment]
Closing this here. Related discussions should be in the INCEpTALYTICS repo.
