### ISSUE TITLE
No longer able to open Wikidata in KB page

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#367]
**Describe the bug**
In the latest code, it is no longer possible to open Wikidata (UKP-local instance) in the KB page.

**To Reproduce**
1. Create a KB using the UKP Wikidata KB URL
2. Try opening that KB in the KB page
3. Page loads forever and eventually fails with a timeout message from the reverse proxy

**Expected behavior**
After a short moment, the KB page loads and shows the concepts in the hierarchy.

Works in  0.3.3-SNAPSHOT (2018-06-27 17:55:14, build f780cd62cc0f7e11178955f0580291db797ddad9)

**Please complete the following information:**
 - Version and build ID: 0.4.0-SNAPSHOT (2018-07-02 13:20:46, build 5bedb5eb63bf9a8a2771fc2f56c0b0bf09a54cc7)

**Comment by naveen2507** [comment]
I tried with [https://query.wikidata.org/sparql
](https://query.wikidata.org/sparql
) , it works for me. 

Can you ping me the Wikidata (UKP-local instance) URl , I don't have that right now.  


![image](https://user-images.githubusercontent.com/10420950/42183710-2c8d0798-7e43-11e8-8f14-12917b351acf.png)


![image](https://user-images.githubusercontent.com/10420950/42183663-04b5ed84-7e43-11e8-8750-b181690098a9.png)

**Comment by naveen2507** [comment]
@reckart Can you help me with the Wikidata (UKP-local instance) URl or where can I find it?

**Comment by reckart** [comment]
Diagnosis showed that the problem was caused by the `read only` flag not being set to `true` in the remote KB with which I tested. Most likely the KB was created before the read-only flag has been introduced. 

The problem could have been easier to detect if the "read-only" checkbox would not be hidden but just disabled in the KB settings for remote KBs.
