### ISSUE TITLE
Active learning may suggest annotations that are not visible on screen

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#369]
**Describe the bug**
There are different situations where the active learning sidebar may ask for feedback on a suggestion that is actually not visible on screen.

**To Reproduce**
At least two cases are known:
* #29 - AL shows recommendation no longer available in the predictions
* #326 - AL shows recommendation hidden during rendering due to overlaps with actual annotations

**Expected behavior**
The AL should only suggest annotations that are actually visible on screen.

**Screenshots**
See:
* #29 - AL shows recommendation no longer available in the predictions
* #326 - AL shows recommendation hidden during rendering due to overlaps with actual annotations

**Please complete the following information:**
- Version and build ID:  0.4.0-SNAPSHOT (2018-07-02 13:20:46, build 5bedb5eb63bf9a8a2771fc2f56c0b0bf09a54cc7)

**Solution**

- [x] Add a field `visible` to the `AnnotationObject`
- [x] the code which determines the visibility of a suggestions needs to be refactored to be CAS-based instead of VDOC-based such that it can be used by `PredictionTask` as well as by  `RecommendationRenderer`
- [x] During prediction, the `PredictionTask` needs to initialize the `visible` field based on which annotations are present in the CAS.
- [x] During rendering, `RecommendationRenderer` needs to update the `visible` flag on the `AnnotationObject` - depending on whether the suggestion is added to the VDOC or not. `setVisible` needs to be called in both cases (visible/not visible) because the visibility state is carried across renderings.
- [x] The AL sidebar needs to listen to the `RenderAnnotationsEvent` (the event is triggered after the `RecommendationRenderer` has completed its work) and check if the suggestion it currently shows is visible or not using `AnnotationObject.isVisible()`. If it is not visible, the AL needs to update itself and present a new visible suggestion.
- [x] `RecommendationEditorExtension.render(JCas, AnnotatorState, VDocument)` needs to generate a even `PredictionsSwitchedEvent`
- [x] The AL sidebar needs to listen to `PredictionsSwitchedEvent` and re-calculate the suggestion ranking. The AL sidebar does not to re-calculate the suggestion ranking every time a user makes an action. Only if there is no ranking yet (i.e. when AL is activated) and if `PredictionsSwitchedEvent` is called (related to #228). The `AnnotationObject.isVisible()` flag is **not** relevant for the moment during ranking because the `RecommendationRenderer` either shows or hides all annotations at the same location. So just rank without taking visibility into account.
- [ ] Remove PredictionsSwitchedEvent and use AjaxPredictionsSwitchedEvent

**Comment by rcffc** [comment]
In PredictionTask::isOverlappingForFeature I want to check if there is already an existing annotation overlapping the prediction for a feature, but I am getting this error:

```
2018-07-03 18:35:42 ERROR [SYSTEM] TaskConsumer - PredictionTask [project=POS, user=admin] failed.
org.apache.uima.cas.CASRuntimeException: Trying to access value of feature "de.tudarmstadt.ukp.dkpro.core.api.lexmorph.type.pos.POS:PosValue" as feature structure, but is primitive type.
	at org.apache.uima.cas.impl.FeatureStructureImpl.getFeatureValue(FeatureStructureImpl.java:239) ~[uimaj-core-2.10.2.jar:2.10.2]
	at de.tudarmstadt.ukp.inception.recommendation.scheduling.tasks.PredictionTask.isOverlappingForFeature(PredictionTask.java:179) ~[classes/:?]
	at de.tudarmstadt.ukp.inception.recommendation.scheduling.tasks.PredictionTask.filterPredictions(PredictionTask.java:156) ~[classes/:?]
	at de.tudarmstadt.ukp.inception.recommendation.scheduling.tasks.PredictionTask.run(PredictionTask.java:114) ~[classes/:?]
	at de.tudarmstadt.ukp.inception.recommendation.scheduling.TaskConsumer.run(TaskConsumer.java:63) [classes/:?]
```

**Comment by reckart** [comment]
@rcffc the proper way of obtaining a feature value would be to get a `FeatureSupport` for the layer/feature that you want to read from the `FeatureSupportRegistry` and then calling `FeatureSupport.getFeatureValue`.

**Comment by reckart** [comment]
Note that this method would create KBHandles for concept features. If you just want to get the string value from the cas, you can use `FSUtil.getFeature(featurestructure, featurename, String.class)`

**Comment by reckart** [comment]
@rcffc @matchlesswei please open a PR as soon as you have the branch ;)

**Comment by rcffc** [comment]
@matchlesswei The problem with the existing annotation is now solved.

**Comment by matchlesswei** [comment]
To make sure, after receiving the `PredictionsSwitchedEvent`, AL sidebar doesn't update the recommendation shown in the webpage right sidebar, just updating the recommendation list maintained in `ActiveLearningRecommender`, right?

**Comment by reckart** [comment]
Any highlight from the AL sidebar in the main part needs to be updated as well. This might lead to the AL highlight disappearing if the new recommendation is not visible in the main part.

**Comment by matchlesswei** [comment]
Is there `RenderAnnotationsEvent` after every `PredictionsSwitchedEvent`?

**Comment by reckart** [comment]
See `recommendationService.switchPredictions(aState.getUser(), aState.getProject());` - so the event is generated as part of the render phase.

**Comment by matchlesswei** [comment]
After updating the left sidebar, does the main editor need to jump to the location of new recommendation?

**Comment by reckart** [comment]
No.

**Comment by reckart** [comment]
Not if the update is triggered by a switch. The jump happens only when the user makes an accept/reject/correct/skip action in the AL sidebar.

**Comment by reckart** [comment]
What happened to the code which updates the visibility state during rendering?

**Comment by reckart** [comment]
@rcffc @matchlesswei one of the todos in the issue description says:

> During rendering, RecommendationRenderer needs to update the visible flag on the AnnotationObject

So it might be a problem of ordering. I guess the `PredictionsSwitchedEvent` is generated at the time the predictions are switched - which is before the `RecommendationRenderer` renders its data (i.e. updates the visibility flag)?

**Comment by rcffc** [comment]
> Should ActiveLearningSidebar also set other recommendations of this token to be invisible after user makes an action? What about a user annotates in the main editor und right sidebar?

Annotations from the right sidebar and accepted recommendations from the main window don't need it, because after a new annotation is created, the rendering process will create new AnnotationObjects anyway, and if on a position there already is a token, it is set to invisible.

> I didn't know which code updates the visibility state during rendering exactly.

In RecommendationSpanRenderer line 110-112, PredictionTask::setVisibility is called.

> So it might be a problem of ordering. I guess the PredictionsSwitchedEvent is generated at the time the predictions are switched - which is before the RecommendationRenderer renders its data (i.e. updates the visibility flag)?

Yes. So, it seems to that the predictions should be given to ActiveLearningSidebar when RecommendationRenderer has finished his work.

**Comment by matchlesswei** [comment]
@reckart 
Suppose a user accepts a suggestion in the al sidebar, after the user presses the button, the following actions should happen:

`set the annotation for this token` ---> `update the visible state` ---> `get the next recommendation` ---> `jump to the next suggestion location`

`actionAnnotate` in the sidebar includes the action: `set the annotation for this token`, `get the next recommendation` and `jump to the next suggestion location`
`PredictionsSwitchedEvent` includes the action `update the visible state of recommendations`

And `actionAnnotate` happens **before** `PredictionsSwitchedEvent` in the al sidebar.

So, `updating the visible state` happens **after** `getting the next recommendation`, that's why the next recommendation of al sidebar is always the old recommendation according to `actionAnnoate`. And even the recommendation updates after `PredictionsSwitchedEvent`, the main page doesn't jump to the corrected recommendation location.

What's the best solution for this problem?

**Comment by matchlesswei** [comment]
Another thing, the recommendation list was maintained in `ActiveLearningRecommender`, but class `ActiveLearningRecommender` cannot receive `PredictionsSwitchedEvent`. So I'd like to move all the functions of this class to `ActiveLearningServiceImpl` and create a state there to store and maintain the recommendation list. Is this all right?

**Comment by betoboullosa** [comment]
After discussing this issue with @matchlesswei , it seemed to us that there are two possible solutions:

1. The method actionAnnotate directly updates the visible state.

2. The actions "get the next recommendation ---> jump to the next suggestion location" be called AFTER the PredictionsSwitchedEvent, meaning that, as a side effect, the main window would jump whenever the recommendation currently visible in the AL sidebar changed (something that @reckart said before that is not desirable).

**Comment by reckart** [comment]
I think that 1 is the best option. However, the AL will also need necessary to explicitly call `RecommendationService.switchPredictions` before updating the visibility since otherwise it would potentially calculate visibility based on outdated predictions.

Instead of re-writing the code which updates the visibility, I think it would be best to implement this in such a way that the `RecommendationService` provides some method `updateRecommendationVisibility` which the AL can call and which is also called by the `RecommendationService` itself during rendering.

**Comment by betoboullosa** [comment]
Is @rcffc then going to create the updateRecommendationVisibility method for @matchlesswei ?

**Comment by rcffc** [comment]
Okay.

**Comment by betoboullosa** [comment]
If it already exists, probably it should be moved to RecommendationService. @matchlesswei , can you please take a look if the existing method fits your needs?

**Comment by matchlesswei** [comment]
From my limited knowledge about the recommendation model, I don't know...

**Comment by matchlesswei** [comment]
RenderAnnotationsEvent (Wicket Event) is used for updating AL sidebar suggestions if the recommendation in the main editor changes.

In the screenshot, the old suggestion in AL sidebar and in the main editor is `Voldmort` for Text Potter. I annotate manually `Harry Potter` in the right sidebar for Text Potter. 
<img width="1280" alt="screen shot 2018-08-13 at 12 44 12" src="https://user-images.githubusercontent.com/23156705/44027643-88f222d2-9ef7-11e8-8335-9a953ffc22cd.png">

The old suggestion `Voldmort` in the main editor is gone after annotation:
<img width="1280" alt="screen shot 2018-08-13 at 12 44 53" src="https://user-images.githubusercontent.com/23156705/44027746-df707dac-9ef7-11e8-8609-91985319c7d5.png">

But the suggestion `Voldmort` is still visible from the recommendation list. I think recommendationService should already set this suggestion to invisible.
![screen shot 2018-08-13 at 12 45 23](https://user-images.githubusercontent.com/23156705/44027808-142703a4-9ef8-11e8-94ba-4db970cd3c67.png)

@reckart @rcffc WDYT about this problem?

**Comment by rcffc** [comment]
> I suppose that the recommendation module already sets invisible for that recommendation. Is it possible that the recommendation module sets invisible only to a list of new updated recommendations, but active learning keeps the old outdated recommendations? So, does it mean that the recommendation module generates new recommendations after every user action?

After every user action, a new training + prediction task is started. New recommendations are not generated after every user action, but rather when a prediction task is finished. During rendering of the BratAnnotator, the visibility of the recommendations are updated. But it is indead strange that it is not updated for `currentRecommendation`... I couldn't figure out why this is the case.

**Comment by reckart** [comment]
@rcffc @matchlesswei is `currentRecommendation` re-fetched from the model/recommendation service? It can be that Wicket internally creates a clone of the recommendation such that whatever object the recommendation service updates is not the same object as the one stored in the AL sidebar. The sidebar will have to ensure it has the latest copy.

**Comment by matchlesswei** [comment]
@reckart after annotating the suggestion, I tried `getPredictionsByTokenAndFeature`, but the visibility status is not updated.

![screen shot 2018-08-20 at 14 12 32](https://user-images.githubusercontent.com/23156705/44340843-67de6080-a486-11e8-81d6-9f4e4ef4cefd.png)

**Comment by reckart** [comment]
Set a breakpoint in the setter method for visibility to see if/when the visibility is actually updated.

**Comment by matchlesswei** [comment]
`setVisibility` is called in the `PredictionTask`:
<img width="629" alt="screen shot 2018-08-21 at 01 05 18" src="https://user-images.githubusercontent.com/23156705/44371279-70fb1c00-a4de-11e8-87d9-b352df152d00.png">

**Comment by rcffc** [comment]
Some observations:
When accepting a recommendation through the Active Learning sidebar, the highlighting is not set. Also it does not appear when the page is refreshed. But when I click on the word in the Active Learning sidebar, the highlighting appears in the right position. It seems like this causes the AnnotationEditor to change predictions. The problem does not occur with reject and skip. 

![refresh-on-click](https://user-images.githubusercontent.com/13070150/44714821-8c55c080-aab6-11e8-9a1f-6e24ab2f7218.gif)

When I create a new annotation, the current recommendation in the Active Learning sidebar is not refreshed.

![does-not-update](https://user-images.githubusercontent.com/13070150/44714823-8d86ed80-aab6-11e8-8837-888ce7ab179b.gif)

**Comment by reckart** [comment]
> And `(Ajax)PredictionsSwitchedEvent` is sent every time a user makes an action(annotate, reject, skip) in a POS task. It is also sent everytime when a user opens the sidebar. Is it normal? Is this event sent in a wrong place?

The `(Ajax)PredictionsSwitchedEvent` is sent after two things happened:
1. new predictions are available (i.e. the recommender background thread has completed)
2. the new predictions are actually rendered to the screen (i.e. the user has performed an action which causes the annotation editor to re-render)

If step 1 completes very quickly, then it might complete even within a single rendering cycle. However, the more annotations the user makes, the larger the project is and not the least depending on which recommendation algorithm is used, step 1 can take considerable time.

**Comment by matchlesswei** [comment]
@rcffc The reason for these observations is that **AnnotationObject is always visible** which I have mentioned in the discussions _several times_. If you read the discussions, you will find that the AnnotationObject in the list of `Prediction` hasn't been set to invisible after a user made an annotation. AL sidebar read the AnnotationObject from the list of Prediction, so al sidebar cannot get the correct next suggestion.

**Comment by rcffc** [comment]
No progress.

**Comment by reckart** [comment]
Closing this issue for the moment as PR #388 has been merged and as the history of this issue is already growing quite long. That said, there might still be an issue with the AL not consistently jumping to the right location. We need to figure this out and if necessary open a new issue.
