### ISSUE TITLE
Deleting an accepted annotation from the history does not delete annotation

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#37]
Removing an accepted item from the active learning history should also remove the annotation that was created by accepting this item.

If the label of the annotation has meanwhile changed, a message should be displayed to the user that the annotation with the recommended label no longer exists.

If the annotation has been deleted, a corresponding message should be displayed to the user.

**Comment by reckart** [comment]
@betoboullosa @matchlesswei What do you think about this?

**Comment by betoboullosa** [comment]
I think it might make sense, but maybe it's not entirely clear to the user that deleting from the history also deletes the annotation. A possible help would be showing a warning like this: "Attention, this action will also delete the corresponding annotation. Proceed?".

**Comment by matchlesswei** [comment]
- first jump to the annotation
- then delete that annotation

**Comment by reckart** [comment]
We have a reusable ConfirmationDialog which could be used here.

**Comment by matchlesswei** [comment]
@reckart so you mean 1. jump to the annotation 2. ask the user for confirmation 3. delete the annotation?

**Comment by reckart** [comment]
Aye. That would incorporate @betoboullosa valid concern.

**Comment by matchlesswei** [comment]
@reckart for deleting the annotation, I think I could use getActionHandler().actionDelete(aTarget), but I need to set the `Selection` before that, right? Do you have any suggestion for setting the `Selection`?

**Comment by reckart** [comment]
Only for accepted annotations if the deletion from the history also triggers a deletion of the actual annotation.

**Comment by reckart** [comment]
`AnnotationDetailEditorPanel.actionDelete(AjaxRequestTarget)` (or via AnnotationActionHandler interface) should be used to trigger the deletion. Mind this might cause a second confirmation dialog to pop up if deleting the annotation triggers the deletion of further annotations (e.g. relations attached to the deleted span).

**Comment by matchlesswei** [comment]
@reckart @betoboullosa 
Do we ask for a confirmation to delete the history and annotation(if user choose cancel, then history is kept)?
Or do we delete that history without confirmation, then ask for a confirmation to delete the annotation?

**Comment by reckart** [comment]
I would say just for the annotation. The history item would be deleted anyway.
