### ISSUE TITLE
Allow import of Preannotated Spacy Doc files

### ISSUE THREAD

**Issue by jonnyfoka** [inception-project/inception#3722]
**Is your feature request related to a problem? Please describe.**

For a relation classification task I have annotated several news like text documents with prodigy annotation software. Prodigy outputs the format in a JSONL file that can be converted into a .spacy file. In the JSONL format, each line represents one news article with its annotations.

Now I want to convert my annotations into a more standardized format like CONLL, so that I can work with my annotations with Inception (Prodigy has not been a good choice). Unfortunatly, I haven't found any lib, script or tool that can convert prodigy Jsonl/Spacy to CONLL.

**Describe the solution you'd like**
Allow to import pre-annotated documents with .spacy format. 

**Describe alternatives you've considered**
Pre-annotated .spacy Doc converter (e.g. for CONLL-U)

**Comment by reckart** [comment]
Note that if you want to map your data to custom annotation layers in INCEpTION, then you should use UIMA CAS XMI (dkpro-cassis) - CONLL-U will only help if you stick to the handful of layers that CONLL-U / INCEpTION's CONLL-U-reader/writer support.

**Comment by reckart** [comment]
Closing as there was no further feedback.
