### ISSUE TITLE
ArrayIndexOutOfBoundsException when uploading file

### ISSUE THREAD

**Issue by RobinSchaefer** [inception-project/inception#3724]
**Describe the bug**
We receive an ArrayIndexOutOfBoundsException when uploading an WebAnno TSV 3.3 file that we created from original brat annotations. 

**To Reproduce**
1. Create a project with the following customized features, etc. 
    - Layer: ArgumentComponent
    - Feature: UKP
    - Tagset connected to UKP: MajorClaim, Claim, Premise
2. Upload essay001.tsv using WebAnno TSV 3.3 format

**Expected behavior**
The upload will fail and the ArrayIndexOutOfBoundsException message will appear (see screenshot_error_message.png).

**Screenshots**
![screenshot_error_message](https://user-images.githubusercontent.com/23155320/212673656-6313e6ec-3e83-4cec-9089-3a1be3dec90c.png)
![screenshot_example_annotation](https://user-images.githubusercontent.com/23155320/212673703-0c48a2bf-c982-4018-883a-3e2aa8f52c80.png)
![screenshot_project_layer_tagset](https://user-images.githubusercontent.com/23155320/212673749-ff66bb81-75fa-48b7-934e-b70ff6217590.png)

**Please complete the following information:**
 - Version and build ID: INCEpTION -- 24.1; build 631d180b
 - OS: Linux
 - Browser: Chrome

**Additional context**
essay001.tsv will be sent by email.

**Comment by reckart** [comment]
@RobinSchaefer thanks for the report.

So the reason why your file does not import is that every line that should be empty instead contains `""`. If you globally search/replace `""` with nothing, the import works on my machine.
