### ISSUE TITLE
Allow opening URL feature values in new browser window

### ISSUE THREAD

**Issue by letailli** [inception-project/inception#3728]
**Is your feature request related to a problem? Please describe.**
We use document metadata to store the URLs from which the documents we annotate originate. The problem is that these URLs appear as a string (we use the "Primitive:String" feature type) and it's not convenient to open the link: users have to copy the link, open a new tab, paste.

**Describe the solution you'd like**
Add a feature type "URL" that would enable to open the link in a new tab. This would be close to the feature "Image URL" behavior.

**Additional context**
This demand comes from @rbossy (@Bibliome) with whom I'm currently working.

**Comment by reckart** [comment]
How about we enhance the existing string feature to auto-detect if a feature value is a valid URL and if so display a button to open that URL in a new window? 

That would only happen if no tagset is associated with the feature (i.e. the feature editor is only a simple input field).

Would that work for you?

**Comment by rbossy** [comment]
That would be both pretty and useful.

I suppose that this would not cover properties bound to a KB. Those URIs aren't always dereferenceable.

**Comment by reckart** [comment]
When you link to a KB, a concept-feature-editor is used. The single-value concept-feature-editor already has a button to open the IRI in a new tab (which may fail if the IRI is not resolvable).

**Comment by reckart** [comment]
@rbossy @letailli If you have not already tried this feature in SNAPSHOT or beta versions, there is now a release candidate available containing this feature so you can test it: https://github.com/inception-project/inception/releases/tag/inception-27.0-rc-1
