### ISSUE TITLE
Selectively import documents

### ISSUE THREAD

**Issue by betoboullosa** [inception-project/inception#373]
**Is your feature request related to a problem? Please describe.**
Currently, there is no method for selecting which result documents to import, they are always imported when their content is inspected.

**Describe the solution you'd like**
Add a button to allow importing the desired documents.
 
**Describe alternatives you've considered**
Importing in bulk will be done in a future issue.

**Comment by az79nefy** [comment]
Inspecting the content of the document no longer automatically imports the document.
Result documents now are only imported when a separate link in the "Action" column is clicked.
Should I add a button instead of the link?

**Comment by reckart** [comment]
If you ask me, the layout of the entire search results should be changed to be more like the interface we used in READER. So I wouldn't invest time at the moment into improving the current layout.

**Comment by az79nefy** [comment]
Then this can be closed, since the functionality of selectively importing documents is already implemented.
We can discuss the layout change in #372
