### ISSUE TITLE
OAuth Unable to Configure

### ISSUE THREAD

**Issue by blochsbek** [inception-project/inception#3731]
Hi @reckart ;

I'm having a terrible time trying to configure OAuth with Auth0, with regards to set-up, it won't seem to accept configurations that should be working. 

**To Reproduce**
1. Attempt to set-up OIDC with Auth0 using a web app set up with a config such as:
```
    spring.security.oauth2.client.registration.inception-client.client-name=Auth0
    spring.security.oauth2.client.registration.inception-client.client-id=imaclientid
    spring.security.oauth2.client.registration.inception-client.client-secret=imasecret
    spring.security.oauth2.client.registration.inception-client.scope=openid, profile
    spring.security.oauth2.client.registration.inception-client.authorization-grant-type=authorization_code
    spring.security.oauth2.client.registration.inception-client.redirect-uri=https://urlofinceptionrunning/login/oauth2/code/inception-client
    spring.security.oauth2.client.provider.inception-client.user-name-attribute=preferred_username
    spring.security.oauth2.client.provider.inception-client.authorization-uri=https://<ourdomain>.auth0.com/authorize
    spring.security.oauth2.client.provider.inception-client.token-uri=https://<ourdomain>.auth0.com/oauth/token
    spring.security.oauth2.client.provider.inception-client.jwk-set-uri=https://<ourdomain>.auth0.com/.well-known/jwks.json
    spring.security.oauth2.client.provider.inception-client.user-info-uri=https://<ourdomain>.auth0.com/userinfo
    spring.security.oauth2.client.provider.inception-client.issuer-uri=https://<ourdomain>.auth0.com/
    spring.security.oauth2.client.provider.inception-client.client-authentication-method=post
    spring.security.oauth2.client.registration.inception-client.redirect-uri=https://urlofinceptionrunning/login/oauth2/code/inception-client
```
2. Get errors like invalid code, or other authorization errors.

**Expected behavior**
Auth0 would be a supported OIDC provider and these settings would work.

**Additional context**
Auth0 provides a Spring SDK https://auth0.com/docs/quickstart/webapp/java-spring-boot/01-login and might be helpful to get it working as an option

This config is how other OIDC apps are enabled, and it works quite well, this should be working but isn't....

**Comment by reckart** [comment]
I know that I got it working with Keycloak and I have received feedback that based on the Keycloak examples that I provided other people were also able to get it working with their Keycloaks and even with Azure. 

I'm afraid, I do not know Auth0's service. Normally, I believe it should not be necessary to configure all the URLs individually if the service provides a proper auto-discovery descriptor relative to the `issuer-uri`.

Maybe I can provide ideas if you provide error messages...?

**Comment by blochsbek** [comment]
Is there a way to get expanded logs from Inception? The auth0 error we get is a "Failed Exchange" for the authorization code itself.

**Comment by reckart** [comment]
Try adding these config properties:

```
logging.level.org.springframework.security=TRACE
logging.level.de.tudarmstadt.ukp.inception.security=TRACE
```

**Comment by blochsbek** [comment]
Logs can be found below, just getting an unauthorized result from Auth0, which is quite odd, because it's getting a code....

[inceptionlogs.txt](https://github.com/inception-project/inception/files/10448057/inceptionlogs.txt)

**Comment by reckart** [comment]
```
2023-01-18 15:20:38 TRACE [SYSTEM] OAuth2LoginAuthenticationFilter - Failed to process authentication request
org.springframework.security.oauth2.core.OAuth2AuthenticationException: [invalid_token_response] An error occurred while attempting to retrieve the OAuth 2.0 Access Token Response: 401 Unauthorized: [no body]
```

Look like your IdP is sending back an empty request. Normally, it should send back a response that contains the assertions about the authenticated user, no?

**Comment by reckart** [comment]
So I'm not the guy that wrote the book on OAuth, but it appears to me that this happens after your IdP has redirected back to INCEpTON and while INCEpTION is trying to obtain more information from the IdP - and whatever it tries to obtain, the IdP seems to send back `401 Unauthorized` as a response instead of a decent answer. 

Maybe try removing all the `uri` settings except the `issuer-uri` and let the thing auto-configure itself?

**Comment by blochsbek** [comment]
Sonofa... Close this out. User error. PEBKAC

**Comment by reckart** [comment]
Roger :) Happy it works.

**Comment by blochsbek** [comment]
OK, I fixed it. It's a bit weird, but it works. What method are you using to authenticate the token?

**Comment by reckart** [comment]
What do you mean by "what method"?

**Comment by blochsbek** [comment]
Validation of a token: The requested authentication method for the token endpoint. Possible values are 'None' (public application without a client secret), 'Post' (application uses HTTP POST parameters) or 'Basic' (application uses HTTP Basic).

**Comment by reckart** [comment]
In my configuration, I just gave Spring Security a client-id/client-secret and it "just works"™️ - My guess would be that Spring Security  uses a POST request. I don't see any settings that would seem relevant to that question in Keycloak either.

**Comment by reckart** [comment]
In its client registration metadata, keycloak tells me: 

```
token_endpoint_auth_methods_supported":["private_key_jwt","client_secret_basic","client_secret_post","tls_client_auth","client_secret_jwt"]
```
