### ISSUE TITLE
Annotators per document for Static Workload

### ISSUE THREAD

**Issue by GiantEnemyCrab** [inception-project/inception#3757]
While Dynamic Workload can specify "Annotators per document", it will be great to have that option in Static Workload as well.
Some group of people use external work management, like JIRA to assign subsets of documents  for annotators.
This is to be able to assign specific workload ahead of time and also that work being tracked with all other work in a single JIRA system, for example.

Dynamic Workload would not be used unfortunately in this kind of environment, but there is a great concept that is helpful to be applied to static workload, such as "annotators per document".

Let's say that 8 annotators get assigned to one project. Only 2 annotators need to complete per document.
It's a bit tedious to lock documents, per range of documents per annotator, and if a new annotator gets added, batch locking will need to be done for the new annotator.

Once 2 annotators complete annotation, the document status moves to ANNOTATION-COMPLETE, and clearer for curators to pick up the work, because currently unless all annotators complete the work, it stays in ANNOTATION-IN-PROGRESS state, so it is hard to distinguish which document has reached the desired number of annotators completion per document.

The "annotators per document" should be specifiable for static workload.

**Comment by reckart** [comment]
Why not use the dynamic workload in this scenario?

**Comment by GiantEnemyCrab** [comment]
Does dynamic workload allow assignment of specific number of documents per annotator?
That might sound like static, but an idea is it's semi-static, but dynamic too.
Annotators will keep getting new documents without being specified which documents by project managers.

Does dynamic workload allow unlimited number of notes per annotator?  If so, the feature request here is to apply some limit if unlimited. My team wants to distribute specified amount of work per annotator, and if the annotator is done with the assignment, the annotator moves onto a different project.

**Comment by reckart** [comment]
> Does dynamic workload allow assignment of specific number of documents per annotator?

Dynamic mode currently focusses on maximizing throughput. Limiting the number of documents per annotator wound introduce an element of "fairness" into the process such that not one annotator would be able to grab all the work - however, it would also potentially reduce throughput. 

From your response, I assume this element of "fairness" is important to you, right? It is not that you really want to meticulously assign specific documents to specific users. 

> Does dynamic workload allow unlimited number of notes per annotator?

What is a "note" in this context?

> My team wants to distribute specified amount of work per annotator, and if the annotator is done with the assignment, the annotator moves onto a different project.

Ok, so if the dynamic workflow mode had an option to impose an upper limit on the number of documents that annotators should annotator, it would resolve your need, right? So in addition to the "max annotators per document" setting that the dynamic workload already has, you are asking for a "max documents per annotator" setting?

**Comment by GiantEnemyCrab** [comment]
Yes that's precisely right, "max documents per annotator", that it is good to have mechanism to prevent "fast annotators" to end up completing pretty much all documents without giving chance to others.
And that will make it possible to even out the work distribution too, while still benefiting the convenience of dynamic workload feature.

"Note" would be each document/file in inception.

**Comment by reckart** [comment]
Solved by https://github.com/inception-project/inception/pull/4718
