### ISSUE TITLE
Export is not working after update

### ISSUE THREAD

**Issue by andrerenis** [inception-project/inception#3797]
Nothings happens any more after click on export under settings, regardless which format you choose. In the log-file everything seems right, you can see that files are collected but nothing is happening! I upgraded to 26.6, but still the same. In an older version it worked. 

I attached a demo project. https://box.hu-berlin.de/d/fd3c3816fc314cb0aae8/

Server is running on debian 10 with nginx proxy
Client is chromium/latest on ubuntu
[inception.tar.gz](https://github.com/inception-project/inception/files/10662247/inception.tar.gz)

java -version
openjdk version "11.0.16" 2022-07-19
OpenJDK Runtime Environment (build 11.0.16+8-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Debian-1deb10u1, mixed mode, sharing)

Thank you! 
André

**Comment by reckart** [comment]
Which version was the "older" version?

**Comment by andrerenis** [comment]
I don't  remember, exactly, it has been the version which came out immediately after the log4j-bug

**Comment by reckart** [comment]
My guess would be that it was a pre-websocket version and that you are running behind a reverse proxy that needs its configuration to be updated to support the new websocket-based features of INCEpTION. Please check the reverse proxy configuration section in the Admin Guide to see if you need to update your reverse proxy configuration.

**Comment by andrerenis** [comment]
You are right. It's a websocket problem with the nginx reverse proxy. Thank you! Do you know if I can turn off WS?

**Comment by reckart** [comment]
Yes, but eventually the option to turn it of will disappear. You should better fix your proxy configuration.

To disable, add `websocket.enabled=false` to your `settings.properties`.

**Comment by andrerenis** [comment]
Thank you again!
