### ISSUE TITLE
Bulk curation

### ISSUE THREAD

**Issue by parvva** [inception-project/inception#3806]
**Is your feature request related to a problem? Please describe.**
We like to merge annotated files which have more than a threshold agreement automatically and without going to curation process

**Describe the solution you'd like**
an option to bulk merging or curation

**Describe alternatives you've considered**
for now the curator opens every file in curation and without any curation locks it as done

**Additional context**
It is valuable for projects without curator or/and with large number of documents

**Comment by reckart** [comment]
Duplicate of https://github.com/inception-project/inception/issues/4768
