### ISSUE TITLE
Cannot set value in concept feature editor when there are constraints

### ISSUE THREAD

**Issue by ahoo1260** [inception-project/inception#3813]
We are using the latest version (26.7) of Inception. We have uploaded a KnowledgeBase file (see attached ) . We are using it as a feature to a layer.  Meanwhile we defined **constraints** on a layer in this project.   

During annotation, when we want to select from this feature, it does the search, it finds the match:

![image](https://user-images.githubusercontent.com/26032359/218708650-eb31d92b-c2b6-48dd-98c5-303dc0732b73.png)

but when I click on the matched term, the whole page crashes (Even when the constraints is empty (just the automatic comment line), the error happens. I get this error in the log :

```
VM8131:1 Uncaught TypeError: Cannot read properties of undefined (reading 'dataItem')
    at Wicket.Ajax.ajax.dep (<anonymous>:1:1078)
    at Object._calculateDynamicParameters (wicket-ajax-jquery-ver-6C3579C63E0C4EBFA954D232A7F1B943.js:1:4788)
    at Object.doAjax (wicket-ajax-jquery-ver-6C3579C63E0C4EBFA954D232A7F1B943.js:1:6164)
    at Object.<anonymous> (wicket-ajax-jquery-ver-6C3579C63E0C4EBFA954D232A7F1B943.js:1:4990)
    at i (jquery-3.6.0-ver-7B432A70897DCD6A8F6D26413CDF1916.js:2:88757)

```
When we try the same steps( we tried same steps using another kb as well ) in a new project, which **does not have constraints**, it works as expected. So, we believe that it is the constraints which causing the issue.

 - Version and build ID: 26.7
 - OS: Linux (ubuntu 20.04)
 - Browser: chrome
 - The kb file to reproduce the error:

[gdprov.ttl.txt](https://github.com/inception-project/inception/files/10731362/gdprov.ttl.txt)

Could you please help with this issue?

**Comment by reckart** [comment]
Did you find an RDF version of Snowmed somewhere or did you prepare it yourself?

**Comment by ahoo1260** [comment]
@reckart we investigated more on this issue and we have more information now. I have updated this issue.

**Comment by reckart** [comment]
@ahoo1260 have you tried transferring the constraints from the broken project to the working project to see if they break it?

Can you provide a minimal example project export that contains such constraint rules?

**Comment by ahoo1260** [comment]
I tried creating a project without constraints which is working properly. Then I imported the constraints and the same error is happening. I am sharing the project here. I hope it answers your question. 

[test15955908078397902334.zip](https://github.com/inception-project/inception/files/10733114/test15955908078397902334.zip)

**Comment by reckart** [comment]
Thanks for the report, that was a good catch. I think I have a fix :)

Still, I wonder if the Snowmed RDF KB you are using is publicly available anywhere?

**Comment by ahoo1260** [comment]
@reckart Thank you for quick fix. Will you make a new release or shall we pull it from repo? 
About the Snomed, we have downloaded it from here https://www.nlm.nih.gov/research/umls/licensedcontent/snomedctfiles.html and then we converted it to RDF by https://github.com/IHTSDO/snomed-owl-toolkit

**Comment by reckart** [comment]
INCEpTION 26.8 has been released yesterday. Best subscribe to the mailing list or watch the project to get release notifications.
