### ISSUE TITLE
Export stops with error message

### ISSUE THREAD

**Issue by Jonathan-ipn** [inception-project/inception#3823]
I download the whole project every week via "export" for a backup. However since last week whenever I click on "Export the whole project" it stops after 90% and I get the following error message:

> WHOOPS!
> Request path | /whoops
> -- | --
> 25.2 (2022-10-25 17:41:05, build 4a7663f9)
> Ubuntu 11.0.17
> Linux 5.4.0-139-generic amd64

I tried this on Chrome as well as Firefox and get the same problem.
I also tried different formats.
If I only download curated documents, it works
As the project gets larger every week due to many annotations and the download also gets slower every week, my initial assumption is, that our project is to big? Is there a data limit?

Is there any other way to backup the project, besides the "export" function?

**Comment by reckart** [comment]
Can you please check in the server logs if you see a related exception with a stack trace that you could share with us?

**Comment by reckart** [comment]
There are no particular limits implemented in INCEpTION, but of course you could at some point run out of memory when performing certain actions. Export should not be such an action.

You should not endlessly grow a project - better create new projects.

**Comment by reckart** [comment]
Closing as no additional input has become available that could be used to further investigate the problem.
