### ISSUE TITLE
External NER recommender errors since last version

### ISSUE THREAD

**Issue by Atlogit** [inception-project/inception#3843]
The external recommendations for NER used to work. Since last month (26.8 version, I think) the results registered in INCEpTION are one entity label for the **whole text** as one span. It acts as a document classifier rather than words NER.
It seems that the external recommender receives and parses data correctly, so this may be an issue with the results registration back in INCEpTION. A PoS recommender running in parallel works fine and results register as always (per word).

*hint*: I think it is related to the new Editable Segmentation. I enabled the ui.sentence-layer-editable, and started using it to tag sentences. Sometime later I noticed the NER issue. The issue persists regardless of whether the sentence layer exists in the project. I haven't tried to disable the feature completely and check if NER goes back to normal (too afraid to lose the sentences segmentation on the annotated documents).

**Comment by reckart** [comment]
The ability to edit sentence segmentation is experimental for a reason ;) It is pretty much unknown which side effects it has.

What are your layer settings for the NER layer, in particular the granularity and whether cross-sentence annotations are allowed?

Does your external recommender ensure that its suggestions are made inside the boundaries of the sentences?

Can you add logging output to your recommender to see the offsets of the annotations that it creates?

**Comment by Atlogit** [comment]
I'm not sure the issue is with sentence segmentation. As mentioned, the NER label recommendation is on the entire text, but the sentence layer works OK.
NER layer settings (custom layer, not default Named Entity layer): 
Internal Name: webanno.custom.CategoryType
Type: Span
Validation: Always
Granularity: Token-level
Overlap: Any
Allow crossing sentence boundaries: no
Show span text in tooltip popup: Yes

> Does your external recommender ensure that its suggestions are made inside the boundaries of the sentences?

I'm not sure. I'm using the spaCy NER, as in the external recommender examples. I'm not sure how to add logging output to se the offsets of the annotations. Can you point me to that direction?

**Comment by reckart** [comment]
Btw. have you tried (temporarily) downgrading to another version of the 26.x line to check if the problem disappears?

**Comment by Atlogit** [comment]
I will try.

**Comment by reckart** [comment]
Btw. I have tried the spacy NER locally and didn't observe the problem so far. But I also didn't enable the sentence layer and play around with it yet.

**Comment by Atlogit** [comment]
Update: The issue is with my model, NOT with INCEpTION.
I found an older model that works as intended. I'm not sure what changed, since everything seems to be the same in the configs.
The only log difference I see is that when the external NER recommender gets the request on the old and working model, it prints a list of the words in the text: ['word1', 'word2', 'word3', '.'] and an empty dict: ()
With the new faulty models, where I get the one annotation across all text, it prints the list the same, but the dictionary includes the document: ( word 1 word 2 word 3 .,)
If you have any idea about it, please share, but all in all - issue is canceled as far as INCEpTION is concerned.

**Comment by reckart** [comment]
Thanks for letting us know that you found the issue on your side.
