### ISSUE TITLE
Webserver should run on a headless setup

### ISSUE THREAD

**Issue by DavidNemeskey** [inception-project/inception#3854]
**Is your feature request related to a problem? Please describe.**
I would like to run INCEpTION as a web server on a headless system. Currently this is not possible because it tries to show the splash screen, which won't work with a headless JRE (no `awt`).

For us, a main use case would be to install INCEpTION on server and give annotators access to it. Having all of them install INCEpTION on their own computers would be suboptimal and would introduce a lot of user errors. Unfortunately, the INCEpTION web server does not run in headless mode. 
 
**Describe the solution you'd like**
I don't think it makes much sense to have a native splash screen for a web server. Simply removing it would allow the web server to run on a headless system. I have tried it and it works perfectly.

Another option would be to catch the error (`java.lang.UnsatisfiedLinkError` / `java.lang.reflect.InvocationTargetException`) and move forward silently if the splash screen cannot be displayed. Or semi-silently, printing something to the effect of "_Looks like you are running INCEpTION in a headless setup; skipping splash screen_".

**Describe alternatives you've considered**
An alternative would be to add a `--headless` argument to the JAR file.

Another alternative would be to install a fake X server, such as Xvfb. However, this is something only the user can do, and I see no point in forcing them do anything when the issue could be solved perfectly well within the application.

**Comment by reckart** [comment]
Start with `-Djava.awt.headless=true`.

**Comment by reckart** [comment]
@DavidNemeskey So, I tried reproducing this:

* I ran a basic docker image without X11 libraries installed (`docker run -it openjdk:11` - same we use for the INCEpTION docker image)
* copied the INCEpTION standalone JAR into it
* execed into the container `docker exec -it CONTAINER_ID /bin/bash`
* started inception `java -jar inception-app-webapp-28.0-SNAPSHOT-standalone.jar`

I got no error. At the end of the startup procedure, I got:

```
2023-03-08 19:03:14 INFO [SYSTEM] StandaloneShutdownDialogManager - Console: available
2023-03-08 19:03:14 INFO [SYSTEM] StandaloneShutdownDialogManager - Headless: yes
2023-03-08 19:03:14 INFO [SYSTEM] StandaloneShutdownDialogManager - Running in server environment or from command line: disabling interactive shutdown dialog.
2023-03-08 19:03:14 INFO [SYSTEM] StandaloneShutdownDialogManager - You can close INCEpTION from the command line by pressing Ctrl+C
2023-03-08 19:03:14 INFO [SYSTEM] StandaloneShutdownDialogManager - You can now access INCEpTION at http://localhost:8080/
```

I wonder what went wrong on your machine. Have you possibly installed a non-headless JRE (i.e. one linked against X11) onto a headless machine?

**Comment by reckart** [comment]
What OS are you using?

**Comment by DavidNemeskey** [comment]
KDE is the desktop environment, KDE Neon is the name of the OS. But yes,
it's Ubuntu under the hood.

**Comment by reckart** [comment]
I can reproduce the issue in an Ubuntu VM. 

It seems that I had a different understanding of what a "headless JRE" is than the developers of those "headless JRE" packages that ship with Ubuntu. 

In had the believe that a "headless JRE" is one that has been compiled without support for graphical user environments, thus having a smaller binary size and dependency footprint. Such a version would always return `true` when asked whether it was headless. Looks like that was wrong as according to the [OpenJDK build instructions](https://hg.openjdk.org/jdk-updates/jdk9u/raw-file/tip/common/doc/building.html), it seems that building the JDK/JRE always requires graphics and sound libraries, even if the intention is to have only a "headless" build.

So, anyway, since I can now reproduce it, I can check if catching the exception and handling it is an option.

**Comment by reckart** [comment]
I am still wondering why I could start INCEpTION nicely without the `headless` system property inside the OpenJDK Docker container that -as far as I could see- didn't include any X11 libraries. Maybe I just missed them when I listed the packages.... odd.

**Comment by reckart** [comment]
IMHO this is a problem with the Ubuntu OpenJDK/OpenJRE packages.

@DavidNemeskey I had a brief look at the Ubuntu Launchpad Bugs tracker, but I did not find a corresponding bug report Maybe you could check as well and consider opening a bug report upstream as well and telling them that their "headless" packages are in fact claiming to be not headless?

Ubuntu with "headless" openjdk 11:

```
$ uname -a
Linux ubuntu-linux-22-04-desktop 5.15.0-67-generic #74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

$ java -version
openjdk version "11.0.18" 2023-01-17
OpenJDK Runtime Environment (build 11.0.18+10-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.18+10-post-Ubuntu-0ubuntu122.04, mixed mode)

$ jshell
Mar 10, 2023 8:15:50 AM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
|  Welcome to JShell -- Version 11.0.18
|  For an introduction type: /help intro

jshell> java.awt.GraphicsEnvironment.isHeadless()
$1 ==> false

jshell> 
```

OpenJDK Docker container:

```
# uname -a
Linux 0ea268728bd0 5.15.49-linuxkit #1 SMP PREEMPT Tue Sep 13 07:51:32 UTC 2022 aarch64 GNU/Linux

# java -version
openjdk version "11.0.16" 2022-07-19
OpenJDK Runtime Environment 18.9 (build 11.0.16+8)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.16+8, mixed mode, sharing)

% docker run -it openjdk:11
Mar 10, 2023 6:17:38 AM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
|  Welcome to JShell -- Version 11.0.16
|  For an introduction type: /help intro

jshell> java.awt.GraphicsEnvironment.isHeadless()
$1 ==> true

jshell>
```

**Comment by reckart** [comment]
For good measure, if I run Ubuntu using Docker, I get

```
% docker run -it ubuntu
# apt update
# apt install openjdk-11-jdk-headless
# uname -a
Linux bbd304b27a3b 5.15.49-linuxkit #1 SMP PREEMPT Tue Sep 13 07:51:32 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

# java -version
openjdk version "11.0.18" 2023-01-17
OpenJDK Runtime Environment (build 11.0.18+10-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.18+10-post-Ubuntu-0ubuntu122.04, mixed mode)

# jshell
Mar 10, 2023 7:25:15 AM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
|  Welcome to JShell -- Version 11.0.18
|  For an introduction type: /help intro

jshell> java.awt.GraphicsEnvironment.isHeadless()
$1 ==> true

jshell>
```
