### ISSUE TITLE
Provide information why a layer cannot be deleted

### ISSUE THREAD

**Issue by DGKore** [inception-project/inception#3857]
I use inception to annotate data in my browser. In my annotation project I created several layers. I've decided not to use some of them. I was able to disable them, but I want to remove them completely from the list of layers. However, when I click on one of those layers and try to remove it by clicking on the three vertical dots in the "Layer Details"-section (next to the cancel button), I cannot click the "Delete"-button. It simply does not work. The red colour of the button is also muted. How can I solve this problem? I need to have those layers removed, simply disabling them is not sufficient.  
Thank you in advance for your help!

**Comment by reckart** [comment]
Span layers cannot be removed as long as a relation layer is connected to them. First remove the relation layers, then you should be able to remove the span layers.

**Comment by reckart** [comment]
Same if the layer is used as the target of a link feature. In that case, you'd have to delete the feature first.

**Comment by reckart** [comment]
@DGKore Upcoming versions will display which layers/features are blocking the deletion of a layer:

<img width="971" alt="Screenshot 2023-03-11 at 15 37 28" src="https://user-images.githubusercontent.com/1410238/224490618-5286e435-750e-4b92-a504-bf9daff18f7a.png">
