### ISSUE TITLE
warning when running inception latest versions

### ISSUE THREAD

**Issue by Atlogit** [inception-project/inception#3882]
### Describe the bug

On the server there is a recurring warning when starting the db (maria(:
`db_1  |  [ERROR] Incorrect definition of table mysql.column_stats: expected column 'hist_type' at position 9 to have type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB','JSON_HB'), found type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB').`
and
`db_1   | [ERROR] Incorrect definition of table mysql.column_stats: expected column 'histogram' at position 10 to have type longblob, found type varbinary(255).`

This has been going on for a few versions. I haven't witnessed any issues with running the software because of this warning, but thought this might interest you.

### Environment

Version and build ID: see bottom of the INCEpTION browser screen
Operating system: e.g. Windows, Linux, OS X
Browser: e.g. Chrome, Safari, Firefox, ...

**Comment by reckart** [comment]
It seems that those columns are not part of the INCEpTION database schema but rather of the internal MariaDB / MySQL DB schema. You might have to perform maintenance on your database. E.g. There is a command called [mariadb-upgrade/mysql_upgrade that checks and updates your tables to the latest version](https://mariadb.com/kb/en/mysql_upgrade/) which might help. But be sure to have a backup of your DB before trying maintenance.

**Comment by reckart** [comment]
It could also be that you are still using a database schema that was originally created using a MySQL database and then switched to using it with a MariaDB. You might consider exporting your data from the database, setting up the installation from scratch and importing your data back again. Be sure to keep a restorable backup.
