### ISSUE TITLE
Annotations not created if mouse is released on empty space

### ISSUE THREAD

**Issue by maks1812** [inception-project/inception#3890]
**Describe the bug**
The process of creating a new span became too sensitive to where your mouse lies. Span will be created only if you release the mouse on exactly the last character. That wasn’t the case  before the 27.1 version
  
**To Reproduce**

highlight multi-words span (mainly words ending with "I") and release the mouse. Span will not be created

**Expected behavior**
Span should be created.

**Screenshots**
![Screenshot_no_span_if_release](https://user-images.githubusercontent.com/47788759/226672402-3c57143c-b26c-47b5-a497-06b67bd60e76.jpg)

**Please complete the following information:**
 - Version and build ID: 27.1 build 93bb6f04
 - OS: Linux
 - Browser: FireFox , Google as well

**Additional context**
-

**Comment by reckart** [comment]
I cannot reproduce it with v27.1 for text that is in the middle of a sentence.

https://user-images.githubusercontent.com/1410238/226689742-b5fa6aad-38b5-4e69-9e3c-4a44931fc5e0.mp4

However, I can your problem when the text is at the end of a line and I release the mouse to far to the right in an area where there is no text anymore.

Do you remember what the last version was that you used before v27.1?

**Comment by blochsbek** [comment]
26.6
