### ISSUE TITLE
Languages written from right to left

### ISSUE THREAD

**Issue by EsraaK-009** [inception-project/inception#3893]
Hello, 
I find inception great, so thanks a lot for this tool!
I was trying to work with another language (Arabic) and it works but with one problem, it reverses the words, making it from left to right. I tried to change the format and add codes to my txt file and it didn't work. I tried also the lazy approach and change the style itself.

I was asking if there is a way to do this that I don't know. And if there's not, can someone please point me to where I can start if I wanted to add this? I've gone through the code but I didn't work that much with java so I'm kind of lost. 

Thanks!

**Comment by reckart** [comment]
Go to the to project settings and there to the "annotation" panel. Set the script direction to RTL or to allowing the annotator to choose. If you set it to the latter option, you have a button to switch between RTL/LTR on the annotation page action bar.

**Comment by EsraaK-009** [comment]
Thanks a lot
I don't know how I didn't notice this. 
Thank you again
