### ISSUE TITLE
Accept best button missing from recommendation sidebar

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#3909]
I'm using 27.2, but I cannot spot an "Accept best" button. I didn't mention that I'm using a remote recommender.

![image](https://user-images.githubusercontent.com/6357197/228352776-2926d18a-c770-46d7-ae23-ba0d5cb81d3d.png)

_Originally posted by @senier in https://github.com/inception-project/inception/discussions/3902#discussioncomment-5458282_

**Comment by senier** [comment]
Let me know if you want me to provide more information or test a development version.
