### ISSUE TITLE
WebSocket connection to 'wss://inception.myorg.org/ws' failed: 

### ISSUE THREAD

**Issue by fishfree** [inception-project/inception#3910]
I use the latest 23.7 release docker-compose.yml [here](https://inception-project.github.io/releases/23.7/docs/admin-guide.html#_docker_compose). I run the commands below:
```
$ sudo mkdir -p /srv/inception/app-data
$ sudo mkdir /srv/inception/app-data
$ sudo chown -R theloggedinusername /srv/inception
$ touch /srv/inception/app-data/settings.properties
$ cat > /srv/inception/app-data/settings.properties << EOF
wicket.core.csrf.enabled=false
wicket.core.csrf.no-origin-action=allow
wicket.core.csrf.conflicting-origin-action=allow
server.servlet.context-path=/inception
EOF
$ export INCEPTION_HOME=/srv/inception/app-data
$ export INCEPTION_DB_HOME=/srv/inception/db-data
$ docker-compose -f docker-compose.yml -p inception up
```
Then, I set up an nginx reverse proxy strictly as the config [here](https://inception-project.github.io/releases/27.3/docs/admin-guide.html#_nginx_as_reverse_proxy), exceptionally change the domain name to my own.

Then I can login in INCEpTION, creat a project and redirect to the project page, there is error in the F12 console as described in the issue title. Also in the docker-compose logs -f, there is an error: 
`app_1  | 2023-03-29 22:59:48 ERROR [SYSTEM] DefaultHandshakeHandler - "Handshake failed due to invalid Upgrade header: null"`
But in the F12 tools, the "Connection: Upgrade" header has been requested as the screenshot below:
![image](https://user-images.githubusercontent.com/1741341/228698885-ff7475bd-f083-4a4c-811b-d8b6c1d6caae.png)

**Comment by reckart** [comment]
In order for WebSocket to work, CSRF needs to be configured properly - not turned off.

**Comment by reckart** [comment]
Closing as user mentioned in other issue that websocket is working now.
