### ISSUE TITLE
 27.3 (2023-03-28 21:05:02, build cdd73a94) does not support inception-external-recommender-v2

### ISSUE THREAD

**Issue by fishfree** [inception-project/inception#3911]
I cannot find the "Remote Classifier v2" option when configuring recommenders as the GIF tutorial [here](https://raw.githubusercontent.com/inception-project/inception-external-recommender-v2/main/img/galahad_inception.gif).

I either cannot find the abov option in [the official demo server](https://morbo.ukp.informatik.tu-darmstadt.de/), which is the same build as mine. But the official demo server has much more layer options to select.

**Comment by reckart** [comment]
The v2 recommender branch has not been merged yet. You'd have to build from this branch: https://github.com/inception-project/inception/pull/2313
