### ISSUE TITLE
Search results not showing

### ISSUE THREAD

**Issue by bgittel** [inception-project/inception#3922]
**Describe the bug**
I experienced that the results of my search are not showing, although the search finds annotations. See the screenshot attached please

**Screenshots**
see below

**Please complete the following information:**
Version and build ID: 26.3 (2022-12-22 10:35:19, build https://github.com/inception-project/inception/commit/7c7cfc6dde57b5e58f4a3f221614bb8aa23afd2b)
OS: Windows
Browser: chrome

**Additional context**
I can't reproduce the behavior in other projects. The project concerned is the same, I send you today related to bug report #3921.

![Unbenannt](https://user-images.githubusercontent.com/58990077/230014994-677797d8-129a-403c-a6ae-8b3b7fb06cf4.png)

**Comment by reckart** [comment]
You need to write `<Wertung/>` (i.e. the tag must close). It is indeed interesting that it looks like you get results but none show. Not sure if this is a bug in INCEpTION or in the MTAS library we are using. Anyway, if you add the `/` before the closing bracket, it works.

**Comment by bgittel** [comment]
Thank you! I got it.

2 short follow ups: I numbered my features in order to make them appear in
the most practical order in the annotation window. However, the search does
not accept names like "1 Polarity" (strangely, it uses the labels of the
features not the variable names I see when I read the exported data). Is
there another way to force a certain order of the features on one layer?

It seems to me that every user can only search his own annotations. But how
can I as admin/ project manager a) search in all annotations of all users
and, more importantly, b) how can i search within all curated documents?
This would be very helpful in practice.

Best,
Ben



Am Mi., 5. Apr. 2023 um 19:16 Uhr schrieb Richard Eckart de Castilho <
***@***.***>:

**Comment by reckart** [comment]
> I numbered my features in order to make them appear in the most practical order in the annotation window. However, the search does not accept names like "1 Polarity" (strangely, it uses the labels of the features not the variable names I see when I read the exported data). Is there another way to force a certain order of the features on one layer? 

Not yet: https://github.com/inception-project/inception/issues/1592

I'm afraid the index currently does like neither spaces in feature names nor e.g. umlauts or other foreign characters. I have already wondered if it might be necessary to allow configuring the index field names explicitly...

> It seems to me that every user can only search his own annotations. But how can I as admin/ project manager a) search in all annotations of all users and, more importantly, b) how can i search within all curated documents? This would be very helpful in practice.

* a) https://github.com/inception-project/inception/issues/2958
* b) you can enable the [curation sidebar feature](https://inception-project.github.io/releases/27.3/docs/user-guide.html#_curation_sidebar). When you start the curation mode with the curation target set to **curation document** and then switch to the search sidebar, you should be able to search the curated documents.

**Comment by bgittel** [comment]
Thank you! It works as expected in the curation sidebar feature.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virenfrei.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Am Mi., 5. Apr. 2023 um 20:52 Uhr schrieb Richard Eckart de Castilho <
***@***.***>:
