### ISSUE TITLE
Error accessing PDF

### ISSUE THREAD

**Issue by martin-lentschat** [inception-project/inception#3923]
**Describe the bug**
After uploading a PDF file, I am not able to see or annotate it.
It seems that the server is not able to access the file, the Console is giving me the following error messages: 
-  `Refused to connect to 'http://my.server.name.fr/p/test2/annotate?3-1.1-centerArea-editor-vis&time=1680690334665' because it violates the following Content Security Policy directive: "connect-src 'self'".`
- `Refused to connect to 'http://my.server.name.fr/p/test2/annotate?3-1.1-centerArea-editor-vis&time=1680690334665' because it violates the document's Content Security Policy.`

I eddited the settings.properties file with different `wicket.core.csrf.accepted-origins` but it did not changed anything.

**Observations**
- I tried changing editors, the brats are working (but are not adapted to annotate pdfs) and PDF(legacy) indicates an incompatible file format (pdf2). I believe those behaviour are expected (same thing happens with different pdf files).
- The console also indicates that the connexion to the WebSocket failed. This message appears when entering a project and I do not know if it is important since it does not seems that it is affecting anything.
- When clicking on the link in the console error message, `http://my.server.name...`, the pdf opens in the brower, but is redirected to http***s***. Could this be related ?

**Information:**
 - Version and build ID: 27.3 (2023-03-28 21:05:02, build cdd73a94)
 - OS: Windows
 - Browser: Chrome

**Comment by martin-lentschat** [comment]
So, I found the source of the issue: the `/etc/apache2/conf-available/inception.local.conf` file had not been created.

However a new message appeared in the console:
`The Cross-Origin-Opener-Policy header has been ignored, because the URL's origin was untrustworthy. It was defined either in the final response or a redirect. Please deliver the response using the HTTPS protocol. You can also use the 'localhost' origin instead. See https://www.w3.org/TR/powerful-features/#potentially-trustworthy-origin and https://html.spec.whatwg.org/#the-cross-origin-opener-policy-header.`

I do not know if it is a problem or not, since everything seems to work fine.

**Comment by reckart** [comment]
Great you found theissue :)

Certain browser security features will not be available unless you use https. The browser lets you know this.

**Comment by martin-lentschat** [comment]
Strange thing is that https is not activated anymore. It was before.

I will keep this issue open for a few days if that's ok, and update you with my investigations ^^

**Comment by reckart** [comment]
If you upgraded - depending on what your old version was - it might be that relevant Spring properties have changed their names.

**Comment by martin-lentschat** [comment]
I just noticed this, looks like project are not properly deleted anymore:
![image](https://user-images.githubusercontent.com/26545993/230088252-00e4aca2-41fd-4d8f-a338-bd246d620e17.png)

**Comment by reckart** [comment]
Would be nice if you could collect the stack trace of that error and add it to another bug report.

Probably it is due to the index migration that INCEpTION was trying to run as part of the upgrade as you opened some document of that project before trying to delete it.

**Comment by reckart** [comment]
23.11 was using Spring Boot 2.6.9, 27.3 is using 2.7.8 - I guess the properties for https support shouldn't have changed between these.

**Comment by reckart** [comment]
They did ;) https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes - scroll down to SSL

**Comment by reckart** [comment]
Errors are logged in the server log with a message and then a bunch of lines saying where the error happened (see e.g. the "screenshot" section of [this](https://github.com/inception-project/inception/issues/3821#issue-1590242789) issue.)

**Comment by tehaef** [comment]
@martin-lentschat could you, by any chance please explain, what you had change to get it working, i.e. what the inception.local.conf for apache had to looked like? My setup is docker-compose + apache 2.4 with mod_proxy and i'm encountering essentially the same issue:

`PDFAnnoPage.ts:154 Refused to connect to 'http://my.domain.example/inception/p/test/annotate?18-1.1-centerArea-editor-vis&time=xyz' because it violates the following Content Security Policy directive: "connect-src 'self'".`

Which is particularly surprising, because Apache is already properly setup for https and i don't understand where the "http" in the error message might originate from.  Thank you!

**Comment by reckart** [comment]
@tehaef that looks like INCEpTION is not getting the external host and protocol properly forwarded so it thinks that it is running on a http URL instead of a https URL.

**Comment by tehaef** [comment]
@reckart thanks for the quick response. You were right. I solved it by added something like this to the apache config:

```
Requestheader unset "X-Forwarded-Proto"
RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
RequestHeader unset "X-Forwarded-SSL"
RequestHeader set "X-Forwarded-SSL" expr=%{HTTPS}
```

**Comment by reckart** [comment]
@tehaef Would you like to propose an update to the documentation to include this information? https://github.com/inception-project/inception/blob/main/inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_ssl_apache.adoc
