### ISSUE TITLE
Cannot merge link feature with same target on curation page

### ISSUE THREAD

**Issue by bgittel** [inception-project/inception#3934]
### Describe the bug

I have a link feature with role labels on a span layer. If I have two links with the same target on one span, Inception does not let me accept both in the curation window. Instead it changes the role label of the feature in the curation_document.

### To Reproduce

1. Go to curation window
2. Click on two links on the same span with different roles but the same target
3. See how Inception does not copy both into the curation document

### Expected behavior

accept both links for gold standard

### Environment

Version and build ID: 27.4
Operating system: Windows
Browser: Chrome

**Comment by reckart** [comment]
The merge feature for links assumes that typically, every link should point to a different target. That means if the curator clicks on any link, an existing link to the same target is replaced. That seems to be a bad/unhelpful assumption - at least in your case.

**Comment by bgittel** [comment]
Right, since links can have labels, it seems reasonable to have two links
with the same target. Suppose you want to annotate the target of an
evaluation and the evaluater as links, than you can have cases of
self-evaluation (e. g., I'm the best), where the problem occurs. So will
this be accommodated in a future version of inception?

Richard Eckart de Castilho ***@***.***> schrieb am Fr., 14.
Apr. 2023, 08:50:
