### ISSUE TITLE
Per-project based automatically ingest files as documents from a server folder

### ISSUE THREAD

**Issue by fishfree** [inception-project/inception#3968]
Now, we can only manually import files in the web UI.

**Comment by reckart** [comment]
You can also enable the remote API and use it to import documents.

**Comment by reckart** [comment]
What would be the benefit if importing documents from a server folder?

**Comment by fishfree** [comment]
I can set up a WebDAV or FTP services to a folder, let users upload documents there, then INCEpTION can automatically scan and import documents there.

**Comment by reckart** [comment]
If you have this need, you can write a script which scans your folder automatically and then pushes the documents into INCEpTION through the remote API.

**Comment by fishfree** [comment]
@reckart Thank you! I will use the HTTP API.
