### ISSUE TITLE
Please provide HTTP API documentation

### ISSUE THREAD

**Issue by fishfree** [inception-project/inception#3988]
I only searched out [The third-party Python library pycaprio can be used to facilitate accessing the remote API](https://inception-project.github.io/releases/22.5/docs/admin-guide.html#sect_remote_api). But no HTTP API doc provided. I have to call INCEpTION by using PHP.

**Comment by reckart** [comment]
There is no ready-made client library for PHP. However, the REST-like API is pretty straight-forward and documented here: https://openminted.github.io/releases/aero-spec/1.0.0/omtd-aero/

Also, there is a self-explanatory Swagger API/UI available by clicking on the "API" link in the top bar after you enabled the remote API and when you then access INCEpTION using an account that has the `ROLE_REMOTE`.

**Comment by fishfree** [comment]
@reckart Thank you very much!
