### ISSUE TITLE
Annotation and correction for grammar errors

### ISSUE THREAD

**Issue by vishalmodagekar** [inception-project/inception#3989]
**Describe the solution you'd like**
Consider a text file containing grammatically incorrect sentences. These sentences when passed through a Grammar Error Correction module are expected to be corrected by the module. The goal is to edit the sentence into a grammatically correct form if not corrected by the module and annotate the error corrections on text span level using Inception. Please guide as to how this can be accomplished using Inception.

**Comment by reckart** [comment]
INCEpTION has a built-in layer called `Orthography` that you could use to annotate the changes that you would like to be made to a sentence to correct it. It has two features, one that identifies the change operation (e.g. insert, delete, etc.) and one that holds the value (e.g. the text to insert). Note that INCEpTION has no particular functionality to commit such changes to the text. So if you would be interested in applying the annotated changes to the document, you would need to export the annotated data and then write a script that interprets the `Orthography` annotations and applies them to the text.
