### ISSUE TITLE
Layer validation should not consider hidden conditional features

### ISSUE THREAD

**Issue by parvva** [inception-project/inception#3990]
**Describe the bug**
We faced an issue on a feature which is conditional. The scenario is:
A is a feature can get value "aa" and "bb"
if "aa" is selected, then feature B is visible and it is required
otherwise if "bb" is selected, feature B is hidden, so not required

right now if we choose "bb" and feature B is required, we cannot finish the document with error that feature B is required. Although it is hidden!

**Expected behavior**
When no constraints applies to a _required_ feature and it is hidden, it should become not-required automatically.
Also, when a feature is hidden by a constraint, its value should be reset/cleared.

**Please complete the following information:**
 - Version and build ID: 27.6

**Comment by reckart** [comment]
I have had a look at this issue. In principle, it should not be too difficult to fix. However, a simple fix could impact performance very negatively. Implementing this in such a way that the performance impact is minimal requires more consideration.

Validation can happen during rendering and when finishing a document. When finishing a document, we have access to the `AnnotatorState` which caches the constraints. But when rendering, we generally do not have access to the `AnnotatorState`. That means, a way of caching the constraints independently from the `AnnotatorState` would need to be implemented.
