### ISSUE TITLE
Support interface language localization

### ISSUE THREAD

**Issue by fishfree** [inception-project/inception#3995]
I found no way to translate the interface language, which is popular for Java applications.

**Comment by reckart** [comment]
What are you trying to do any why?

**Comment by fishfree** [comment]
I'd like to translate the interface into Chinese.

**Comment by reckart** [comment]
I would recommend you look at this thread and maybe also respond to it: https://groups.google.com/g/inception-users/c/DaNIQXPA5jQ

The strings in INCEpTION are quite distributed at the moment. If people are interested in contributing translations, we need to figure out how this can be done in a good and maintainable way.

**Comment by fishfree** [comment]
Thank you very much!
