### ISSUE TITLE
Why is there "Error: NO LABEL"?

### ISSUE THREAD

**Issue by fishfree** [inception-project/inception#4001]
INCEpTION -- 27.3 
After using the inception-external-recommender spacy_ner, it always shows "Error: NO LABEL" as the attached screenshot.

![image](https://github.com/inception-project/inception/assets/1741341/23f86a9e-bbc1-4d8c-b0db-6afabaeedecc)
![image](https://github.com/inception-project/inception/assets/1741341/c2f601e0-23ed-4a43-874d-44d5afc2d003)
![image](https://github.com/inception-project/inception/assets/1741341/19e82811-1d3c-4c43-ac77-60379fdcbb6d)

**Comment by reckart** [comment]
The error comes from there being a value `LOC` in the `identifier` feature - this is not a valid URI and it cannot be resolved using any knowledge base in the project. Thus you see the error.

Values such as the entity categories predicted by spacy (`LOC`, `ORG`, ...) would need to go into a string feature like `value`.

Maybe you had configured your classifier to predict `identifier` before?

**Comment by fishfree** [comment]
Thank you for your explanation!
