### ISSUE TITLE
Is it possible to make GUM-similar corpus with INCEpTION?

### ISSUE THREAD

**Issue by fishfree** [inception-project/inception#4006]
Pelase see [this issue](https://github.com/korpling/pepper/issues/150#issuecomment-1546128692) first. 
Is it necessary to establish some schema conformed to ANNIS?

I also had a try: downloaded the file [GUM_academic_art.tsv](https://raw.githubusercontent.com/amir-zeldes/gum/master/coref/gum/tsv/GUM_academic_art.tsv), then imported into INCEpTION. Error occured as below:
![image](https://github.com/inception-project/inception/assets/1741341/591f6a2f-94f0-44ed-ab3f-d40e1fa632c2)

**Comment by reckart** [comment]
You cannot import WebAnno TSV files without first setting up a project to be compatible with the files. I believe GUM contains files in CoNLL-U format - you could try importing those.

**Comment by reckart** [comment]
Btw. you'll have the same problem with any file format that allows custom layers (e.g. XMI, UIMA JSON JCAS, WebAnno TSV, etc.). If you want to import any of these, the project first needs to be configured with the layers that these files use.

**Comment by fishfree** [comment]
@reckart Thank you for your answering. I modified the GUM_academic_art.tsv file header as below:
```
#FORMAT=WebAnno TSV 3.3
#T_SP=webanno.custom.Referent|entity|infstat|salience|identity|centering
#T_RL=webanno.custom.Coref|webannottype|BT_webanno.custom.Referent

```
And created the correspondent layers with features as the attached screenshot:
![image](https://github.com/inception-project/inception/assets/1741341/4cec1df0-2a01-4145-995c-f16d22fbebdf)
![image](https://github.com/inception-project/inception/assets/1741341/e717cc93-cd0a-449c-ac00-6730278d2219)

Now the error changed when importing the file:
![image](https://github.com/inception-project/inception/assets/1741341/3b073fe1-f139-43f5-88e7-5166df2a12a9)

**Comment by reckart** [comment]
Yes, we have been here over a year ago already ;) It is a "bug" in GUM. 

https://github.com/amir-zeldes/gum/issues/101

I just noted you even had commented on the issue at the time.

**Comment by gersh0m** [comment]
Still It is not clear to me how to import a GUM project file into INCEpTION. By sure there there is a lack of documentation  over here:
https://inception-project.github.io/use-cases/gum/
