### ISSUE TITLE
Where did the annotations go after importing a Conll-U file?

### ISSUE THREAD

**Issue by fishfree** [inception-project/inception#4019]
This is the content of my conll-u file:
```
# sent_id = 1
# text = They buy and sell books.
1	They	they	PRON	PRP	Case=Nom|Number=Plur	2	nsubj	2:nsubj|4:nsubj	_
2	buy	buy	VERB	VBP	Number=Plur|Person=3|Tense=Pres	0	root	0:root	_
3	and	and	CONJ	CC	_	4	cc	4:cc	_
4	sell	sell	VERB	VBP	Number=Plur|Person=3|Tense=Pres	2	conj	0:root|2:conj	_
5	books	book	NOUN	NNS	Number=Plur	2	obj	2:obj|4:obj	SpaceAfter=No
6	.	.	PUNCT	.	_	2	punct	2:punct	_
```
After importing it, I see nowhere the form / lemma / pos /dep annotations are.
![image](https://github.com/inception-project/inception/assets/1741341/feedc467-4ad7-473a-bb75-bbdd3dda1886)

**Comment by reckart** [comment]
You seem to have created a project from the "simple span/relation" template. The CoNLL-U support requires the build-in layers that are part of a "standard" project. So either you create a standard project and import the data there - or you go to the project settings, open the drop-down next to the layer list's "create" button and add layers like `Part of Speech`, `Lemma`, `Dependency`, etc. from there. After that, you should see those annotation layers in the editor.

**Comment by fishfree** [comment]
@reckart Thank you very much for your patient answer! I have to read the documentation more carefully to understand the related concepts.
