### ISSUE TITLE
Unable to borrow CAS error on RHEL8

### ISSUE THREAD

**Issue by jeweinb** [inception-project/inception#4020]
**Describe the bug**
When attempting to setup a project for the first time I am getting this error. I try to upload a test document manually and simply go to "Annotations" and click on it. The app hangs a while and goes to a "Whoops" screen. Then if I try it again it hangs for a while and returns the error below. What is going on?

**Unable to borrow CAS**

![image](https://github.com/inception-project/inception/assets/87095331/a4de4b86-362b-45af-9fd7-a897350f7592)

**Please complete the following information:**
 - Version and build ID: inception-app-webapp-28.0-standalone.jar
 - OS: RHEL8
 - Browser: chrome
 - MariaDB: 10.5
 - nginx reverse proxy
 - openjdk version "11.0.19" 2023-04-18 LTS
OpenJDK Runtime Environment (Red_Hat-11.0.19.0.7-1.el8_7) (build 11.0.19+7-LTS)
OpenJDK 64-Bit Server VM (Red_Hat-11.0.19.0.7-1.el8_7) (build 11.0.19+7-LTS, mixed mode, sharing)

**Additional context**

**Comment by jeweinb** [comment]
May 25 11:47:11 apvrp98054 inception.jar[16359]: 2023-05-25 11:47:11 INFO [SYSTEM] DocumentServiceImpl - Imported source document [hi.txt](12) to project [admin - New project](6)
May 25 11:47:11 apvrp98054 inception.jar[16359]: 2023-05-25 11:47:11 INFO [SYSTEM] ApplicationPageBase - admin: Document [hi.txt] has been imported successfully!
May 25 11:47:11 apvrp98054 inception.jar[16359]: Exception in thread "inception-worker-11" org.xerial.snappy.SnappyError: [INVALID_CHUNK_SIZE] Recorded length is 0 bytes but actual length after decompression is 3068 bytes
May 25 11:47:11 apvrp98054 inception.jar[16359]:         at org.xerial.snappy.pure.SnappyRawDecompressor.decompress(SnappyRawDecompressor.java:73)
May 25 11:47:11 apvrp98054 inception.jar[16359]:         at org.xerial.snappy.pure.PureJavaSnappy.rawUncompress(PureJavaSnappy.java:182)
May 25 11:47:11 apvrp98054 inception.jar[16359]:         at org.xerial.snappy.Snappy.uncompress(Snappy.java:551)
May 25 11:47:11 apvrp98054 inception.jar[16359]:         at org.xerial.snappy.SnappyFramedInputStream.ensureBuffer(SnappyFramedInputStream.java:563)
May 25 11:47:11 apvrp98054 inception.jar[16359]:         at org.xerial.snappy.SnappyFramedInputStream.read(SnappyFramedInputStream.java:296)
May 25 11:47:11 apvrp98054 inception.jar[16359]:         at java.base/java.io.ObjectInputStream$PeekInputStream.read(ObjectInputStream.java:2893)
May 25 11:47:11 apvrp98054 inception.jar[16359]:         at java.base/java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2909)
May 25 11:47:11 apvrp98054 inception.jar[16359]:         at java.base/java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3406)
May 25 11:47:11 apvrp98054 inception.jar[16359]:         at java.base/java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:932)
May 25 11:47:11 apvrp98054 inception.jar[16359]:         at java.base/java.io.ObjectInputStream.<init>(ObjectInputStream.java:375)
May 25 11:47:11 apvrp98054 inception.jar[16359]:         at de.tudarmstadt.ukp.inception.annotation.storage.driver.filesystem.CasPersistenceUtils.readSerializedCas(CasPersistenceUtils.java:174)
May 25 11:47:11 apvrp98054 inception.jar[16359]:         at de.tudarmstadt.ukp.inception.annotation.storage.driver.filesystem.CasPersistenceUtils.readSerializedCas(CasPersistenceUtils.java:167)
May 25 11:47:11 apvrp98054 inception.jar[16359]:         at de.tudarmstadt.ukp.inception.annotation.storage.driver.filesystem.FileSystemCasStorageDriver.readCas(FileSystemCasStorageDriver.java:149)
May 25 11:47:11 apvrp98054 inception.jar[16359]:         at de.tudarmstadt.ukp.inception.annotation.storage.CasStorageServiceImpl.readOrCreateUnmanagedCas(CasStorageServiceImpl.java:570)
May 25 11:47:11 apvrp98054 inception.jar[16359]:         at de.tudarmstadt.ukp.inception.annotation.storage.CasStorageServiceImpl.lambda$readOrCreateCas$1(CasStorageServiceImpl.java:409)
May 25 11:47:11 apvrp98054 inception.jar[16359]:         at de.tudarmstadt.ukp.inception.annotation.storage.CasHolder.of(CasHolder.java:117)
May 25 11:47:11 apvrp98054 inception.jar[16359]:         at de.tudarmstadt.ukp.inception.annotation.storage.CasStorageServiceImpl.lambda$readOrCreateCas$2(CasStorageServiceImpl.java:408)
May 25 11:47:11 apvrp98054 inception.jar[16359]:         at com.github.benmanes.caffeine.cache.LocalCache.lambda$statsAware$2(LocalCache.java:167)
May 25 11:47:11 apvrp98054 inception.jar[16359]:         at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2668)
May 25 11:47:11 apvrp98054 inception.jar[16359]:         at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1908)
May 25 11:47:11 apvrp98054 inception.jar[16359]:         at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2666)
May 25 11:47:11 apvrp98054 inception.jar[16359]:         at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2649)
May 25 11:47:11 apvrp98054 inception.jar[16359]:         at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:112)
May 25 11:47:11 apvrp98054 inception.jar[16359]:         at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
May 25 11:47:11 apvrp98054 inception.jar[16359]:         at de.tudarmstadt.ukp.inception.annotation.storage.CasStorageServiceImpl.readOrCreateCas(CasStorageServiceImpl.java:407)
May 25 11:47:11 apvrp98054 inception.jar[16359]:         at de.tudarmstadt.ukp.inception.annotation.storage.CasStorageServiceImpl$$FastClassBySpringCGLIB$$77bb5466.invoke(<generated>)
May 25 11:47:11 apvrp98054 inception.jar[16359]:         at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
May 25 11:47:11 apvrp98054 inception.jar[16359]:         at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
May 25 11:47:11 apvrp98054 inception.jar[16359]:         at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
May 25 11:47:11 apvrp98054 inception.jar[16359]:         at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704)
May 25 11:47:11 apvrp98054 inception.jar[16359]:         at de.tudarmstadt.ukp.inception.annotation.storage.CasStorageServiceImpl$$EnhancerBySpringCGLIB$$7adc4c51.readOrCreateCas(<generated>)
May 25 11:47:11 apvrp98054 inception.jar[16359]:         at de.tudarmstadt.ukp.inception.documents.DocumentServiceImpl.createOrReadInitialCas(DocumentServiceImpl.java:848)
May 25 11:47:11 apvrp98054 inception.jar[16359]:         at de.tudarmstadt.ukp.inception.documents.DocumentServiceImpl.createOrReadInitialCas(DocumentServiceImpl.java:822)
May 25 11:47:11 apvrp98054 inception.jar[16359]:         at de.tudarmstadt.ukp.inception.documents.DocumentServiceImpl$$FastClassBySpringCGLIB$$5931451b.invoke(<generated>)
May 25 11:47:11 apvrp98054 inception.jar[16359]:         at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
May 25 11:47:11 apvrp98054 inception.jar[16359]:         at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
May 25 11:47:11 apvrp98054 inception.jar[16359]:         at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
May 25 11:47:11 apvrp98054 inception.jar[16359]:         at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704)
May 25 11:47:11 apvrp98054 inception.jar[16359]:         at de.tudarmstadt.ukp.inception.documents.DocumentServiceImpl$$EnhancerBySpringCGLIB$$4b114b3f.createOrReadInitialCas(<generated>)
May 25 11:47:11 apvrp98054 inception.jar[16359]:         at de.tudarmstadt.ukp.inception.search.scheduling.tasks.IndexSourceDocumentTask.execute(IndexSourceDocumentTask.java:68)
May 25 11:47:11 apvrp98054 inception.jar[16359]:         at de.tudarmstadt.ukp.inception.scheduling.Task.run(Task.java:109)
May 25 11:47:11 apvrp98054 inception.jar[16359]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
May 25 11:47:11 apvrp98054 inception.jar[16359]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
May 25 11:47:11 apvrp98054 inception.jar[16359]:         at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by jeweinb** [comment]
getting this error too on simple one word text file.

**Exception in thread "inception-worker-11" org.xerial.snappy.SnappyError: [INVALID_CHUNK_SIZE] Recorded length is 0 bytes but actual length after decompression is 3068 bytes**

**Comment by reckart** [comment]
So if a document gets stuck in the CAS pool and cannot be borrowed anymore, the only fix at the moment is to restart INCEpTION. If you have a case where you can consistently reproduce something getting stuck in the pool, I'd love to know how you do it.

The SnappyError is somewhat odd and scary. I have never seen it. You could add the following options to your `settings.properties`:

```
cas-storage.paranoid-cas-serialization=true
cas-storage.compressed-cas-serialization=false
```

That will try to catch serialization problems more aggressively by performing a validation read operation directly after every write operation. It also will disable compression - so if snappy is for some reason broken on your system, it would just be disabled. Note that disabling snappy will only affect new documents, so maybe start with a new project after disabling CAS compression.

**Comment by jeweinb** [comment]
Thank you for the suggestion I will try that out. This is a brand new setup, we are trying to import our first test documents and are getting this error. I wouldn't rule out we don't have dependencies setup correctly, our servers come very bare bones and we have to provision everything ourselves.

**Comment by reckart** [comment]
INCEpTION comes with most stuff bundled up inside. Everything you should need to get it running is a JRE 11+. MariaDB is recommended and reverse proxy is also useful, but the issue you are seeing wouldn't be related to either of those. Are you using some kind of network storage or non-local storage for your file system?

**Comment by jeweinb** [comment]
I am using a mounted storage (its bigger and fit for a database) our vm doesn't come with much storage.

I made the changes above to my settings file and I no longer get the error!!! Very excited :)

**Comment by reckart** [comment]
Note that it is known that INCEpTION has problems with some network storages. In particular Azure users have reported that INCEpTION regularly displays messages of "concurrent modification" (this message normally only comes when a user tries to edit a document with multiple windows/tabs at the same time) to the annotation data because Azure storage timestamps are inaccurate. Just to let you know in case you run into the same issue at some point. M

**Comment by reckart** [comment]
You might want to keep it on for a bit just in case, but eventually you should turn it off again.

**Comment by reckart** [comment]
How much memory does your VM have?

**Comment by jeweinb** [comment]
Right now its set at 8cpu/64gb ram. Database has 200gb hard drive. I can make all of these things bigger if needed.

**Comment by reckart** [comment]
Are you deploying with Docker or natively?

**Comment by jeweinb** [comment]
Natively for now, want to move to docker at some point.

**Comment by reckart** [comment]
Keep an eye out during startup of INCEpTION for what it tells you how much max memory it has available. If this is significantly less then you would expect, you need to pass the amount you want using Java's `-Xmx` parameter. In particular the Docker image by default is set to a very conservative memory limit (`-Xmx750m`) and usually needs to be increased through the `JAVA_OPTS` environment variable.
