### ISSUE TITLE
Support for error tracking with Sentry

### ISSUE THREAD

**Issue by torgeirl** [inception-project/inception#4026]
**Is your feature request related to a problem? Please describe.**
As a system administrator I would like to be able to use Sentry as an error tracker the Inception deployment I maintain.

**Describe the solution you'd like**
This would be possible if the needed [Sentry SDK libraries (MIT License)](https://github.com/getsentry/sentry-java) were included in the standard build of Inception. Since Inception is built using Spring Boot, this would include two new dependencies:

* `sentry-spring-boot-starter` (required)
* `sentry-log4j2` (optional; would allow for transaction performance monitoring)

The later could in addition be supported by also adding [`SentryAppender`](https://docs.sentry.io/platforms/java/guides/spring-boot/logging-frameworks/#log4j2) to [the list of supported loggers](https://inception-project.github.io/releases/27.8/docs/admin-guide.html#_logging_in_json_format). Otherwise, it would have to be specified as a custom logger.

[Sentry's documentation for Spring Boot](https://docs.sentry.io/platforms/java/guides/spring-boot/)

**Describe alternatives you've considered**
Kibana/ELK is fine for metrics/general traffic monitoring, but compared to Sentry they require more setup to monitor errors, include more noise, and often requires you to already be digging for answers to a reported issue.

**Additional context**
I would happily expand Inception's documentation with instructions on how to set it up if the needed libraries get included.

**Comment by reckart** [comment]
@torgeirl how are you sentry experiments going? Is this something we should keep? If you don't get sentry to run, I would consider removing the dependencies again.

**Comment by torgeirl** [comment]
@reckart: I have been traveling since right before you added the latest dependency, and have therefore not had the change to test it yet. Back at the office this Thursday. Will give you an update either Thursday or Friday!

**Comment by torgeirl** [comment]
@reckart: seems to be working well now, but I like to test some more to be sure. Is there a rough timeline for the 29.0 release ("docs due date")?

**Comment by reckart** [comment]
@torgeirl would you like to write up a few lines of documentation regarding sentry this week? The 29.0 release is scheduled for Tuesday next week.

**Comment by torgeirl** [comment]
> @torgeirl would you like to write up a few lines of documentation regarding sentry this week? The 29.0 release is scheduled for Tuesday next week.

Will do! :+1:

**Comment by reckart** [comment]
Thx. I have squashed-merged it and in the process updated the commit comment according to the usual format. Normally, I prefer regular merges, but then the commit messages should already follow the conventions.
