### ISSUE TITLE
Support recommendation of relations

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#406]
It would be nice to have recommender that can predict relations. In INCEpTION, there are 4 types of layers that could be predicted:

1. Relations #1239
2. Predicate-Argument Structures
3. Coreference Chains
4. KB Facts

![image](https://user-images.githubusercontent.com/934600/59102028-22165a00-892b-11e9-9703-b5f22f067f5b.png)

**Comment by FajunChen** [comment]
Is it already finished to support recommendation of relations? I see no related example in the inception-external-recommender subproject.

**Comment by jcklie** [comment]
There is support in INCEpTION and we have an internal recommender for relations, I just did not have a use case/model yet for an external one. What would you like to use it for?

**Comment by FajunChen** [comment]
I'd like to train a coreference resultion model through active learning.

**Comment by FajunChen** [comment]
May I reuse the Server and Classifier classes provided by the ariadne package?

**Comment by reckart** [comment]
We have basic support for relations since #1239 in v20.
