### ISSUE TITLE
Exporting coreference annotation

### ISSUE THREAD

**Issue by AldawsariNLP** [inception-project/inception#4072]
Thanks for sharing this cool project!
Why is The built-in coreference layer can not curated? Also, conll format is not supported, right? if so what is the alternative or a way to convert the annotation to conll format.

**Comment by AldawsariNLP** [comment]
I see and good luck in implementing the curation.  but how the agreement is calculated between annotators in the coreference layer now?

**Comment by reckart** [comment]
You cannot select features of a chain layer (like the coreference layer) on the agreement page.
