### ISSUE TITLE
import/export tagsets/layers is impossible

### ISSUE THREAD

**Issue by cedricemvista** [inception-project/inception#4092]
Hello, great project, thank you so much for your work!

**Describe the bug**

When I export a tagset from a project and I import this tagset into another project I obtain this error (see screenshot). Nevertheless, the layer is created but it doesn't contain information (it contains only the description of the tagset). 

NB: I have the same problem with layers. 
NB: I have the same behaviour when I create a new projet even if the project is well created but without layers and tagsets).

**To Reproduce**
1. Export a tagset
2. Import the tagset into another project

**Expected behavior**
Ability to create projects, import and export tagsets.

**Screenshots**
![image](https://github.com/inception-project/inception/assets/36985683/b90ff1d4-cc32-48ea-9425-14ec2b9f3943)

**Please complete the following information:**
 - I use the latest docker image, version 27.

**Additional context**
Her are some logs:

inception-stack_inception.1.4tomn8934t5q@lin003    | Caused by: java.sql.SQLException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'rank, tagset) values (NULL, '0', 0, 224)' at line 1
inception-stack_inception.1.4tomn8934t5q@lin003    | 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1693) ~[mariadb-java-client-2.7.8.jar!/:?]
inception-stack_inception.1.4tomn8934t5q@lin003    | 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1555) ~[mariadb-java-client-2.7.8.jar!/:?]
inception-stack_inception.1.4tomn8934t5q@lin003    | 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1518) ~[mariadb-java-client-2.7.8.jar!/:?]
inception-stack_inception.1.4tomn8934t5q@lin003    | 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:319) ~[mariadb-java-client-2.7.8.jar!/:?]
inception-stack_inception.1.4tomn8934t5q@lin003    | 	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:220) ~[mariadb-java-client-2.7.8.jar!/:?]
inception-stack_inception.1.4tomn8934t5q@lin003    | 	at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149) ~[mariadb-java-client-2.7.8.jar!/:?]
inception-stack_inception.1.4tomn8934t5q@lin003    | 	at org.mariadb.jdbc.ClientSidePreparedStatement.executeUpdate(ClientSidePreparedStatement.java:181) ~[mariadb-java-client-2.7.8.jar!/:?]
inception-stack_inception.1.4tomn8934t5q@lin003    | 	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[HikariCP-4.0.3.jar!/:?]
inception-stack_inception.1.4tomn8934t5q@lin003    | 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[HikariCP-4.0.3.jar!/:?]
inception-stack_inception.1.4tomn8934t5q@lin003    | 	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:197) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
inception-stack_inception.1.4tomn8934t5q@lin003    | 	at org.hibernate.dialect.identity.GetGeneratedKeysDelegate.executeAndExtract(GetGeneratedKeysDelegate.java:58) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
inception-stack_inception.1.4tomn8934t5q@lin003    | 	at org.hibernate.id.insert.AbstractReturningDelegate.performInsert(AbstractReturningDelegate.java:43) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
inception-stack_inception.1.4tomn8934t5q@lin003    | 	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3279) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
inception-stack_inception.1.4tomn8934t5q@lin003    | 	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3914) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
inception-stack_inception.1.4tomn8934t5q@lin003    | 	at org.hibernate.action.internal.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:84) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
inception-stack_inception.1.4tomn8934t5q@lin003    | 	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:645) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
inception-stack_inception.1.4tomn8934t5q@lin003    | 	at org.hibernate.engine.spi.ActionQueue.addResolvedEntityInsertAction(ActionQueue.java:282) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
inception-stack_inception.1.4tomn8934t5q@lin003    | 	at org.hibernate.engine.spi.ActionQueue.addInsertAction(ActionQueue.java:263) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
inception-stack_inception.1.4tomn8934t5q@lin003    | 	at org.hibernate.engine.spi.ActionQueue.addAction(ActionQueue.java:317) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
inception-stack_inception.1.4tomn8934t5q@lin003    | 	at org.hibernate.event.internal.AbstractSaveEventListener.addInsertAction(AbstractSaveEventListener.java:329) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
inception-stack_inception.1.4tomn8934t5q@lin003    | 	at org.hibernate.event.internal.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:286) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
inception-stack_inception.1.4tomn8934t5q@lin003    | 	at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:192) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
inception-stack_inception.1.4tomn8934t5q@lin003    | 	at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:122) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
inception-stack_inception.1.4tomn8934t5q@lin003    | 	at org.hibernate.event.internal.DefaultPersistEventListener.entityIsTransient(DefaultPersistEventListener.java:185) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
inception-stack_inception.1.4tomn8934t5q@lin003    | 	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:128) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
inception-stack_inception.1.4tomn8934t5q@lin003    | 	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:55) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
inception-stack_inception.1.4tomn8934t5q@lin003    | 	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:107) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
inception-stack_inception.1.4tomn8934t5q@lin003    | 	at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:756) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
inception-stack_inception.1.4tomn8934t5q@lin003    | 	... 149 more
inception-stack_inception.1.4tomn8934t5q@lin003    | 2023-07-07 06:55:06 ERROR [SYSTEM] ApplicationPageBase - cedric: Error: org.hibernate.exception.SQLGrammarException: could not execute statement

**Comment by cedricemvista** [comment]
Solved with a change into MariaDB driver.
org.hibernate.dialect.MySQL8Dialect **instead of** org.hibernate.dialect.MariaDB103Dialect

**Comment by reckart** [comment]
Thanks for saving me the work to investigate it :)
