### ISSUE TITLE
Accepting recommendation in main editor adds rejection items to AL history

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#41]
This is in active learning mode:

When there are multiple recommendations at the same location, accepting one of them does not only add an "ACCEPT" item to the AL history, but also "REJECT" items for the other recommendations that were not accepted. 

That means in order to "undo" the action, the user would not only have to delete one item from the AL history (the ACCEPTed one) but also the REJECTed ones.

The AL history should only log explicit actions. Implicit actions should also be logged, but this should happen in the event log.

0.3.0-SNAPSHOT (2018-04-11 12:25:58, build 9fcfc7066f57f2849c22ce3a45cd1817818e6c60)

**Comment by matchlesswei** [comment]
@reckart If the user accepts an annotation in the main editor, al sidebar shows another suggestion, but the main editor doesn't jump to the new location. Is it a bug or a feature so that user could view things they have annotated?

**Comment by matchlesswei** [comment]
I also tend to think it is a bug and have tried to fix it. But at the first glance, `actionShowSelectedDocument` is also called with the correct beginCharacterOffset. And the old annotated sentence is always be moved 2 sentences backward. So I wonder whether it is designed to be so.

**Comment by reckart** [comment]
@matchlesswei can you please check the settings dialog on the annotation page an see whether "auto-scroll" is enabled?

**Comment by reckart** [comment]
@matchlesswei IMHO only explicit actions should be recorded. So if the user presses a button (accept/reject/skip) in the sidebar, that action should be recorded. If the user accepts or rejects something in the main view, that should be recorded. Implicit effects, e.g. the fact that alternative suggestions are no longer visible after something has been accept should not be recorded in the learning log as rejections.

**Comment by matchlesswei** [comment]
@reckart yes, after enable "auto-scroll", jumping works well. Shall we do some changes for it?

I have removed the implicit effects.

**Comment by reckart** [comment]
@matchlesswei please open  a separate issue for the auto-scroll problem.
