### ISSUE TITLE
Exporting large project opens blank window

### ISSUE THREAD

**Issue by raykyn** [inception-project/inception#4145]
### Describe the bug

When I try to export the backup archive for a large project (ca. 1000 docs), then press the Download Button, it replaces the current window with a blank window with an address "\<server\>/ui/api/export/521fe0e7-ad9a-46bb-8b1b-fdbb4820fae0/data".

This behavior is not completely consistent: I tested it with and without additional format and sometimes I could download as expected when trying it with or without data.

### To Reproduce

1. Create a large project (I've only met this error with the large project, smaller ones never had this problem)
2. Export the project, possibly with additional format CAS XMI 1.1
3. Blank window opens (at least sometimes)

### Expected behavior

If it's due to a server error, I'd expect to see a message informing about it.
In the best case, just the download as needed.

### Environment

Version and build ID: INCEpTION -- 26.8 (2023-02-14 18:25:57, build dd3733ba)
Operating system: Ubuntu Server
Browser: Firefox

### Additional context

It would be nice if there was an easier way to export data formats like CAS XMI 1.1 for further processing, especially choosing only a subset of all the documents in the project to be exported.

**Comment by reckart** [comment]
Interesting, I have never seen such a behavior. And when the current window gets replaced, does the download start at least? If not, can you possibly see if there is any kind of error message in the browser JavaScript console or network panel?

Where would you expect an option to export a subset of documents to be located in the UI? Would the export always include data from all annotators or do you expect to also be able to select a subset of annotators?

**Comment by raykyn** [comment]
No, the download did also not start, which is the core problem.

![image](https://github.com/inception-project/inception/assets/9513086/70f326ee-c0da-4434-b936-b6b02e18ce57)

Looks like the call to the export API 404s.

I was initially looking for an export option in the monitoring windows. As this one already has options to choose subsets of document by status, editor, etc, I think this would be the perfect place to enable a subset download.

**Comment by reckart** [comment]
Opened a separate issue regarding the export: https://github.com/inception-project/inception/issues/4147

**Comment by raykyn** [comment]
> > Looks like the call to the export API 404s.
> 
> Maybe you are hitting this bug which was recently fixed:
> 
> #4086
> 
> Best try upgrading to the latest version (29.0) and check if the issue persists for you.

Hm, I'm also manager, so it doesn't quite fit. But I'll update soon anyways, and let you know if the problem persists.

> > Btw, thank you so, so much for maintaining this repo! Without Inception our research project wouldn't be doable.
> 
> Thanks :) We have a [use-case gallery on the website](https://inception-project.github.io/use-cases/) where some of the projects that have used INCEpTION are presented. If you have an interesting project that you may now (or in the future e.g. after you have made a publication on your project) would like to present there, let me know.

Thanks, probably still one or two years to go before we've got something to show :-)

**Comment by raykyn** [comment]
I've got a hunch now what was up. The server I was using was very small and disk space was pretty much all used up. So I could imagine the export file was too large to be written or was deleted very quickly too make space again ( i assume it gets created as a temp-file?)
