### ISSUE TITLE
Retain xml:id of TEI sentences

### ISSUE THREAD

**Issue by sinairusinek** [inception-project/inception#4166]
**Describe the bug**
I am not sure if this is a bug or an error on my part:  I cannot export the sentence id's  (which are crucial for me) and word order(less crucial) from a TEI that I imported and annotated. 

**To Reproduce**
1. upload xml with xml:id's
2. download xml
3. no id found

**Expected behavior**
My preferred export format is inline xml where the sentence id will be identical to the xml-id the s elements. I didn't find the ID's also in the CAS 1.0 export which I was told was supposed to include all data in the file. 

**Screenshots**
input text with xml:id's:
<img width="627" alt="Screen Shot 2023-08-30 at 11 05 58" src="https://github.com/inception-project/inception/assets/4381316/f0440715-4389-437b-a129-2b73291179ab">
output text without id's:
<img width="917" alt="Screen Shot 2023-08-30 at 11 07 26" src="https://github.com/inception-project/inception/assets/4381316/16211c7e-9f5f-43e8-89b0-7fb03d6fb678">

**Please complete the following information:**
 - Version and build ID: [ 23.6 (2022-05-29 11:50:02, build e3136a42)]
 - OS: [Mac High Sierra 10.13.6 ]
 - Browser: [chrome,]

**Additional context**
Adding a sample source file. I changed the extension from xml to txt to fit here. 
[ByNameRashiAug30source.txt](https://github.com/inception-project/inception/files/12473288/ByNameRashiAug30source.txt)

**Comment by reckart** [comment]
I wouldn't say it is a bug, but it is also not currently a feature that the `xml:id` attribute of TEI files from either sentences or tokens would be retained on import (assuming you are using the `TEI` format from the format dropdown when importing the TEI files). The TEI reader currently simply discards this information.

**Comment by sinairusinek** [comment]
Thanks! Can we make it into a feature request?

**Comment by reckart** [comment]
Sure. The problem though (as I said) is that the info is discarded on import. So if we add the feature, it will not affect any docuemnts you have already imported/annotated - only new ones.

**Comment by sinairusinek** [comment]
Great! this will be very helpful! (xml:id to sentence id). No problem about the current files. Thanks!

**Comment by sinairusinek** [comment]
should I write it separately as feature request?

**Comment by reckart** [comment]
No need, I'll just label this issue here as a feature request.
