### ISSUE TITLE
Data export not possible

### ISSUE THREAD

**Issue by snaxony** [inception-project/inception#4171]
**Describe the bug**
I am currently facing the problem that I can not export data from our Inception project. Both provided "methods" don't work:
1. Administration > pick project > Export  > Export backup archive | Export curated documents
2. choose project > Settings > Export > Export backup archive | Export curated documents
While the first method still worked some while ago (28.07.23) , the second never worked for me.
I intended to export as UIMA CAS XMI (XML 1.0), but other formats didn't work es well.
After clicking the "Start export..." button the loading wheel appears shortly, but nothing else happens.

It is also noteworthy that the right window panel remains grey with the letters "Connecting..."  after the Export tab was entered.

The same behavior is true for firefox and chromium browsers.
The current installation is: INCEpTION -- 29.0 (2023-08-08 14:34:53, build 86d5bbd2) 

**To Reproduce**
1. Administration > "pick project" > Export  > Export backup archive | Export curated documents

**Expected behavior**
1. After clicking the "Start export..." button it is expected that the download of the backup-archives starts.
2. the right window panel should display information instead of writing "Connecting..." 

**Screenshots**
Screenshot:
![inception_issue_4171](https://github.com/inception-project/inception/assets/131248627/d3c97de9-5f17-45d3-8e93-fafe110a147b)
Console Logs:
[inception.wesis.org-1694109082330.log](https://github.com/inception-project/inception/files/12552134/inception.wesis.org-1694109082330.log)

**Please complete the following information:**
 - Version and build ID: INCEpTION -- 29.0 (2023-08-08 14:34:53, build 86d5bbd2) 
 - OS (client): Ubuntu 22 (reproduction & logs), Windows 10 (reproducable)
 - Browser: chromium, firefox

**Additional context**
none

**Comment by reckart** [comment]
Please check if your INCEpTION instance is running behind a reverse proxy. If so, please check that your reverse proxy is configured to support WebSocket connection upgrades. You can find corresponding options for several reverse proxies in our documentation:

https://inception-project.github.io/releases/29.0/docs/admin-guide.html#sect_reverse_proxy

**Comment by snaxony** [comment]
Wow that was fast. I will check this out and reach out back with the results. Thank you very much for the quick help.

**Comment by reckart** [comment]
Since there was no additional feedback, I assume the issue has been resolved. Closing.
