### ISSUE TITLE
Reduce logging output during indexing

### ISSUE THREAD

**Issue by Rentier** [inception-project/inception#418]
**Describe the bug**
For every annotation and token (?) indexed, a line is logged. This totally overflows the log, other messages cannot be found and read easily.

**To Reproduce**
Open a project with several documents

**Expected behavior**
The log is readable and not moving too fast

**Please complete the following information:**
All versions

**Additional context**
Use `trace` instead of `debug`

**Comment by naveen2507** [comment]
Covering this issue with PR #417
