### ISSUE TITLE
Seamless Project Migration: Export and Import Projects Across Inception Instances and Versions

### ISSUE THREAD

**Issue by shgulomov** [inception-project/inception#4194]
**Is your feature request related to a problem? Please describe.**
 I am facing difficulty in exporting an entire project, including its settings, documents, and annotations, from an older Inception server (version 26.0) and importing it into a new server (version 29.0) running on Kubernetes.

**Describe the solution you'd like**
I would like a feature in the Inception labeling tool that allows users to easily export the whole project, including settings, documents, and annotations, and import them into another server with a different version of Inception.

**Describe alternatives you've considered**
An alternative solution could be to manually export and import documents and annotations, but this process can be time-consuming and may not preserve all project settings.

**Additional context**
This feature would be helpful for users who need to migrate their projects between different Inception instances or upgrade their Inception servers to newer versions while preserving their existing projects and annotations.

**Question**
What is the best solution for me at this situation? What can I do alternatively?

**Comment by reckart** [comment]
Go to the project settings panel and in the left sidebar scroll down to "Export". There you can export the entire project including all settings. The only thing missing from the export are passwords of any users. So if you import the project on another instance where the users are not present yet, you can enable the option "create missing accounts" in the import panel and then you have to manually set a password for each of the created users in the user management.

If this does not work for you, please describe what error you are facing.

**Comment by shgulomov** [comment]
![image](https://github.com/inception-project/inception/assets/111745208/6c26be60-ca47-4ae2-ac62-1bae12561c82)

It couldn't export the project with the following error

**Comment by reckart** [comment]
Instead of the format "AUTO", you can choose "No additional format" - that should resolve the issue. For copying a project to another instance, you do not need any additional format in the project export.

Once you are on INCEpTION version 29.0 or higher the [issue with the non-serializable characters](https://github.com/inception-project/inception/issues/4058) should be fixed.

Note that INCEpTION 29.2 has just been released - optimally you should upgrade to this version.

Also note that the Admin Guide explains an [in-place upgrade procedure](https://inception-project.github.io/releases/29.2/docs/admin-guide.html#sect_upgrade) where moving to a different instance through project exports is not required. It is always a good idea to keep backups though.

**Comment by shgulomov** [comment]
I could successfully export with "No additional format" option. 
However, when importing, it is throwing the error:
![image](https://github.com/inception-project/inception/assets/111745208/47760a8a-29d3-4847-87e9-ee57a5d6ba1b)

**Comment by shgulomov** [comment]
![image](https://github.com/inception-project/inception/assets/111745208/e7576b7b-af04-4c67-8f6e-e1be1162ad33)

This is the error log inside the Pod in Kubernetes.

**Comment by reckart** [comment]
Ok, this is strange. What database are you using on the new instance? If you are using MariaDB, what encoding does the database / the `logged_event` table use? Did you set up the DB manually or are you using our Docker Compose file?

**Comment by shgulomov** [comment]
In the previous setup, our old Inception instance was running on an EC2 server using Docker Compose, and it was connected to the same MariaDB database on AWS that our new instance is currently connected to.

About the encoding, I don't remember that I've set anything related to encoding while setting up the DB

**Comment by reckart** [comment]
Please check that the DB and all tables are set up to use the `utf8mb4_bin` encoding.

See https://inception-project.github.io/releases/29.2/docs/admin-guide.html#_prepare_database

**Comment by shgulomov** [comment]
![image](https://github.com/inception-project/inception/assets/111745208/ed7f29fe-79be-4631-8e53-ebe041a79b5c)

Basically, we have several parameters related to encoding. To ensure compatibility, it is recommended that all these parameters are set to utf8mb4, right?.

**Comment by reckart** [comment]
I only am aware of the settings listed in the INCEpTION documentation, not about the others.

**Comment by shgulomov** [comment]
The error still exists even after having changed the parameters to the specified encoding.

**Comment by reckart** [comment]
Ah, did you delete/re-create the DB and the tables after changing the parameters? If you kept the db / tables, you'd have to alter them individually - the global parameters do not affect already existing dbs/tables, only new ones. 

If removing the event.log file fixes the issue, it would be interesting to know where the characters that the DB complains about came from.

**Comment by shgulomov** [comment]
I haven't deleted the database yet. First, I will try import it by deleting event.log.

**Comment by shgulomov** [comment]
Indeed, the error was related to event.log. After having deleted it, I could successfully imported. Thank you very much for the support!

**Comment by reckart** [comment]
> I think after the recreation of the database, there won't be need in deleting the event.log, right?

Hopefully.

**Comment by shgulomov** [comment]
Somehow, some projects cannot be exported. When I press the export button, nothing happens. There is a blink of loading though. But, nothing happens after all.

**Comment by shgulomov** [comment]
What could be the reason?. The project is a large though, like 1.5+ gb.

**Comment by reckart** [comment]
Do you see anything in the logs?

**Comment by shgulomov** [comment]
Bunch of info logs about the project being exported, and this error:


Exception in thread "inception-worker-218" java.lang.IllegalArgumentException: Document contains at least one immense term in field="content" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: '[115, 1, -48, -97, -47, -128, -48, -75, -48, -68, -47, -116, -48, -75, -47, -128, 45, -48, -68, -48, -72, -48, -67, -48, -72, -47, -127, -47, -126, -47]...', original message: bytes can be at most 32766 in length; got 33089

**Comment by shgulomov** [comment]
I think it is about the encoding again

**Comment by shgulomov** [comment]
Is there any way that we can export projects without UI? or any solution how we can export annotated docs  or settings

**Comment by reckart** [comment]
You can enable the [remote API](https://inception-project.github.io/releases/29.2/docs/admin-guide.html#sect_remote_api) and then export projects using that.

**Comment by reckart** [comment]
I assume all questions have been resolved. Closing.
