### ISSUE TITLE
How to upgrade INCEpTION deployed with docker?

### ISSUE THREAD

**Issue by fishfree** [inception-project/inception#4281]
I deployed INCEpTION  according to [this doc](https://inception-project.github.io/releases/27.3/docs/admin-guide.html#_docker_compose).  Now how can I upgrade to the latest version without data loss? Please share some detailed doc. Many thanks!!

**Comment by reckart** [comment]
First of all, make sure you have a backup. The easiest way is to export each of the projects. For a group installation, make sure you backup the data folder/volume as well as the database contents in such a way that you can restore them. How exactly that works depends on your setup.

For the docker-compose based setup, you can for example change the version for the `app` image to the latest available version. Then stop the compose environment (do **NOT** delete the volumes), pull the latest images, then start the environment again, e.g.

```
docker compose pull; docker compose down; docker compose up -d
```
