### ISSUE TITLE
Suppress or mark concepts in the search that are marked as owl:deprecated

### ISSUE THREAD

**Issue by tehaef** [inception-project/inception#4379]
**Is your feature request related to a problem? Please describe.**
We use an OWL ontology as a local knowledge base in INCEpTION (30.0; local/default lucene search). The ontology includes some concepts that are marked with `owl:deprecated`. As expected, they do not show up at most places in INCEpTION like for example the knowledge base browser. But (unexpectedly) they do show up in the "identifier" search bar and are not visually discernible from non-deprecated concepts.

**Describe the solution you'd like**
It would be nice to have a way to either visually identify these concepts or suppress them altogether.

**Describe alternatives you've considered**
We tried the following workarounds:
* Converting `owl:deprecated` to `rdfs:comment`. This works partially. However, if there is more than `rdfs:comment`, only one of them seems to be displayed and in a non-predictable way.
* In the knowledge base settings (custom schema), setting "Description IRI " to `owl:deprecated` this does not work at all.
* In the knowledge base settings (custom schema, setting "Description IRI " to `schema:description` and converting the deprecation statement to this property which is otherwise unused. This kind of works, but we won't see the regular comments anymore.

**Additional context**
-

**Comment by reckart** [comment]
Can't you just filter the KB before importing in such a way that all deprecated concepts are removed?

**Comment by tehaef** [comment]
Yes, filtering these concepts out was our first intuition, too. After giving it some thought, however, my suspicion was that it might be not so easy (at least for some knowledge bases/ontologies) while keeping the internal structure of the rest of the KB intact at the same time. In simple cases, you can probably just remove the concept and all triples pertaining to it (recursively), but for some more involved cases it would probably require a thorough by-case investigation of the actual KB/ontology first and/or maybe the application of a semantic reasoner. Maybe i'm wrong. In case, i thought having a visual cue to quickly identify these concepts might be a compromise between having the concepts just in the KB and filtering them out.

**Comment by reckart** [comment]
Thanks for the feedback. Do you know if deprecation is also a feature in other models like SKOS or others and how it is modelled there?

**Comment by tehaef** [comment]
I do not know of any other models that have deprecation as a feature, but i'm no expert on this. I'm currently only aware of one SKOS-based vocabulary [1] that has some sort of deprecation and it uses a literal deprecation note with `skos:historyNote` as well as a formalized one using `owl:deprecated`. This is, more or less, also the approach suggested by [SKOSMOS](https://github.com/NatLibFi/Skosmos) [2]. A [quick search](https://lov.linkeddata.es/dataset/lov/terms?q=deprecated) revealed two other vocabularies that apparently have such a property but i don't know anything about them.

[1] https://zbw.eu/stw/version/latest/download/about.en.html
[2] https://github.com/NatLibFi/Skosmos/wiki/Data-Model#deprecated-concepts

**Comment by reckart** [comment]
@tehaef INCEpTION 31.0 will mark deprecated concepts in the auto-complete dropdown.

![Screenshot 2024-01-30 at 11 59 19](https://github.com/inception-project/inception/assets/1410238/d9105a5d-b093-43c1-8a8b-97775432483a)

**Comment by tehaef** [comment]
@reckart This is great – Thank you so much for implementing this!
