### ISSUE TITLE
Add more default KB profiles and tests

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#438]
Add more default KB profiles and also add these to the KB tests:

* `http://zbw.eu/beta/sparql/stw/query` (SKOS ontology)
* `http://zbw.eu/beta/sparql/gnd/query`(SKOS ontology)

**Comment by naveen2507** [comment]
@reckart I have already added that for 0.5.0 in https://github.com/inception-project/inception/blob/6d86150e99cfc2e80f2269d7093dcc8768168a0e/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceRemoteTest.java#L219

**Comment by naveen2507** [comment]
@reckart I will add the KB Profile for this

**Comment by naveen2507** [comment]
@reckart I will add the KB Profile for this

**Comment by naveen2507** [comment]
@reckart Bdw, Yago is failing on  [build server](https://zoidberg.ukp.informatik.tu-darmstadt.de/jenkins/job/INCEpTION%20(GitHub)%20(PR%20builder)/783/) for connection issue. Although Its running on my local.
