### ISSUE TITLE
Relations are not exported using TSV3.3

### ISSUE THREAD

**Issue by moloti** [inception-project/inception#4380]
### Describe the bug

When I'm exporting my annotated project using TSV3.3, relation layers don't get exported, only span layers. 
So in my TSV File, I only have #T_SP and no #T_RL even though I have annotated relations.

### To Reproduce

Create a Span Layer and a Relation Layer and annotate a document with a direct relation between two spans. Then export.

### Environment

Version and build ID: 29.3 (2023-09-26 18:49:48, build d5392a99)
Operating system: OS X Sonoma
Browser: Chrome

### Additional context

Maybe I'm missing a setting somewhere, but I haven't found one.

**Comment by reckart** [comment]
I tried to reproduce this but for me, it works.

* Create a new project from the "basic span/relation" template
* Upload a simple text document
* Annotate words and relation
* Export from the annotation page in TSV 3.3 format

![Screenshot 2023-12-19 at 14 49 12](https://github.com/inception-project/inception/assets/1410238/4e39b35c-7c37-4219-8dab-333981aae7ae)

```
#FORMAT=WebAnno TSV 3.3
#T_SP=custom.Span|label
#T_RL=custom.Relation|label|BT_custom.Span


#Text=test test
1-1	0-4	test	one	_	_	
1-2	5-9	test	two	relation	1-1	
```

Can you provide a simple project export to reproduce the issue?

**Comment by reckart** [comment]
Even if I remove the features and only have a simple span/relation without any features at all, it works:

```
#FORMAT=WebAnno TSV 3.3
#T_SP=custom.Span|
#T_RL=custom.Relation|BT_custom.Span


#Text=test test
1-1	0-4	test	*	_	
1-2	5-9	test	*	1-1	
```

**Comment by moloti** [comment]
Maybe I found the issue. It seems like having a feature of type StringArray on the relation is causing the issue. Just a wild guess. I attached an example project.
[admin6822998262231466828.zip](https://github.com/inception-project/inception/files/13716849/admin6822998262231466828.zip)

**Comment by reckart** [comment]
String array features are not supported by WebAnno TSV. The format is a legacy format which supports the mechanisms that were present in WebAnno. For those INCEpTION projects where you only use such old mechanisms, an export in WebAnno TSV is possible. However, new mechanisms like multi-value features are not getting support in WebAnno TSV anymore. The recommended export format for INCEpTION is rather UIMA CAS XMI (XML 1.0) or UIMA CAS JSON which can are both supported e.g. by [DKPro Cassis (Python)](https://github.com/dkpro/dkpro-cassis) or Apache UIMA (Java, [1](https://github.com/apache/uima-uimaj-io-jsoncas/tree/main), [2](https://github.com/apache/uima-uimaj#creating-a-common-analaysis-structure-object)).

**Comment by moloti** [comment]
Okay, thanks, I was not aware of that. In that case I will close the issue.
I started with UIMA CAS JSON and DKPro Cassis, but I found it hard to work with and not well documented.

**Comment by reckart** [comment]
Writing good documentation is difficult, in particular for developers trying to put themselves into the position of a newcomer for whom the documentation should be helpful.

Pointers/feedback on how to improve the documentation would be welcome in the respective repos. Pull-requests with documentation improvements would be even better (possibly after questions have been discussed in an issue or forum post).

**Comment by reckart** [comment]
Feedback on how to improve the API - in particular for Cassis - are also helpful :)

**Comment by moloti** [comment]
Sure, I'm happy to do that. Not today, but I'll open a thread in the Cassis repo with some questions and thoughts on the API. I understand the idea of a format that is easy to exchange and also import again, but it also adds complexity it seems :). 

It would be great if you had more examples of how to get your annotations into a format that can be used for NER, entity linking, RE, etc. with other NLP tools without much effort. For example this one: 
{
  # document ID (please make sure doc_key can be used to identify a certain document)
  "doc_key": "CNN_ENG_20030306_083604.6",

  # sentences in the document, each sentence is a list of tokens
  "sentences": [
    [...],
    [...],
    ["tens", "of", "thousands", "of", "college", ...],
    ...
  ],

  # entities (boundaries and entity type) in each sentence
  "ner": [
    [...],
    [...],
    [[26, 26, "LOC"], [14, 14, "PER"], ...], #the boundary positions are indexed in the document level
    ...,
  ],

  # relations (two spans and relation type) in each sentence
  "relations": [
    [...],
    [...],
    [[14, 14, 10, 10, "ORG-AFF"], [14, 14, 12, 13, "ORG-AFF"], ...],
    ...
  ]
}
Or an example how do go from the UIMA CAS format to a BIO format. 

I mean you write in the readme "This can ease in particular the integration of Python-based Natural Language Processing (e.g. [spacy](https://spacy.io/) or [NLTK](https://www.nltk.org/)) and Machine Learning librarys (e.g. [scikit-learn](https://scikit-learn.org/stable/) or [Keras](https://keras.io/)) in UIMA-based text analysis workflows."
But the only example is the one with spacy which is not super descriptive to be honest :)

**Comment by reckart** [comment]
@moloti looking forward to your thread in the cassis repo for discussion.
