### ISSUE TITLE
Duplicate entries for Wikidata

### ISSUE THREAD

**Issue by naveen2507** [inception-project/inception#440]
**Describe the bug**
Duplicate entries for Wikidata in Concept tree 

**To Reproduce**
1. Create a project
2. Configure Wikidata in KB
3. Go to Knowledge Base 
4. Duplicate entries in Wikidata Concept tree

**Expected behavior**
Should not show duplicate entries

**Screenshots**

![image](https://user-images.githubusercontent.com/10420950/43770184-ec278f10-9a3b-11e8-874b-a6737ba19f2e.png)

**Please complete the following information:**
 - Technische Universität Darmstadt -- Computer Science Department -- INCEpTION 𝜶 -- 0.5.0-SNAPSHOT (2018-08-06 14:02:37, build e230e9eb1add8be17759fca7ec081d0003d92107)
 - Linux
 - chrome

**Additional context**

**Comment by reckart** [comment]
I also observed this with at least one other ontology (either `http://zbw.eu/beta/sparql/gnd/query` or `http://zbw.eu/beta/sparql/stw/query` but I don't remember which concept).

**Comment by naveen2507** [comment]
Issue with the #51 : When we add multiple comments to the entity, then it show the concept in duplicity. 

Possible Solution : We should be able to handle this with SPARQL, otherwise it would be computationally very expensive

**Comment by reckart** [comment]
I still seem to see duplicates:

**Comment by naveen2507** [comment]
Ohhk. Need to take a look into this.

**Comment by reckart** [comment]
Opened new issue as it seems to be a new bug.
