### ISSUE TITLE
Adding new document level non-singleton annotations adds them in strange order

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#4449]
### Describe the bug

When adding new document level annotations, I would expect the list to be ordered. But they are added in between the existing ones without any apparent logic, adding 2 after another adds them often at different spots. I would expect them to be ordered, added at the top or bottom.

### To Reproduce

1. Create document level layer with string feature
2. Add some annotations (5+)
3. See that adding new ones has no apparent order.

### Expected behavior

I would expect them to be ordered, added at the top or bottom.

### Environment

Version and build ID: see bottom of the INCEpTION browser screen
Operating system: e.g. stable
Browser: Chrome

**Comment by reckart** [comment]
The annotations in the document metadata sidebar are grouped by annotation layers. The layers are ordered by their name. Does that explain the behaviour that you see or do you see a different behavior?

**Comment by jcklie** [comment]
I mean this:


https://github.com/inception-project/inception/assets/934600/2fceb771-3c87-47c4-8204-f5b85c3e0dbe
