### ISSUE TITLE
Release 0.4.2

### ISSUE THREAD

**Issue by naveen2507** [inception-project/inception#445]
- [x] Merge 0.4.x into master
- [x] Release the kraken
- [x] Merge 0.4.x again into master with `git merge -s ours 0.4.x`
- [x] Sign the JAR
- [x] Update auto-deployment script for testing on blinky
- [x] Update stable instance on blinky to release version
- [x] Upload the Jar to releases
- [x] Write mail
- [x] Update documentation
- [x] Write release announcement and add to GitHub release
- [x] Send release announcement and send to mailing list

**Comment by reckart** [comment]
@naveen2507 The three commits filed above under this issue do not have the correct format. The first line of the comment should consist of the issue number and the issue title. I do also not understand what `Merge to 0.4.x` is supposed to mean. Looking at the history, the commits are clearly no merge-commits.

**Comment by naveen2507** [comment]
@reckart  We have already reverted the changes #451. I will close this issue and reopen another fresh issue.

**Comment by reckart** [comment]
@naveen2507 Why do you need to close this issue and create a new one?

**Comment by naveen2507** [comment]
> @naveen2507 Why do you need to close this issue and create a new one?

As you said, the issue has commits which are clearly no merge-commits. We have already reverted the changes for one of the pull request for milestone 0.4.2 (it needs more evaluation on functionality level of approach). I will raise a fresh issue for the release for 0.4.2 tomorrow to do the release.

**Comment by reckart** [comment]
Why can't you just continue with this issue? Why is there a need for a new issue number?

**Comment by naveen2507** [comment]
@reckart Ok . I thought it wud be better as the issue refers to commit which has already been reverted and would help you to review the PR if we have a fresh issue. But, ofcourse we can continue with the same issue otherwise.

**Comment by reckart** [comment]
I'm just wondering - I wouldn't have closed the issue until it's done.

The bad commits seem to be only on the branch `bugfix/421-cannot_create_subclass_issue` (it doesn't seem they were merged into the `master` or `0.4.x` branches) - so I'd probably rewrite the history of that branch to remove the commits. That should also remove them from this issue.

**Comment by reckart** [comment]
@naveen2507 ok, master is prepped now. Feel free to continue on preparing the actual release branch/PR.
