### ISSUE TITLE
Support for link feature recommendations

### ISSUE THREAD

**Issue by jvdzwaan** [inception-project/inception#4491]
I'm trying to create a recommender for measurements. In our data model, we have layers `Measurement` and `Measurementpart` that are linked with a `MeasurementPartLink`. A measurement has a feature `parts`, which points to an array of `MeasurementPartLink`s. 

Example:
```
w.c.Measurement(
    begin=3, 
    end=12, 
    parts=u.c.FSArray(
        elements=[
            webanno_custom_MeasurementPartsLink(
                xmiID=16159, 
                role='value', 
                target=webanno_custom_Measurementpart(
                    xmiID=16038, 
                    begin=17, 
                    end=19, 
                    type=Type(name=webanno.custom.Measurementpart)
                ), 
                type=Type(name=webanno.custom.MeasurementPartsLink)
            )
        ]
    ), 
) 
```

Is it possible to create a recommender that makes recommendations like this? If so, do you have an example of how to do this?

I created a a hard-coded example that seems to produce the correct data structure (no errors from inception), but it doesn't show up as recommendation in inception.

**Comment by reckart** [comment]
@jvdzwaan I have moved the issue from the external recommender module to INCEpTION itself.

**Comment by jvdzwaan** [comment]
Thank you!
