### ISSUE TITLE
Support exporting in brat format

### ISSUE THREAD

**Issue by jianlins** [inception-project/inception#4498]
Brat is another annotation tool. But we found [its format](https://brat.nlplab.org/standoff.html) is really intuitive and easy to parse, and it's concise. Can you add this format in export function?

**Comment by reckart** [comment]
brat export will be available as an experimental feature in INCEpTION v31. You will have to activate it in the `settings.properties` file before it can be used. Please try it and provide feedback. I'd be curious if the brat format that INCEpTION can produce works for you.
