### ISSUE TITLE
Other data types than strings in active learning

### ISSUE THREAD

**Issue by MeDarina** [inception-project/inception#4527]
It would be nice to use other types than the "Primitive: String" as a feature in the active learning of the recommendation technology. Currently, only this type is available.

Currently, we need a Boolean an we are using the work-around of adding the string labels true and false - which works fine (but using the "real" type we need would be cleaner)

**Comment by reckart** [comment]
Implemented in 1c7c1a0ea5a6aa40932f220ed20e7c175fabd545 as part of #4525 - Support recommendations for non-string primitive features.
