### ISSUE TITLE
Unit test case failing

### ISSUE THREAD

**Issue by naveen2507** [inception-project/inception#453]
**Describe the bug**
Test is failing on master for Jenkins check

**To Reproduce**
PR failing due to issue #444 

**Expected behavior**
Jenkins check should pass

**Screenshots**
![image](https://user-images.githubusercontent.com/10420950/44029262-f1e48208-9efc-11e8-81b8-19c750faccf5.png)

**Comment by naveen2507** [comment]
Need to fix this issue for release of 0.4.2

**Comment by betoboullosa** [comment]
Duplicate of #444.
