### ISSUE TITLE
Cannot create long-distance relation in PDF editor

### ISSUE THREAD

**Issue by tpluscode** [inception-project/inception#4547]
### Describe the bug

The user guide instructs to select first annotation and then right-click on the target and "select Link to…​.". This does not work, as the standard context menu appears

### To Reproduce

1. Open a document for annotating
2. Click on a span
3. Scroll down to another span
4. Right click

### Expected behavior

Presumably, a custom menu should appear

### Screenshots

https://github.com/inception-project/inception/assets/588128/5e054913-97cc-498f-8396-550a5ea6d272

### Environment

Version and build ID: 31.1 (2024-02-20 23:27:52, build c78ce3c5)
Operating system: macOS 10.15.7
Browser: 
1. Brave 1.61.120 (Chromium 120.0.6099.234)
2. Firefox 123

**Comment by reckart** [comment]
Seems to be an issue with the PDF editor.

**Comment by tpluscode** [comment]
Wow. Thanks for such a quick fix
