### ISSUE TITLE
Support full text search in knowledge bases running on AllegroGraph

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#4572]
**Is your feature request related to a problem? Please describe.**
AllegroGraph SPARQL endpoints cannot use FTS.

**Describe the solution you'd like**
Add support for the AllegroGraph FTS mechanism.

**To do**
- [x] Provide FTS support
- [x] Upgrade test to AllegroGraph 8.1.1 / enable test

**Comment by tpluscode** [comment]
FYI, AllegroGraph 8.1.1 has been published

**Comment by reckart** [comment]
Great. Tested and it works now.
