### ISSUE TITLE
Selecting multiple target layers for a link property

### ISSUE THREAD

**Issue by tpluscode** [inception-project/inception#4580]
**Is your feature request related to a problem? Please describe.**

I defined the following layers:

- Bus Or Coach
- Engine
- Spec

I intended `Spec` to be a universal "leaf" that I could link to either `Bus Or Coach` or `Engine` to define its properties, such as "length" or "cylinder count".

The problem is that I need to define a separate link property for each target. Currently, that requires me to either create a separate link property for `Bus Or Coach`, `Engine`, and any additional target layer. The other option is multiple `"Spec"` layers, for each layer it would describe. 

Both options add clutter to the annotation view and overall process

**Describe the solution you'd like**

It would simplify my layers and annotation if it was possible to select not one but multiple layers allowed as link targets (#1319?)

**Describe alternatives you've considered**

Allowing relations between layers would also be an option, if I were able to freely link any two annotations of various layers.

**Comment by tpluscode** [comment]
This issue might be of "thinking out loud" category.

On second thought, the idea of separate "detail" layers, such as "Engine detail" or "Bus detail" may not be bad ideas to separate concerns logically and visually although it will probably explode if the structure becomes more complex, and the relations deeper (in graph lingo)

**Comment by reckart** [comment]
You can select `Link: Any` which allows you to link to any kind of layer.

However, I would suggest you try using just a single span and relation layer and adding a string feature on that layer `category` and associate it with a tagset `bus or coach`, `engine`, etc.

**Comment by reckart** [comment]
People using INCEpTION to annotate statements in texts typically follow this approach at the moment:

* span layer `concept`:
  * `concept` feature allowing to link it to a concept from a knowledge base
  * `value` feature used if the annotated span is not a concept but a (normalized) literal value
* relation layer `relation`
  * `concept` feature allowing to link it to a concept from a knowledge base

A statement is then a triple: `concept` --(`relation`)--> `concept`

So the origin of a relation annotation is the subject of the statement and that would always be linked to a concept.
The target of a relation is the object of the statement and would either be linked to a concept or be a literal value.
The concept feature on the relation layer indicates the predicate of the statement.

**Comment by tpluscode** [comment]
Of course! How didI miss the `<Any>` setting

The thing about my desired output is that the values are complex structures. For now using `schema.org/QuantitativeValue` etc. They can even be deep, and have additional, optional properties themselves.

Think of a **bus** `B` whose **engine** `MAN D0834 LOH03` outputs `132 kW` at `400 RPM`. The engine is **mounted** at the `rear`

1. The bus would be annotated as a concept. 
2. The engine could be another layer, not linked to concept but rather modeled as a blank node. `schema.org` has an `EngineSpecification` type as a structure to describe engines.
3. The output power would be that `Detail` layer, modeling `schema.org/QuantitativeValue`. It has a required `value` property, which could be by default derived from the annotated text.
4. I wanted to avoid annotating units, instead sourcing them from a KB as a property of the detail layer
5. Finally, details can have more details, as above the engine power is measured at a specific RPMs
6. To make things more interesting, the engine placement is actually a concept itself

So, the final would be like this:

```turtle
<>
  # layer bus, linked to a concept
  wikibus:bus </bus/B> ;
  schema:vehicleEngine
    [
      # layer engine
      a schema:EngineSpecification ;
      schema:engineType "MAN D0834 LOH03" ;      # annotated text
      wikibus:enginePlacement wikibus:Rear ;     # generic concept layer, linked to bus layer?
      schema:enginePower
        [
          # layer detail
          a schema:QuantitativeValue ;
          schema:value 132 ;                     # annotated text
          schema:unitCode unit:KiloW ;           # property unit
          schema:valueReference
            [
              # layer detail
              a schema:QuantitativeValue ;
              schema:value 400 ;                 # annotated text
              schema:unitCode unit:REV-PER-MIN ; # property unit
            ] ;
        ] ;
.
```

The generic concept layer could be useful to map terms used as objects of triples, instead of the structure like `Bus`. Other examples include fuel type (`Diesel`, etc) or engine environmental norms (`EURO V`, etc).

Given the ability to create relations freely between all layers would still be the easiest way to connect the graph. Above, each such occurrence of relation would map properties `schema:vehicleEngine`, `wikibus:enginePlacement`, `schema:valueReference` which the necessity. Else, I think I will only use link so that there is only one way to define all linkage
