### ISSUE TITLE
Hide arcs in PDF editor by default until annotation is selected

### ISSUE THREAD

**Issue by tpluscode** [inception-project/inception#4582]
**Is your feature request related to a problem? Please describe.**

Given many links, the editor view can quickly become very cluttered with arrows obscuring content. It then becomes quite difficult to select spans to annotate

**Describe the solution you'd like**

It would be nice to be able to hide link arcs by default, either as a global setting, or specific switch in property settings.

Such hidden arcs would then only appear once an annotation is selected which is the source or target of a link

**Comment by tpluscode** [comment]
I suppose similar could apply to relations...

**Comment by reckart** [comment]
It's probably not something I will get around to doing soon... 

Didn't you mention you like coding JavaScript? The PDF editor is JavaScript ;)

**Comment by reckart** [comment]
Duplicate of #4826

@tpluscode not the default, but it is an option now.
