### ISSUE TITLE
Annotations are misaligned when PDF pages vary in dimensions

### ISSUE THREAD

**Issue by tpluscode** [inception-project/inception#4587]
**Describe the bug**

I have PDFs where some pages are merged. Sometimes they are fold outs where 4 or more pages of the original document are a single page in PDF

**To Reproduce**
1. Go to a project
2. Upload [this PDF](https://wikibus.blob.core.windows.net/sources5711/Mercedes-Benz%20Kombi-Ausflugs-Omnibus%20O%20303%20KHP-A.pdf)
3. Open it for annotation
4. Go to page 6 which is 4 times wider than a single page
5. Start annotating something
6. Notice that the highlights are not aligned with the document contents although mouse events are correctly positioned

The degree to which the annotations are off appears to change with zoom level

**Screenshots**

![image](https://github.com/inception-project/inception/assets/588128/dc7e109e-4a77-4b44-b951-92d90e57d5ce)

https://github.com/inception-project/inception/assets/588128/ecfe0fba-340e-4f98-b571-bc0c78bc2ecf

**Please complete the following information:**
 - Version and build ID: 31.1 (2024-02-20 23:27:52, build c78ce3c5)
 - OS: OS X Catalina
 - Browser: Brave 1.61 (Chromium 120)

**Comment by reckart** [comment]
I had fixed this some time ago for the case that the first page is wider than the others - but in your case, it is just the opposite. Should work now.

**Comment by reckart** [comment]
https://github.com/inception-project/inception/assets/1410238/80da4cd3-069c-462f-8ac6-7c72429e7cba

**Comment by tpluscode** [comment]
> the case that the first page is wider than the others

Now that you mention it, I tried one like that too. There's this effect that the annotations shift initially but zoom in/out fixes them:

https://github.com/inception-project/inception/assets/588128/77009d28-93ec-4a60-a8f6-534c65d61fa0

That is not so bad and I also notice the pages are actually clipped a little (separate issue?)

**Comment by reckart** [comment]
@tpluscode do you have a public link to that PDF?

**Comment by tpluscode** [comment]
Sorry, yes: https://wikibus.blob.core.windows.net/sources1/TU%CC%88RKKAR%20CITY%20ANGEL%20E.D..pdf

**Comment by tpluscode** [comment]
I confirm that the Mercedes PDF now behaves correctly. Thank you,

The City Angel above is still broken though. Pages clipped and annotations on the 2nd page shift back and forth

**Comment by reckart** [comment]
@tpluscode The City Angel should work fine with https://github.com/inception-project/inception/pull/4613

**Comment by reckart** [comment]
Regarding clipping - that's probably an issue of PDF.js itself. Maybe try opening the PDF in Mozilla which uses PDF.js as its native PDF viewer to check (although INCEpTION likely uses an older version than current Mozilla versions).

**Comment by tpluscode** [comment]
Super. Thank you so much for your awesome work on this project!

**Comment by reckart** [comment]
If by any chance you hear that the AllegoGraph version with the path query fix comes out (8.1.1 I believe), would be great if you could briefly ping me.

**Comment by tpluscode** [comment]
That PDF looks good in Firefox 123 🤷 

> If by any chance you hear that the AllegroGraph version with the path query fix comes out (8.1.1 I believe), would be great if you could briefly ping me.

Will comment on that issue or PR as soon as I know.
