### ISSUE TITLE
Apache reverse proxy configuration didn't let WebSockets pass through, there is an alternative

### ISSUE THREAD

**Issue by TuringTux** [inception-project/inception#4595]
First of all, thank you for the comprehensive documentation in the INCEpTION admin guide. I managed to get an instance up and running with an Apache reverse proxy in almost no time.

However, I had some issues with Web Sockets as the provided configuration (see https://inception-project.github.io/releases/28.5/docs/admin-guide.html#_apache_httpd_as_reverse_proxy) would not work for me: The browser console always yielded an HTTP 400 error, with no connection possible to the websocket.

After a while, I found the following configuration that works for me:

```apache
<VirtualHost inception.mydomain.example:443>
        ServerName inception.mydomain.example
        ProxyPass "/" "http://localhost:8080/" upgrade=websocket
        ProxyPassReverse "/" "http://localhots:8080/"
        ProxyPreserveHost On

        RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
        RequestHeader set "X-Forwarded-SSL" expr=%{HTTPS}

        SSLCertificateFile /etc/letsencrypt/live/inception.mydomain.example/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/inception.mydomain.example/privkey.pem
        Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
```

This doesn't need `mod_proxy_wstunnel` (which is probably good, because the module is deprecated: https://httpd.apache.org/docs/2.4/mod/mod_proxy_wstunnel.html) and instead uses the `upgrade=websocket` directive from `mod_proxy` (https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#wsupgrade)

Maybe this is helpful for other admins as well :)

If requested, I'd be happy to open a pull request for the docs. Thanks!

**Comment by reckart** [comment]
@TuringTux thanks for sharing your findings. A PR would be very welcome! Best include in the update which version of Apache you were using.
