### ISSUE TITLE
Search results scrolling jumps back to top

### ISSUE THREAD

**Issue by UWinch** [inception-project/inception#4608]
**Is your feature request related to a problem? Please describe.**
I'm going through search results from the search sidebar by clicking on the results one by one. When a new document is loaded, the results list jumps back to the top. This makes it hard to keep track of the results that I already looked at.

**Describe the solution you'd like**
It would be great if the place that I scrolled to could be kept when loading a new document by clicking on a search result.

**Describe alternatives you've considered**
My current workaround is to mark my place with the result check-boxes, but this would not be feasible for other workflows.

**Comment by reckart** [comment]
I believe you already opened that bug 4 years ago. https://github.com/inception-project/inception/issues/1606
