### ISSUE TITLE
Improve speed of annotation

### ISSUE THREAD

**Issue by mromanello** [inception-project/inception#462]
**Describe the bug**

I'm annotating a bunch of fairly long documents having many annotations on multiple layers (NER, entity co-reference, entity-linking).  

**To Reproduce**
1. Go to project CHS
2. Select to annotate document `5787_5791.xmi`
3. Select the first mention of 'Plato' (entity type=`AAUTHOR`) 
4. Try to modify the `author_uri` or `work_uri` field by a) unlinking the mention or b) linking with another entity in the KB

**Expected behavior**
You will notice that any operations takes quite a long time (from 1/2 to 1 minute sometimes). The interface is on hold (sort of freezes) and the wheel on the top right corner keeps spinning.  

What I gathered from inspecting the log file is that the application may be slowed down by an indexing process that gets triggered for each change/update on any annotation. Although this indexing should be running in the background, the interface waits for it to complete (wheel stops spinning when indexing completes).

**Please complete the following information:**
 - [Inception stable](https://blinky.ukp.informatik.tu-darmstadt.de/inception-stable/)
- version 0.4.2 

**Additional context**
I was able to reproduce the same issue also on a local installation. I attached an export of the project in case anyone wants to reproduce the issue.

[CHS_2018-08-09_0903.zip](https://github.com/inception-project/inception/files/2292856/CHS_2018-08-09_0903.zip)

**Comment by betoboullosa** [comment]
The scheduler needs to run asynchronously the process of indexing a single document whenever there is a change in an annotation. I'm working on it.
