### ISSUE TITLE
Can not open imported projects which were exported by users with Administration permissions

### ISSUE THREAD

**Issue by thetaaaaa** [inception-project/inception#4644]
**Describe the bug**
I deployed Inception in my laptop, and loged in as the user of admin, with the authority administration. I export an annotation project witch the default setting,and then, I import the project, and try to open it. When I click the project, the project are not opening, and there's a prompt says "[ProjectDashboardPage] requires a project to be selected".

**To Reproduce**
1. Go to 'Project setting.'
2. Click on 'Export.'
3. Go back to main page.
4. Click on 'Import Project',and import the .zip project file which was exported in the last step. 
5. Click the imported project ,and the problem shows up, it cannot be open.

**Expected behavior**
I want every Inception instance and any user can open the project I exported, just like Example projects provided by the official website. 

**Screenshots**
![d598545df0592efe0f8319adbe3c0b6](https://github.com/inception-project/inception/assets/66288540/58f64d54-e6ce-40af-9cf4-37e305f4ccee)

**Please complete the following information:**
 - Version and build ID: INCEpTION -- 31.0 (2024-02-06 23:22:40, build 8e5dd706)
 - OS: Windows
 - Browser: Edge

**Additional context**
**The issue appears to have been resolved**. just now, I found if I filled the slug of the imported project, the project can be open. The problem seems caused by I named the project in Chinese instead of English, and thus the 'slug' was not automatic generated. I want to know if it is the right practice (fill the "slug", which is optional, not mandatory) to open a exported project or it's a BUG. Finally, I hope this issue can be optimized, for example, by setting the slug as a mandatory option.

**Comment by reckart** [comment]
Please fill in the template - without a proper description of how the problem can be reproduced - or what the actual problem is in the first place - no help can be provided.
