### ISSUE TITLE
Unsatisfied Link Error

### ISSUE THREAD

**Issue by gpythomas** [inception-project/inception#4733]
After installation, Inception is running fine on my Ubuntu server, but after importing a project, whenever I try to open a file for annotation I am sent to an error page (inception/whoops). I have attached the relevant section of  application.log for this issue.

I get the same kind of error when trying to import an annotation file (conllu) into a new project:

> ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: /tmp/snappy-1.1.10-b60ba389-1689-4139-ba82-b453e350776f-libsnappyjava.so: /tmp/snappy-1.1.10-b60ba389-1689-4139-ba82-b453e350776f-libsnappyjava.so: failed to map segment from shared object [in thread "http-nio-127.0.0.1-18080-exec-8"]

Note that I am running into this issue only with Inception on my server. I have no issues importing/opening the same projects and annotation files with the standalone Inception jar version 31.4 on my desktop.

**Please complete the following information:**
 - Version and build ID: 31.4 (2024-04-02 20:54:33, build daaa22b2)
 - OS:  Ubuntu 20.04.6 LTS
 - Browser: chrome
 - Java version: openjdk 17.0.10
 
[log.txt](https://github.com/inception-project/inception/files/14984904/log.txt)

**Comment by reckart** [comment]
Interesting. What does `uname -a` say on your system?

**Comment by reckart** [comment]
Are you using selinux by any chance?

**Comment by reckart** [comment]
You could disable snappy by adding `cas-storage.compressed-cas-serialization=false` to your `settings.properties` file, but  if the project you import contains compressed `ser` files, you'd first have to find a machine where you can import it, then disable compression there, then export it again, and then import on your machine.

**Comment by reckart** [comment]
E.g. on  a `x86_64` system, you should have a libraries (e.g. glibc) that export these symbols in order to be able to load the snappy lib:

```
$ objdump -p libsnappyjava.so
...
Version References:
  required from ld-linux-x86-64.so.2:
    0x0d696913 0x00 04 GLIBC_2.3
  required from libc.so.6:
    0x09691a75 0x00 03 GLIBC_2.2.5
    0x09691972 0x00 02 GLIBC_2.3.2
```

**Comment by gpythomas** [comment]
Thanks for your help.

> Interesting. What does `uname -a` say on your system?

`Linux {my server} 5.4.0 #1 SMP Tue Jan 9 19:45:01 MSK 2024 x86_64 x86_64 x86_64 GNU/Linux`

> Are you using selinux by any chance?

It doesn't look like it, the `sestatus` command is not found.

> You could disable snappy by adding `cas-storage.compressed-cas-serialization=false` to your `settings.properties` file, but if the project you import contains compressed ser files, you'd first have to find a machine where you can import it, then disable compression there, then export it again, and then import on your machine.

Thanks, that solved the issue for importation of annotation files (conllu). As you explained in your answer, that still didn't solve the issue with imported projects. I'll try to set up my desktop as a server and install Inception there to see if I can disable compression in the projects.

In the end, do you know what is causing the issue?

**Comment by reckart** [comment]
If possible, snappy-java uses a native library to speed up (de)compression. It embeds binaries for a wide range of platforms. When loading such a library fails, it can be due to reasons such as an incompatible libc6, dynamic linker or potentially an incompatible CPU (e.g. if the binary requires AVX but the CPU does not have it). Your system seems to be reasonably up-to-date. I checked if https://github.com/xerial/snappy-java has any current issues that might be relevant but found none. 

You can try downloading the snappy-java JAR from [here](https://repo1.maven.org/maven2/org/xerial/snappy/snappy-java/1.1.10.5/), extracting it and look for the native library for your platform. Then run `objdump -T libsnappyjava.so | grep "GLIBC"` on it. Also run `objdump -T /lib/x86_64-linux-gnu/libc.so.6`. My guess is that there might be some symbols required by snappy that your libc does not export....

**Comment by reckart** [comment]
Actually, you can probably just call `ldd` on the snappy.so:

```
$ ldd libsnappyjava.so
	linux-vdso.so.1 (0x00007ffdb4173000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f82c4561000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f82c43a1000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f82c4946000)
```

**Comment by gpythomas** [comment]
Here is the output of `objdump -T libsnappyjava.so | grep "GLIBC"` for the Linux x86_64 `libsnappyjava.so` from snappy-java JAR [the xerial repo](https://repo1.maven.org/maven2/org/xerial/snappy/snappy-java/1.1.10.5/):

```
$ objdump -T libsnappyjava.so | grep "GLIBC"
0000000000000000  w   DF *UND*  0000000000000015  GLIBC_2.3.2 pthread_cond_destroy
0000000000000000      DF *UND*  0000000000000b1b  GLIBC_2.2.5 memset
0000000000000000      DF *UND*  00000000000002d1  GLIBC_2.2.5 abort
0000000000000000      DF *UND*  000000000000017c  GLIBC_2.2.5 memchr
0000000000000000  w   DF *UND*  0000000000000015  GLIBC_2.3.2 pthread_cond_signal
0000000000000000      DF *UND*  0000000000000224  GLIBC_2.2.5 malloc
0000000000000000      DF *UND*  000000000000005e  GLIBC_2.2.5 __cxa_atexit
0000000000000000      DF *UND*  00000000000000fb  GLIBC_2.2.5 fputc
0000000000000000      DF *UND*  000000000000018a  GLIBC_2.2.5 free
0000000000000000      DF *UND*  00000000000000e9  GLIBC_2.2.5 strlen
0000000000000000  w   DF *UND*  0000000000000126  GLIBC_2.2.5 __cxa_finalize
0000000000000000      DF *UND*  0000000000000145  GLIBC_2.3   __tls_get_addr
0000000000000000      DF *UND*  0000000000000090  GLIBC_2.2.5 sprintf
0000000000000000      DF *UND*  0000000000000037  GLIBC_2.2.5 syscall
0000000000000000      DF *UND*  00000000000000b9  GLIBC_2.2.5 strerror
0000000000000000      DF *UND*  000000000000013a  GLIBC_2.2.5 fputs
0000000000000000      DF *UND*  0000000000000465  GLIBC_2.2.5 memcpy
0000000000000000      DF *UND*  0000000000000174  GLIBC_2.2.5 memmove
0000000000000000      DF *UND*  00000000000001a3  GLIBC_2.2.5 dl_iterate_phdr
0000000000000000      DF *UND*  0000000000000021  GLIBC_2.2.5 strcmp
0000000000000000  w   DF *UND*  0000000000000015  GLIBC_2.3.2 pthread_cond_wait
0000000000000000      DF *UND*  0000000000000494  GLIBC_2.2.5 memcmp
0000000000000000      DO *UND*  0000000000000008  GLIBC_2.2.5 stderr
0000000000000000      DF *UND*  0000000000000163  GLIBC_2.2.5 fwrite
0000000000000000  w   DF *UND*  0000000000000015  GLIBC_2.2.5 pthread_mutex_lock
0000000000000000      DF *UND*  0000000000000475  GLIBC_2.2.5 realloc
0000000000000000      DF *UND*  0000000000000080  GLIBC_2.2.5 write
0000000000000000  w   DF *UND*  0000000000000015  GLIBC_2.3.2 pthread_cond_broadcast
0000000000000000  w   DF *UND*  0000000000000015  GLIBC_2.2.5 pthread_mutex_unlock
```
Here is the output of `objdump -T /lib/x86_64-linux-gnu/libc.so.6`: [objdump.txt](https://github.com/inception-project/inception/files/15000500/objdump.txt). Not sure what to look for in there.

Here is the output of `ldd` on the `libnsappyjava.so` extracted from the snappy-java JAR above:

```
$ ldd  -v libsnappyjava.so
        linux-vdso.so.1 (0x00007fffd81fc000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa72b5e7000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa72b3f5000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fa72b996000)

        Version information:
        ./libsnappyjava.so:
                ld-linux-x86-64.so.2 (GLIBC_2.3) => /lib64/ld-linux-x86-64.so.2
                libc.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.3.2) => /lib/x86_64-linux-gnu/libc.so.6
        /lib/x86_64-linux-gnu/libm.so.6:
                ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2
                libc.so.6 (GLIBC_2.4) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_PRIVATE) => /lib/x86_64-linux-gnu/libc.so.6
        /lib/x86_64-linux-gnu/libc.so.6:
                ld-linux-x86-64.so.2 (GLIBC_2.3) => /lib64/ld-linux-x86-64.so.2
                ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2
```

**Comment by reckart** [comment]
Seems ok. 

If you want to track this down, maybe consider opening a bug report in the[ snappy-java](https://github.com/xerial/snappy-java) repo. Maybe they have more ideas how to track your problem down.

**Comment by reckart** [comment]
Closing since there was no additional information. Workaround was provided.

If an issue is filed upstream, please link it here.
