### ISSUE TITLE
Is it possible to do semantic role labelling with INCEpTION?

### ISSUE THREAD

**Issue by fishfree** [inception-project/inception#4740]
https://en.wikipedia.org/wiki/Semantic_role_labeling#:~:text=In%20natural%20language%20processing%2C%20semantic,the%20meaning%20of%20the%20sentence.

**Comment by reckart** [comment]
UIMA CAS JSON and UIMA CAS XMI formats can contain any layers that INCEpTION produces.

**Comment by fishfree** [comment]
@reckart Thank you! UIMA CAS is still not widely adopted by many systems. :(

**Comment by reckart** [comment]
Python is widely adopted. You can use [dkpro cassis](https://github.com/dkpro/dkpro-cassis) to load the CAS files and transform implement Python code to transform and write the data out in whatever way you like.
