### ISSUE TITLE
KeyBindings on document annotation task

### ISSUE THREAD

**Issue by PotOfJam** [inception-project/inception#4758]
**Is your feature request related to a problem? Please describe.**
I'm conducting a document classification annotation campaign where documents are annotated with n classes. My annotators, who are doctors, have limited time to allocate to my campaign. Therefore, I need to optimize the time it takes to annotate a document. While there is an existing keybindings function for annotation, it only works on spans. I would like keybindings for labels that function in document classification tasks.

**Describe the solution you'd like**
I would like to be able to utilize the current label key bindings system for document annotation tasks. Currently, the keybindings are unresponsive in this context.

**Describe alternatives you've considered**
I considered transforming my annotation campaign to use spans so that my users could utilize key bindings. However, this approach is cumbersome and likely to cause confusion, so I abandoned the idea.

**Additional context**
![Capture d’écran (5)](https://github.com/inception-project/inception/assets/116809610/0a81d3be-fd7c-47c7-a831-3512897f9754)

**Comment by reckart** [comment]
Can you please please test if this works for you in INCEpTION 32.0 or higher? I have just tried this using 33.0-SNAPSHOT and here, the key bindings were recognized by the document-level annotation.

**Comment by PotOfJam** [comment]
I tried in INCEPTION 31.4 and 32.0.

In 31.4 key bindings aren't working in document annotation (i tried every type of combo i could think of).
In 32.0 key bindings in document annotation works except mono numerical ones (example : 1 doesn't work but CRTL 1 does).

Thanks a lot ^^

**Comment by reckart** [comment]
I have tried binding `1` and `SHIFT 1` to two different values on a document-level annotation and could use both bindings to switch between the values. Could there be any other special circumstance that needs to be involved?

Mind that key bindings will not work at all if the focus is on an input field.
