### ISSUE TITLE
Cannot export CAS RDF

### ISSUE THREAD

**Issue by tpluscode** [inception-project/inception#4769]
**Describe the bug**

I've just tried the new export format for the first time. I had an existing document with some annotations

**To Reproduce**
1. Go to a document
2. Export as CAS RDF
      `Export failed: IllegalArgumentException: Not a valid (absolute) IRI: test/YOUNGMAN City New Liner Bus.pdf#1`

**Expected behavior**

I could not determine where that relative IRI is coming from. Does the export need a base IRI?

**Please complete the following information:**
 - Version and build ID: 32.0 (2024-04-16 21:51:23, build c79f9936)

**Additional context**

Here's an export of that project: 
[test17103255409251902022.zip](https://github.com/inception-project/inception/files/15141939/test17103255409251902022.zip)

**Comment by reckart** [comment]
The writer code doesn't add a scheme to the URI - that is why it fails.
