### ISSUE TITLE
BOM not removed when importing plain text files

### ISSUE THREAD

**Issue by azankl** [inception-project/inception#4791]
I exported a text file from Inception in BioC Format. When I examine the file in VSCode, there is an unknown character, marked with a question mark, at the beginning of the first `text` element:

<img width="786" alt="Screenshot 2024-05-05 at 3 16 40 PM" src="https://github.com/inception-project/inception/assets/4812335/3d2a5947-d272-445f-85ad-8b8068045878">

This character is not visible in Inception:

<img width="997" alt="Screenshot 2024-05-05 at 3 15 11 PM" src="https://github.com/inception-project/inception/assets/4812335/065cfeb0-8eee-4901-b4cb-5ebbb220a26a">

Is this a bug?

The BioC file is here:
[PMID23125460_3.xml.zip](https://github.com/inception-project/inception/files/15211841/PMID23125460_3.xml.zip)

Thanks!
Andreas

**Please complete the following information:**
 - Version and build ID: INCEpTION -- 32.1 (2024-04-30 22:21:12, build c22cbf2f)
 - OS: macOS 14.4.1 (23E224)
 - Browser: Safari 17.4.1

**Comment by reckart** [comment]
Please go do the project settings, locate the file in the documents panel and export it from there. Then check if the text file comes with this extra character.

**Comment by azankl** [comment]
I exported the text file and the extra character is not in the txt file:
[PMID23125460_3.txt.zip](https://github.com/inception-project/inception/files/15214941/PMID23125460_3.txt.zip)
I then opened that file in the Inception Annotator and immediately exported it as BioC without making any annotations.
And the character is there:
[PMID23125460_3.xml.zip](https://github.com/inception-project/inception/files/15214943/PMID23125460_3.xml.zip)

**Comment by reckart** [comment]
It is called a "byte order mark" and is also part of the text file. 

<img width="553" alt="Screenshot 2024-05-06 at 07 49 13" src="https://github.com/inception-project/inception/assets/1410238/cdc7c209-19a2-40ea-bfb2-f9fc5c7289ee">

INCEpTION needs to be changed to filter that out.

**Comment by reckart** [comment]
@reckart Did you import the text file via a file upload to the documents panel or e.g. from the PubMed search?

**Comment by azankl** [comment]
via a file upload. As we are only annotating the patient description, my student Lisanne copy/pastes the patient description from the full text article into a text file which I then upload. @lisannesw can you please describe how exactly you create the text file? Do you copy the clinical description from PDFs or full text articles in the web browser? Which app do you copy them in to create the text files?

**Comment by lisannesw** [comment]
@azankl I copy the patient description from full text article in web browser (google chrome version 124.0.6367.119) and copy them to the standard notepad on my windows computer (Windows Notepad 11.2402.22.0), and it automatically saves it as .txt
