### ISSUE TITLE
Ability to filter entity candidates via typing

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#48]
After a user marks an entity, he gets a ranked list of candidates. 
He should be able to browse the Instance Selector in the AnnotationDetailEditorPanel (ConceptFeatureEditor) by typing. 
Kendo Combo Box could be useful for this task.

**Comment by reckart** [comment]
@rcffc merged #49 - does it fully resolve this issue?

**Comment by rcffc** [comment]
Yes
