### ISSUE TITLE
Error when opening annotation page as annotator in dynamic workflow mode

### ISSUE THREAD

**Issue by PotOfJam** [inception-project/inception#4819]
### Describe the bug

I let my INCEpTION server run for several weeks, and now my users (non-admin) can't do anything on the web app. Whenever they try to annotate or log in, they get an Internal Server Error 500.

### To Reproduce

**Fair warning:** I don't know how the bug appeared, but here are the steps to reproduce it now.

**Steps to reproduce the behavior:**

1. Launch the app using: `java -Djava.awt.headless=true -jar inception-app-webapp-32.0-standalone.jar`
2. Go to `localhost:8080`
3. Log in with a non-admin account (for an unknown reason, the bug never seems to occur with admin accounts).
4. Sometimes (about half the time), the login is successful. When you try to click on annotation, the bug occurs (100% of the time).
5. See the error.

### Expected behavior

You should be able to login with non-admin account and the application should not throw 500 Internal server error.

### Screenshots

![INCEpTION - Error](https://github.com/inception-project/inception/assets/116809610/8055e4a5-ede4-448a-ba68-ee828cdb2112)
[bug_application.log](https://github.com/inception-project/inception/files/15399113/bug_application.log)

### Environment

Version and build ID: **32.0 (2024-04-16 21:51:23, build c79f9936)**
Operating system: Linux 4.18.0-513.24.1.el8_9.x86_64 amd64
Browser: Firefox Version 125.0.3 (64bit)
Java : Oracle Corporation 21.0.2

### Additional context

I added the log file in the sceenshot area

**Comment by reckart** [comment]
Looks like there might be a bug in the dynamic workflow mode. I'll investigate.

Meanwhile, if it is viable for you, switch the project into the static workload mode, then you should be able to continue working.

**Comment by reckart** [comment]
Even in dynamic workload mode, managers can switch freely between documents - that is probably why you do not see the issue when logging in with a manager account.

**Comment by reckart** [comment]
Due to the endless loop error I can see in the log, the system might currently be in an unstable state.
So please restart the system after switching the project to static workload mode just to be sure the system is again in a clean state. Note, normally you do not need to restart the system when you change project settings.

**Comment by PotOfJam** [comment]
it does seems to resolve the bug, is there a way to have static workload and give documents to the users without them needing to select which one they want to work on ?

for this page not to show when my users start to annotate : 
![Screenshot 2024-05-22 at 10-33-03 INCEpTION - Annotation](https://github.com/inception-project/inception/assets/116809610/086966a2-2a0f-425b-8af7-8452e8ba8032)

**Comment by reckart** [comment]
No, auto-selection of documents is reserved to the dynamic mode. The next bug-fix release is tentatively scheduled for next Tuesday - I hope I can fix the issue by then.

**Comment by reckart** [comment]
You can use the filter icons on the top-right (circle and play) to filter specifically for new/in-progress documents. Or you can click on the state column header to sort by that. Maybe those functionalities can help you while the bug still exists.
