### ISSUE TITLE
Option to show relation arcs only when span is selected

### ISSUE THREAD

**Issue by lfcc1** [inception-project/inception#4826]
**Is your feature request related to a problem? Please describe.**
The annotations I have are very dense, resulting in numerous relation arcs across the text, which makes it difficult to see the text clearly. To make the annotation process easier, I decided to hide the arcs. However, this is not optimal because I would still like to see the relation information.
**Describe the solution you'd like**
I would like the arcs to be hidden by default and only shown when I select a specific span (only show the arcs related to that span).

**Comment by reckart** [comment]
Which editor are you using? Default brat?

**Comment by lfcc1** [comment]
brat (line-oriented)

**Comment by reckart** [comment]
Hiding relations in that annotator would mean that either there'd be a lot of empty space between the lines when they are hidden or that the layout would change *a lot* when selecting an annotation. Do you really think it would improve the experience?

**Comment by lfcc1** [comment]
When we have the arcs displayed on the editor, the text is barely visible (see both images).
![Captura de ecrã 2024-05-24 134342](https://github.com/inception-project/inception/assets/36732127/d4f3e49e-5f72-4494-b224-de05906f5e86)

However, when hiding the relations, the text comes together. Our annotation team has requested that we hide the relations. They prefer to annotate the text without the arcs.
![Captura de ecrã 2024-05-24 134327](https://github.com/inception-project/inception/assets/36732127/54ec6ae9-4992-41d1-aa9b-74031db1cf45)


Our proposal is for the system to be reactive, reconstructing the layout upon span selection, and showing only the arcs related to the annotation span selected. This way, we could have the best of both worlds.

**Comment by reckart** [comment]
So let's think about this a bit more.

Rule 1: We render a relation only when a span is selected to which is either the start or the end of a relation. So far so good.

Now, what do you expect to happen when the user selects a relation? Should then only this individual relation be rendered? 

Note that only one annotation can be selected at a time, so when the user selects a relation, the selection will be removed from the span, meaning that Rule 1 no longer applies.

**Comment by reckart** [comment]
I've added an option to render arcs only "when selected". It renders relation arcs attached to a selected span or when a relation is selected, it renders only the arc for that individual relation. It is a per-layer setting replacing the "render arcs" boolean setting which is now a drop-down "Render mode" that can be set to always, when selected or never.

<img width="553" alt="Screenshot 2024-05-25 at 14 31 11" src="https://github.com/inception-project/inception/assets/1410238/7f455e66-c971-493e-b140-5a573637d9a9">
<img width="640" alt="Screenshot 2024-05-25 at 14 31 05" src="https://github.com/inception-project/inception/assets/1410238/52fbcc52-f89a-4cb4-8305-511ec24cd9f6">
<img width="522" alt="Screenshot 2024-05-25 at 14 30 58" src="https://github.com/inception-project/inception/assets/1410238/0ab86265-073a-4e8b-9a3c-f099dc0eb331">

**Comment by reckart** [comment]
@lfcc1 You could get getting the lateat JAR build from here and try it out locally: https://build.ukp.informatik.tu-darmstadt.de/job/inception-main/

**Comment by lfcc1** [comment]
Hey,
I have pulled from the last docker image, but I'm not able to see the "Render mode" option on the layer detail settings.

**Comment by reckart** [comment]
@lfcc1 which version did you pull?

**Comment by lfcc1** [comment]
32.3

**Comment by reckart** [comment]
The feature is currently available on the 33.0-beta-3 release. https://github.com/inception-project/inception/pkgs/container/inception-snapshots

If all goes well, there will be a 33.0 final release tonight.

**Comment by lfcc1** [comment]
ok,
