### ISSUE TITLE
Concept features - Choose scope via a concept tree or auto-complete field

### ISSUE THREAD

**Issue by naveen2507** [inception-project/inception#483]
**Is your feature request related to a problem? Please describe.**
 Choose scope via a concept tree or auto-complete field . Follow Up issue for #124 

**Describe the solution you'd like**
Provide the user with a concept tree to choose the concept for the feature in the layer configuration

**Comment by reckart** [comment]
Looks like we have this since https://github.com/inception-project/inception/issues/1368

See: https://github.com/inception-project/inception/blame/85e7c85d99e3214d0772f15b6887f4e258f5f514/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureTraitsEditor.java#L104
