### ISSUE TITLE
Unable to use UKP Wikidata anymore

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#486]
**Describe the bug**
When the UKP Wikidata SPARQL server is used, we no longer get any annotations rendered nor does the KB page display anything.

**To Reproduce**
1. Create a new project and add the UKP Wikidata server to it (make sure "support concept linking" is on, otherwise it wouldn't be surprising if nothing worked)
2. Try opening the annotatation page
3. Try opening the KB page

**Expected behavior**
Should work "normally".

**Please complete the following information:**
 - Version and build ID: 0.5.0-SNAPSHOT (2018-08-23 00:10:24, build 61b243e62f430d2d94045451c568192e4a73bd37)

**Comment by reckart** [comment]
@naveen2507 @rcffc @MdeBoer95 any idea which of the recent changes might have broken this and why our unit tests didn't catch it?

**Comment by naveen2507** [comment]
@reckart I can access the KB with master branch on my local 

![image](https://user-images.githubusercontent.com/10420950/44530002-bc374980-a6ed-11e8-8469-d44a58d1e681.png)

**Comment by rcffc** [comment]
I can also access the UKP_WIKIDATA KB page on master.
I do not know which changes could have caused it, before 14.8. it worked fine and after that I was away for a week.

**Comment by reckart** [comment]
@naveen2507 can you also access the annotation page, in particular when annotations linked to the KB are present?

**Comment by naveen2507** [comment]
> @naveen2507 can you also access the annotation page, in particular when annotations linked to the KB are present?

@reckart Yeah. 

![image](https://user-images.githubusercontent.com/10420950/44569860-06670c00-a77c-11e8-8078-070ded9f3f6e.png)

**Comment by reckart** [comment]
@naveen2507 What is the commit hash that you are testing (make sure you don't have local modifications when reporting).

**Comment by naveen2507** [comment]
@reckart :
Technische Universität Darmstadt -- Computer Science Department -- INCEpTION 𝜶 -- 0.5.0-SNAPSHOT (2018-08-24 10:36:37, build dcaae0450228b73fedf91794394f9faae7b68754)

**Comment by reckart** [comment]
@naveen2507 note that according to GitHub, the commit dcaae0450228b73fedf91794394f9faae7b68754 is only on the branch feature/50-statement-editor-with-validation, not on the master branch.

**Comment by reckart** [comment]
@rcffc @naveen2507 @betoboullosa  I have tried again on blinky/experimental yesterday (f88ff040e5a65030f6e952c20cc95ace58feb81a). The KB page seems to work (again). However, the annotation page stalls. I believe this has nothing to do with the KB directly, but rather with the fact that when a document is opened for annotation, it is updated internally which causes it to be re-indexed. This can be a very slow process if there are many entities that need to be resolved from a remote KB and unfortunately, presently it is a synchronous process. However, #462 is about to address this.

**Comment by reckart** [comment]
This has been addressed by #462.
