### ISSUE TITLE
The latest 33.x docker-compose cannot run up

### ISSUE THREAD

**Issue by fishfree** [inception-project/inception#4879]
Following [this](https://inception-project.github.io/releases/33.0/docs/admin-guide.html#sect_docker_compose), after running `docker-compose -p inception up -d` , it stuck on:

```
……
   ⠿ 9442f290c438 Pull complete                                                                                   273.2s
[+] Running 2/3
 ⠿ Network inception_inception-net  Created                                                                         0.1s                        0.1s        Waiting                                                                      4385.8s
[+] Running 2/3ception-db-1         Waiting                                                                         0.1s ⠿ Network inception_inception-net  Created                                                                         0.1s  
 ⠿ Container inception-db-1         Waiting                                                                     16790.3s   ⠿ Container inception-app-1        Created                                                                         0.1s 
```

What's the problem?

**Comment by reckart** [comment]
Please check the log of the containers - in particular the containers that hang.

**Comment by fishfree** [comment]
@reckart But you cannot check logs of a `waiting `container. :-(

**Comment by reckart** [comment]
The output you posted seems garbled. Which containers are actually waiting?

What happens if you try do `docker run` the respective images?

**Comment by reckart** [comment]
Is this a first-time run or did you run INCEpTION via docker compose on that system before?

**Comment by reckart** [comment]
I have just tried the docker-compose file from the manual again locally. For me, it works.

**Comment by fishfree** [comment]
@reckart My fault, my db-data folder is not empty :-(
