### ISSUE TITLE
Where to configure the cookie-session time?

### ISSUE THREAD

**Issue by fishfree** [inception-project/inception#4887]
It seems the use will be forced to log out without activity for 20 minutes. Where to configure this? I found nowhere in the settings.properties file.

**Comment by reckart** [comment]
Should be [`server.servlet.session.timeout=15m`](https://www.baeldung.com/spring-security-session#2-configure-the-session-timeout-with-spring-boot)

**Comment by fishfree** [comment]
@reckart Many thanks!
