### ISSUE TITLE
Incorrect repetitions of sentences

### ISSUE THREAD

**Issue by s2fische** [inception-project/inception#4935]
INCEpTION displays several lines/sentences (12, 81, 201, 205, 206, 219-227, 233, 235) of a specific document incorrectly: The text appears twice, once without line breaks (thus leaving the frame) and once with them. Only the first occurrence can be annotated; when trying to highlight text in the second one, the annotations automatically jump back to the first occurrence. In line 222, the text even repeats itself three times.

<img width="557" alt="Screenshot 2024-07-08 174613" src="https://github.com/inception-project/inception/assets/170112224/4ce1d9f7-bd17-408d-afdb-9c7ad13de439">

<img width="551" alt="Screenshot 2024-07-09 121634" src="https://github.com/inception-project/inception/assets/170112224/de5f240a-66dd-41d4-b779-0a5ab60c9224">

The lines are not doubled in the original .txt-file: 
[Auerbach_Der_Kindesmord.txt](https://github.com/user-attachments/files/16141899/Auerbach_Der_Kindesmord.txt)

**Please complete the following information:**
 - Version and build ID: INCEpTION -- 33.1 (2024-06-25 09:45:14, build 26410d34)
 - OS: Windows 11
 - Browser: Chrome

**Comment by s2fische** [comment]
Same thing happened in another document, so it's probably not related to the specific file (see the repetition of "Ein Wiedersehen"):

<img width="472" alt="Screenshot 2024-07-09 175303" src="https://github.com/inception-project/inception/assets/170112224/71a879c9-000a-4f89-a7b9-70b27291b05c">

**Comment by reckart** [comment]
Indeed an interesting problem. Thanks for reporting. It seems to appear mainly for the sentence-oriented mode. Switching to the line-oriented mode, the problem disappears for me. Also, it does not happen when I configure to show only a single row and then switch e.g. to row 12. As soon as I configure the editor to render two rows, it starts happening though.

**Comment by reckart** [comment]
The problem seems to be on the backend side as some odd token offsets are sent to the client, e.g `[39,40],[0,40],[40,272],[42,47],[48,51]` - normally these should be non-overlapping and in increasing order.
