### ISSUE TITLE
OAuth and SAML logins do not work if a servlet path is used

### ISSUE THREAD

**Issue by kzgrzendek** [inception-project/inception#4940]
### Describe the bug

Hello, 

First, I'd like to thank you for the awesome work you're providing the community with! This is my first issue on that project, so don't hesitate to tell me if I'm not posting it correctly.

I'm currently trying to enable OAuth2 login on an INCEpTION deployed with a custom servlet context set with the `server.servlet.context-path=/inception` parameter, according to the documentation.

It seems that although the application is indeed deployed on `https://my-hostname/inception` as intended, when I click on the OIDC login button, the application is redirecting me to `https://my-hostname/oauth2/authorization/{client-id}` instead of `https://my-hostname/inception/oauth2/authorization/{client-id}`, hence returning me a 404, since nothing is listening for that URL.

Now, I tried to go in-depht in Spring Security configuration's options, and it doesn't looks like  I can add a configuration option to fix that, but maybe I'm missing something.

I cannot do shenanigans with my reverse-proxy neither, like playing with URL rewrites of `/`, or `/oauth`, because other services on the same hostname needs those URLs (besides, I think that issue should be fixed on the application's end).

I can make OIDC work without issues if I stick to a deployment on the root URL (`/`), so I dont think I'm having any other configuration issues here.

Thanks for your support and don't hesitate if you have further questions!

### To Reproduce

1. Configure the `server.servlet.context-path` to `/inception` in the `settings.properties` file
2. Set-up a working OAuth2 configuration in the `settings.properties` file
3. Try to connect using your OIDC client by clicking on the icon (`Keycloak`, in this example)
    ![image](https://github.com/user-attachments/assets/9f2c5519-ee8e-438a-b407-549ba5d35da1)
4. Notice that the URL you're redirect to by clicking doesn't contain the servlet context path sat in the first step

### Expected behavior

The redirection URL should contain a custom servlet context path if one have been set : 

http(s)://my-hostname/{custom-servlet-context-path}/oauth2/...

### Environment

- INCEpTION version  33.2 (2024-07-09 22:18:36, build 893606ca)
- Tested with Brave and Firefox browsers
- Deployed as a container inside a K8S Pod 
  - Settings mounted as a ConfigMap
  - Ingress NGINX (vanilla community version, no weird configurations or URL rewrite)

**Comment by reckart** [comment]
Thanks for reporting the issue. I can reproduce it and I think I have a fix as well.

**Comment by kzgrzendek** [comment]
That's perfect! Let me know if I can help in any way. Thank you

**Comment by reckart** [comment]
If you want, you can build the `release/33.x` branch and test.

**Comment by kzgrzendek** [comment]
@reckart I can confirm it works like a charm in the 33.3 release. Thanks!
