### ISSUE TITLE
INCEpTION image at docker hub

### ISSUE THREAD

**Issue by vipulg13** [inception-project/inception#4952]
Dear team,

are there any plans to make INCEpTION image available at docker hub? I can only mirror images from docker hub or redhat registry into our local repository, to be used in our Kubernetes environment. If not, then I will need to perform a custom build using the base image eclipse-temurin:17.

**Comment by reckart** [comment]
INCEpTION stopped publishing images to DockerHub when DockerHub did announce to change their conditions for open source projects, phase out free DockerHub organizations.

I believe they meanwhile have reverted their position - but INCEpTION had already moved to using the GitHub registry, so I didn't follow the developments closely.

You can find the Dockerfile used by INCEpTION and the Docker build instructions here: https://github.com/inception-project/inception/tree/main/inception/inception-docker

**Comment by reckart** [comment]
Is there a specific reason why you allow mirroring from DockerHub but not from our [GitHub registry](https://github.com/inception-project/inception/pkgs/container/inception)?

**Comment by vipulg13** [comment]
> Is there a specific reason why you allow mirroring from DockerHub but not from our [GitHub registry](https://github.com/inception-project/inception/pkgs/container/inception)?

I am informed that only official RedHat registry and DockerHub registry are supported at the moment. I will ask the principle system administrator for the reason behind not supporting GitHub registry.

**Comment by vipulg13** [comment]
As far as I understood from the e-mail correspondence, the admin team doesn't support mirroring process from GitHub registry due to security reasons. I didn't fully comprehend the reason and still in discussion with them, because irrespective of the registries, the presence of a malicious program in the application codebase will anyway be inherited.

**Comment by reckart** [comment]
>  I didn't fully comprehend the reason and still in discussion with them, because irrespective of the registries, the presence of a malicious program in the application codebase will anyway be inherited.

Exactly. IMHO it does not make a difference if I push the image to GitHub or DockerHub - in both cases, it is the same image.

**Comment by vipulg13** [comment]
@reckart the issue is resolved. Our IT-team now supports a github registry as well. I close this issue and leave now at your discretion, whether you want to publish images at docker hub or not.
