### ISSUE TITLE
API UIMA CAS export incomplete

### ISSUE THREAD

**Issue by tpluscode** [inception-project/inception#4966]
**Describe the bug**

When I export annotations from the browser, I get all the annotations. When I use the API, all the `<uima:webanno.custom.*>` are missing

**To Reproduce**
1. Create some annotations in a document
2. Enable API access and create a user with API role
3. Fetch from `/api/aero/v1/projects/${PROJECT_ID}/documents/${documentId}?format=rdfcas`
4. Find no layer data

**Expected behavior**
The RDF contents should be exactly the same when exported from the app and from the api

**Please complete the following information:**
 - Version and build ID: 33.1 (2024-06-25 09:45:14, build 26410d34)

**Additional context**
Same issue when exporting to UIMA CAS JSON

**Comment by reckart** [comment]
You have to use the annotation endpoint: https://openminted.github.io/releases/aero-spec/1.0.0/omtd-aero/#_read_annotations

**Comment by tpluscode** [comment]
Thanks. That did cross my mind to try but the mandatory annotator I'd is a nuisance. Can I find the annotator of any given document using the API? Also, there can be only one annotator per document, right?

**Comment by reckart** [comment]
As manager, you upload a document which becomes the **source document**. When an annotator opens that for annotation, it is copied and henceforth the annotators is working on their private copy which is called the **annotation document**. There can be many **annotation documents** for each **source document**.

**Comment by reckart** [comment]
You can use the list endpoint to see who annotated which documents: https://openminted.github.io/releases/aero-spec/1.0.0/omtd-aero/#_list_annotations

**Comment by tpluscode** [comment]
Thank you for the explanation. Now I got it to work
