### ISSUE TITLE
Can't change pages correctly

### ISSUE THREAD

**Issue by Madness75** [inception-project/inception#4969]
**Describe the bug**
When I try to annotate a .txt file document, I can't go to the next page because it doesn't show it.
For example: when I'm on lines 1-10 and I want to go to lines 11-20 by clicking on the "next page" button, it keeps showing lines 1-10, and if I click again, it will directly go to lines 21-30.

**To Reproduce**
1. Go to 'Projects Tab'
2. Click on 'The Project'
3. Click on 'Annotation'
4. Click on the text document
5. Click on next page button
6. See error

**Expected behavior**
The next page of the document shloud appear but instead it's dont show it and if i continue to click on it will go to the next one 

**Screenshots**
https://github.com/user-attachments/assets/b0a3614c-2fa5-4147-a303-670df63186fc

[bordeaux_extraits_V1_163.txt (one of the documents that doesn't work)](https://github.com/user-attachments/files/16425660/bordeaux_extraits_V1_163.txt)

**Please complete the following information:**
 - Version and build ID: INCEpTION -- 33.0 (2024-06-11 20:43:31, build 8865ebbd)
 - OS: Windows 11
 - Browser: Chrome

**Additional context**
- I tried on different browser Edge and Firefox but i does the same 
- I'm not sure of that but i don't had the problem before importing the same project in INCEpTION

**Comment by reckart** [comment]
Thanks for the report. I have imported the file a into my current development version and that seems to render ok.

Could you please upgrade to 33.3 and check if the problem persists for you?

**Comment by Madness75** [comment]
Ok, it works better with this version, thanks!

**Comment by reckart** [comment]
Let me know if you hit the problem again,
