### ISSUE TITLE
random duplicated sentences

### ISSUE THREAD

**Issue by chlor** [inception-project/inception#4972]
**Describe the bug**

We have some documents in clinical setup with randomly lines, they repeat the content of the line.
I you click in the second part an want to annotate a span, the annotation jumps to the first part.
Recommender is configured.

**To Reproduce**
Sorry. I have no idea.

**Expected behavior**
--

**Screenshots**
is attached.

**Please complete the following information:**
 - Version and build ID: 33.2
 - OS: Windows
 - Browser: Edge

**Additional context**
We downloaded the CAS XMI exported of 1 document and checked the file. It was ok, we think, it depends on the display.

![fehler_zeile](https://github.com/user-attachments/assets/b6ab8276-421a-42d1-b2fc-99bcd62b6554)

**Comment by chlor** [comment]
Note beside: The PHI annotation in the picture is set by us as a example, but it is not derived from the recommender system.

**Comment by reckart** [comment]
This was probably fixed in https://github.com/inception-project/inception/issues/4935

Please try upgrading to v33.3.

If the issue persists with 33.3, please let me know.

**Comment by chlor** [comment]
Thanks!! I was not sure and have not found an mail, etc. thanks a lot!! ;-)
