### ISSUE TITLE
Statement Editor with Validation

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#50]
**General**
- [x] Spring registry component for all the value supports: `ValueTypeSupportRegistry`
- [x] dropdown field where the type of value can be chosen; depending on the chosen type, the editing fields change

**Literal value supports**
- [x] choice should be restricted by range of the respective property if the property defines a range (we may assume for the moment that a property has at most one range)
- [x] **string literals**: value field, language field
- [x] **boolean literals**: checkbox field

**Non-literal value support**
- [x] **resource**: auto-complete field where the user can type the name of a class or instance or even directly an IRI in case the target is actually *not* in the KB
- [x] when the resource is not in editing mode but in display mode, the resource should be shown by its label (i.e. `KBHandle.getUiLabel()`) and it should be clickable. Clicking on it should open the respective class or instance (maybe even property) in the KB page.
- [x] choice should be restricted by range of the respective property if the property defines a range (we may assume for the moment that a property has at most one range)
- [x] when adding statements - drop down choices for properties should be restricted to range (currently it throws exception otherwise)

Cases to consider:

* statement has a value -> show editor for that value (even if the respective property range would not allow it normally)
* statement has no value but there is a property with a range -> show editor matching the range
* statement has no value and there is no range -> show dropdown from which the user can choose an data type and depending on that the respective editor is shown
  * sub-case: user switches from one data type to another using the dropdown
* property has more than one range -> this probably cannot happen for literals; for resources it would require that we do quite complex inference, so we should probably assume that there is at most one range. However, consider subtypes.

**Adding statements for new properties**
* [x] which properties can be chosen for a given instance should respect the "domain" of the respective properties

**Comment by naveen2507** [comment]
Some issue from the merge :

1.  `StatementEditor.java` code : ` WebMarkupContainer presenter = valueTypeRegistry
                    .getValueSupport(aStatement.getObject(), property.getObject())
                    .createPresenter("value", model, property);` breaks KB and clicking on any concept fives Internal Error. (Fixed)

2.  After creating a new project, it doesn't show properties in KB UI panel.  (Debugging currently)

**Comment by naveen2507** [comment]
@reckart In `ValueTypeSupportRegistryImpl.getValueSupport()` , it calls `s.accepts(aStatement, aProperty)`  where it checks `aStatement.getValue()` .

 Now in case we get a aStatement as `de.tudarmstadt.ukp.inception.kb.graph.KBStatement@750d455f[instance=KBHandle[identifier=http://www.w3.org/TR/2003/PR-owl-guide-20031209/wine#WineColor,name=WineColor],property=KBHandle[identifier=http://www.w3.org/TR/2003/PR-owl-guide-20031209/wine#hasColor,name=hasColor],value=<null>,language=<null>,inferred=false,originalStatements=[]]` , here the value is null. What exactly would this accept function ideally check?

**Comment by reckart** [comment]
The method would check:

* does the statement have a value? if yes return true if the ValueTypeSupport supports this value (e.g. if the value is a String, then StringLiteralValueTypeSupport returns true)
* does the property have a range? if yes return true if the ValueTypeSupport supports this range type (e.g. if the value is a String, then StringLiteralValueTypeSupport returns true)
* neither of the above: return false

**Comment by MdeBoer95** [comment]
@reckart @naveen2507 
I want to use IRIs as model object for the autocomplete field 
https://github.com/inception-project/inception/blob/95f5f0a254ccd93a66fb1f049dd18b419f8f183e/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/value/editor/IRIValueEditor.java#L54-L66
How can I implement a custom renderer for this that does not use a property of the class but instead implements something that extracts the concept name from the IRI (e.g with substring(...).
So that the user can just type a short name instead of the whole IRI.

**Comment by naveen2507** [comment]
@MdeBoer95 If i understand correctly, does getUiLabel doesn't help in this case?

**Comment by reckart** [comment]
Check what the ConceptFeatureEditor does.

**Comment by naveen2507** [comment]
@reckart In case of auto-complete field where the user can type the name of a class or instance or even directly an IRI in case the target is actually not in the KB. As we want to restrict the auto-complete fields with the range of values, wouldn't it be a good idea to just show the drop down list. But in case we follow the drop down approach, what if the property doesn't explicitly mark a range for itself

**Comment by reckart** [comment]
It should be possible for the user to enter an IRI directly. The `KendoAutoCompleteTextFeatureEditor` showcases how the auto-complete field can be used in a way that it is not limited to the things that appear in the dropdown but also accepts any value in the input field.

**Comment by reckart** [comment]
I think to avoid problems with typos, we would need to have two different value editors: one that is limited to things that exist in the KB and one that allows entering and IRI
