### ISSUE TITLE
The exported CoNLL-files contain no annotations

### ISSUE THREAD

**Issue by thetaaaaa** [inception-project/inception#5063]
**Describe the bug**
The exported CoNLL-files contain no annotations

**To Reproduce**
1. Set custom Tagsets, and bind it to the default Span Layer.
2. Start annotating.
3. Export annotated data in CoNLL2002 format. 
4. The  exported annotated data in CoNLL2002 format contain no valid annotations, they are all in 'O'.

**Expected behavior**
The  exported annotated data in CoNLL2002 format should contain annotations in "BIO" format.

**Screenshots**
The screenshots of annotated text:
![image](https://github.com/user-attachments/assets/181693c7-b0e7-437a-9cf3-3f097908b5ac)
The screenshots of  exported annotated text in CoNLL2002 format:
![image](https://github.com/user-attachments/assets/dd12997b-1f03-42d0-b1f6-c372e9de2726)
The setting of Span Layer:
![image](https://github.com/user-attachments/assets/078d667a-9772-4919-af2b-d0b5e0ab2c74)

**Please complete the following information:**
 - Version and build ID: INCEpTION -- 33.7 (2024-09-18 21:04:21, build c156ca28)
 - OS: Windows
 - Browser: Edge

**Additional context**
There is also no valid annotation shown on the annotating page when I upload a ConLL2002 file to Inception.
The srceenshot of raw data in CoNLL 2002 format:
![image](https://github.com/user-attachments/assets/5a1bcfe5-89bf-4d90-a220-2f9e8762cf98)
The srceenshot of raw data in CoNLL 2002 format shown in annotating page:
![image](https://github.com/user-attachments/assets/f97eb9b9-f068-48eb-aef0-dca9cfe82591)

**Comment by reckart** [comment]
Please check the documentation to see which layers are supported by which formats, e.g. https://inception-project.github.io/releases/33.7/docs/user-guide.html#sect_formats_conll2000

The "Span" layer is not listed for any of the CoNLL formats. Basically, it counts as a "Custom" layer.

I understand that with the inclusion of layers like "Span" and "Relation", the distinction between what is considered as a "built-in" layer like "POS", "Dependency" etc. and a "custom" layer is blurred because "Span" does in fact come with the first project template that can be selected. The documentation needs updating on this point.

Thanks for brining this up... I'll have to think about if/how this can be addressed.

**Comment by thetaaaaa** [comment]
Thank you for your quick reply. But, please forgive my clumsiness......I checked your link, and I think I can not understand what does the table mean for the "Custom Layers: No" part.
The srceenshot of the description of CoNLL2002 format:
![image](https://github.com/user-attachments/assets/31ace20e-9dcf-419c-902f-789891e3ce8e)
I create a new Layer and named it as "NER", and annotate it with my own tags. But I still get nothing of my annotataion in CoNLL-X format.
The srceenshot of annotating page, and you can see I am annotating it with my custom layer "NER":
![image](https://github.com/user-attachments/assets/2fcc8ebc-1ba0-467a-b147-bf6a3973d606)
The srceenshot of exported annotated result in CoNLL 2002 format:
![image](https://github.com/user-attachments/assets/f07aca47-9533-4de0-8652-ce0407f38e4f)
My point is that it seems that the dafault layer "Span" and my Custom Layer "NER"(If my understanding of Custom Layer is correct) both can not export valid CoNLL 2002 result. Can you instruct me how to adjust my setting so I can export data in CoNLL 2002 format ?

**Comment by thetaaaaa** [comment]
I finally understand how to solve the problem in the latest version now ! I need to manully add the pre-defined "Named entity" Layer by clicking the button "Add" at the page of Layer setting and add one of "Named entity Tagging” or "Named entity Linking”, and then bind my custom tagsets to the pre-defined "Named entity" Layer. After that, everything will work as expected. I agree that the User Documentation need to make this point clear.
The screenshot shows the way to add pre-defined "Named entity" for others reference:
![image](https://github.com/user-attachments/assets/a4cabfa4-f6e7-4da6-9779-8170179f4214)

**Comment by reckart** [comment]
Thanks for sharing your solution. It is also what I would have suggested to you.

There is also a second option, namely that you create your project from the **Entity annotation** template.

<img width="1359" alt="Screenshot 2024-09-25 at 20 02 05" src="https://github.com/user-attachments/assets/7b926aa3-6df6-4999-9841-6078416f0af2">

I think it might be an option to introduce a CoNLL-like BIO export option for projects containing only a single span-type layer or to change the CoNLL 2002 exporter such that if a project does not contain the **Named Entity** layer but a single other span layer, that it would then export that...

**Comment by reckart** [comment]
I have tried making the information which format supports which layer better accessible in the documentation.

https://github.com/inception-project/inception/pull/5072/files
