### ISSUE TITLE
Presence of deprecated RDF4J SYSTEM repository may cause trouble

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#508]
**Describe the bug**
If the deprecated RDF4J `SYSTEM` repository is still present on disk, it may prevent the creation of new KBs. This certainly happens when using RDF4J 2.4.0-M3 but I also just observed it on a Linux machine using RDF4J 2.3.2.

See: https://github.com/eclipse/rdf4j/issues/1077

**To Reproduce**
1. Ensure that a `SYSTEM` repository exists (can even be an empty directory)
2. Try creating a new KB
3. Observe that no KB is created after finishing the wizard

**Expected behavior**
The KB should have been created

**Please complete the following information:**
 - Version and build ID: af1c5ead9420b5e6f5d144511f5fd1fe8a135288

**Comment by reckart** [comment]
Fix actually breaks more stuff because it doesn't give RDF4J the opportunity to migrate from the `SYSTEM` repo situation to the "config.ttl per repo" situation. Need to roll back and think again.

**Comment by HansBrende** [comment]
@reckart were you able to verify if [PR 1078](https://github.com/eclipse/rdf4j/pull/1078) fixed this bug?

**Comment by reckart** [comment]
@HansBrende It seems that 
https://github.com/eclipse/rdf4j/pull/1078 fixes the issue. I tested with 2.4.0-M3 which produces the problem when the `SYSTEM` folder is present. When I switch to a08bd93b87329629e71c39140fbecabbd891129a which includes the PR, the present of the `SYSTEM` folder appear not to cause the problem anymore. Thanks!

**Comment by reckart** [comment]
@HansBrende Looking forward to an 2.4.0-M4 or 2.4.0 final release now :)
