### ISSUE TITLE
Conditional feature option for integer features should not be offered

### ISSUE THREAD

**Issue by lfcc1** [inception-project/inception#5098]
### Describe the bug

I created a span feature of type Primitive Integer. I enabled the 'Show only when constraints apply' option for this feature. However, the feature is not hidden in the annotation interface, even though no constraints are set for it. It remains visible when it should be hidden.

### To Reproduce

1.  create a span feature of type Primitive Integer.
2. Enable the 'Show only when constraints apply' option for this feature.
3. Ensure that no constraints are set for this feature.
4. Open the annotation interface and check if the feature is visible.

### Expected behavior

The feature should be hidden in the annotation interface, as no constraints apply.

### Screenshots

![image](https://github.com/user-attachments/assets/91d9d579-9826-4bc3-a0c6-60958375bc3e)

### Environment

Version and build ID: 33.0 (2024-06-11 20:43:31, build 8865ebbd)
Operating system: Linux
Browser: Edge

### Additional context

I have also noticed that if the "Limited" option is checked and saved on a "Primitive: Integer" feature, it cannot be unselected afterwards. -> https://github.com/inception-project/inception/issues/5101

**Comment by reckart** [comment]
The bug here is probably that the **Show only when constraints apply** option is available for non-string features. Constraints currently only work for string features that have tagsets.
