### ISSUE TITLE
Make SPARQL query limit configurable by user

### ISSUE THREAD

**Issue by mromanello** [inception-project/inception#513]
When querying a KB via SPARQL the number of results retrieved is limited, by default, to 1,000.

I'd like to be able to configure this limit manually via the inception configuration file and, if possible, I'd like to be able to specify that I want all results to be retrieved.

**Comment by reckart** [comment]
I think it would be best to allow configuring this on a per-KB basis.

**Comment by naveen2507** [comment]
@reckart Yeah, that's what we are doing. But the code on 0.5.x doesn't quite align with the specificity. Code on  the master has the structure set up for that.

**Comment by reckart** [comment]
For 0.5.1, add a setting to be added to the `settings.properties` file. For master, we can make it configurable on a KB-basis and use the value from the `settings.properties` file as the default value. WDYT?

**Comment by reckart** [comment]
For adding configuration settings to `settings.properties`cf. e.g. `de.tudarmstadt.ukp.inception.conceptlinking.config.EntityLinkingProperties`.
