### ISSUE TITLE
Using the own fonts in the application

### ISSUE THREAD

**Issue by enrico84** [inception-project/inception#5138]
**Describe the refactoring action**
I wanted to know if it is possible to insert fonts in the application home folder, the ".inception" folder.
I created another folder called "/fonts" inside the application home folder of the application, and I placed in it some fonts, referenced these fonts in the themes.css file using the "@font-face" property, but when I start the application I get an error of "fonts" class not found.

I didn't find anything about this in the guides, so I wanted to know if Inception has this feature, thanks.

**Expected benefit**
I would like to be able to use new fonts inside the Inception application

**Comment by reckart** [comment]
How did you inject your custom CSS files?

**Comment by reckart** [comment]
Resources like fonts or images for use in custom themes are currently not supported.

Be aware that inception may break custom themes at any time. If you build own styles you have to maintain them and adjust the when upgrading inception. You probably won't know a style is broke until your users tell you.

**Comment by enrico84** [comment]
If I want to change fonts or images only locally for testing, is it possible to do so? 

> Be aware that inception may break custom themes at any time. If you build own styles you have to maintain them and adjust the when upgrading inception. You probably won't know a style is broke until your users tell you.

What do you mean when you say "Please note that inception can break custom themes at any time."?

**Comment by reckart** [comment]
> If I want to change fonts or images only locally for testing, is it possible to do so?

You can check out the source code and make direct modifications to it including adding/changing resources.

> What do you mean when you say "Please note that inception can break custom themes at any time."?

When changes are made to the INCEpTION UI, these may introduce new styles or change existing styles. Such changes may potentially conflict with the custom styles in your theme.

**Comment by enrico84** [comment]
> When changes are made to the INCEpTION UI, these may introduce new styles or change existing styles. Such changes may potentially conflict with the custom styles in your theme.
Yes, I know it.

> You can check out the source code and make direct modifications to it including adding/changing resources.
I modified the global style of INCEpTION by adding the new fonts that I want to use, that are the .tff files, in the theme.css file and I inserted them inside the ".inception" folder. The ".inception" folder is located in a different position of my filesystem from the location of the actual INCEpTION application.
What happens when the INCEpTION application starts is that these fonts of mine are not loaded: if I'm doing something wrong (maybe the .tff files should be inserted in another position of the filesystem or in an application folder) could you give me support?
Thanks

**Comment by reckart** [comment]
INCEpTION does not come with a `theme.css` file. So what you are using seems to be the [theming](https://inception-project.github.io/releases/34.3/docs/admin-guide.html#_theming) functionality. However this functionality is limited to providing a single `theme.css` file - no other static resources.

If you want to do a custom build of INCEpTION with additional static resources, you would have to:

* check out the code from the repository
* add additional resources e.g. to the folder `inception/inception-app-webapp/src/main/resources/public`, e.g. `.../public/myfont.ttf`
* build a JAR from your locally modified code using `mvn clean install` - the JAR would end up in `inception/inception-app-webapp/target`
* your `theme.css` file should then be able to access the files under e.g. `http://localhost:8080/myfont.ttf`
