### ISSUE TITLE
Support different types of line breaks

### ISSUE THREAD

**Issue by hunnguye** [inception-project/inception#5191]
**Is your feature request related to a problem? Please describe.**
It appears CR newlines are not suported.

Inception displays following text:
![image](https://github.com/user-attachments/assets/b0e95499-ba35-4696-aeae-4e81b0c39f8d)

But when downloading the text as a txt file and opening it in notepad++ it looks like this:
![image](https://github.com/user-attachments/assets/0b4b7205-6988-4c19-b0ac-b1a419f2eca0)

**Describe the solution you'd like**
Displaying correct newlines might increase user experience and help decreasing cognitive load on annotators.

**Additional context**
Inception Version 34.3
Editor: brat (wrapping @ 120 chars)

**Comment by reckart** [comment]
Which editor mode have you configured? Did you use "brat (line-based)" or "brat (wrap at 120 chars")?

**Comment by hunnguye** [comment]
Thanks for  responding so quickly!

We are using the "brat (wrapping @ 120 chars)" Editor
