### ISSUE TITLE
User should choose a certain KB when setting up the fact layer

### ISSUE THREAD

**Issue by matchlesswei** [inception-project/inception#52]
I think actually, when user creates a new fact layer, a Knowledgebase should be chosen. So we just need to list the predicates of that layer. 

@reckart wrote:
> Good question. I think I would agree. If we allow that facts are linkable across KBs, that could make things quite complicated.

**Comment by reckart** [comment]
Let me quickly run you through how did the traits for the AnnotationFeatures:

* In the `FeatureSupport` interface, I have added three new methods: `createTraitsEditor`, `readTraits` and `writeTraits`. The `createTraitsEditor` by default returns an empty panel. The other methods also do nothing by default.
* when the use selects a specific feature type in the feature detail editor, the UI asks the `FeatureSupport` responsible for the feature type about a traits editor (`createTraitsEditor`).
* presently `ConceptFeatureSupport` returns a traits editor and also the `PrimitiveUimaFeatureSupport` for String features.
* the traits editor gets embedded as a sub-form into the `ProjectLayersPanel.FeatureDetailForm` and it gets submitted along with the user pressing the "save" button on the main form. 
*the sub-form in the `ConceptFeatureTraitsEditor` implements `onSubmit` and there it saves its data to the `AnnotationFeature` model from the main form using the `ConceptFeatureSupport.writeTraits` method.
* in the main form `ProjectLayersPanel.FeatureDetailForm`, the saving of the `AnnotationFeature` is not made in the `onSubmit`method, but rather in the `onAfterSubmit` method, so it is guaranteed that the sub-form has already written the traits to the `AnnotationFeature` before that is saved.

So have a look at the traits-related methods in the `ConceptFeatureSupport` and at the code of the `ConceptFeatureTraitsEditor` - I think you can actually copy and reuse them for the `PropertyFeatureSupport`, just removing the `scope` trait and keeping the `knowledgeBase` trait.

**Comment by matchlesswei** [comment]
Thanks @reckart. I'll look into it after finishing Qualifier in Knowledge Base.

**Comment by matchlesswei** [comment]
We decide that:

- [ ] we reuse the kb setting from concept feature traits
- [ ] user should not be able to choose KP:Property in Type for features
