### ISSUE TITLE
Users should be able to change their own password by default

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#5201]
**Is your feature request related to a problem? Please describe.**
It is a best practice to ask users to change their password after the first login. However, by default access to the user profile to change the password is not available and must be explicitly enabled by the admin.

**Describe the solution you'd like**
Allow access to the profile by default while still allowing the admin to turn access off.

**Comment by mawiesne** [comment]
Thx @reckart for fixing this. We ran into the very same problem recently. After updating to the latest release, problem is gone. 👍
