### ISSUE TITLE
Typo in documentation: Admin Guide

### ISSUE THREAD

**Issue by pkolb** [inception-project/inception#521]
There's a typo in the [Installing as a service](https://inception-project.github.io//releases/0.5.1/docs/admin-guide.html#_installing_as_a_service) subsection of the Admin Guide. It reads:
```
JAVA_OPTS="-Djava.awt.headless=true -inception.home=/srv/inception"
```
(the `D` is missing for the second option). It should be:
```
JAVA_OPTS="-Djava.awt.headless=true -Dinception.home=/srv/inception"
```
or you'll get the following error message in `/var/log/inception.log`:
```
Unrecognized option: -inception.home=/srv/inception
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by reckart** [comment]
Fixed. Thanks for reporting!
