### ISSUE TITLE
changing the name of an instance adds a label to the concept of that instance

### ISSUE THREAD

**Issue by MdeBoer95** [inception-project/inception#533]
**Describe the bug**
When the label of an instance is changed in the KB page the new value for the label is also added to the concept that this instance belongs to.

**To Reproduce**
1. Go to KBPage
2. Select any instance and rename it by changing the label
3. See that the label statement group of the concept changes

**Expected behavior**
the change should only affect the instance

**Please complete the following information:**
 - Version and build ID: [Technische Universität Darmstadt -- Computer Science Department -- INCEpTION 𝜶 -- 0.6.0-SNAPSHOT (, build ) ]
 - OS: Linux
 - Browser: chrome

**Comment by reckart** [comment]
@MdeBoer95 if you look at fixing this, please create the bugfix branch off the 0.5.x branch.
