### ISSUE TITLE
Creating multiple projects causes exception (embedded database)

### ISSUE THREAD

**Issue by munnellg** [inception-project/inception#534]
**Describe the bug**
If I try to create more than one project in sequence in the Projects tab, INCEpTION reports an exception. A workaround is to simply navigate to the home screen then back into the Projects tab before trying to create the second project.

**To Reproduce**
1. From home screen go to Projects
2. Click Create
3. Give the project a name and save it
4. Click Create again
5. Give the new project a name and click save - INCEpTION will report an exception

**Expected behavior**
Should be able to repeatedly create projects without navigating away from the Projects window

**Please complete the following information:**
 - Version and build ID:  0.5.2 build 08f5facb646bb5c007962f4cf37e6daa68db2bbb
 - OS: Linux Mint 18 Sarah
 - Browser: Chrome

**Comment by reckart** [comment]
Thanks for reporting this. We knew there was a bug but we did not know how to trigger it. The error you were experiencing is a safeguard that we put in to ensure we will eventually find how to trigger it. Now you found it out! 

Now we'll look at how to fix it :)

**Comment by reckart** [comment]
Upstream issue: https://github.com/webanno/webanno/issues/1057

**Comment by reckart** [comment]
Upstream issue has been resolved.
