### ISSUE TITLE
Unit tests fail for Hucit due to SPARQL service being unavailable

### ISSUE THREAD

**Issue by munnellg** [inception-project/inception#543]
The unit tests in `de.tudarmstadt.ukp.inception.kb.KnowledgeBaseServiceRemoteTest` fail when running `mvn clean compile package` due to the Hucit SPARQL service being unavailable. I am not sure if this is due to the service being unavailable in my area (I have tried on several different networks) or because the service itself is down. Either way, the unavailability of the service arguably should not cause the entire unit test to fail and result in maven terminating the build as this failure is not due to the INCEpTION code base.

**Comment by reckart** [comment]
@munnellg Thanks for the report. We have multiple tests which check against remote KBs. This is not the best way in principle, but we want to be able to check that our tests really work against the latest live systems. 

@mromanello Probably we shouldn't test against your SPARQL endpoint? I guess it is quite a bit less stable than say Wikidata or DBPedia. WDYT?

@Rentier @naveen2507 Any comments?

**Comment by reckart** [comment]
@munnellg If you want to be bleeding edge, you could also get pre-compiled binaries of the latest automatic builds from our integration branch (master) from here: https://zoidberg.ukp.informatik.tu-darmstadt.de/jenkins/job/INCEpTION%20(GitHub)%20(master)/

**Comment by Rentier** [comment]
We could check in the test whether it is available or not and depending on that run the tests or not and print a warning.

**Comment by reckart** [comment]
@Rentier sounds good. We can use the JUnit `assume` mechanism to conditionally skip the test if the endpoint is not there.

**Comment by munnellg** [comment]
I tend to build from source as a way to get to grips with a new project. It's more of a personal process than a need to be on the bleeding edge, but thanks for the link!

Let me know if these issue reports get spammy. Just trying to flag things as I spot them. Seems like a good idea to have a record of them somewhere, even if the long term plan is not to address them.

**Comment by reckart** [comment]
@munnellg we're definitely happy go be getting your issue reports! The last two issues you reported are already fixed.

For a true bleeding-edge build of the INCEpTION master, you also need a local checkout of the master branch from the WebAnno repo since the two co-evolve. E.g. I had to fix the two issues you have reported before in the WebAnno codebase, even if they didn't really directly affect the WebAnno application itself.

It is good to receive all issues via the INCEpTION tracker - we can then triage and decide whether they are to be fixed in the INCEpTION code itself or in upstream code.

**Comment by reckart** [comment]
@naveen2507 @MdeBoer95 I think adding the [`assume`](https://junit.org/junit4/javadoc/4.12/org/junit/Assume.html) to the KB tests such that they are skipped if the remote SPARQL endpoint is not available falls into your area of responsibility.

**Comment by naveen2507** [comment]
DONE
