### ISSUE TITLE
Show IRI in description tooltip/popup

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#553]
**Is your feature request related to a problem? Please describe.**
If the user searches for something in the concept feature editor, it may happen that there are duplicates. The user cannot tell if these are true duplicates (different IRIs) or if there is a bug (e.g. #552).

**Describe the solution you'd like**
It would be useful to see the IRI of the concept along with the description in the tooltip/popup

**Comment by naveen2507** [comment]
DONE
