### ISSUE TITLE
Features can use disabled KBs

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#554]
**Describe the bug**
A concept linking feature may refer to a KB which is disabled.

**To Reproduce**
1. Create a KB
2. Create a concept linking feature and choose the previously created KB in the "Knowledge base" dropdown
3. Disable the KB (uncheck the "enabled" checkbox)
4. Switch back to the concept linking feature - the disabled KB is still listed

**Expected behavior**
If a concept linking feature links to a specific KB and that KB is disabled, then I would expect the feature to stop working. I would say this is expected behavior (not sure if this is actually the case though). However, the user should be warned in the concept feature editor as well as in the feature editor that the KB is disabled and the feature therefore does not work.

**Screenshots**

**Please complete the following information:**
 - Version and build ID: INCEpTION 𝜶 -- 0.5.2 (2018-10-04 15:37:48, build 08f5facb646bb5c007962f4cf37e6daa68db2bbb)

**Comment by naveen2507** [comment]
Works
