### ISSUE TITLE
Switching between projects does not hide KB details panel

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#557]
**Describe the bug**
The KB details panel remains visible when switching between projects.

**To Reproduce**
1. Go to a project with a KB and select the KB in the KB tab so that its details are visible
2. Click on another project
3. the list of KBs updates, but the details of the old project's KB are still shown

**Expected behavior**
KBs are project-specific. When selecting another project, the KB detail panel should be hidden.

**Screenshots**

**Please complete the following information:**
 - Version and build ID: 0.6.0-SNAPSHOT (2018-10-13 00:20:53, build 1b4ac7f18bd929953d6b55cce183dfe49e7014c6)

**Comment by MdeBoer95** [comment]
@naveen2507 I think we don't have this issue anymore with the new layout.

**Comment by naveen2507** [comment]
With the new layout we would have the issue with project setting page. 

![image](https://user-images.githubusercontent.com/10420950/47654830-f6a8e100-db8b-11e8-9076-5714f040663d.png)

**Comment by naveen2507** [comment]
Done
