### ISSUE TITLE
Entity search only finds concepts with labels

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#560]
**Describe the bug**
When a concept does not have a label (as is the case for most of the concepts in the Wine ontology), they cannot be found via the local Lucene-based indexing.

**To Reproduce**
1. Import wine ontology (local FTS enabled)
2. Try linking via a Named Entity annotation
3. Only "wine" and "Wine ontology" are shown in auto-complete field

**Expected behavior**
~~All items that show up on the KB page should also be retrievable via the auto-complete field (assuming that it is configured correspondingly)~~ (see https://github.com/inception-project/inception/issues/560#issuecomment-477513570)

- [x] KB creators should always include labels for their KB items ( classes/instances/properties) and the INCEpTION documentation should make explicit that these labels are mandatory in order to find the items.
- [x] it should be possible to search for items by entering their **full** IRI.

**Please complete the following information:**
 - Version and build ID: e93744a9a169c83a8226a4fef6098447a88395c1

-----

>>> @reckart When I import the wine ontology into a local KB (OWL mapping) with FTS enabled and create a layer with a KB-linked feature that allows classes/instances from any KB/scope - I still only get auto-completions for "Wine Ontology" and "wine", but for nothing else from the KB.

>> @rcffc In the Wine ontology, these two are the only items that have used `rdfs:label`. I am having a look at the build.

> @reckart I see. I wonder if we can maybe hook into/configure the LuceneSail indexing process somehow so that it also allows us to index the IRI suffixes that we show in the UI if no label is available.

@reckart Looks like that is not easily possible. We'd have to make changes directly to the RDF4J Lucene indexing code. The code already stores an "URI" field in the lucene index, but that cannot be queried - at least not via SPARQL as the analyzer used to parse the query tries to remove special characters. We'd get something like this when trying

```
ERROR LuceneIndex - There was a problem evaluating query 'uri:"http://mbugert.de/pets#animal"' for property 'null!
java.lang.IllegalStateException: field "uri" was indexed without position data; cannot run PhraseQuery (phrase=uri:"http mbugert.de pets animal")
```

**Comment by Rentier** [comment]
There is a property `INDEXEDFIELDS` which we might be able to leverage:

```
Defining the indexed Fields
The property INDEXEDFIELDS is to configure which fields to index and to project a property to another. Syntax:
 # only index label and comment
 index.1=http://www.w3.org/2000/01/rdf-schema#label
 index.2=http://www.w3.org/2000/01/rdf-schema#comment
 # project http://xmlns.com/foaf/0.1/name to rdfs:label
 http\://xmlns.com/foaf/0.1/name=http\://www.w3.org/2000/01/rdf-schema#label
```

**Comment by reckart** [comment]
We need to index the subject of the triple in a specific way, not a property. This is why I believe this `INDEXEDFIELDS` doesn't help us for this particular issue.

**Comment by reckart** [comment]
I see no reason why this should not also apply to non-local KBs, so I changed the title. The "problem" is that our searches are very much geared towards the label properties in general and do in general not take into account the IRIs. Doing so would considerably slow down the queries because **no** FTS engine really does try to extract a human-readable label from the IRI and make that searchable. So eventually, I see no way of really fixing this in a consistent and convenient way at the code level.

The solution is that KB creators should always include labels for their KB items ( classes/instances/properties) and the INCEpTION documentation should make explicit that these labels are mandatory in order to find the items.

A secondary solution should be to allow the user to search for items by entering their **full** IRI.

**Comment by reckart** [comment]
Users are now able to search for items by their full IRI. Also, the problem with the labels is now documented.
