### ISSUE TITLE
Cannot update "feature" field of recommender in Project Settings

### ISSUE THREAD

**Issue by rcffc** [inception-project/inception#565]
**Describe the bug**
The feature value of a recommender cannot be updated.

**To Reproduce**
1. Go to Project Settings (Recommender)
2. Click on "Create" and select Named Entity with feature "identifier".
3. Save
4. Then change feature to "value"
5. Save again.
6. Click on other tab
7. See that the feature has changed back to "identifier

**Expected behavior**
It should be possible to update the feature.

**Screenshots**
![peek 2018-10-15 12-26](https://user-images.githubusercontent.com/13070150/46945772-0a295780-d076-11e8-99a3-b6b08a4d2def.gif)

**Please complete the following information:**
 - build 0d83b05cf28d901b68cbd02c27c1bd1e4ce9cc8f
 - Ubuntu 16.04
 - Chrome

**Comment by reckart** [comment]
Does this also happen on the `feature/398-recommender-cas-in-out` branch?

**Comment by reckart** [comment]
Btw. seems to work ok for me on 7fdf5cfc4c7e6dc918b01d69317cd7a0e8d8c246

**Comment by rcffc** [comment]
Does not work on 7fdf5cfc4c7e6dc918b01d69317cd7a0e8d8c246, but on `feature/398-recommender-cas-in-out`.

**Comment by reckart** [comment]
Since https://github.com/inception-project/inception/pull/399 has been merged into master by now, I take this is fixed. Also, I didn't note any trouble configuring recommenders during my testing in the recent days.
