### ISSUE TITLE
Active Learning clears Annotation window

### ISSUE THREAD

**Issue by rcffc** [inception-project/inception#567]
**Describe the bug**
When Active Learning is started, the annotation window is blank.

**To Reproduce**
1. Go to Annotation Page.
2. Click on 'Start' (Active Learning)
3. Observe that Annotation window is blank.

**Expected behavior**
Text and annotations should continue to show.

**Screenshots**
![peek 2018-10-16 10-50](https://user-images.githubusercontent.com/13070150/47004246-6a310400-d131-11e8-85c5-47bd375c7e9a.gif)

**Please complete the following information:**
 - Version and build ID: 7fdf5cfc4c7e6dc918b01d69317cd7a0e8d8c246 (master)
 - OS: Ubuntu 16.04
 - Browser: Chrome

**Comment by reckart** [comment]
@rcffc has already been fixed : https://github.com/webanno/webanno/issues/1078

Please ensure you have the latest WebAnno code/JARs.
