### ISSUE TITLE
Refactoring KB Module

### ISSUE THREAD

**Issue by naveen2507** [inception-project/inception#572]
**Describe the refactoring action**

-------------------------------------------------------------------------------------------------------------------
- add documentation to make clear how KB - classes are related.
-------------------------------------------------------------------------------------------------------------------
- Change the structure of the UI. 
- KnowledgeBaseCreationWizard and KnowledgeBaseDetailedPanel use the same panel and we have a 
  redundant task for simpler modifications
  Eg. Use a type step panel or something and use it everywhere, that way we don't have redundant work
- remove view mode in project settings
- should be done before https://github.com/inception-project/inception/issues/598
-------------------------------------------------------------------------------------------------------------------
- Introduce something like KBUIUtil to shrink up the KBSI and put in methods which are related to UI part 
-------------------------------------------------------------------------------------------------------------------
- Move queries from RDFUtils to SPARQLQueryStore
-------------------------------------------------------------------------------------------------------------------

**Expected benefit**
Better structured KB module

**Comment by naveen2507** [comment]
Needs to be discussed.

**Comment by reckart** [comment]
@naveen2507 I think this issue should be split up into multiple issues - basically one issue for each off the sections in the description above which are separated by he horizontal lines.

**Comment by naveen2507** [comment]
@naveen2507 Please split me up.

**Comment by MdeBoer95** [comment]
@naveen2507 @reckart After having a look at the code again, I think we don't really need a KBUIUtils class at the moment but instead we can move some methods (e.g. ``checkSchemaProfile``) to corresponding UI classes (in case of ``checkSchemaProfile`` to ``SchemaProfile``) as we already discussed.
So I would change the issue description accordingly if you agree.

**Comment by naveen2507** [comment]
@MdeBoer95 yeah, that's what we discussed in the last meeting.

**Comment by reckart** [comment]
@MdeBoer95 please link the smaller issues created from this one, then close it.

**Comment by reckart** [comment]
@MdeBoer95 ping?

**Comment by MdeBoer95** [comment]
Has been split up into #788, #640, #639
