### ISSUE TITLE
Refactoring recommender Part 2

### ISSUE THREAD

**Issue by Rentier** [inception-project/inception#576]
Follow-up to #398. It might be a good idea to split these tasks even further.

**Describe the refactoring action**
- [x] Refactor annotation object (now called `AnnotationSuggestion`)
- [x] Remove the unused `documentUri` field from `AnnotationSuggestion`
- [x]  Port active learning
- [x]  JavaDoc
- [x]  Developer documentation
- [x]  Tutorial to implement simple recommender
- [x]  Adhere to max suggestions

**Expected benefit**
The code will be easier to maintain and read.

**Comment by reckart** [comment]
PR #388 made several changes to the annotation object (now called `AnnotationSuggestion`) and also to active learning.

What are the changes related to the annotation object that should be done as part of this issue here?

**Comment by Rentier** [comment]
The main thing for the annotation object was to not store lists of list, but store one annotation span in one object and group them into something like sentences.

**Comment by reckart** [comment]
Ok, that list of lists thingy is gone. We now have the `SuggestionGroup` which groups suggestions from different sources on the same location (e.g. POS/PosValue suggestions from OpenNLP and StringMatcher for the same word). We also have the `SuggestionDocumentGroup` which groups together multiple `SuggestionGroup`s from the same document. Does that resolve the bullet point for the moment?

**Comment by Rentier** [comment]
I think so. Next would be the renderer.

**Comment by Rentier** [comment]
Did we simplify the annotation ids?

**Comment by reckart** [comment]
`AnnotationSuggestion` has a method `getVID()` - but you probably do not mean the visual ID but the `ExtendedId` which is used in the `Predictions` object. `ExtendedId` and `Predictions` where both not refactored (or at least not simplified).

**Comment by reckart** [comment]
`AnnotationSuggestion` in fact still has that field, but it is not used anywhere except in `toString()`. We should remove it. `SuggestionGroup` and `SuggestionDocumentGroup` use only the document name.

**Comment by reckart** [comment]
Ok, PR merged. I already ticked some more boxes in this issue. What about the remaining todos? Leave here or create a follow-up issue?

**Comment by Rentier** [comment]
There are now 2 boxes left, I think you already did the renderer, and the last point " Maybe merge adjacent suggestions with the same label" is not relevant anymore.
