### ISSUE TITLE
Search sidebar shows duplicates

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#578]
**Describe the bug**
The search sidebar shows duplicates for linked entities

**To Reproduce**
Steps to reproduce the behavior (see screenshot):
1. Link some entities in a text to a KB
2. Perform search

**Expected behavior**
Every mention should only appear once

**Screenshots**
<img width="686" alt="2018-10-24_13-45-21" src="https://user-images.githubusercontent.com/1410238/47428323-39854600-d793-11e8-8217-a4fc9344c63c.png">

**Please complete the following information:**
 - Version and build ID: 4ef41a7884ae10fe7389f030de09b69937ab2582

**Comment by naveen2507** [comment]
Did the description for the entities show the same URLs?

**Comment by reckart** [comment]
What description do you mean?

**Comment by naveen2507** [comment]
IRI added to description field in #553

**Comment by reckart** [comment]
In the screenshot, you see two annotations for "Obama". But when I search for "Obama" (query see screenshot), I get 7 hits (4 duplicates of the first annotation and 3 duplicates of the second annotation). I believe the IRI shown in the description actually doesn't matter here. It seems that the NE annotations are indexed repeatedly with the same label.

**Comment by naveen2507** [comment]
Oh, Ok . Can you please check once with the exact query, if it repeats the same behaviour. I believe its related with the hierarchy of the concepts/instances. Is it WIkidata KB?

**Comment by reckart** [comment]
I tried it and there were even more duplicates. 

Then I pressed the "Reindex" button at the bottom of the sidebar - the duplicates disappeared.

Also after opening the document a second time, adding/changing annotations, the effect did not come back.

So it might have been a problem with an old index. I'll close the issue for now assuming that the "Reindex" has permanently fixed the problem.

**Comment by reckart** [comment]
Note: the version when I did the last try was 9bd5ff6f211035c9455d73293c3b5f112216fa5b
