### ISSUE TITLE
Re-arrange KB configuration items

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#598]
**Describe the refactoring action**
The arrangement of the configuration items in the KB settings (project settings) should be changed to group related items with each other:

* General settings
  * **Name** 
  * Enabled
  * **Language**
  * **Base prefix**
* Access settings
  * **Local / remote**
  * Write protection
* Access-specific settings (remote)
  * **SPARQL endpoint URL**
* Query settings
  * Results limit - note the name change, if we leave SPARQL in the name, it looks like the setting would only apply for remote KBs, but it likewise applies to local KBs, so we should change the name
  * Full-text search mode
* **Schema mapping**
  * Class / Instance mapping
    * Class marker IRI
    * Sub-class property IRI
    * Instance-of property IRI
    * Label property IRI
    * Description property IRI
  * Property mapping
    * Property marker IRI
    * Sub-property property IRI
    * Property label property IRI
    * Property description property IRI
* Root concepts

**Expected benefit**
A clear and concise description of what you expect to improve by the refactoring.

**Comment by reckart** [comment]
@MdeBoer95 I guess we should move this to 0.7.0, hm?

**Comment by MdeBoer95** [comment]
@reckart We can leave it in 0.6.3 for now. I will move it if necessary.
