### ISSUE TITLE
Refactor `AnnotationObject`

### ISSUE THREAD

**Issue by Rentier** [inception-project/inception#6]
Currently, the recommender API has some quirks which render it not very user friendly, hard to test and error prone. The main problem I have are with the AnnotationObject in combination with some coding problems. The first round of refactorings I want to do are

- [x] Remove the inheritance of `AnnotationObject` from `TokenObject`
- [x] Remove unused fields, generics and constructors in there.
- [ ] Let an annotation object have a list of `TokenObject` that its annotating to allow multi token annotations
- [ ] Remove the `List<List<List<AnnotationObject>>>` with a more readable signature, move predictions from the 3rd list to the second so that a has a list of `AnnotationObject`, if there are multiple predictions, then they live side by side instead per token

**Comment by Rentier** [comment]
I removed the inheritance of `AnnotationObject` to `TokenObject` and copied the fields and getter/setter into `AnnotationObject`. Now, the fields are

```
    private Offset offset;
    private String coveredText;
    private String documentURI;
    private String documentName;
    private int id;

    private List<TokenObject> sentenceTokens;
    private String annotation;
    private String description;
    private final String feature;
    private final String classifier;
    private final double confidence;
    private long recommenderId;
```

I want to defnitely delete `sentenceTokens`.

@reckart Which of these fields are really needed/sensible?

**Comment by reckart** [comment]
I would remove Offset and replace it by begin/end (int).

There was a reason why we needed access to the other tokens in the sentence, but I do not remember what reason it was. Maybe check where this field is used. Mind that we do not have a sentence object or sentence ID at the moment.

Recommender ID and classifier are kind of redundant. I guess that classifier was used when the code was still more separated from the rest of the code base. The `feature` info is in principle accessible via the recommender (via `recommenderId`). If we dare to couple to code more tightly into the rest of the codebase, then `classifier`, `recommenderId` and `feature` could be replaced by simply embedding a `Recommender`-type field. In terms of coding, it should facilitate things a lot doing that.

`documentName` and `documentURI` are probably also redundant. Needs to be check what is used where. Again, if we care to couple the code more tightly, embedding an `AnnotationDocument` here could be an option.

Some renaming:
* annotation -> label
* description -> uiLabel

**Comment by Rentier** [comment]
The `documentName` is used in the active learning to detect duplicate recommondatons. I think that we could replace it by implementing a proper `equals` or using the annotation id.

**Comment by Rentier** [comment]
I would also rename `classifier` -> `source`.

**Comment by Rentier** [comment]
The `documentName` is also used in `ExtendedId`.

**Comment by Rentier** [comment]
@reckart When I change the `AnnotationObject` to have a list of tokens instead of one, how can I create it then properly from a CAS? Does a CAS just have annotations per token or is there information which belong together?

**Comment by reckart** [comment]
Let's say you have a named entity in the CAS at offsets 0-10 and there are two tokens in the CAS at 0-4 and at 5-10. You can retrieve these tokens using (J)CasUtil.selectCovered(namedEntity, Token.class).

**Comment by Rentier** [comment]
We will no longer use this object (see #399) in the future, therefore I would close this.
