### ISSUE TITLE
document doesn't jump to the next suggestion location if "auto-scroll" is enabled

### ISSUE THREAD

**Issue by matchlesswei** [inception-project/inception#61]
If "auto-scroll" is enabled and active learning session is open, the document doesn't jump to the next suggestion location after acceptance in the main editor.

Check where auto-scroll is called.
Try different orders. (move refresh documents)

**Comment by matchlesswei** [comment]
I cannot reproduce this bug anymore.

**Comment by reckart** [comment]
Closing as "cannot reproduce" then. If anybody notices it again, please re-open (or create new issue).
