### ISSUE TITLE
Sentences list jumps back to top

### ISSUE THREAD

**Issue by shohre10539** [inception-project/inception#618]
**Describe the bug**
I am using inception to curate my annotated data. When using the curator UI, if the text is long and the annotated part needs to have a scrollbar to fit in the page, every-time I click on the next page button the scrollbar will jump to the first annotation page and I should scroll down again if I want to click on the annotation directly.

**To Reproduce**
1. Go to Project/Curation
2. Scroll down to a page in the annotation curation.
3. Click on the Next page
4. See that the scrollbar on the side jumps to the first page of annotations(pages)

**Expected behavior**
I would expect to see the same pages which I am working on in the curation process, wethear I am using next page button to go to the next annotation page or I am clicking it from the left side bar. I find it unpleasant to scroll down every-time I want to click on an annotation close to  the position I am currently working on.

**Screenshots**
![index](https://user-images.githubusercontent.com/22494696/48012533-7d2c6800-e122-11e8-8012-f94a6b4132a5.jpeg)

**Please complete the following information:**
 - Version and build ID:  INCEpTION 𝜶 -- 0.6.0 
 - OS: Linux

 - Browser: Chrome, Firefox

**Comment by reckart** [comment]
Right - I can see how that is annoying. I'll try to see if there is a quick fix to this.

**Comment by reckart** [comment]
Upstream issue: https://github.com/webanno/webanno/issues/1102
