### ISSUE TITLE
Recommender recommondations not removed when recommender is removed

### ISSUE THREAD

**Issue by rcffc** [inception-project/inception#64]
![ezgif-2-088ca52b8a](https://user-images.githubusercontent.com/13070150/38981624-20a90dd6-43c0-11e8-8454-b475ac5249ec.gif)

**Comment by rcffc** [comment]
What about adding a new Event: RecommenderDeletedEvent?
The RecommendationService could listen to it and remove predictions with the respective recommender id.

**Comment by reckart** [comment]
> What about adding a new Event: RecommenderDeletedEvent?

+1

**Comment by rcffc** [comment]
Okay, to finish this it must be possible to access the current user on the RecommendationEditorPanel. Do you have an idea how to do that?

**Comment by reckart** [comment]
Inject the UserDao into your component and call `UserDao.getCurrentUser()`.
