### ISSUE TITLE
Learning curve diagram

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#649]
**Is your feature request related to a problem? Please describe.**
We want to be able to see the performance of the recommenders configured on a given project in the recommendation sidebar.

**Describe the solution you'd like**
Display the performance as a "learning curve" diagram with time on the x axis and score on the y axis.

**Steps**
- [x] add a method to the RecommendationService to load RecommenderEvaluationResultEvent from the LoggedEvent table + unit test 
- [x] Decide on a JS library to use for rendering the chart
- [x] If a recommender is disabled in the project settings, then no line for it should be drawn
- [x] Create a new Wicket panel which loads the JS library and uses it to render the time/score information from the RecommenderEvaluationResultEvents retrieved in the first step + unit test
- [x] document the new feature in the user documentation (recommender section)
- [x]  on-mouse-over-infobox is drawing below the sidebar tab are, causing it to appear cut off. 
- [x] show only 4 digits behind the comma for scores

**Comment by Sibgha360** [comment]
"t-50" to "t-0" takes a lot of space as compared to if we show sequence 50-0. The panel width is small for displaying categories on the x axis. So in the latest commit I showed 0-50 sequence. Should there be a better idea, I will change it.

The graph is done for the multiple recommenders. Thinking how to handle layers as well as recommenders!

**Comment by reckart** [comment]
@Sibgha360 We said the multiple layers support should go to a separate issue / PR. So that means this PR should be good for review and probably merging now, right?

**Comment by Sibgha360** [comment]
Yes. It is good for the review.

**Comment by reckart** [comment]
> * Create a new Wicket panel which loads the JS library and uses it to render the time/score information from the RecommenderEvaluationResultEvents retrieved in the first step + unit test

@Sibgha360 The PR implements the new functionality directly in the RecommendationSidebar. Could you please move it to a separate `LearningCurveChartPanel` (java+html) which you then instantiate and add to the `RecommendationSidebar`. The panel should include only the chart, not the surrounding box, so the HTML template for the `LearningCurveChartPanel` is very basic and basically only contains the `chart-container` element.

These two still need to be done:

> * If a recommender is disabled in the project settings, then no line for it should be drawn
> * document the new feature in the user documentation (recommender section)

**Comment by reckart** [comment]
@Sibgha360 can we hide the legend below the chart (i.e. the names of the recommenders) such that they only appear when we move the mouse over a line?

![2018-12-07_13-33-05](https://user-images.githubusercontent.com/1410238/49648030-afccc780-fa24-11e8-948f-972251ea03b8.png)

For some reason, the on-mouse-over-infobox is drawing below the sidebar tab are, causing it to appear cut off. Maybe increase the z-index of the infobox?

The score values are *very* long. Having max 4 digits behind the comma should be more then enough.

**Comment by Sibgha360** [comment]
> @Sibgha360 can we hide the legend below the chart (i.e. the names of the recommenders) such that they only appear when we move the mouse over a line?
The legends below the chart are rendered by the JS library. I will check if it is possible to remove them. But isnt it necessary to show which line belongs to which recommender? It is also clickable so one can remove or add the line of a particular recommender.

**Comment by reckart** [comment]
The reason why I believe it would be nice if the names are not shown is that it makes the height of the chart unpredictable. But anyway, it's not critical. The comments on the PR are more important. We can leave the legend in for the time being.
