### ISSUE TITLE
Tool list sometimes not updated in recommender editor

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#681]
**Describe the bug**
In the recommender editor, the UI does not always properly update itself when switching between values. E.g. the may happen that the list of tools gets stuck and doesn't start showing the OpenNLP POS recommender when switching to the POS layer. Also, some elements like the activation strategy does not get re-rendered properly whens switching between values.

**To Reproduce**
Steps to reproduce the behavior (doesn't always work):
1. Create a new recommender
2. Choose layer "Named entity"
3. Choose feature "value"
4. Choose layer "POS"
5. note that the POS recommender may not be visible in the dropdown list now

**Expected behavior**

**Screenshots**
Screen should re-render properly depending on the value settings.

**Please complete the following information:**
 - Version and build ID: 9bec828e308597b1f8314ca2af8e8540abd0f47d

**Comment by reckart** [comment]
Humpf... accidentally committed directly to 0.6.x without doing a PR...

**Comment by Rentier** [comment]
Looks ok
