### ISSUE TITLE
Wine Ontology missing from packaged version

### ISSUE THREAD

**Issue by mbugert** [inception-project/inception#687]
**Describe the bug**
In the knowledge base creation wizard, when attempting to add the wine ontology:
`Unable to download or import knowledge base file class path resource [de/tudarmstadt/ukp/inception/kb/pre-defined-knowledge-bases/wine.rdf] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/srv/inception-stable/inception-stable.jar!/WEB-INF/lib/inception-kb-0.6.2.jar!/de/tudarmstadt/ukp/inception/kb/pre-defined-knowledge-bases/wine.rdf`

**Please complete the following information:**
 - Version and build ID: 0.6.2 (2018-11-12 15:17:55, build a125fe72aeee207568c5c1da32b702e9b14d3f69) and still in  0.7.0-SNAPSHOT (2018-11-20 23:16:44, build 9d8ea76dbd5c87fef45dd8be9095fda4a9a6f705)

**Comment by naveen2507** [comment]
@MdeBoer95 can you take a look into this?
