### ISSUE TITLE
Incorrect usage of fact linking gives verbose, but unhelpful error messages

### ISSUE THREAD

**Issue by mbugert** [inception-project/inception#688]
**Describe the bug**
Annotation page, in the fact linking layer: If one disobeys the feature types when linking subjects, objects, etc. many errors appear. See GIF below.

**Expected behavior**
Links to incorrect types should not be possible, I suppose.

**Screenshots**
![peek 2018-11-21 13-15](https://user-images.githubusercontent.com/23331603/48846356-3e8fe200-ed9f-11e8-9db3-bd26cc8ace00.gif)

**Please complete the following information:**
 - Version and build ID: 0.6.2 (2018-11-12 15:17:55, build a125fe72aeee207568c5c1da32b702e9b14d3f69)

**Comment by reckart** [comment]
The fact layer is no longer enabled by default.
