### ISSUE TITLE
NPE when creating annotation in hidden annotation layer

### ISSUE THREAD

**Issue by mbugert** [inception-project/inception#689]
**Describe the bug**
Feedback panel shows `Error: null`.

**To Reproduce**
1. Have project with POS, Dependency layers
2. Open annotation page
3. Uncheck 'show' for dependency layer in the settings modal
4. Create two POS annotations, then attempt to draw a dependency relation between them

**Expected behavior**
Dep annotation should either not be created, or (even better): User could be informed discreetly that he could create dependency relations here, but the layer is disabled.

**Screenshots**

**Please complete the following information:**
 - Version and build ID: 0.6.2 (2018-11-12 15:17:55, build a125fe72aeee207568c5c1da32b702e9b14d3f69)

**Comment by reckart** [comment]
Upstream issue resolved: https://github.com/webanno/webanno/issues/1153
