### ISSUE TITLE
Search feature - annotations in bulk

### ISSUE THREAD

**Issue by Tiberiu17** [inception-project/inception#705]
**Is your feature request related to a problem? Please describe.**
Manually stepping through all search results to create/review annotations is cumbersome. The ability to apply changes to multiple match locations or annotations would greatly speed up things.

**Describe the solution you'd like**
- [x] Perform a query in the search sidebar. Note that the sidebar effectively only identifies matching spans, not individual matching annotations!
- [x] Optionally add checkboxes to the match results to allow restricting the following actions to a subset of the matches.
- [x] Create an annotation or click on an existing one to open it in the annotation detail editor in the right sidebar. This provides information about the layer we want to operate on and an annotation template.
- [x] **Annotate all** button which creates a new annotation corresponding to the one in the editor at every match location. If there already is an annotation of the same type do nothing. Optionally allow the user to enable an **override mode** which would update the existing annotation to the values currently shown in the feature editor. Note that features depending on the annotation context (i.e. link features) are ignored.
- [x] **Delete all** button which deletes all matching annotations from the given layer. Optionally only delete those which match the feature values shown in the editor.

**Describe alternatives you've considered**

**Additional context**

----

Hi,

Thanks for all the great features in Inception. Game changing.

I have a few proposals of enhancing the Search function. These additions will translate in significant time saved for the user, particularly when conducting corrections.

- annotate all instances of searched token/tokens with a specific label/value
- remove all annotations of a searched value
- shift all annotations of a searched value to a different value within the same layer or different layer

Thanks.

**Comment by reckart** [comment]
> Thanks for all the great features in Inception. Game changing.

Thanks :)

I think we already track your request under this issue: #295

**Comment by reckart** [comment]
Considering, this is different from #295. I have updated the issue description with a more concrete idea of what to do.
