### ISSUE TITLE
External recommender should not send empty training requests

### ISSUE THREAD

**Issue by Rentier** [inception-project/inception#738]
The external recommender sends training requests even when there are no annotations yet. It would be nice to not do that.

**Comment by reckart** [comment]
> Do you think it makes sense to look in the TrainingTask whether a CAS contains annotations and then just do not hand it to the recommenders?

Yes, I think that makes sense.

**Comment by Rentier** [comment]
@Horsmann INCEpTION should not send empty training requests anymore.
