### ISSUE TITLE
KBs sometimes used even though they are disabled

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#741]
**Describe the bug**
It seems that KBs are used in some cases even if they are disabled. 

**To Reproduce**
1. Create a KB and uncheck the "enabled" checkbox
2. Put a breakpoint into `KnowledgeBaseServiceImpl.getConnection(KnowledgeBase)`
3. Try annotating named entities, adding entity linking recommender, etc and see when the breakpoint gets it

**Expected behavior**
If a KB is disabled, it should not be used.

**Please complete the following information:**
 - Version and build ID: 0bb114157b7391bb8b0417f2ab7944594f8839ea
 - OS: [e.g. Windows, Linux, OS X]
 - Browser: [e.g. chrome, safari]

**Comment by Rentier** [comment]
There are many `for (KnowledgeBase kb : getKnowledgeBases(aProject))` which neglect checking for enabled.

What is the difference between `readKBIdentifier` and `readInstance`? I started to work on this, but `readKBIdentifier` is untested, therefore I do not want to touch it without understanding it, writing tests and see what happens after adding a guard for `isEnabled`.

**Comment by reckart** [comment]
@MdeBoer95 Do you know the answer to this question?

> What is the difference between readKBIdentifier and readInstance?

**Comment by reckart** [comment]
@Rentier I wouldn't check for enabledness at such a low level (i.e. `readInstance()`). KB enabledness should IMHO be checked at a high level such as when listed in the UI or being used for higher-level tasks such a entity linking. Low-level access to the KB should not be prevented even if it is disabled.

**Comment by naveen2507** [comment]
> @MdeBoer95 Do you know the answer to this question?
> 
> > What is the difference between readKBIdentifier and readInstance?

`readKBIdentifier(..)` reads any IRI regardless of it being concept or instance and returns  Optional<KBObject> whereas `readInstance(..)` is a method limited to read just instance. The purpose for `readKBIdentifier(..)`  was  basically to identify if any particular IRI is part of the KB as an entity.

**Comment by MdeBoer95** [comment]
```readInstance``` looks specifically for instances, so something that is *typeof* <Any Class/Concept>. If the given identifier belongs to a concept or a property it will return ```Optional.empty()```
```readKBIdentifier``` looks for both concepts and instances and with #529 also properties.

**Comment by MdeBoer95** [comment]
@reckart where did the code from #595 go? It solved the problem for the feature editors and the feature traits.

For the other cases I think we just need to replace some ```getKnowledgeBases(...)``` with ```getEnabledKnowledgeBases(...)``` like for example in the FactLinkingService:
https://github.com/inception-project/inception/blob/a5e973ba58aca2877ecd6fb62c8eaa72b239e7df/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/FactLinkingServiceImpl.java#L67-L72



For methods like ```readKBIdentifier(Project aProject, String aIdentifier)``` I would say we also use ```getEnabledKnowledgeBases(...)``` here otherwise it would be to much effort to filter out the results that come from an enabled knowledge base at a higher level.

**Comment by reckart** [comment]
@MdeBoer95 I don't know why, but the changes appear to have been lost between f2c3a8127937ef892e1aad7a1dcd289ca5f3334d (your commit) and 42d2ccaac98001e23de97a75659fc9bffd4fdca6 (my commit). I don't remember having discarded that code as part of a merge/conflict resolution - but it seems I must have done that.... sorry. Can you resurrect the lost code from f2c3a8127937ef892e1aad7a1dcd289ca5f3334d?

**Comment by MdeBoer95** [comment]
@reckart I set a breakpoint but the knowledge base does not appear at that point when it is disabled. Do you remember your setup?
Also thinking about my previous comment again it might actually be better to leave things as they are right now. The remaining ```getKnowledgeBases()``` are invoked from come kind of "ServiceImpl" or in the UI at places where they are necessary.
