### ISSUE TITLE
Bad self-evaluation of OpenNLP POS recommender

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#751]
**Describe the bug**
The evaluation of the POS recommender is overly optimistic. I guess that is because it learns on partially annotated data (i.e. incomplete sentences) and just learns the majority class (`GAP`) and then even considers a prediction of `GAP` on a token without a POS tag to be a true positive.

**To Reproduce**
1. add OpenNLP POS tagger to a project
2. open the recommendation sidebar to see the learning curve (requires PR #708)
3. annotate data

**Expected behavior**
It can be seen that the more data is annotated, the less recommendations we get from the OpenNLP POS recommender - in particular if we annotate wildly across sentences, leaving many partially annotated sentences around.

I would expect that a `GAP` prediction on a token without a POS does not count towards the score of the recommender.

**Screenshots**
![2018-12-07_13-19-55](https://user-images.githubusercontent.com/1410238/49647605-5b751800-fa23-11e8-8aa4-b6f24511e5d2.png)

**Please complete the following information:**
 - Version and build ID: 57666340d08ea5a8379ab66bf8b1df791f6a2473

**Comment by Horsmann** [comment]
Yes, seems to be the same source problem. What I encountered was that I received mostly "GAP" predictions with the TC backend. In particular, for large documents it becomes a problem to assume a "GAP" label for tasks such as POS tagging. The majority of words will be GAP at the beginning (i.e. nothing annotated yet). This class receives during model training such a high frequency weight that you will probably never receive any other prediction than "GAP". I didn't really think about incomplete sentence annotation yet. Not sure what happens in the tc-recommender under this condition.

**Comment by reckart** [comment]
Well, we don't consider sentences that for the OpenNLP POS tagger that do not have *any* POS annotation. The sentence must have at least one POS annotation to be taken into account.

**Comment by reckart** [comment]
@UWinch Do you know if this is covered by https://github.com/inception-project/inception/pull/1070?

**Comment by UWinch** [comment]
Yes, it should be covered.

**Comment by UWinch** [comment]
closed with #1050
