### ISSUE TITLE
Get documents from Hadoop/Spark for external search

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#769]
**Is your feature request related to a problem? Please describe.**
It would be nice if I could access documents from my Hadoop/Spark Cluster

**Describe the solution you'd like**
It might be possible to use existing solutions like [elastic-hadoop](https://github.com/elastic/elasticsearch-hadoop).

**Comment by reckart** [comment]
There is no use-case in sight for this functionality, so we likely will not implement it any time soon. If the use-case appears, re-open or create a new issue.
