### ISSUE TITLE
Improve Candidate Selection Step by refining SPARQL queries

### ISSUE THREAD

**Issue by rcffc** [inception-project/inception#77]
There are still some wikimedia-specific instances that are not desirable and should be filtered, 
namely disambiguation pages, category pages, wikimedia list articles, wikimedia templates, wikimedia news articles and wikimedia navigational templates.

Another thing is that the recently added descriptions are retrieved in english and german, whereas we only want english ones.

**Comment by reckart** [comment]
What do the additional filters from #78 filter out?

**Comment by rcffc** [comment]
Updated description.
