### ISSUE TITLE
Add scheduling introspection capabilities

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#772]
Create an API which can be used to display the status of background jobs of the current user / of all users, e.g. on the annotation page or elsewhere in the UI. We can query the status of a task, independent of whether that task is still in the queue or already running

- [x] Add introspection capabilities in backend

**Comment by Rentier** [comment]
@reckart Where do you want to display the running tasks? Should it be a new item in the dasboard?

**Comment by reckart** [comment]
Depends. For some tasks, you want to see them in the place where you started them or where it is relevant to track them. E.g. the suggestion sidebar could show the status of background training/prediction. But it would be nice to have a general access to all background tasks from the current user e.g. via a popup list accessible from the page footer or header.

Maybe for a start, add a (reusable) training progress indicator to the AL and/or recommendation sidebar?

**Comment by reckart** [comment]
Removing the subtask for displaying running tasks in the UI from this one. We can have a separate issue for it (if we don't even already have one).
