### ISSUE TITLE
Apply a source code formatter as part of the pre-commit process?

### ISSUE THREAD

**Issue by rgabbard** [inception-project/inception#779]
**Is your feature request related to a problem? Please describe.**

I noticed in your [contribution guide](https://dkpro.github.io/contributing/) that you provide Eclipse style files for the desired code style which can apparently also be used with plugin which replaces IntelliJ's usual code formatting with Eclipse's (though it appears sometimes this plugin breaks with IntelliJ updates).

I was wondering if you had considered the alternative of using an automated code formatter as a pre-commit hook?  Such an approach tends to be more contributor-friendly and is IDE-neutral (Eclipse seems to be hemorrhaging users in the past few years...).  We've found this helpful on several internal projects, especially since the standard automated layouts (Google's format for Java, `black` for Python) tend to minimize diff sizes (at the cost of less efficient use of vertical space).

**Describe the solution you'd like**

Use https://github.com/google/google-java-format as a pre-commit hook (e.g. using https://github.com/Cosium/maven-git-code-format ) to ensure consistent formatting after each commit.

**Describe alternatives you've considered**

The current approach (providing style files for Eclipse + IntelliJ plugin) works and the ISI team is happy to use it for our contributions.  I mention the alternative just because I was reading through the contributors guide and thought it might make lower the barrier for users making "drive-by" bug fixes, etc.

**Comment by reckart** [comment]
Besides, doing this now would impact on the ability to use the "blame" feature.

**Comment by rgabbard** [comment]
No problem - those are all reasonable reasons for not doing it.
