### ISSUE TITLE
External search document preview is missing

### ISSUE THREAD

**Issue by shinyichen** [inception-project/inception#789]
**Describe the bug**
The external search results had links to preview the documents, but now they are missing. From conversation with @reckart on gitter, the problem is due to this line of code
[`link.add(new Label("title", result.getUri()));` in `de.tudarmstadt.ukp.inception.app.ui.externalsearch.SearchPage.ResultRowView`](https://github.com/inception-project/inception/blob/master/inception-ui-external-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/externalsearch/SearchPage.java#L314), where `result.getUri()` should be `documentTitle`.

**To Reproduce**
1. Enable external search
2. Go to a project's external search page, type a keyword and enter.
3. The results have no titles and no links to preview.

**Expected behavior**
Step (3) above, the each result should have a title which is a link to preview the document.

**Screenshots**
Current behavior
<img width="654" alt="screen shot 2018-12-18 at 2 54 29 pm" src="https://user-images.githubusercontent.com/636361/50189468-33669e00-02da-11e9-8d00-52928061ecf6.png">
Expected behavior
![49902710-0131e800-fe65-11e8-8f25-29f65a2e618d](https://user-images.githubusercontent.com/636361/50189482-44afaa80-02da-11e9-950f-fcaf1feddc72.png)

 - Version and build ID: 0.7.0-SNAPSHOT
 - OS: OSX 10.12.6
 - Browser: Chrome
-  Branch: master
-  Commit: b2f780d949ac005ea8138a0e6ce338e40f86eb10

**Comment by rgabbard** [comment]
Our preferred order would probably be title, then ID, then URI.  I don't remember how we set up our index, but we can easily re-index with a human-readable title.

**Comment by reckart** [comment]
Order updated in PR #794.
