### ISSUE TITLE
Easy way to resume annotation

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#804]
**Is your feature request related to a problem? Please describe.**
When coming back to annotation after a few hours/days/weeks, it is sometimes difficult to remember where to resume the work.

**Describe the solution you'd like**
An easy way to go back to the last location worked on to resume working from there.

* The project dashboard could provide an overview over the user's last activities (from the event log) in the project and e.g. show the last document edited/curated and allow directly opening it from the dashboard, optimally even jumping to the last edited location within the document.

**Describe alternatives you've considered**
The last edited location could also be saved as a per-user preference. However, the user-preference code need to be rewritten and before that adding new preferences doesn't make much sense. Also, the idea of resuming work is much more related to activity than to preference.

**Comment by UWinch** [comment]
Concerning adding a progress-icon to the open-document-dialog:
In my opinion, this can be completely done in Webanno by adding a new variable to the Annotation- or SourceDocumentState which is then mapped to an icon when the document-list is build in the OpenDocumentDialogPanel. 
Can I move this to a Webanno-Issue?

**Comment by UWinch** [comment]
Moved the document state icons to new issue https://github.com/inception-project/inception/issues/1180
