### ISSUE TITLE
Allow/prevent annotation overlap behavior

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#805]
**Is your feature request related to a problem? Please describe.**
The named entity layer cannot be exported in any of the CoNLL formats if there are overlapping annotations. However, there is no way to enforce the non-overlap of annotations. Only **stacking** can be disabled, but not **overlapping**.

**Describe the solution you'd like**
- [x] Replace the **Allow stacking** option with dropdown choice **Ambiguity**  (?) which offers options like **Allowed**, **No stacking**, **No overlap**.
- [x] Highlight annotations with an error highlight if they violate the behavior.
- [x] Prevent closing a document while there are any invalidly placed annotations.
- [ ] ~~Add validation sidebar~~ moved to separate issue -> https://github.com/inception-project/inception/issues/864

**Describe alternatives you've considered**
Considered adding a new boolean option **Allow overlap**, but we already had the confusion about the granularity checkboxes, so better directly switch to a dropdown choice.

**Additional context**
* Related upstream issue: https://github.com/webanno/webanno/issues/1206

**Comment by mariaBio** [comment]
I would opt for the 2nd and 3rd suggestions: 
[2] - highlight annotation which violate the chosen format.
[3] - prevent closing a document while there're invalid annotations. (Keep the erroneously annotated spans highlighted)

**Comment by reckart** [comment]
The first point (replace the "Allow stacking" checkbox with a drop-down choice) seems important to me as well because stacking and overlapping are not fully orthogonal. A stacked annotation is by definition overlapping. I am not sure if the name/options mentioned right now (name "Ambiguity", options "Allowed", "No stacking", "No overlap") are good though. Having meanwhile thought more about it, I think that maybe the name of the choice should be "Overlap" and the options should be "None", "Any", "Stacking only", "Overlapping but not stacked".

Most of the refactoring to allow implementing this feature has meanwhile been done (in https://github.com/webanno/webanno/issues/1170). What is left now is to implement the actual checks and the related UI/DB changes.

**Comment by mariaBio** [comment]
I agree with your observation and suggestion regarding the options. The reason of my initial preference for the 2nd and 3rd options was the use of CoNLL format. 
With the extensive choice of stacking modalities, the question is when it would be applied. I thought, it could be useful to ask the user to specify the desired export format right at the beginning of the annotation process. It would provide constraint on the stacking/overlapping spans and avoid unnecessary drop-down checkboxes and the necessity to use them. Then, depending on the selected export format, one of the initially suggested solutions will be invoked when the annotation error occurs.  Would it make sense?

**Comment by reckart** [comment]
Asking the user for the preferred export format of the project during project creation and configuring the defaults accordingly would be quite some effort. I am not sure if the improvement in user experience will at this time compensate the effort.

I would rather suggest to use conservative defaults (i.e. such working for most/all export formats) for the settings, e.g. not allowing stacking/overlap on the built-in named entity layer and possible not on any of the other layers. Also, when the user creates a new layer, similarly conservative settings should be chosen. If the user then decides to change these settings to permit overlap, we should assume that it is a conscious choice and that the users understand their preferred data format well enough to know whether or not it is actually able to represent such annotations.

**Comment by mariaBio** [comment]
Sure. Would it imply then that the error check would only work with the original restrictive settings? Or the checking system would first consult the settings specified by the user for compatibility?

**Comment by reckart** [comment]
The errors displayed to the user in the annotation editor depend on the current layer settings. 

Let's say you start out allowing stacking and later decide that stacking was a bad idea. Then you can go to the layer settings and change the setting. When you go back to the annotation screen, you'll see that any stacked annotations now have error markers.

When you mark a document as finished, it is the same thing: the current layer settings are used to perform the validation. That said, if you have already marked any documents as finished and then change your layer settings, these finished documents are not re-validated again. The validation happens only when pressing the "finish" button.

**Comment by mariaBio** [comment]
Thank you for the detailed answer.
The "finish" button is indeed a bit too "decisive". Honestly, I do not use it to be able eventually come back to the document at later stages.

**Comment by reckart** [comment]
I agree with this observation. I have been thinking about adding a "Validation sidebar" on the annotation screen where you could manually trigger a validation of all documents in the projecta nd get a list of the problems. Clicking on a problem would then load the respective location/annotation in the editor and allow the user to resolve it (e.g. by deleting all but one of the stacked annotations). Since full project validation can take some time, the user would need to explicitly request validation/revalidation by clicking a button. But that would allow validation without having to mark the document as finished ;)

**Comment by mariaBio** [comment]
I think such functionality would be very useful!

**Comment by reckart** [comment]
Moved creation of the validation sidebar to a separate issue: #864
