### ISSUE TITLE
Recommenders for character-based NER 

### ISSUE THREAD

**Issue by qiuwei** [inception-project/inception#843]
**Is your feature request related to a problem? Please describe.**
Inception doesn't provide any recommenders for character-based span annotation.

**Describe the solution you'd like**
Since the recommenders for token based annotation is already implemented, treating characters as tokens makes some sense. It might cause performance issues. However, for languages which don't have clear word boundaries, e.g., CJK languages, this might be the only option.

**Describe alternatives you've considered**

**Additional context**
For text in English, I also encountered some cases especially for medical text, in which the annotation cannot be purely token based. I think providing character level recommenders makes sense.

**Comment by reckart** [comment]
@qiuwei do you have any recommendation for an easy-to-integrate Java-based ML package which generates char-based annotations - best something already pre-configured for a specific task (comparable to level of complexity of working with - let's say - the named entity recognizers provided by OpenNLP)?

**Comment by qiuwei** [comment]
@reckart Sorry I am not aware of that. I guess for English, it's not a common need. 
I think opennlp maxent model should also work for character based models, but I have never tried it out.

I think a character level string matcher is already very helpful for CJK languages. 

I would like to contribute, but I am rather new to this project.
What part of the code should I dig into to implement this?

**Comment by reckart** [comment]
If you are looking to adapt a string-based approach, you could look at https://github.com/inception-project/inception/tree/master/inception-imls-stringmatch

* `src/main/java/.../StringMatchingRecommender.java` - implements the actual recommender. It is based on a trie - so that should work ok for characters - but the `extractData()` method in particular operates over sentences and tokens. 
* src/main/java/.../StringMatchingRecommenderFactory.java` - makes the recommender available to the application and controls on which granularities it can be used (accepts() method)
* src/test/java/.../StringMatchingRecommenderTest.java` - implements some unit tests

**Comment by qiuwei** [comment]
@reckart I tried manually adding space between all of the characters for Chinese, it seems both StringMatcher and OpenNLP NER recommender already work pretty well for my use case.

**Comment by reckart** [comment]
Nice 👍

**Comment by Rentier** [comment]
As I am also interested in recommendation for Chinese, I would ask you to leave this issue open; I want to have a look into it.

**Comment by qiuwei** [comment]
@Rentier I agree. The current approach still feels like a hack. I will also try finding out whether there is any better way.

**Comment by Apollo-XI** [comment]
I have the same a similar issues with Spanish texts with bad spelling and grammatical errors. In some of them, some annotations couldn't be purely token based. I think that it would be nice if INCEpTION could offer this possibility or at least allow to use external recommenders to make character-based NER predictions.

**Comment by jcklie** [comment]
@reckart What do you think would happen if we allow external recommender for non-token based layers? I think that we do not use token in the external recommender right now. We use tokens in `PredictionTask::extractSuggestions` though.

**Comment by jcklie** [comment]
We added this feature to our [external recommender framework](https://github.com/inception-project/inception-external-recommender).
