### ISSUE TITLE
Enabled dropdown boxes do not look enabled

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#845]
Enabled dropdown boxes do not look enabled . It would be nice to make it more visible that they are enabled .

**Comment by reckart** [comment]
Really? For me it looked like the *enabled* dropdowns look rather disabled as lone as the *None* option is chosen. I didn't think the *disabled* dropdowns would not look disabled...

**Comment by reckart** [comment]
I believe the intended semantics of the "Choose One" option being gray is that is in fact actually not choosable (it is a null value and the field is mandatory) - so one could argue that this particular option is disabled. But it looks like the entire field would be disabled.

**Comment by reckart** [comment]
The upgrade to Bootstrap 4 fixed this one.
