### ISSUE TITLE
Documents outdated for the latest 0.7.0 version 

### ISSUE THREAD

**Issue by qiuwei** [inception-project/inception#857]
**Describe the bug**
In the installation guide, there are plenty of information about installing webanno.
I guess it's outdated? 

**To Reproduce**
https://inception-project.github.io//releases/0.7.0/docs/admin-guide.html#_application_home_folder

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/1304505/51094497-99b2e380-17e8-11e9-954b-2359380c6d69.png)

**Please complete the following information:**
 - Version and build ID: 0.7.0 (2019-01-24)
 - OS: OS X
 - Browser: chrome

**Comment by reckart** [comment]
INCEpTION and WebAnno share a part of their documentation. After the recent restructuring of the documentation, I apparently did not sufficiently check it. Thanks for noticing. The documentation is up-to-date except the naming in some shared parts.

**Comment by reckart** [comment]
Fixed on the website for the 0.7.0 documentation and will be fixed in the embedded online help in 0.7.1.
