### ISSUE TITLE
[Question] inception still uses embedded database even though I have configured a standalone one.

### ISSUE THREAD

**Issue by qiuwei** [inception-project/inception#858]
I guess it's not a bug, but I couldn't find other places to ask(btw, is there a slack channel for questions?)

I am trying to dockerize inception and got inception successfully running. However, inception uses the embedded database instead of the one I have configured. 

The inception.conf is already owned by root:root. 
I start inception by simply running java -jar /srv/inception/inception.jar

**Comment by reckart** [comment]
How have you configured the external DB? I mean - how do you tell INCEpTION to use it?

**Comment by qiuwei** [comment]
I followed the documents, by creating the config files inception.conf and settings.properties under /srv/inception.

**Comment by reckart** [comment]
The default location for the `settings.properties` file is the home folder of the user running INCEpTION. If you want to keep it in `/srv/inception`, you'd have to use `java -Dinception.home=/srv/inception -jar /srv/inception/inception.jar`

You could copy over the WebAnno dockerization configuration from:

* https://github.com/webanno/webanno/tree/master/webanno-webapp/src/main/docker
* https://github.com/webanno/webanno/blob/72a44411e104fa2bbb2f2065ac4f121b3e368d73/webanno-webapp/pom.xml#L679

... and adjust it for inception. Feel free to open a PR if you do that.

**Comment by reckart** [comment]
There is no Slack channel - we use Gitter: https://gitter.im/inception-project/Lobby

**Comment by qiuwei** [comment]
@reckart the dockerfiles for webanno requries very little adaption, thx:)

I will try to make a pull request after I cleaned up things.
