### ISSUE TITLE
Group search results by feature value

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#867]
**Is your feature request related to a problem? Please describe.**
When refactoring annotations (e.g. changing many named entities with the label `LOCATION` to the label `CITY`) it would be beneficial to be able to group search results by feature values.

Consider the user running a search like `<NamedEntity/>`. The results are now grouped by documents and it is not possible to see what each entity is annotated as. 

**Describe the solution you'd like**
An option to group search results by a feature. E.g. considering the example above, it would be nice to see the entity matches grouped by "LOCATION", "PERSON", etc. In this way, the annotator could more conveniently find the relevant annotations to refactor. 

- [x] Add choice to group by document / feature value
- [x] Offer user to select one (or maybe more) features
- [x] For feature grouping, the values of the selected features are then displayed as the group headers in the search results

**Describe alternatives you've considered**
None so far.

**Additional context**
Probably best to do this one before moving on to implement #705.

**Comment by mariaBio** [comment]
All four options are very useful. 
The 1st one gives all the flexibility to the user. 
The 2nd option is handy when user believes that only a restricted number of feature values have been used during the annotation, or user is interested in a specific feature subset. 
The 3rd helps to ease and speed up the revision process.
The 4th one compensates to some extent for absence of the 3rd feature, if only the 1st option is offered.

**Comment by MdeBoer95** [comment]
@reckart I have the following problem for layers where stacking is enabled:
![grafik](https://user-images.githubusercontent.com/37872452/58748729-0f100f80-847d-11e9-8076-560403de0e61.png)
In this example I have two stacked Chunk annotations at token 55. One of them has a feature value Tag = "myTag" (I guess that's elements 10 and 11) and the other one has no feature value (element 12 then). Is there any way to find out whether token 11 belongs to 10 or 12 other than looking at the order in the list ?

**Comment by reckart** [comment]
I don't see any way how we can tell to which "Chunk" the "Chunk.Tag" belongs by looking at the index data. There are a few fields in the `MtasToken` which I believe we do not use yet, e.g. the "real offset" fields - but I am not sure if we can simply abuse them to store the UIMA Feature Structure addresses in there....

**Comment by reckart** [comment]
What are the bracketed `[-------.------]` thingies in your screenshot? Maybe these are fields we could abuse?

**Comment by MdeBoer95** [comment]
This one is the "real offset". The empty ```[----]``` fields at the end are ```parentId``` and ```tokenPayload```.

**Comment by reckart** [comment]
`tokenPayload` sounds like we might care to use it...

**Comment by MdeBoer95** [comment]
I will use it then to store the UIMA Feature Structure addresses.

**Comment by reckart** [comment]
Ok, but mind that you cannot actually use the address to look something up lateron - you can only use it to figure out which pieces of index information belong together. The FS addresses may change whenever the user opens a document, so you cannot use the addresses stored in the index to retrieve FSes from the CAS.
