### ISSUE TITLE
Improve performance of Candidate Selection Step

### ISSUE THREAD

**Issue by rcffc** [inception-project/inception#87]
- [x]  The query strings should be in lowercase
- [x]  Compare the typed string with the mention and query the mention, if the typed string is a prefix of the mention. Otherwise query the typed string. Examples:
Mention: Jordan | Typed String: **Michael Jordan**
Mention: **Jordan** | Typed String: Jor
Mention: Jordan | Typed String: **Airness**
Mention: Jordan | Typed String: **Jordan Rudess**

The KendoAutoCompleteBox has the behavior of triggering the listing instances multiple times, sometimes even twice for the same typed string. Therefore it would be good to set up caches for the candidate selection and the candidate ranking. The performance time of the candidate ranking is almost exclusively dependent on the retrieval of the semantic signature.

- [x]  Cache the candidate set retrieved by each query string
- [ ]  Cache the semantic signature for each wikidata string

Retrieving the candidates from the Remote server with a limit of 2500 takes 1.5s -1.8s, whereas retrieving from a cache takes less than 2ms. Candidate ranking time with 25 candidates drops from <4s to <30ms.

**Comment by reckart** [comment]
No Guava please. Please stick to Apache Commons libraries.

**Comment by rcffc** [comment]
> No Guava please.
May I ask why?

**Comment by reckart** [comment]
Because Guava tends not to be backwards compatible with itself. I have often run into trouble because different libraries draw in incompatible versions of Guava. Apache Commons has a strong history of being reliably backwards compatible.

**Comment by rcffc** [comment]
Okay, how big shall the cache be?

**Comment by rcffc** [comment]
My compiler does not recognize Collections.synchronizedList() although the compiler level is 1.8. Can you check if it works for you?

**Comment by reckart** [comment]
Create a configuration bean:

```
@Component
@ConfigurationProperties("inception.entity-linking")
public class EntityLinkingProperties
{
    private int cacheSize = 1000;

   // getters and setters
}
```

After that, you can configure property via the settings.properties file:

```
inception.entity-linking.cacheSize = 10000
```

**Comment by reckart** [comment]
I have no idea what a sensible default cache size would be.

> My compiler does not recognize Collections.synchronizedList() although the compiler level is 1.8. Can you check if it works for you?

Maybe a problem with generic types? The method in general exists for me.

That said: Instead of a synchronized list, would a CopyOnWriteArrayList be suitable? What do you need the synchronized list for?

Normally, I would expect a cache to use something like https://commons.apache.org/proper/commons-collections/apidocs/org/apache/commons/collections4/map/LRUMap.html

**Comment by reckart** [comment]
Might also consider checking out https://github.com/ben-manes/caffeine

**Comment by Rentier** [comment]
Please measure performance when you implement optimizations.

**Comment by rcffc** [comment]
Retrieving the candidates from the Remote server with a limit of 2500 takes  1.5s -1.8s, whereas retrieving from a cache takes less than 2ms.
