### ISSUE TITLE
Feedback notification immediately disappearing

### ISSUE THREAD

**Issue by wpmp** [inception-project/inception#875]
**Describe the bug**
When creating a new span annotation it can happen that the feedback notification immediately disappears after showing up.
This can happen in both, brat and PDF editor.
It seems to only happen when a new annotation is created in some other sentence than the annotation is that was created before.
If annotation is in the same sentence the bug won't occur.
Also double clicking a word for annotation it seems to happen more frequently than selecting the word manually.

**To Reproduce**
1. Go to the brat or PDF editor and select a document
2. Select a word for annotation
3. Feedback notification will appear and sometimes immediately disappear
4. Select another word for annotation in another sentence (double clicking)
5. Feedback notification will appear and immediately disappear

**Expected behavior**
The feedback notification should disappear after a short amount of time, not immediately.

**Please complete the following information:**
 - Version and build ID: 0.8.0-SNAPSHOT (2019-01-17 09:49:33, build 51ba243f6960dcc08f0d17625651afab082f2ee0)
 - OS: Linux (Arch Linux)
 - Browser: Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by wpmp** [comment]
@reckart should I take care of this issue or will someone else fix this?
As mentioned it seems this also affects the brat editor.

**Comment by reckart** [comment]
Have not noticed this for along time.
