### ISSUE TITLE
First rank per candidate frequency, then compute time-intensive features like semantic signature

### ISSUE THREAD

**Issue by rcffc** [inception-project/inception#88]
We seek to come up with a general entity linking approach for smaller topic-specific KBs, but at the moment we are using Wikidata as reference KB. A disadvantage of general-knowledge KBs is that the entities are heterogenous and have more ambiguity.
For entity linking on large KBs like Wikidata or DBPedia it is beneficial to sort the entities for a popularity prior due to the large amount of candidates retrieved, and then compute time-intensive features like the semantic signature. 

For popularity prior we have two options:
1. Their inlink count of their wikipedia articles first. But this frequency file is specific to wikidata.
2. The ID of an entity, where smaller IDs are more popular. It is probable that many large KBs make it possible to query this property, but I tend to like the first option more.

I am aware that this is a tradeoff between recall for new/infrequent entities and performance time. At this point, I am not sure what is more important to a user. We might know after usability, if there are complaints. In the future, one could implement a slider in ConceptFeatureEditor to adjust the candidate limit.

For custom KBs we have to speculate that the number of retrieved candidates won't be that high (because we cannot rely on neither of the two above mentioned popularity priors),  otherwise the computation of the semantic signature will take too long for > 100 candidates.

Right now (22.April.2018) in the master branch the ranking is solely based on the edit distance of the candidate entity vs the mention and its context.

**Comment by reckart** [comment]
In principle, there'd be an additional popularity prior: number of mentions in the current project that are linked to a given concept. IMHO that would be the best option for custom KBs.

Also, it would be possible to let the user place a file containing entityId/score tuples into the inception home directory to avoid having to ship large and resource-specific priors and to make the whole thing more customizable.

**Comment by rcffc** [comment]
> Also, it would be possible to let the user place a file containing entityId/score tuples into the inception home directory to avoid having to ship large and resource-specific priors and to make the whole thing more customizable.

Adressed in https://github.com/inception-project/inception/pull/85/commits/5d391319647ed3cd8b463405051c705d79acad6a

**Comment by rcffc** [comment]
> In principle, there'd be an additional popularity prior: number of mentions in the current project that are linked to a given concept. IMHO that would be the best option for custom KBs.

I created a separate issue for that: https://github.com/inception-project/inception/issues/96
