### ISSUE TITLE
Monitoring hangs when there are  a large number annotators

### ISSUE THREAD

**Issue by qiuwei** [inception-project/inception#897]
**Describe the bug**
I have created 40 annotators for a project. When clicking on monitor or agreement, INCEpTION freezes for a while then the browser complains that there is no response.
I checked the log but didn't find any errors. At the same time, one cpu core has full usage. 

**To Reproduce**
1. create a project 
2. create 40 annotators for the project
3. click on monitoring or agreement

**Expected behavior**
Monitoring should show the progress of the annotation.
Or at least give a warning that there might be too many annotators. 

**Please complete the following information:**
 - Version and build ID: 0.7.0 (2019-01-13 23:29:04, build 2a706c9e60e52474b5d60975fd4d13e0cbb64178)
 - OS: linux
 - Browser:  chrome, safari

**Additional context**

**Comment by qiuwei** [comment]
I reduced the number of annotators to 30, now it does respond but takes a very long time (~ 10 minutes).

**Comment by qiuwei** [comment]
Agreement has similar behavior.

**Comment by reckart** [comment]
At least for monitoring, I believe the new monitoring page should address this: #1990

**Comment by reckart** [comment]
There have meanwhile been many performance improvements. There are is certainly still much room for improvement in different areas. If anybody identifies a problematic situation, please open a more specific bug.
