### ISSUE TITLE
Configurable annotation work assignment

### ISSUE THREAD

**Issue by qiuwei** [inception-project/inception#900]
**Is your feature request related to a problem? Please describe.**
We have multiple annotators and a rather large number of files to be annotated（This is quite common in the crowdsourcing scenario）. Of course, it's not very affordable to ask the annotators to annotate each document. We end up using a spreadsheet to track the assignment.
 
**Describe the solution you'd like**
To my knowledge,   in the current version of INCEpTION there is no concept about work assignment.
I could set the state to IGNORE in annotation_document table as a workaround, but that feels cumbersome.   

I would propose two assignment models for this usecase:
1. manual assignment: the project manager could manually(selecting one by one, or using filters like regex based on the filenames, or just random sampling a portion), then assign the documents to a certain annotator.
2. fully automatic assignment: the project manager just define some rules, e.g., how many times one document should be annotated, how many documents should be annotated only once. Then the documents will be dispatched to the annotators automatically, or even dynamically.

**Describe alternatives you've considered**

**Additional context**

**Comment by reckart** [comment]
Believe it or not, we actually have this on our todo list - just didn't get around to create an issue for it yet :)

**Comment by reckart** [comment]
There is a dynamic workload assignment now in version 0.18.0 which is essentially queue-based and allows the manager to configure how many annotators should work on any document. Also, the monitoring page (for static workload management) has been improved to better support bulk actions - this will be included in 0.19.0.
