### ISSUE TITLE
Annotation Editor action commands

### ISSUE THREAD

**Issue by wpmp** [inception-project/inception#904]
**Describe the refactoring action**
Currently the action commands (for example spanOpenDialog) used in the brat editor are located in the de/tudarmstadt/ukp/clarin/webanno/brat/message package in the response classes within brat module.
Those commands will be moved to a more appropriate location in webanno/webanno#1210 and INCEpTION must adjust to this changes.

**Expected benefit**
 Better decoupling, helpful for implementing other editors beside brat like PDF editor.

**Comment by reckart** [comment]
The refactoring of actions as part of the JS API has taken care of this.
