### ISSUE TITLE
Changing URL of remote KB requires server restart

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#916]
**Describe the bug**
When the URL of a remote KB is changed, this change is not applied immediately. Restarting the server helps.

**To Reproduce**
1. Create a remote KB connecting to some SPARQL endpoint
2. Open the KB on the KB page
3. Go back to the project settings and change the URL to point to another SPARQL endpoint
4. Open the KB on the KB page
5. Still see the same data...

**Expected behavior**
Changes to the SPARQL URL should either be prevented or take effect immediately.

**Please complete the following information:**
 - Version and build ID: a5e973ba58aca2877ecd6fb62c8eaa72b239e7df

**Comment by jcklie** [comment]
Apparently, rdf4j saves the URL also by itself. This is not changed when we update just the database.

**Comment by david-waterworth** [comment]
Possibly related but when using a remote KB, there doesn't seem to be any way of refreshing the KB in inception. For example I delete and recreate my DB on Fuseki and reload a changed TTF file. The inception server seems to cache the old KB.

**Comment by reckart** [comment]
The URL change bug is in principle separate from the caching - but when we get to address it, indeed we also need to flush the caches.
