### ISSUE TITLE
Label sub-properties not working for instances

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#920]
**Describe the bug**
The instances in the GND SPARQL endpoint do not get proper labels. The "Bevorzugter Name der Körperschaft" (http://d-nb.info/standards/elementset/gnd#preferredNameForTheCorporateBody) inherits via http://d-nb.info/standards/elementset/gnd#preferredName from rdfs:label but is not recognized as a label property for instances.

**To Reproduce**
1. Configure a KB as indicated on the first screenshot
2. Navigate to a concept as indicated on the second screenshot and have a look at the instances

**Expected behavior**
Any property that is a sub-property of a label property should also be considered to be a label property.

**Screenshots**
![2019-02-05_12-24-03](https://user-images.githubusercontent.com/1410238/52270322-f1082780-2940-11e9-8a6b-d83e84d4e8ce.png)

![2019-02-05_12-21-49](https://user-images.githubusercontent.com/1410238/52270235-a2f32400-2940-11e9-9561-04e5b8fd9329.png)

**Please complete the following information:**
 - Version and build ID: 1e992e5a1f2e0657159cc6a7c1c99489c308c850

**Comment by MdeBoer95** [comment]
@reckart it's because the subpropertyIRI is configured as ```http://www.w3.org/2000/01/rdf-schema#comment```
If you create it from the profile it should be set to ```http://www.w3.org/2000/01/rdf-schema#subPropertyOf```
It worked for me (on master and 0.7.x)

**Comment by reckart** [comment]
Ok, my fault then. Thanks!
