### ISSUE TITLE
Instance which has statements is shown in Properties in KB(only for Reification KB)

### ISSUE THREAD

**Issue by matchlesswei** [inception-project/inception#95]
The Instance which has statements is shown in Properties in KB(only happens in Reification KB).
It looks like query conflict. 

```
List<KBHandle> resultList = read(kb, (conn) -> {
            String QUERY = String.join("\n"
                         , "SELECT DISTINCT ?s ?l WHERE {"
                         , "  ?s ?pTYPE ?oPROPERTY ."
                         , "  OPTIONAL {"
                         , "    ?s ?pLABEL ?l ."
                         , "    FILTER(LANG(?l) = \"\" || LANGMATCHES(LANG(?l), \"en\"))"
                         , "  }"
                         , "}"
                         , "LIMIT 10000");
            TupleQuery tupleQuery = conn.prepareTupleQuery(QueryLanguage.SPARQL, QUERY);
            tupleQuery.setBinding("pTYPE", kb.getTypeIri());
            tupleQuery.setBinding("oPROPERTY", aType);
            tupleQuery.setBinding("pLABEL", RDFS.LABEL);
            tupleQuery.setIncludeInferred(aIncludeInferred);

            return evaluateListQuery(tupleQuery, aAll);
```
also returns Instance in a KB with Reification, if aType = RDF.PROPERTY.

**Comment by reckart** [comment]
What is a query conflict?

**Comment by Rentier** [comment]
If you exclude inferred statements (change the 3rd argument in `listProperties` to false), then it works.

**Comment by matchlesswei** [comment]
What does actually inferred statement mean?

**Comment by reckart** [comment]
An ontology/kb can include "rules" which generate statements that are actually not in the KB.

E.g. if you have the statements "B subclass-of A" and "C subclass-of B", then you can **infer** the statement "C subclass-of A".

**Comment by Rentier** [comment]
It is on per default for properties. I want to rewrite these functions with booleans anyway, because it is really difficult to read whether a boolean means inferred or implicit. I wonder why the KB infers Obama is a property.
