### ISSUE TITLE
Remote access failed

### ISSUE THREAD

**Issue by AleksZhang** [inception-project/inception#959]
I can't see a possibility to set up remote access in Inception v 0.7.2.
Could you please tell if there is any possibility to get data from Inception via remote access?

**Comment by reckart** [comment]
See: https://inception-project.github.io//releases/0.7.2/docs/admin-guide.html#sect_remote_api

**Comment by AleksZhang** [comment]
Thanks a lot!
But after, there's another problem:
while trying to export curated document with my custom layers, I get just the initial conllu document, without any additions.
My call looks like 
/api/aero/v1/projects/5/documents/546/curation
I'm trying to implement "format" parameter of [?format={format}], but it doesn't help.
Thanks in advance!

**Comment by reckart** [comment]
Try setting "ctsv3" as the format.

**Comment by AleksZhang** [comment]
It worked, thanks!
The main problem was in [] around the format description.

When trying to reach Inception data via Aero API, you don't need square brackets around the format description, like it's in userguide for AERO.
![image](https://user-images.githubusercontent.com/17126610/53161856-d50cb300-35db-11e9-9496-df2be9ec8eef.png)

The right link will be /api/aero/v1/projects/{projectId}/documents/{documentID}/curation?format={format}

**Comment by reckart** [comment]
The brackets are meant to indicate that the parameter is optional. Good it works for you now!
