### ISSUE TITLE
Random score option in external search

### ISSUE THREAD

**Issue by shinyichen** [inception-project/inception#968]
**The Problem**
The current external search (ElasticSeach) returns results in order of the best match. We would like to have the option to use the consistent random ordering when searching.

**Solution**
Have the random order option when configuring a new document repository. Use the [`random_score`](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html#function-random) in ElasticSearch query. 

**Alternatives**
Have the random order checkbox in the search form.

**Comment by reckart** [comment]
With the fixed random seed currently used, all users will get the same results for the same query. If you wanted to have different users get different results (but still consistently across sessions/searches), it could be considered to use a hash of the user ID as the seed. I don't know what your specific motivation is for randomization.
