### ISSUE TITLE
Search sidebar does not find last token in a document

### ISSUE THREAD

**Issue by MdeBoer95** [inception-project/inception#975]
**Describe the bug**
When searching for the last token of a document in the search-sidebar no results are shown.

**To Reproduce**
1. Go to Annotation Page and open a document
2. Open the search sidebar and search for the last token of the document
(If the document doesn't end with a "." it's easier to see)
4. See that the token is not found

**Expected behavior**
The search should be able to find all tokens in the document including the last one.

**Screenshots**
![auswahl_007](https://user-images.githubusercontent.com/37872452/53419619-7d56b900-39da-11e9-8462-3165865902e9.png)

**Please complete the following information:**
 - Version and build ID: [ Technische Universität Darmstadt -- Computer Science Department -- INCEpTION -- 0.8.0-SNAPSHOT (, build )
Warnings
]
 - OS: [Linux]
 - Browser: [chrome]

**Additional context**

**Comment by reckart** [comment]
Yep, I can confirm this. Searching for `"."` in a document yields all kinds of punctuation, but not the last full stop in the document.
