### ISSUE TITLE
KB Searchfield sometimes shows odd results and fails to render InfoPanel

### ISSUE THREAD

**Issue by MdeBoer95** [inception-project/inception#979]
**Describe the bug**
The search field on the KB Page sometimes shows results that don't really match the actual search-string. (See screenshot)
When clicking on such a result the KBPage doesn't show the result in corresponding InfoPanel.

**To Reproduce**
1. Go to KBPage after adding ```Wine KnowledgeBase``` to the project
2. See screenshot...
3. Click on the result
4. See that nothing happens

**Expected behavior**
The results should always match the searched string and be shown in the InfoPanel when clicked on.

**Screenshots**
![auswahl_008](https://user-images.githubusercontent.com/37872452/53438327-f87e9600-39ff-11e9-84a5-1916df7ff536.png)

**Please complete the following information:**
 - Version and build ID: [see bottom of the browser screen]
 - OS: [e.g. Windows, Linux, OS X]
 - Browser: [e.g. chrome, safari]

**Additional context**

**Comment by reckart** [comment]
I cannot reproduce this anymore with the current `0.8.x` branch. I guess one of the recent fixes also fixed this one.

Tested using: 0cb82e51ef186e5b166c803a43f10e834a33f21a
