### ISSUE TITLE
Changing Annotation Layer on the annotation page doesn't change the editor 

### ISSUE THREAD

**Issue by MdeBoer95** [inception-project/inception#992]
**Describe the bug**
When trying to select a new layer for an existing annotation, the editor doesn't change and it is not possible to create a new annotation for the selected layer.

**To Reproduce**
1. Go to annotation page
2. Select an existing annotation and try to change the type
3. See that editor doesn't change

**Expected behavior**
Editor should change according to selected annotation layer

**Screenshots**
![peek 2019-02-27 20-01](https://user-images.githubusercontent.com/37872452/53515575-963e9780-3aca-11e9-8436-5e90f2f22799.gif)

**Please complete the following information:**
 - Version and build ID: [see bottom of the browser screen]
 - OS: [e.g. Windows, Linux, OS X]
 - Browser: [e.g. chrome, safari]

**Additional context**

**Comment by reckart** [comment]
What you are observing is intended behavior: https://github.com/inception-project/inception/issues/928
